### ISSUE TITLE
Websocket response .close() can hang indefinitely

### ISSUE THREAD

**Issue by mpaolini** [aio-libs/aiohttp#1002]
## Long story short

By looking at [this loop in the websockertesponse .close() code](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web_ws.py#L190) it looks like a malicious client can hang the `.close()` method forever by sending regular messages every 10 seconds.
## Expected behaviour

WebSocketResponse `.close()` should timeout by default after some time.
## Actual behaviour

WebSocketResponse `.close()` can wait indefinitely for a close opcode, provided some other data arrives every 10 seconds.
## Steps to reproduce

None yet
## Your environment

linux/python35

**Comment by asvetlov** [comment]
Good catch! I believe client code has the same loop.

It can be solved by either calculating total elapsed time for closing call or counting amount of loops.

@mpaolini are you interesting in providing a patch?

**Comment by mpaolini** [comment]
@asvetlov yep, I can write one maybe later tonight

**Comment by mpaolini** [comment]
won't have time in the near future (next month or so) for this

**Comment by asvetlov** [comment]
Got it

**Comment by asvetlov** [comment]
Fixed by #1084
