### ISSUE TITLE
Next aiohttp release will be 1.0

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1007]
## Problem

We have a long enough story now.

From one hand aiohttp is widely used in production and proved to be mature enough.

From other hand it still has bugs and feature requests.

I suspect we will not get _final and frozen_ state in near future, the list of fixes and improvements is infinite.

I myself not even sure when nested apps, HTTP/2 and faster HTTP parser will be supported by the library.
## Resolution

The next aiohttp release will be `1.0`. 
Period.

**Comment by ipfans** [comment]
Will aiohttp 1.0 invoke other speedup enhanced? like move some implementations into cython.

**Comment by asvetlov** [comment]
Not now.
Maybe in future.
Volunteers are welcome.
