### ISSUE TITLE
Where smtp?

### ISSUE THREAD

**Issue by vir-mir** [aio-libs/aiohttp#1008]
## Long story short

Use this framework, but the problem with the mail! no normal library!

@asvetlov , will be to implement, I can push my implementation, but it is curve.
https://github.com/vir-mir/aiosmtp Here much wrong. There are alternatives?

**Comment by ludovic-gasc** [comment]
You should start this discussion on aio-libs and/or tulip mailing lists.

**Comment by asvetlov** [comment]
smtp support is out of scope of the library.

**Comment by asvetlov** [comment]
What I can recommend to use _right now_ is execution regular smtp library in thread pool by `loop.run_in_executor` calls.
