### ISSUE TITLE
POST with application/json headers

### ISSUE THREAD

**Issue by argaen** [aio-libs/aiohttp#1011]
## Long story short

According to [Request.post](http://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.Request.post), the data is only retrieved if the the given headers are '', application/x-www-form-urlencoded or multipart/form-data. What about if data in json format needs to be sent? Unless I'm missing something I can't seem to make it work, it's always returning empty Multidict.
## Expected behaviour

Return dict with data sent in the body
## Actual behaviour

Returns and empty Multidict
## Steps to reproduce

define a POST route and call `self.request.post()` within the view when sending data with "Content-Type: application/json".

**Comment by asvetlov** [comment]
Call `await response.json()` for getting JSON object.

See also `.read()`, `.text()` and `.content`.

**Comment by argaen** [comment]
Ah, I think you meant `self.request.json()`. This is working, thanks! :)
