### ISSUE TITLE
Add reasonable timeout to test suite functions

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1012]
Right now if tests hangs -- they are hangs forever.

It would be nice to have timeout for a test execution.

Honestly I don't care too much about `unittest` based approach but want to have it for pytest based solutions.

Timeout should be small enough (in aiohttp typical test are executed much faster than a second).

And it should be configurable at least by ini file.

**Comment by esaezgil** [comment]
Would it be acceptable to make use of a pytest plugin? In particular pytest-timeout [https://pypi.python.org/pypi/pytest-timeout] Of course that would add a new requirement. 

Additionally the minimum configurable timeout using this plugin is 1sec at the moment but there is already a PR for setting fractional seconds in their repo [https://bitbucket.org/pytest-dev/pytest-timeout/pull-requests/6/allow-fractional-second-timeouts/diff]

**Comment by asvetlov** [comment]
Thanks for suggestion.
I've tried to use the plugin.
Looks like it works.

**Comment by asvetlov** [comment]
Fixed by 9b20b37
Thanks, @esaezgil
