### ISSUE TITLE
Refactor websocket message type

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1019]
1. `msg.tp` should be `msg.type`. Keep `.tp` alias
2. `.data` and `.extra` are not self-explained names. Let's keep it for backward compatibility but introduce new fields.
   2.1. `.result` in case of normal data frame
   2.2. `.exception` in case of error
   2.3. Special attribute `.closed` for closing message

**Comment by ganadist** [comment]
It seems no one look on it.
It is mine. :P

**Comment by asvetlov** [comment]
Fixed by #1078
