### ISSUE TITLE
Implement StreamResponse.task attribute

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1027]
Access to the attr should be `None` if response wasn't prepared or was closed.

See also #922 discussion etc.

**Comment by mpaolini** [comment]
watch out for circular references

**Comment by asvetlov** [comment]
`ServerHttpProtocol` already has `._request_handler` attribute, we need to borrow it.

**Comment by asvetlov** [comment]
Fixed by #1410
