### ISSUE TITLE
.url() has different interface in different resources

### ISSUE THREAD

**Issue by berislavlopac** [aio-libs/aiohttp#1030]
I basically wrote a shortcut as requested in #895, but ran into the issue that `.url()` method has different signatures on various `Resource` subclasses. Specifically:

``` python
class AbstractResource(Sized, Iterable):
    @abc.abstractmethod  # pragma: no branch
    def url(self, **kwargs):
        pass

class ResourceAdapter(AbstractResource):
    def url(self, **kwargs):
        return self._route.url(**kwargs)

# BUT:

class PlainResource(Resource):
    def url(self, *, query=None):
        return self._append_query(self._path, query)

class DynamicResource(Resource):
    def url(self, *, parts, query=None):
        url = self._formatter.format_map(parts)
        return self._append_query(url, query)
```

So I would like to look into it and get the `.url()` signatures in line, and also include my shortcut method above. If anyone can think of a reason against it please let me know!

**Comment by asvetlov** [comment]
I don't follow your question.
`url(*, parts, query=None)` is subset of `url(**kwargs)`, isn't it?

Other question is that without URL class `url(request, 'name', parts={'name': 'John', 'age': '20}, query='?filter=age')` still looks ugly.

**Comment by berislavlopac** [comment]
It is not the subset: the bare `*` is used when you want to specify that your method accepts no positional arguments and you want to define only keyword ones. For example:

``` python
def foo(*, a=1):
    print(a)
```

will throw an error if called as:

``` python
foo(2)
```

But not if called as

``` python
foo(a=2)
```

Using both `*` and positional arguments (like `parts` there) is incorrect, because that essentially ignores the `*`.

Another reason why it is not a subset is that if you don't explicitly define `**kwargs` only the ones explicitly defined will be allowed.

So, both of the latter examples break the `.url()` interface, and I believe that can easily be worked around; for example the `DynamicResource` case above can easily be defined as:

``` python
class DynamicResource(Resource):
    def url(self, query=None, **kwargs):
        url = self._formatter.format_map(kwargs)
        return self._append_query(url, query)
```

**Comment by asvetlov** [comment]
> Using both \* and positional arguments (like parts there) is incorrect, because that essentially ignores the *.

It's totally correct. This is called _keyword-only argument without default value_.

Let's return to the discussion after you'll finish reading of https://www.python.org/dev/peps/pep-3102/

**Comment by berislavlopac** [comment]
I've read the PEP some time ago, and I stand corrected about this being incorrect.

But the rest of my points still stand. First, `def foo(*, a, b=c)` is not a subset of `def foo(**kwargs)` as the latter will accept _any_ keyword arguments, while the former will accept only `a` and `b` and nothing else. Second, it will throw an error if `a` is not provided, while the second example will accept being called without any arguments as well.

**Comment by asvetlov** [comment]
`**kwargs` doesn't mean _accept any keyword argument_, on `kwargs` processing users may (and many libraries do)  raise exception like:

```
if 'arg' not in kwargs:
    raise ValueError('parameter arg is required')
```

It doesn't much differ from `def f(*, arg)`.

**Comment by berislavlopac** [comment]
This is absolutely true; but this will still limit your method to accepting only `arg` and nothing else, unlike `**kwargs`. Basically what you want is `def f(*, arg, **kwargs)` to have it both ways.

**Comment by asvetlov** [comment]
But `def url(self, query=None, **kwargs)` is even worse, it changes function signature more dramatically.

Sorry, I'll not accept the change.

**Comment by asvetlov** [comment]
Making keyword parameter mandatory is more consistent than adding arbitrary position parameter.

**Comment by berislavlopac** [comment]
`DynamicResource` in particular breaks the expected behaviour. The documentation states:

```
url(**kwargs)[source]

    Construct an URL for route with additional params.

    kwargs depends on a list accepted by inherited resource class parameters.
```

But `DynamicResource.url` requires the argument `parts`, which acts the same way as `kwargs` does in the documentation. I'm just trying to figure out what is the expected behaviour supposed to be here.

**Comment by berislavlopac** [comment]
> Making keyword parameter mandatory is more consistent than adding arbitrary position parameter.

I don't think I anywhere suggested adding an "arbitrary position parameter"?

**Comment by asvetlov** [comment]
Let's close this endless discussion.

**Comment by berislavlopac** [comment]
Sorry, but this is not acceptable. You have not answered my questions and you have not provided an explanation for the inconsistent behaviour of `.url()`.

**Comment by asvetlov** [comment]
As the aiohttp library maintainer I have a strong feeling that keeping existing API is good idea.
I've tried to explain it.
Sorry, maybe my English is bad or I'm not good in describing complex non-obvious matters.

Feel free to fork the project if you need it -- it's Open Source.
Period.

**Comment by berislavlopac** [comment]
OK, I've figured it out, my initial understanding of how `.url()` works was incorrect.

**Comment by berislavlopac** [comment]
Thanks.
