### ISSUE TITLE
regression - 405: Method Not Allowed - after 0.21.6

### ISSUE THREAD

**Issue by marcelotduarte** [aio-libs/aiohttp#1035]
## Long story short

Using 0.21.6, my app is fine, but upgrading to 0.22.4 fail. I'm noted that after 0.22.0a0 it is failing.
## Expected behaviour

old behaviour
## Actual behaviour

Here is the reponse header, I'm geting with firebug:
HTTP/1.1 405 Method Not Allowed
Content-Type: text/plain; charset=utf-8
Content-Length: 23
Allow: Get
Date: Tue, 02 Aug 2016 03:17:18 GMT
Server: Python/3.5 aiohttp/0.22.0a0
## Steps to reproduce

In my app one router is:
app.router.add_route('GET', '/', raiz)

If I change to:
app.router.add_route('*', '/', raiz)

It will pass. But that is not what I expect.

I'm suspecting that the cause is #838.
## Your environment

Python 3.5.2 (32 and 64 bit)
Windows 10 64bit
Chrome52 and Firefox 47.0.1 (lastest releases).

**Comment by argaen** [comment]
Hi! Something similar happened to me yesterday as well. I think it's related with the `multidict` version that is installed. Can you try to do a `pip install --upgrade multidict`, it fixed the error for me.

**Comment by marcelotduarte** [comment]
Hi! You're right. It's mutidict. But upgrade it doesn't solve the problem. I had mutidict 2.0.0 and uninstalling multidict and upgrading aiohttp, install the correct versions, aiohttp 2.22.4 and multidict 1.2.2.
Thanks.
I will close the issue because I have seen that support multdict 2 is being implemented.

**Comment by asvetlov** [comment]
aiohttp 0.22.6 should fix the issue by pinning multidict version
