### ISSUE TITLE
User Sessions example out of date within web.rst?

### ISSUE THREAD

**Issue by mentaal** [aio-libs/aiohttp#1042]
## Long story short

When running "User Sessions" Example I get an exception.
Perhaps Example is out of date with regard to the aiohttp-session docs which seems to want a 32 byte key.
## Expected behaviour

Running Example

## Actual behaviour

`"Fernet key must be 32 url-safe base64-encoded bytes."
ValueError: Fernet key must be 32 url-safe base64-encoded bytes.`
## Steps to reproduce

Execute "User Sessions" example within web.rst
## Your environment

Windows x64
Anaconda supplied aiohttp

`pip show aiohttp
Metadata-Version: 2.0
Name: aiohttp
Version: 0.22.5
Summary: http client/server for asyncio
Home-page: https://github.com/KeepSafe/aiohttp/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
Installer: pip
License: Apache 2
`

Python 3.5.2
"Stable" example from docs

**Comment by asvetlov** [comment]
Fixed on master.
For actual example you may take a look on https://github.com/aio-libs/aiohttp_session#usage

Thanks for report.
