### ISSUE TITLE
Support per-view custom methods

### ISSUE THREAD

**Issue by tumb1er** [aio-libs/aiohttp#1045]
## Long story short

I'm trying to implement DAV protocol over aiohttp, and for custom HTTP-methods like MKCOL, PROPFIND I'm receiving 405 Method Not Allowed.
## Expected behaviour

web.View is able to define extra supported methods, not listed in web.hdrs.METH_ALL
## Actual behaviour

``` python
@asyncio.coroutine
    def __iter__(self):
        if self.request.method not in hdrs.METH_ALL:
            self._raise_allowed_methods()
```
## Steps to reproduce

Implement ANY method not listed in `hdrs.METH_ALL`
## Your environment

python3.5 aiohttp 0.22.5

**Comment by tumb1er** [comment]
I think, that's enough:

``` python
class View:
    METHODS = hdrs.METH_ALL
    @asyncio.coroutine
    def __iter__(self):
        if self.request.method not in self.METHODS:
            self._raise_allowed_methods()
        ...
```

**Comment by asvetlov** [comment]
It's fixed by #1037 isn't it?

**Comment by tumb1er** [comment]
That's it. Is #1037 released?

**Comment by asvetlov** [comment]
Not yet.
Please wait for aiohttp 1.0.
I'm planing to release in a couple weeks.
