### ISSUE TITLE
Cannot share `TCPConnector` between `ClientSession` objects

### ISSUE THREAD

**Issue by AndreLouisCaron** [aio-libs/aiohttp#1048]
I'm using `aiohttp` as the basis for a Python 3.5-based load testing framework.  For various reasons (I can get into more detail if you need them), I'd like to limit the number of outbound open connections.

However, I'd like to have a distinct `ClientSession` object for each "client" in order for them to each have their own cookie jar, among other things.

I tried doing this by sharing a `TCPConnector(limit=N)` instance as the `connector` parameter for all my `ClientSession` instances.  There's nothing in the docs against this, so I thought I would try.

It works fine until one of the `ClientSession` objects is closed, at which point I get exceptions of this type:

```
File "...\lib\site-packages\aiohttp\client.py", line 537, in __aenter__
    self._resp = yield from self._coro
  File "...\lib\site-packages\aiohttp\client.py", line 151, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed 
```

It seems the `ClientSession` is closing the connector when it cleans up.  I'm guessing this is intended because it's the only clear cleanup point for the TCP connector.

I guess I could wrap the `TCPConnector` in my own context manager object that ignores the `.close()` call, but do you think it would be doable to change the API to support my use case?  If not, do you have another approach to recommend?

Thanks!

**Comment by asvetlov** [comment]
Yes, session was designed to exclusively own a connector.
If doc doesn't explicitly state this -- documentation patch is welcome.

The design decision was perfectly reasonable at time of `ClientSession` creation. 
But now, after deletion of deprecated `TCPConnector(shared_cookies=True)` parameter a connector has no session information but connections only.
Thus now is possible to make a fix for sharing connector object between multiple sessions.

Personally I don't have a strong motivation for this patch but can consider a Pull Request.

**Comment by asvetlov** [comment]
After rethinking I've decided to close the issue.
The requested functionality is actually rare and can be implemented on top of aiohttp without the core source code changing.

Adding custom reference counting for connectors is not exciting addition.
