### ISSUE TITLE
Responses-like lib/example for mocking requests

### ISSUE THREAD

**Issue by hyzhak** [aio-libs/aiohttp#1051]
Is there any library or example of mocking requests to random url, something similar like https://github.com/getsentry/responses for https://github.com/kennethreitz/requests/.

For example I have API that trigger some facebook API:

``` python
async def send_message(sender, text):
    async with session.post(
            'https://graph.facebook.com/v2.6/me/messages/',
            params={
                'access_token': os.environ['FB_ACCESS_TOKEN']
            },
            data={
                'recipient': {'id': sender},
                'message': {'text': text}
            }) as resp:
        return await resp.json()
```

and I'd like to have some simple unit test for it, like:

``` python
@responses.activate
async def test_my_api():
    responses.add(responses.POST, 'https://graph.facebook.com/v2.6/me/messages/',
                  body='{"status": "ok"}', status=200,
                  content_type='application/json')

    resp = send_message(1, 'hi!')

    assert resp.status == 'ok'
```

sadly responses doesn't work with aiohttp

**Comment by argaen** [comment]
Hi Eugene,

I'm using something like [this](https://github.com/KeepSafe/aiohttp/pull/973#issuecomment-235680392) for mocking requests to external services. You can see the code for building the ClientResponse object in the changes. Maybe it's not the best solution but for me it's similar of how I was mocking with the `requests` library. If you need further help of how it works don't hesitate to ask :).

**Comment by asvetlov** [comment]
Superseded by #980

**Comment by garbas** [comment]
https://github.com/pnuckowski/aioresponses

**Comment by marco-c** [comment]
There's also https://github.com/CircleUp/aresponses.

**Comment by asvetlov** [comment]
`aresponses` is better, sure.
