### ISSUE TITLE
Document set_cookie(expires=)

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#1056]
In HTTP version 1.1, `expires` was deprecated and replaced with the easier-to-use `max-age`, but Internet Explorer (ie6, ie7, and ie8) does not support `max-age`.

So, either:
- document that, or
- calculate one value from other.

**Comment by asvetlov** [comment]
The practical advice right now to use both properties AFAIK.

> calculate one value from other

How should it work?
