### ISSUE TITLE
How to get a global app object?

### ISSUE THREAD

**Issue by 631068264** [aio-libs/aiohttp#1057]
I want to know that a global **app** object.

```
app = web.Application()
app.router.add_route('GET', '/', hello)
```

 Because this object has some method want to use in other **.py** file,I don`t like to use it as a parameter.

I hope I can get it easily like Flask`s  request.

**Comment by asvetlov** [comment]
aiohttp has no global app object: http://aiohttp.readthedocs.io/en/stable/web.html?highlight=global#data-sharing

If you need a global variable -- you are doing something wrong.

**Comment by 631068264** [comment]
Thanks your reply and prompt.Why I need it because I want to do this.

```
class Redirect(Response):
    def __init__(self, route_name, query=None, **kwargs):
        Response.__init__(self)
        self._parts = kwargs
        self._route_name = route_name
        self._query = query

    def conext_update(self, **kwargs):
        self._parts.update(kwargs)
        self._request = self._parts.pop('request')

    def output(self):
        path = self._request.app.router[self._route_name].url(
            parts=self._parts, query=self._query)
        return aiohttp.web.HTTPFound(path)
```

I am sorry that I did not read the document carefully, so I do not know app can get by request.Thank you very much.
