### ISSUE TITLE
“HEAD” response with wrong content-length?

### ISSUE THREAD

**Issue by zjyes** [aio-libs/aiohttp#1058]
when make request with HEAD, but the resource does not support HEAD method, server responses with "HTTP/1.1 405 Method Not Allowed" is ok, but content-length should not be "CONTENT-LENGTH: 23", where 23 stands for  the literal "405 Method Not Allowed".
it should be CONTENT-LENGTH: 0, which means only HEAD is delivered. Or else the client will expect 23 bytes reponse, but server never send that. eg:

D:\prog\comp.lang.python>curl -i -X head -H "'Content-type':'application/x-www-form-urlencoded', 'charset':'utf-8', 'Accept': 'text/plain'" -d 'json_data={"a":"aaa","b":"bbb","data":[{"c":"ccc","d":"ddd","keywords":[{"e": "eee", "f":"fff", "g":"ggg"}]}]}' localhost:8080/
HTTP/1.1 405 Method Not Allowed
CONTENT-TYPE: text/plain; charset=utf-8
CONTENT-LENGTH: 23
ALLOW: GET
DATE: Mon, 08 Aug 2016 04:40:49 GMT
SERVER: Python/3.5 aiohttp/0.22.4

curl: (18) transfer closed with 23 bytes remaining to read

**Comment by kxepal** [comment]
@yinzuojie you should use `curl -I` instead if `curl -XHEAD`

**Comment by kxepal** [comment]
Also, request methods are case sensitive, so you did wrong HEAD request.

**Comment by zjyes** [comment]
Got it. Thanks!
