### ISSUE TITLE
error install aiohttp

### ISSUE THREAD

**Issue by beryindo** [aio-libs/aiohttp#1059]
some one help me ? why error install aiohttp ?

```
RuntimeError: aiohttp requires Python 3.4.1+

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/aiohttp
Storing debug log for failure in /root/.pip/pip.log
```

```
root@ubuntu:/opt# python -V
Python 3.5.2
```

**Comment by asvetlov** [comment]
Do you really use python3 for installing aiohttp?
Maybe you've executed `pip install aiohttp` but your pip is python2-pip?
In general I highly recommend virtual environments for python development.
