### ISSUE TITLE
aiohttp.test_utils.make_mocked_request should accept regular dict as headers [easy]

### ISSUE THREAD

**Issue by rutsky** [aio-libs/aiohttp#1068]
Currently `aiohttp.helpers.make_mocked_request` doesn't support `headers` value type other than CIMultiDict. If you try to pass regular `dict` as `headers` and try to use such mocked request you will get error similar to:

```
test_aio.py:6: in handler
    assert request.headers.get('token') == 'x'
../../../stuff/aio-libs/aiohttp/aiohttp/helpers.py:442: in __get__
    val = self.wrapped(inst)
../../../stuff/aio-libs/aiohttp/aiohttp/web_reqrep.py:214: in headers
    return CIMultiDictProxy(self._message.headers)

TypeError: CIMultiDictProxy requires CIMultiDict instance, not <class 'dict'>
```

This can be easily fixed by adding [here](https://github.com/KeepSafe/aiohttp/blob/dfe0244e6a7500cff0593e9c3cd0a1043d5525a1/aiohttp/test_utils.py#L608) something like:

```
    if headers:
        hdrs = headers
        if not isinstance(hdrs, CIMultiDict)
           hdrs = CIMultiDict(hdrs)
        raw_hdrs = [
(k.encode('utf-8'), v.encode('utf-8')) for k, v in headers.items()]
```

plus add test for this case.

**Comment by Taekyoon** [comment]
If nobody took it, I'll take it

**Comment by jincreator** [comment]
If nobody is working on it, I'll take it.

**Comment by jincreator** [comment]
Seems someone else is already working on it...

**Comment by asvetlov** [comment]
Fixed by #1073

**Comment by rutsky** [comment]
@argaen, thanks!

**Comment by argaen** [comment]
You're welcome :).
