### ISSUE TITLE
router applies URL template AFTER urldecoding, which is a bug.

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#1070]
http://aiohttp.readthedocs.io/en/stable/web.html#aiohttp-web-variable-handler

So, route like `/users/{username}/operations` WILL FAIL to parse if username contains slashes (`/`).
i.e. URL `http://127.0.0.1/users/hel%2F%2Flo/operations` will fail, although it is correct.

It is not said if regexp applied before or after URLDecoding. In fact, after, which is also bug, as I think.

In most scenarios, urldecode should be called on each parameter separately, and router matching should be done on unescaped urls.

Also, it is not said if `Reverse URL Constructing` will urlescape url properly. If yes, these urls MUST be parsed back by router. even if variables contain slashes.

**Comment by socketpair** [comment]
Same situation in flask:
http://flask.pocoo.org/snippets/76/

**Comment by asvetlov** [comment]
I believe it's fixed by yarl

**Comment by socketpair** [comment]
yarl ? what is it ?

**Comment by asvetlov** [comment]
https://yarl.rtfd.io
