### ISSUE TITLE
Close server-side websocket connection after certain period of inactivity.

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1081]
The only reliable way to make sure that socket is still alive is listening for _ping_ message.

Server should terminate web socket if no incoming event was for _timeout_ period.

By default the period should be `None` for keeping backward compatibility.

**Comment by jincreator** [comment]
If nobody is working on it, I'll take it.

**Comment by fafhrd91** [comment]
We have now `receive_timeot` and `heartbeat`, should be enough
