### ISSUE TITLE
Logging send/receive data at DEBUG level

### ISSUE THREAD

**Issue by pohmelie** [aio-libs/aiohttp#1087]
This issue is result of aio-libs google group [discussion](https://groups.google.com/d/topic/aio-libs/4WOi3b_XNHY/discussion). Since often developer have no server-side code/protocol/api, but trying to reverse client-side by comparing requests/responses, ability to «see what happend» is very important. For insecure connections there is wireshark, but most of services are secure nowadays.
Easiest way is to wrap transport, but I don't really know how this will affect performance.

**Comment by asvetlov** [comment]
I want just state it: logging should be performed in debug mode only. Perhaps it requires `debug` param in `ClientSession` constructor, that's fine.

Do you want to save request/response headers only or the whole bodies?
The last may be tricky: logging the whole content of downloaded file is very expensive, but saving the first 100 bytes maybe is now enough.
Suggestions?

**Comment by pohmelie** [comment]
Don't really know which case is better, but sometimes you need 101 bytes, and you'll be sad if some "bad library developer" will cut you at 100. I think there definetly should be some options/log levels restrictions for logging all bytes.

**Comment by asvetlov** [comment]
@pohmelie the decision is up to you.
I don't want to make a patch personally but rely on you.
It can be `debug_info` parameter with default value `100` but maybe you'll suggest better name.
`debug_info=100` means 100 bytes, `debug_info=0` or `debug_info=None` disables logging.
I really want to have the single param, blowing up leads to explosion.

**Comment by pohmelie** [comment]
@asvetlov 
Is this what you mean?

``` python
if debug_info is not None:
    logging.debug(...)
```

Also, I read requests/urllib3 sources to see what is going on there. And they are just logging method, url, http version, response status code and response size. So, after that I think request/response content should not be logged, since you can log it on your own in user code.
Since this, should we still make condition for logging debug info? In case of excluding content there should be not so much things to log to(just lines before content?).
Regardless of choosen solution I need help to find place(s), where aiohttp actually converts "dictionaries" to bytes and sending data.

**Comment by asvetlov** [comment]
Ok, if we need boolean parameter than just `debug=False` is good name.
The explicit param is required, it allows to speed up execution in production mode a little bit.

Request sending is here: https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client_reqrep.py#L482
Response info is available here: https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client_reqrep.py#L668

Maybe pushing logging into redirection loop https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L182 is cleaner than modifying request/response classes.

Let's cope with regular http requests first and add websocket logging in another PR.

**Comment by pohmelie** [comment]
Maybe better solution is to use [protocol.send_headers](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/protocol.py#L647) and [protocol.HttpResponseParser](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/protocol.py#L224)? Cause this have all headers/cookies in native view. And there is no need to keep «http dicts» in mind.

**Comment by asvetlov** [comment]
Please no.
`protocol` is overridden by implementation details but I want to refactor it very deeply for sake of performance.
Also think about HTTP/2. Perhaps it will require different implementation.
Let's keep the proper abstraction level for request/response logging.

**Comment by txomon** [comment]
Guys, would it be possible to have some kind of logging. I am trying to understand how cookies and sessions get modified in my application and the docs speak about [Logging](http://aiohttp.readthedocs.io/en/stable/logging.html) but setting up client logging is totally useless at the moment.

Anything is better than something. If you are worried about performance go with the module variable way, but please, something!

**Comment by pohmelie** [comment]
@txomon, unfortunately I still have no time for this, sorry. As I realized this should be done very accurate: be in proper level of abstraction and don't decrease performance too much.

**Comment by txomon** [comment]
Just in case, debug level is not used in production, just during
development, therefore the performance shouldn't be that concerning.

Doing it the http.client is by far the most performing solution, although
logging was also quite performing when not logging.

About the abstraction level, the use case of client debugging is usually
used when developing the library, so method, headers and body, and response
status, headers and optionally body are the expected items.

I think I am missing something because design wise it's just copying other
libraries, isn't it?

**Comment by mikenerone** [comment]
Just wanted to toss my vote in here, too. Situations come up for me regularly where some raw request logging would be very helpful.

**Comment by cecton** [comment]
What about receiving file objects for debugging? Like `debug_in` and `debug_out`. If the dev provides a valid file object opened in binary mode, every packet receive will be sent raw to `debug_in` and every packet sent will be sent to the other one.

With that, the implementation of the actual logging is done by the dev.

**Comment by asvetlov** [comment]
Superseded by #2313
