### ISSUE TITLE
ClientSession Crashes with websockets 3.2

### ISSUE THREAD

**Issue by AraHaan** [aio-libs/aiohttp#1095]
## Long story short

So, I updated websockets to 3.2 accidentally with PyCharm thinking aiohttp would be fine but seems it causes a Unclosed client Session Error that immediately disconnects.
## Expected behaviour

For aiohttp to support websockets v3.2
## Actual behaviour

Unclosed Client Session Error.
## Steps to reproduce

Use PyCharm to Download websockets 3.2 or just install websockets with pip and it will download 3.2.
## Your environment

Windows 7 Ultimate x64
All Windows Updates Installed.
Python: 3.5.2 (Embedded & installed)(both x86 and x64 interpreters as well)

**Comment by asvetlov** [comment]
What is `websockets 3.2`?
If you are talking about https://pypi.python.org/pypi/websockets/3.2 -- the library doesn't use aiohttp and in turn aiohttp doesn't rely on websockets.
aiohttp has own websocket implementation.
Please elaborate your issue.
