### ISSUE TITLE
Streaming to FormData

### ISSUE THREAD

**Issue by an5t** [aio-libs/aiohttp#1101]
According to docs, we can pass file-like object as FormData value to stream file without reading them whole into memory. Actually it works when passing file from local disk, but doesn't work if the field value is StreamReader. For example, I want to send file from another response:

```
f = await session.get('http://python.org')
data = FormData()
data.add_field('file',
               f.content,
               filename='index.html')
await session.post('http://httpbin.org/post', data=data)
```

```
TypeError: unknown body part type <class 'aiohttp.streams.FlowControlStreamReader'>
```

I use Python 3.5.2 and aiohttp 0.22.5 on Linux.

**Comment by asvetlov** [comment]
Sorry, the requested functionality is not supported yet.
Would you provide a Pull Request?

**Comment by fafhrd91** [comment]
this is part of #1172
