### ISSUE TITLE
incompatible with multidict >=2.0

### ISSUE THREAD

**Issue by smurfix** [aio-libs/aiohttp#1112]
multidict 2.0 replaced upcase with titlecase, i.e. upstr("GET") is now "Get".

This breaks method name comparison in quite a few places.

**Comment by asvetlov** [comment]
What aiohttp version are you talking about?

**Comment by smurfix** [comment]
Bah. Sorry. Brain fart on my part, I was somehow convinced that the relevant changes happened before 0.22.4 (which is the version packaged in Debian at the moment).

I've submitted a bug to the Debian packager instead.
