### ISSUE TITLE
How do I send requests from a specific source IP address?

### ISSUE THREAD

**Issue by avamsi** [aio-libs/aiohttp#1114]
In the case of hosts with multiple IP addresses, can I make requests from a specific IP address?
Something like [this](https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection)?

**Comment by asvetlov** [comment]
You should pass `local_addr` to [`TCPConnector`](http://aiohttp.readthedocs.io/en/stable/client_reference.html#tcpconnector)
