### ISSUE TITLE
Document non-gunicorn based approaches for deployment

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1120]
1. Just starting server.
2. Pushing multiple server processes behind nginx. Nginx config template should be attached.

**Comment by allan-simon** [comment]
what are the advantages/drawbacks of both approach as I think it's good to know why there's an alternative ? I already made for tornado a deployment like you described , nginx with a upstream configured to round-robin accross different processes handled by supervisor so if that's what you looking for, I can create a PR :)

**Comment by asvetlov** [comment]
You are getting rid of intermediate (gunicorn) but should control/monitor your services by external tool (`supervisord` or similar).

I very appreciate a contribution into this part of doc.
Looks like I cannot find a time for fixing the issue by myself.

**Comment by allan-simon** [comment]
I see I think I need to read a bit more about how gunicorn is working, because I always thought it was only for traditionnal sync framework and that it would not play well with asyncio ones (or at least it will hurt 'peformances'  by inducing extra buffering etc. )

**Comment by asvetlov** [comment]
Gunicorn does hurt performance but overhead is relative low.

**Comment by ssolari** [comment]
+1 this would be awsome.  Since I was having problems with gunicorn #1223, I tried to run aiohttp web.run_app behind nginx without gunicorn, but couldn't get things to work.   Tried just proxy_pass to the 127.0.0.1 port but no go.   I'm not sure what i was doing wrong. nginx isn't that easy to understand and the interactions between webservers is really tricky.

**Comment by moden-py** [comment]
Search does not work for `Nginx+Gunicorn` section in `deployment.rst`.
Steps to reproduce:
1. open https://aiohttp.readthedocs.io/en/stable/
2. Type 'Gunicorn' in the `Quick search` field, press `Go`
3. Click on 'Deployment using 'Gunicorn' result
Actual result: 'This page does not exist yet.'

I'm not sure why, but the 'Gunicorn' result leads to `http://aiohttp.readthedocs.io/en/stable/`**gunicorn.html**`?highlight=Gunicorn` url, although it should lead to some `/`**deployment.html**`?highlight=Gunicorn`

I was unable to find the mistake in `deployment.rst`.

**Comment by asvetlov** [comment]
Fixed by aiohttp==1.1.1
