### ISSUE TITLE
Outdated documentation about minimum supported Python version

### ISSUE THREAD

**Issue by jwilk** [aio-libs/aiohttp#1131]
Since b3eeedbc2f515ec2aa6e87ba129524c17b6fe4e3, aiohttp requires Python 3.4.2.
But some pieces of documentation still say that the minimum version in 3.4.1:
- `README.rst`
- `docs/index.rst`
- `docs/faq.rst`

**Comment by rutsky** [comment]
@jwilk thanks for noticing this, can you provide pull request fixing this?
