### ISSUE TITLE
Support X-Forwarded-* and Forwarded implicitly, deprecate secure_proxy_ssl_header.

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1134]
It's not obvious and the current doc is misleading: it proposes `secure_proxy_ssl_header='X-Forwarded-Proto'` but should do `secure_proxy_ssl_header=('X-Forwarded-Proto', 'https')`.

Looks like @popravich made a mistake on documenting it by d4954ef4
1. `X-Forwarded-For`, `X-Forwarded-By`, and  `X-Forwarded-Proto` should be supported. See the spec at http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html
2. `Forwarded` header from RFC 7239 https://tools.ietf.org/html/rfc7239 should be supported as well.

The issue doesn't require a single Pull Request, most likely it should be several PRs, each for other aspect for sake of easy reviewing etc.

Until we'll remove deprecated `secure_proxy_ssl_header` support it should be processed first before all other rules.

**Comment by evertlammerts** [comment]
What's the status on this? I'm going to use:

- [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded)
- [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto), [X-Forwarded-Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host) and [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)
- [Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host)

... to try to determine how & where my service can be reached during runtime. I can do this in my own code but I can also shoot in a PR. How about this approach:

- add the above headers to [aiohttp.hdrs](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/hdrs.py)
- use them in the above order in `Request._scheme`, `Request.host` and `Request.url` in an attempt to determine the correct vales
- explain resolution order in the docs

Would that be useful enough to be included?

**Comment by fafhrd91** [comment]
@evertlammerts PR would be very good!

**Comment by evertlammerts** [comment]
How about something like this? There are no tests in there yet and I'm not sure how deprecation works in aiohttp. Any pointers?

I'll revisit soon, just about to leave on a trip.

**Comment by fafhrd91** [comment]
we use deprecation warning. but what do you want to deprecate?

**Comment by evertlammerts** [comment]
Title says "deprecate secure_proxy_ssl_header"

**Comment by fafhrd91** [comment]
@samuelcolvin could you check? I think you last one who modified "secure_proxy_ssl_header"

**Comment by evertlammerts** [comment]
Personally I think making a best effort to determine scheme, host and port using standard and defacto standard headers is enough. People can always check for less common headers manually. In any case, maybe deprecation of secure_proxy_ssl_header could be a different PR?

I'm not completely sure about the most common semantics of X-Forwarded-Host, and whether its value is mostly the same as what the Host header contains without a proxy; in particular, does it normally contain the port number if not 80/443? I'll research next week.

**Comment by evertlammerts** [comment]
Any chance this can still make it into 2.1?

**Comment by fafhrd91** [comment]
sure

**Comment by a-urth** [comment]
So, am I missing something or support for `X-Forwarded-For` actually wasn't added during this issue?
If so intended, then is it expected to be added later on?

**Comment by a-urth** [comment]
@evertlammerts Thanks for answer. For me there is no problem since we already doing split by comma, as You proposed. I was just confused since this issue mentions such problem, but I found nothing about that in merge request. Anyway, good to know and thanks again.

**Comment by asvetlov** [comment]
I don't think that forwarded-for is interesting to anybody. But please feel free to open a new PR if needed.

**Comment by asvetlov** [comment]
Let's close the issue, it's completed from my perspective.

**Comment by adamcharnock** [comment]
For anyone else chasing their tail trying to figure out where this feature has gone, it has been removed and moved into middleware. See here:

https://github.com/aio-libs/aiohttp/issues/2171#issuecomment-346689565
