### ISSUE TITLE
Gzipped pages cause UnicodeDecodeErrors

### ISSUE THREAD

**Issue by obmarg** [aio-libs/aiohttp#1141]
## Long story short

Gzip decoding seems to be broken just now.  Attempting to load a gzipped website using aiohttp causes UnicodeDecodeErrors.
## Expected behaviour

aiohttp should be able to load gzipped data from a request.
## Actual behaviour

I've seen 2 UnicodeDecodeErrors, from 2 different servers.  This one is from httpbin.org:

> UnicodeDecodeError: 'charmap' codec can't decode byte 0xff in position 9: character maps to <undefined> 

This one is from a private server:

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
## Steps to reproduce

``` python
import aiohttp
import asyncio
run = asyncio.get_event_loop().run_until_complete
resp = run(aiohttp.get('http://httpbin.org/gzip'))
run(resp.text())

UnicodeDecodeError: 'charmap' codec can't decode byte 0xff in position 9: character maps to <undefined>
```
## Your environment

Python 3.5.1
Aiohttp 0.22.3
Seen on MacOS & Linux

**Comment by asvetlov** [comment]
Your example just works on my machine :)

**Comment by obmarg** [comment]
You know what: it works on my machine as well, when run from a clean virtualenv.  Must be something specific to the virtualenv I was running it in yesterday.  Let me do some more investigation and see if I can pin it down.
