### ISSUE TITLE
Incomplete Websockets Documentation

### ISSUE THREAD

**Issue by frederikaalund** [aio-libs/aiohttp#1144]
The current [websockets documentation](http://aiohttp.readthedocs.io/en/stable/web.html#websockets) only handles two message types: `MsgType.text` and `MsgType.error`. However, a runtime error may occur if `MsgType.closed` is not handled as well. This should be clear from the official documentation.

It took me a long time to figure out why my program returned errors because of this. Now that we are at it: Why not simply catch the `MsgType.closed` in the [`__anext__`](https://github.com/KeepSafe/aiohttp/blob/v0.22.5/aiohttp/web_ws.py#L309) function? It is unintuitive that `autoclose=True` (which is also the default) doesn't deal with `MsgType.closed` when it deals with `MsgType.close`. I realize that the former is your own internal message while the latter is part of the WS standard.

Side note: In the [web_ws example](https://github.com/KeepSafe/aiohttp/blob/v0.22.5/examples/web_ws.py#L33) this is implicitly handled correctly through an else clause.

I'm using Python 3.5.1 and Aiohttp 0.22.5.

**Comment by asvetlov** [comment]
Agree with implicit catching closing message in `__anext__`.
Would you make a Pull Request?

**Comment by frederikaalund** [comment]
> Agree with implicit catching closing message in **anext**.

Great.

> Would you make a Pull Request?

Yeah sure, I can do that.

**Comment by asvetlov** [comment]
Fixed by #1145
