### ISSUE TITLE
Redirects for HEAD requests should use HEAD

### ISSUE THREAD

**Issue by catlee** [aio-libs/aiohttp#1146]
## Long story short

I'm trying to do a HEAD request to a service that returns a 303 redirect. aiohttp then does a full GET on the new location.
## Expected behaviour

aiohttp should instead do a HEAD on the new URL.
## Actual behaviour

aiohttp does a GET on the new URL

The code responsible is here: https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L228
This references this PR from the requests library: https://github.com/kennethreitz/requests/pull/269/files. However, the requests library is preserving the HEAD method for subsequent requests.

**Comment by asvetlov** [comment]
Makes sense.
Would you provide a fix?
