### ISSUE TITLE
Publish ClientSession.loop property

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1149]
`web.Application.loop` is very handy -- all server code has access to application instance and therefore loop is not need to be tediously passed into every function call.

Let's implement the same for client session.

**Comment by Kentzo** [comment]
@asvetlov I think this feature request may be related to this task: http://bugs.python.org/issue26969

**Comment by asvetlov** [comment]
No. I recommend to pass loop explicitly everywhere.
The property is just convenient helper allowing to not pass loop along with `ClientSession` because the session already has a reference to loop inside.
