### ISSUE TITLE
Implement StreamReader.readuntil() method

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1151]
Should be mimic to `asyncio.StreamReader` counterpart: https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamReader.readuntil

**Comment by asvetlov** [comment]
Looks like nobody need it.
Feel free to reopen the issue with the use case

**Comment by yapith-suplari** [comment]
@asvetlov I described my issue/use-case in #3881, but I'll summarize it here:

I'm pulling data from web services that don't provide response content-length and doesn't not have explicit EOF character. Under high concurrent network load, I'm seeing `await read()` returns partial data sometimes. I suspect that it catches its internal buffer empty and terminates prematurely. (Is this even possible? Let me know if I'm making bad assumptions here)

`readuntil` allows me to seek an explicit end-of-stream indicator if known and make aiohttp more reliable
