### ISSUE TITLE
Deprecate old websocket specs

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1160]
it seems we don't really need `SEC_WEBSOCKET_KEY1` header support

**Comment by asvetlov** [comment]
Sorry, I don't follow.

**Comment by fafhrd91** [comment]
Search it in source code

**Comment by asvetlov** [comment]
Sorry, I still don't understand you.
What concrete actions should be done for fixing your request?

**Comment by fafhrd91** [comment]
`SEC_WEBSOCKET_KEY1` is from old websocket spec, it is not used anymore.
