### ISSUE TITLE
Client session method that accepts http verb as a parameter

### ISSUE THREAD

**Issue by thanosexcite** [aio-libs/aiohttp#1167]
## Long story short

I'd like to create a wrapper function around the http client and a small annoyance that I'm having is that there is no method in ClientSession that accepts the http verb as a parameter. There are just .get(), .post(), etc methods as far as I can see. So, to make my wrapper, I need to have multiple if statements that will choose the correct method from ClientSession, depending on the passed http verb string.

Is it possible to have something like a .request() that can accept the verb as a param? There is one like that for the Basic API of the client, but not in the session one.
## Expected behaviour

A ClientSession.request(self, method, url, _, data=None, *_kwargs) function should exist that accepts the verb as a param, but other than that, it should be the same as the other ClientSession verb methods.
## Actual behaviour

There is no such method.
## Your environment

aiohttp==0.22.5
Linux

**Comment by asvetlov** [comment]
`ClientSession.request exists for a year and half.
