### ISSUE TITLE
MultipartWriter does not support binary content encoding

### ISSUE THREAD

**Issue by AleksandrIakhnev** [aio-libs/aiohttp#1168]
## Long story short

There is no support of binary encoding in MultipartWriter
Some services require binary encoding. Seems that easy to implement with just returning unprocessed chunks.
## Expected behaviour

Supported binary encoding
## Actual behaviour

Not implemented encoding
https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/multipart.py#L858
## Steps to reproduce

Specify header 'Content-Transfer-Encoding' to 'binary' in MultiPartWriter

**Comment by kxepal** [comment]
Good catch. Please check #1169
