### ISSUE TITLE
HTTP GET + compress=True = 501

### ISSUE THREAD

**Issue by a-urth** [aio-libs/aiohttp#117]
There are some strange behavior with proxies. Trying to do HTTP GET request, requests package gives correct result, asyncio - 501.

Response headers:
SERVER - squid/3.1.4
MIME-VERSION - 1.0
DATE - Mon, 14 Jul 2014 20:20:15 GMT
CONTENT-TYPE - text/html
CONTENT-LENGTH - 3136
X-SQUID-ERROR - ERR_UNSUP_REQ 0
VIA - 1.0 host (squid/3.1.4)

Proxy - 173.234.226.20:8800

Seems that GET method for such proxy is incorrect, even if request done through http.
Any suggestions?

**Comment by fafhrd91** [comment]
is it still the problem?

**Comment by danielnelson** [comment]
I think it must be still an issue based on comments in #835.

**Comment by fafhrd91** [comment]
@danielnelson what to fix it?

**Comment by danielnelson** [comment]
sure

**Comment by asvetlov** [comment]
Fixed by #891
