### ISSUE TITLE
Refactor data stream uploading for client api

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1172]
Now `aiohttp.ClientSession.request(..., data=data)` supports too many available constructions:
1. `FormData`
2. `asyncio.StreamReader`
3. `aiohttp.StreamReader`
4. `io.IOBase` 
5. `bytes`
6. `bytearray`
7. `streams.DataQueue`
8. `coroutine` with `yields` inside

I propose to drop (well, with deprecation period) two latest options but implement support for asynchronous iterators as data source.
Async generators is the most native way for upload BODY asynchronously IMHO. 
Python 3.6 allows to write them with very elegant syntax (https://www.python.org/dev/peps/pep-0525/). As workaround for Python 3.5 user may use https://github.com/njsmith/async_generator

It should fix also long standing #183

**Comment by kxepal** [comment]
Sounds good for me. 
I wonder if it would be possible to implement some [single](https://xkcd.com/927/) interface that will cover all current cases and will let people pass various custom objects as data if they fulfil it?

**Comment by asvetlov** [comment]
I have no idea how this single interface should look like.
For me byte and file API is good for simple cases and async generator covers all complex needs.
Hmm, we could drop bullets 2 and 3 as well: `asyncio.StreamReader` and `aiohttp.StreamReader` both support async iteration protocol :)

**Comment by dhrp** [comment]
I ran into something I don't understand on this topic, and posted on Stackoverflow. Is this related? 

http://stackoverflow.com/questions/40299114/with-aiohttp-post-how-do-i-pass-it-some-data-to-iterate

**Comment by asvetlov** [comment]
I don't understand do you have problems with your example or not?

Yes, coroutine support should be deprecated but it still exists and working.
See https://github.com/KeepSafe/aiohttp/blob/master/tests/test_client_functional_oldstyle.py#L427-L457 for unit test.

**Comment by fafhrd91** [comment]
I am working on refactoring in `payload-refactoring` branch #1664

**Comment by fafhrd91** [comment]
merged
