### ISSUE TITLE
Unclosed client session warning

### ISSUE THREAD

**Issue by tahajahangir** [aio-libs/aiohttp#1175]
## Long story short

We see rare logs with error level `ERROR` saying `Unclosed client session` during normal operation.
## Expected behaviour

No log!
## Actual behaviour

Sample log:

```
2016-09-14 18:42:28,511 ERROR asyncio Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd2b06469b0>
```

As an aiohttp user, can we do anythin to prevent unclosed sessions? If no, it's better to have a specific warning class (subclass of `ResourceWarning`), not just using the original base class.
## Steps to reproduce

Cannot reproduce manually!
## Your environment

Debian 8
Python 3.5.2
aiohttp (0.22.5)

**Comment by asvetlov** [comment]
Either use `async with aiohttp.ClientSession() as session: ...` or call `await session.close()` explicitly.

**Comment by tahajahangir** [comment]
We don't use `ClientSession` directly:

``` python
async with aiohttp.post(check_url, data=data) as resp:
    if resp.status == 200:
        return await resp.json()
```

Is it wrong?!

**Comment by asvetlov** [comment]
It's deprecated and removed from the documentation's _usage_ part.
Perhaps we had reasons for it, isn't it?
And the main reason is impossibility to provide steady graceful shutdown with this API.

**Comment by Kentzo** [comment]
@asvetlov Unfortunately `warnings.warn` is not a widely adopted (or known?) technique. And even fewer users know in advance that particular package utilizes it.

Maybe a banner should be added to the tutorial stating that? Or even a suggestion to turn warnings into exceptions?

**Comment by asvetlov** [comment]
Teaching users to working with warnings is out of scope of this project.
I don't want to mess tutorials with banners like notes or warnings.
Even Django (super newbie friendly tool) just uses `DeprecationWarning`.
