### ISSUE TITLE
RuntimeError when running inside a tornado handler

### ISSUE THREAD

**Issue by arthurdarcet** [aio-libs/aiohttp#1176]
## Long story short

dc79e14b69bae57db3bfb09ae4640c4c80dc0d1c introduced timeouts for every request, using `async_timeout.Timeout` which isn't compatible with tornado.
Before this commit, using `aiohttp.Timeout` in a tornado handler would fail but simple requests were working as expected. This commit makes every request fail with a `RuntimeError('Timeout context manager should be used inside a task')`.

If I'm not mistaken, `asyncio.wait_for` works even with tornado, I would suggest using this if available instead of `async_timeout.Timeout`, but since the current `Timeout` implementation is a regular context manager (and not an async one), implementing this fallback is not obvious and would require some API changes.

Additionnally, adding a comment on this line https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L197 would help since this is what appears in the stack trace. Maybe something like "aiohttp is not compatible with tornado, consider using tornado.httpclient.AsyncHTTPClient instead"
## Steps to reproduce

``` python
import asyncio
import aiohttp
import tornado.platform.asyncio
import tornado.web

class Handler(tornado.web.RequestHandler):
    async def get(self):
        result = await aiohttp.get('http://httpbin.org/')
        self.write(str(result.status))

tornado.platform.asyncio.AsyncIOMainLoop().install()
tornado.web.Application([(r"/", Handler)]).listen(8888)
asyncio.get_event_loop().run_forever()
```
## Your environment

tornado 4.4.1
aiohttp 1.0.0 (works with 0.22.5)

**Comment by asvetlov** [comment]
It is known issue and, sorry, bug is not inside aiohttp.
In asyncio a coroutine is always executed inside a task -- either directly by `loop.create_task(coro())` call or indirectly by using `await coro()` inside other coroutine.

But it's not true for tornado.
Thus tornado is not 100% compatible with asyncio.

As workaround I can suggest to wrap every tornado callback with a decorator for task creation.
Something like this (untested):

```
def deco(func):
    async def wrapper(*args, **kwargs):
        return asyncio.get_event_loop().create_task(func(*args, **kwargs))
   return wrapper

class Handler(tornado.web.RequestHandler):

    @deco
    async def get(self):
        ...
```

P.S.
`wait_for()` creates a task, the call is much slower than `aiohttp.Timeout` when timeouts are used massively.

**Comment by arthurdarcet** [comment]
OK, thank you for your response. I will stick with aiohttp 0.22 until we are ready to dump tornado and switch to a complete asyncio stack.

**Comment by asvetlov** [comment]
Would you try a solution with decorating tornado's callback methods?

**Comment by arthurdarcet** [comment]
Yes, it works, but that's not an option in my use-case

**Comment by asvetlov** [comment]
Up to you.
I don't want to give up from very handy tool just because tornado doesn't support it (yet).
The main aiohttp audience is asyncio-based code and we are striving to be compatible with asyncio itself only.
