### ISSUE TITLE
Websocket interface change break existing code

### ISSUE THREAD

**Issue by iceboy233** [aio-libs/aiohttp#1178]
## Long story short

We recently noticed that `aiohttp.web.MsgType` was changed to `aiohttp.web.WSMsgType`, which break existing code, such as https://github.com/aio-libs/sockjs/blob/master/sockjs/transports/rawwebsocket.py#L39.
## Your environment

aiohttp 1.0.0

**Comment by twd2** [comment]
+1

**Comment by asvetlov** [comment]
Would you make a PR for sockjs for using canonical name?
I'm also ok for adding `aiohttp.web.MsgType` alias for `aiohttp.web.WSMsgType` and keeping in for 1.5 years.
