### ISSUE TITLE
Django CSRF cookie not being set with 1.0.0 and gunicorn 19.6.0

### ISSUE THREAD

**Issue by dalberto** [aio-libs/aiohttp#1179]
## Long story short

Before upgrading to 1.0.0 (using aiohttp 0.22.5), cookies were correctly being passed from the aiohttp gunicorn worker to django. Now it seems like it is not.
## Expected behaviour

Django should see the csrf cookie.
## Actual behaviour

Django returns a 403 response, with the error message `CSRF cookie not set`.
## Steps to reproduce

Executing the following:
`gunicorn my_app.wsgi:application -w 2 -k gaiohttp --log-file=- -b :8000`

```
# wsgi.py
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "my_app.settings")

application = get_wsgi_application()
```
## Your environment

aiohttp 1.0.0
django 1.9.8
gunicorn 19.6.0

Like I said before, if I revert back to 0.22.5 there are no issues.

**Comment by fafhrd91** [comment]
oh, thats bad idea in first place. django is not suitable to run with asyncio loop.

also aiohttp.wsgi is mostly deprecated.

**Comment by asvetlov** [comment]
Hmm. I have no idea what change had break the code.
gaiohttp does nothing with cookies.

Could you display headers provided to your django app behind both aiohttp 0.22 and 1.0?

**Comment by asvetlov** [comment]
Also yes, as @fafhrd91 mentioned gaiohttp is not the best tool for running django.

**Comment by dalberto** [comment]
ok, let me try to get a sample of the headers with the different versions. I also tried the `aiohttp.worker.GunicornWebWorker` worker class but that seems to be incompatible. I'm guessing I would need https://github.com/etianen/aiohttp-wsgi in order to use that worker class.

**Comment by fafhrd91** [comment]
just my opinion but there is no any reason to run django inside aiohttp

**Comment by dalberto** [comment]
Fair enough. If it's not an officially supported use-case, then the best course of action is to switch to a different worker class. Thanks!
