### ISSUE TITLE
Provide MacOSX binary wheels. Help needed!

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1181]
I'd love to publish MacOSX binary wheels on PyPI.
## Current State for Deployment

Now we support wheels for Windows and Linux (using `manylinux` platform).

We have the following build matrix:
- linux
  - platform
    - x86_64 (64 bit)
    - i686 (32 bit)
  - python
    - python 3.4
    - python 3.5
- Windows
  - platform
    - win_amd64 (64 bit)
    - win32 (32 bit)
  - python
    - python 3.4
    - python 3.5
## What's Required

According to [cryptography](https://pypi.python.org/pypi/cryptography/1.5) MacOSX build matrix should be:
- MacOSX
  - os version
    - 10.6
    - 10.10
  - platform
    - win_amd64 (64 bit)
    - win32 (32 bit)
  - python
    - python 3.4
    - python 3.5

Maybe MacOSX 10.6 is not important -- I can live with 10.10 only. Honestly I can live without Mac OS at all, my OS of choice is Ubuntu -- but many aiohttp users works on Macs for good or for bad.

So far so good.
I'm using travis-ci.org for building linux wheels and tarball and appveyor.com for Windows.
Deployment process is highly automated -- I just add new git tag and CIs does all dirty job.
Personally I'm very happy with deployment process.

I would add the same for MacOS.
But I have no MacOS box, this is the problem!
As far as I know Travis supports MacOS but it doesn't support `python` command for this configuration, no python is installed.
Ok, I've read that `brew install python3` works on Travis.
I need not _the latest_ python but exactly **python 3.4** and **python 3.5** installed.
## Conclusion

I need a volunteer for tuning Travis build matrix.
The person doesn't need to be committer for the project.
Only committers have access writes for pushing new git tags, you know.
What I'm asking is modifying `.travis.yml` for running aiohttp test suite on MacOS.
Just making the suite working on MacOSX on both Python 3.4 and Python 3.5 would be perfect!
After that I could add required commands for building binary wheels and publishing them on PyPI.

Is there any volunteer?

**Comment by fafhrd91** [comment]
you can ping Philipp, i'm sure we can find solution

**Comment by asvetlov** [comment]
@philippb ping!

**Comment by zoidyzoidzoid** [comment]
I have a homebrew tap for Python 3.4 and Python 3.5. I'll make sure they're the latest versions of 3.4 and 3.5 tomorrow. It should be possible to use it on Travis.

https://github.com/zoidbergwill/homebrew-python

**Comment by asvetlov** [comment]
@zoidbergwill thank you.

Most likely I don't need the latest versions but 3.4.2+ and any 3.5
What I need is a PR for travis build matrix.

Unfortunately I have no access to MacOS box and have no knowledge about homebrew usage.
I'd very appreciate if you would to update `.travis.yml` for passing tests on MacOS

**Comment by zoidyzoidzoid** [comment]
@asvetlov I'll happily have a look, and see how far I can get. 

Using `pyenv` might be an option too. I'll try.

**Comment by zoidyzoidzoid** [comment]
Looking into this, it sounds like this should be possible and simple enough with Travis, borrowing some stuff from Cryptography's scripts. 

I'm gonna have a look at it during PyConZA sprints this weekend.

**Comment by asvetlov** [comment]
Cool! Have you a nice conference!

**Comment by zoidyzoidzoid** [comment]
I've got OSX tests running on Travis CI now.

The wheels build and install for me locally, and I just need to tidy up my [branch/commits](https://github.com/KeepSafe/aiohttp/compare/master...zoidbergwill:travis-ci-osx) a bit, then I'll make a PR.

**Comment by zoidyzoidzoid** [comment]
The tests don't pass for me on Python 3.5 on OSX, both on Travis and locally: https://travis-ci.org/zoidbergwill/aiohttp/builds/166216735

But work on older versions of OSX. :/

**Comment by asvetlov** [comment]
Very good!
I can cope with failed test later probably.

**Comment by zoidyzoidzoid** [comment]
Seems like it's a bit of a dice roll. [Working now](https://travis-ci.org/zoidbergwill/aiohttp/builds/166220781)

**Comment by fafhrd91** [comment]
Will it help if we ran aiohttp on commercial Travis account?

**Comment by AraHaan** [comment]
hmm @zoidbergwill if you would like you can always help me with setting OSX up on my bin2c C++ project for the absolute latest gcc, g++ and clang available so that way I could make absolute use of the experimental filesystem header on that. So far it has been Erroring nonstop and sending annoying emails so with someone who knows more on OSX than me it would be great if I could get builds to work again on it.
