### ISSUE TITLE
Is forbidding charset in content_type intended?

### ISSUE THREAD

**Issue by iceboy233** [aio-libs/aiohttp#1182]
## Long story short

aio-libs/sockjs now raises ValueError: charset must not be in content_type argument
## Long story

There are multiple calls to `web.Response` with `content_type` parameter including charset information, such as `application/json; charset=UTF-8` in [`sockjs/route.py`](https://github.com/aio-libs/sockjs/blob/master/sockjs/route.py).

We noticed that there's a separate parameter `charset` and we should put charset there (and utf-8 is defaulted so we should simply remove), but doing so would make it inconsistent between setting `content_type` and setting `headers` - there's another bunch of code which sets `hdrs.CONTENT_TYPE` directly, such as `(hdrs.CONTENT_TYPE, 'application/javascript; charset=UTF-8')` in `sockjs/transports/*.py`.
## Your environment

aiohttp 1.0.1
sockjs 0.4

**Comment by asvetlov** [comment]
In aiohttp `content_type` ctor parameter is compatible with `response.content_type` property, the same is true for `charset`.
`Content-Type` header is an another story, it's represented by `.content_type` and `.charset` properties combination.

**Comment by asvetlov** [comment]
Previous behavior for `web.Response` was just a not found in time bug.
