### ISSUE TITLE
Custom headers are ignored

### ISSUE THREAD

**Issue by peterstark72** [aio-libs/aiohttp#1184]
## Long story short

Custom headers are ignored and are not added to the request.
## Expected behaviour

headers = {
        "Content-Type": "application/json",
        "x-api-key": "foo"
 }
session.post(url, headers=headers)

I expect the headers to be added to the HTTP request. 
## Actual behaviour

No custom headers are added. 
## Steps to reproduce

headers = {
        "Content-Type": "application/json",
        "x-api-key": "foo"
 }
session.post(url, headers=headers)
## Your environment

aiohttp 1.01
Python 3.5.2

**Comment by asvetlov** [comment]
Please double check your code.
aiohttp **passes** custom headers.
See 4883b00 for explicit test for the issue.

**Comment by peterstark72** [comment]
Sorry, I checked again, and the headers are there. 

BUT the problem seems to be that "x-api-key" is changed by aiohttp into "X-Api-Key" and the server I am talking to does not accept that.

**Comment by asvetlov** [comment]
You have bad server which doesn't conform to RFC documents (https://tools.ietf.org/html/rfc7230 for example). A header name should be case insensitive.

We support `raw_headers` (unconverted bytes for both header's name and value) for request but responses.

If you are interesting -- please create a new issue. 
A Pull Request is welcomed as well :smile:

**Comment by ludovic-gasc** [comment]
Hi @peterstark72, I'd already have this type of issue: A crappy device to provision where you need to send the exact HTTP content they want to work.
To face about that without to change aiohttp, I use some custom configuration in a HAProxy, where you can easily rewrite HTTP requests and responses.

An HAProxy example:

```
reqirep ^X-API-KEY:\ (.*) x-api-key:\ \1
```

You have also rspirep to rewrite HTTP responses.
Certainly cleaner to do that directly at aiohttp level, but it's better than nothing, isn't it ? ;-)
