### ISSUE TITLE
Support HPKP

### ISSUE THREAD

**Issue by rugk** [aio-libs/aiohttp#1185]
HPKP improves the security of HTTPS connections in a great extend! It would be nice if aiohttp would support it out of the box.

https://scotthelme.co.uk/hpkp-http-public-key-pinning/
https://developer.mozilla.org/de/docs/Web/Security/Public_Key_Pinning
https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning
https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning
https://timtaubert.de/blog/2014/10/http-public-key-pinning-explained/
https://tools.ietf.org/html/draft-ietf-websec-key-pinning-21

**Comment by asvetlov** [comment]
Agree, it would be nice.
Unfortunately the issue has low priority for me but if you, @rugk want to make a Pull Request -- please go ahead!

**Comment by rugk** [comment]
I am not really experienced in Python. Maybe /cc @lgrahl

**Comment by lgrahl** [comment]
I'll have a look at it as soon as I can find some time.

**Comment by asvetlov** [comment]
Great!

**Comment by lgrahl** [comment]
Just wanted to let you know that it will take quite some time before I can potentially pick this up. So, if anyone else wants to implement it, please go for it.

**Comment by asvetlov** [comment]
Close as not active for very long time.

**Comment by rugk** [comment]
Are you kidding, no… this is still a feature that is missing. Nobody was active to implement it.

**Comment by asvetlov** [comment]
If nobody wants to implement it -- it will be missed forever.
The bug tracker is not a wishlist for never implemented dreams.
If you still want it -- please come up with a pull request.

**Comment by rugk** [comment]
@lgrahl You talked about time… I am here from the future… :stuck_out_tongue_winking_eye:
