### ISSUE TITLE
Remove MD5 & SHA1 from certificate validation

### ISSUE THREAD

**Issue by rugk** [aio-libs/aiohttp#1186]
Please remove SHA-1 and MD5 as [options for verifying certificates](https://aiohttp.readthedocs.io/en/stable/client_reference.html?highlight=tcpconnector#tcpconnector). MD5 is known to be broken for decades and SHA-1 is considered insecure and being depreciated.

Just do not offer these insecure options anymore, so that developers cannot use them. Get security by default!

**Comment by asvetlov** [comment]
We cannot just suddenly remove something without very strong reason.
What can we do is: 
1. Update documentation by suggesting SHA256 only and declaring MD5/SHA-1 deprecation
2. Raise a warning on MD5 or SHA-1 usage but keep supporting them for 1.5 years.

Volunteer is needed.

**Comment by rugk** [comment]
Yes this would be good. Although I would argue to drop MD5 support earlier than SHA-1. (maybe MD5: 0.5 years, SHA1: 1.5y)

**Comment by Taekyoon** [comment]
Can I put some messages when developers choose 'MD5' or 'SHA-1' to the functions?
And If it's okay, should I just put comment on code or print in console?

**Comment by asvetlov** [comment]
@Taekyoon I don't follow.
From my perspective it should be [warnings.warn](https://docs.python.org/3/library/warnings.html#warnings.warn) call along with [logging.warning](https://docs.python.org/3/library/logging.html#logging.Logger.warning)

**Comment by jake-jake-jake** [comment]
I've added a warning.warn call and have updated the docs to show that the older hashes are insecure and deprecated on [this branch on my fork](https://github.com/jake-jake-jake/aiohttp/tree/connection_warnings). What is your preferred method of testing this behavior? (I am not super familiar with PyTest.)

**Comment by asvetlov** [comment]
These tests: https://github.com/KeepSafe/aiohttp/blob/master/tests/test_client_functional.py#L256-L308 should raise warning on deprecated fingerprints.
Warning could be caught by `with pytest.warns(DeprecationWarning): ...` context manager.

**Comment by asvetlov** [comment]
Fixed by #1341
