### ISSUE TITLE
Server example on home page

### ISSUE THREAD

**Issue by tailhook** [aio-libs/aiohttp#1194]
There is a following example on the home page:

```
from aiohttp import web

async def handle(request):
    name = request.match_info.get('name', "Anonymous")
    text = "Hello, " + name
    return web.Response(body=text.encode('utf-8'))

app = web.Application()
app.router.add_get('/{name}', handle)

web.run_app(app)
```

From my perspective this example has following problems:
1. There is no page at `http://localhost:8080` (it's 404), this also means `get('name', "Anonymous")` is useless
2. When I visit `http://locahost:8080/something` it's served with `Content-Type: application/octed-stream`, so it's not user-friendly (page is downloaded rather than shown). Adding a content-type of `plain` or `html` should help.

I have aiohttp 1.0.1 if that matters.

**Comment by asvetlov** [comment]
Makes sense.
