### ISSUE TITLE
Additional handler params for gunicorn worker 

### ISSUE THREAD

**Issue by imbolc** [aio-libs/aiohttp#1196]
It looks like there is no way to pass additional params like `secure_proxy_ssl_header` into `app.make_handler` of gunicorn worker.

**Comment by asvetlov** [comment]
BTW Particular `secure_proxy_ssl_header` should be deprecated and replaced with #1134

**Comment by Valian** [comment]
I've found quick and dirty workaround until clean support is implemented

```
from functools import partial

application.make_handler = partial(
    application.make_handler, 
    secure_proxy_ssl_header=('X-Forwarded-Proto', 'https'))
```
