### ISSUE TITLE
Timeout without keep-alive

### ISSUE THREAD

**Issue by imbolc** [aio-libs/aiohttp#1198]
Should not here be a check if keep-alive mode is active? https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/server.py#L227

**Comment by fafhrd91** [comment]
this is different, it is slow request check. client can abuse connection and send header very slowly (kind of ddos)

**Comment by imbolc** [comment]
I mean if keep-ailve mode is off, shouldn't we count here only `self._slow_request_timeout`?

**Comment by fafhrd91** [comment]
i think it is just complicates code without benefits, also we run this code on first request as well when keep-alive state is not defined yet

**Comment by imbolc** [comment]
I mean the case in which `tcp_keepalive` disabled in `app.make_handler`. E.g. 

```
app.make_handler(
    tcp_keepalive=Flase,
    slow_request_timeout=30
)
```

If I do not mention `keepalive_timeout` in this config it will be 75. So `max(self._slow_request_timeout, self._keepalive_timeout)` will be 75. But I expect 30.

**Comment by imbolc** [comment]
Maybe `tcp_keepalive` is redundant, why don't use `keepalive_timeout=0` instead?

**Comment by fafhrd91** [comment]
actually `tcp_keepalive` is only viable option for aiohttp. `keepalive_timeout` is incredibly slow under load.

**Comment by asvetlov** [comment]
Handling keep-alives  is required for supporting HTTP persistent connections.
But tcp_keepalive is very different, it works on TCP socket keepalive level (http://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/)

Thus we need both.

**Comment by imbolc** [comment]
Understood, thanks :)
