### ISSUE TITLE
Gunicorn[UVLoop]WebWorker doesn’t follow gunicorn's signal semantics

### ISSUE THREAD

**Issue by hynek** [aio-libs/aiohttp#1201]
## Long story short

From http://docs.gunicorn.org/en/latest/signals.html:

> QUIT, INT: Quick shutdown
> TERM: Graceful shutdown. Waits for workers to finish their current requests up to the graceful timeout.

`Gunicorn[UVLoop]WebWorker` don’t follow that.
## Expected behaviour

Do what the docs say. :)
## Actual behaviour

SIGINT and SIGTERM behave the same and perform graceful shutdowns.
## Suggested Fix

If I’m not mistaken, it would be enough to remember whether the shutdown is supposed to be graceful or not and based on that perform https://github.com/KeepSafe/aiohttp/blob/8a145e07d56ab0fcccd2caaa5df6bd8699ce250e/aiohttp/worker.py#L81-L86 conditionally.

**Comment by 1st1** [comment]
This might be related to #1202, please try uvloop 0.5.4.

**Comment by hynek** [comment]
This isn’t related to uvloop; it doesn't work with the vanilla worker either.

**Comment by fafhrd91** [comment]
fixed by #1420
