### ISSUE TITLE
Write non-autodoc reference for test_utils API

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1210]
http://aiohttp.readthedocs.io/en/stable/testing.html#module-aiohttp.test_utils is a mess.

The section should be rewritten using explicit doc style (like `client_reference.rst` or `web_reference.rst`).

It's an easy task, I very appreciate a Pull Request with fix.

**Comment by Taekyoon** [comment]
I want to try this one, but I have no idea to approach this problem.
If you give me a hint, I could do that one!

**Comment by asvetlov** [comment]
In https://raw.githubusercontent.com/KeepSafe/aiohttp/master/docs/testing.rst I've started to document `TestServer` and `TestClient`.
You could pickup the work and move it forward.

**Comment by jake-jake-jake** [comment]
@Taekyoon you making progress on this? If not I can take a look.

**Comment by asvetlov** [comment]
@jake-jake-jake please do.
If @Taekyoon has something to display -- I'll be a coordinator for solving merge conflicts.
Documentation is the pain, you know.
I'm strongly trying to keep it up to date etc. but very very appreciate any contributions.

**Comment by Taekyoon** [comment]
@jake-jake-jake @asvetlov  I'm sorry... I was busy with my work, so I didn't take care of this. Sure! you can take this issue.

**Comment by asvetlov** [comment]
Fixed by #1424 

Docs are not perfect though and pytest fixtures should be described.
