### ISSUE TITLE
extra call to the request handler with 'favicon.ico' ?

### ISSUE THREAD

**Issue by ssolari** [aio-libs/aiohttp#1214]
## Long story short

Seeing an extra call to the request handler using aiohttp sever example? https://pypi.python.org/pypi/aiohttp/0.17.2
what is and why is 'favicon.ico' being passed to the request handler after the request has been processed?
## Expected behaviour

Calling http://127.0.0.1:8080/smith expecting to see:
HERE smith
smith 0
smith 1
smith 2
smith 3
smith 4
## Actual behaviour

Seeing:

HERE smith
smith 0
smith 1
smith 2
smith 3
smith 4
HERE favicon.ico
favicon.ico 0
favicon.ico 1
favicon.ico 2
favicon.ico 3
favicon.ico 4
## Steps to reproduce

``` python
import asyncio
from aiohttp import web

async def handle(request):
    name = request.match_info.get('name', "Anonymous")
    print("HERE", name)
    text = "Hello, " + name
    for i in range(5):
        print(name, i)
        await asyncio.sleep(0.5)
    return web.Response(body=text.encode('utf-8'))

async def init(loop):
    app = web.Application(loop=loop)
    app.router.add_route('GET', '/{name}', handle)
    srv = await loop.create_server(app.make_handler(),
                                        '127.0.0.1', 8080)
    print("Server started at http://127.0.0.1:8080")
    return srv

loop = asyncio.get_event_loop()
loop.run_until_complete(init(loop))
loop.run_forever()
```
## Your environment

Python 3.5.2
Aiohttp 0.17.2
macbook pro

**Comment by asvetlov** [comment]
A browser makes a call for `favicon.ico` automatically.
Sorry, it's the standard behavior. 
I see nothing wrong with it.

**Comment by ssolari** [comment]
Thanks!  Just my non-understanding of what to expect.
