### ISSUE TITLE
Support load/save cookie_jar

### ISSUE THREAD

**Issue by ahuigo** [aio-libs/aiohttp#1219]
I found that cookie_jar do not provide any function to _load or save cookie_jar_

Is there any pythonic way to implement  these two method?

```
session.cookie_jar.load('foo.cookie.txt')
....# do sth.
session.cookie_jar.save()

```

**Comment by asvetlov** [comment]
Thank you for raising the question!

It's definitely possible but not implemented yet.

The problem is the cookies storage format.
I believe making it compatible with everything doesn't make sense.
If we'll make an agreement that the storage is just opaque binary data (a pickled dict of SimpleCookies actually) -- implementation is reduced to pickling/unpickling `CookieJar._cookies` attribute.

Another option is adding pickle support to `CookieJar` itself without adding `load()`/`save()` methods.

@ahui132 would you work on Pull Request?

**Comment by ahuigo** [comment]
I've commited [support load/save cookie_jar](https://github.com/KeepSafe/aiohttp/compare/master...ahui132:master). And it works well.

But encountered a problem about py.test(I have never written a py.test case before), 
It seemed that I should install fixture _event_loop_ and _mocker_, I do not know how to do it.

```
___________________________________ ERROR at setup of test_index ___________________________________
file /usr/local/lib/python3.5/site-packages/aiohttp.src/demos/polls/tests/test_integration.py, line 13
  def test_index(create_app, event_loop, app_db):
file /usr/local/lib/python3.5/site-packages/aiohttp.src/demos/polls/tests/conftest.py, line 9
  @pytest.yield_fixture
  def create_app(event_loop, unused_tcp_port):
E       fixture 'event_loop' not found
>       available fixtures: LineMatcher, _pytest, anypython, app_db, cache, capfd, capsys, create_app, doctest_namespace, linecomp, loop, monkeypatch, pytestconfig, record_xml_property, recwarn, test_client, test_server, testdir, tmpdir, tmpdir_factory, unused_port
>       use 'pytest --fixtures [testpath]' for help on them.

____________________________ ERROR at setup of test_access_logger_atoms ____________________________
file /usr/local/lib/python3.5/site-packages/aiohttp.src/tests/test_helpers.py, line 148
  def test_access_logger_atoms(mocker):
E       fixture 'mocker' not found
>       available fixtures: LineMatcher, _pytest, anypython, cache, capfd, capsys, doctest_namespace, linecomp, log, loop, monkeypatch, pytestconfig, record_xml_property, recwarn, test_client, test_server, testdir, tmpdir, tmpdir_factory, unused_port
>       use 'pytest --fixtures [testpath]' for help on them.

```

I won't add pull request until this problem is solved.

**Comment by asvetlov** [comment]
Did you try `pip install -r requirements-dev.txt` ?
