### ISSUE TITLE
Unable to log certain environment variables in access log

### ISSUE THREAD

**Issue by VladV** [aio-libs/aiohttp#1225]
`%{FOO}e` format doesn't accept underscores, so variables like `SERVER_SOFTWARE` cannot be included in the log.
Tested on 0.21.6, probably applies to the latest version as well.

**Comment by asvetlov** [comment]
Regex from https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/helpers.py#L272 should accept underscore.
The patch is easy.
Any volunteers?

**Comment by esaezgil** [comment]
I will address this :)

**Comment by asvetlov** [comment]
Fixed by @1226
