### ISSUE TITLE
verify_ssl for aiohttp.request

### ISSUE THREAD

**Issue by wabu** [aio-libs/aiohttp#127]
I did not find a way to pass `verify_ssl` to `aiohttp.request`. It somehow seems implemented in `ClientRequest` and `TCPConnector`, but it is not passed on in `aiohttp.request`. 

A workaround for now is to pass `connector=aiohttp.TCPConnector(force_close=True, verify_ssl=False)`, but it's not very usable.

**Comment by amfarrell** [comment]
One challenge this causes is needing to make sure that connector always gets properly closed.

**Comment by popravich** [comment]
@amfarrell, you can use connector with `ClientSession` and it will close the one properly.
