### ISSUE TITLE
ProxyConnector Documentation update

### ISSUE THREAD

**Issue by apiszcz** [aio-libs/aiohttp#1283]
http://aiohttp.readthedocs.io/en/stable/client_reference.html?highlight=connector

The example shown in the documentation may have an error.

Should, conn ==  be conn =  ?
# 

conn == ProxyConnector(proxy="http://some.proxy.com")
session = ClientSession(connector=conn)
async with session.get('http://python.org') as resp:
    assert resp.status == 200

**Comment by asvetlov** [comment]
Fixed by b16c6f7
The modern code shouldn't use `ProxyConnector` anyway.
