### ISSUE TITLE
broken interface for response.url

### ISSUE THREAD

**Issue by wumpus** [aio-libs/aiohttp#1292]
The docs say that response.url is a string, but, it's currently yarl.URL ... I see that the conversion to using yarl is new?

While I'm in there, can I note that response.host is useless, because it doesn't have a port? At best it's a misleading interface.

**Comment by asvetlov** [comment]
Docs reflects the latest release but `response.url` became a `yarl.URL` in master only.
Maybe it's wrong idea and `yarl.URL` property should have own name.
I didn't polish the API yet.
Suggestions? `resp.url_obj` looks ugly.

Agree about `host`.

**Comment by wumpus** [comment]
Changing the interface after 1.0, not so nice!

I agree resp.url_obj is a little ugly, but I can't think of a better name. I do like the idea of access to an object, because I have a crawler which sometimes spends a lot of cpu time manipulating urls.

**Comment by asvetlov** [comment]
Fixed by #1295
