### ISSUE TITLE
Pypi missing 1.0.4 release.

### ISSUE THREAD

**Issue by alunduil** [aio-libs/aiohttp#1298]
## Long story short

Looks like the 1.0.4 release wasn't uploaded to pypi.  I'd prefer to stay in sync with pypi in the ebuild definition.
## Expected behaviour

Release tarball is available via pypi.
## Actual behaviour

Release tarball is not available via pypi.
## Steps to reproduce

wget 'https://pypi.python.org/packages/source/a/aiohttp/aiohttp-1.0.4.tar.gz'
## Your environment

aiohttp-1.0.4, Gentoo Linux, no proxy.

**Comment by asvetlov** [comment]
It was my fault as release manager.
There is no 1.0.4 release but there is a record for it and git tag.
Basically 1.0.3 and 1.0.4 are the same.
After merging #1297 I'll publish aiohttp==1.0.5

**Comment by asvetlov** [comment]
aiohttp 1.0.5 released
