### ISSUE TITLE
request that StaticRoute has the option to follow symlinks

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#1299]
Currently `.resolve(), relative_to()` [here](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web_urldispatcher.py#L399-L400) causes `ValueError` to be raised if the path is a symlink to a file outsite the directory and 404 is returned.

Would be good if there was a a way to get `StaticRoute` follow symlinks, obviously default to false.

**Comment by asvetlov** [comment]
You are asking for breaking security sandbox :)
But I'm ok with it unless the requested behavior is off by default.

**Comment by samuelcolvin** [comment]
Yes, I think it would be ok if it's off by default. Same as apache and nginx.

**Comment by asvetlov** [comment]
PR is welcome :)

**Comment by samuelcolvin** [comment]
will do.

A few of related extensions to `StaticRoute` which I would suggest:
- `/path/to/dir` serves `path/to/dir/index.html` if it exists
- `/path/to/file` serves `path/to/file.html` if it exists - this is slightly less standard.
- `/path/to/file` serves `/path/to/file` as `content-type: text/html` if `file` starts with `<!DOCTYPE` - not a convertion but would be useful where there's no easy way to set file metadata like content type. **Update:** This is perhaps a less good idea as it would mean opening every file without an extension twice: once to check first line, once for `sendfile`. Also "clean urls" can be accomplished with the above options.

Example [here](https://github.com/samuelcolvin/aiohttp-devtools/blob/1ea5b74aed8febad481a5ff53182bc9985758d31/aiohttp_devtools/runserver/serve.py#L251-L274) of the first two.

I can do on the same PR, or a new PR or create a new issue to discuss?

**Comment by asvetlov** [comment]
`index.html` should be optional -- now we display a directory index if `show_index=True`.
`file->file.html` convention looks harmless but should be optional too.
The third option is really strange.

Anyway, please add these extensions in separate PR.

**Comment by samuelcolvin** [comment]
Will do, third option is available with S3 if you set the content-type metadata on the file which is why I suggested it.

Will do PRs when I have a chance.

**Comment by asvetlov** [comment]
File system has no place for metadata.
Let's don't invite semi-working  strategy for this.
`<!DOCTYPE` is available for html pages only, it's not hard to name a file like `fname.html` and file type will be detected by file extension.
For other resources (images, js/css files etc) content type should be autocalculated by `mimetypes.guess_type` anyway and `FileSender` does this call.

**Comment by asvetlov** [comment]
Fixed by #1327
