### ISSUE TITLE
Make test suite passed on python 3.6 and default

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1302]
Right now several tests are failed with errors like 'Mock object is not iterable' etc.

It should be fixed.

For reproducing the problem uncomment `3.6-dev` and `nightly` python versions in `.travis.yml` and create a PR. Or just run test suite on python 3.6 beta.

**Comment by izhun** [comment]
Is it still actual?

**Comment by asvetlov** [comment]
No
