### ISSUE TITLE
Client Tracing

### ISSUE THREAD

**Issue by hynek** [aio-libs/aiohttp#1309]
Go 1.7 added [tracing](https://blog.golang.org/http-tracing) to its http client which I find quite intriguing:

> The collected information can be used for debugging latency issues, service monitoring, writing adaptive systems, and more.
> # HTTP events
> 
> The httptrace package provides a number of hooks to gather information during an HTTP round trip about a variety of events. These events include:
> - Connection creation
> - Connection reuse
> - DNS lookups
> - Writing the request to the wire
> - Reading the response

Is that something you’d find a good fit for aiohttp?

**Comment by asvetlov** [comment]
Brilliant idea.
Perhaps aiohttp signals could be reused for hooks implementation

**Comment by thehesiod** [comment]
btw in a sorta related note I'm adding this to DataDog in this PR: https://github.com/DataDog/dd-trace-py/pull/294

**Comment by asvetlov** [comment]
If you want to pick up the issue (very complex task btw but we can eat an Elephant piece by piece) you are welcome. 
It could not only avoid patching aiohttp code by DataDog but is very useful for other aiohttp users.

**Comment by asvetlov** [comment]
Close for sake of #2313
