### ISSUE TITLE
app.startup() not documented and not called automatically

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#1313]
Currently if you register co-routines to run "on startup" with `app.on_startup.append(foobar)` you need to make sure `startup()` is called manually, like in `web.run_app`. This should be documented.

**Comment by asvetlov** [comment]
`on_startup` is not special.
The same behavior is for `on_shutdown` and `on_cleanup` signals.
Do you really want to document it?
If yes -- provide a Pull Request please.

**Comment by f0t0n** [comment]
@samuelcolvin I don't get your confusion here.

It's already called in the [`web.run_app()`](https://github.com/KeepSafe/aiohttp/blob/v1.0.5/aiohttp/web.py#L309) and in the [`GunicornWebWorker.run()`](https://github.com/KeepSafe/aiohttp/blob/v1.0.5/aiohttp/worker.py#L39).

So if you run the instance of the application using either Gunicorn or `web.run_app()` the `Application.startup()` will be called.
