### ISSUE TITLE
Per-app compression option

### ISSUE THREAD

**Issue by silverwind** [aio-libs/aiohttp#1321]
## Long story short

Currently, there seems to be no way to enable compression for methods like `json_response`, while it'd be especially beneficial for performance to compress big JSON responses. While it's possible to compress JSON responses using the low-level API, one has to jump through a few hoops to do so. I'd imagine a app-wide switch to enable opportunistic compression on all responses.
## Expected behaviour

`app.enable_compression(force=None)`

**Comment by asvetlov** [comment]
I don't think it's good idea. Enabling something _globally_ may lead to confusing behavior very easy.
Moreover, adding `compression` parameter to `Response` ctor and `json_response` function to use it on per-request basis doesn't make much sense.

Compression should be controlled by client.
If client informs server about accepted compression via `Accept-Encoding` header aiohttp web server applies this compression automatically.

**Comment by silverwind** [comment]
> Compression should be controlled by client.

Yes exactly that's what I mean by opportunistic. But to my knowledge, `aiohttp` never compresses responses unless `.enableCompression()` is called on the response, even in the presence of supported `Accept-Encoding` request headers.

> Enabling something globally may lead to confusing behavior very easy

I think it's reasonably to enable it globally if the negotiation works reliably. For comparison, in the [Express framework](https://github.com/expressjs/compression), I can simply `app.use(compression())`, and the library handles the rest.

**Comment by fafhrd91** [comment]
is there value to do compression on aiohttp side? usually nginx is in front of application.

**Comment by silverwind** [comment]
While I generally agree and in fact do run most of my HTTP servers behind a reverse proxy, having resonable performance standalone is still valuable to me.

**Comment by asvetlov** [comment]
Digging into the subject deeper I'm inclining to don't implement global compression in aiohttp.
The reason is: no clean rule for deciding where do compression and where don't.

Say, [NGINX](http://nginx.org/en/docs/http/ngx_http_gzip_module.html) has complex options for controlling compression -- and these options are not shrinked to simple boolean parameter.

From other hand the issue could be solved by custom middleware (with settings and behavior which are satisfactory for concrete use case).
