### ISSUE TITLE
Performance decreasing while using many coroutines

### ISSUE THREAD

**Issue by skavans** [aio-libs/aiohttp#1354]
I need to crawl really many (about half a billion) different URLs (each is on the different domain). I've decided to use `asyncio` and `aiohttp` to do this. I want to crawl as fast as my network channel can.

```python
#!/usr/bin/python3.5

import asyncio
import aiohttp
import traceback
import sys
from datetime import datetime
import socket
from aiohttp.resolver import AsyncResolver
from codecs import open
from concurrent import futures

queue = asyncio.Queue()

COROS = int(sys.argv[1])
LINES = int(sys.argv[2])
TIMEOUT_SEC = int(sys.argv[3])
INPUT = sys.argv[4]

done = 0
errs = 0
timeouts = 0

connector = aiohttp.TCPConnector(verify_ssl=False, limit=None, 
								 family=socket.AF_INET, 
								 resolver=AsyncResolver(nameservers=["127.0.0.1"]))
client = aiohttp.ClientSession(connector=connector)

for u in open(INPUT).readlines()[:LINES]:
	queue.put_nowait(u.strip())

async def crawl():
	global done, errs, timeouts
	while not queue.empty():
		try:
			url = queue.get_nowait()
			with aiohttp.Timeout(TIMEOUT_SEC):
				async with client.get(url) as r:
					await r.read()
			done += 1
			# print(done)
		except futures._base.TimeoutError:
			timeouts += 1
		except Exception as e:
			# print(traceback.format_exc())
			errs += 1


loop = asyncio.get_event_loop()

start = datetime.now()
loop.run_until_complete(asyncio.wait([crawl() for _ in range(COROS)]))
print('done in', (datetime.now() - start).total_seconds())

print ('ok={} errors={} timeouts={} timeout_percent={}%'
	   .format(done, errs, timeouts, round((float(timeouts)/(done+errs+timeouts))*100), 2))
client.close()
```

I use a unlimited TCPConnector instance here together with AsyncResolver to do things faster. But first trouble I face with is that increasing the coroutines count benefits only for a some limit (e.g. 500) and the following increasing does not benefit in crawling speed but extremely increase the timeout errors count (this is the second trouble).

Here is the output of script with input of real different domains URLs:

```bash
user@localhost:~$ python3.5 aio.py 100 2000 5 urls
done in 24.048247
ok=1924 errors=8 timeouts=68 timeout_percent=3%

user@localhost:~$ python3.5 aio.py 300 2000 5 urls
done in 12.273534
ok=1856 errors=8 timeouts=136 timeout_percent=7%

user@localhost:~$ python3.5 aio.py 500 2000 5 urls
done in 11.461395
ok=1702 errors=9 timeouts=289 timeout_percent=14%

user@localhost:~$ python3.5 aio.py 1000 2000 5 urls
done in 9.432362
ok=1468 errors=9 timeouts=523 timeout_percent=26%

user@localhost:~$ python3.5 aio.py 2000 2000 5 urls
done in 5.650822
ok=966 errors=7 timeouts=1027 timeout_percent=51%
```

You can see that increasing the coroutines count from 100 to 200 decrease the execution time about 1.5 times but the following increasing makes the script execution slower and increase the error percent.

I understand well that it can be the side-effect of event loop running so the coroutines can not get interpreter in time but it is strange that it is at the 500 coroutines already.

**Comment by asvetlov** [comment]
You could try uvloop.
Also python 3.6 has speedups for asyncio performance.

**Comment by asvetlov** [comment]
Hmm.
I've re-readed your code.
Scheduling too many requests in the same line is counter-productive.
You should create a limited pool of fetchers and spread network activity between them.

For inspiration lease take a look on this example: https://github.com/aosabook/500lines/tree/master/crawler
