### ISSUE TITLE
Extending UrlDispatcher and passing app object

### ISSUE THREAD

**Issue by toumorokoshi** [aio-libs/aiohttp#1365]
## Long story short

The new version of aiohttp supports subapps. Which is awesome! Unfortunately, it makes extending UrlDispatcher a little tricky.

I've previously been extending the UrlDispatcher for my extension (I add a way to mount my api methods):

https://github.com/toumorokoshi/aiohttp-transmute/blob/master/aiohttp_transmute/url_dispatcher.py#L8

Example:

https://github.com/toumorokoshi/aiohttp-transmute/blob/master/aiohttp_transmute/tests/example.py#L42

However, this breaks in the newest version, due to the new app object requirement. Unfortunately, since I have to pass the router into the app object during creation, I don't have the app object to properly instantiate the Router.

## Expected behaviour

I'm thinking something like this?

```
app = web.Application(loop=loop, router_class=TransmuteUrlDispatcher)
```

Then the code for app would look something like:

```
    def __init__(self, *, logger=web_logger, loop=None,
                 router=None, router_class=web_urldispatcher.UrlDispatcher,
                 handler_factory=RequestHandlerFactory,
                 middlewares=(), debug=False):
        if loop is None:
            loop = asyncio.get_event_loop()
        if router is None:
            router = router_class(self)
        assert isinstance(router, AbstractRouter), router
```

## Actual behaviour

Unable to instantiate the router properly. I'm passing in app=None right now, but that'll break for subapps.

I'm also open to alternative approaches to what I'm trying to do (mount custom routes, and then keep a dictionary that I use later for documentation).

I can do the PR for this too, if there's agreement on the approach.

Thanks!

**Comment by asvetlov** [comment]
`UrlDispatcher` was not designed for extending.
Use it as is -- or implement `AbstractRouter` from scratch.
Regarding to `aiohttp-transmute` I suggest another design:
1. Push transmute context and swagger info into `web.Application` as `app['AIOHTTP_TRANSMUTE_CONTEXT']` for example.
2. Implement `add_transmute_route(app, *args)` top-level function for registering route in given application.

**Comment by toumorokoshi** [comment]
ok, got it. Didn't realize that wasn't for inheriting.

I think i'll move forward with the top-level function and app values as you described. thanks!
