### ISSUE TITLE
Graceful shutdown can (I think) truncate connections that it shouldn't

### ISSUE THREAD

**Issue by njsmith** [aio-libs/aiohttp#1369]
The idea of graceful shutdown is that we finish sending out all existing responses before shutting down. But from code inspection, I think it can happen that in certain cases aiohttp will truncate a response, even though it could easily have finished within the time limit.

Specifically, the problem is, how do we know that we've actually finished sending the complete response body to the client? AFAICT there are two ways to do this in asyncio: (a) wait for a `connection_lost` callback, (b) call `await stream_writer.drain()`, *after* calling `stream_writer._transport.set_write_buffer_limits(0)`.

As far as I can tell, aiohttp calls `await stream_writer.drain()`, but without the crucial second step. Without this, `drain` can and will return while there is still unsent data buffered inside the event loop, and if we then proceed with shutting down this data can silently lost.

**Comment by asvetlov** [comment]
Fixed by #1478 
If data has not been sent after lingering timeout -- connection is stalled and should be aborted anyway.
