### ISSUE TITLE
pytest_pyfunc_call now broken with python 3.6b4+ and nightly

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#1371]
[This](https://github.com/python/cpython/commit/c8bb1ac8c59d0522845e0b3bd9157a18ced8831b) commit to python yesterday has broken [pytest_pyfunc_call](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/pytest_plugin.py#L33-L46) with the error

```
RuntimeError: Cannot run the event loop while another loop is running
```

Example of the failure [in travis here](https://travis-ci.org/samuelcolvin/aiohttp-devtools/jobs/173507111). 

I guess the default loop on the main thread needs to be stopped first?

**Comment by asvetlov** [comment]
No, it's not broken.
But your test is not correct: it is a coroutine which  starts a new loop by `check_app_factory` call: https://github.com/samuelcolvin/aiohttp-devtools/blob/master/aiohttp_devtools/runserver/main.py#L37

**Comment by samuelcolvin** [comment]
Thanks, sorry I was being dumb.
