### ISSUE TITLE
ClientOSError when trying to connect to certain hosts

### ISSUE THREAD

**Issue by Tsumiki-Chan** [aio-libs/aiohttp#1376]
## Long story short

When I try to connect to certain pages using aiohttp get or post I just get an ClientOSError (Cannot connect to host)

## Expected behaviour

The webpages should return their content.

## Actual behaviour

aiohttp is not able to connect to the host

```
[Errno 101] Cannot connect to host konachan.com:80 ssl:False [Can not connect to konachan.com:80 [Network is unreachable]]
[Errno 101] Cannot connect to host cykably.at:80 ssl:False [Can not connect to cykably.at:80 [Network is unreachable]]
```

## Steps to reproduce

- Make aiohttp try to connect to one of these hosts:
    - konachan.com
    - cykably.at

## Your environment

Python 3.5.2
aiohttp 1.0.5
Connection is made using a ziproxy proxy server

## Additional notes

Trying to connect using aiohttp 0.22.5 on the same setup is successfull and returns the expected behaviour.

**Comment by asvetlov** [comment]
Please try aiohttp 1.1

**Comment by Tsumiki-Chan** [comment]
Well, I can't atm as that will break other libs (in the current state)

See: https://github.com/Rapptz/discord.py/pull/384

**Comment by Tsumiki-Chan** [comment]
using aiohttp 1.1.1 together with yarl 07.0 works fine for me.
