### ISSUE TITLE
subapp url route without '/' not working

### ISSUE THREAD

**Issue by chrisWhyTea-zz** [aio-libs/aiohttp#1383]
## Long story short
I'm trying to use the aiohttp subapp router to split my application into smaller bits but the expected routes are not as pretty as expected 

I have the main application that runs 
`app.router.add_subapp('/api/v1', apiv1_app)`
and the subapp that runs
`apiv1_app.router.add_get('/', api_info)`

## Expected behaviour
using '/api/v1' url should call api_info

## Actual behaviour
doesn't call api_info only but using '/api/v1/' is calling it... sofar so good (makes sense because thats what i had written there ) but using
`api_app.router.add_get('', api_info)` (the get without '/') results in `ValueError: path should be started with /`

**Comment by asvetlov** [comment]
Thank you very much for report.
I'll fix the bug soon.

**Comment by asvetlov** [comment]
BTW I have a feeling that subapps documentation is not perfect -- at least I did it very quickly.
Maybe you might propose something?
Pull Request for docs would be awesome!

**Comment by chrisWhyTea-zz** [comment]
I can do that... it was a bit try and errorish ;D

**Comment by asvetlov** [comment]
Fixed by #1387 and aiohttp 1.1.3

**Comment by asvetlov** [comment]
`apiv1_app.router.add_get('', api_info)` is supported now

**Comment by asvetlov** [comment]
@jettify it might be interested to you
