### ISSUE TITLE
Problem with share cookie between requests

### ISSUE THREAD

**Issue by nodermann2** [aio-libs/aiohttp#1386]
The problem, I accidentally discovered when doing regular bot on aiohttp
1. make POST request
2. A website returns a 302, and returns a Set-Cookie header with the data to further authenticate the
3. The redirection occurs with these cookies
4. Returns 200 status code and a successful authentication
5. But when I print cookies, but these cookies weren't shared from 302 to last request (200)

I thought the problem with the website, but on the test server the problem persists, I created a test server to ensure that this is so

test_server.py
```
from flask import Flask, jsonify, redirect

app = Flask(__name__)


@app.route('/ok')
def index():
    return jsonify(code=200), 200


@app.route('/')
def cookie_insertion():
    redirect_to_index = redirect('/ok')
    response = app.make_response(redirect_to_index)
    # say that the cookies are set, make a redirect
    response.set_cookie('test_cookie', value='hello cookie')
    return response

  
if __name__ == '__main__':
    app.run(debug=True, host='localhost', port=5000)
```
test_request_302.py
```
import asyncio
import aiohttp


async def fetch(url):
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as resp:
            print('history', resp.history)  # cookies were set
            print('status', resp.status)
            print('cookie', resp.cookies)
            print(await resp.text())


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(fetch('http://localhost:5000/'))
```

Python 3.5.2
aiohttp 1.1.1 (pip install aiohttp)

**Comment by popravich** [comment]
See [aiohttp.ClientResponse.cookies](http://aiohttp.readthedocs.io/en/stable/client_reference.html#aiohttp.ClientResponse.cookies)
Last response's cookie attribute will contain value of `Set-Cookie` header.
The `index` endpoint doesn't set any cookies so `response.cookies` is empty.
You can check `ClientSession.cookie_jar` attribute to get all collected cookies.

**Comment by nodermann2** [comment]
I have not found cookie_jar into ClientSession, but I created a function to extract the cookies from history, I'll put it here if someone will be useful

```
def get_cookie_from_history(history, index=-1, as_header=False):
    history = history[index]
    cookie_dict = dict()
    if as_header:
        cookies = []
        for key, morsel in sorted(history.cookies.items()):
            cookies.append('%s=%s' % (key, morsel.value))
        cookie_dict['Cookie'] = '; '.join(cookies)
        return cookie_dict
    else:
        for key, morsel in history.cookies.items():
            cookie_dict[key] = morsel.value
        return cookie_dict
```
