### ISSUE TITLE
TestClient does not consume instance of yarl.URL

### ISSUE THREAD

**Issue by imbolc** [aio-libs/aiohttp#1389]
I think it would be more consistent to allow it working with `yarl.URL`. Eg because reversing url by `app.route` returns it. But now it can't because of `assert path.startswith('/')` in `TestServer.make_url()` method [here](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/test_utils.py#L81).

**Comment by asvetlov** [comment]
Would you provide a PR?

**Comment by imbolc** [comment]
Done :)

**Comment by asvetlov** [comment]
Fixed by #1391
