### ISSUE TITLE
Build chat server with aiohttp

### ISSUE THREAD

**Issue by deounix** [aio-libs/aiohttp#1390]
I'm trying to make chat server with aiohttp. I want to build this server with TLS/SSL.
My questions :

1. Is aiohttp good for big number of connections ? (Millions)
2. What should I use ? WebSocket ?

The Whole point is : Chat server that accept json packet like :

{"message": {"from": "from_user@domain.tld", "to": "to_user@domain.tld", "text": "Hi there"}}

Then send it to other users.

Thanks.

**Comment by asvetlov** [comment]
Yes, webocket is very widely used technology for building tools like chat.
aiohttp supports _a lot_ of parallel connections but millions are probably is too high value for single node regardless of chosen framework and programming language. Such massive highload could be achieved by cluster of machines only I believe.
