### ISSUE TITLE
Inconsistency in test_client request and response urls

### ISSUE THREAD

**Issue by imbolc** [aio-libs/aiohttp#1407]
Now `test_client` takes relative url in request, but returns an absolute one in response. And only way I found to check if response url is matched with some named url is:
```
url = client.app.router['name'].url_for()
r = await client.get(url)
assert r.url.path == url.path
```
The `.path` in assert statement looks confusing and redundant for me. I think client response should return relative url as it takes it. But also we should consider the case of redirecting to external url and keep possibility to check absolute url. Could we add something like `r.rel_url`? Or maybe enhance router with something like `router.url_for(_absolute=True)` or even `router.abs_url_for()`? What do you think?

**Comment by asvetlov** [comment]
`resp.rel_url` looks useless and confusing because response may be redirected to other host.
Regarding to return absolute url from router -- it's impossible in general: hostname part becomes available only after getting request as `HOST` header. Router knows nothing about own host.

As alternative I suggest you the following check: `assert r.url == client.make_url(url)`

**Comment by imbolc** [comment]
And so  we have three different urls:
- relative `yarl.URL` with `router.url_for()`
- absolute `yarl.URL` with `resp.url_obj` and `client.make_url()`
- absolute string url with `resp.url`

Even you made a mistake in the last message, it should be `assert r.url_obj == client.make_url(url)` :)

**Comment by asvetlov** [comment]
Yes, sorry.
`resp.url` should keep existing implementation for sake of backward compatibility.

Relative/absolute URLs dichotomy was present from very beginning.

**Comment by Kentzo** [comment]
@asvetlov are there plans to introduce deprecation policy for interface and behavior? I'm watching aiohttp-related repos for some time and it's not the first time "backward compatibility" is used as an argument.

**Comment by asvetlov** [comment]
`resp.url` was deprecated by aiohttp 1.1 release at Oct 2016.
Deprecation period is a year and half.
Thus this property will be removed most likely at Apr 2018.
After that we could reuse this beautiful name again by making it an alias for `url_obj` for example.

**Comment by imbolc** [comment]
`test_client` requests methods consume only relative `yarl.URL` and strings which start with '/' for now. Why wouldn't we consider another strings as urlnames? And then if we add `url_name` into response it would look like

```
resp = await client.get('my_resource')
assert resp.url_name == 'my_resource'
```

It would work for static routes only, but I think it's most common case. For dynamic routes it would be just a little verbose:

```
url = client.app.router['my_resource'].url_for(...)
resp = await client.get(url)
assert resp.url_name == 'my_resource'
```

**Comment by asvetlov** [comment]
`client.get()` returns a vanilla `aiohttp.ClientResponse` which has no `.url_name`.
I don't want to add `.url_name` to `aiohttp.ClientResponse` nor return derived class from test client's call.
