### ISSUE TITLE
message argument is not optional in BadHttpMessage

### ISSUE THREAD

**Issue by simonklb** [aio-libs/aiohttp#1408]
## Long story short

From the looks of it, you should be able to use, for example, the HttpBadRequest exception without specifying an error message seeing it has a default error message set. But since it's extending the BadHttpMessage exception which requires a message that is currently not possible.

## Expected behaviour

Raising BadHttpMessage() without a message.

## Actual behaviour

`TypeError: __init__() missing 1 required positional argument: 'message'`

**Comment by asvetlov** [comment]
I curious why do you create an `HttpBadRequest` instance.
I pretty sure it is very internal class. User might want to catch it but never throw.

**Comment by simonklb** [comment]
Probably because I haven't read the documentation properly. :)

What is the proper way to create an error response?

Here's a snippet of how I'm currently doing it:

```
    async def set_desired_size(self, request):
        data = await request.json()
        try:
            self.pool.set_desired_size(data["desiredSize"])
            return web.Response()
        except KeyError:
            raise HttpBadRequest("")
```

**Comment by asvetlov** [comment]
`raise web.HTTPBadRequest()` 
See http://aiohttp.readthedocs.io/en/stable/web.html#exceptions

**Comment by simonklb** [comment]
Ah, sorry! Just out of curiosity - how come you expose the HttpBadRequest at the top level module?

**Comment by asvetlov** [comment]
It's a long story.
Short answer is: `HttpBadRequest` appeared before `aiohttp.web`.
Maybe HttpBadRequest will be removed eventually (aiohttp 2.0?) but now we should keep it.
