### ISSUE TITLE
_sendfile_system incompatible with uvloop (epoll based)

### ISSUE THREAD

**Issue by mayfield** [aio-libs/aiohttp#1412]
## Long story short

_sendfile_system uses a dup() FD;  This causes problems with current uvloop;  See: MagicStack/uvloop#61

## Expected behaviour

CPU usage below 100%

## Actual behaviour

libuv gets stuck in a loop and consumes 100% CPU.

## Steps to reproduce

Use static file handler and uvloop to serve a large file over a slow link.  Something sufficient to cause BlockingIOError during `os.sendfile()`

## Your environment

Linux
Python 3.5.2
HEAD uvloop
HEAD aiohttp

**Comment by asvetlov** [comment]
I believe it should be fixed by uvloop itself.

**Comment by mayfield** [comment]
Yeah, i should have updated this.  It's fixed on uvloop 0.6.6.
