### ISSUE TITLE
Sec-WebSocket-Accept header case doesn't match RFC

### ISSUE THREAD

**Issue by willmcgugan** [aio-libs/aiohttp#1432]
## Long story short

We've recently uncovered a bug in a websocket client library, where it is incorrectly doing a case sensitive comparison on the ``Sec-WebSocket-Accept`` header.

The problem is that aiohttp is sending ``Sec-Websocket-Accept`` (note lower case S). This causes the clients to break.

I know the bug technically isn't in aiohttp, because http headers should be treated as case-insensitive. But would it be possible to change the case of the websocket headers to match the RFC exactly? Currently we can't switch to the new version of our server without breaking our android applications.

**Comment by fafhrd91** [comment]
You can create custom 'WebSocketResponse' class and override 'prepare' method

**Comment by willmcgugan** [comment]
Thanks. I'll give that a try.

All the same, I think it probably would be best to match the case. In the spirit of "be strict when sending and tolerant when receiving".

I was hoping it would be a quick fix, and I could PR. But it doesn't seem straight-forward with the multidict implementation.

**Comment by fafhrd91** [comment]
You can monkey patch 'HttpMessage.addHeader()'

**Comment by willmcgugan** [comment]
It doesn't seem as straight-forward as that. The problem is that the `headers` attribute is a `CIMultiDict`. Anything added to there will lose the case. And the constants in `hdrs.py` aren't strings, but `istr` objects.

I think I might be able to monkey patch `send_headers`. But a better solution may be to have a version of multidict that preserves the case without breaking the other semantics.

**Comment by asvetlov** [comment]
Maybe it's an option -- I don't know.
Another option is adding `raw_headers` to response (we have them in request already).

**Comment by asvetlov** [comment]
But, honestly, better to patch your client.

**Comment by willmcgugan** [comment]
@asvetlov Thanks for re-opening this one. Yeah, we are patching the client. But It will take a while for the apps to update.

I've forked aiohttp in the short term, and I've fudged the headers at the point where they are sent.

**Comment by fafhrd91** [comment]
i don't think we should add `raw_headers`, we would need to do this on protocol.py level.

**Comment by asvetlov** [comment]
It might be useful for sending malformed headers.
But, I agree, not the best solution for this particular case.
