### ISSUE TITLE
Using yarl.URL in request methods leading to wrong responses

### ISSUE THREAD

**Issue by playpauseandstop** [aio-libs/aiohttp#1433]
## Long story short

After 1.1 version all `str` URLs passed to `ClientSession.get` or other request methods converts to `yarl.URL` instances, which may lead to wrong responses as web-server may be configured in non-expected way.

## Expected behaviour

Request to https://pbs.twimg.com/media/CyX3YxlXAAYgu6c.jpg:large should results in 200 OK as if request done by browser or curl.

## Actual behaviour

Request to https://pbs.twimg.com/media/CyX3YxlXAAYgu6c.jpg:large results in 404 Not Found.

## Steps to reproduce

```python
import asyncio

from aiohttp import client
from yarl import URL


async def main(loop):
     async with client.ClientSession(loop=loop) as session:
         # Request will succeed, as URL is "encoded"
         response = await session.get(URL('https://pbs.twimg.com/media/CyX3YxlXAAYgu6c.jpg:large', encoded=True))
         assert response.status == 200, response.status

         # Request will failed, as it tries to open,
         # https://pbs.twimg.com/media/CyX3YxlXAAYgu6c.jpg%3Alarge
         # which will return 404
         response = await session.get('https://pbs.twimg.com/media/CyX3YxlXAAYgu6c.jpg:large')
         assert response.status == 200, response.status


if __name__ == '__main__':
    try:
        loop = asyncio.get_event_loop()
        loop.run_until_complete(main(loop))
    finally:
        loop.close()
```

## Your environment

- Python 3.5.2
- aiohttp 1.1.5
- yarl 0.7.1

----

In total, I'm not sure what is a proper way to "fix" this. I found out a workaround for the problem, but from my point of view docs for [YARL and URL encoding](http://aiohttp.readthedocs.io/en/stable/whats_new_1_1.html#yarl-and-url-encoding) is not very trivial to found and [HTTP Client](http://aiohttp.readthedocs.io/en/stable/client.html) and [HTTP Client Reference](http://aiohttp.readthedocs.io/en/stable/client_reference.html) pages missed a direct reference that by default all strings will be encoded to canonical URL representation. And using strings with colons, spaces and other non-canonical characters may lead to wrong responses as remote web-server can be configured in non-expected way.

**Comment by asvetlov** [comment]
`:` is a valid symbol for path, I'll fix it in yarl.

Regarding to mentioning yarl in docs -- please make a patch

**Comment by asvetlov** [comment]
Fixed by upstream
