### ISSUE TITLE
Unclosed connections when using the Streaming API

### ISSUE THREAD

**Issue by PGryllos** [aio-libs/aiohttp#1435]
I am working on a simple proxy server. The requested page can be anything so the proxy has to be able to stream the results. When I am using the Streaming API though the connections remain open and the server produces those messages

> Unclosed connection
client_connection: Connection<('www.python.org', 443, True)>
Unclosed response
client_response: <ClientResponse(https://www.python.org/) [200 OK]> ...

Here is my server implementation

```python
import asyncio

import aiohttp
import aiohttp.server


class HttpRequestHandler(aiohttp.server.ServerHttpProtocol):
    async def handle_request(self, msg, load):
        resp = await aiohttp.request('GET', msg.path)

        client = aiohttp.Response(
            self.writer, resp.status, http_version=(1, 1)
        )
        client.add_header('Content-Type', resp.headers['Content-Type'])
        client.add_header('Content-Length', resp.headers['Content-Length'])
        client.send_headers()

        async for data in resp.content.iter_chunked(1024):
            client.write(data)
        await client.write_eof()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()

    srv = loop.create_server(
        lambda: HttpRequestHandler(debug=True, tcp_keepalive=False),
        '0.0.0.0', '8080'
    )

    loop.run_until_complete(srv)
    try:
        loop.run_forever()
    except KeyboardInterrupt:
        pass
```

I am working with python3.5 and aiohttp 1.1.5

**Comment by PGryllos** [comment]
sorry I didn't realize I should be closing the connections manually or using `with`

**Comment by ClericPy** [comment]
### aiohttp/client.py
#### line_no: 328
```python
try:
    resp = req.send(conn)
    try:
        await resp.start(conn, read_until_eof)
    except BaseException:
        resp.close()
        conn.close()
        raise
except ClientError:
    raise
except OSError as exc:
    raise ClientOSError(*exc.args) from exc
```
Here may raise the uncatched exception: 
**Cannot write to closing transport <class 'concurrent.futures._base.CancelledError'>**
and then the **Unclosed connection** warning occurred.

traceback by add 

```python
except Exception as e:
    print(e, type(e), id(conn))
```
to the bottom of the former code snippet
