### ISSUE TITLE
Websockets in client mode use non-compliant/insecure RNG to select masking keys

### ISSUE THREAD

**Issue by njsmith** [aio-libs/aiohttp#1437]
aiohttp's websocket implementation in client mode appears to [use the `random` module to pick masking keys](https://github.com/KeepSafe/aiohttp/blob/7193a3c7639107584eb49281488231f9e1947023/aiohttp/_ws_impl.py#L323-L325). This violates RFC 6455, which says:

> The masking key is a 32-bit value chosen at random by the client.
> When preparing a masked frame, the client MUST pick a fresh masking
> key from the set of allowed 32-bit values. The masking key needs to
> be unpredictable; thus, the masking key MUST be derived from a strong
> source of entropy, and the masking key for a given frame MUST NOT
> make it simple for a server/proxy to predict the masking key for a
> subsequent frame. The unpredictability of the masking key is
> essential to prevent authors of malicious applications from selecting
> the bytes that appear on the wire.

This pretty much defeats the purpose of masking. Of course it isn't entirely clear how important masking is in the first place... it's used to avoid problems with dodgy "transparent" proxies that can be tricked into certain cache poisoning attacks, and no-one's entirely sure how common those are. If they do exist, though, then the effect is that if an aiohttp websocket client connects to a malicious server over a network that's running one of these dodgy proxies, then the malicious server can pretty take over how that proxy responds to arbitrary requests, thus hijacking everyone's web sessions.

[Autobahn has a similar issue](https://github.com/crossbario/autobahn-python/issues/758), and in the discussion there it was [suggested](https://github.com/crossbario/autobahn-python/issues/758#issuecomment-263138957) that using secure entropy for the masking keys is only important for browser-based clients. But this [appears to be wrong](https://github.com/crossbario/autobahn-python/issues/758#issuecomment-263343318): Python clients and browser-based clients appear to be equally vulnerable.

The solution is to use `os.urandom` to select masking keys. This is slightly slower, though probably not enough to matter; if it does prove to be a bottleneck then [there are ways to speed it up](https://github.com/crossbario/autobahn-python/issues/758#issuecomment-263464825).

**Comment by asvetlov** [comment]
Well, I don't care about it personally but Pull Request is welcome.

**Comment by oberstet** [comment]
FWIW, I agree with @asvetlov ;)

> If they do exist, ..

@njsmith I have never seen one or be shown one. Do you know one?

It would need to be broken in a very specific way. As commented on the Autobahn thread, even with your WS ping/pong trick to make Python WS client send arbitrary _payload_, you cannot get rid of the WS framing bytes on wire, and hence cannot control the bytes on wire fully.

**Comment by njsmith** [comment]
@oberstet: I haven't seen one! But this is totally meaningless, because I am just some random person who has absolutely zero access to data on what weird kinds of broken HTTP intermediaries are deployed in the wild. I'm pretty sure the RFC editors and browser vendors are aware of the complications you point out, and they seem to think it's a concern anyway...

**Comment by fafhrd91** [comment]
do we have any actionables for this issue? i don't care same as @asvetlov
