### ISSUE TITLE
[QUESTION] Does WebSocketResponse supports gzip transparent compression?

### ISSUE THREAD

**Issue by Marco-Sulla** [aio-libs/aiohttp#1440]
As title. Furthermore, is there a way to enable compression globally, without calling enable_compression() for each response?

**Comment by asvetlov** [comment]
1. No. #673 
2. No. #1321

**Comment by jzwinck** [comment]
The answer to the title question is now "Yes," thanks to #2273.  And you do not need to call `enable_compression()` on each response--it is done automatically if the client supports it.

**Comment by asvetlov** [comment]
Yep, the situation has changed since 2016 :)
