### ISSUE TITLE
Subscribe to Google group without gmail?

### ISSUE THREAD

**Issue by Kentoseth** [aio-libs/aiohttp#1441]
## Long story short

I am attempting to subscribe to the forum/g-group, but there is no email to which I can subscribe to the list.

## Expected behaviour

A subscription email like: aio-libs+subscribe@googlegroups.com

## Actual behaviour

Just this email is available: aio-libs@googlegroups.com

## Steps to reproduce

None

## Your environment

None-gmail address

**Comment by asvetlov** [comment]
What do you suggest?

**Comment by Kentoseth** [comment]
@asvetlov :

If Google Groups supports it, I suggest adding the option for subscription, via email, for the group.

(the other inconvenient suggestion is to run a mailing list)

I did some digging and found this:

[https://support.google.com/groups/answer/1067205?hl=en&visit_id=0-636162114488853001-3754545977&rd=1](https://support.google.com/groups/answer/1067205?hl=en&visit_id=0-636162114488853001-3754545977&rd=1)

**Comment by Kentoseth** [comment]
Are you guys moving forward with google-groups? 

The issue was just closed without discussion.

**Comment by kxepal** [comment]
@Kentoseth 
Alternatives? The only good ones I know are about to setup own ML service somewhere on own host, but this involves more questions to resolve:
- Which platform?
- Which hosting?
- Who'll own all of this, maintain and pay for? 
- etc.

And by taking into account current Google Groups activity, personally, I don't feel there is a really need for such major movements for now.

**Comment by asvetlov** [comment]
@kxepal +1
Google Groups admin page has no configuration for your problem.

**Comment by Kentoseth** [comment]
@kxepal 

fair enough. Just thought I'd bring it up in case it restricts participation.

Thanks.
