### ISSUE TITLE
Tests for demo polls app fail with "fixture 'event_loop' not found"

### ISSUE THREAD

**Issue by gyermolenko** [aio-libs/aiohttp#1459]
I try to run `pytest tests/test_integration.py` (from `../aiohttp/demos/polls` folder) and I get this error: "fixture 'event_loop' not found" . 

pytest-aiohttp plugin is installed.
`pytest --fixtures` command gives the list of available fixtures, and there is no `event_loop`.

**Comment by asvetlov** [comment]
Demo's tests are out of date.

The fix is very appreciated!

**Comment by gyermolenko** [comment]
This bug was fixed in `aiohttp-demos` repo

**Comment by asvetlov** [comment]
Cool! Let's close the issue
