### ISSUE TITLE
aiohttp server behind a reverse proxy: url_for() needs to emit the "real" URL

### ISSUE THREAD

**Issue by smurfix** [aio-libs/aiohttp#1467]
I am running an aiohttp server behind an SSL reverse proxy, so that https://real_server:80/foo/bar/baz is served by http://localhost:8080/bar/baz.

How do I teach my aiohttp server to return the "real" URL from url_for()?

(This is an enhancement issue for aiohttp's documentation. Also a feature request if this isn't yet possible. ;-)

**Comment by asvetlov** [comment]
`url_for()` returns a relative URL, isn't it?

**Comment by smurfix** [comment]
I'd rather have one option (or a small snippet of code) in my app to prefix the URLs with, than to be required sprinkle every url_for in my templates with {{host_prefix}} variables. That doesn't scale well, and if these are missing anywhere nobody will notice until it's deployed and customers complain.

aiohttp can already do nested applications, so I just need a way to specify the prefix manually.

**Comment by asvetlov** [comment]
aiohttp **does** prepending prefixes for nested application but doesn't automatic making these URLs absolute by adding scheme/host/port info.
E.g. for `/name/{to}` `url_for()` might return something like `/name/John` but never `https://example.com/name/John`. 
Relative URLs work pretty well inside a site but when a browser crosses site boundary it should use absolute ones.

You could specify [secure_proxy_ssl_header](http://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.Application.make_handler) and do something like `req.url.join(req.app.url_for('name'))` though.

**Comment by fafhrd91** [comment]
maybe we should introduce some general rewriting rules for url generation,
that would help with virtual hosts.

**Comment by asvetlov** [comment]
For virtual host we need something like `app.router.add_virtual_host('virtual.host.com', subapp)` I think.

Implementation looks to be pretty easy but I personally have issues with higher priority in my virtual todo list.

The same for subdomains.

**Comment by smurfix** [comment]
you don't want improvement issues to remain open?

**Comment by asvetlov** [comment]
What exact improvement are you talking about?
`.url_for()` should return a relative URL (as it does right now)

**Comment by asvetlov** [comment]
Hmm, maybe we need to resurrect aio-libs/aiohttp_jinja2#23 instead of changing `url_for()` behavior.
@smurfix what do you think?

**Comment by smurfix** [comment]
Something like that, though I'd need a configurable fixed prefix instead of calculating it from request params, as those might have been mangled by my front-end server – the URL in the response needs to be the pre-mangled version.

**Comment by asvetlov** [comment]
Sounds good.
Your PR for aiohttp_jinja2 is welcome.
I believe your issue should be solved by template renderer
