### ISSUE TITLE
[QUESTION] API-Hour vs Gunicorn?

### ISSUE THREAD

**Issue by Marco-Sulla** [aio-libs/aiohttp#1472]
In documentation there's an example about Gunicorn used as wsgi server. It's stated that it's easier but slower than using nginx directly as load balancer.

Anyone tried [API-Hour](https://pythonhosted.org/api_hour/tutorials/all_in_one.html) with nginx and benchmarked it? [I found one bench comparison](http://blog.gmludo.eu/2015/02/macro-benchmark-with-django-flask-and-asyncio.html) but it's a bit dated.

**Comment by asvetlov** [comment]
API-Hour is Gunicorn-based solution which works on top of aiohttp gunicorn support
