### ISSUE TITLE
`request` should be a public attribute/property of `ClientResponse`

### ISSUE THREAD

**Issue by garyvdm** [aio-libs/aiohttp#1482]
In order to debug my application, I wanted to inspect attributes of the request (e.g. headers). I could not find a way to do this, and ended up hacking the aiohttp code to do this. 

It would be nice if `request` was a public attribute/property of `ClientResponse` so that one could do this:

```
async with aiohttp.ClientSession(headers=...) as session:
    async with session.get('https://api.github.com/events', headers=...) as resp:
        print(resp.request.headers)

```

**Comment by asvetlov** [comment]
I don't want to expose `ClientRequest` class -- it has too many internal details which should be never touched by user.
But I'm ok with introducing `RequestInfo` named tuple with `url` and `headers` fields.

@garyvdm would you make a Pull Request?

**Comment by AraHaan** [comment]
hmm I could look at it then add tests for it if I could can get it to do such sometime.

**Comment by penguinolog** [comment]
https://github.com/aio-libs/aiohttp/pull/1733 - ClientResponse implementation (mistakenly used another bug id).

**Comment by fafhrd91** [comment]
#1733 is merged
