### ISSUE TITLE
Fix broken Cookies support

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1485]
Broken on Python 3.4 by #1453

https://travis-ci.org/aio-libs/aiohttp-session/jobs/184720151
https://travis-ci.org/aio-libs/aiohttp-security/jobs/184720027

**Comment by thehesiod** [comment]
looking

**Comment by fafhrd91** [comment]
maybe depends on python version? travis fails with python3.4.2 but you use 3.4.3

**Comment by thehesiod** [comment]
can someone add 3.4.3 to travis?  if it passes then I'm assuming it's a bug in 3.4.2

**Comment by jettify** [comment]
created PR to check 3.4.3 https://travis-ci.org/aio-libs/aiohttp-security/jobs/194945494

**Comment by jettify** [comment]
And tests are green!

**Comment by fafhrd91** [comment]
perfect!

**Comment by thehesiod** [comment]
yay, @jettify @asvetlov  is there a way to disallow 3.4.2 in setup.py?

**Comment by thehesiod** [comment]
I think I found the fix btw: http://bugs.python.org/issue22775, found from https://docs.python.org/3.4/whatsnew/changelog.html#python-3-4-3

**Comment by jettify** [comment]
Is any way to use http://bugs.python.org/review/22775/diff/13196/Lib/http/cookies.py to workaround this bug for 3.4.2 ? or should we care about 3.4.2 ?

**Comment by fafhrd91** [comment]
i'd say we do not care about 3.4.2, it is too old. 

@asvetlov ?

**Comment by jettify** [comment]
cc @popravich @kxepal

**Comment by fafhrd91** [comment]
anyone?

**Comment by fafhrd91** [comment]
closing. if anyone wants to talk about python3.4.2 support, please re-open.

**Comment by kxepal** [comment]
Late for the party. Support of 3.4.2 and 3.4 at all sounds without any reasons to do for me, but if people would like to contribute compatibility fixes without breaking or making support of modern Pythons complicated - that's fine.

**Comment by fafhrd91** [comment]
added back port for python3.4.2
