### ISSUE TITLE
 aiohtpp + yarl = Segmentation fault

### ISSUE THREAD

**Issue by ivan-is** [aio-libs/aiohttp#1492]
`aiohtp >= 1.1.0` (with `yarl`) gives **Segmentation fault** with this url: 
_http://www.baseballcolony.com/send.php?s=ahr0c_

 **Code sample for reproducing this error:**

```
import asyncio
import aiohttp

async def crawler(loop):
    url = 'http://www.baseballcolony.com/send.php?s=ahr0c'
    async with aiohttp.ClientSession(loop=loop) as session:
        async with session.get(url) as response:
            print(response.status)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(crawler(loop))
    loop.close() 
```

**Debug trace:**

`Program received signal SIGSEGV, Segmentation fault.
0x00007fffeb2e3c47 in __pyx_f_4yarl_8_quoting__do_quote (
    __pyx_v_val=__pyx_v_val@entry='j\x1a\udcf4q\udcda/\udc97g\udcee\udccb\x0ch\udccb\x18\udce4v\x1b\udce2\udcce\udccecom/y\udccepj\x16', 
    __pyx_v_safe="@:abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~!$'()*,;+&=/", 
    __pyx_v_safe@entry='@:', __pyx_v_protected=__pyx_v_protected@entry='/', __pyx_v_qs=__pyx_v_qs@entry=0)
    at yarl/_quoting.c:2273
2273	yarl/_quoting.c: No such file or directory.`

**Environment:**

```
OS: CentOS 7

uname -r

3.14.32-xxxx-grs-ipv6-64

pip3.5 freeze

aiodns==1.1.1
aiohttp==1.1.6
async-timeout==1.1.0
chardet==2.3.0
multidict==2.1.4
pycares==2.1.1
yarl==0.8.1
```

**Comment by asvetlov** [comment]
Should be fixed by yarl itself: aio-libs/yarl#41

**Comment by AraHaan** [comment]
hmm odd I never gotten an Segmentation fault from this and my Discord bot uses both rofl.

**Comment by asvetlov** [comment]
I don't know what's going on but I've reproduced crash
