### ISSUE TITLE
Separate run_app in init_app and start_app, for daemons

### ISSUE THREAD

**Issue by Marco-Sulla** [aio-libs/aiohttp#1497]
Now you can initialize the entire application using one function, `run_app()`. For daemons, it's useful to fork the main process as late as possible, since if the program will fail after fork, the service manager will not be informed and the daemon results as successfully started. For this reason I think it's useful to have at least a separation of `run_app()` in an init function and a start one, so you can run them separately if you want.

**Comment by asvetlov** [comment]
Running asyncio programs should not be forked.
Moreover, forking event loop instance is very error-prone.
Taking it into account I doubt if splitting `run_app()` makes any sense.
