### ISSUE TITLE
ClientSession is not aware of TestClient

### ISSUE THREAD

**Issue by saaj** [aio-libs/aiohttp#1499]
There's a `ResourceWarning` and message per test method in `test_utils.AioHTTPTestCase`. The following produces:
```python

from aiohttp import web, test_utils

class TestCase(test_utils.AioHTTPTestCase):

    def get_app(self, loop):
        return web.Application(loop = loop)

    def test1(self):
        pass

    def test2(self):
        pass
```

` python -m unittest test`

```
aiohttp/test_utils.py:212: ResourceWarning: Creating a client session outside of coroutine is a very dangerous idea
  **kwargs)
Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f5cbc921cc0>
.Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f5cbc921e48>
```

This is because `ClientSession` expects running IO loop.

Note that there's not only a warning, but also a call to `loop.call_exception_handler()` with mocked context, so this is impossible prevent this output with normal Python `warnings.filterwarnings` which is likely an warning design issue in the package. 

aiohttp 1.2.0

**Comment by AraHaan** [comment]
I am considering adding an optional arg to ``ClientSession`` that if set to ``False`` then no warning messages would be displayed. (at least upon Creation and Deletion) but only if set to False that is.

**Comment by asvetlov** [comment]
Fixed. `get_application()` now is recommended way for application creation but `get_app()` is still supported.
