### ISSUE TITLE
Add a recreate coroutine function to ClientSession().

### ISSUE THREAD

**Issue by AraHaan** [aio-libs/aiohttp#1503]
## Long story short

ClienSession does not have a coroutine function that allows to recreate a client session after it has been closed unless the class is reinitialized which can generate a Resource or a Memory leak if done enough times.

## Expected behaviour

A method that would abstract the whole needing to recreate it that actually calls the ``__init__`` method without reinitializing the class to invoke that method.

## Actual behaviour

``__init__`` method is only invoked when calling for a new instance which when done enough times makes a Resource / Memory leak (Spikes the Memory to python.exe considerably if done too much).

## Steps to reproduce

1. have a class that creates a client session similar to how discord.py does it.
2. close and recreate the client session just by overwriting the session variable in the class with a new instance every time.
3. Now after that is done now you have a problem with spiking memory usage that cannot be explained and can spike till there is no more memory left.

## Your environment

Python Version: 3.5.2 and 3.6.0
OS: Windows 7 Ultimate x64 Build 7601
Proxy: None, I run it all locally.

**Comment by asvetlov** [comment]
No. It's  very bad idea.
If you have memory leaks -- fix them without aiohttp spoiling.

**Comment by AraHaan** [comment]
cant be helped when it is from an library that runs it in a loop if the session is closed that my code uses.

**Comment by AraHaan** [comment]
hmm actually I got a better idea to make us both happy.

The change would be in the close method where it would delete it's own instance of the class when someone forget tos delete the instance itself after calling ``close()``

not sure if ``del self`` would do that or not but maybe it would help and then it would only be 1 line of changed code too.

This way it catches the people who forget to delete the old instance before creating a new instance of ``ClientSession`` when it is part of a variable they set it to.
