### ISSUE TITLE
here how to i get a dictionary from  "http://url/?a=1&b=2&c=3"

### ISSUE THREAD

**Issue by yjdwbj** [aio-libs/aiohttp#1509]
Hi. here is my code.please help how use aiphttp handle http GET request.

```sh
from aiohttp import web
import asyncio

@asyncio.coroutine
def AppLogin(request):

   ## here how to i get a dictionary {'uuid':'abc','key':"123456"}  from url "http://127.0.0.1:9000/iot/auth/app/?uuid=abc&key=123456" 
    return web.json_response({"req":str(get_params)})


@asyncio.coroutine
def create_app(loop):
    app = web.Application(loop=loop)
    app_resource = app.router.add_resource('/iot/app/auth/',name='applogin')
    app_resource.add_route('GET',AppLogin)
    return app
```
---
```
# curl "http://127.0.0.1:9000/iot/auth/app/?uuid=abc&key=123456" 
```

**Comment by rutsky** [comment]
@yjdwbj  Please ask usage questions on [support forum](https://groups.google.com/forum/#!forum/aio-libs).

With aiohttp>=1.1 You can get query string params using `request.rel_url.query`:

```
@asyncio.coroutine
def AppLogin(request):
    uuid = request.rel_url.query['uuid']
    ...
```

@asvetlov access of query parameters indeed not covered in [Server Tutorial](https://aiohttp.readthedocs.io/en/stable/tutorial.html)

**Comment by asvetlov** [comment]
@rutsky please create a PR for tutorial. This data should be available as `request.GET` too but I doubt if we should promote the property.
Maybe better to deprecate `.GET` and `.POST` and promote `.rel_url.query`, `.post()` and `.multipart()` as prime API?

**Comment by Skorpyon** [comment]
@asvetlov `.query_params`, `.data` and `.multipart` is good choice I think.

**Comment by fafhrd91** [comment]
we have `.query`, `.post()` and `.multipart`

**Comment by asvetlov** [comment]
@rutsky good point
@fafhrd91 let's keep the issue open until I'll fix tutorial by mentioning `request.rel_url.query` in it.

**Comment by fafhrd91** [comment]
@asvetlov I tried to use `.rel_url` and ergonomics is not good. I think we should provide 
`query`, `query_string`, etc as a first class attributes of request object.

**Comment by asvetlov** [comment]
N.P. we could remove deprecation marks and expose aliases for most useful properties.
I volunteer for PR for it if nobody object.

**Comment by asvetlov** [comment]
Done in aiohttp 2.1 I believe
