### ISSUE TITLE
Raise Custom Exceptions from web_ws.py, not RuntimeError

### ISSUE THREAD

**Issue by alexjc** [aio-libs/aiohttp#1511]
## Long story short

It's good practice for libraries to return distinct exceptions so they can be caught without fear of catching standard Python errors. In this case, the websocket implementation.

## Expected behaviour

Raise a custom `aiohttp.WebSocketError` (name of exception TBD).

## Actual behaviour

Currently `web_ws.py` throws standard `RuntimeError`.

## Steps to reproduce

Any websocket error throws RuntimeError, see source code.

## Notes

Happy to contribute a PR to fix this if you can suggest the exception name you prefer.

**Comment by fafhrd91** [comment]
i think it is good idea

**Comment by AraHaan** [comment]
Yeah, good catch. Also I think having the Error named ``WebsocketRequestError`` and have that return the Error codes from the website / webservice when it Errors like that.

**Comment by asvetlov** [comment]
No. If you take a look on `web_ws.py` carefully it uses `RuntimeError` as signal for programming error, e.g. sending date over closed websocket etc.
All these exceptions should never be caught by user code but software developer should fix the issue by changing source code.

P.S. 
Please count how many exceptions introduced by `asyncio` itself. Is it library built on bad practices? :)

**Comment by alexjc** [comment]
@asvetlov Thanks for the explanation! If these are programmer errors then I'd suggest using `assert` or `AssertionError` rather than `RuntimeError` (which docs define very roughly as "Raised when an error is detected that doesn’t fall in any of the other categories.") It was not clear to me that you consider this a programmer mistake.

Assuming this, my issues were relating specifically to the handling of CLOSE messages and internal `_closed` status. Are you 100% sure there are no race conditions that can occur between a close message being sent, the client's clean-up code, and other messages that try to send via the websocket?  Are client libraries expected to check if the websocket is not closing before every call to `send()`?

**Comment by fafhrd91** [comment]
removing RuntimeError exceptions from send_xxx methods makes sense.
