### ISSUE TITLE
Drop python3.4 support

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1513]
i think it is time

**Comment by AraHaan** [comment]
Yeah 3.4 has a coroutine bug which was fixed since 3.5 and 3.6 is actually better. However 3.4 users who use aiohttp on debian systems don't even have a final version of 3.5 so that is an issue their last version is 3.4 for now unless they can build from source.

**Comment by asvetlov** [comment]
It's very tempting decision but I'm thinking about python 3.5 support in major linux distributions.
Say, Debian includes Python 3.4 only in the latest Debian Jessie.

**Comment by AraHaan** [comment]
Yeah, which is sad that means they would have to manually compile 3.6 but it is good thing not hard to do.

Other than that if they can ``make install`` I think they would be fine with building 3.6 from source.

**Comment by asvetlov** [comment]
No, it's not an option.

IIRC Blind `sudo make install` on Debian effectively breaks OS down to non-bootable state :)

**Comment by mwfrojdman** [comment]
Debian Stretch ought to be released in the second half of 2017 if progress is as before. Seems it will include only 3.5, not 3.6 as freeze is around now.

**Comment by Rapptz** [comment]
I haven't dropped 3.4 support in my libraries for similar reasons. Not every distro comes with it and truthfully if there's a compatibility layer then the effort of supporting 3.4 and 3.5+ is not too steep.
