### ISSUE TITLE
Strange behavior when installing aiohttp on Python 3.6

### ISSUE THREAD

**Issue by AraHaan** [aio-libs/aiohttp#1538]
## Long story short

``_websocket.cp36-win32.pyd`` and ``_websocket.cp36-win_amd64.pyd``'s are not compiled upon installing on Python 3.6

## Expected behaviour

To be able to have those pyd files on Python 3.6 Like I have them on 3.5.

## Actual behaviour

on 3.5:
![ss 2017-01-10 at 07 30 33](https://cloud.githubusercontent.com/assets/15173749/21808198/ca7b2b40-d707-11e6-925e-42ec8371f83a.png)

on 3.6:
![ss 2017-01-10 at 07 31 01](https://cloud.githubusercontent.com/assets/15173749/21808202/d0c2aa64-d707-11e6-873a-28f53e20e833.png)

## Steps to reproduce

On Python 3.5 x64:

```cmd
python.exe -m pip install --target "E:\Users\Elsword\Desktop\DecoraterBot\Async\resources\Dependencies\win32-deps\3.5" --no-compile --upgrade aiohttp
```

On Python 3.5 x86:

```cmd
python.exe -m pip install --target "E:\Users\Elsword\Desktop\DecoraterBot\Async\resources\Dependencies\win32-deps\3.5\x86" --no-compile --upgrade aiohttp
```

On Python 3.6 x64:

```cmd
python.exe -m pip install --target "E:\Users\Elsword\Desktop\DecoraterBot\Async\resources\Dependencies\win32-deps\3.6" --no-compile --upgrade aiohttp
```

On Python 3.6 x86:

```cmd
python.exe -m pip install --target "E:\Users\Elsword\Desktop\DecoraterBot\Async\resources\Dependencies\win32-deps\3.6\x86" --no-compile --upgrade aiohttp
```

## Your environment

Python 3.5 & 3.6
aiohttp: v1.2.0
Windows 7 Ultimate x64 Build 7601

Note: The reason why I do both 32 and 64 bit installs is because I use both 32 and 64 bit python versions.

**Comment by fafhrd91** [comment]
i don't think this is related to aiohttp. re-open if you have any actionable
