### ISSUE TITLE
Use Homebrew to install python on OSX.

### ISSUE THREAD

**Issue by AraHaan** [aio-libs/aiohttp#1549]
## Long story short

On travis CI, OSX by default comes with homebrew. Because of that we can install python using something like this:

```yaml
      - if [[ "`uname`" == "darwin" ]]; then echo -n | brew tap AraHaan/python3; fi
      - if [[ "`uname`" == "darwin" ]]; then echo -n | brew install python342; fi
      - if [[ "`uname`" == "darwin" ]]; then echo -n | brew install python343; fi
      - if [[ "`uname`" == "darwin" ]]; then echo -n | brew install python344; fi
      - if [[ "`uname`" == "darwin" ]]; then echo -n | brew install python345; fi
      - if [[ "`uname`" == "darwin" ]]; then echo -n | brew install python346; fi
      - if [[ "`uname`" == "darwin" ]]; then echo -n | brew install python350; fi
      - if [[ "`uname`" == "darwin" ]]; then echo -n | brew install python351; fi
      - if [[ "`uname`" == "darwin" ]]; then echo -n | brew install python352; fi
      - if [[ "`uname`" == "darwin" ]]; then echo -n | brew install python353; fi
      - if [[ "`uname`" == "darwin" ]]; then echo -n | brew install python360; fi
```
Note: You might need to do all the testing and other stuff with 3.4.2 before using 3.4.3 unless you have it only install 3.6/3.5 and use venv for the for 3.4.x or any minor updates to 3.5.
For more info look at [AraHaan/python3](https://www.github.com/AraHaan/python3).

## Expected behaviour

For travis to use homebrew to install the python versions aiohttp needs for osx.

## Actual behaviour

Not using homebrew for this and disabled OSX for travis.

## Steps to reproduce

N/A

## Your environment

N/A, This is more along the lines of travis.

Note: Hopefully my changes would get merged into homebrew/core. I just need accurate information to be able to make it for homebrew.

**Comment by AraHaan** [comment]
Ok, I changed my mind about PRing homebrew/core take a look at [AraHaan/python3](https://www.github.com/AraHaan/python3).

**Comment by fafhrd91** [comment]
is there any actionable for this ticket?
