### ISSUE TITLE
Make it possible to add HTTP caching support

### ISSUE THREAD

**Issue by gsnedders** [aio-libs/aiohttp#1553]
It would be nice to make it possible to plugin some HTTP caching support (or, of course, just include it with the library!), especially for the client.

[CacheControl](https://cachecontrol.readthedocs.io/en/latest/) does this for requests, if some inspiration is required!

**Comment by fafhrd91** [comment]
scope of this plugin is large. we may need someone to build such library and if needed we can add additional extension points for `aiohttp`.

**Comment by asvetlov** [comment]
Caching is out of scope of aiohttp client api.
It's subject for another library built on top of aiohttp
