### ISSUE TITLE
POST request always follow redirects

### ISSUE THREAD

**Issue by ghost** [aio-libs/aiohttp#1557]
POST requests made using the aiohttp ClientSession always follow redirect as the `allow_redirects` attribute cannot be set for this method.

Other methods (GET/OPTIONS/HEAD) do support enabling/disabling of HTTP redirects.

Allowing redirects to be set on POST request allows one to retrieve header information (such as the redirect specific HTTP code)

**Comment by fafhrd91** [comment]
i can not find any code that prevents usage of `allow_redirects`, just pass `allow_redirects`

https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L404

**Comment by ghost** [comment]
My bad. Apologies. Misread the code
