### ISSUE TITLE
Support proxy headers for CONNECT requests

### ISSUE THREAD

**Issue by omribahumi** [aio-libs/aiohttp#1561]
Curl has been supporting this for a while (says [here](https://daniel.haxx.se/blog/2014/04/04/curl-and-proxy-headers/)), and it is also possible with `requests` by overriding the [proxy_headers()](http://docs.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter.proxy_headers) method of HTTPAdapter.

How hard would it be to implement this in `aiohttp`?

**Comment by omribahumi** [comment]
Looks like this is the part of the code I need to modify:
https://github.com/KeepSafe/aiohttp/blob/add3bd9e32b0712dfaa4466194e165145a46e6d4/aiohttp/connector.py#L646

I can even implement this in my own connector.

**Comment by fafhrd91** [comment]
seems you found solution

**Comment by dshoe1989** [comment]
Is there an official solution to this or is the suggested solution to just to create your own connector that extends TCPConnector and add support for it there?

**Comment by asvetlov** [comment]
As workaround you could extend TCPConnector right now.
But if you would make a Pull Request with adding `proxy_headers` parameter to `session.request()` API -- you are welcome.
Honestly I feel the request is rare so I have no motivation for implementing it myself.
