### ISSUE TITLE
Deprecation policy

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1575]
we need some formal way to deprecate api/features/etc.

my suggestion, lets create DEPRECATIONS.txt, and whenever we add deprecation warning to code, we add entry to this file with links to code, reasons, and removal date.

**Comment by fafhrd91** [comment]
@asvetlov @kxepal @popravich @jettify

**Comment by kxepal** [comment]
@fafhrd91 
I fear it will make too complicated procedure of understanding what to expect in a new release since unlikely people will read DEPRECATIONS.txt or else file after CHANGES.txt.

How about to pick [keepchangelog](http://keepachangelog.com/en/0.3.0/) way and describe all the things in a CHANGES.txt as more verbose as they deserve? Having one single place that describes all the changes, deprecations, migrations and mitigations for a specific release is a good idea.

**Comment by fafhrd91** [comment]
this file is not for people, it is for us. for example i have no idea when to remove some deprecated api. and we have a lot.

**Comment by kxepal** [comment]
That sounds like `warning.warn('will be removed in X.Y.Z, use method foo() instead. See also #123 on GH', DeprecationWarning)` and a related issue here for speciifed milestone would be enough. As a bonus, there would be a place to discuss surrounding problems, compatibility issues and the rest things. Once you decide to cut X.Y.Z. release, you'll have to close those tickets/PRs anyway so you wouldn't miss them and they wouldn't bloat a single text file.

**Comment by fafhrd91** [comment]
i still prefer one file, which i can just read and not browse gh.
sometimes we can not show deprecation warning, for example cookies back port for python3.4.2

**Comment by fafhrd91** [comment]
sure we will need to include info to changes about upcoming deprecations and removal of apis. but we can source it from one place.

**Comment by kxepal** [comment]
Well, it's up to you, I just see DEPRECATIONS.txt as an another source of manual work: you'll have to not forget apply those deprecations in time. The tagged/milestoned issues are better reminders with a little bit more features like discussion and feedback accumulation.

**Comment by AlJohri** [comment]
Maybe you can automatically generate deprecations.txt from running the test suite and capturing warnings or static code analysis for all deprecation warnings.

**Comment by fafhrd91** [comment]
we not always have deprecation warnings in-place, sometimes it is set of apis, for example wsgi.

**Comment by popravich** [comment]
I'm agree with @kxepal — properly tagged issues should work better.
In my opinion DEPRECATIONS.txt would look like issues filtered by that tag...
Anyway I'm ok with any choice.

**Comment by fafhrd91** [comment]
i hate open issues.
