### ISSUE TITLE
[doc] Finding the number of requests per second

### ISSUE THREAD

**Issue by nodox** [aio-libs/aiohttp#1579]
## Long story short

I looked over the documentation and I noticed there is no mention of how man `requests per second` aiohttp can make. How can I determine this information without having to calculate the RPS directly on my server using basic math?

**Comment by fafhrd91** [comment]
I do not understand your question? You want to know how calculate rps for your service or you just need rps from benchmark?

**Comment by nodox** [comment]
The following code sample makes 10k requests. I want to know the rate of requests per second. Does the below code make 10k requests per second? Or does it make 10k total requests at a different rate of RPS?

How do I determine how many requests per second are made by `aiohttp`?

```
import asyncio
import aiohttp

async def fetch(session, url):
  with aiohttp.Timeout(10, loop=session.loop):
      async with session.get(url) as response:
            return await response.text()

async def run(r):
    url = "http://localhost:3000/"
    tasks = []

    # Create client session that will ensure we dont open new connection
    # per each request.
    async with aiohttp.ClientSession() as session:
        for i in range(r):
          html = await fetch(session, url)
          print(html)


# make 10k requests per second ?? (not confident this is true)
number = 10000
loop = asyncio.get_event_loop()
loop.run_until_complete(run(number))
```

**Comment by fafhrd91** [comment]
```
>> time python ./test_client.py
real    0m1.361s
user    0m0.001s
sys     0m0.002s
```

**Comment by nodox** [comment]
I'm sure I understand how this helps me. Are all my requests being made in one call?

**Comment by fafhrd91** [comment]
yes

**Comment by fafhrd91** [comment]
concurrently

**Comment by nodox** [comment]
Is there a way to debug/profile the number of concurrent requests in real time?

**Comment by fafhrd91** [comment]
how do you see this should happen?

**Comment by nodox** [comment]
I'm not sure I understand your question. I am conducting asynchronous networking research with `aiohttp` and I need to confidently state how many concurrent requests `aiohttp` is capable of making. How would I determine the number of concurrent network requests?

**Comment by fafhrd91** [comment]
add simple counter in your code
