### ISSUE TITLE
normalize_path_middleware tests failures

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1583]
code is in https://github.com/KeepSafe/aiohttp/tree/normalize-middleware-fixes
travis build https://travis-ci.org/KeepSafe/aiohttp/builds/198126584

@argaen i need you to look into this problem

**Comment by argaen** [comment]
Sure, I'll have a look at it

**Comment by fafhrd91** [comment]
it would be cool if you could look into this problem sooner. i'd like to release aiohttp 1.3, but can not without this fix

**Comment by argaen** [comment]
I'll try to have a look at it today but if not for sure tomorrow

**Comment by argaen** [comment]
Mmmm I don't know why this behavior but with the test case of `//resource1//a//b`, the `request.path` variable contains the following:

```python
ipdb> request.path
'//a//b'
```

and that's why it fails. How did you fix the issue of the relative/absolute urls?

**Comment by fafhrd91** [comment]
i see. i will fix that. thanks

**Comment by socketpair** [comment]
This bug asso affects me (!)

**Comment by socketpair** [comment]
Tests have failed, but commit ended up in master. How is this possible? Is 1.3.1 considered stable release? I want to remind, that this version already landed in PIP.

**Comment by fafhrd91** [comment]
This was fixed befor 1.3.0 released

**Comment by socketpair** [comment]
Unfortunatelly, NO!. Tests are failed in 1.3.1. How can I help ?

**Comment by fafhrd91** [comment]
Submit PR or unit test.

**Comment by fafhrd91** [comment]
@socketpair i am planing to make 1.3.2 release today, could you provide unit test or PR?

**Comment by socketpair** [comment]
I have attached logs of failing tests. Please ask additional information if you need.
[bug.txt](https://github.com/KeepSafe/aiohttp/files/781345/bug.txt)

**Comment by fafhrd91** [comment]
hmm, interesting. it passes for me. check if you have latest yarl. also upgrade to 1.3.2, i added yarl requirements

**Comment by socketpair** [comment]
Is it safe to update yarl to latest version, and stay on aiohttp 1.2.0 ?

**Comment by fafhrd91** [comment]
Yes

**Comment by socketpair** [comment]
OK, I'm working in complex environment, so I will update yarl, and after that will try to re-build aiohttp with it.

**Comment by fafhrd91** [comment]
I would test before pushing to production

**Comment by fafhrd91** [comment]
Btw it doesn't matter for aiohttp 1.2, we added normalization middleware in 1.3

**Comment by socketpair** [comment]
Yes, I just wanted to update aiohttp and it did not pass tests...
