### ISSUE TITLE
(Broken) HTTP/1.0 server workaround for 'Connection: closed'?

### ISSUE THREAD

**Issue by mickeyl** [aio-libs/aiohttp#1584]
## Long story short

I need to communicate with a (broken|nonstandard) HTTP/1.0 embedded in a digital IP camera. This camera has a GET method and returns (text)lines of events, when they happen. The connection is supposed to be held open for hours and despite the server returning something like

```
HTTP/1.0 200 OK
Connection: closed
Content-type: text/plain; charset=utf-8
Last-modified: Thu, 01 Jan 1970 00:00:00 GMT

alarmimage=066267.3;timestamp=1486142859.602;date=2017-02-03;time=18:27:39;events=ima_51911cc4;eventlist="name=IMA 3,eventid=ima_51911cc4,type=IMA,sensortype=asen";alarmcounter=24704
```

the client is not supposed to close the connection here as more event lines will come eventually.

## Expected behaviour

I would have hoped that using the aiohttp streaming API the connection would not get closed

## Actual behaviour

aiohttp closes the connection, I guess the particular passage is in `protocol.py`:
```
        # read headers
        headers, raw_headers, close, compression = self.parse_headers(lines)

        if close is None:
            close = version <= HttpVersion10
```

Am I on the right track thinking it is aiohttp closing the connection? If so, how could I work around this
behavior?

Thanks!

**Comment by fafhrd91** [comment]
client should work already in your case
https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/protocol.py#L318

**Comment by mickeyl** [comment]
It doesn't, however upon reconsidering I think it does not make sense to use aiohttp in such a scenario or tweak it to support broken HTTP servers. I ended up directly talking to the server via asyncio, formulating my "HTTP" request in place. Works for me.
