### ISSUE TITLE
Drop aiohttp.get(), aiohttp.options(), aiohttp.head(), aiohttp.post(), aiohttp.put(), aiohttp.patch(), aiohttp.delete(), and aiohttp.ws_connect()

### ISSUE THREAD

**Issue by AraHaan** [aio-libs/aiohttp#1593]
``aiohttp.get()``, ``aiohttp.options()``, ``aiohttp.head()``, ``aiohttp.post()``, ``aiohttp.put()``, ``aiohttp.patch()``, ``aiohttp.delete()``, and ``aiohttp.ws_connect()`` are deprecated, use the ones in ``aiohttp.ClientSession()`` instead.

People using these deprecated versions had plenty of time to move to the ones in ``ClientSession`` instead.

Remove in v1.4.

**Comment by fafhrd91** [comment]
i am not sure about this.

**Comment by AraHaan** [comment]
thanks, Also I just realized I forgot to include to drop aiohttp.request since aiohttp.ClientSession().request basically replaces it as well. @fafhrd91 sorry about that.

**Comment by fafhrd91** [comment]
i removed `request()` from list, i do not want to remove it for now
