### ISSUE TITLE
aiohttp for long data processing

### ISSUE THREAD

**Issue by ghost** [aio-libs/aiohttp#1600]
i had code which process data for long time from 5 to 10 seconds.
How aiohttp cope with such situations(tornado is not good solution)? I am choosing the suitable framework.

**Comment by fafhrd91** [comment]
Should be fine, but only if your code is IO bound.

**Comment by samuelcolvin** [comment]
Have you considered setting up a worker to do these jobs so aiohttp can return and leave the job to happen outside the request-response cycle?

I built [arq](https://github.com/samuelcolvin/arq) for situation exactly like this, it plays nicely with aiohttp.
