### ISSUE TITLE
Explicitly require yarl versions <= 0.9.3

### ISSUE THREAD

**Issue by Gallaecio** [aio-libs/aiohttp#1632]
## Long story short

The example code at http://aiohttp.readthedocs.io/en/stable/client_reference.html fails with yarl > 0.9.3 due to https://github.com/aio-libs/yarl/issues/55

## Expected behaviour

The aiohttp package, that installed using pip, should prevent the installation of any yarl version with this issue, so far 0.9.4 and 0.9.5.1. Otherwise, 'pip install aiohttp' installs a broken aiohttp.

**Comment by fafhrd91** [comment]
Fixed with yarl 0.9.6
