### ISSUE TITLE
Client does not work with yarl==0.9.5

### ISSUE THREAD

**Issue by atomikin** [aio-libs/aiohttp#1635]
## Description

Client crashes [here](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client_reqrep.py#L73), because when yarl==0.9.5 installed url is BaseURL, not URL  
```
75  ->	assert isinstance(url, URL), url
76  	assert isinstance(proxy, (URL, type(None))), proxy
(Pdb) url
BaseURL('<url string>')
```
And the client obviously fails here. when I downgraded the yarl lib to lowest version from *setup.py* (0.8.1), it  started to work as usual. 
```
75  ->	assert isinstance(url, URL), url
76  	assert isinstance(proxy, (URL, type(None))), proxy
(Pdb) url
URL('<url string>')
```
## Expected behaviour

Client is expected to either freeze the yarl version or to handle BaseURL as well as URL.

**Comment by GDICommander** [comment]
If this can help, here is the new code in yarl that is probably causing the problem:

```
class URL(BaseURL):

    def __new__(cls, val='', *, encoded=False, strict=False):
        if isinstance(val, BaseURL):
            return val
        else:
            # This returns an instance of BaseURL.
            return super(URL, cls).__new__(cls)
```

**Comment by GDICommander** [comment]
The problem started to occur at yarl==0.9.4.
yarl==0.9.3 is fine.

**Comment by leynos** [comment]
Looks like a new version of yarl (0.9.6) is out that addresses the backwards incompatibility: https://github.com/aio-libs/yarl/releases/tag/0.9.6
