### ISSUE TITLE
aiohttp.CookieJar.filter_cookies does not accept string parameter

### ISSUE THREAD

**Issue by melkamar** [aio-libs/aiohttp#1636]
## Long story short

[Documentation](http://aiohttp.readthedocs.io/en/1.3.1/client.html#keep-alive-connection-pooling-and-cookie-sharing) states that it should be possible to filter cookies using URL as a plain string. However, that raises an exception:

```
filtered = session.cookie_jar.filter_cookies('http://httpbin.org')
```

## Expected behaviour

It should be possible to filter cookies by plain string.

## Actual behaviour

Using plain string causes an exception.

## Steps to reproduce

Follow example in [documentation](http://aiohttp.readthedocs.io/en/1.3.1/client.html#keep-alive-connection-pooling-and-cookie-sharing).

**Comment by fafhrd91** [comment]
merged
