### ISSUE TITLE
 Readme client example throws an AssertionError

### ISSUE THREAD

**Issue by cclauss** [aio-libs/aiohttp#1640]
## Long story short

[Readme client example](https://aiohttp.readthedocs.io/en/stable/client_reference.html) throws an AssertionError:
```
assert isinstance(url, URL), url
AssertionError: http://python.org
```

Client example runs.

## Actual behaviour

```
assert isinstance(url, URL), url
AssertionError: http://python.org
```

## Steps to reproduce

Run the code under Python 3.6

## Your environment

Up-to-date MacBook with Python 3.6

**Comment by fafhrd91** [comment]
fixed with yarl 0.9.6
