### ISSUE TITLE
Next release 2.0

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1642]
Low level part of aiohttp is completely re-written. And with 2.0 we can drop a lot of deprecated code, like wsgi and `.url_obj`. And speed gain can encourage developers to migrate to 2.0

On other hand nothing has changed in high level api.

**Comment by AraHaan** [comment]
Yeah, I say go for it,

**Comment by fafhrd91** [comment]
@kxepal @asvetlov

**Comment by kxepal** [comment]
Do we strictly follow semver or any else versioning policy?

Otherwise, according all the changes, I think 2.0 is a good one to reflect all of them.

What's the schedule for a new release?

**Comment by fafhrd91** [comment]
i am targeting first week of the march.

i still need to add tests for pipelining and exception handling in pipelining mode. also we need to think what to drop and what to just deprecate

**Comment by kxepal** [comment]
Cool. I'll revisit multipart module then. It strongly need in a refresh.

**Comment by asvetlov** [comment]
We shouldn't drop deprecations too fast.
I tried to keep 1.5 year deprecation period.
1 year is shortest value from my point of view.
Otherwise support the code which is built on top of aiohttp is nightmare -- people don't like to be unable running half year old codebase with fresh aiohttp version.

**Comment by kxepal** [comment]
With such strategy calendar versioning would be perfect. Things that are deprecated in 16.03 will be removed not before 17.03.

**Comment by asvetlov** [comment]
But sometimes we break own strategy for strong reasons, e.g. if bug fix cannot be done in backward compatible way.

I mean just pure calendar versioning doesn't work too.

**Comment by fafhrd91** [comment]
@asvetlov I agree with that, but we have opportunity to make nicer api right now which we probably won't have for long time. I am talking about things like `.url` vs `.url_obj` and that's why I need your help

**Comment by fafhrd91** [comment]
actually i'd just rename `ClientResponse.url_obj` -> `ClientResponse.url`, thats annoys me a lot :)

everything else seems good.

**Comment by fafhrd91** [comment]
Because of personal matter, I've decided to stop support and contribute to aiohttp project within KeepSafe organization.

I reverted all my changes that I've made for 2.0 release.

Regarding my changes I developed for last couple weeks, I may push to separate repository later.

**Comment by kxepal** [comment]
@fafhrd91 
What happened? Is aiohttp get moved to aio-libs organization?

**Comment by fafhrd91** [comment]
I am not with Keepsafe, I do not have any influence on this matter

**Comment by fafhrd91** [comment]
I moved all my code to https://github.com/fafhrd91/aiohttp
