### ISSUE TITLE
Pure Python version is broken

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1646]
After introducing new parser aiohttp is not available in pure python version.

All current releases support fallbacks if Cython optimization is not available.
I believe it's good practice.
At least CPython itself follows it in Standard Library for strong reasons.
The most important one is seamless support of alternative interpreters (read PyPy).

PyPy will be capable of running asyncio code in a year (even now master branch has limited support for it).
Keeping pure python http parser is very important from this perspective.

Could we save `parsers.py` with running tests on both parser versions?

**Comment by fafhrd91** [comment]
We run tests on Travis with extensions disabled. Also I am workin on converting `tests_http_parser.py` to pytest, new tests works with both parsers

**Comment by fafhrd91** [comment]
https://github.com/KeepSafe/aiohttp/blob/master/tests/test_http_parser.py#L39

**Comment by asvetlov** [comment]
Aaah, sorry.
I still not very familiar with your latest changes.
Looks perfect!
