### ISSUE TITLE
request.files in addition to request.data

### ISSUE THREAD

**Issue by ilkarman** [aio-libs/aiohttp#1651]
It seems the only way to add files to a request with aiohttp is by referencing them in the data parameter. However this becomes problematic when you have an API that expects to see something in 'files', not 'data.

For example, this works (using requests):
```
files = {'imagefile': open(fname, 'rb')}
requests.post(url, files=files)
```
However this doesnt:
```
files = aiohttp.FormData()
files.add_field('imagefile', open(fname, 'rb'))
response = yield from s.request('post', url, data=files)
```

**Comment by AraHaan** [comment]
So, what you need is an ``files=`` parameter for ``request``?

**Comment by AraHaan** [comment]
I created an PR that adds that parameter however I have not implemented the usage of it fully yet until I find out more on how requests works on it.

**Comment by AraHaan** [comment]
I have void the github repo for the requests package I am looking into how they implemented their ``files=`` on it to hopefully add it into aiohttp.

**Comment by AraHaan** [comment]
Ok, @iksteen I am working on it to where this would work for you (or at least something of the similar):

```py
files = {'imagefile': open(fname, 'rb')}
response = yield from s.request('post', url, files=files)
```

**Comment by fafhrd91** [comment]
i do not think `files=` is good idea. 

maybe something like ```aiohttp.request(data=FormData(File('file.name'), File(fileObject, filename=''), Stream(streamReader)))``` etc

**Comment by AraHaan** [comment]
@ilkarman doe's @fafhrd91 comment help fix this issue?

**Comment by asvetlov** [comment]
IIRC we had `files` param but it was too ambiguous.
Let's think about API changing very carefully.
Personally I feel a need for sleeping on it before next discussion iteration.

**Comment by fafhrd91** [comment]
I agree, we need to think about this api carefully. I envision some `UploadItem` interface that we can use as `data` value or as argument to `FormData` which in turn can implement `UploadItem` interface. it has to support sizable/unsizable stream types. also we should be able to use it in `aiohttp.web` as well.

**Comment by fafhrd91** [comment]
better name is `PayloadItem`

**Comment by fafhrd91** [comment]
@asvetlov let's move conversation to #1172
