### ISSUE TITLE
Change `ClientResponse.url` to `yarl.URL` instance

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1654]
Deprecate `ClientResponse.url_obj` attribute

**Comment by fafhrd91** [comment]
done

**Comment by asvetlov** [comment]
@fafhrd91 I should say again: you are running too fast in dropping deprecated code.
`url_obj` was introduced in aiohttp 1.1 which was released 2016-11-03
The change is 4 months only!
I suspect that many your changes suffer from similar problems.

P.S. I highly respect your contribution but please don't be so aggressive in dropping old styled API.
P.P.S. I would review the changes before next release. Have no time for it at weekend but I promise to spend a couple hours per day at least starting from next week.

**Comment by fafhrd91** [comment]
I was careful about api compatibility. But I am bullish about url_obj, it is so ugly. Also it is not big change, just replacing `resp.url` with  `str(resp.url)`. We have this opportunity with 2.0, I do not know when we get another version bump. Also I don't think people read deprecation warnings

**Comment by fafhrd91** [comment]
changed in master
