### ISSUE TITLE
It is not possible to send pre-chunked stream

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1655]
Client code automatically enables chunking if headers contains `transfer-encoding: chunked`
So it is not possible to implement custom chunking encoding or send pre-chunked stream

**Comment by fafhrd91** [comment]
If `chunked` enabled,  `content-length` and `transfer-encoding` in headers should be forbidden

**Comment by fafhrd91** [comment]
@asvetlov @kxepal

**Comment by kxepal** [comment]
@fafhrd91
 Ok with `content-length` - IIRC spec explicitly forbids that, but isn't `chunked=True` in arguments and `transfer-encoding: chunked` in headers are synonyms? Or I miss something?

**Comment by fafhrd91** [comment]
If `transfer-encoding` is in headers we turn on chunking, and enable chunking on writer. But what if I want to chunk stream myself?

For content length we should raise exception if user pass it in headers and enables chunking

**Comment by fafhrd91** [comment]
also we have to honor `CONTENT-LENGTH` header

**Comment by fafhrd91** [comment]
fixed in 2.0
