### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by aleksey925** [aio-libs/aiohttp#1656]
I can not understand why the memory is not freed. The memory usage increases after each request is growing more and more.
https://gist.github.com/aleksey925/372f34f458c9f843d0fb8c579e530b7c

What could be the problem? This is a bug?

**Comment by fafhrd91** [comment]
Is it in mastrer?

**Comment by aleksey925** [comment]
This is the latest available release (1.3.2).

**Comment by fafhrd91** [comment]
I found leak, will release 1.3.3 version later today
Thanks!
