### ISSUE TITLE
Prefix all private modules with undescore

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1659]
`aiohttp` has the following *public* modules:
* `aiohttp` itself
* `aiohttp.web`
* `aiohttp.abc`

Let's hide all others like `aiohttp.connector` -> `aiohttp.connector` because all public names from `connector.py` are exposed by `aiohttp` root namespace.

It will prevent user code from writing ugly imports, e.g. `from aiohttp.connector import TCPConnector` (because `aiohttp.TCPConnector` is the only officially supported name).

@fafhrd91 ?

**Comment by fafhrd91** [comment]
we can import `aiohttp.web` in `aiohttp.__init__` 
I mean, we can import all available namespaces in `__init__`, and then we can forbidden to do imports anything beyond `import aiohttp`

I dont like `_` prefix, if we really want hide modules we can add submodules

**Comment by fafhrd91** [comment]
we should trust developers :)
well, at least provide good defaults. but if developer wants to do ugly staff then we can not prevent that.

**Comment by asvetlov** [comment]
How can you forbid imports?
Underscore is explicit sign for "don't touch me, it's a private property and subject for change without any notification and deprecation".

**Comment by fafhrd91** [comment]
underscores are too ugly. we would need to use underscore too often.

maybe we should explicitly import names in `aiohttp/__init__.py`

**Comment by fafhrd91** [comment]
I don't like `_` as prefix, but I can live with that

**Comment by AraHaan** [comment]
tbh Why not ``__`` for private and protected or something like that?

**Comment by kxepal** [comment]
I think for such problem handling submodules/packages should be used.  You can have one of themcalled, say, `aiohttp.internals` where no backward compatibility rules and for imports in third party projects the name explicitly says that you're going into danger zone, beware dynozavrs.

Underscore prefixed modules are all fine while there is a strong reason for them and you don't mind some naming conflicts with C-extensions.

**Comment by fafhrd91** [comment]
I don't like idea of `internals`, and in general it is not about backward compatibility but rather private apis (or wrong usage of those)

**Comment by fafhrd91** [comment]
but we have to make decision before 2.0

**Comment by kxepal** [comment]
Well, whatever it be, it should clearly say that you're importing something you shouldn't. You cannot forbidd to do that, but you can put right sign on those modules. Python is a gentelmen club in anyway. I think namespace is good for this - prettry hard to misread it, but underscore prefix also may works.

**Comment by AraHaan** [comment]
Well normally the convention is for python that most modules starting with ``_`` are C/C++ Python Extension modules.

**Comment by fafhrd91** [comment]
@asvetlov we need to make decision
