### ISSUE TITLE
Client exceptions refactoring

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1661]
New hierarchy of exceptions:

- `ClientError`
  - `ClientResponseError` - exceptions that could happen after we get response from server 
     - `WSServerHandshakeError` - web socket server response error
     - `ClientHttpProxyError` - proxy response
  - `ClientConnectionError` - exceptions related to low-level connection problem
     - `ClientOSError` - subset of connection errors that are initiated by OSError exception
        - `ClientConnectorError` - connector related exceptions
           - ClientProxyConnectionError` - proxy connection initialization error
     - `ServerConnectionError` - server connection related errors
        - `ServerDisconnectedError` - server disconnected
        - `ServerTimeoutError` - server operation timeout, (read timeout, etc)
        - `ServerFingerprintMismatch` - server fingerprint mistmach

**Comment by fafhrd91** [comment]
@kxepal @asvetlov

**Comment by asvetlov** [comment]
I have strong temptation for dropping `ClientError` (for deprecation period we can make it as alias for `Exception` and deriving `ClientConnectionError` from `OSError`.
Sorry, I have no time for explaining  my motivation right now but will try to describe my ideas tomorrow evening.

**Comment by fafhrd91** [comment]
we can kill `ClientRequestError` and replace it with `ValueError`

**Comment by fafhrd91** [comment]
`ClientRequestError` is removed
