### ISSUE TITLE
Allow method override for REST API emulation

### ISSUE THREAD

**Issue by kreopt** [aio-libs/aiohttp#1665]
## Long story short

It is common technique to override HTTP method by attaching X-Http-Method-Override (or similar variants) header with desired method string to make it possible to use REST API from browser. Aiohttp does not support this and method is not overridable cause it is read only and so unusable for REST services that should be used from browsers.

## Expected behaviour

Possibility to override method with X-Http-Method-Override or similar header

## Actual behaviour

no way to do this

**Comment by fafhrd91** [comment]
you can build custom middleware, and then WebRequest.clone() with new method

**Comment by kreopt** [comment]
Thanks! Missed clone() method. It is exactly what I need
