### ISSUE TITLE
url quote error

### ISSUE THREAD

**Issue by pc10201** [aio-libs/aiohttp#1680]
Hi.I use python 3.6.0 and django.

I have an FBV like:
```
def vendor(request, vendor_name):
    print vendor_name
    return vendor_name
```
if the url is like

```
http://example.com/a b
```

I use:
```
gunicorn --worker-class gunicorn.workers.ggevent.GeventWorker
```
the vendor_name is 'a b'

but I use
```
gunicorn --worker-class aiohttp.worker.GunicornUVLoopWebWorker
```

the vendor_name is 'a%20b'

I spent an whole day to find it.

**Comment by fafhrd91** [comment]
not enough info. need at least some code examples
