### ISSUE TITLE
Client Session Timeouts - Usage Question

### ISSUE THREAD

**Issue by owaaa** [aio-libs/aiohttp#1686]
## Long story short

We are using client sessions for the lifetime of the application as described here. 

> Unless you are connecting to a large, unknown number of different servers over the lifetime of your application, it is suggested you use a single session for the lifetime of your application to benefit from connection pooling

However. sometimes after running for several days, no requests through the session work. Every request results in a Timeout and Cancelled error shown below. The services which aiohttp are attempting to call are heathy and responding in less than 200ms when this occurs. The only resolution appears to be to kill and restart the process where the aiohttp client is running:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/aiohttp/client.py", line 529, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.5/site-packages/aiohttp/client.py", line 165, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.5/site-packages/async_timeout/__init__.py", line 44, in __exit__
    raise asyncio.TimeoutError from None

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/aiohttp/client.py", line 165, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.5/site-packages/aiohttp/connector.py", line 306, in connect
    yield from self._create_connection(req)
  File "/usr/local/lib/python3.5/site-packages/aiohttp/connector.py", line 585, in _create_connection
    transport, proto = yield from self._create_direct_connection(req)
  File "/usr/local/lib/python3.5/site-packages/aiohttp/connector.py", line 608, in _create_direct_connection
    local_addr=self._local_addr)
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 762, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 285, in result
    raise CancelledError
concurrent.futures._base.CancelledError
```

## Expected behaviour

The session correctly creates and closes behavior through the lifetime of the application as documentation describes above. I have read in past github issues it seems people have trouble if trying to manually re-instantiate later in the life time of the application as well. If this is not the correct usage, then I would like to understand that and documentation to reflect how to handle when the session is no longer "good".

## Actual behaviour

After running for a period of days, the session becomes unresponsive and no future requests work without a timeout.

## Steps to reproduce

I haven't reproduced this manually yet. It happens in our deployed environments about every week. We migrated from requests where we did not see these stability issues.

## Your environment

Python 3.5. Docker official container (Debian). aiohttp==1.1.6 (I am open to an upgrade but we had planned to field soon so I want to understand correct usage and want to be certain an upgrade would fix. I'd rather be certain the code pattern could handle failure cases).

**Comment by fafhrd91** [comment]
could you try 1.3.x release.

I'd suggest to migrate to 2.0 version of aiohttp, It has much better implementation for client side connection pool.

**Comment by owaaa** [comment]
Hi, its still an issue with 1.3.3. We've found only stable long term thing is to `async with` every client call. I wasn't aware there was a 2.X? I don't see any tags for that?

**Comment by fafhrd91** [comment]
2.0 is not release fully, yesterday I released rc1. I am planing to release 2.0 final within 5-10 days.

**Comment by fafhrd91** [comment]
btw  do you use custom keep-alive time for connector?

**Comment by fafhrd91** [comment]
should be fixed

**Comment by kalafut** [comment]
@owaaa Where did you end up on this?  I'm seeing a very similar thing.

**Comment by zmedico** [comment]
It may be related to https://github.com/aio-libs/aiohttp/issues/1879, fixed by https://github.com/aio-libs/aiohttp/commit/ab8efa4231041d86de2684af50793c0810382c33.

**Comment by owaaa** [comment]
@kalafut I never got this to work, it was too untrustworthy as the server never recovered so we have to create a new client every group of requests.

**Comment by gjthompson1** [comment]
I might be having a similar issue. 

[https://stackoverflow.com/questions/45800857/aiohttp-error-rate-increases-with-number-of-connections#45803926](https://stackoverflow.com/questions/45800857/aiohttp-error-rate-increases-with-number-of-connections#45803926) 

Although rather than "CancelledError" I am getting "TimeoutError" or maybe its un-related. It feels that way though, once one request hits a timeout the others all timeout.
