### ISSUE TITLE
ClientDisconnectedError when server returns buggy redirect

### ISSUE THREAD

**Issue by MarSoft** [aio-libs/aiohttp#1689]
## Long story short

There are some servers which do redirects in a strange way. Some examples are `http://fwmedia.com/`, `http://ebooks.artistsnetwork.com/`, `http://artistsnetwork.tv/`.
The common point between them is that they return redirect and close connection *immediately* after sending `Location` header:
```
 $ curl -v http://artistsnetwork.tv/
*   Trying 216.59.59.63...
* TCP_NODELAY set
* Connected to artistsnetwork.tv (216.59.59.63) port 80 (#0)
> GET / HTTP/1.1
> Host: artistsnetwork.tv
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Location: http://www.artistsnetwork.tv/
* Curl_http_done: called premature == 0
* Connection #0 to host artistsnetwork.tv left intact
```
Notice there is no empty line returned after `Location` header.

While `requests` library, `curl` and browsers tolerate this behaviour and recognize it as a redirect, `aiohttp.client` fails.

## Expected behaviour

There should be a way to handle such responses. Ideally I think such "unexpectedly broken" connections should be recognized in a special way, so that if there is enough information then we consider them "good".

## Actual behaviour

```
Traceback (most recent call last):
  File "/tmp/env/lib/python3.6/site-packages/aiohttp/client.py", line 220, in _request
    yield from resp.start(conn, read_until_eof)
  File "/tmp/env/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 614, in start
    message = yield from httpstream.read()
  File "/tmp/env/lib/python3.6/site-packages/aiohttp/streams.py", line 625, in read
    result = yield from super().read()
  File "/tmp/env/lib/python3.6/site-packages/aiohttp/streams.py", line 456, in read
    yield from self._waiter
aiohttp.errors.ServerDisconnectedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/tmp/env/lib/python3.6/site-packages/aiohttp/client.py", line 227, in _request
    raise aiohttp.ClientResponseError() from exc
aiohttp.errors.ClientResponseError
```

## Steps to reproduce

```
import asyncio, aiohttp
loop = asyncio.get_event_loop()
loop.run_until_complete(aiohttp.client.get('http://artistsnetwork.tv/'))
```

## Your environment

```
Python 3.6.0
aiohttp==1.3.3
yarl==0.9.8
```

**Comment by MarSoft** [comment]
As a temporary workaround / monkey-patch (had to use it in one of my projects):
```
import asyncio
import aiohttp

# XXX remove this after KeepSafe/aiohttp#1689 is fixed
def readuntil(self, stop, limit=None):
    assert isinstance(stop, bytes) and stop
    stop_len = len(stop)
    eof = False
    while True:
        if self._helper.exception:
            raise self._helper.exception
        pos = self._data.find(stop)
        if pos >= 0:
            end = pos + stop_len
            size = end
            if limit is not None and size > limit:
                raise aiohttp.errors.LineLimitExceededParserError(
                    'Line is too long.', limit)
            data = self._data[:size]
            del self._data[:size]
            return data
        elif eof:
            # value not found but stream was closed, so return everything
            data = self._data[:]
            if b'Location:' in data:
                del self._data[:]
                return data
            else:
                # no location header, so effectively re-raise
                raise eof
        else:
            if limit is not None and len(self._data) > limit:
                raise aiohttp.errors.LineLimitExceededParserError(
                    'Line is too long.', limit)
        try:
            self._writer.send((yield))
        except aiohttp.streams.EofStream as e:
            eof = e
# Changed: catch EofStream exception and treat it as if stopper was found
aiohttp.parsers.ParserBuffer.readuntil = readuntil
```

**Comment by fafhrd91** [comment]
I do not think this is possible to fix. in 2.0 version we use http-parser from nodejs, it does not produce complete http message

**Comment by MarSoft** [comment]
@fafhrd91, what is a 2.0 version of aiohttp, is it available somewhere? And do you mean [this C parser](https://github.com/nodejs/http-parser)?

**Comment by fafhrd91** [comment]
In new version we use http-parser from nodejs 

https://github.com/aio-libs/aiohttp

**Comment by fafhrd91** [comment]
I will add parsed headers to exception, so developer can make decision about redirect. 
but aiohttp won't support this behavior.

**Comment by fafhrd91** [comment]
actually, it is possible to make this redirect. question is, should we? 6732a79fdbd146458f54621a16f0a241c174a788

@asvetlov @kxepal @popravich @socketpair thoughts?

**Comment by socketpair** [comment]
I think, we should not handle that. It is RFC violation. Moreover, we can't use this partial response, since some headers may be missing. For example, `expires:`, which is VERY important for `301 Moved Permanently`. We don't know if connection was unexpectedly closed or it was intended so.

Also, It is OK to be able to handle parial messages in some way. I mean, it is OK to raise an exception like `raise PartialResponse()` which will contain some data of the original response.

**Comment by fafhrd91** [comment]
ok, good.

@MarSoft I added `message` attribute to `ServerDisconnectedError`, it may hold partial RawResponseMessage object
