### ISSUE TITLE
Can we get the response time?

### ISSUE THREAD

**Issue by whybeyoung** [aio-libs/aiohttp#1692]
compare with  3-rd party lib requests, response object has an property: response.elapsed
but in aiohttp , i can't find a method to get the time about the response, i wrote one decorator to wrap the fetch function to calculate the time ,but it is not precise， so can we have a pythonic method to get the response time(  the cost of time when get the first char recieved)

thanks a lot!

**Comment by AraHaan** [comment]
It is possible to use time.time to calculate it from the request to the response and export it as an property.

**Comment by asvetlov** [comment]
There are too many interesting time intervals: DNS resolution, connection establishment, timeout between sending first byte through the wire and getting response back, full time between `session.get()` call and returning the whole response back etc. etc.
`response.elapsed` is the only one of desired metrics.

@hynek suggested to add signals for tracing client states (#1309).
Unfortunately request is still waiting for hero but the issue should be done in this way.
It's the big amount of work through.

Closing as superseded by #1309

P.S.
Tracing facility should not affect performance if disabled (default value).
