### ISSUE TITLE
GET requests sometimes works with HTTP/1.0 sometimes with HTTP/1.1

### ISSUE THREAD

**Issue by niteeshm** [aio-libs/aiohttp#1695]
## Long story short

I have an endpoint for simple health check ( `GET /health_check` ) which just returns `web.json_response(text="OK", status=200)`. HAProxy calls this but requires protocol HTTP/1.0 to be mentioned , when request comes with default HTTP/1.1 , it gives 405 Method not allowed error.

If I curl to the endpoint from some other machine , it works fine with HTTP/1.1 .  Now with HAProxy hitting my server with HTTP/1.0 results in a new connection everytime which should not happen since its just a health check. 

Something wrong in my configuration ?

## Expected behaviour

Hitting the endpoint with the GET request should work fine irrespective of HTTP 1.0/1.1 . Behaviour should not be ambiguous.

## Actual behaviour

Sometimes GET works with HTTP 1.1 and sometimes requires 1.0 . It should always work with 1.1

## Your environment

aiohttp==1.2.0
Python 3.5.2 
Running with Supervisord

**Comment by fafhrd91** [comment]
could you test this against https://github.com/aio-libs/aiohttp/

**Comment by fafhrd91** [comment]
not clear what is this issue about.

reopen when you post more information.
