### ISSUE TITLE
oauthlib support

### ISSUE THREAD

**Issue by juanriaza** [aio-libs/aiohttp#17]
Is there any plan to implement support for [oauthlib](https://github.com/idan/oauthlib)?

**Comment by dmwyatt** [comment]
@fafhrd91 I might work on this.  Does `aiohttp` have some sort of auth extension interface like [this](http://docs.python-requests.org/en/latest/user/advanced/#custom-authentication)?

**Comment by kxepal** [comment]
@dmwyatt it's quite easy to implement this by yourself [1](https://github.com/kxepal/aiocouchdb/blob/master/aiocouchdb/authn.py#L209-L267) and [2](https://github.com/kxepal/aiocouchdb/blob/master/aiocouchdb/client.py#L230-L281). What the underlying library or auth method will be used is up to your requirements.

**Comment by fafhrd91** [comment]
@dmwyatt aiohttp does not have support for custom auth. but PR are welcome!

**Comment by klen** [comment]
I've written `aioauth-client` library https://github.com/klen/aioauth-client. It in beta version now, and should be tested. For my cases (github and twitter authorization, api requests) it works well.

**Comment by ludovic-gasc** [comment]
thank you @klen, I'll test that in the future because we need to implement an integration with Office365.
