### ISSUE TITLE
Reading a client response content stream raises confusing error when EOF is received

### ISSUE THREAD

**Issue by seppestas** [aio-libs/aiohttp#1702]
## Long story short

When reading the client response content stream an `errors.ContentEncodingError('deflate')` exception gets raised when an EOF is received from the server. This is a pretty confusing error when dealing with a connection that does not use any type of compression. It's very common to send an EOF to close streams, e.g in [SSE streams](https://www.w3.org/TR/eventsource/#parsing-an-event-stream).

## Expected behaviour

An error that is a bit less confusing, like just trowing a `ContentEncodingError` or something more specific like maybe a new type of `EOFError`.

Note that [Requests package](http://docs.python-requests.org/en/master/) raises a `ChunkedEncodingError` if the stream receives an EOF, so sticking to a `ContentEncodingError` that is a bit less confusing might be the best option in order to be consistent.

## Actual behaviour

An `errors.ContentEncodingError('deflate')` error get's raised, resulting in the following error message:
```python
aiohttp.errors.ContentEncodingError: 400, message='deflate'
```

## Steps to reproduce

- Connect to an event stream (e.g a SSE source)
- Read server sent events, e.g by [iterating over lines](http://aiohttp.readthedocs.io/en/stable/streams.html#asynchronous-iteration-support):
```python
try:
    async with session.get(
        'https://your.eventsource.io',
        headers={
            'Accept': 'text/event-stream'
        },
        timeout=None
    ) as r:
        if r.status == 200:
            async for line in r.content:
               print(line)
        else:
            print('Failed to connect to eventsource')
except aiohttp.errors.ServerDisconnectedError:
    print('Server disconnected')
```
- Wait till the eventsource closes by sending an EOF
- Stare in confusion at the resulting `ContentEncodingError` exception telling you something about a 400 error code with the message "deflate". 

## Environment

Python 3.6 (built and installed from source)
Debian 8.7
Linux 3.16.0-4-amd64

**Comment by fafhrd91** [comment]
could you test this against https://github.com/aio-libs/aiohttp/

**Comment by fafhrd91** [comment]
problem is fixed in master, it raises ClientPayloadError with specific message, like content-encoding error or transfer encoding error.

documentation is not ready though.
