### ISSUE TITLE
Attach Request and Response to HttpProcessingError raised from client

### ISSUE THREAD

**Issue by justanr** [aio-libs/aiohttp#1705]
With request's Response.raise_for_status, the raised exception has the request and responses that caused that status attached to it. This allows handling of error codes + content to be off loaded from the calling code (into a decorator etc).

If there's interest, I'm happy to put together a PR.

**Comment by fafhrd91** [comment]
could you provide PR in this repo https://github.com/aio-libs/aiohttp

**Comment by justanr** [comment]
Yeah, is that the new canonical repo?

**Comment by fafhrd91** [comment]
I dont really want to document ClientRequest class, too much specific low level details. otherwise any PRs are welcome

**Comment by penguinolog** [comment]
Response to HttpProcessingError - i agree this idea. if @fafhrd91 @asvetlov will accept - pull request will be made at short time.
Currently, on our deploy, we to use our own `raise_for_status` with this functionality.

**Comment by fafhrd91** [comment]
`ClientResponseError` now has `request_info` attribute
