### ISSUE TITLE
The doc is wrong about accessing app from a TestClient object

### ISSUE THREAD

**Issue by penghou620** [aio-libs/aiohttp#1706]
## Long story short

I tried to access the app from a TestClient object as describe in the Testing secions like `cli.app`. But it didn't work for me. 

## Expected behaviour

`cli.app` should return the app object

## Actual behaviour

I looked deep and tried out that `cli.server.app` works

## Steps to reproduce

Following the second code snippet in the [pytest](https://aiohttp.readthedocs.io/en/stable/testing.html#pytest) section

```
import pytest
from aiohttp import web


async def previous(request):
    if request.method == 'POST':
        request.app['value'] = (await request.post())['value']
        return web.Response(body=b'thanks for the data')
    return web.Response(
        body='value: {}'.format(request.app['value']).encode('utf-8'))

@pytest.fixture
def cli(loop, test_client):
    app = web.Application(loop=loop)
    app.router.add_get('/', hello)
    return loop.run_until_complete(test_client(app))

async def test_set_value(cli):
    resp = await cli.post('/', data={'value': 'foo'})
    assert resp.status == 200
    assert await resp.text() == 'thanks for the data'
    assert cli.app['value'] == 'foo'
```

## Your environment

- python=3.6
- aiohttp=1.3.4

**Comment by fafhrd91** [comment]
docs have been updated for master and 1.3 branches
