### ISSUE TITLE
Опечатка в документации

### ISSUE THREAD

**Issue by businka** [aio-libs/aiohttp#1711]
https://aiohttp-session.readthedocs.io/en/stable/reference.html#module-aiohttp_session
В разделе Simple Storage
в примере написано
app = aiohttp.web.Application( middlewares=[aiohttp_session.SimpleCookieStorage()])

надо 
app = aiohttp.web.Application( middlewares=[session_middleware(aiohttp_session.SimpleCookieStorage())])

сильно запутывает

**Comment by fafhrd91** [comment]
you need this repo https://github.com/aio-libs/aiohttp-session

**Comment by fafhrd91** [comment]
перенеси свой вопрос в https://github.com/aio-libs/aiohttp-session
