### ISSUE TITLE
2.0 rc release

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1714]
what we need to do for 2.0 dev0 release.

original issue https://github.com/fafhrd91/aiohttp/issues/6

@jettify @kxepal @thehesiod @samuelcolvin @arthurdarcet

**Comment by samuelcolvin** [comment]
happy for you to move aiohttp-devtools to aio-libs if you'd like? I still need to test it properly with master.

Also, can I suggest an "rc" release on github? That way we all know what we're downloading and testing. And it might prompt others to test the latest version of aiohttp

**Comment by fafhrd91** [comment]
cool, lets move aiohttp-devtools.

I like rc idea

**Comment by samuelcolvin** [comment]
I'm getting 

> You don’t have the permission to create repositories on aio-libs

I guess you need to give me permissions

**Comment by fafhrd91** [comment]
sure

**Comment by fafhrd91** [comment]
you should have permission

**Comment by samuelcolvin** [comment]
done, just transferring now.

**Comment by fafhrd91** [comment]
great

**Comment by fafhrd91** [comment]
I updated migration.rst, I need someone to review it.

http://aiohttp.readthedocs.io/en/latest/migration.html

**Comment by arthurdarcet** [comment]
One or two breaking changes could be avoided, and simply be deprecations ; but imo we don't need to worry about that since this is a major release (the `(BaseConnector|ClientSession).close` methods could return an already-resolved `asyncio.Future` instead of returning None, this way `await session.close()` would still work)

I have pushed some minor changes in #1716, other than that, looks good to me

**Comment by fafhrd91** [comment]
I am not sure, how big is the problem with close().
probably ClientSession.close() could return noop()

**Comment by arthurdarcet** [comment]
that was one of the breaking change that impacted some of my code, but i think it's perfectly ok to have breaking changes in a major release… Deprecating it first would have been nice, but nothing is forcing people to upgrade to 2.0 immediately so i don't feel like it's required here

**Comment by jettify** [comment]
As far as I remember @asvetlov made `ClientSession.close()` coroutine in order to provide better finalisation in future. We did mistake with `close` method in  `aiopg.Connection` by making it regular function. 

@asvetlov could you please review this change.

**Comment by fafhrd91** [comment]
problem with graceful shutdown is that we can not really do it for session. 
session does not track requests, and with new changes all completed responses release connections immediately. so developer needs to close reponses otherwise all connections that are in use can not be gracefully be closed.

**Comment by fafhrd91** [comment]
added "deprecate_noop" specifically for this case

**Comment by fafhrd91** [comment]
I prepared release https://github.com/aio-libs/aiohttp/releases/tag/untagged-df01c1c4674fe2267db7

I need help with review. anyone wants to add anything to release text?

**Comment by samuelcolvin** [comment]
You should add:

""
You can install and test this release with

    pip install https://github.com/aio-libs/aiohttp/archive/2.0.0rc0.zip

"""

Installing zips with pip is a little-known feature and much faster and less error prone than installing from the 84 different types of scm uri.

**Update:** just corrected the url. Not important, but isn't the first rc generally called rc1 not rc0?

**Comment by arthurdarcet** [comment]
I would suggest using
```
pip install https://github.com/aio-libs/aiohttp/archive/2.0.0rc0.tar.gz#egg=aiohttp-2.0.0rc0
```
it helps with subsequent updates

**Comment by fafhrd91** [comment]
I want to make release on pypi

**Comment by fafhrd91** [comment]
version is changed

**Comment by samuelcolvin** [comment]
I just tweaked the release text so the pip command shows up as code.

aiohttp-devtools is currently failing with 2.0 due to problems with aiohttp-debutoolbar, see https://github.com/aio-libs/aiohttp-devtools/pull/45 and https://travis-ci.org/aio-libs/aiohttp-devtools/jobs/211466016

**Comment by fafhrd91** [comment]
do you think it is reasonable to support two major versions at the same time?

**Comment by fafhrd91** [comment]
add dependency aiohttp<2.0

and make new major version with aiohttp>=2.0

**Comment by arthurdarcet** [comment]
the current version of the devtools is 0.2
=> i think the version should just bump to 0.3 and require aiohttp 2, it's not unreasonable to break things in a v0

**Comment by fafhrd91** [comment]
thanks everybody for help.

**Comment by fafhrd91** [comment]
I think we ready for release, I just want to wait couple days before making final release

**Comment by samuelcolvin** [comment]
Sounds good to me, aiohttp-devtools is ready with debugtoolbar switched off by default until it's fixed.
