### ISSUE TITLE
get_extra_info for ClientWebSocketResponse

### ISSUE THREAD

**Issue by kdub0** [aio-libs/aiohttp#1717]
I'd like to be able to retrieve the server's certificate from an https websocket.  Right now, this is possible with something like:

```
async with aiohttp.ws_connect(url) as ws:
    cert = ws._conn.writer.get_extra_info('peercert')
```

Is there a way to do this that is future proof?  or can the API be extended to expose the websocket's transport?

Thanks!

**Comment by fafhrd91** [comment]
makes sense. I added `get_extra_info` to `ClientWebSocketResponse` in master
I do not think we should allow access to transport object.

**Comment by kdub0** [comment]
Awesome, much appreciated!
