### ISSUE TITLE
AttributeError: 'Response' object has no attribute '_body_payload'

### ISSUE THREAD

**Issue by rutsky** [aio-libs/aiohttp#1718]
aiohttp_cors tests started to fail with master branch of aiohttp recently, all with the same exception: https://travis-ci.org/aio-libs/aiohttp-cors/jobs/211117879

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/aiohttp/web_protocol.py", line 430, in start
    yield from resp.write_eof()
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/aiohttp/web_response.py", line 569, in write_eof
    elif self._body_payload:
AttributeError: 'Response' object has no attribute '_body_payload'
```

@fafhrd91 I haven't investigated this yet, but I think you would be interested to take a look, since you changed related logic two days ago.

**Comment by rutsky** [comment]
I can prepare exact tests for this error, but I have feeling that @fafhrd91 only by stack trace will figure out what is the source of the error in two seconds.

**Comment by fafhrd91** [comment]
Sure, thanks

**Comment by fafhrd91** [comment]
should be fixed
