### ISSUE TITLE
Implement streaming request data generation for ClientRequest

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#1721]
i.e. possible API (pseudocode, actual API may be completely different):

```python
with web.ClientSession() as session:
    async with session.post('/') as req:
        writestream = req.get_write_stream()
        writestream.write('xxx')
        await writestream.drain()
        writestream.write_eof()
        ...
```

In my case, I have unknown amount of data that sould be sent in the body of the POST-request (i.e. chunked request). Streaming request/response is available for server-side. But for client-side, streaming requests are not available...Maybe I miss something ?

**Comment by fafhrd91** [comment]
this is for 2.0 http://aiohttp.readthedocs.io/en/latest/client.html#streaming-uploads
this is for 1.3 http://aiohttp.readthedocs.io/en/stable/client.html#streaming-uploads

**Comment by fafhrd91** [comment]
I like your idea, I need to think how implementation could look like

**Comment by socketpair** [comment]
wow. http://aiohttp.readthedocs.io/en/stable/client_reference.html#aiohttp.ClientSession.request said that:

![image](https://cloud.githubusercontent.com/assets/1157412/24018942/d21a8b96-0ab7-11e7-89da-9071284ece9d.png)

So, it does not mention that this can be stream, actually...
Also,
![image](https://cloud.githubusercontent.com/assets/1157412/24018989/030143ee-0ab8-11e7-8fee-49aaf960b560.png)

Is `writer.write()` really coroutine ?

**Comment by fafhrd91** [comment]
it is new subsystem in 2.0, there is payload registry, it is not documented yet.

here is payload implementation for StreamReader https://github.com/aio-libs/aiohttp/blob/master/aiohttp/payload.py#L263

technically `writer.write()` is not a coroutine, but I would use it as coroutine because it does drain()
writer is an instance if PayloadWriter class https://github.com/aio-libs/aiohttp/blob/master/aiohttp/http_writer.py#L130

**Comment by fafhrd91** [comment]
with payloads you can do fancy stuff like this:

https://github.com/aio-libs/aiohttp/blob/master/tests/test_web_functional.py#L1526
