### ISSUE TITLE
PicoHTTPParser

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1722]
as we already use http-parser, we should try PicoHTTPParser. should be relatively easy to replace http-parser

https://github.com/h2o/picohttpparser

**Comment by samuelcolvin** [comment]
Looks interesting.

Is there any chance we could use a parser which supports http2? I had a quick look (eg. [here](https://github.com/http2/http2-spec/wiki/Implementations)) but couldn't find an "obvious" option which supported http2.

**update**: Perhaps https://github.com/nghttp2/nghttp2 it's used by curl I think so must be pretty well respected.

**Comment by fafhrd91** [comment]
I think http2 integration is more than just parser integration. we need to investigate. but for sure we can not use http2 parser written in python, it would be very slow.

I am working on tokio(rust) based event loop, it should be relatively easy to integration rust based parser.

**Comment by socketpair** [comment]
I suggest nginx http parser, if possible.

https://github.com/nodejs/http-parser

and also look to, just for interest.
http://natsys-lab.blogspot.ru/2014/11/the-fast-finite-state-machine-for-http.html

**Comment by fafhrd91** [comment]
aiohttp already uses http-parser, https://github.com/aio-libs/aiohttp/tree/master/vendor/http-parser

but PicoHTTPParser seems 4-5x faster.

**Comment by socketpair** [comment]
OK, but this should be optional, since AFAIK PicoHTTP is not strict HTTP parser, that's why it so fast.

**Comment by fafhrd91** [comment]
my priorities slightly changed, I am not planing to work on this issue. if anyone wants to try please re-open
