### ISSUE TITLE
Add API that will allow/deny/warn automatic decoding of json based on content-type.

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#1723]
Now, aiohttp issue warning if `await response.json()` called and response does not contain correct content-type.
This should be configurable. I suggest to to require `content_type.startswith('application/json')`. Aiohttp's users must be able to turn this check off and also specify his own MIME-type that should pass this check. I understand, that many broken HTTP-servers give JSON-response without setting correct content-type. I think, we should fight against these servers.

**Comment by fafhrd91** [comment]
makes sense

**Comment by fafhrd91** [comment]
added

**Comment by pnuckowski** [comment]
What about `application/vnd.api+json` is it correct content-type?
