### ISSUE TITLE
Some option to call raise_for_status() automatically on any request.

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#1724]
I have many places where my application issues HTTP-request, for example:

```python
async def get_network_interfaces():
    async with ClientSession() as session:
        async with session.get('http://localhost/network/interfaces') as response:
            response.raise_for_status()  # <- THIS LINE
            return await response.json()
```

The marked line annoys me, since our programmes forgot to add it too frequently. Unforunatelly, our web services report error with HTTP code 542 and JSON-response of error, so returning from such functions without exception is a bug.

**Comment by fafhrd91** [comment]
added to master.

PS you should re-use session object

**Comment by socketpair** [comment]
WOW!
1. What did you mean when you say about `ClientSession` resuse ? As I understand, you suggest to make it global in my application. Where I can read about correct usage pattern ?
2. You have added `raise_for_status=False`. This is good, but it does not solve my problem. Programmers will forget to set it anyway. Is any way to set it to `True` globally ?

**Comment by fafhrd91** [comment]
just use one global `ClientSession` instance, then you can configure your session once.
http://aiohttp.readthedocs.io/en/latest/client_reference.html#client-session

**Comment by fafhrd91** [comment]
global session does connection pooling and cookie sharing if you need cookie

**Comment by socketpair** [comment]
Keep-Alive is more important for me than cookies. So, I already know about such `ClientSession` usage. Thank you for the advice.

**Comment by tpraizler** [comment]
@fafhrd91 Why the issue was close? The issue was about removing the need to do `response .raise_for_status()`. I don't see that this was addressed. is there a reason for that?
