### ISSUE TITLE
AioHTTP Unescaping URL-Encoded Components in the URL or Params 

### ISSUE THREAD

**Issue by kevinjdolan** [aio-libs/aiohttp#1725]
## Long story short

When I make a request, as follows:

```
import aiohttp
import asyncio

async def main(loop):
    async with aiohttp.ClientSession(loop=loop) as session:
        url = 'http://localhost:9766/stupid-test/'
        params = 'hello=space%40invader'
        async with session.get(url, params=params) as response:
            print(response)

loop = asyncio.get_event_loop()
loop.run_until_complete(main(loop))
```

The url params are unescaped to transform the `%40` to `@`. This also occurs when placing the query string directly in the URL.

This is evidenced by the url field of the response object, which now looks like:

```
<ClientResponse(http://localhost:9766/stupid-test/?hello=space@invader) [200 OK]>
```

...as well as the UWSGI logs for the receiving server.

This causes problems with a hash-based request signing procedure that my company uses.

We have observed this in aiohttp version 1.3.5, but not version 1.0.2 (unclear exactly where the behavior begins).

**Comment by kevinjdolan** [comment]
It seems to be ultimately boiling down to the use of YARL... not sure to what degree this behavior is non-conformant with specs, but it is not consistent with the behavior of other Python request libs.

```
>>> from yarl import URL
>>> u = URL('http://www.test.com/?email=smooth%40criminal')
>>> u
URL('http://www.test.com/?email=smooth@criminal')
```

**Comment by fafhrd91** [comment]
yes, that's yarl

**Comment by fafhrd91** [comment]
you can use encoded=True

```
url = yarl.URL('http://www.test.com/?email=smooth%40criminal', encoded=True)
session.get(url)
```

**Comment by flyte** [comment]
May I propose this goes in the documentation somewhere? It's inconsistent with requests and curl and is a bit astonishing once you finally work out why your requests aren't working properly.

**Comment by asvetlov** [comment]
The behavior is mentioned here: https://docs.aiohttp.org/en/stable/client_quickstart.html#passing-parameters-in-urls

Please feel free to make PR for documentation improvement if you have an idea how to make it better

**Comment by flyte** [comment]
Ah, my mistake. I did see that section but didn't understand/read it properly. Thank you for the quick response.

**Comment by asvetlov** [comment]
No problem. Maybe the note should be raised up?

**Comment by flyte** [comment]
I think my problem was not knowing what 'canonization' meant. The section title might have been a bit misleading for me too, since I wasn't explicitly passing in parameters, instead they were already included in the URL I was using (built from `generate_presigned_url` in the boto3 S3 library). My use case is probably dissimilar to the majority though.

**Comment by asvetlov** [comment]
ok
