### ISSUE TITLE
Add API to easily send JSON as request body

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#1726]
i.e. some shortcut for

```python
data = {'answer': 42}
client_session.post(
    'http://example.com',
    data=json.dumps(answer),
    headers={'content-type': 'application/json'}
)
```

**Comment by socketpair** [comment]
Tornado automatically makes `json.dumps` + set content-type when it see that `isinstance(data, dict)`. This covers many usecases. But even with this, we needed to patch tornado. We send lists as json. So, as I think, most intuitive API will be:

* `post(json=..).` -- calls `json.dumps()` and sets content-type `application/json` (if content-type was not set using `headers=...`
* `post(text=..).` -- calls `.encode('utf-8')` and sets content-type `text/plain; charset=utf-8` (if content-type was not set using `headers=...`

This will match how the `web.Response()` works. But unfortunatelly only for `data=...` and `text=...`. Also, it will be nice to add `json=...` to `web.Response`, and say that `web.json_response` is obsolete.

**Comment by fafhrd91** [comment]
we can add payload for dict and list, something like https://github.com/aio-libs/aiohttp/blob/master/aiohttp/payload.py#L199

I'd add "json=" and "text=" but we should be very careful, `request()` method has so many parameters already.

**Comment by AraHaan** [comment]
discord.py can request json like so (They basically made a class that creates their own ``request function`` that has an param named ``json``

```py
import aiohttp
import asyncio
import json

class HTTPClient:
    def __init__(self, loop, *args, *kwargs):
        self.loop = loop
        self.session = aiohttp.ClientSession(loop=self.loop, *args, **kwargs)

    @asyncio.coroutine
    def request(self, url, method, **kwargs):
        if 'json' in kwargs:
            headers['Content-Type'] = 'application/json'
            kwargs['headers'] = headers
            kwargs['data'] = json.dumps(kwargs.pop('json'), separators=(',', ':'), ensure_ascii=True)
        r = yield from self.session.request(method, url, **kwargs)
        yield from r.release()

```

As you can see json can be passed just fine into ``data=``.

**Comment by fafhrd91** [comment]
added `json` parameter, but I am not sure about `text`

**Comment by fafhrd91** [comment]
regarding `json` for `web.Response()`, @asvetlov has some reasons not to add json. 
@asvetlov could you clarify?

**Comment by socketpair** [comment]
Great! I have now more reasons to throw out Tornado from our projects!

**Comment by jettify** [comment]
previous discussion about json in`web.Response()` https://github.com/aio-libs/aiohttp/issues/592

**Comment by AraHaan** [comment]
Well, as much as I like json and I use it a lot. I also hate having to use BeutifulSoup and lxml just to convert simple xml responces to json data. It ais also pain as well as I wanted to use the xml.dom.minidom in the standard library for the conversion of it to json. Hopefully an future version of aiohttp would allow me to convert xml responces to json so I can kill two dependencies with one stone (in this case aiohttp doing it for me).

**Comment by fafhrd91** [comment]
added separate ticket for web.Response
