### ISSUE TITLE
Why - 'Concurrent call to receive() is not allowed'

### ISSUE THREAD

**Issue by AlexanderMartynoff** [aio-libs/aiohttp#1729]
Can I find out what is the technical reason for this restriction?

**Comment by fafhrd91** [comment]
Websocket protocol parser does not support multiple reader. Thechnically, non of low-level data streams support concurrent reading

**Comment by AlexanderMartynoff** [comment]
But at the level `aiohttp` it possible to simulate a multiple reading?

**Comment by fafhrd91** [comment]
No, aiohttp does not provide multi reader stream as well, check streams.py
But you can build your own solution on top of aiohttp receive()

**Comment by AlexanderMartynoff** [comment]
Yes, of course. Thank you!
