### ISSUE TITLE
Changelog for 1.3.5 seems to be missing

### ISSUE THREAD

**Issue by jayfk** [aio-libs/aiohttp#1730]
## Long story short

The latest release in https://github.com/aio-libs/aiohttp/blob/master/HISTORY.rst is `1.3.4` and https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst begins at `2.0.0rc1`.

## Expected behaviour

Have a changelog for 1.3.5.

## Actual behaviour

No changelog for 1.3.5.

## Steps to reproduce

Open
- https://github.com/aio-libs/aiohttp/blob/master/HISTORY.rst 
- https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst

CTRL/CMD + F 

<img width="304" alt="screen shot 2017-03-20 at 11 03 42" src="https://cloud.githubusercontent.com/assets/2930472/24095333/f04954c4-0d5c-11e7-8bb1-8708f25bcb31.png">

**Comment by jayfk** [comment]
Looks like the release page on PyPi has it: https://pypi.python.org/pypi/aiohttp

Forgot to commit and push `CHANGES.rst`?

**Comment by fafhrd91** [comment]
https://github.com/aio-libs/aiohttp/blob/1.3/CHANGES.rst

**Comment by samuelcolvin** [comment]
We shouldn't have `HISTORY.rst` and `CHANGES.rst`, it's confusing for both users and pyup.

**Comment by fafhrd91** [comment]
Changes.rst contains only last release changes. Otherwise changes.rst would be huge

**Comment by samuelcolvin** [comment]
Well whatever we do it should work with pyup as that description of changes in PRs is extremely useful. I see no problem with a huge changelog.

**Comment by jayfk** [comment]
> We shouldn't have HISTORY.rst and CHANGES.rst, it's confusing for both users and pyup.

While I agree that this is confusing, it isn't a problem for pyup to parse the changelog. The underlying issue is that the `1.3.5` changelog wasn't merged back into master and seems to only appear on the `1.3` branch.

I can understand why that's been done, but I think that's even more confusing. As a user (and tool author) I'd expect to see the full changelog of all available releases on the master branch.

**Comment by fafhrd91** [comment]
I do not this it is problem in general. It is just current situation with 2.0, usually it takes much less time and amount of changes to make new release

**Comment by fafhrd91** [comment]
Help is welcome

**Comment by samuelcolvin** [comment]
I'm still not clear what the problem would be with just `HISTORY.rst` which contains all changes back to the beginning of time?

That would be clear for users and afaik would work with pyup/changelog.

If that's an acceptable solution I'll happily submit a PR.

**Comment by fafhrd91** [comment]
ok

**Comment by fafhrd91** [comment]
I fixed history

**Comment by jayfk** [comment]
thanks 👍🏼
