### ISSUE TITLE
Add API to easily send JSON as web response body

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1732]
we may need to reconsider adding "json=" parameter to web.Response class.

more discussions in #1726 and #592

**Comment by fafhrd91** [comment]
it is about convenience. 

Of course for proper handling of json encoding with versioning and custom serialization proper middle should be used.

**Comment by fafhrd91** [comment]
@popravich @socketpair @kxepal @jettify

**Comment by alex-eri** [comment]
Why is this better than `aiohttp.web.json_response`?

**Comment by fafhrd91** [comment]
it is not better it is convenient.

**Comment by asvetlov** [comment]
It's like moving in backward direction.
`web.Response` is a class for sending either text or binary data back to client.

Honestly I have a feeling than the class is overcomplicated (take a look in `Response.__init__` code).
For sake of clean architecture we need two classes: `TextResponse` and `BinaryResponse`.
But I can live with current state.

Adding a new parameter leads to combinatorial explosion.

**Comment by fafhrd91** [comment]
I am ok with this. we can close this ticket

**Comment by AraHaan** [comment]
I agree with @asvetlov on aiohttp needing 2 response classes and having the json response part of TextResponse. I would do it myself but I am not sure what parts are for binary data and what parts are for text data or both. That is how complicated it is. However there might be places where binary data is sent with json data. In that case it might break unless there is a way to avoid it?
