### ISSUE TITLE
HTTP requests pipelining in ClientSession

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#1740]
Does Aiohttp 2.0 support pipelining ? I know, that NGINX HTTP parser supports pipelining. But what about Aiohttp ? Does it handle the case :

1. Request 1 parsed, and is awaiting it's coroutine A to complete
2. Request 2 parsed, and is awaiting it's coroutine B to complete
3. Coroutine B completed. But it's response must not be written to the connection, until A's response is written.

In general, for any TCP-connection (used as HTTP), it is possible to have many coroutines that handle requests simultaneously, and their answers must be strictly ordered. It seems, we should have some queue of responses associated with TCP-connection.

Also, we should be able to specify if pipelining should be used. It have many corner-cases which may be not expected. The same for ClientSession. Should it issue piplined requests or not. In both cases pipelining shuold turned off by default (at least for now).

**Comment by fafhrd91** [comment]
pipelining is supported on server side for right now. 2 is default number of concurrent handlers

queue is built with combination of StreamWriter and PayloadWriter from
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/http_writer.py

I am not sure if aiohttp needs to provide stronger guarantees for ordering. aohttp relies on the fact that tasks initialization is ordered, technically it is implementation details, but for right now default loop and uvloop has this guarantees.

https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_protocol.py#L293
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_protocol.py#L412

**Comment by fafhrd91** [comment]
I am not sure about ClientSession. pipelining support would require api redesign. I am not ready for this task right now :)

**Comment by socketpair** [comment]
Once again, is aiohttp ready for pipelining even for the case when two (pipelined) responses are streaming writes ? (Sorry, it's hard for me to completely understand internal design for now)

**Comment by fafhrd91** [comment]
Yes, it is. Writes to transport are queued. Sendfile support pipelining.

**Comment by socketpair** [comment]
So, since server's pipelining is supported, I am going to rename issue.

**Comment by socketpair** [comment]
Well, regrading pipelining in ClientSession, I expect this behaviour: when connection limit (per domain) reached, if pipelining is enabled, it should pick random connection to the same domain and send pipelined request. If pipelining is not enabled, it should wait until some connection released.

**Comment by fafhrd91** [comment]
here is test for pipeline ordering https://github.com/aio-libs/aiohttp/blob/master/tests/test_web_protocol.py#L717

**Comment by fafhrd91** [comment]
I think client pipeline support should be explicit. something like:

```python

with session.pipeline('https://www.python.org') as pipe:
      yield from pipe.get('/inde.html')
      yield from pipe.put(..)

```

**Comment by socketpair** [comment]
Well, In our applicationS all requests can be pipelined. So, with this API programmers are required to write `with session.pipeline` in every place. It is not intuitive. Maybe, it desirable to write

```python
ClientSession(pipelined_domains=['domain1.com', '*.example.com'])
ClientSession(pipelined_domains=['1.2.3.4', '[2001:db8:a0b:12f0::1]:80'])
ClientSession(pipelined_domains=['*'])
```

I do not recommend to use regexps, since programmers will often add a mistake for not escaping the dot.
Or, myabe, 

```python
generic_session = ClientSession()
pipelined_session = ClientSession(pipeline=True)
```

And force programmers to use different sessions for all pipelined requests and non-pipelined. The second variant is more appropriate for us.

**Comment by fafhrd91** [comment]
I think separate pipeline client is better, but I'd like to limit host upfront.

```python
pipeline = ClientPipeline(host='...')
pipeline.get(path='/some-path')
```

**Comment by socketpair** [comment]
If I understand right, `ClientPipeline` is an pipeline-enabled `ClientSession`. So, why I should specify host ? Also, note, that in some scenario, actual url might look like `mirror1.host.com`, `mirror2.host.com` and so on (list of mirrors is dynamic). In such scenario it may be convenient to specify `*.host.com` or even `mirror*.host.com`.

But such complex API (with globs) is not very nice. So I prefer

```python
pipelined_session = ClientSession(pipeline=True)
```

**Comment by fafhrd91** [comment]
I'd like to avoid unnecessary complexity. Client pipeline impl will be complex on itself. Multiple host as load balancer makes sense, star doesn't. With star developer needs to choose host name at calling site then what's the point to use star in session.

**Comment by fafhrd91** [comment]
Pipeline support will need extra support from developer. There will be extra extra state, "request pipelined, but server disconnected"

**Comment by asvetlov** [comment]
Let's close the issue: pipelining shows nice benchmark numbers but very impractical for real programming.

**Comment by Suor** [comment]
Pipelining is quite efficient approach, can't see it as impractical.

**Comment by asvetlov** [comment]
@Suor you can try proposing a pull request.
Talking about pipelining is general doesn't make a productive discussion.
Maybe a concrete implementation sketch can provide a better basement for it.
