### ISSUE TITLE
Add ClientResponse().history elements to ClientResponseError

### ISSUE THREAD

**Issue by penguinolog** [aio-libs/aiohttp#1741]
## Long story short

During investigation of HTTP client exceptions on big installations, history can provide information about failure reason (incorrect redirect and etc).
De-facto needed fields:
  url, code, reason, location if present in headers (all headers is better)

## Expected behaviour

Accessible list `ClientResponseError().history`

## Actual behaviour

Currently this information is unavailable.

Proposed solution:

```python
HistoryRecord = namedtuple('HistoryRecord', ('url', 'code', 'reason', 'headers'))
ClientResponseError().history: typing.List[HistoryRecord]
```

**Comment by fafhrd91** [comment]
Let's just add history to exception. Do we really need new type?

**Comment by penguinolog** [comment]
Just following request_info idea.
May I add just response to exception and expose it fields? (like it done in requests).

**Comment by fafhrd91** [comment]
`request_info` is required only because `ClientRequest` is private class.
`ClientResponseError` may be raised without response, so exception should have history of interactions and response that is cause of exception or none if there is no one.

**Comment by penguinolog** [comment]
Accepted. Thank you!

**Comment by fafhrd91** [comment]
Merged
