### ISSUE TITLE
Need possibility to modify client.Session default headers in constructed session

### ISSUE THREAD

**Issue by penguinolog** [aio-libs/aiohttp#1746]
## Long story short

`client.Session._default_headers` is "protected" field, while sometimes required to modify it in runtime (set specific 'User-Agent' and etc) without restart.

## Expected behaviour

Getter property `client.Session.default_headers` (it's mutable -> setter is not needed) is suitable solution for changing headers between requests.

## Actual behaviour

`client.Session._default_headers` is used.

**Comment by fafhrd91** [comment]
I do not think this is good idea. What is your specific use case?

**Comment by penguinolog** [comment]
Currently not mine case: zeep library sets HTTP-Client header on received session, constructed outside.

**Comment by fafhrd91** [comment]
But that's bad behavior. Let's say library set default header, but then owner of session modifies it, so no one would be able to rely what's in default headers.

-1

**Comment by penguinolog** [comment]
Accepted concern.
