### ISSUE TITLE
Type hinting in code

### ISSUE THREAD

**Issue by penguinolog** [aio-libs/aiohttp#1749]
## Long story short

While working on big project, typing check helps to exclude shot in the leg scenario.

## Expected behaviour

Type annotations on public methods.

## Actual behaviour

No any type annotations, including the most docstrings.

## Note

**Need a decision: typing in global requirements or use version-specific requirements (PEP496/PEP508)**

**Comment by penguinolog** [comment]
@fafhrd91 Please comment decision, if possible.

**Comment by fafhrd91** [comment]
Personally, I do not use type annotations. But I am fine with type annotations on public methods

**Comment by penguinolog** [comment]
I'm about requirements on `typing` library. We can require it on every python version and can specify 3.4 only due to it presence in 3.5+ out of box.

**Comment by fafhrd91** [comment]
That's fine

**Comment by iceboy233** [comment]
I personally dislike type annotations in performance sensitive code in python. Any footprint bloat would slow things down, especially in interpreted languages.

**Comment by fafhrd91** [comment]
I thought there should be no runtime penalty?

**Comment by iceboy233** [comment]
the annotations are accessible at runtime through `__annotations__`, so it will increase the memory footprint, allocator load (for the hash table for `__annotations__`), incref for the type objects, parsing time, etc.

**Comment by fafhrd91** [comment]
Ah, but compared to overall speed of python that doesn't really matter. I guess it is possible to come up with method how to strip annotations data at startup

**Comment by iceboy233** [comment]
The annotations are not necessarily for type hints and are runtime visible. It's just the IDEs using them for type hints. I have used annotation for other things in my programs, such as param sanitizing.

**Comment by asvetlov** [comment]
Annotations are perfect concept but before applying it to aiohttp we need reliable type checker tool.
The only existing tool for now is `mypy` and it's not production ready yet.

At least I had big problems when tried to check annotations for smaller aio-libs projects.
Let's postpone the issue (without closing).

**Comment by thehesiod** [comment]
extra datapoint: all the code I write has type hints as it greatly helps finding issues in pycharm while developing

**Comment by kxepal** [comment]
I also had negative experience with type hints as annotations. Tools are not ready indeed and you have to choose between two evils: do additional imports for getting types and accidentally end with circular ones or double number of files to maintain. So far good old sphinx docstrings are more handy and PyCharm can use it for type hinting. You still have to write docs anyway.

However, I think you can start make annotations today as [typeshed](https://github.com/python/typeshed/tree/master/third_party/3)  part or as standalone project with stubs like [pyspark](https://github.com/zero323/pyspark-stubs) and contribute back fixes of any problems you found.

**Comment by asvetlov** [comment]
python/typing#84 is a blocker: without support for third-party libs in mypy type annotations are useless for aiohttp users.

**Comment by asvetlov** [comment]
I don't want to support aiohttp stubs in typeshed but want to add annotations into aiohttp itself

**Comment by penguinolog** [comment]
I have requirements concern:
typing is available starting from Python 3.5, backport can be required using PEP0508 (incorrectly parsed by some packagers), PEP0426 (deprecated way, totally ignored by some packagers) or patching requirements list in setup.py (bad looking way).

**Comment by asvetlov** [comment]
I think we'll drop 3.4 before adding type hints

**Comment by chrisimcevoy** [comment]
Can the "on hold" status be revoked now that 3.0 is out the door?

**Comment by webknjaz** [comment]
@chrisimcevoy is fairly hard to add typing everywhere instantly, but you are welcome to help with this by adding bit of type annotations in PRs ;)

**Comment by asvetlov** [comment]
How aiohttp 3.0 release is related to PEP 561 implementation?
mypy tool doesn't support it yet.
I don't want adding types without checking them like we don't write a code without adding unittests.
Maybe it is an acceptable practice for other projects but aiohttp assumes high code quality.

**Comment by chrisimcevoy** [comment]
@webknjaz Agreed. Gradual typing would be best. I would like to find time for a small-ish PR if it would aid discussion and get the ball rolling.

@asvetlov Apologies, I should have been more clear. I was referring to your earlier comment, that dropping Python 3.4 support was a prerequisite for type hinting aiohttp. If mypy support for PEP 561 is also a blocker, then so be it.

**Comment by asvetlov** [comment]
I hope mypy issue will be solved soon.

**Comment by asvetlov** [comment]
Blockers: python/mypy#4255 and python/mypy#4403

**Comment by asvetlov** [comment]
python/mypy#4693 is a new blocker

**Comment by asvetlov** [comment]
https://mypy.readthedocs.io/en/latest/installed_packages.html

**Comment by asvetlov** [comment]
We need to wait for mypy 0.590 release, after that setup mypy tool on travis and start adding annotations.
Multidict and Yarl should be adopted first.

**Comment by samuelcolvin** [comment]
v0.590 and v.600 are both released, what's the next step for this?

**Comment by asvetlov** [comment]
I have a #3049 
Not done yet, `make mypy` generates about a dozen errors.
Next `mypy` release should fix two of them (I've added `typeshed` stubs for `netrc` and `sys.implementation`.

Others should be fixed in the branch before merging.

The branch has a limited typing support, but after the merge we can do the rest in separate iterations.
