### ISSUE TITLE
obsolete reference to WSClientDisconnectedError

### ISSUE THREAD

**Issue by jwilk** [aio-libs/aiohttp#1751]
## Long story short

`docs/web_reference.rst` contains this line:

```
      :raise: :exc:`~aiohttp.errors.WSClientDisconnectedError` on closing.
```

But `WSClientDisconnectedError` has been removed in v1.1.0.

## Your environment

8a539ef8f8d5b6a301937b978b3edc3b0c270c1b

**Comment by fafhrd91** [comment]
thanks. removed ref
