### ISSUE TITLE
aiohttp.errors is gone

### ISSUE THREAD

**Issue by jwilk** [aio-libs/aiohttp#1753]
## Long story short

The `aiohttp.errors` module used to be public, documented API.
Now it's gone.

If this backwards-incompatible change is intentional, then it should be documented.

## Steps to reproduce

```console
$ python3 -c 'import aiohttp.errors'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'aiohttp.errors'

$ grep -Fcw aiohttp.errors CHANGES.rst HISTORY.rst 
CHANGES.rst:0
HISTORY.rst:0
```

## Your environment

aiohttp 2.0.3

**Comment by AraHaan** [comment]
yeah it sucks not being able to handle aiohttp exceptions if you wanted to. Unless I pull an hack and do this ``from aiohttp import errors``.

```
Python 3.6.0rc1 (v3.6.0rc1:29a273eee9a5, Dec  7 2016, 04:31:34) [MSC v.1900 32 b
it (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiohttp
>>> aiohttp.errors
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aiohttp' has no attribute 'errors'
>>> from aiohttp import errors
>>> dir(errors)
['BadHttpMessage', 'BadStatusLine', 'ClientConnectionError', 'ClientDisconnected
Error', 'ClientError', 'ClientHttpProcessingError', 'ClientOSError', 'ClientRequ
estError', 'ClientResponseError', 'ClientTimeoutError', 'ContentEncodingError',
'DisconnectedError', 'FingerprintMismatch', 'HttpBadRequest', 'HttpMethodNotAllo
wed', 'HttpProcessingError', 'HttpProxyError', 'InvalidHeader', 'LineLimitExceed
edParserError', 'LineTooLong', 'ProxyConnectionError', 'ServerDisconnectedError'
, 'TimeoutError', 'TransferEncodingError', 'WSServerHandshakeError', '__all__',
'__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '
__package__', '__spec__']
>>>
```

**Comment by fafhrd91** [comment]
`aiohttp.errors` was never ment to be used directly

**Comment by AraHaan** [comment]
Except when you want to handle aiohttp exceptions in another library (discord.py is one of those libraries) to know when you get an 200, 404, or w/e error code it returns or when the request was bad / invalid. They also use ``ServerDisconnectedError`` to know when to reconnect. (the service the library covers has an ``HEARTBEAT_ACK``)

**Comment by fafhrd91** [comment]
@jwilk updated are updated

**Comment by bartaelterman** [comment]
@fafhrd91 if your code raises those errors, why shouldn't we import them directly so we can catch them?

**Comment by fafhrd91** [comment]
Something like this should be enough:

```python

try:
    yield from aiohttp.request()
except aiohttp.ClientError as err:
    print(err)

```
