### ISSUE TITLE
ClientResponseError after upgrading to latest version

### ISSUE THREAD

**Issue by r0fls** [aio-libs/aiohttp#1754]
## Long story short

After the release of the latest version of aiohttp our unit tests started failing here:
https://travis-ci.org/channelcat/sanic

## Expected behaviour

The tests used to pass.

## Actual behaviour

Some of our tests now fail with `ClientResponseError("400, message='400, message='data received after completed connection: close message''",)`

## Steps to reproduce

This is only happening on travis.ci. I tried upgrading locally but the error doesn't occur there.

## Your environment

Travis.ci with the latest version of aiohttp on python 3.5 and 3.6.

I'm just wondering if anyone has any hints that could help fix this, since I haven't had the time to dig into it very much.

**Comment by fafhrd91** [comment]
hmm, I am not sure what this issue about. provide more information.
