### ISSUE TITLE
Deprecating default in `_request` timeout param?

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiohttp#1757]
in particular: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L150

given you can now set the conn + read timeouts in ClientSession, and the major changes in 2.x it seems like it would have been nice to set the default conn/read timeouts in clientsession to be something like `DEFAULT_TIMEOUT` and then set the default `_request` timeout to None.  Thoughts?  Sorry I didn't think about this earlier.

**Comment by fafhrd91** [comment]
it is possible to change/disable timeout per request. with default timeout in session, it would be not possible. but I don't have strong opinion on timeout

**Comment by thehesiod** [comment]
ya, I'm not saying to remove the param from `_request`, but change the default to `None`, and change the `ClientSession` `read_timeout` + `conn_timeout`  default to `DEFAULT_TIMEOUT`

**Comment by fafhrd91** [comment]
that is exactly what I mean. if you set default timeout on session, then it is not possible to disable timeout per-request, you'd need to create session with none as default timeout. and question is which behavior is better default.

**Comment by thehesiod** [comment]
oh, sorry, we could use a sentinel then.

**Comment by fafhrd91** [comment]
ok

**Comment by fafhrd91** [comment]
@thehesiod are you planing to work on this ticket? if not, lets just close it

**Comment by thehesiod** [comment]
k
