### ISSUE TITLE
I think there is a bug for using std http.cookies.SimpleCookie as a cookiejar in class ClientResponse !

### ISSUE THREAD

**Issue by ryanrain2016** [aio-libs/aiohttp#1758]
Firstly,I am sorry for my poor English!
I found a cute repo https://github.com/pandolia/qqbot a few days ago,but was discouraged by its poor performance.So,I tried replace requests.session with aiohttp.ClientSession.But I failed at the getVfwebqq step.Finally,I figured out where the problem laid. From the previous response,I got the cookie as below:
`['pt2gguin=o3422351980; EXPIRES=Fri, 02-Jan-2020 00:00:00 GMT; PATH=/; DOMAIN=qq.com;', 'uin=o3422351980; PATH=/; DOMAIN=qq.com;', 'skey=@htCMcHfYf; PATH=/; DOMAIN=qq.com;', 'p_uin=o3422351980; PATH=/; DOMAIN=web2.qq.com;', p_skey=t29vEql2SN6mmrMHi*aHalZnqhidEnAqgE9Bv9QugYg_; PATH=/; DOMAIN=web2.qq.com; ;', 'pt4_token=vM67W3HYBEkh8yBmzHAH4yD65uLHb47Z0k3E-crGhS0_; PATH=/; DOMAIN=web2.qq.com;', 'p_uin=; EXPIRES=Fri, 02-Jan-1970 00:00:00 GMT; PATH=/; DOMAIN=qq.com;', 'p_skey=; EXPIRES=Fri, 02-Jan-1970 00:00:00 GMT; PATH=/; DOMAIN=qq.com;', 'pt4_token=; EXPIRES=Fri, 02-Jan-1970 00:00:00 GMT; PATH=/; DOMAIN=qq.com;']`
after excuting 
`for hdr in self.headers.getall(hdrs.SET_COOKIE, ()):
            try:
                self.cookies.load(hdr)
            except http.cookies.CookieError as exc:
                client_logger.warning(
                    'Can not load response cookies: %s', exc)`
in client_reqrep.py,cookies was parsed as : 
`Set-Cookie: p_skey=; Domain=qq.com; expires=Fri, 02-Jan-1970 00:00:00 GMT; Path=/
Set-Cookie: p_uin=; Domain=qq.com; expires=Fri, 02-Jan-1970 00:00:00 GMT; Path=/
Set-Cookie: pt2gguin=o3422351980; Domain=qq.com; expires=Fri, 02-Jan-2020 00:00:00 GMT; Path=/
Set-Cookie: pt4_token=; Domain=qq.com; expires=Fri, 02-Jan-1970 00:00:00 GMT; Path=/
Set-Cookie: skey=@htCMcHfYf; Domain=qq.com; Path=/
Set-Cookie: uin=o3422351980; Domain=qq.com; Path=/`
The cookie with DOMAIN=web2.qq.com just disappeared or was overwrite.
The reason is  http.cookies.BaseCookie is derived from dict.Thus,no duplicate keys.And the author just assume that one response's cookies are all with the same one domain.So the cookie with same key although different domain will be overwrite.
I think it should be fixed! Thank you!

**Comment by blueyed** [comment]
What is `self.cookies` in `for hdr in self.headers.getall(hdrs.SET_COOKIE, ()): try: self.cookies.load(hdr)` ?

**Comment by blueyed** [comment]
Cookies are stored with their domain (https://github.com/aio-libs/aiohttp/blob/9504fe2affaaff673fa4f3754c1c44221f8ba47d/aiohttp/cookiejar.py#L184), and `filter_cookies` returns only a single value (the matching one for the URL): https://github.com/aio-libs/aiohttp/blob/9504fe2affaaff673fa4f3754c1c44221f8ba47d/aiohttp/cookiejar.py#L188-L226

So I think this can be closed, or more information should be provided.

**Comment by ryanrain2016** [comment]
@blueyed 
Thanks for the reply.
I am sorry to keep this thread so long.
This problem has been solved. The web I crawled has a redirect address with ip, so I should set up a unsafe=True CookieJar to deal with the cookie. There's nothing wrong here.
Thanks again.
