### ISSUE TITLE
support for ujson as json parser

### ISSUE THREAD

**Issue by penguinolog** [aio-libs/aiohttp#1760]
By default aiohttp.Session uses standard json, which is slow.

Allowing ujson via
```python
try:
    import ujson as json
except ImportError:
    import json
```
will reduce json processing time, if ujson is installed.

**Comment by popravich** [comment]
You can do this with two lines:
```python
import ujson
aiohttp.ClientSession(json_serialize=ujson.dumps)
```

**Comment by penguinolog** [comment]
Yep, just mine suggestion is for support it out of box without direct parser set.

**Comment by kxepal** [comment]
Why not rapidjson instead? It's faster.

But my point is that we cannot and shouldn't care about all the JSON implementations, but provide an easy way to use the one you like as default. And there is a support for that.

**Comment by popravich** [comment]
ASFAICS, `usjon` API is not compatible with stdlib `json`, for instance it serializes basically everything
in contrast to json where you need to pass `default` callback to serialize custom objects.
"Explicit is better than implicit" remember? )
Shadowing json with such a "try-import" might lead to random errors when one installation has usjon installed and other similar does not.

**Comment by penguinolog** [comment]
Accepted concern. Closing.

**Comment by fafhrd91** [comment]
added son_serialize info to client.rst
