### ISSUE TITLE
Sending a request with a body crashes if the server responds before the body is sent

### ISSUE THREAD

**Issue by arthurdarcet** [aio-libs/aiohttp#1761]
if the server handler is something like
```python
async def handler(request):
    return web.Response(text='ok')
```

then `session.post('…', data=b'0')` will crash (trying to write to a closed transport)

I'll submit a pull request for this next week (i have a memory leak i need to track down first)

**Comment by fafhrd91** [comment]
could you test this

**Comment by arthurdarcet** [comment]
yep perfect thanks
