### ISSUE TITLE
secure_proxy_ssl_header with gunicorn

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#1762]
## Long story short

I think it's not possible to set `secure_proxy_ssl_header` when deploying with gunicorn.

## Expected behaviour

gunicorn config or environment variable should allow me to set `secure_proxy_ssl_header='X-Forwarded-Proto'` so `request.scheme` is correct.

## Actual behaviour

No apparent way to set it.

## Steps to reproduce

Can give more detail if required.

## Your environment

Heroku, but should be the same with any other.

**Comment by samuelcolvin** [comment]
currently i'm using

```python
secure = 'https' in (request.scheme, request.headers.get('X-Forwarded-Proto'))
ws_scheme = 'wss' if secure else 'ws'
ws_url = f'{ws_scheme}://{request.host}/ws'
```

In addition to fixing `secure_proxy_ssl_header` it would be great if there was `request.secure: bool` to avoid the need for `== 'https'` etc.

**Comment by fafhrd91** [comment]
do you want to work on this?

**Comment by samuelcolvin** [comment]
Can do, just a key word argument to Application should work.
