### ISSUE TITLE
Connections are not correctly kept after HEAD requests

### ISSUE THREAD

**Issue by arthurdarcet** [aio-libs/aiohttp#1769]
When the client makes a HEAD request, it parses the response as if it was a regular message.

But the HTTP specs has a nice trick: HEAD requests `SHOULD` respond with the exact same headers than the corresponding GET request. This includes `Content-Length` or `Transfer-Encoding: chunked` headers.

This means that when the client receives a HEAD response with a `Content-Length: 5` response, it should not expect any body and `payload.is_eof()` should be True immediately, not after receiving 5 more bytes.

Currently `ResponseHandler.should_close` is True for HEAD requests with a `Content-Length: …` because `payload.is_eof()` is False when it should be True, hence the underlying connection is closed and not re-used when it could be.

This is only inefficient on the client side, not at all a bug, and does not produce any wrong results.

(also, I was mistaken a few minutes ago: returning a Content-Length header with an empty body is perfectly valid, and the `allow_head=True` parameter of the `add_get` method works perfectly well, no problem at all on the server side)

reproducer:
==========

https://github.com/aio-libs/aiohttp/issues/1769#issuecomment-614775045

**Comment by hubo1016** [comment]
Does aiohttp client support pipelining? If a client sends more than one requests on the same connection before server returns, this may be a problem if the client mistakenly parses the next respond as the respond body.

**Comment by fafhrd91** [comment]
client does not support pipelining, issue #1740

**Comment by sethmlarson** [comment]
Dropping in to say that I was bitten by this bug as well, took a few hours to debug why it was happening.

**Comment by webknjaz** [comment]
It'd be great if somebody could post a complete reproducer. Or better yet — a test marked with xfail as per https://pganssle-talks.github.io/xfail-lightning.

**Comment by sethmlarson** [comment]
Would something like this work?

```python
import aiohttp


async def test_head_request_reuses_connection():
    class SingleTCPConnector(aiohttp.TCPConnector):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._connections_created = 0

        def _create_connection(self, *args, **kwargs):
            self._connections_created += 1
            if self._connections_created > 1:
                raise ValueError("only one connection!")
            return super()._create_connection(*args, **kwargs)

    async with SingleTCPConnector(limit=1) as connector:
        for _ in range(2):
            async with aiohttp.request("HEAD", "http://example.com", connector=connector) as resp:
                await resp.read()
```

That test case fails for `HEAD` but passes for any other method.

**Comment by sethmlarson** [comment]
I have this as a simple reproducer locally FYI:

```python
import aiohttp


async def test_head_request_reuses_connection():
    class SingleTCPConnector(aiohttp.TCPConnector):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._connections_created = 0

        def _create_connection(self, *args, **kwargs):
            self._connections_created += 1
            if self._connections_created > 1:
                raise ValueError("only one connection!")
            return super()._create_connection(*args, **kwargs)

    async with SingleTCPConnector(limit=1) as connector:
        for _ in range(2):
            async with aiohttp.request("HEAD", "http://example.com", connector=connector) as resp:
                await resp.read()
```

Fails with `HEAD` but passes with all other methods.

**Comment by webknjaz** [comment]
@sethmlarson yeah, it'd be great if you could send that as a PR.
