### ISSUE TITLE
Document that WebSocketResponse.protocol is now called WebSocketResponse.ws_protocol

### ISSUE THREAD

**Issue by frederikaalund** [aio-libs/aiohttp#1771]
I recently upgraded to 2.0.0 and I didn't find this mentioned in the migration guide. The change was implemented in [this commit](https://github.com/aio-libs/aiohttp/commit/514179c46a8853ab9d5e6c5e29db664c29a86f1a).

**Comment by fafhrd91** [comment]
thanks

**Comment by fafhrd91** [comment]
added info
