### ISSUE TITLE
OAuth Server using aiohttp library

### ISSUE THREAD

**Issue by pvagare** [aio-libs/aiohttp#1776]
Hi All,

Should I create the OAuth Server using the aiohttp library?
Currently I am using the Flask. I want to shift from flask to aiohttp. How should Create the OAuthServer same like https://github.com/lepture/example-oauth2-server ? Please let me know as early as possible

**Comment by fafhrd91** [comment]
I do not know any existing solutions. overall example looks simple enough, should easy to reimplement in aiohttp.

**Comment by fafhrd91** [comment]
I do not think this is actionable
