### ISSUE TITLE
parse_frame receives a 1 byte buf when using proxy and fails to parse header

### ISSUE THREAD

**Issue by fatalis** [aio-libs/aiohttp#1777]
When I use a proxy (Burp Suite) on the websocket client, I get "Received frame with non-zero reserved bits". Problem line is here:
https://github.com/aio-libs/aiohttp/blob/c715ad589e8dc59df23ebe01e0d01b1ac7985fbd/aiohttp/http_websocket.py#L281

**Comment by fafhrd91** [comment]
I do not have much experience with web socket proxies, try to remove check for 0 in web socket parser and what happen

**Comment by fatalis** [comment]
link line please..

**Comment by fafhrd91** [comment]
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/http_websocket.py#L300

**Comment by fafhrd91** [comment]
ping

**Comment by fafhrd91** [comment]
reopen, if you have more info
