### ISSUE TITLE
aiohttp.ClientResponse .json() method returns a generator with non retrievable JSON result embedded  

### ISSUE THREAD

**Issue by rohansb** [aio-libs/aiohttp#1795]
## Long story short

aiohttp.ClientResponse .json() method returns a generator with non retrievable JSON result embedded  
Not able to retrieve expected JSON object is a big deal!! 

I am struggling with this error for a few days now, Please review what i might be missing or if its a real bug

## Expected behaviour

futures task.result().json()  should return a json dict object as documented here:
http://aiohttp.readthedocs.io/en/stable/client_reference.html#aiohttp.ClientResponse.json

## Actual behaviour

futures task.result().json() returns an unexpected `generator-object`
upon doing `next(generator-object)` it issues a StopIteration exception
within the exception i could see the json embedded as a part of the exception message
sample output: https://gist.github.com/rohansb/4ba6295aa2c8f3fa44f9ed03ad950d1c

## Steps to reproduce

Code:
https://gist.github.com/rohansb/8fa125ec34d23a319e647993507d327c
Line number 158 is where it errors out, and produces the anticipated JSON as the part of the exception itself

## Your environment

python 3.5
requirements:
- asyncio
- aiohttp
- werkzeug

**Comment by kxepal** [comment]
>  data = await task_result.json()

since `ClientResponse.json()` is a coroutine.

**Comment by rohansb** [comment]
ClientResponse.json()  will always be a co-routine?
I was under the impression that, i have received all the response with get requests already but apparently not. Is there anything i could do to make sure that i have all the responses back before i can get data out of response objects?
so you are suggesting process_job_response should also be a co-routine and should be passed to something like run_until_complete from the same event loop i have created, is that correct?

**Comment by kxepal** [comment]
It always was, it always now. Won't tell for the whole the future, but it tends to be so.

**Comment by rohansb** [comment]
Thanks so much for your quick responses.

I got it working, although now i am running into random number of successful responses and rest of it as **ConnectionErrors**

Please advice. 
Error: https://gist.github.com/rohansb/07c642e20e653e0ecc29d411d3a6af62
Updated code is here: https://gist.github.com/rohansb/8fa125ec34d23a319e647993507d327c

this feels like i am failing to ensure futures?
