### ISSUE TITLE
aiohttp 2.0.x regression on timeouts (proxy combined with throttling through Semaphore?)

### ISSUE THREAD

**Issue by MRigal** [aio-libs/aiohttp#1797]
## Long story short

Exactly the same code runs on aiohttp 1.3.x and fails in 2.0.5

## Expected behaviour

I use async.gather() to create 1000 futures occurence of an API call, where timeout is set to 5 secs.
I use a semaphore to limit to 100 the amount of parallel running requests.
When running on 2.x it works if I do not use a proxy, but it fails if I define a proxy.
The whole process should take around 20s and does so on aiohttp 1.3.5

## Actual behaviour

After 5 seconds, the requests are failing due to TimeoutError. I fear the proxy connections of the futures are started (aenter) all at once, not when the semaphore actually releases them and thus a TimeoutError is probably raised before the requests were actually sent out.

## Steps to reproduce

I've tried to describe it above. My code is actually pretty complex, but as I said a simple downgrade of aiohttp fixes the problem.
Maybe the description is enough to fix the bug. Else, if required, I could try to write a proper test, but this is not so tricky as it requires finding real-life API calls to be made to trigger the timeouts... Maybe the description is enough...

## Your environment

Ubuntu 16.04, python 3.6.0 or 3.5.1, pyenv virtualenv and proxy in local network

**Comment by fafhrd91** [comment]
it is hard to say what is the problem. timeouts and connection limits are changed significantly in 2.0

with 2.0 you don't really need separate semaphore, you can use "limit" parameter for TcpConnection,
it limits number of concurrent requests.

**Comment by fafhrd91** [comment]
as example for this kind of test you can use test_client_functionional.py 
you can start local http server and implement exact logic you need

**Comment by MRigal** [comment]
Thanks @fafhrd91 for pointing to the right test, I might try to write something if I can find the time for it...

Just as a note: I am using the semaphore also because behind these 1000 queries (which are even more on production), I have the same amount of read to the DB (!) And I don't want to build up thousands of connections. The advantage of the semaphore is that it should limit all async functions underneath. This is why I think that aiohttp should handle it properly in the version 2.x also! :)

**Comment by fafhrd91** [comment]
I don't see any reason why it should not. Default limit is 100, try to set it to 0



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MRigal** [comment]
You might have misunderstood me. I have no doubt "limit" is working for TcpConnection.
Just that I want to use the semaphore for a block of commands using different async frameworks (DB and aiohttp). And probably the semaphore is actually in terms of calls used properly by aiohttp, but at least not on the timing level as it raises these TimeoutErrors. 
I guess the timing is instantiated at future creation and not when the call is actually issued :-/

**Comment by fafhrd91** [comment]
I don't see reasons why Semaphore should not work. 

yes, timer starts when you make `client.request()`, so if it hit connection limit it would count against this timer. try to create connector with "limit=0", this will effectively turn off limitations on aiohttp side.

**Comment by fafhrd91** [comment]
did you able to build test case?

**Comment by MRigal** [comment]
I will try, but it's pretty hard to isolate

**Comment by MRigal** [comment]
@fafhrd91 I was able to write a "strange test" that can reproduce the "wrong" timeouts I am noticing.

You can find it on that branch: https://github.com/orderbird/aiohttp/tree/1797-timeout-regression

However, the same test rebased against 1.3.x is also (although differently) failing :-(, contrary to the behaviour I could observe with my software :-/
https://github.com/orderbird/aiohttp/tree/1797-on-1x-timeout-regression

I let you eventually check out these branches and play a bit around, also with the different possible settings I am using with pytest.parametrize

I will also on my side try to enhance this tomorrow...

**Comment by fafhrd91** [comment]
actual behavior is right, from asyncio perspective. problem is that gather() does not protect from exceptions and if timeout get raised it bubbles up to `asyncio.gather(*rows)` line.

you need to shield line "resp = await session.get(server.make_url('/'), timeout=0.1)"

this is confusing, I think we should add some code to do this kind of queries.

**Comment by MRigal** [comment]
@fafhrd91 as mentioned in the PR, I could put in evidence that this happens only when using a proxy. But I was not able to write a good enough test, nor do I know what to do to "shield line"

**Comment by fafhrd91** [comment]
I will write example later today, then it should be more obvious what is the problem

**Comment by MRigal** [comment]
OK at the end, it is even not the issue of a proxy... I have now a failing test that shows a clear difference of behaviour without any proxy but that I couldn't reproduce with a local server...
Besides that case, I still encounter a real regression on 2.0.x towards 1.3.x when using a proxy, even when setting `limit=0` on the connector
