### ISSUE TITLE
Unable to set response.content_length

### ISSUE THREAD

**Issue by iceboy233** [aio-libs/aiohttp#1801]
## Long story short

Unable to set response.content_length

## Expected behaviour

```
>>> from aiohttp import web
>>> r = web.Response()
>>> r.content_length = 1
```

## Actual behaviour

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_response.py", line 561, in content_length
    super().content_length = value
AttributeError: 'super' object has no attribute 'content_length'
```

## Your environment

aiohttp 2.0.6
python 3.5.2

**Comment by kxepal** [comment]
Interesting. Any reasons to do that?

**Comment by asvetlov** [comment]
Current implementation is obviously buggy but I believe `Response.content_length` setter should raise `RuntimeError` unconditionally.
Length might be assigned for `StreamResponse` only.

**Comment by fafhrd91** [comment]
fixed

**Comment by iceboy233** [comment]
imo the correct way should be removing `content_length.setter`?
