### ISSUE TITLE
response.text() crash if body contain non UTF-8 symbol

### ISSUE THREAD

**Issue by Dexus77** [aio-libs/aiohttp#1802]
## Long story short
Unfortunately the world is not perfect. 
Server in body UTF-8 can return non UTF-8 character.

Content-Type:      text/html; charset=utf-8

<a href="/те(bad symbol)нополь">

Error: utf-8' codec can't decode byte 0x80 in position 19404: invalid start byte

**Comment by kxepal** [comment]
I guess, for imperfect servers you should use [`.read()`](http://aiohttp.readthedocs.io/en/stable/client_reference.html#aiohttp.ClientResponse.read) instead and satinize all the bad symbols in the way you think it's right. I don't think there is a good strategy to deal with non UTF-8 symbols in UTF-8 response except to raise an exception.

**Comment by Dexus77** [comment]
OK. Thanks for the quick reply.
