### ISSUE TITLE
Unable to iterate over chunks as sent by server.

### ISSUE THREAD

**Issue by ahane** [aio-libs/aiohttp#1805]
## Long story short

I am talking to a HTTP server that uses `transfer-encoding: chunked` to stream records, whith each chunk representing one record. 
aiohttp currently offers no API for iterating over the chunks exactly as sent by the server.

## Expected behaviour

I would expect the response.content.iter_chunked(n) method to default to the chunking already defined by the server if n=None or a special flag is passed.

See the [similar method in the Requests library](http://docs.python-requests.org/en/master/api/#requests.Response.iter_content) that shows the desired behaviour.

## Actual behaviour

n=None returns an empty bytestring, while n=-1 doesn't return at all.

There is no method to recover the chunking of the server.

**Comment by fafhrd91** [comment]
you can use `readany`, it returns data available in buffer. but right now it is not possible.
would you like to provide PR?

**Comment by ahane** [comment]
yes ;) readany does join all chunks in the buffer into one bytestring though
https://github.com/aio-libs/aiohttp/pull/1806

**Comment by fafhrd91** [comment]
fixed by you :)
