### ISSUE TITLE
[Tracking] SSL leak in python versions >= 3.5.3

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiohttp#1809]
This bug is just a marker to let other people know that this is an issue, but not in aiohttp...so if they google for this issue they can find what the real issue is.

Per my research in https://github.com/kennethreitz/requests/issues/3933 I found that the underlying Python SSL sockets are leaking.  I logged http://bugs.python.org/issue29870 where they recently found and proposed a patch to fix this leak.  I'll close this as soon as they're released new versions of python with the fix.

I'm not sure if it's worthwhile adding a warning to let users know that certain python versions will leak when using SSL sockets.

**Comment by Fitblip** [comment]
Damn, huge props @thehesiod for digging into this. I was at the cusp of starting to really dig into the cause of this leak as well, but you just saved me many hours of pulling out my hair!

Do you know if there's a workaround for this issue yet? Thankfully for my use case SSL isn't 100% necessary, but it'd be nice to be able to keep it enabled. 

Thanks again!

**Comment by fafhrd91** [comment]
@Fitblip you can use uvloop

**Comment by thehesiod** [comment]
i don't think uvloop will help, the issue is with the raw python SSL sockets.  Per Christian Heimes + Antoine Pitrou in the python bug, the issue is with crlDistributionPoints in the SSL certificates.  So theoretically if you don't have certs that have these it shouldn't leak.

**Comment by Fitblip** [comment]
@fafhrd91 - The leak still seems present even if I use uvloop. When I switch all my aiohttp requests to plain-text HTTP though the leak goes away.

**Comment by fafhrd91** [comment]
I guess uvloop should not use ssl from python

**Comment by thehesiod** [comment]
will be fixed in 2.7.14, 3.5.4, 3.6.2: https://github.com/python/cpython/pull/526
