### ISSUE TITLE
Working with aiohttp.ClientSession from a command line

### ISSUE THREAD

**Issue by vladyslav2** [aio-libs/aiohttp#1812]
Hello.

Pretty simple question but still I'm not sure how to solve it.
Before creating a code i'm usually playing with ipython to check if i have right idea to solve a task.
But i got an issues with ClientSession:
```
ipython:
...
# session = loop.run_until_complete(aiohttp.ClientSession())
```

Will return error:
```
Traceback (most recent call last):
  File "image_migrations.py", line 69, in <module>
    session = loop.run_until_complete(aiohttp.ClientSession())
  File "uvloop/loop.pyx", line 1181, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25184)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 519, in ensure_future
    raise TypeError('A Future, a coroutine or an awaitable is required')
```

But if I will do:
```
session = aiohttp.ClientSession()
```

I will get a warning:
```
ERROR:asyncio:Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x103ec10b8>
```

Sorry for dumb question, but what i'm doing wrong?

**Comment by fafhrd91** [comment]
session.request() is a coroutine. `run_until_complete()` requires a coroutine.

For unclosed, just close session with session.close()

**Comment by fafhrd91** [comment]
i.e. run_until_complete requires a coroutine

**Comment by vladyslav2** [comment]
@fafhrd91 aiohttp.ClientSession() is coroutine ? 
if not why does in documentation i can see this example:
`async with aiohttp.ClientSession() as session:` ?

**Comment by fafhrd91** [comment]
"async with" is not "await". with async with, you create session and then wait. While your code uses session contractor as a cotoutine

**Comment by vladyslav2** [comment]
@fafhrd91 sorry, I red `await` instead of `async`

But still, in command line:
```session = aiohttp.ClientSession()```
why does i get error
```
ERROR:asyncio:Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x103ec10b8>
```

PS i updated origin post - i got different error
?

**Comment by fafhrd91** [comment]
well, it is not good idea creating session outside of async environment.

to silence this warning you can use `aiohttp.ClientSession(loop=asyncio.get_event_loop())`

**Comment by asvetlov** [comment]
You might try [asyncronous python console](https://github.com/vxgmichel/aioconsole) for easy experimenting with `await` syntax etc.

**Comment by vladyslav2** [comment]
@fafhrd91 thank you for you reply

@asvetlov thanks, i saw aioconsole, but i like ipython.
But raw python console hard to use sometimes :)
