### ISSUE TITLE
Package aiohttp-2.0.6-1.tar.gz make PyPI reports a inexistent 2.0.6.post1 release for pip

### ISSUE THREAD

**Issue by osantana** [aio-libs/aiohttp#1815]
## Long story short

There is a `aiohttp-2.0.6-1.tar.gz` at aiohttp's PyPI that `breaks pip.index.PackageFinder` that returns an inexistent `2.0.6.post1` release.

When I ran a tool to update project requirements (like `pip-tools` or an IDE like PyCharm) they report an release newer than `2.0.6` (`2.0.6.post1`) that cannot be installed correctly.

```
DEBUG:pip.index:Found link https://pypi.python.org/packages/66/3f/eac06f68743e2654915650de34893391ff1006cd144a48655d2f75084e17/aiohttp-2.0.6-1.tar.gz#md5=1720
```
## Steps to reproduce

```python
>>> from requests import Session
>>> from pip.index import PackageFinder
>>> f = PackageFinder(index_urls=['https://pypi.python.org/simple'], find_links=[], session=Session())
>>> c = f.find_all_candidates("aiohttp")
>>> [str(x.version) for x in c if "2.0.6" in str(x)]
['2.0.6', '2.0.6.post1']
```

Trying to install it:

```shell
Collecting aiohttp==2.0.6.post1
  Downloading aiohttp-2.0.6-1.tar.gz (1.1MB)
  Requested aiohttp==2.0.6.post1 from https://pypi.python.org/packages/66/3f/eac06f68743e2654915650de34893391ff1006cd144a48655d2f75084e17/aiohttp-2.0.6-1.tar.gz#md5=17207ea5e9fe0a4e16d2cc02f683efe2, but installing version 2.0.6
```

## Fix proposal

Remove `https://pypi.python.org/packages/66/3f/eac06f68743e2654915650de34893391ff1006cd144a48655d2f75084e17/aiohttp-2.0.6-1.tar.gz` from PyPI.

**Comment by fafhrd91** [comment]
should be fixed in 2.0.7 release
