### ISSUE TITLE
HTTP protocol using picohttpparser

### ISSUE THREAD

**Issue by mosquito** [aio-libs/aiohttp#1820]
The Python-based HTTP protocol is too slow compared with [picohttpparser](https://github.com/h2o/picohttpparser).

Is it possible to integrate aiohttp with [picohttpparser](https://github.com/h2o/picohttpparser)?

**Comment by kxepal** [comment]
Python-based parser is a fallback one. aiohttp uses nginx-based parser if you have Cython installed.

See also: https://github.com/aio-libs/aiohttp/issues/1722

**Comment by mosquito** [comment]
Thank you
