### ISSUE TITLE
API signatures in docs do not match APIs anymore

### ISSUE THREAD

**Issue by hynek** [aio-libs/aiohttp#1822]
I’ve run into it with TCPConnector that happily declares that it accepts `conn_timeout` but it’s nowhere to be found when the parameters are described.  I suspect this problem is much more pervasive.

**Comment by fafhrd91** [comment]
PR is welcome!

**Comment by asvetlov** [comment]
The concrete `conn_timeout` is fixed in aiohttp 2.3
Feel free to create a new issue if find something.
