### ISSUE TITLE
What happens when a WebSocket Server is publishing faster than a Client?

### ISSUE THREAD

**Issue by vrde** [aio-libs/aiohttp#1823]
## Long story short
What happens if the client is not consuming the events coming from the server? Can a malicious client jam the server?

Those two links might be relevant to understand the problem:
 - [what happens when tcp/udp server is publishing faster than client is consuming?](http://stackoverflow.com/questions/1997691/what-happens-when-tcp-udp-server-is-publishing-faster-than-client-is-consuming)
 - [Write completion flow control](http://www.lenholgate.com/blog/2008/07/write-completion-flow-control.html)
 - [TCP flow control and asynchronous writes](http://www.serverframework.com/asynchronousevents/2011/06/tcp-flow-control-and-asynchronous-writes.html)

I dug in the code, the closest thing I've found about handling buffers is the [`drain`](https://github.com/aio-libs/aiohttp/blob/d08651ce281abed518c0bcefedd03cfc72b07a74/aiohttp/http_writer.py#L118) method. 

*Side note*: I'm not familiar with the `aiohttp` code base, but I noticed that `drain` is a coroutine that is eventually called by `send_str`, but `send_str` is not a coroutine, is it a problem?

## Expected behaviour

The server should stop writing to that specific WebSocket, or overwrite the buffer with the new data.

## Actual behaviour

I've no idea.

### Client code
After connecting to the server, the client starts twiddling its thumbs.

```python
# Client

import asyncio
import aiohttp


async def run(session):
    async with session.ws_connect('http://localhost:8080/') as ws:
        while True:
            await asyncio.sleep(1000)

session = aiohttp.ClientSession()
loop = asyncio.get_event_loop()
loop.run_until_complete(run(session))
```

### Server code
On the other side, the server works hard to deliver it's extremely important kilobyte of `a`s
```python
# Server

import asyncio
from aiohttp import web


async def websocket_handler(request):
    ws = web.WebSocketResponse()
    await ws.prepare(request)

    s = 'a' * 1024

    i = 0
    while True:
        i += 1
        print('send ', len(s) * i)
        ws.send_str(s)
        await asyncio.sleep(0.1)

    return ws


app = web.Application()
app.router.add_get('/', websocket_handler)
web.run_app(app)
```
## Your environment

Python 3.6+aiohttp-2.0.7 on a Ubuntu machine.

**Comment by fafhrd91** [comment]
jus use "await ws.send_str(..)", this will take care on back-pressure

**Comment by fafhrd91** [comment]
buffer is 64k though

**Comment by vrde** [comment]
Hi @fafhrd91, thanks for your answer.

> jus use "await ws.send_str(..)", this will take care on back-pressure

I'm confused. If `ws.send_str(...)` is a coroutine, why the [examples in the docs](http://aiohttp.readthedocs.io/en/stable/web.html#websockets) are not using the `await` keyword?

> buffer is 64k though

What happens when the buffer is full and the server tries an `await ws.send_str('some data')`?
