### ISSUE TITLE
bools in params are treated differently from bools in formdata

### ISSUE THREAD

**Issue by nlitsme** [aio-libs/aiohttp#1824]
## Long story short

When using the `ClientSession.post` method, 
both the url parameters and form post data can be passed as a dictionary.
In the url parameter dictionary you cannot pass boolean values, while you can in the form dictionary.

## Expected behaviour

I expect both the form and url parameter encoding to behave in a similar way,
so passing a boolean in a url parameter dict will be converted to a string "True" or "False".

## Actual behaviour

Instead i get an exception:

    Invalid variable type: mapping value should be str or int, got True

Traceback:
 * `yarl/__init__.py`  line 737 in `with_query`
 * `aiohttp/client_reqrep.py` line 71, in `__init__`

## Steps to reproduce

```python
import asyncio
import aiohttp


client = aiohttp.ClientSession()

async def trypost(urlparam, formparam):
    try:
        response  = await client.post("http://example.com/", params={"urlparam":urlparam}, data={"formparam":formparam})
        response.close()
        print((urlparam, formparam), "->", response)
    except Exception as e:
        print((urlparam, formparam), "->", e)

tasks = [
        trypost("true", True),
        trypost(True, "true"),
]

loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.gather(*tasks))

client.close()
```

## Your environment

I am using aiohttp v2.0.7

**Comment by fafhrd91** [comment]
@kxepal what should we do?

**Comment by kxepal** [comment]
> I expect both the form and url parameter encoding to behave in a similar way, so passing a boolean in a url parameter dict will be converted to a string "True" or "False".

Actual problem is in expectations. `"True"` and `"False"` are oblivious candidates, but most of API in the world accepts booleans as `true` and `false` - I never saw the ones who prefer Python-like bools. Some of the APIs expects bools as `1` or `0`. 

So evern if the cover some cases there still be the rest where you'll have to override bool encoding rules.

**Comment by fafhrd91** [comment]
I do not feel good about converting bool to string

**Comment by kxepal** [comment]
So do I. It's not clear how to do that to fit everyone.

**Comment by fafhrd91** [comment]
does anyone know what is request's behavior?

**Comment by kxepal** [comment]
requests does `str` on boolean values. Sweet, but not very helpful in real.

**Comment by asvetlov** [comment]
I suggest to keep existing behavior
