### ISSUE TITLE
Faster websocket masking

### ISSUE THREAD

**Issue by willmcgugan** [aio-libs/aiohttp#1827]
## Long story short

I recently came up with a way of doing websocket masking that is faster than the current implementation. (please see https://www.willmcgugan.com/blog/tech/post/speeding-up-websockets-60x/). I'd be happy to create a PR, if you think it would be worth updating.

**Comment by fafhrd91** [comment]
sure.
did you do tests against _websocket.pyx?

read your article this morning :)

**Comment by willmcgugan** [comment]
I added _websocket.pyx to the [graph](https://www.willmcgugan.com/blog/tech/post/speeding-up-websockets-60x/#figure_2), and it compared very well indeed!

Create a PR https://github.com/aio-libs/aiohttp/pull/1838

**Comment by fafhrd91** [comment]
Fixed by #1838
