### ISSUE TITLE
The EOF stream cause the reserved bits error

### ISSUE THREAD

**Issue by yxzhm** [aio-libs/aiohttp#1829]
## Long story short
The 'resp.write_eof()' cause the Error "One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1" in client. It looks the error happens in self.transport.write(b'0\r\n\r\n') under aiohttp.protocal.py.
**I don't know shall I remove the yield from resp.write_eof() at the ending.**

I have posted my code as following:
`
    
status, headers, parser, writer, wsprotocol = websocket.do_handshake(

            message.method, message.headers, self.transport)
            resp = aiohttp.Response(self.writer, status)

            resp.add_headers(*headers)

            resp.send_headers()

           .........

            yield from proxy.handle_connection(server, app_id)

            yield from resp.write_eof()`

## Expected behaviour

In Chrome, there is no reserved error message.

## Actual behaviour

I can see this error message in Chrome console.

## Your environment
OS: Windown7 64 bit
aiohttp: 0.16.2 / 1.3.5 
In my project, I still refer to the old version 0.16.2, But I tried the 1.3.5. This error message still can be reproduced.

**Comment by fafhrd91** [comment]
I think your refer to old (removed) internal api. for server you have to use aiohttp.web.WebSocketResponse()

**Comment by yxzhm** [comment]
Before I close the Websocket, shall I still send the EOB stream?
Thank you.

**Comment by fafhrd91** [comment]
Websocket connection requires closing procedure. But you can close itimmidietly. WebSocketResponse implements it, you can see it in web_ws.py in master
