### ISSUE TITLE
Streaming uploads doesn't seem to work

### ISSUE THREAD

**Issue by tailhook** [aio-libs/aiohttp#183]
The functionality described here:
http://aiohttp.readthedocs.org/en/v0.11.0/client.html#streaming-uploads

Doesn't actually work as advertised. I.e. as much as producer is able to produce will be buffered in the output buffer. Seems either some `drain()` calls should be added or another type of data producer might be invented.

**Comment by fafhrd91** [comment]
will fix within #1172 context
