### ISSUE TITLE
Subsecond timeouts

### ISSUE THREAD

**Issue by gsakkis** [aio-libs/aiohttp#1835]
## Long story short

It seems that aiohttp rounds up epoch times and timeouts using `math.ceil`, effecitvely preventing timeouts of less than 1 second.

## Expected behaviour

Subsecond timeouts should be supported, at least at the millisecond level.

## Actual behaviour

Subsecond timeouts are not respected.

## Steps to reproduce

I stumbled on this issue while trying unsuccessfully to write a unit test that tests timeouts, until I came across some related tests in aiohttp itself that [patch `aiohttp.helpers.ceil` to be a no-op](https://github.com/aio-libs/aiohttp/blob/master/tests/test_client_functional.py#L580). Without the patch these tests (usually) fail.

## Your environment

`aiohttp==2.0.7`

**Comment by fafhrd91** [comment]
that is explicit decision. maybe we should add helper method or automatically patch ceil for tests

**Comment by gsakkis** [comment]
That seems odd; what's the rationale for the decision? At the very least this should be documented and ideally expose a way to disable it, not just for tests.

**Comment by fafhrd91** [comment]
Performance reasons. I think we added ceil relatively long time ago.

**Comment by asvetlov** [comment]
There is no practical reason for timeouts lesser than 1 sec except testing.
But even for testing purposes better to use specialized testing event loop like asyncio itself does.

**Comment by asvetlov** [comment]
Let's close it as "wont fix"

**Comment by gsakkis** [comment]
I must be missing something. 1 second is a [noticeable delay](https://www.nngroup.com/articles/response-times-3-important-limits/) for web page/app end users, let alone API servers that often have latency requirements of less than 100ms.

**Comment by fafhrd91** [comment]
aiohttp timeout is at the same level as default request timeout, which is 5 minutes. also aiohttp timeout is timeout for complete request, from start to finish. 

if you need sub seconds timeout, you can disable aiohttp timeout and use async_timeout with any precision level.

**Comment by gsakkis** [comment]
Thanks, async_timeout works for me. I still think this behaviour (and the async_timeout workaround)  should be documented to prevent others tripping on it.

**Comment by asvetlov** [comment]
@gsakkis this issue is the first request for subsecond timeouts.
It means the need is very rare (and there is workaround with timeout disabling and using `async_timeout` as @fafhrd91 mentioned).
But if you think the behavior should be explicitly documented -- please make a PR for documentation update.
