### ISSUE TITLE
Fix async_timeout and and asyncio.Task.current_task usage

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1837]
I just realized that it is not possible to customize `asyncio.Task.current_task` behavior.
it is f..cking not possible! "current_tasks" variable is defined in c module as static variable.

**Comment by kxepal** [comment]
How did you plan to modify it? Just curious.

**Comment by argaen** [comment]
+1, also why do you want to modify it? The behavior of current_task does what it is expected to and its simple enough: https://github.com/python/cpython/blob/master/Lib/asyncio/tasks.py#L47

**Comment by fafhrd91** [comment]
@kxepal yes, seems we don't have much options.

@argaen I am working on alternative event loop implementation. And right now there is no any way how custom task implementation can participate in current_task() api. You point to python impl, in c ext private static variable is used, so you can not access internal var at all. 

Btw We say that tornado should implement this API to support aiohttp timeouts, but it is not possible at all.

**Comment by asvetlov** [comment]
Keep calm please.
`current_task()` is an Public API.
I recall discussion about adding `Task.register_task` and `Task.unregister_task` static methods but it wasn't implemented in Python 3.6.

I want discuss the issue on US PyCon next month.

**Comment by fafhrd91** [comment]
I think better api would be "loop.current_task()" in that case each event loop can provide its own implementation.

PS you should return back to active development

**Comment by asvetlov** [comment]
If you are implementing custom task class you could register it via `loop.set_task_factory`.
Does it satisfy your needs?

**Comment by fafhrd91** [comment]
I implement everything.

**Comment by fafhrd91** [comment]
I need your help, so we can push changes to python faster

**Comment by fafhrd91** [comment]
here are two monkey patches that I need to apply to make asyncio work 

https://github.com/fafhrd91/aiohttp-tokio/blob/master/aiohttp_tokio/patch.py

**Comment by asvetlov** [comment]
So if you have own loop and own task why do you care about C private variable for CPython task implementation?

**Comment by fafhrd91** [comment]
because you can not participate in Task.current_task() call. there is no way how to set current task

**Comment by fafhrd91** [comment]
also asyncio utility functions uses private attributes, so you have to provide private attributes to make public api work

**Comment by fafhrd91** [comment]
https://github.com/fafhrd91/async-tokio/blob/master/src/pytask.rs#L72
https://github.com/fafhrd91/async-tokio/blob/master/src/pytask.rs#L93
https://github.com/fafhrd91/async-tokio/blob/master/src/pytask.rs#L170
https://github.com/fafhrd91/async-tokio/blob/master/src/pytask.rs#L176

this is kind of ugly too
https://github.com/fafhrd91/async-tokio/blob/master/src/pytask.rs#L185

**Comment by asvetlov** [comment]
@1st1 could you take a look?

**Comment by fafhrd91** [comment]
@asvetlov hey, do you have plans to work on aiohttp? or you are not interested in aiohttp anymore?

**Comment by asvetlov** [comment]
Sure, I have.

**Comment by fafhrd91** [comment]
we have so much tasks, and I don't have enough time for everything

**Comment by 1st1** [comment]
> So it seems like asyncio devs say "go f..ck yourself" to developers who try to implements custom loop.

I'm a bit surprised to hear this since there are asyncio developers who implemented their own custom loops :)

Speaking of `Task.current_task` - yes, the API is decoupled from the loop, and yes it complicates things if you want to provide your own implementation of `Task`. But that's why I invested a lot of effort into writing a fast C version of `asyncio.Future` and `asyncio.Task`. They work fast (I doubt you can make it any faster with Rust or whatever else) and are compatible with any alternative loop. 

Anyways, I'm working on a PEP to propose asyncio improvements in 3.7. I'll think about adding `loop.current_task()` and deprecating `Task.current_task`. While this is important for project like Tornado (to improve compat), I don't think this is otherwise a deal breaker.

**Comment by fafhrd91** [comment]
it is not about speed, it is about different implementation. I am building event loop based on tokio-rs (rust), and I want be able to participate in tokio loop.

**Comment by 1st1** [comment]
> [..] I want be able to participate in tokio loop

Can you expand on this? I.e. what specific functionality you are trying to implement that forces you to rewrite `Task` in Rust?

**Comment by fafhrd91** [comment]
I want to be able to write code in rust and python and run both within same process and event loop. and I want to be able seamlessly mix and match both

**Comment by 1st1** [comment]
> I want to be able to write code in rust and python and run both within same process and event loop. and I want to be able seamlessly mix and match both

OK, I understand now.

But FWIW you can implement Future-like object in Rust and it would work just fine, right? It's that `Task.current_task` wouldn't point to the correct Rust-task?

**Comment by fafhrd91** [comment]
that is right. "loop.current_task()" is preferable way, but something like "Task.set_current_task()" would work too

**Comment by fafhrd91** [comment]
added "loop.current_task()", but I'd prefer to have official api for this.
