### ISSUE TITLE
Make resolving a url easier

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#1846]
## Long story short

Assuming there's a resource `/foo/bar/`, I want (like in django) a request to `/foo/bar` to be redirected (301) to `/foo/bar/`. 

I don't want this to be built into aiohttp, it's very simple in middleware and belongs outside the main repo, however currently it involves calling numerous private methods.

## Expected behaviour

`request.app.router.resolve_str('/foo/bar/')` (or whatever) to return information about the associated resource

## Actual behaviour

My current solution is

```python
except HTTPException as e:
    if request.method == METH_GET and e.status == 404 and not request.rel_url.raw_path.endswith('/'):
        possible_path = request.rel_url.raw_path + '/'
        for resource in request.app.router._resources:
            match_dict = resource._match(possible_path)
            if match_dict:
                raise HTTPMovedPermanently(possible_path)
```

Note the use of private properties.

**Comment by fafhrd91** [comment]
is this middleware that you need?
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_middlewares.py#L25

**Comment by samuelcolvin** [comment]
That's good to know, thank you. Unfortunately, the situation is slightly more complicated, I lied slightly in my issue: I actually built my app (wrongly in retrospect) the other way round: urls do not have trailing slashes. So the middleware has to remove slashes rather than add them.

Unfortunately, others have now integrated with the API so it's not simple to switch. The middleware I'm using is https://github.com/tutorcruncher/socket-server/blob/2f7d18093e38fb78994c941eb797f5da9ccaccb0/tcsocket/app/middleware.py#L59-L64

I still think for other cases it would be useful to have a `resolve()` method which doesn't require me to create a dummy request object to evaluate it.

**Comment by fafhrd91** [comment]
Ok, what is your proposal?

**Comment by asvetlov** [comment]
Resolver could potentially rely not only on *url* but for example on *HOST* header or even on `Content-Type`.
Thus properly constructed `Request` is necessary.
 I suggest to close the issue.
