### ISSUE TITLE
how to specify log request format in aiohttp

### ISSUE THREAD

**Issue by jacopofar** [aio-libs/aiohttp#1850]
I can't find a way to set the access log format with aiohttp2.
The [documentation](https://aiohttp.readthedocs.io/en/stable/logging.html) gives a list of placeholder for the log components, but I don't understand where I should put them to obtain a log in a custom format.

I found only [this usage](https://github.com/aio-libs/aiohttp-devtools/blob/bf97ba10b2b2b889c04fc30e0299aa158a383dec/aiohttp_devtools/runserver/serve.py#L83) so I tried to follow that method:
```
mylogger = logging.Logger('aiohttp.access')
mylogger.setLevel(logging.DEBUG)
mylogger.addHandler(ch)

handler = app.make_handler(
        logger=mylogger,
        access_log_format='%r %s %b',
)
```

but it does produce a log at all.

Is there a code example to use this logging microformat ?  I opened a [stackoverflow question](https://stackoverflow.com/questions/43500983/specify-log-request-format-in-aiohttp-2) but with no results.
gets no result, either (no logging at all)

**Comment by fafhrd91** [comment]
you need to pass access_log https://aiohttp.readthedocs.io/en/stable/logging.html#access-logs
logger just for internal logging, exceptions, warnings, etc

**Comment by fafhrd91** [comment]
if you pass access_log aiohttp will do access logging, but you have to configure python logging subsystem
