### ISSUE TITLE
Fix documentation and remove sign 'coroutine' where it is deprecated

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#1851]
For example, `ClientSession.close()` Documentation said that this is coroutine, but sources say that it is not.

New users must use DOCUMENTATION as source of truth (instead of reading source code).

**Comment by fafhrd91** [comment]
would you provide PR?

**Comment by AraHaan** [comment]
I think I can fix it.

**Comment by AraHaan** [comment]
Ok, let me know if I need to make changes. Also now that I am reading the docs a bit more I also found some places that can easily be confusing on. So for those I plan to fix those areas sometime as well. I did this PR on my iPhone this time as I am currently at school.
