### ISSUE TITLE
Docs doesn't match code for version param in ClientSession.request()

### ISSUE THREAD

**Issue by alefteris** [aio-libs/aiohttp#1856]
## Long story short

Hi there. I noticed that in the aiohttp latest docs https://aiohttp.readthedocs.io/en/latest/client_reference.html#aiohttp.ClientSession.request mentions that a `version` param can be provided. But looking at the source code, `version` is set only during the session construction, but not at the session.request() method. So I'm wondering if it should be deleted from the docs or code has to be updated to allow version to be set also from the session.request() method, in addition to the session construction?

## Your environment

aiohttp master

**Comment by AraHaan** [comment]
I believe it was changed back in v2.0 to just instace. But not sure right now.

**Comment by fafhrd91** [comment]
It should be deleted. Version was long time deprecated
