### ISSUE TITLE
routing subapps with subdomains

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#1860]
## Long story short

Would be great if we could route to different sub-apps based on the (sub)domain/host.

## Expected behaviour

I guess something like

```python
app.add_subapp('/', api, host='api.example.com')
app.add_subapp('/', ui, host='example.com')
app.add_subapp('/admin', admin, host='example.com')
```
Also happy if the domain was just added to the prefix.

## Actual behaviour

As far as I can tell this isn't currently possible.

**Comment by fafhrd91** [comment]
I think we have ticket for this. @asvetlov wanted to work on this feature

**Comment by samuelcolvin** [comment]
duplicate of #1342. Sorry.
