### ISSUE TITLE
In unit tests, Application comparisons can report false positive

### ISSUE THREAD

**Issue by Anvil** [aio-libs/aiohttp#1866]
Comparison between Application is performed at the MutableMapping level. MutableMapping says that, like dict objects, if all keys and matching values are the same 2 instances, then they are equals. This means that `web.Application() == web.Application()` will return True.

See:

```python
>>> a = aiohttp.web.Application()
>>> b = aiohttp.web.Application()
>>> a == b
True
>>> a["foo"] = "bar"
>>> a == b
False
>>> b["foo"] = "bar"
>>> a == b
True
```

I think those few unit tests are assuming a different behaviour:
* test_subapp_middlewares
* test_subapp_on_response_prepare
* test_subapp_on_startup
* test_subapp_on_shutdown
* test_subapp_on_cleanup

A change has been submitted for `test_subapp_middlewares` in #1854 to fix that. While the solution may or may not be accepted as is, all tests should be fixed.

Also, maybe an additional `test_application_equal` should be implemented, to be ensure expected behavior. Unless `web.Application.__eq__` special method gets implemented to change current behaviour, it should look like something like that:

```python
def test_application_equal():
    app1 = web.Application()
    app2 = web.Application()
    assert app1 == app2
    app1["foo"] = "bar"
    assert app1 != app2
```

**Comment by asvetlov** [comment]
You've raised an interesting problem.
1. We could leave apps comparison as is but this way will constantly produce many subtle bugs.
2. On other hand we could forbid applications comparison in the way that apps are equal if and only if they are the same (`app1 is app2`). Ordering should be fixed as well.

I'm inclining to option 2 (all potentially broken tests should be fixed as well).
I believe the change will not affect our users: most likely the only case for app comparison is test writing.

**Comment by Anvil** [comment]
For the record (and as far as my opinion matters), I would agree with option 2.
