### ISSUE TITLE
Problem with trailer header

### ISSUE THREAD

**Issue by yurifedoseev** [aio-libs/aiohttp#1876]
## Long story short
I described an issues in https://github.com/aio-libs/aiohttp/issues/1619 Later I update aiohttp for new version however the problem is still here.

Http response (body and trailers part):
"{ "doc": "some data"}\nX-Custom-Header1=0\r\nX-Custom-Header2=custom2\r\nX-Custom-Header3={}\r\n\r\n

## Expected behaviour
aiohttp loads json body and skips trailers. Parsing of the next response should not read any trailers from previous response.

## Actual behaviour
aiohttp loads json and do not read any trailer data from reader. Debugging shows that response reader buffer contains this trailer data.
When I use the same session the next response parsing will be started from the trailers. Therefore it leads to parsing exception.
## Steps to reproduce
1. Use the same session for requests
2. Get response from server with trailer headers (as shown above)  
## Your environment
macOS Sierra, aiohttp 2.0.7

**Comment by fafhrd91** [comment]
could you write test case?

**Comment by yurifedoseev** [comment]
Sure, in which format it should be?

**Comment by fafhrd91** [comment]
Doesn't matter, probably in test_client_protocol, I think it would be simplest

**Comment by yurifedoseev** [comment]
I've found out that the problem was on my side while writing the test case. Your fix works as expected. Thanks!
