### ISSUE TITLE
Tests for aiohttp app failed due to OSError on creating test server

### ISSUE THREAD

**Issue by playpauseandstop** [aio-libs/aiohttp#1895]
## Long story short

We have more than 1000 tests for our aiohttp app and sometimes they failed with `OSError` while aiohttp attempts to create new test server. In most cases next CI build fixes the previous one, but sometimes error repeated for 3-5 builds in a row.

## Expected behaviour

There should not be any `OSError` on creating test server while running tests for aiohttp app.

## Actual behaviour

I will not copy whole traceback, but here the most important part:

```py
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
app/tests/common.py:81: in prepare_client
    client = await test_client(app)
/usr/local/lib/python3.6/dist-packages/aiohttp/pytest_plugin.py:194: in go
    yield from client.start_server()
/usr/local/lib/python3.6/dist-packages/aiohttp/test_utils.py:215: in start_server
    yield from self._server.start_server(loop=self._loop)
/usr/local/lib/python3.6/dist-packages/aiohttp/test_utils.py:73: in start_server
    handler, self.host, self.port, ssl=self._ssl)
uvloop/loop.pyx:1363: in create_server (uvloop/loop.c:27511)
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 36370): address already in use
```

## Steps to reproduce

Am not sure that there are any proper steps to reproduce as `OSError` raised in random manner and for some builds one test failed when for other - another one.

## Your environment

- Python 3.6.1
- aiohttp 2.0.7
- pytest 3.0.7
- pytest-asyncio 0.5.0
- pytest-aiohttp 0.1.3
- uvloop 0.8.0

**Comment by asvetlov** [comment]
Fixed by #1896
