### ISSUE TITLE
Any difference between url and url_obj in URL

### ISSUE THREAD

**Issue by Kilerd** [aio-libs/aiohttp#1898]
just like the demo in official website http://aiohttp.readthedocs.io/en/stable/client.html

```python
async with aiohttp.ClientSession() as session:
    async with session.get('https://api.github.com/events') as resp:
        print(resp.status)
        print(await resp.text())
```
while the types of `resp.url` and `resp.url_obj`  are `aiohttp.URL` instance
it means that assert does not work like this:
```python
assert resp.url == 'http://httpbin.org/get?key2=value2&key1=value1'
```

in my code while pytesting.
it raise like that:
```bash
AssertionError: assert URL('http://127.0.0.1:40404/123') == 'http://127.0.0.1:40404/123'
```
but, actually, the str of URL is the same as `http://127.0.0.1:40404/123`

is that any feature instead of? or is it a bug?

**Comment by asvetlov** [comment]
In aiohttp 1.1+ `,url` pointed to `str` but `.url_obj` to `URL`.
Starting from aiohtp 2.0 they are aliases, `.url_obj` is deprecated.

Docs should be updated, most likely in the way like this: `assert str(resp.url) == 'htpp://....'`
