### ISSUE TITLE
Message: 'Error handling request' on python3.4, used to work just fine with 1.3x

### ISSUE THREAD

**Issue by eLvErDe** [aio-libs/aiohttp#1902]
Hello,

A very simple piece of server code that used to work just fine before now crashes completely (even serving static html content on / route) with the following exception:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib64/python3.4/logging/__init__.py", line 573, in format
    record.exc_text = self.formatException(record.exc_info)
  File "/usr/lib64/python3.4/logging/__init__.py", line 523, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "/usr/lib64/python3.4/traceback.py", line 169, in print_exception
    for line in _format_exception_iter(etype, value, tb, limit, chain):
  File "/usr/lib64/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/lib64/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'
Call stack:
  File "./main.py", line 221, in <module>
    loop.run_forever()
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 1295, in _run_once
    handle._run()
  File "/usr/lib64/python3.4/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/lib64/python3.4/site-packages/aiohttp/web_protocol.py", line 547, in handle_parse_error
    resp = self.handle_error(request, status, exc, message)
  File "/usr/lib64/python3.4/site-packages/aiohttp/web_protocol.py", line 512, in handle_error
    self.log_exception("Error handling request", exc_info=exc)
  File "/usr/lib64/python3.4/site-packages/aiohttp/web_protocol.py", line 358, in log_exception
    self.logger.exception(*args, **kw)
Message: 'Error handling request'
Arguments: ()
```
Forget the logging_error part, it's related to y Python 3.4 bug I guess:
https://github.com/getlogbook/logbook/issues/146

But if you're interested in, I workarounded the issue like this in my asyncio error handler:
```
        if 'exception' in context:
            # Workaround some weird Python bug I guess
            # IE: https://github.com/getlogbook/logbook/issues/146
            exc_info = sys.exc_info()
            if exc_info is not None and exc_info != (None, None, None):
                logger.exception("Uncatched exception occurred in asyncio loop: %r", context['exception'])
            else:
                logger.error("Uncatched exception occurred in asyncio loop: %r", context['exception'])
        else:
            logger.error("Uncatched exception occurred in asyncio loop: %r", context['message'])
```
Thanks in advance for your help, I have absolutely no clue of what's going on...

Best regards, Adam.

**Comment by asvetlov** [comment]
Do you have steps for reproducing the issue reliable?

**Comment by eLvErDe** [comment]
Hi,

I guess you were going to ask that. I'm just waking up, give me a couple of hours and I'll provide a standalone example code.

Adam

**Comment by AraHaan** [comment]
@eLvErDe Cant you try this with 3.5+ as python 3.4 has an ``yield from`` bug? Also in 3.5+ you do not have to worry about using ``async def`` and ``await`` but is supported.

**Comment by eLvErDe** [comment]
@AraHaan Sadly, it won't help me. The code is aimed for a long standing project, running on Centos7 which comes with Python3.4.5. Debian stable with 3.4.2 fails too.

Here is a very simple piece of code that worked on aiohttp 1.x but does not on 2.x:

```python
import aiohttp.web
import asyncio

class CG_AsyncWebServer():

    def __init__(self, loop):
        self.app = aiohttp.web.Application()
        self.loop = loop
        self.handler = None

        # Alias add_route method
        self.add_route = self.app.router.add_route
        self.add_route('GET', '/', self.index)

    def make_handler(self):
        """Built-in function that has to be defined"""
        self.handler = self.app.make_handler()
        return self.handler

    def index(self, _):
        body = '<html><body>'
        body += '<h2>The index</h2>'
        body += '</html></body>'
        return aiohttp.web.Response(body=body.encode('utf-8'), content_type='text/html')


if __name__ == '__main__':

    bind = ('0.0.0.0', '8899')
    loop = asyncio.get_event_loop()

    ws_app = CG_AsyncWebServer(loop)
    ws_handler = ws_app.make_handler()
    f = loop.create_server(ws_handler, *bind)

    loop.run_until_complete(f)
    loop.run_forever()
```

Thank in advance, Adam.

**Comment by fafhrd91** [comment]
I can not reproduce this problem. there is nothing in script that can cause exception

**Comment by asvetlov** [comment]
Let's close it

**Comment by eLvErDe** [comment]
Hi,

Guys, really, I just gave a try again on Centos7 x64, and it does not work.
Reverting to 1.3 make it work again...

If you're interrested in giving a try, here is the RPMS/SRPMS I made (based of Fedora devel package + minor backporting for Centos7)....
https://cloud.le-vert.net/index.php/s/6tjVNZOgxo4hJup

Regards, Adam.

**Comment by fafhrd91** [comment]
This is not very useful bug report. Could you at least set debug log level and report exception

**Comment by asvetlov** [comment]
Let's keep it open for tracking the issue for a while.
Maybe @eLvErDe will provide more information

**Comment by eLvErDe** [comment]
Right now, powering laptop on.

**Comment by eLvErDe** [comment]
Hi,

I did more testing using a Centos7 docker and my own RPMs of the python3 stack and here's what happens:
It fails when using all RPMs, but works if I keep only the dependencies and git clone / checkout 2.2.0 aiohttp. So I guessed it somehow cames from cython which is used by Centos to build the package.
That explains why the error is so weird.

Finally it turns out upgrading async-timeout and yarl to latest issue fixed the issue, even with the cython build so I'm not sure how to explain that.

Anyway, it's working now so I guess you can close the ticket safely....

Regards, Adam.
