### ISSUE TITLE
Run tasks (fetch urls) inside separate thread

### ISSUE THREAD

**Issue by shax-xxx** [aio-libs/aiohttp#1921]
## Long story short

The idea is to have ability to suspend all running/queued tasks for a time
As I understand it, threads can wait for events as long as needed, so i try to run asyncio loop inside a thread class, and then control its state by events.
According to aiohttp docs its good practice to run all requests in one session per app, and if i have single-threaded app, everything works fine.
But if i run same fetch tasks in separate thread with one session for all of them - i recieve the error about `Timeout context manager`
On the other hand, if i change task like in `fetch_per_request()` - then error goes away

(closed connections after thread wakeup are not a problem)

I think that I poorly understand the interaction between threads and asyncio tasks
Can someone clarify how to run all requests in one session per thread?

## Expected behaviour

No exception

## Actual behaviour

<GetContentThread(Thread-1, started 140570646071040)> start
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/python/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "threads_simplify.py", line 23, in run
    self.loop.run_until_complete(task)
  File "/opt/python/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/opt/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "threads_simplify.py", line 29, in fetch_per_thread
    async with self.session.get('http://python.org') as resp:
  File "/home/user/python3.5_proj/p1/env/lib/python3.5/site-packages/aiohttp/client.py", line 626, in __aenter__
    self._resp = yield from self._coro
  File "/home/user/python3.5_proj/p1/env/lib/python3.5/site-packages/aiohttp/client.py", line 208, in _request
    with timer:
  File "/home/user/python3.5_proj/p1/env/lib/python3.5/site-packages/aiohttp/helpers.py", line 680, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task

## Steps to reproduce

```

import asyncio
import aiohttp
import threading


class GetContentThread(threading.Thread):
    def __init__(self, *args, **kwargs):

        super(GetContentThread, self).__init__(*args, **kwargs)

        self.loop = asyncio.new_event_loop()
        self.conn = aiohttp.TCPConnector(verify_ssl=False, limit=0, limit_per_host=5, force_close=True)
        self.session = aiohttp.ClientSession(connector=self.conn, conn_timeout=30)

    def run(self):
        print('{} start'.format(threading.current_thread()))

        asyncio.set_event_loop(self.loop)
        
        # does not work
        task = self.loop.create_task(self.fetch_per_thread())
        
        # work
        #task = self.loop.create_task(self.fetch_per_request())

        self.loop.run_until_complete(task)

        print('session {}'.format(id(self.session)))

    # session per thread
    async def fetch_per_thread(self):
        async with self.session.get('http://python.org') as resp:
            assert resp.status == 200
            return await resp.text()

    # session per request
    async def fetch_per_request(self):
        async with aiohttp.ClientSession(loop=self.loop) as client:
            async with client.get('http://python.org') as resp:
                assert resp.status == 200
                return await resp.text()


t = GetContentThread()
t.start()

```

## Environment
Python 3.5.2
aiohttp (2.0.7)
asyncio (3.4.3)

**Comment by justanr** [comment]
What's the context for running the loop in a thread?

**Comment by shax-xxx** [comment]
Let's say we want to download 1000 files from server. We create one session and 1000 tasks with `session.get()`, then `loop.run_until_complete(asyncio.gather(*tasks))`
After 100 successful requests server begin drop us due some reason (ex. sequential requests limit or something else - doesn't matter) and we catch `aiohttp.ServerTimeoutError` as a result of 101 task and all subsequent. At that moment (when we read 101 task result) we want to pause all remaining tasks (or whole event_loop) for a time, then resume it and retry remaining connections (without job for recreating tasks)
As far as I understand, I can not pause event_loop itself, only stop. But i can call `event.wait(time)` for the thread with event_loop.

**Comment by justanr** [comment]
https://docs.python.org/3/library/asyncio-sync.html#event

Any reason you can't use the asyncio compatible synchronization primitives?

**Comment by shax-xxx** [comment]
For reason that can only be explained by my inattention, i missed it. ;(
Thank you. I will definitely try asyncio synchronization.

However, this doesn't move me closer to understanding why threaded code above raise a RuntimeError in case with one session per thread, and doesn't raise it if one session per request.

**Comment by asvetlov** [comment]
Because you neither pass event loop explicitly nor setup default loop in thread context (the second way is preferable for Python 3.6).
Just call `set_event_loop()` after `new_event_loop()`.

I guess the issue could be closed.
