### ISSUE TITLE
aiohttp 2.1.0 release

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1922]
Let's just make it.

I want to finish #1915.
#1910 worth to be finished too.

But both are no show-stoppers, we could publish a bugfix release as soon as theses fixups will be ready.

Looks like people want for already merged PRs publishing and we have pretty long list of them.

@fafhrd91 ?

**Comment by fafhrd91** [comment]
It is yours, I am really busy with other project.

**Comment by asvetlov** [comment]
Done
