### ISSUE TITLE
Travis CI tests improvement

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiohttp#1926]
Hi,

I saw, the current `.travis.yml` is somewhat incomplete.

I'm just wondering if you'd accept changes to it:
- introduce build stages (pipelines) support to make sure `deploy` step only runs if tests in all the envs succeed, not just in chosen one;
- "teach" Travis CI run tests under OS X (is this needed?);
- make cleanup (currently the whole `matrix` section makes no sense);
- anything else I might miss.

**Comment by fafhrd91** [comment]
+1

**Comment by asvetlov** [comment]
Please do with maybe only exception.
IFAIK OSX boxes are unacceptable slow

**Comment by fafhrd91** [comment]
maybe we can just build OS X wheels?

**Comment by webknjaz** [comment]
> OSX boxes are unacceptable slow

They are. Wait time + running tests is 8 times slower, than Linux containers. Didn't compare 'em w/ VMs.

The workaround could be enabling `fast_finish` + `allow_failure`, w/o pipelines. But with them enabled, this won't help.

**Comment by webknjaz** [comment]
I see tests happen in strange places.

And current config results in 15 uploads per tagged build. What is the point of this?

I would like to optimize this.

**Comment by asvetlov** [comment]
Yes, I know about upload problem. Please fix it.
But what do you mean by 'tests happen in strange places'?

**Comment by webknjaz** [comment]
Well, it's not obvious which parts of config are the real tests, which ones are just build scripts and which are responsible just for building wheels and uploading them to PYPI.
In other words, it's not obvious what flow did you want to follow for running tests.

In my mind, the pipelines should be executed in the following order:
1) lots of jobs with tests under different envs, which may be parallelized;
2) just the deployment job(s)

Could you please describe your vision of how CI should work?

**Comment by asvetlov** [comment]
I've added travis stages to aiojobs: https://github.com/aio-libs/aiojobs/blob/master/.travis.yml
The project could be used as sketch for aiohttp travis file improvement
