### ISSUE TITLE
Fix Regex 'invalid escape sequence' Warnings

### ISSUE THREAD

**Issue by cooperlees** [aio-libs/aiohttp#1934]
## Long story short
3.6 now cares about these invalid Deprecated escape sequences.
Paste: https://pastebin.com/dTXU06FA

## Expected behaviour
These should be r'' strings

## Actual behaviour
- Here are all the warnings found @ import time
https://pastebin.com/dTXU06FA

## Steps to reproduce
Run python3 -W all

## Your environment
CentOS 7
Python 3.6

**Comment by asvetlov** [comment]
Fixed by #1908 isn't it?

**Comment by cooperlees** [comment]
Sorry, my virtualenv had an outdated version. I'll check harder next time.

**Comment by asvetlov** [comment]
NP
