### ISSUE TITLE
Content length is 0 by default in aiohttp.web.Response

### ISSUE THREAD

**Issue by julien-duponchelle** [aio-libs/aiohttp#1940]
## Long story short

If you create an empty web response you will have a content length of 0 instead of None.

## Expected behaviour

Content length should be None.

## Actual behaviour

Content length is 0

## Steps to reproduce
```python
import aiohttp.web
r = aiohttp.web.Response()
r.content_length
>>> 0
```

## Your environment

aiohttp 2.0.7 on macos

**Comment by julien-duponchelle** [comment]
I'm not sure of me. But it seem sometimes this can create trouble with chunked encoding. That's why previously I opened this PR:
https://github.com/aio-libs/aiohttp/pull/1933

**Comment by fafhrd91** [comment]
this is intended behavior, because you supply response body. by default it is empty.

**Comment by julien-duponchelle** [comment]
Thanks
