### ISSUE TITLE
Changing state of started or joined application is deprecated....grrrr

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#1947]
## Long story short

I very often want to set items on "frozen" app. I'm getting depreciation warnings for this and in future (presumably) this will fail outright. This is very frustrating.

This is made worse by pytest 3.1 which prints all warnings making this harder to ignore.

## Expected behaviour

```python
app['database'] = await create_my_database(...)
```

In a startup function should not cause deprecation warnings.

## Actual behaviour

I'm getting warnings in lots of setups which I would have thought sensible.

### Examples

**in unit tests** setting up a secondary server:

```python
@pytest.fixture
def mock_external_server(loop, test_server):
    app = Application()
    app.router.add_post('/whatever.json', handler)
    server = loop.run_until_complete(test_server(app))
    app['server_name'] = f'http://localhost:{server.port}'
    return server
```

This causes a warning because I'm setting the `server_name` item on an app which is started.

**using startup function:**
```python
async def startup(app: web.Application):
    app['pg_engine'] = await create_engine(pg_dsn(app['database']), loop=app.loop)

...

app = web.Application()
app.on_startup.append(startup)
```
(real life example [here](https://github.com/tutorcruncher/socket-server/blob/master/tcsocket/app/main.py#L15-L20))

This again causes warnings setting `pg_engine` in a startup script.

## Workaround

Surely this warning is wrong? If not what workaround should I use?

The only solution I can think of is an ugly bodge:

```python
async def startup(app: web.Application):
    app['data']['pg_engine'] = await create_engine(pg_dsn(app['database']), loop=app.loop)

...

app = web.Application(middlewares=middleware)
app['data'] = {}
app.on_startup.append(startup)
```

**Comment by asvetlov** [comment]
Hmm.
Initial intention for 'freezing' was prevention on route table modification after initialization phase.
After that I've though that freezing global state after `on_startup` is also good idea.

As I see in code for `run_app` this sequence is supported: `.freeze()` is called on first server socket creation, all `on_startup` signals are finished at this time.

**Comment by samuelcolvin** [comment]
```python
import pytest
from aiohttp import web


async def startup(app):
    app['foobar'] = 123


async def handle(request):
    return web.Response(text='hello')


def create_app():
    app = web.Application()
    app.on_startup.append(startup)
    app.router.add_get('/', handle)
    return app


@pytest.fixture
def cli(loop, test_client):
    app = create_app()
    return loop.run_until_complete(test_client(app))


async def test_hello(cli):
    resp = await cli.get('/')
    assert resp.status == 200
    text = await resp.text()
    assert 'o' in text
```

Then run
```
pytest --pythonwarnings=error test_example.py
```

gives: `DeprecationWarning: Changing state of started or joined application is deprecated`

**Comment by asvetlov** [comment]
The error was in `aiohttp.test_utils`. `aiohttp.web.run_app` was working as expected.
Fixed. Thanks for report.

**Comment by asvetlov** [comment]
Ooop, something is wrong with `run_app` too. I'll fix it.

**Comment by asvetlov** [comment]
Finally fixed
