### ISSUE TITLE
Doc clarification -  StreamReader.iter_any() vs iter_chunks()

### ISSUE THREAD

**Issue by pkch** [aio-libs/aiohttp#1949]
It might help to clarify in the documentation the difference between [`iter_any`](http://aiohttp.readthedocs.io/en/stable/streams.html#aiohttp.StreamReader.iter_any) and [`iter_chunks`](http://aiohttp.readthedocs.io/en/stable/streams.html#aiohttp.StreamReader.iter_chunks). Currently it says

> Iterates over data chunks in order of intaking them into the stream

> Iterates over data chunks as received from the server

But it's not clear what the difference is between the chunks received from the server and the chunks that were taken into the stream.

My (naive) reading suggests the (almost certainly incorrect) interpretation that `iter_chunks` guarantees to preserve the chunks produced by the server under chunked transfer encoding, and yield them one by one. OTOH, since the `aiohttp` implementation is free to decide how to accept the chunks from the server into the stream (it can combine them or even split them), `iter_any` provides no guarantees about each yielded chunk is (other than that, if they are put together, they will of course combine to whatever the server sent).

BTW, this came up when I was reading the discussion about the chunked transfer encoding and `iter_any`, and specifically [this clarification](https://github.com/aio-libs/aiohttp/pull/1900#issuecomment-302840811):

> [...] Chunked encoding is just transport protocol only, semantically it's a sequence of bytes without boundaries. Just like a TCP socket is semantically a stream of bytes while the content is transferred by packets. From my perspective partial chunks are totally correct.

**Comment by asvetlov** [comment]
@pkch suggestions?

**Comment by pkch** [comment]
I tried to read the code, but for the life of me I can't see what the difference between these two functions is. As far as I can tell, they do exactly the same thing (except for a possible wording in the warning message).

**Comment by asvetlov** [comment]
Fixed by #2150
