### ISSUE TITLE
Multiple workers: seperate package or included in aiohttp

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#1950]
## Background

gunicorn, tornado, sanic & japronto all use the same system of multiple processes connecting to the same socket to utilise multiple CPUs. Unlike tornado sanic and japronto; aiohttp does not have built-in support for multiple workers, instead relying on gunicorn or a proper reverse proxy like nginx, this must have been a conscious decision but I can't find it documented anywhere.

## Question

If I want this functionality should I submit a PR to include it in aiohttp or create a new package?

## Why not gunicorn?

Gunicorn has been a trusted friend for many years, and I'm using it in production on numerous projects. For projects using uwsgi it's invaluable.

However, it's a victim of its own success/age and much of it's API is far out of sync with python 3.5/6. It's also pretty big and unwieldy as it was designed for wsgi and to do lots more than just connect multiple processes with to the same socket and supervise them.

Also as the docs say:

> But nothing is for free: running aiohttp application under gunicorn is slightly slower.

## The Replacement

Whether the replacement for gunicorn is builtin or a separate package it can be extremely concise and easy to reason with:

```python
from multiprocessing import Process
from socket import SOL_SOCKET, SO_REUSEADDR, socket
from aiohttp import web

def serve_multiple(app, workers):
    sock = socket()
    sock.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
    sock.bind(('0.0.0.0', 8000))
    sock.set_inheritable(True)

    processes = []
    for i in range(workers):
        process = Process(target=web.run_app, name=f'worker-{i}', kwargs=dict(app=app, sock=sock))
        process.daemon = True
        process.start()
        processes.append(process)

    try:
        for process in processes:
            process.join()
    except KeyboardInterrupt:
        pass
    finally:
        for process in processes:
            process.terminate()
        sock.close()

async def index(request):
    return web.Response(body='hello world')

app = web.Application()
app.router.add_get('/', index)
serve_multiple(app, 4)
```

(this works and gives almost 4 times the request throughput of just `run_app`).

The only thinks which would need to be added for production (AFAIK) are:
* logging
* restarting workers on failure
* request time limits, this could be implemented as aiohttp middleware
* an equivalent of gunicorn's `max_requests` which gracefully kills that worker, then restarts it
* anything else?

**Comment by asvetlov** [comment]
What's purpose for this issue?
Better benchmark numbers only?
For real world all enumerated bullets should be supported, especially worker restarting.
I think it's significant amount of work for making it running and especially for support (bug fixes etc.)

Anyway people will start aiohttp behind nginx and control worker processes via systemd, supervisord or similar daemon. Also they usually want to collect some statistics and push it into Grafana etc.

If you would create a separate project -- it's on your own, sure.

**Comment by fafhrd91** [comment]
I agree with @asvetlov. is gunicorn is not good enough? why would we want duplicate process/socket management in aiohttp? there are good tools for that already/

**Comment by samuelcolvin** [comment]
The purpose of this issue is fairly clear - I asked a specific question.

I don't really care about benchmarks, I'm interested in removing gunicorn from my stack because I think I'm only using 1% of it and the other 99% is clouding my vision.

**Comment by samuelcolvin** [comment]
Thanks for the prompt and definitive answer. 

From some tests I think nginx is properly a better way to distribute load than shared sockets anyway.

**Comment by sp-1234** [comment]
Does the above code example (with shared socket) play nicely with a SSL context?

**Comment by asvetlov** [comment]
Yes

**Comment by jaddison** [comment]
I realise this is a closed issue, but for anyone watching - does python bug https://bugs.python.org/issue21998 not affect the 'forkability' here? (noting that `Process(...)` by default uses `os.fork()` behind the scenes)

**Comment by asvetlov** [comment]
Short answer: "There is a possibility to fork open sockets without forking asyncio loops and related structures."
Long version is out of the project scope.
