### ISSUE TITLE
Websocket issues while headers are fragmented

### ISSUE THREAD

**Issue by molszowy** [aio-libs/aiohttp#1951]
I am looking for help to narrow down an issue with websockets. Intermittently, the server sends a frame that is split in multiple TCP/IP packets which seems to be the problem for the websocket client implementation in aiohttp. I observe the errors like : "Received frame with non-zero reserved bits" or no response to PING which drops the connection as 'Idle'.

The example is PING which is normally send in one single packet(packet 10902) and parsed correctly by the library but when it comes split in two packets(11135, 11136), it's not recognized as PING. I put the debug line in http_websocket.py to see what's coming in to parse_frame()

http_websocket.py
```
def _feed_data(self, data):

      DEV_LOGGER.debug('parse-frame: %s' % data)

      for fin, opcode, payload in self.parse_frame(data):
```

Packet capture:

![image](https://cloud.githubusercontent.com/assets/8876243/26779252/0183096e-49e5-11e7-8672-5cf44d536be6.png)

Logs from my client:
**2017-06-02 15:57:10,960http_websocket.py:191: _feed_data() parse-frame: b'\x89\x00'**
2017-06-02 15:57:10,961 Detail="The websocket received a ping."
2017-06-02 15:57:10,961 Detail="Sent pong response."
2017-06-02 15:57:10,961 Detail="Listening for messages on websocket."
**2017-06-02 15:57:26,087http_websocket.py:191: _feed_data() parse-frame: b'\x89'
2017-06-02 15:57:26,087http_websocket.py:191: _feed_data() parse-frame: b'\x00'**

If I am not mistaken the library treats the received data as two independent frames(framing issue?) and does not detect PING. 

Thanks in advance for help!

**Comment by fafhrd91** [comment]
Thanks for detailed description! I will look into this problem

**Comment by molszowy** [comment]
Thanks Nikolay! Did you have a chance to investigate this further ? Let me know if you need more data, etc.

**Comment by jonathanslenders** [comment]
Hi @fafhrd91,

Probably this was caused by a bug in the ``parse_frame`` function in ``http_websocket.py``.
Every time we break because of not enough data yet, the remaining data should be assigned to ``self._tail``.

So, ``self._tail = buf[start_pos:]`` needs to be placed before every break in ``parse_frame``.
@molszowy: can you confirm that?

Thanks,
Jonathan

**Comment by fafhrd91** [comment]
haven't looked yet. 

@jonathanslenders would you create PR?

**Comment by pjknkda** [comment]
I'm working on this issue and other websocket-related issues (based on https://rawgit.com/pjknkda/ws-spec-check/master/reports/fuzzingclient/index.html) and it's almost done.

**Comment by molszowy** [comment]
@pjknkda thanks for fixing this problem! Seems to work fine :)
When can we expect a new release ?

**Comment by asvetlov** [comment]
I'll publish 2.1.1 bugfix with #1962 very soon.

**Comment by fafhrd91** [comment]
Wait befor I review #1955

**Comment by asvetlov** [comment]
Sure. Any other issues?
I wanted to cherry-pick 03984c24 only without publishing all other 2.2.0 features.

**Comment by fafhrd91** [comment]
I don't think we have any breaking changes, lets just release everything as 2.1.1

**Comment by asvetlov** [comment]
It works to me.
Should I wait for #1955 ?

**Comment by fafhrd91** [comment]
yes, I want to fix it

**Comment by willmcgugan** [comment]
This issue effects us. Working on the master branch fixes it. Any ETA on 2.1.1 ?
