### ISSUE TITLE
2.x: ClientSession read_timeout should not be cumulative

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiohttp#1954]
read_timeout is usually implemented as time from receiving each chunk of data.  This is to prevent servers which are not data back w/in a certain amount of time.

2.x changed the behavior for this to be cumulative, which means that short downloads will work ok, but large downloads will fail even for servers that are still responding correctly.  I have never seen read_timeout be a cumulative timeout.  This change is similar to https://github.com/aio-libs/aiohttp/issues/1907 in that it's a change in behavior that no-one will expect.  

Further there's no real reason to apply a cumulative read_timeout as this will be handled by the `_request` `timeout` parameter.

In a minimum this needs to be changed to have a flag to disable this behavior and make it work like before as to do the previous behavior clients will have to take over the read timeout handling.

**Comment by fafhrd91** [comment]
I think `read_timeout` in general is useless or unneeded. async_timeout is perfectly fine solution

**Comment by thehesiod** [comment]
actually it's really important, there's a distinction between a request taking 'N' seconds, and a server responding w/n N seconds.

AWS for instance can immediately give you back a response stream, but then hang mid-way through reading the stream.

We have one of our services which downloads files from 10k to 800MB.  We can't say we want to request to take N seconds because it depends how big the file is.  What we can say is to fail the request if the server doesn't send any data w/in N seconds.

**Comment by fafhrd91** [comment]
you get back response object when server return http message, so technically it is "time to until" you can start reading response payload. that is reason why I think it is useless.

**Comment by thehesiod** [comment]
http://docs.python-requests.org/en/master/user/advanced/#timeouts

**Comment by fafhrd91** [comment]
so what method can you use to timeout requests in sync world?

**Comment by thehesiod** [comment]
note here too: http://docs.python-requests.org/en/master/user/quickstart/#timeouts  This is how all native libraries I've ever used works too.

you mean an overarching max timeout? You'd have to manually iterate over the chunks and keep your own max timeout..given you know each chunk will be a max of `read_timeout`

**Comment by fafhrd91** [comment]
requests as an example does not make sense. with requests you just don't have other options.

you can implement whatever method you want for aiohttp. it just not possible to satisfy all use cases.
I dont care about `read_timeout`. you can provide PR and doc changes if everyone agrees with reasoning.

@asvetlov @kxepal

**Comment by thehesiod** [comment]
more examples:
http://botocore.readthedocs.io/en/latest/reference/config.html
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740476.aspx (SO_RCVTIMEO, applies to each call to `recv`, not across all calls)

**Comment by fafhrd91** [comment]
can you find similar information for asynchronous sockets?

**Comment by thehesiod** [comment]
you say it doesn't make sense but provide no basis from why the current impl makes "sense", in fact I've provided various examples why the current impl does not make "sense".  The current impl also relies on the user having to immediately do all the reads after the connect, what if that is not the case?  I've seen no evidence that the current impl is tailored for most users given how this has worked in libraries in the past (we should always build on the lessons learned from others).  k, I'll try to put something together.

**Comment by thehesiod** [comment]
this isn't really an asyncio vs sync issue, asyncio behaves similarly to sync w/ threads.  This is the defacto asyncio lib =)

**Comment by thehesiod** [comment]
yet another: https://msdn.microsoft.com/en-us/library/bk6w7hs8(v=vs.110).aspx
current impl is just wrong, you have not implemented a read timeout, you've implemented something else entirely.

**Comment by fafhrd91** [comment]
do you understand what is the reason for timeout for system calls in sync world?

**Comment by thehesiod** [comment]
obviously I'm not going to convince you, this is not a sync vs async issue.  This is a normative/declarative issue.  In the old world they could have done an overarching timeout like you've done here as well but they didn't because it's not as useful.  You can layer your current impl on top of the normative model.  So feel free to close this and we'll just layer our own timeouts on top of aiohttp.  To us it doesn't really matter, I'm just trying here to help others who expect read_timeout to historically behave differently.
