### ISSUE TITLE
[Docs] #1134 mentioned twice in CHANGES.rst

### ISSUE THREAD

**Issue by SoumenDass** [aio-libs/aiohttp#1960]
## Long story short

Change #1134 mentioned twice in CHANGES.rst (http://aiohttp.readthedocs.io/en/stable/changes.html#id1)

## Expected behaviour

Should be mentioned once.

## Actual behaviour

Change #1134 mentioned twice in CHANGES.rst (http://aiohttp.readthedocs.io/en/stable/changes.html#id1)

## Steps to reproduce

View page here

## Your environment

Not environment specific.

Comment: Edit: submitted pull request

**Comment by fafhrd91** [comment]
Thanks
