### ISSUE TITLE
The documentation on "Background tasks" is wrong

### ISSUE THREAD

**Issue by cecton** [aio-libs/aiohttp#1964]
## Long story short

In the example provided here: https://github.com/aio-libs/aiohttp/blob/master/docs/web.rst#background-tasks we add a new key to the application which is a background task.

If you activate the warnings using `-Wdefault` and execute the script, you will get:

```
/tmp/b.py:15: DeprecationWarning: Changing state of started or joined application is deprecated
```

## Expected behaviour

Not sure. Not having the warning? The example doesn't look bad, only `make_handler` is called before the `on_startup` signal which freezes the app before the signal is sent.

## Actual behaviour

When the example in the doc is executed, you get the warning.

## Steps to reproduce

I made this variant to test it out:

```
import asyncio
from aiohttp import web


async def listen_to_redis(app):
    try:
        await asyncio.sleep(200)
    except asyncio.CancelledError:
        pass
    finally:
        print("cleanup")


async def start_background_tasks(app):
    app['redis_listener'] = app.loop.create_task(listen_to_redis(app))


async def cleanup_background_tasks(app):
    app['redis_listener'].cancel()
    await app['redis_listener']


app = web.Application()
app.on_startup.append(start_background_tasks)
app.on_cleanup.append(cleanup_background_tasks)
web.run_app(app)
```

And run: `python -Wdefault <script>.py`

## Your environment

Python 3.6, Arch Linux

**Comment by asvetlov** [comment]
The warning should be relaxed: see #1947

**Comment by cecton** [comment]
Okay good to know thanks.

**Comment by asvetlov** [comment]
Fixed
