### ISSUE TITLE
Feature request: accept a set of fingerprints in TCPConnector

### ISSUE THREAD

**Issue by sp-1234** [aio-libs/aiohttp#1965]
## Long story short

Right now, if I understand correctly, it's only possible to set a single fingerprint which will be accepted by https client.
Sometimes, endpoint may use one of several certificates (for example if the exact time of certificate update is unknown), so it would make sense to trust a set of certificates instead of just one.

Also, as I see in the current source, it should be a very easy change:

    got = self._hashfunc(cert).digest()
    expected = self._fingerprint
    if got != expected:
        …

so if you agree but have no time, I can give it a try.

**Comment by asvetlov** [comment]
I think better fix would be adding `fingerprint` parameter to `client.get()` etc. like we have it for proxy support now. If you would to make a PR -- you are welcome.

**Comment by sp-1234** [comment]
@asvetlov so if I do this issue, I should also do https://github.com/aio-libs/aiohttp/issues/1128 in the same PR?

**Comment by asvetlov** [comment]
Please make two separate PRs.
It makes reviewing much easier.

**Comment by cecton** [comment]
Started in #2184

**Comment by asvetlov** [comment]
Fixed in aiohttp 2.3 by #2184
