### ISSUE TITLE
Dependency problem when using tox

### ISSUE THREAD

**Issue by cecton** [aio-libs/aiohttp#1973]
## Long story short

Related to the comments in #1219 

I made some PR here and at first I didn't manage to make the tests work properly. Recently I investigated a little bit more and I realized that tox was installing its own version of py.test and somehow ignores any py.test plugins I installed on the system.

## Expected behaviour

Running tox should make the test run out of the box.

## Actual behaviour

```
Fixture 'mocker' not found
```

## Steps to reproduce

Hard to tell... I have a different version of py.test installed and tox is installing its own probably because the version is different but maybe it would do it anyway.

## Your environment

Arch Linux, Python 3.6, fish...

## A possible solution

```patch
diff --git a/tox.ini b/tox.ini
index fd0a550e..02dcec44 100644
--- a/tox.ini
+++ b/tox.ini
@@ -1,11 +1,12 @@
 [tox]
 
 envlist = check, {py34,py35}-{debug,release}-{cchardet,cython,pure}, report
 
 [testenv]
 
 deps =
     pytest
+    pytest-mock
     # pytest-cov
     coverage
     gunicorn
```

I just added pytest-mock to the dependencies to make sure it's installed in the tox environment.

**Comment by asvetlov** [comment]
Thanks
