### ISSUE TITLE
How do you package aiohttp 2.1 for Debian?

### ISSUE THREAD

**Issue by amirouche** [aio-libs/aiohttp#1974]
## Long story short

At $WORK we are using aiohttp for several services but we are using the 0.21 version available in Debian Jessie. The problem is that we would like to use the latest version of aiohttp and possibily to latest stable release of Python. The issue is that no stable release of Debian include both Python 3.5 nor aiohttp 2.1 so we need to create .deb packages for all of Python 3.5 and aiohttp 2.1

## Expected behaviour

There is a debian repository that extend Debian Jessie with Python 3.5 and aiohttp 2.1

## Actual behaviour

There is no repository

## Steps to reproduce

Install Debian Jessie and see that aiohttp is 0.21 and Python is 3.4

## Your environment

Debian Jessie.

## Summary

How do you package the latest and greatest of Python + aiohttp in production ?

Thanks!

**Comment by asvetlov** [comment]
Linux distributions packaging is out of scope for the project (and definitely not aiohttp specific).
You could try to search Internet for receipts like https://unix.stackexchange.com/questions/332641/how-to-install-python-3-6 though

**Comment by amirouche** [comment]
I am asking the community for feedback about the usage of aiohttp in production, it's not a bug in aiohttp.

**Comment by fafhrd91** [comment]
I don't think using deb for single package makes sense. I prefer to use `virtualenv`, or at least pack your application into one deb file.

**Comment by amirouche** [comment]
@fafhrd91 So you use virtualenv for python dependencies? Do you use a particular pypi cache?

**Comment by fafhrd91** [comment]
we use relatively old process, Jenkins downloads all deps and pack to tar file, then on prod server we just use local files for `pip install`

**Comment by amirouche** [comment]
This looks like an ad-hoc pip cache solution.
