### ISSUE TITLE
Deprecate app.on_loop_available signal

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1978]
From my understanding on `app.on_startup` the loop is already present.
Why do we need additional signal?
`app.on_loop_available` is not documented BTW
@fafhrd91 ?

**Comment by fafhrd91** [comment]
I think this was for config and runtime separation. I am not sure if it is useful, we can deprecate any of those.

**Comment by kxepal** [comment]
+1 to deprecate and remove `on_loop_available`, don't see how it could be useful.

**Comment by justanr** [comment]
It looks like `on_loop_available` happens outside running the event loop, right? That's useful for doing blocking setup or interacting with third party packages that use the various run methods on the loop to do work. I've run into an issue where a package tries to use the loop to do something but it's already running so it just crashes.

**Comment by asvetlov** [comment]
> It looks like on_loop_available happens outside running the event loop, right?

No, there is no such guarantee.

If you need to do something blocking etc -- please do it before `run_app()` call.

**Comment by justanr** [comment]
Ah, in that case, yeah it should probably go the way of the dodo.
