### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1986]
We should make release. we need to push fixes for several serious bugs.

- [x] #1985 
- [x] #1978
- [ ] #1910
- [x] #1939
- [x] #1977

**Comment by fafhrd91** [comment]
@asvetlov

**Comment by asvetlov** [comment]
I'd like to solve several issues before:
#1985 
#1978
#1910
Maybe:
#1939
#1977

**Comment by asvetlov** [comment]
Release is out!
#1910 is not ready for merging yet.

**Comment by kxepal** [comment]
🎉
