### ISSUE TITLE
Add support for retrieving randomly selected port numbers

### ISSUE THREAD

**Issue by abingham** [aio-libs/aiohttp#1987]
If you pass `0` as the port to `aiohttp.web.run_app()`, aiohttp will select any available port. However, it is not currently possible to determine *which* port was selected. It would be useful in some cases to be able to determine which port is being used.

A motivating example for this is [the traad Python refactoring server](https://github.com/abingham/traad/tree/aiohttp). This listens for HTTP requests to perform various kinds of refactoring operations. It is typically used via a text editor like Emacs. Users of traad don't normally care what port it's running on; they may not even know that they're running an HTTP server at all. They just expect Emacs to "do the right thing". As such, it doesn't make sense to ask them to specify a port for the server. 

The emacs client for traad starts the server, telling it to choose any available port. Once the server starts, it prints its actual port to stdout and the emacs client parses that. This is possible in the current bottle-based implementation of traad, but the experimental aiohttp version is a impractical because we can't determine the port that it selects.

For my purposes, it would be great if I could register an `on_startup` listener that could then fetch the port from the app. But right now there's no way to get the port.

FWIW, there was [some discussion of this on stackoverflow](https://stackoverflow.com/questions/44610441/how-to-determine-which-port-aiohttp-selects-when-given-port-0).

**Comment by alexmnazarenko** [comment]
You can always do something like this:

```py
  sock = socket.socket()
  sock.bind(("127.0.0.1", 0))
  # Aiohttp will call 'listen' inside.
  # But it must be called before we actually use the port,
  # any attempts to connect before the 'listen' call will
  # be rejected.
  sock.listen(128)
  _, port = sock.getsockname()
  print("Port: %d" % (port,))

  aiohttp.web.run_app(app, sock=sock)
```

I use similar code in unittests. Note that while 'listen' is optional and kinda ugly, there is no way to reliably 'wait' for listen call by aiohttp (as on_startup is called before setting up asyncio servers). As about this weird looking '128' param - took it from aiohttp defaults.

Hope that helps )

**Comment by asvetlov** [comment]
The problem is `Application` might be used for listening on several tcp and unix sockets.
Right not we don't register them into application but PR is welcome.

**Comment by abingham** [comment]
FWIW, [this SO post](https://stackoverflow.com/questions/44610441/how-to-determine-which-port-aiohttp-selects-when-given-port-0) has a solution that works well for my situation.

**Comment by abingham** [comment]
> Right not we don't register them into application but PR is welcome.

This seems straightforward enough to do, with the main caveat being what @alexmnazarenko pointed out: there's no signal after aiohttp creates the "servers" that would let me inspect the app and get the socket/port info.

It doesn't look like it would be too hard to add a new signal, however. I could add one right before the call to `loop.run_forever` called `pre_serve' or something. I'll see if I can knock that together, and we can discuss naming based on that.

**Comment by alexmnazarenko** [comment]
That would be interesting.

For now I find myself forced to make custom copies of `run_app` to work around those issues.

Following is a little rant on `run_app` issues, just FYI:

* I have a close copy of `run_app` which is a coroutine. Had to make it so I can run aiohttp after some async initialization.

* Also current `run_app` doesn't allow to run multiple applications on different endpoints in a single thread. I've solved that with AsyncServer class (methods `start`/`stop`/`wait`, where `start` is essentially a `run_app` copy). Usecase: 'web' endpoint 0.0.0.0:8080 and 'local monitor/admin' endpoint 127.0.0.1:54442.

**Comment by abingham** [comment]
Check out [my `add-pre-serve-signal` branch](https://github.com/abingham/aiohttp/tree/add-pre-serve-signal). I think this does all of the right things, though I'm eager for improvements to the names I've used. If we can get this into acceptable shape, I'll be happy to make a PR.

FWIW, I've tested this out with me specific use-case, and it seems to work fine.

**Comment by abingham** [comment]
Since discussion of this issue seems to be stalled here, I've created [a pull request](https://github.com/aio-libs/aiohttp/pull/2135) to see if I can get feedback from others.

**Comment by abingham** [comment]
The PR I created to try to address this issue has been ignored and will almost certainly require a rewrite. Before I do that (if I bother at all...it felt like a waste of my time the first time), I thought I'd check to see if recent work has made it possible to access the port information. Is there some way to do it with the current version of aiohttp?

**Comment by asvetlov** [comment]
Now initialization process under the hood looks like:
```
runner = AppRunner(app)
await runner.initialize()  # setup app loop and run `on_startup()` signal.
site = HTTPSite(runner, 'localhost', 8000)
await site.start()
sslsite = HTTPSite(runner, 'localhost', 8443, ssl_context=....)
await sslsite.start()
# wait for closing
await runner.finalize()  # close sites, call app.cleanup()
```
List of running sites is available as `rinner.sites`, `site.name` is a string URL used to serve the site on specific host/port.

Is this information enough for you or you need additional signals?
I like decoupling Application from info about application running details but maybe I'm wrong.

**Comment by abingham** [comment]
The suggested way (at least, on the project page) of running an app is:

```
app = web.Application()
# add endpoints to the app
web.run_app(app)
```

If this is how I'm supposed to do things, then I think I still need a new signal so that I can access the sites after they've figured out their ports. 

The code you list looks something like the internals of `run_app`, and of course I could just reimplement that, thereby gaining access to the sites before I start serving. But that saddles me with needing to keep my implementation up-to-date with what are effectively the internals of aiohttp. The new signal (or some mechanism) seems much cleaner to me.

> I like decoupling Application from info about application running details but maybe I'm wrong.

That sounds like a good idea to me, too, and I don't mean to suggest that we should bind these things too closely. Really, I'm not married to any particular approach, I just want access to the port assignments.

**Comment by asvetlov** [comment]
`AppRunner` **is** a part of aiohttp 3.0 public API, not implementation detail.
The class appears as solution for people who don't want to call blocking `run_app` for running aiohttp server.
If proposed snippet works to you -- no need for new app signal.
Just a few extra lines instead of simple `run_app` call.

**Comment by abingham** [comment]
OK, I'll go with that and close this out. Thanks!

**Comment by asvetlov** [comment]
Welcome!

**Comment by abingham** [comment]
Any idea when you'll have a new release? It doesn't look like the technique described here will work with the latest (2.3.6).

**Comment by asvetlov** [comment]
The feature is brand new. Next aiohttp release is expected in January

**Comment by abingham** [comment]
Cool. I can wait until then.
