### ISSUE TITLE
light version of HttpClient

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#199]
i removed HttpClient from 0.12, but i think we need some lightweight version of it,
something like

```
    client = aiohttp.HttpClient('http://...', keep_alive=True)
    yield from client.request('GET', '/path1')
    yield from client.request('POST', '/path2')
```

@asvetlov @kxepal @popravich ?

**Comment by asvetlov** [comment]
Fixed by introducing `ClientSession` #328
