### ISSUE TITLE
Deprecate registering synchronous web handlers

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1993]
Right now `aiohttp.web` wraps sync handlers by async wrapper.
I think the behavior should be deprecated.

Opinions?

**Comment by kxepal** [comment]
+1

**Comment by fafhrd91** [comment]
+1

**Comment by kornsn** [comment]
Possible we have a little bug.

I have a handler that looks like a code below:

```
class MyHandler:
    aync def __call__(self, request):
        ...
```

This handler is asinchronous, but aiohttp thinks like it is sinchronous and writes deprecation warning.

Please, let's check it.

We can add one more test into test_urldispatch.py

```
def test_not_deprecate_async_call_class(router, recwarn):
    class Handler:
        async def __call__(self, request):
            pass
            
    router.add_route('GET', '/handler', handler)
     
    assert len(recwarn) == 0
```

What do you think? Should I make a pull-request?

**Comment by kornsn** [comment]
Also, using of lambda functions leads to deprecation warnings too, and we have not async lambdas. May be just let to use both of sync and async functions?

Sorry for late opinion.

**Comment by asvetlov** [comment]
Sorry, lambdas support is deprecated and will be removed.
Both sync and async makes a mess and unnecessary slowdown.

Regarding async `__call__` -- I really like to solve it on Python stdlib introspection level.
Maybe `async_calllable(arg)` utility (we have `callable(arg)` already)

If you are interested in -- file a bug on https://bugs.python.org , add asvetlov and yselivanov to nosy list
