### ISSUE TITLE
[Client] Incorrect handling of '..' in url path.

### ISSUE THREAD

**Issue by panagiks** [aio-libs/aiohttp#1996]
## Long story short

When making a request with a ClientSession object:
If a requested path contains a path level that is `..` it is not translated by removing the previous level from the path.

## Expected behaviour

Example: 
A request to `http://mysite.com/lvl1/lvl2/../file.tar.gz` should be translated to `http://mysite.com/lvl1/file.tar.gz` before sending.

## Actual behaviour

The request is sent to `http://mysite.com/lvl1/lvl2/../file.tar.gz` 

## Steps to reproduce

```py
import asyncio
import aiohttp

@asyncio.coroutine
def main():
    session = aiohttp.ClientSession()
    resp = yield from session.get('https://pypi.python.org/simple/aiohttp-swagger/../../packages/f1/db/0d22688d79b5de9fc325c5438a0b036bca9d711f80190aa2308f7a3942ad/aiohttp-swagger-1.0.0.tar.gz')
    print(resp.status)
    session.close()

asyncio.get_event_loop().run_until_complete(main())

```

In contrary with wget : 

```sh
wget https://pypi.python.org/simple/aiohttp-swagger/../../packages/f1/db/0d22688d79b5de9fc325c5438a0b036bca9d711f80190aa2308f7a3942ad/aiohttp-swagger-1.0.0.tar.gz
```
will result in

```sh
--2017-06-21 14:52:30--  https://pypi.python.org/packages/f1/db/0d22688d79b5de9fc325c5438a0b036bca9d711f80190aa2308f7a3942ad/aiohttp-swagger-1.0.0.tar.gz
Resolving pypi.python.org (pypi.python.org)... 151.101.112.223, 2a04:4e42:1b::223
Connecting to pypi.python.org (pypi.python.org)|151.101.112.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
```
Note that it translates the url path before sending the request.

## Your environment

Ubuntu16.04 amd64 Python3.5 aiohttp 2.1.0

**Comment by asvetlov** [comment]
Well, it should be done in `yarl` library on path normalization

**Comment by panagiks** [comment]
Yeah, I don't know the structure of the project (and as a result which module should do it) that's why I am reporting it here. If there is no further action that can/should be taken by aiohttp feel free to close the issue.

**Comment by asvetlov** [comment]
Please create an issue in https://github.com/aio-libs/yarl and close it here.

**Comment by panagiks** [comment]
Ok opened a [ticket](https://github.com/aio-libs/yarl/issues/84) to yarl.
