### ISSUE TITLE
Cleanup root folder

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2013]
We have too many entries in it.

I suggest the following:
- [x] Moving `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` into `.github` ( @kxepal you was right).
- [x] `build-wheels.sh`, `build.cmd`, `run_docker.sh` should go into `tools`.
- [ ] Not sure about requirement files but I want to move them into `requirements` folder. http://aiohttp.readthedocs.io/en/stable/contributing.html should be updated as well.

**Comment by kxepal** [comment]
+1

We can replace requirements files with setuptools extras. All the dependencies will be defined in setup.py and if you need to install aiohttp on CI, just `pip install .[ci]` - that's it. Same for dev and the rest. One setup.py to manage them all.

**Comment by asvetlov** [comment]
https://pyup.io/ bot makes PR for every dependency update and we can sure that everything works fine with our dependencies. That's why dependency files are still should be kept in.

If there is an alternative for `setup.py` -- please name it.

**Comment by kxepal** [comment]
> https://pyup.io/ bot makes PR for every dependency update and we can sure that everything works fine with our dependencies. That's why dependency files are still should be kept in.

pyup can't watch deps defined in setup.py extras?

> If there is an alternative for setup.py -- please name it.

There is only [pipfile](https://github.com/pypa/pipfile) but not sure if we should use it now. Quite beta.

**Comment by asvetlov** [comment]
> pyup can't watch deps defined in setup.py extras?

Sure it isn't

**Comment by asvetlov** [comment]
Done

**Comment by kxepal** [comment]
>> pyup can't watch deps defined in setup.py extras?

> Sure it isn't

That's a shame.

**Comment by webknjaz** [comment]
It is also possible to use declarative `setup.cfg` [starting with setuptools v30.3.0](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files), which would reduce amount of logic in `setup.py`
