### ISSUE TITLE
Add underscore prefix to all modules except web

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2015]
I see a lot of aiohttp import mis-usage.

While everywhere in docs we do promote `import aiohttp` for client API and `from aiohttp import web` for server one people constantly do something like `from aiohttp.web.web_response import Response`.

I suspect the source of the issue is IDEs suggest this name. If we *hide* our non-public modules maybe IDE will choose something from our `__all__` in `aiohttp` and `aiohttp.web`?

I cannot confirm it because I'm using EMACS. 
But maybe some PyCharm or PyDev user could comment my thoughts?

**Comment by justanr** [comment]
Alternatively, could these be moved into proper modules? e.g.

```
aiohttp/
    __init__.py
    web/
        response.py
        ...
    client/
        ...
```

`aiohttp.__init__` could just do `from .client import *` to maintain the current interface.

**Comment by kxepal** [comment]
PyCharm will happy to show you everything that target module has regardless what you have in `__all__`. However, it doesn't respect transictive imports - the `from aiohttp.web.web_response import Response` case won't get hint on `web_response`, but if you write it by yourself `import` statement will get the right hints. 

I don't see how underscores will help here. If people start to misuse aiohttp imports one additional character will not stop them to continue. 

Sometimes I miss export feature too, when you can define what others could actually import.

**Comment by kxepal** [comment]
I think the best option here is to provide some sort of linter (as pylint plugin or whatever) and encourage people use it. Though, it would have to do something more than just check how you do your aiohttp imports.

**Comment by fafhrd91** [comment]
Agree with @kxepal -1
Same as sequirity by obscurity

**Comment by kxepal** [comment]
Btw, what modern import hook system could provide for this?  Does it knows where import comes from and in which form to raise a warning or sort of?

**Comment by asvetlov** [comment]
@justanr it doesn't improve current situation very much.

**Comment by asvetlov** [comment]
@kxepal no, import system doesn't know `import` statement caller.
About linters: we could implement one but I pretty sure nobody will use it.

**Comment by asvetlov** [comment]
I saw several projects with all modules started from underscore. User just should use only names exposed in `__init__.py`.
But if PyCharm doesn't respect this trick -- let's just close the issue.
