### ISSUE TITLE
Make StreamResponse.write() true coroutine

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2021]
Should be used similar trick as for `ClientSesssion.close()`

**Comment by ghost** [comment]
StreamResponse.write() looks like a synchronous method - ?

**Comment by dennypenta** [comment]
I want to fix it!

**Comment by fafhrd91** [comment]
I think `PayloadWriter::write()` should be converted to coroutine as well

**Comment by asvetlov** [comment]
@fafhrd91 yes, sure

**Comment by asvetlov** [comment]
@dennypenta please do

**Comment by eteamin** [comment]
@asvetlov. Should we implement `__aenter__` and `__aexit__` for this to have simiar context manger like `ClientSession` or am I wrong?

**Comment by asvetlov** [comment]
I don't know.
Maybe it makes sense but please let's make another PR for it.

**Comment by asvetlov** [comment]
Fixed in master
