### ISSUE TITLE
Handlers running ProcessPoolExecutor fail to close socket

### ISSUE THREAD

**Issue by 0wu** [aio-libs/aiohttp#2023]
## Long story short

This is a standard example handling heavy lift tasks with ProcessPoolExecutor within a request handler async function.  The executor successfully finishes the task but fail to close the TCP connection.

The same problem does not happen with ThreadPoolExecutor.

## Expected behavior

when keep-alive is off. Server should close the underlying tcp socket after the response is sent. 

## Actual behaviour

The tcp connection remains in 'established state' as reported by netstat. Tracing suggests the transport.close has been called but no effect.
```
/Users/tingfan/umbo/VisionDolphin/python/cvworker/.env/lib/python3.6/site-packages/aiohttp/web_protocol.py(515)start()
    514                 if self.transport is not None:
--> 515                     self.transport.close()
    516 
```
## Steps to reproduce

Start a aiohttp based webserver serving at http://localhost:8080/
```
#!/usr/bin/env python
from aiohttp import web
import time
import asyncio
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor

executor = ProcessPoolExecutor(1)
loop=asyncio.get_event_loop()

async def handler(request):
    await loop.run_in_executor(executor, time.sleep, 0.1)
    print('done')
    return web.Response(text='resp')

app=web.Application()
app.router.add_get('/', handler)
web.run_app(app, host='localhost', port=8080)
```

In another shell use apache bench to connect. It will hang instead of complete the test.
`
ab -n 1 http://localhost:8080/
`

What's interesting is if one make any new request to the same server. The new request will be processed without issue. Only the first request on a fresh server will hang.

## Your environment
OSX 10.12.5 / Ubuntu 16.04
python 3.5.2 / 3.6.1
aiohttp==2.3.0a0  / 2.1

**Comment by 0wu** [comment]
Is there anything I can help clarify?

**Comment by asvetlov** [comment]
Have no idea what's going on.
`wrk` tool works fine.
I see the hang on `ab` but analyzing `strace` output for aiohttp server shows that the server sends a response and closes incoming socket in time. 

Have no idea why `ab` doesn't process it.

**Comment by asvetlov** [comment]
Closing the issue.
Don't know what can we do here.
