### ISSUE TITLE
Preparing a websocket from a low-level-server request fails

### ISSUE THREAD

**Issue by jhrmnn** [aio-libs/aiohttp#2024]
A request from a low-level server does not have the `app` attribute, but `web.WebSocketResponse.prepare()` takes the event loop from `BaseRequest.app.loop`.

```
  File ".../aiohttp/web_ws.py", line 103, in _pre_start
    self._loop = request.app.loop
AttributeError: 'BaseRequest' object has no attribute 'app'
```

I was able to fix this by assigning a mock app to the request, which has a single `loop` attribute.

**Comment by asvetlov** [comment]
Nice catch!
I think it should be fixed by storing a reference to loop in `BaseRequest` constructor.
