### ISSUE TITLE
Websocket does not register disconnected Safari browser

### ISSUE THREAD

**Issue by jhrmnn** [aio-libs/aiohttp#2025]
With [Websockets](https://websockets.readthedocs.io), when Safari is reloaded or tab closed, the websocket server registers a closed connection. This is not the case with Aiohttp. But Aiohttp correctly registers the disconnection with Chrome. I don't know anything about the websocket protocol internals, but I guess there is a difference in what both browsers send on tab close/reload. In any case, Websockets somehow registers that event in both browsers, but Aiohttp doesn't.

Take the following app. When going to http://localhost:8080/websockets and reloading the site several times, the app emits alternating "Got client", "Lost client" with both Safari and Chrome. Now go to http://localhost:8080/aiohttp: only Chrome triggers lost connections.

```python
import asyncio
from aiohttp import web
import websockets

asyncio.get_event_loop().set_debug(True)

site = """\
<!doctype html>
<script>
const ws = new WebSocket(`ws://{href}`);
</script>
<body></body>"""


async def websockets_handler(ws, path):
    print('Got client')
    while True:
        try:
            print(await ws.recv())
        except websockets.ConnectionClosed as e:
            break
    print('Lost client')


async def aiohttp_ws_handler(request):
    ws = web.WebSocketResponse(autoclose=False)
    await ws.prepare(request)
    print('Got client')
    async for msg in ws:
        print(msg)
    print('Lost client')
    return ws


async def site_handler(request):
    if request.path == '/aiohttp':
        href = 'localhost:8080/ws'
    elif request.path == '/websockets':
        href = 'localhost:6060'
    return web.Response(text=site.format(href=href), content_type='text/html')

asyncio.ensure_future(websockets.serve(websockets_handler, 'localhost', 6060))

app = web.Application()
app.router.add_get('/aiohttp', site_handler)
app.router.add_get('/websockets', site_handler)
app.router.add_get('/ws', aiohttp_ws_handler)
web.run_app(app, host='localhost', port=8080)
```

**Comment by asvetlov** [comment]
Sorry, I have no MacOSX box -- Linux only.
Could somebody take a look on the issue?

**Comment by jhrmnn** [comment]
Btw, Firefox behaves the same way as Chrome: Both aiohttp and websockets register the disconnect. So yes, this will need someone with macOS.

**Comment by fafhrd91** [comment]
I'll check this

**Comment by s-kostyuk** [comment]
@azag0 I think it's related with #2368 and #2309.

Looks like Firefox and Chrome send a special CLOSE frame just before the tab will be reloaded and the connection will be closed. So, in a case of those two browsers, connection is closed gracefully, by a server, in response to the CLOSE frame.

Safari, on the other side, just closes connection abruptly, without sending a CLOSE frame. And thus for some reason aiohttp keeps listening for new packets, even if the client is gone and underlying connection was closed.

Again, it's all just assumptions. I'm a Linux user too and can't test behavior of Safari. But you can test it yourself - just enable [asyncio debugging mode](https://docs.python.org/3/library/asyncio-dev.html) and watch for the following message: `Ignored premature client disconnection` (https://github.com/aio-libs/aiohttp/issues/2309#issuecomment-387003258) in logs. If you found that message in logs - congratulations! aiohttp still can't handle such disconnections yet

**UPD**: But there is a workaround: https://github.com/aio-libs/aiohttp/issues/2283#issuecomment-331136885

**UPD2**: Also attempts to receive the next frame on a closed connection raise CancelledErrors: https://github.com/aio-libs/aiohttp/issues/2061. So we can just catch CancelledError exceptions to detect disconnections.

**UPD3**: Possibly, [heartbeats](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.WebSocketResponse) (periodic pings) are also mandatory for disconnection detection to work

**Comment by asvetlov** [comment]
See #2675 for cancellation logic changing.

I'm closing the issue because of long inactivity period, I even not sure that the problem exists.
Please feel free to open a new one with detailed info if needed.

**Comment by jhrmnn** [comment]
I have slightly updated the code snippet to work with the current `websockets` version.

@s-kostyuk I get no messages about client disconnection when the asyncio debug mode is enabled.

This is really a non-issue, I guess. If the aiohttp websocket server just responds to requests from the client, it will never know that the client had died, but that doesn't really matter. If it sends messages to the client without any prompt, it will find out from the thrown exception.

**Comment by s-kostyuk** [comment]
@azag0, so, the only thing I can recommend is to enable heatbeat, handle exceptions and implement some acknowledge mechanisms **if** it's important to ensure that a message was delivered to client. Otherwise, if client lost connection to the server (WiFi gone down, for example), the server will not notice half-closed connection and will send messages as usual... to nowhere

**Comment by james4388** [comment]
Problem still exist with 3.3.2 :(

**Comment by james4388** [comment]
@s-kostyuk Also try heartbeat and timeout and auto close but it's not working
Exception handler is not working
only see `WARNING:asyncio:socket.send() raised exception.`
Also check for `socket.closed` it say still open

**Comment by s-kostyuk** [comment]
@james4388 I'm starting to thing that the whole situation with disconnection detection will stay mysterious until someone will get a Wireshark, a descent debugger and will finally debug/fix WebSocket implementation. And considering to try Sanic for future projects, because Sanic uses aaugustin/websockets as WS implementation
