### ISSUE TITLE
Implement Connection.startssl(ssl_context) coroutine

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2028]
Prerequirement for #2019

The change makes sense itself -- it simplifies upgrade SSL proxy connection and makes code cleaner.

**Comment by fafhrd91** [comment]
do you expect anyone would create proxy with aiohttp?

**Comment by asvetlov** [comment]
No, I'm thinking about aiohttp internals refactoring only.

Now `TCPConnector` for SSL upgrade does the following:

1. Create a `Connection` for sending `CONNECT` request without registering it in connection pool.
2. Clean up `Connection._transport` (BTW not used anymore attribute) and `Connection._protocol`
3. Negotiate TLS connection by calling `loop.create_connection` with duplicated socket.
4. Close transport
5. Return a new protocol given from TLS

It works but looks cumbersome.
I recall request for SSL upgrade for UNIX sockets. I don't want to copy all this code to UNIX Connector.

Let me experiment with implementation and make a PR.
If I've found the idea is dead -- I reject it.
But now moving ssl upgrade from connector layer to `ClientSession._request` makes sense in my mind.

**Comment by fafhrd91** [comment]
initially I thought about different use case. now it makes more sense.

**Comment by asvetlov** [comment]
Let's close the issue, it should be created on new basis
