### ISSUE TITLE
ClientSession created in aiohttp.request() remains unclosed

### ISSUE THREAD

**Issue by das7pad** [aio-libs/aiohttp#2036]
## Long story short

Using ``aiohttp.request()`` to file http requests spamms the logfiles.

The ``aiohttp.ClientSession`` created in ``aiohttp.request()`` should be closed gracefully, but currently the session reference is just deleted.

## Expected behaviour
No resource warning from using ``aiohttp.request``

## Actual behaviour

Unclosed ``aiohttp.ClientSession``s messages for every request
see https://github.com/tdryer/hangups/issues/340

## Steps to reproduce

call ``aiohttp.request``
https://github.com/tdryer/hangups/blob/master/hangups/http_utils.py#L33-L36

From another project you can find a tester with results on different aiohttp version here:
https://gist.github.com/das7pad/e8f63175377576a0cb3466d20a417fa5

## Your environment

``python v3.5.3``

``aiohttp v2.2.0``

**Comment by das7pad** [comment]
I already have a fix for this issue but as version 2.2.0 is not added to the v2 release branch, I can not submit a pull request to it that could pass all the checks then.
Using the main branch currently throws ``AssertionError``s for the refactored header handling in version 2.3.x and bad lower/upper case usage.

I created a branch from the version tag 2.2.0 and commited there: https://github.com/das7pad/aiohttp/tree/close-created-session
Feel free to cherrypick the commit https://github.com/das7pad/aiohttp/commit/6052619bcb716dc7740253c7f0eb3f6b8fe67348 instead of a PR or guide me to which branch I should commit it to.

**Comment by asvetlov** [comment]
I recommend switch from `aiohttp.request()` to `ClientSession.request()` with proper session closing.

**Comment by das7pad** [comment]
But this change literally deprecates ``aiohttp.request()``.
Application X is now forced to have a more complex setup for a single http request with creating a session, then filing the request from this session and closing the request and session at the end. In addition it has to extend the Exception-handling to close the additional session resource.

In python version 3.5 one could simply use ``async with`` for the session and request, but for version 3.4 it is more than that:
https://gist.github.com/das7pad/4ff20e6a8e7e3242bffb9ee9c30809d3
Every application has to change the http requests now when using ``aiohttp.request`` before.

**Comment by fafhrd91** [comment]
we can silence warning for `aiohttp.request()`

**Comment by asvetlov** [comment]
> we can silence warning for aiohttp.request()

Good to me.

Honestly I want to remove `aiohttp.request()` at all. Maybe along with future drop of Python 3.4 support.
Is there reason to keep the function?

**Comment by fafhrd91** [comment]
simplicity. 
@asvetlov I noticed, you like ceremony a lot :)

**Comment by asvetlov** [comment]
aiohttp is OSS project.
Our changes and overall design should be clean and visible for library users.
It's not a ceremony for ceremony but a way to reduce breaking changes.

Well, I could buy your argument for keeping `aiohttp.request()`. Forcing usage to `async with aiohttp.request()` could get a place for proper session shutdown.

**Comment by fafhrd91** [comment]
What could be cleaner than `aiohttp.request()` ?
Even with async with you can get same warning, even with `with ClientSession` you can get warning. Python just can't enforce right usage. Did you forget your change to clientresponse? Closing session after exit from context is not safe operation.

**Comment by asvetlov** [comment]
Ok, let's just suppress a warning

**Comment by das7pad** [comment]
>  Closing session after exit from context is not safe operation.

@fafhrd91 is that a note to this line? https://gist.github.com/das7pad/4ff20e6a8e7e3242bffb9ee9c30809d3#file-aiohttp_fetch_comparison-py-L29

**Comment by fafhrd91** [comment]
@das7pad I am talking about using session as async context manager. you example is fine.

**Comment by asvetlov** [comment]
The functionality was changed and fixed in aiohttp 3.0
