### ISSUE TITLE
Websocket do not close if use asyncio.wait to handle websocket

### ISSUE THREAD

**Issue by tguillemot** [aio-libs/aiohttp#2037]
## Long story short
To design a websocket proxy I must create a websocket handler coroutine executed by asyncio.wait. 
To be more clear here is a simple example of the code:
```
import aiohttp
import asyncio

from aiohttp import web


async def handle_ws_message(ws):
    print("Bengin handle_ws_message")
    async for msg in ws:
        print(msg)
        if msg.type == aiohttp.WSMsgType.TEXT:
            break
    print("End handle_ws_message")


async def handle_request(request):
    print("Begin handle_request")
    ws = web.WebSocketResponse()
    await ws.prepare(request)
    print("WS ready")
    await asyncio.wait(
        [handle_ws_message(ws)],
        return_when=asyncio.FIRST_COMPLETED
    )
    print("End handle_request")
    return ws


app = web.Application()
app.router.add_route('*', '', handle_request)
web.run_app(app, port=8080)
```
## Expected / Actual behaviour

From google chrome on linux, if I open a websocket using :
```js
ws = new WebSocket("ws://127.0.0.1:8080")
ws.send('hello')
```
I obtain the expected result on my terminal:
```
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
Begin handle_request
WS ready
Bengin handle_ws_message
WSMessage(type=<WSMsgType.TEXT: 1>, data='hello', extra='')
End handle_ws_message
End handle_request
```

But if I open a websocket from google chrome on linux using:
```js
ws = new WebSocket("ws://127.0.0.1:8080")
```
and then close the tabs, I observe on my terminal : 
```
Begin handle_request
WS ready
Bengin handle_ws_message
End handle_ws_message
```
instead of :
```
Begin handle_request
WS ready
Bengin handle_ws_message
End handle_ws_message
End handle_request
```

On that case, it seems that the coroutine never ended.
A bug maybe ?

## Your environment
Executed using linux ubuntu 16.04 (64-bit) on python 3.6 with aiohttp 2.0.5.
Navigator: Google chrome 58.0.3029.110 (64-bit)

**Comment by alexmnazarenko** [comment]
Interesting ) Not sure if it's an issue with aiohttp or with asyncio.

Your handler gets cancelled, you can see it if you surround `asyncio.wait()` with try/except.

**Comment by tguillemot** [comment]
> Your handler gets cancelled, you can see it if you surround asyncio.wait() with try/except.

Indeed, it's a really strange behavior. Maybe it's an asyncio problem indeed. I can open an issue on asyncio too, if you want ?

**Comment by asvetlov** [comment]
Nothing strange, `wait()` is a coroutine and could be cancelled before finishing.
You need another technique: wrap everything into `try/finally`:
```
async def handle_ws_message(ws):
    print("Bengin handle_ws_message")
    ws = web.WebSocketResponse()
    await ws.prepare(request)
    try:
        async for ws:
            ...
    finally:
         print("End handle_ws_message")
    return ws
```

**Comment by tguillemot** [comment]
That's true but I don't really understand on that case why the coroutines is cancelled instead of finished normally (but it's certainly not the place to talk about it).

Try/finally solve my problem thanks @asvetlov.

**Comment by alexmnazarenko** [comment]
Mechanism is clear. I'am also doing some proxying and so have some pretty convoluted handlers. It's unpleasant idea that I need to expect a cancel from each and every await.

This behavior looks ~ok for simpler handlers (e.g. plain GET), but not for more complicated ones which hold some resources (including other asyncio tasks, which won't be cancelled).

Who cancels this task? Should we always handle cancel exceptions in our route handlers?

**Comment by asvetlov** [comment]
The problem is connection handling.
Peer may drop connection at every moment.
Web handler should be closed immediately -- there is no reason to run it if communication channel for sending requested data back is gone.
That's why the handler is cancelled.
Sometimes it is desirable behavior but sometimes not.

I'm working on support for spawning jobs from web handler, jobs supposed to be cancelled only on application shutdown.
The project is in very early stage (#2008). The source code will be extracted into separate library.
API and concept is not stabilized yet.

**Comment by alexmnazarenko** [comment]
Ok, thanks for the info. The Job API will be useful.

As for request handlers, careful try-except-finally will save us all )

**Comment by tguillemot** [comment]
Thanks @asvetlov for the explanation, I better understand the problem now. 
I will have a look to your library :)

**Comment by asvetlov** [comment]
https://github.com/aio-libs/aiojobs
