### ISSUE TITLE
add_route does not allow **kwargs

### ISSUE THREAD

**Issue by psuresh39** [aio-libs/aiohttp#2038]
## Long story short

add_route does not allow **kwargs, it should. Open to suggestions here.

## Expected behaviour

add_get supports it but not add_route. add_route should ideally support it.
## Steps to reproduce
pass **kwargs to add_get will give this exception: TypeError: add_route() got an unexpected keyword argument

**Comment by asvetlov** [comment]
`add_route` is not supposed to silently eat all unprocessed arguments.
But maybe I misunderstand your problem.
What exact argument is not supported?

**Comment by psuresh39** [comment]
I realized I did not provide a clearer example. Here's how to repro:

```
def testing(request, options):
    print(options)

app = web.Application()
app.router.add_get(
    '/test',
    testing,
    option1=abc, 
    option2=xyz
)
```


This seems to raise a error: 
`TypeError: add_route() got an unexpected keyword argument`

How can I pass such options into a handler ?

**Comment by asvetlov** [comment]
I don't think it's good idea.
Use ` app.router.add_get('/ws', functools.partial(websocket_handler, option1=abc, option2=xyz))`

**Comment by psuresh39** [comment]
I see what you are saying. but wouldn't it be a cleaner api for developers if they did not have to use functools and if the library behaved like other web frameworks ?

**Comment by psuresh39** [comment]
> I don't this it's good idea.

Did you mean you think the suggestion is a bad idea ?

**Comment by samuelcolvin** [comment]
You shouldn't need to pass extra arguments to view functions. You should use `app` like a dictionary and add your options to the app when initialising your server.

**Comment by asvetlov** [comment]
Mixing parameters for router (like `add_head=True` or `expect_handler`) with ones should be passed inside web handler makes a mess.
Why `functools.partial` doesn't satisfy your needs?
What other framework supports requested functionality?
IIRC neither Django not Flask.

**Comment by psuresh39** [comment]
I see you point guys. Adding it to the app as @samuelcolvin  suggested is a satisfactory approach. Thanks everyone.

**Comment by asvetlov** [comment]
@samuelcolvin you caught @coolnay309 mind better than me.
I though he want to pass some per-view configuration parameter.
