### ISSUE TITLE
Replace http_writer.URL with yarl.URL.build

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2048]
@fafhrd91 you added this class.

But now construction from parts is supported by yarl: https://yarl.readthedocs.io/en/latest/api.html#yarl.URL.build

Is there reason to keep duplicated code in aiohttp?

Did I miss something?

**Comment by fafhrd91** [comment]
Not really. Let's replace it

**Comment by asvetlov** [comment]
Fixed by @2051
