### ISSUE TITLE
body content length measured in characters instead of bytes

### ISSUE THREAD

**Issue by r7ar7a** [aio-libs/aiohttp#2066]
## Long story short

Content-Length can be miscalculated if multipart body contains special characters (represented by more htan one bytes). I think the following line causes the trouble, since it uses the length of a string instead of the respective byte array.
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/payload.py#L243

## Steps to reproduce

```
import asyncio
import aiohttp
from aiohttp import ClientSession
from io import StringIO

loop = asyncio.get_event_loop()
session = ClientSession(loop=loop)

data = {'asd123': StringIO('ű' * 5000)}
async def x():
    await session.post('http://localhost:2000', data=data)
a = loop.run_until_complete(x())
```

This program results in the following http query:
```
...$ ncat -l 2000 --keep-open --sh-exec '/bin/cat | tee /dev/stderr'

POST / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Host: localhost:2000
User-Agent: Python/3.6 aiohttp/2.2.3
Content-Length: 5232
Content-Type: multipart/form-data; boundary="39e3d5a33c8d4837b3c4a9dfabb3f971"

--39e3d5a33c8d4837b3c4a9dfabb3f971
Content-Disposition: form-data; name="asd123"; filename="asd123"; filename*=utf-8''asd123
Content-Type: text/plain; charset=utf-8
Content-Length: 5000

űűűűűűűűűűűűűűűű...
```

## Your environment

Python 3.6.1
aiohttp==2.2.3

**Comment by asvetlov** [comment]
Good point.
Perhaps it should be replaced with `return len(self._value.getvalue().encode(self._encoding))`
@fafhrd91 ?

**Comment by fafhrd91** [comment]
I agree, this should be fixed. is it possible to convert value once?

**Comment by asvetlov** [comment]
Could do it in `__init__` I guess

**Comment by fafhrd91** [comment]
I think `StringIOPayload` should inherent from `StringPayload`

**Comment by fafhrd91** [comment]
fixed in master
