### ISSUE TITLE
Disable Cookie Handling

### ISSUE THREAD

**Issue by brianjpetersen** [aio-libs/aiohttp#2067]
I'd like to disable cookie processing in the general case for the session but to allow them to be set for requests with redirects.  For example, a request to `httpbin.org/cookies/set?a=1` results in a redirect to `httpbin.org/cookies` with the appropriate `Set-Cookie` header.  If I use a custom cookie jar (per Issue #957) that implements `update_cookies` as a no-op, when the redirect is followed, the cookies set in upstream requests aren't applied during subsequent redirects.

Aside from disabling redirects, setting cookies manually in the case of a redirect and following it manually, is there a way to deal with cookies more granularly than on a per-session basis?

**Comment by hubo1016** [comment]
Maybe create a new session for every request?

**Comment by brianjpetersen** [comment]
Thanks - that could work, although I'd lose the benefits of connection pooling, right?

**Comment by fafhrd91** [comment]
you can use custom connection object and pass `connector_owner=False` to Client session.

**Comment by brianjpetersen** [comment]
Ahh, awesome.  Thanks so much!

**Comment by asvetlov** [comment]
Fixed by 0d9abc9
