### ISSUE TITLE
Backports

### ISSUE THREAD

**Issue by cecton** [aio-libs/aiohttp#2069]
## Long story short

The following commits could be backported to at least 2.2:
 *  afbff7b30fee30cc1e52abeb23a82d08b2396a36 (fix)
 *  6ba5d61e1fa056e4c5816c4aae204127b806446d (test improvement)

## Expected behaviour

/

## Actual behaviour

/

## Steps to reproduce

/

## Your environment

ArchLinux, Python 3.6

**Comment by asvetlov** [comment]
I'm in travel thus not very responsive.
Not sure if I want to apply backport but I'll definitely consider it if the project will need new bugfix release.

aiohttp 2.3 will be published in 3-4 weeks I think.

**Comment by cecton** [comment]
@asvetlov thanks a lot :)
