### ISSUE TITLE
Document about Access log cause confusion

### ISSUE THREAD

**Issue by mapler** [aio-libs/aiohttp#2085]
## Long story short

When I followed the document [here](http://aiohttp.readthedocs.io/en/stable/logging.html#access-logs) to disable access log. It seems not working.

## Expected behaviour

Just use `app.make_handler(access_log=None)` for disabling access log.

## Steps to reproduce

``` python
app.make_handler(access_log=None)
web.run_app(app)
```

After I check the source code [here](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web.py#L428). I know I make mistake about the usage of `make_handler`.
But I think `run_app(app, access_log=None)` is better and more clear than `app.make_handler(access_log=None)` in document.

**Comment by asvetlov** [comment]
Yes. Doc about logger disabling was created before introducing `run_app()` function.

Could you create a PR for doc update?

**Comment by asvetlov** [comment]
Fixed by #2085
