### ISSUE TITLE
Client Content-Type header in response is case sensitive

### ISSUE THREAD

**Issue by argaen** [aio-libs/aiohttp#2095]
## Long story short

When using `response.json()`, if the server sends back a header that doesnt match the case of `Content-Type`, it doesn't work https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_reqrep.py#L723

The behavior was introduced with the following commit: https://github.com/aio-libs/aiohttp/commit/8974844fb1618b2fe6882b0e2dcf2dee60bc9eae (@fafhrd91)

## Expected behaviour

`json()` should work when server sends back a header that doesn't match the case i.e. `CONTENT-TYPE`, `content-type`, etc.

aiohttp==2.2.3

**Comment by fafhrd91** [comment]
Might this be recent changes in multidict?

**Comment by argaen** [comment]
Mmmm no idea, @asvetlov?

**Comment by argaen** [comment]
Nope, I can reproduce this with multidict==2.1.4 which was released December last year. I'm going to provide a MR for this

**Comment by argaen** [comment]
Mmmhhh I think I was doing something wrong with my unit tests. Closing for now, sorry for the noise

**Comment by fafhrd91** [comment]
Headers should be case insensitive

**Comment by asvetlov** [comment]
And they are!

**Comment by argaen** [comment]
Yup, the problem was me mocking headers in one test. Sorry for the noise guys
