### ISSUE TITLE
Please enable coveralls for repo

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#210]
Repo is ready for coverage reports, please just login on https://coveralls.io and enable KeepSafe/aiohttp project.

I cannot do that because I have no admin rights for aiohttp.

**Comment by fafhrd91** [comment]
this service wants access to all my private repos. this won't  happen.

**Comment by asvetlov** [comment]
Ok. Sorry.
I've removed coveralls from .travis.yaml

On Sat, Jan 3, 2015 at 9:31 PM, Nikolay Kim notifications@github.com
wrote:

> this service wants access to all my private repos. this won't happen.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KeepSafe/aiohttp/issues/210#issuecomment-68606453.

## 

Thanks,
Andrew Svetlov

**Comment by fafhrd91** [comment]
Wait, let me check. Maybe Phillip can admin role to you

**Comment by asvetlov** [comment]
I like to see coveralls progress but can live without it.
Of course it should be for aiohttp project only, not for all KeepSafe
private repos,

On Sat, Jan 3, 2015 at 9:38 PM, Nikolay Kim notifications@github.com
wrote:

> Wait, let me check. Maybe Phillip can admin role to you
> 
> On Saturday, January 3, 2015, Andrew Svetlov notifications@github.com
> wrote:
> 
> > Ok. Sorry.
> > I've removed coveralls from .travis.yaml
> > 
> > On Sat, Jan 3, 2015 at 9:31 PM, Nikolay Kim <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > this service wants access to all my private repos. this won't happen.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/KeepSafe/aiohttp/issues/210#issuecomment-68606453.
> > 
> > ## 
> > 
> > Thanks,
> > Andrew Svetlov
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/KeepSafe/aiohttp/issues/210#issuecomment-68606643.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KeepSafe/aiohttp/issues/210#issuecomment-68606708.

## 

Thanks,
Andrew Svetlov
