### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by iSevenDays** [aio-libs/aiohttp#2116]
## Long story short
I have an error when parsing some of responses
    if 'some_text in await response.text():
  File "/Users/seven/python/miniconda3/envs/py36/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 711, in text
    encoding = self._get_encoding()
  File "/Users/seven/python/miniconda3/envs/py36/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 689, in _get_encoding
    ctype = self.headers.get(hdrs.CONTENT_TYPE, '').lower()
AttributeError: 'NoneType' object has no attribute 'lower'

## Expected behaviour

No error

## Actual behaviour

Exception AttributeError

## Steps to reproduce

I can provide only log files as I have a very complicated system

## Your environment

Latest aiohttp 2.2.3, Mac Os, using aiohttp with proxies

```
            async with session.request(method, url, proxy=https_proxy,
                                       headers=headers, data=data,
                                       params=params, timeout=req_timeout,
                                       skip_auto_headers={istr('user-agent'),
                                                          istr('connection')}) as response:
```
...

**Comment by argaen** [comment]
Hmmm I believe this error is because the server is not returning any `Content-Type` header back. This sounds like a bug to me because according to the RFC (https://www.ietf.org/rfc/rfc2045.txt Content-Type defaults section), if no header is sent back we should default to `text/plain`.

@iSevenDays can you confirm the server is not sending back any `Content-Type` header?

**Comment by fafhrd91** [comment]
Do you try to request real public URL? It would be good to be able to reproduce the problem

**Comment by iSevenDays** [comment]
I will try to check, but seems that a server sometimes doesn't send content-type, but all other requests have content-type application/json

**Comment by argaen** [comment]
Hmmm I was checking, if the server doesn't send back `Content-Type` header it works anyway because of the `self.headers.get(hdrs.CONTENT-TYPE, '')`:

```python
import aiohttp
import asyncio


async def test():
    async with aiohttp.ClientSession() as session:
        async with session.get('https://api.github.com/events') as resp:
            resp._content = "Random"
            new_headers = dict(resp.headers)
            new_headers.pop('Content-Type')
            resp.headers = new_headers
            print(await resp.text())
            print(resp.status)

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```
So in order to make it crash, you should explicitly set the key of `hdrs.CONTENT-TYPE` to None to make it crash... I wonder where this may happen.

**Comment by fafhrd91** [comment]
@iSevenDays could you post url your are trying to access? self.headers should not contain None's

**Comment by asvetlov** [comment]
Close issue as invalid.
Feel free to create new one with detailed instructions for the problem reproducing.
