### ISSUE TITLE
request.get got status code 204

### ISSUE THREAD

**Issue by NeverMoes** [aio-libs/aiohttp#2117]
[Here is a json api](http://api.m.taobao.com/h5/mtop.taobao.detail.getdetail/6.0/?appKey=12574478&t=1471594755592&api=mtop.taobao.detail.getdetail&v=6.0&ttid=2013%40taobao_h5_1.0.0&type=jsonp&dataType=jsonp&&data=%7B%22itemNumId%22%3A%22543136119626%22%2C%22exParams%22%3A%22%7B%5C%22id%5C%22%3A%5C%22543136119626%5C%22%7D%22%7D)

When I use requests to request it, it will return status 200 and json context.
But aiohttp got 204.
Here is my code.

```python
import aiohttp
import asyncio
import async_timeout
import requests

url = 'http://api.m.taobao.com/h5/mtop.taobao.detail.getdetail/6.0/?appKey=12574478&t=1471594755592&api=mtop.taobao.detail.getdetail&v=6.0&ttid=2013%40taobao_h5_1.0.0&type=jsonp&dataType=jsonp&&data=%7B%22itemNumId%22%3A%22543136119626%22%2C%22exParams%22%3A%22%7B%5C%22id%5C%22%3A%5C%22543136119626%5C%22%7D%22%7D'

async def fetch(session, url):
    with async_timeout.timeout(10):
        async with session.get(url) as response:
            print(response.status)
            return await response.text()

async def main():
    async with aiohttp.ClientSession() as session:
        text = await fetch(session,url)
        print(text)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())

#######################

print(requests.get(url).text)

```

It really confusing...

**Comment by alex-eri** [comment]
api.m.taobao.com sims block robots in this way. try change User-Agent
