### ISSUE TITLE
DynamicResource can't be subclassed

### ISSUE THREAD

**Issue by pieterb** [aio-libs/aiohttp#2118]
## Long story short

class `DynamicResource` can't be subclassed because (part of) its constructor logic is in `UrlDispatcher.add_resource()`

## Expected behaviour

As a developer, when implementing custom dynamic resource types, I expect it to be possible to derive my new resource type from DynamicResource. I expect the constructors of `DynamicResource` and `PlainResource` to have the same signature

    def __init__(self, path, *, name=None)

where `PlainResource` takes a plain path, and `DynamicResource` takes a templated path.

## Actual behaviour

But when I do so, I find out that the constructor of DynamicResource takes two undocumented parameters (`pattern` and `formatter`) that are very tightly bound to how `UrlDispatcher.add_resource()` constructs either a `PlainResource` or `DynamicResource`.

## Solution

Move constructor logic of class `DynamicResource` from `UrlDispatcher` to where it belongs: `DynamicResource.__init__()`.

I'll submit a PR for this.

**Comment by asvetlov** [comment]
DinamicResource is not intended for inheritance.
If you need it - you are doing something wrong.

**Comment by pieterb** [comment]
I understand (and half expected) your response.

You might still want merge PR #2119 though. I think it's slightly cleaner.

**Comment by asvetlov** [comment]
Fixed by #2119

**Comment by asvetlov** [comment]
Just curious: why do you need subclass DynamicResource?
What is your use case?

**Comment by pieterb** [comment]
To explain how I (maybe erroneously) ended up subclassing DynamicResource, I'll give a "chronological" record:

I am developing a service that will (asynchronously) stream large HAL-JSON responses to clients. The service has multiple (templated) URLs and most of these share a lot of functionality: most of them accept identical query parameters, such as `page_number` and `items_per_page` for paged responses, and `embed` to request embedding of "sub-resources" into the response body.

Reading through the documentation, I thought a nice way of implementing my service was by creating my own inheritance-tree of Resource-classes (all inheriting from `AbstractResource`). I soon found out that `AbstractResource` is very abstract indeed. In order for my classes to play nicely together with the default router (`UrlDispatcher`) I was duplicating a lot of code that was already in `PlainResource` and `DynamicResource`.

So I quickly switched from inheriting `AbstractResource` to inheriting `PlainResource` and `DynamicResource` instead. It was then that I found out that the constructor parameters of `DynamicResource` were intimately coupled with `UrlDispatcher`: in order to construct my own "Sub-DynamicResource"-objects I had to duplicate code in `UrlDispatcher.add_resource` into my own code, at which point I created this issue, and send you pull request #2119.

**Comment by pieterb** [comment]
At the same time, however, my colleague @evertlammerts was reviewing my code. He'd been using aiohttp before, and told me my code was hard to read and understand, partly because he thought I wasn't doing things the "aiohttp-way".

So I refactored my code, stopped implementing my own AbstractResource-classes, and started using `UrlDispatcher` more like the documentation suggests I should.

So everything's ok for now. By offering the `register_resource()` method, you still do support custom Resource classes (which must implement `AbstractResource`), is that right? If so, I'm still a bit confused why the functionality in `PlainResource` and `DynamicResource`, which is very common, shouldn't be part of aiohttp's public interface.
