### ISSUE TITLE
Suggest: add Access Logging option to show `X-Forwarded-For`

### ISSUE THREAD

**Issue by harobed** [aio-libs/aiohttp#2123]
Suggest: add Access Logging option to show `X-Forwarded-For`

Exemple `%f` option return `X-Forwarded-For` value or Remote IP-address if `X-Forwarded-For` don't exist.

**Comment by asvetlov** [comment]
I suggest another change: pass `request` instead of `message` into `AccessLogger.log` (since aiohttp 2.0 `web_protocol.RequestHandler` always create a request instance.
In turn `web.BaseRequest` has `req.host` property, the property respects both `Forwarded` and `X-FORWARDED-HOST` headers.

**Comment by asvetlov** [comment]
@harobed do you want to make a PR for implementing my proposal?

**Comment by harobed** [comment]
Yes, maybe this evening.
