### ISSUE TITLE
Rename changes to CHANGES 

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2130]
The reason is: I want to see changes update in PR at very first place, it simplifies review.
Other option is `changes` -> `CHANGES` rename.

Opinions?

**Comment by asvetlov** [comment]
If nobody object will do it after 2.3 release.

**Comment by webknjaz** [comment]
https://github.com/aio-libs/aiohttp/blob/master/pyproject.toml#L4 what about this?

**Comment by asvetlov** [comment]
Good catch!
Fixed by b213d661

**Comment by webknjaz** [comment]
why don't you just read that config to keep things in a single place?

**Comment by asvetlov** [comment]
What code should read the config?

**Comment by webknjaz** [comment]
https://github.com/aio-libs/aiohttp/commit/969dc5659c98a7556178a9b95cd710be8c6de5dc#diff-58a40afaf674c2840d1dbacfc236d17cR26

**Comment by asvetlov** [comment]
Well, I hope we'll never touch the script anymore.
I respect your striving to have all such config params in single place but please let's keep the script simple.
We can return to the subject on next `CHANGES` renaming, sure.
