### ISSUE TITLE
Giving commit rights to Cecile Tonglet

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2133]
@cecton is very active for last months.
Moreover she is very responsive for review comments etc.

I propose to give she commit rights.

We emailed the main rules already: make PR's for every significant change, don't break code etc.
Pretty sure she will power our team.

Please vote: +1 or silence means acceptance, -1 is a subject for discussion :)

**Comment by fafhrd91** [comment]
+1

**Comment by jettify** [comment]
Not sure I have voting powers here but +1

**Comment by kxepal** [comment]
+1

**Comment by asvetlov** [comment]
@jettify pretty sure you are.
But vote from @fafhrd91 is much powerful than yours :)

**Comment by asvetlov** [comment]
Looks like we have an agreement.
Pretty fast, I expected a day at least

**Comment by asvetlov** [comment]
Invitation sent to @cecton

**Comment by cecton** [comment]
Thanks a lot to all 💋

**Comment by asvetlov** [comment]
Welcome to aiohttp team!

**Comment by kxepal** [comment]
Congrats, @cecton ! And welcome (: 🎉

**Comment by fafhrd91** [comment]
welcome!

**Comment by asvetlov** [comment]
@cecton if you need access to other aio-libs projects -- please let me know.

**Comment by cecton** [comment]
If I may... I would like to move aiosparql to aiohttp

**Comment by asvetlov** [comment]
I know nothing about SPARQL
But if you want to keep supporting the library and be the main person for drive it going-- why not?

**Comment by kxepal** [comment]
@cecton I guess you mean "to aio-libs", right?

**Comment by cecton** [comment]
Yes actually ^_^ I will be the main person as long as I work with it
