### ISSUE TITLE
TypeError: __new__() takes from 1 to 2 positional arguments but 8 were given

### ISSUE THREAD

**Issue by optimum-web** [aio-libs/aiohttp#2139]
## Long story short

I have a webservice, websocket publisher, after restart I got a strange error

selector_events.py[LINE:65]# DEBUG    [2017-07-28 06:29:09,678]  Using selector: EpollSelector
web_protocol.py[LINE:362]# ERROR    [2017-07-28 06:29:38,467]  Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 278, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 274, in aiohttp._http_parser.HttpParser.feed_data (aiohttp/_http_parser.c:4364)
  File "aiohttp/_http_parser.pyx", line 334, in aiohttp._http_parser.cb_on_url (aiohttp/_http_parser.c:5381)
  File "aiohttp/_http_parser.pyx", line 544, in aiohttp._http_parser._parse_url (aiohttp/_http_parser.c:8777)
TypeError: __new__() takes from 1 to 2 positional arguments but 8 were given

## Expected behaviour

websocket server start 

## Actual behaviour

Get Error 500

## Your environment

Docker   debian:jessie (python:slim)

**Comment by fafhrd91** [comment]
What version of aiohttp? Is it reproducible or flaky?

**Comment by optimum-web** [comment]
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiohttp
>>> aiohttp.__version__
'2.2.3'
>>> 

I am trying to reproduce now.  And will attach the code.

**Comment by optimum-web** [comment]
Now it happens constantly, here is the code
`@router('/read/ws/{token}', methods=['GET', ])
async def read_ws(request, **kwargs):

    import time
    websocket = aiohttp.web.WebSocketResponse(timeout=3600, autoclose=True)

    await websocket.prepare(request)

    # simple websocket data generator
    for i in range(10):
        time.sleep(1)
        try:
            websocket.send_json(
                {"alert": 0, "id": 1, "progress": i, "message": "message 1", "level": "info"}
            )
        except Exception as e:
            logging.exception(e)
            logging.warning('Lost connection')
            break
`

**Comment by optimum-web** [comment]
Here is requirements.txt for app

`aiohttp
aiohttp-route-decorator
async-timeout==1.1.0
asynqp==0.5.1
chardet==2.3.0
colorama==0.3.7
gunicorn==19.6.0
multidict==2.1.4
pika==0.10.0
python-digitalocean==1.10.1
redis==2.10.5
requests==2.12.4
yarl==0.8.1
furl
aiodns
cchardet
aiohttp_debugtoolbar`

**Comment by optimum-web** [comment]
Here is browser connection request 
<img width="1020" alt="screen shot 2017-07-28 at 10 26 49" src="https://user-images.githubusercontent.com/12656130/28707141-d53d6fa6-737f-11e7-83f8-697f7891bd04.png">

**Comment by optimum-web** [comment]
I have inserted logging.warning directly in /usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py line 280, in data_received,  so you can see more information below, may be that will help, the output is: 
`
web_protocol.py[LINE:278]# WARNING  [2017-07-28 09:05:19,846]  b'GET /install/read/ws/YtiBhc3bmHJAEeEFuxyFPWrP1zL9n3 HTTP/1.1\r\nHost: myhost.local\r\nX-Real-IP: 172.19.0.1\r\nX-Forwarded-For: 172.19.0.1\r\nX-Forwarded-Proto: http\r\nUpgrade: websocket\r\nConnection: upgrade\r\nPragma: no-cache\r\nCache-Control: no-cache\r\nOrigin: http://myhost.local\r\nSec-WebSocket-Version: 13\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-US,en;q=0.8,nl;q=0.6,ro;q=0.4,ru;q=0.2,it;q=0.2,de;q=0.2,la;q=0.2\r\nSec-WebSocket-Key: oCnavrsbPwSQfXVRz5Cd+w==\r\nSec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n\r\n'
web_protocol.py[LINE:364]# ERROR    [2017-07-28 09:05:19,847]  Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 280, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 274, in aiohttp._http_parser.HttpParser.feed_data (aiohttp/_http_parser.c:4364)
  File "aiohttp/_http_parser.pyx", line 334, in aiohttp._http_parser.cb_on_url (aiohttp/_http_parser.c:5381)
  File "aiohttp/_http_parser.pyx", line 544, in aiohttp._http_parser._parse_url (aiohttp/_http_parser.c:8777)
TypeError: __new__() takes from 1 to 2 positional arguments but 8 were given
` 
thanks

**Comment by arthurdarcet** [comment]
your requirements.txt list dependencies that are too old to be compatible with the latest version of aiohttp.
See https://github.com/aio-libs/aiohttp/blob/master/setup.py#L62

if you really depend on yarl 0.8.1 for instance, then you should also force the aiohttp version to something compatible. And if your only dependency is aiohttp, then your requirements.txt file should not list any other package (and especially not packages with version requirements)
