### ISSUE TITLE
DOC: document that Signal handlers are run sequentally

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#2155]
http://aiohttp.readthedocs.io/en/stable/web.html#signals

This link does not mention significant thing: signal handlers are run sequentally in the order they was registered, even if their handlers are asynchronous.

**Comment by asvetlov** [comment]
Could you make a PR with documentation update?

**Comment by socketpair** [comment]
@asvetlov please take a look.

**Comment by asvetlov** [comment]
Fixed
