### ISSUE TITLE
StaticResource url versioning

### ISSUE THREAD

**Issue by sky-code** [aio-libs/aiohttp#2157]
Add feature for generating urls to static files with version hash to have more control over caching in browser.

## Expected behaviour
When you resolve url from `StaticResource` you can use `append_version` flag to add a hash of file (version) into url, which will change if file content changed and than for browser it's will be new url (which not exists in cache and will be reloaded)

## Example
```html
<script src="{{ url('static', filename='build/js/bundle.js', append_version=True) }}"></script>
```
with `append_version` flag `StaticResource` will append `v` param into url query string  with hash of the file
```
/static/build/js/bundle.js?v=aDc7UcFqFqXFUOYI8crlpxDAW-i41AGSNdDP8eQebSM%3D
```

**Comment by asvetlov** [comment]
Not sure if I want to have the feature in aiohttp.
It looks like solving very specific problem in core while it could be done in third party easily.

Do other libraries/frameworks have the feature? Do nginx support file hashes?

**Comment by sky-code** [comment]
Yes, another web frameworks already have same feature
https://www.davepaquette.com/archive/2015/05/06/link-and-script-tag-helpers-in-mvc6.aspx > Cache Busting

https://www.google.com.ua/search?q=asp.net+core+mvc+append-version

this feature implementation very similar to asp.net core mvc implementation.
I don't see any reason to reject this feature, it's fully optional (you need to use this flag to have any impact) and fully backward compatible with exists code

**Comment by asvetlov** [comment]
Ok

**Comment by asvetlov** [comment]
Done by #2158
