### ISSUE TITLE
[tracking] JetBrains will respect __all__ for import suggestions

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2159]
https://youtrack.jetbrains.com/issue/PY-25484

@kxepal

**Comment by samuelcolvin** [comment]
Good luck, in my experience jetbrains virtually never respond to such issues or fix them based on user requests.

**Comment by kxepal** [comment]
@asvetlov Thanks!

But I still think that for this case Python needs some strict protocol which defines what exactly you can import. `__all__` fails this case. Fixing hints wouldn't stop users do bad imports.

**Comment by asvetlov** [comment]
@samuelcolvin 
Pretty sure the issue will be fixed.
I know many JetBrains dev team members personally.
The issue was raised by their team lead after private conversation.
If not -- I'll ping him on next Python Conference somewhere :)

**Comment by asvetlov** [comment]
@kxepal I dont't follow.
What problem are you raising?
People can do wild imports (not `from mod import *` but import private name marked by underscore) but if IDEs will suggest proper import names -- who cares?

**Comment by kxepal** [comment]
@asvetlov 
Well, with wildcard import you hit another problem: linters don't like them as like as people and both has good reasons againt this. 

The problem I raise is the same as yours: forbid imports of private things (: But at import system level, not at IDE hints one. For example, in Erlang there are no imports, but only exports: each module defines what others can reference and that's public API while everything rest is private. For Python we have `__all__` which filters what wildcard could import, but why not to filter direct imports as well? And yes, I know, that's a dream that won't get real in Python, but I think it's a good one (:

**Comment by asvetlov** [comment]
According to https://youtrack.jetbrains.com/issue/PY-25484 status the issue is implemented.
Let's close it
