### ISSUE TITLE
DOC: ClientResponse.release is not a coroutine

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#2164]
http://aiohttp.readthedocs.io/en/stable/client_reference.html#aiohttp.ClientResponse.release

ClientResponse.release is not a coroutine actually.
TODO: grep other functions as well + document that in previous versions this was a coroutine. So nowadays it returns a stub.

**Comment by fafhrd91** [comment]
backward compatibility. stub should be removed in 3.0

**Comment by asvetlov** [comment]
Sorry for offtopic.
@socketpair did you receive my email? I've sent it to `socketpair@gmail.com`, the address from your github account.

**Comment by socketpair** [comment]
@asvetlov email is correct, but I did not receive any email from you directly. Which subject? Also, you can reach my be telegram @socketpair too. and also google talk works.

**Comment by socketpair** [comment]
@fafhrd91 documentation should be fixed now since new user will write `await xxx.close()` which is wrong.

**Comment by fafhrd91** [comment]
yes, doc should be fixed.

**Comment by dz0** [comment]
seems, it is still not fixed :/ 
why?
