### ISSUE TITLE
Nominate Коренберг Марк aka @socketpair to aiohttp member team

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2166]
We have discussed with @socketpair our rules:
* no wild commits
* everything should go via PRs and be merged only after approvement
* getting commit rights means mostly not rights but responsibilities for reviewing existing PRs and making PRs for new issues.  

Hi understand the rules and hi is very active in python community.

Please vote.
As usual silence means +1 but explicit -1 is a subject for discussion,

**Comment by fafhrd91** [comment]
+1

**Comment by asvetlov** [comment]
+1 from @fafhrd91 has very high weight, thank you.

**Comment by asvetlov** [comment]
Done.
Welcome to team, @socketpair

**Comment by socketpair** [comment]
:) !

**Comment by kxepal** [comment]
+1 
Congrats, @socketpair !
