### ISSUE TITLE
server often throw "concurrent.futures._base.CancelledError"

### ISSUE THREAD

**Issue by larryclean** [aio-libs/aiohttp#2168]
## Long story short

i use aioredis to update data often throw "concurrent.futures._base.CancelledError"  at aiohttp socket.io.
so my data can't update.

## Expected behaviour

i expect can update redis data

## Actual behaviour

```
    @sio.on('disconnect')
    async def disconnect(sid):
        """
        链接断开连接
        :param sid:
        :return:
        """
        await factory.leave_room(sid)
        rooms = sio.rooms(sid)
        for room in rooms:
            sio.leave_room(sid, room)
        await sio.eio.disconnect(sid)
```

## Steps to reproduce

There is no recurrence method,but our production environment has this error

## Your environment

centos 
aiohttp 2.2.3
aioredis 0.3.3
python-socketio 1.8.0

**Comment by asvetlov** [comment]
See #2098 for behavior explanation

**Comment by bluemix** [comment]
I was having two consecutive requests to the server, and I was having 
```
...
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
concurrent.futures._base.CancelledError
```

so, I just placed `await asyncio.sleep(0.1)` between the requests and the above error is gone and everything worked correctly.
