### ISSUE TITLE
500 errors don't go through middlewares

### ISSUE THREAD

**Issue by Natim** [aio-libs/aiohttp#2175]
## Long story short

I'd like to make sure all exceptions are catched and returned as a 503 HTTP JSON response.

I created the [middleware](http://aiohttp.readthedocs.io/en/stable/tutorial.html#aiohttp-tutorial-middlewares) with the following `handle_500`:

```
async def handle_500(request, response):
    logger.error(response.body)
    if response.headers['Content-Type'] != "application/json":
        return web.json_response({
            "status": 503,
            "message": "Service currently unavailable."
        }, status=503)
```

Then I have created the following test:

```
@pytest.fixture
def cli(loop, test_client):
    return loop.run_until_complete(test_client(get_app(loop=loop)))

async def test_500_pages_are_json_responses(cli):
    with mock.patch("aiohttp.web.json_response", side_effect=ValueError):
        resp = await cli.get("/v1/views.json")
        assert resp.status == 503
        assert await resp.json() == {
            "status": 503,
            "message": "Service unavailable"
        }
```

## Expected behaviour

A 503 response with the JSON body

## Actual behaviour

A 500 response without the JSON response

 ```<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>```

**Comment by Natim** [comment]
Actually it goes through the middleware, it is just that the error page middleware in the documentation only catches web.HTTPException ones:

```
def error_pages(overrides):
    async def middleware(app, handler):
        async def middleware_handler(request):
            try:
                response = await handler(request)
                override = overrides.get(response.status)
                if override is None:
                    return response
                else:
                    return await override(request, response)
            except web.HTTPException as ex:
                override = overrides.get(ex.status)
                if override is None:
                    raise
                else:
                    return await override(request, ex)

            except Exception as ex:
                override = overrides.get(500)
                if override is None:
                    raise
                else:
                    return await override(request, ex)

        return middleware_handler
    return middleware
```

**Comment by fafhrd91** [comment]
Would you create PR?

**Comment by fafhrd91** [comment]
I think middleware should handle response uniformally.
@asvetlov was it explicit decision for errors?

**Comment by Natim** [comment]
> Would you create PR?

Of course I would :)

**Comment by asvetlov** [comment]
Middleware should either return response or raise an error.
Returning `aiohttp.web` exception is allowed but discouraged.
`error_pages` middleware used to render custom pages for things like 404 or 500, we could modify example to show recommended way.
But usually this middleware is first in chain, so behavior is correct.

**Comment by fafhrd91** [comment]
middleware returns 503, aiohttp server returns 500.
this looks like a bug

**Comment by Natim** [comment]
Ok makes sense.

**Comment by asvetlov** [comment]
@fafhrd91 sorry, I'm lost.
What middleware and what test are you talking about?
Could you point on local test which I can run to reproduce the problem?

**Comment by fafhrd91** [comment]
I see, @Natim your test case is wrong. test case raises exception in middleware itself.

@asvetlov sorry, false alarm

**Comment by asvetlov** [comment]
no problem
