### ISSUE TITLE
[Client] Boolean value in headers raises error

### ISSUE THREAD

**Issue by panagiks** [aio-libs/aiohttp#2190]
## Long story short

When passing a boolean as a value in headers an exception is raised.

For example this command:

```py
with aiohttp.ClientSession() as session:
        res = yield from session.get('https://google.com', headers={'MyHeader': True})
```

raises the following exception:

```py
File "/.virtualenvs/aiohttp_headers/lib/python3.5/site-packages/aiohttp/http_writer.py", line 250, in <listcomp>
    [k + SEP + v + END for k, v in headers.items()])
TypeError: Can't convert 'bool' object to str implicitly
```

## Expected behaviour

The 'pythonic' expectation would be to pass dictionaries with boolean values instead of having to pass as string.

## Actual behaviour

Currently the dict passed to headers has to be:

```py
{'MyHeader': 'true'}
```

## Steps to reproduce

Run the following script:

```py
#!/usr/bin/env python3
import asyncio
import aiohttp


@asyncio.coroutine
def main():
    with aiohttp.ClientSession() as session:
        res = yield from session.get('https://google.com', headers={'MyHeader': True})


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())

```

## Your environment

Ubuntu 16.04/17.04 
aiohttp 2.2.5

**Comment by panagiks** [comment]
Also my initial thought of casting `v` to string by replacing:

```py
[k + SEP + v + END for k, v in headers.items()])
```

with:

```py
[k + SEP + str(v) + END for k, v in headers.items()])
```

would probably not work since the expected value would be `true` and not `True` which is the result of:

```py
str(True)
```

I will have access to a service that expects/handles boolean values in headers in Wednesday so I can test whether `True` is accepted.

**Comment by asvetlov** [comment]
Don't speculate too much with *pythonic* word please.
The behavior is intentional.
Python `True` could be converted into `True`, `true`, `yes`, `on`, `1` etc. -- it depends on peer expectations/implementation details.
aiohttp/yarl doesn't try to guess what string is expected but enforces user to convert it explicitly.

**Comment by panagiks** [comment]
Ah, ok I see.
Thank you for the quick reply and sorry for the assumption :)
