### ISSUE TITLE
Aiohttp client must forbid to send HEAD and TRACE requests with request-body present.

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#2192]

**Comment by asvetlov** [comment]
It is very subtle subject.
Correct client should never send BODY with HEAD/TRACE.
It should not use BODY with GET too but I know exceptions, e.g. ElasticSearch server API.
Sending BODY with HEAD is a kind of shooting into the leg: nobody want it usually but we are all adults.

Let's close the issue as wontfix
