### ISSUE TITLE
background Client websockets hangs on SIGINT

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#2200]
```python
import asyncio
import aiohttp
from aiohttp import web

async def job():
    async with aiohttp.ClientSession() as session:
        async with session.ws_connect('http://localhost:8080/ws') as ws:
            await ws.receive_json()

async def ws_handler(req):
    ws = web.WebSocketResponse()
    ws.prepare(req)
    await asyncio.sleep(1000)
    ws.close()
    return ws

app = web.Application()
app.router.add_get('/ws', ws_handler)
task = asyncio.ensure_future(job())
web.run_app(app)
```

**Comment by socketpair** [comment]
This application will hang not reacting to SIGINT. Removing client part makes application react as axpected.

**Comment by asvetlov** [comment]
It doesn't hang technically but `run_app` is waiting for 60 secs in `handler.shutdown()`.
Agree, looks confusing.

**Comment by socketpair** [comment]
If I understand right, websocket connection are always awaited for 60 (by default, timeout is got from run_app). Typically websocket connections are long-standing. And so shutdowning any webserver with connected websocket will hang for 60 seconds.

We need to define a new way to configure behavior of websocket handlers when their `.shutdown()` is called.

**Comment by alexmnazarenko** [comment]
Some kind of 'hard' shutdown would be nice. I used quite some workarounds and custom signal handler to make CTRL+C immediate. I did this just for my own sanity during development, it's unlikely to happen too often in the production :smiley:

**Comment by fafhrd91** [comment]
60 sec is graceful shutdown timeout. we can handle CTRL+C as non graceful, and SIGTERM as graceful.
or we need to introduce shutdown process for handlers, then we'd be able to `.close()` web socket loop.

**Comment by EliRibble** [comment]
Agreed, this is also problematic for server-sent events (https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events).

Is anyone actively working on a solution to this? I'd be willing to submit some ideas. It seems like we would just need something like an asyncio.Event that is exposed on the app itself that is set as soon as the app detects a request for a graceful shutdown. Then developers could use something like asyncio.wait(..., return_when=asyncio.FIRST_COMPLETED) to shut down the request handler.

**Comment by asvetlov** [comment]
Sorry, I cannot understand your proposal.
A code sketch would be useful

**Comment by EliRibble** [comment]
Sure. Currently if you are doing something like server-sent events you need an `on_startup` and `on_cleanup` handler and you have to keep track of the streams that are currently open. You could instead have something like this:

```python
async def sse_handler(request):
  stream = await ss_response(request)
  # The queue here is just a means for other coroutines to dump
  # information into this connection to be sent to the client
  queue = asyncio.Queue()
  request.app["queues"].append(queue)
  while not request.app.is_exiting.is_set():
    queue_task = asyncio.Task(queue.get())
    done, pending = await asyncio.wait([
      queue_task,
      request.app.is_exiting.wait(),
    ], return_when=asyncio.FIRST_COMPLETED)
    if queue_task not in done:
      continue
    # send data from the queue to the client
    await stream.send(queue_task.result())
```

In this case `app.is_exiting` would be the asyncio.Event that is exposed on the app. As soon as the app detects a request for a graceful shutdown it would `await app.is_exiting.set()`. This would signal to all of the long-running `sse_handler` connections to perform an immediate and graceful shutdown.

**Comment by asvetlov** [comment]
Looks like you can do it with the current aiohttp:
```
async def on_startup(app):
    app['is_running'] = asyncio.Event()

async def on_shutdown(app):
    app['is_running'].set()

async def check_is_running(request):
    return request.app['is_running'].is_set()
```

**Comment by EliRibble** [comment]
Thanks, that worked, you're right. I had thought that the ordering of the shutdown hook would cause the system to wait for the handlers to exit before calling the callback where we could set the event. I may have gotten confused between `on_shutdown` and `on_cleanup`, however.

For anyone interested, here is my full working example:

```python
#!/usr/bin/env python3
import asyncio
import json
import logging 
import weakref
from contextlib import suppress
from datetime import datetime
from functools import partial

from aiohttp import web

from aiohttp_sse import EventSourceResponse, sse_response


async def worker(app):
  while True:
    now = datetime.now()

    data = json.dumps({'time': 'Server Time : {}'.format(now)})
    for queue in app['queues']:
      await queue.put(data)

    logging.debug("Sent %s", now)
    await asyncio.ensure_future(asyncio.sleep(1, loop=app.loop))


async def on_startup(app):
  app['worker'] = app.loop.create_task(worker(app))


async def clean_up(app):
  logging.debug("Cleaning up app")
  app['worker'].cancel()
  with suppress(asyncio.CancelledError):
    await app['worker']


async def on_shutdown(app):
  logging.debug("Shutting down")
  app["is_exiting"].set()


async def sse_handler(request):
  stream = await sse_response(request)
  # The queue here is just a means for other coroutines to dump
  # information into this connection to be sent to the client
  queue = asyncio.Queue()
  request.app["queues"].append(queue)
  exit_task = asyncio.Task(request.app["is_exiting"].wait())
  queue_task = asyncio.Task(queue.get())
  while not request.app["is_exiting"].is_set():
    done, pending = await asyncio.wait([
      queue_task,
      exit_task,
    ], return_when=asyncio.FIRST_COMPLETED)
    if exit_task in done:
      continue
    if queue_task in done:
      # send data from the queue to the client
      await stream.send(queue_task.result())
      queue_task = asyncio.Task(queue.get())
  logging.debug("Returning stream")
  queue_task.cancel()
  with suppress(asyncio.CancelledError):
    await queue_task
  stream.stop_streaming()
  await stream.wait()
  return stream
    
async def index(request):
  d = """
      <html>
      <head>
          <script type="text/javascript"
              src="http://code.jquery.com/jquery.min.js"></script>
          <script type="text/javascript">
          var evtSource = new EventSource("/hello");
          evtSource.onmessage = function(e) {
            $('#response').html(e.data);
          }
          </script>
      </head>
      <body>
          <h1>Response from server:</h1>
          <pre id="response"></pre>
      </body>
  </html>
  """ 
  return web.Response(text=d, content_type='text/html')
    
      
if __name__ == '__main__':
  logging.basicConfig(level=logging.DEBUG)
  app = web.Application()
      
  app.on_startup.append(on_startup)
  app.on_shutdown.append(on_shutdown)
  app.on_cleanup.append(clean_up)
  app["is_exiting"] = asyncio.Event()
  app["queues"] = []
  app['worker'] = None
  
  app.router.add_route('GET', '/hello', sse_handler)
  app.router.add_route('GET', '/index', index)
  web.run_app(app, host='127.0.0.1', port=8082)
```

**Comment by dzhalaevd** [comment]
Hello, @EliRibble, @socketpair, after reviewing the issue, I think that you have identified the appropriate solution. Given the lack of activity over the past  five years, I suggest we close this issue for now. If needed, we can reopen it at a later time.
