### ISSUE TITLE
ClientResponse.connection becomes None too early

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2205]
Now `ClientResponse._response_eof()` cleans up `self._connection` on getting end of response's BODY.
For relative small bodies the method is called before even very first `resp.read()`.

It works pretty well from content delivery perspective but raises another problem: there is no reliable way to get underlying socket options, in particular we need `transport.get_extra_info('peercert')`.

In theory aiohttp could collect all data before connection releasing but there is no public asyncio API for providing all available transport's keys.
Moreover I could imagine situation where direct call is needed like `tr.get_extra_info('socket').getsockopt(...)`.

I have no good proposal, keeping `resp.connection` until at least first `resp.read()` breaks pipelining if I understand correctly.
But I pretty sure the problem should be fixed.

@fafhrd91 please share your opinion.

**Comment by asvetlov** [comment]
@hellysmile ^^^

**Comment by fafhrd91** [comment]
I think current implementation works very well, I don't think we should change it.

I see several options:
* use api @asvetlov proposed #2019 
* introduce callback for "connection is available"
* custom Response class

**Comment by asvetlov** [comment]
First option is the best maybe. I should find time work working on it.

**Comment by asvetlov** [comment]
Should be fixed by implementing #2019 proposal
