### ISSUE TITLE
Hello world built with Cython doesn't work

### ISSUE THREAD

**Issue by theRobinator** [aio-libs/aiohttp#2210]
## Long story short

The server example on http://aiohttp.readthedocs.io/en/stable/ doesn't work when compiled using Cython.

## Expected behaviour

Compiling with Cython should not affect the server's ability to respond to requests.

## Actual behaviour

Apps compiled with Cython crash with a TypeError.

## Steps to reproduce

First, copy the hello world example from the docs:
```
from aiohttp import web

async def handle(request):
    name = request.match_info.get('name', "Anonymous")
    text = "Hello, " + name
    return web.Response(text=text)

app = web.Application()
app.router.add_get('/', handle)
app.router.add_get('/{name}', handle)

web.run_app(app)
```

Next, compile the script using Cython, using [Cython hello world](http://docs.cython.org/en/latest/src/tutorial/cython_tutorial.html#cython-hello-world)
```
from distutils.core import setup
from Cython.Build import cythonize

setup(
    ext_modules = cythonize("helloworld.py")
)
```

Now, run the app and request a page:
```
Robin$ python -c 'import helloworld' &
======== Running on http://0.0.0.0 ========
Robin$ curl http://localhost:8080
Error handling request
Traceback (most recent call last):
  File "/Users/robink/dev/workspace/python/env/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/Users/robink/dev/workspace/python/env/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/Users/robink/dev/workspace/python/env/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 115, in handler_wrapper
    result = yield from result
TypeError: 'coroutine' object is not iterable
/Users/robink/dev/workspace/python/env/lib/python3.6/site-packages/aiohttp/web_protocol.py:432: RuntimeWarning: coroutine 'handle' was never awaited
  resp = self.handle_error(request, 500, exc)
<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>
```

## Your environment

I'm running OSX 10.11.6, python version 3.6.2

```
Robin$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
```

```
Robin$ pip freeze
aiohttp==2.2.5
chardet==3.0.4
Cython==0.26
multidict==3.1.3
yarl==0.12.0
```

**Comment by fafhrd91** [comment]
I am not sure it is aiohttp bug. And what is the point cythonize python code?

**Comment by theRobinator** [comment]
I will check to see if I can reproduce this using Cython only, and report back. If so I'll open an issue with them and link it here.

I think one of the main use cases for cython+aiohttp is if you want to have a server that has both high network I/O and does heavy internal processing. The Cython wiki reports [a performance gain of 20-50%](http://docs.cython.org/en/latest/src/tutorial/pure.html) for pure Python when cythonized.

**Comment by samuelcolvin** [comment]
> and does heavy internal processing

If you have heavy processing to do you can definitely move that into a separate cython module, compile that, import it in your vanilla python aiohttp app and call your cythonized super fast function inside a view.

There's no reason to cythonize your entire app if there's only a few functions which will benefit from cython.

My experience of cythonizing pure python is no perceptible performance improvement.

**Comment by asvetlov** [comment]
@theRobinator the issue has very low priority from my perspective but if you provide error traceback I can take a look.
Otherwise I tend to close the issue until get more detailed info or Pull Request.
