### ISSUE TITLE
Iterating lines longer than DEFAULT_LIMIT

### ISSUE THREAD

**Issue by r-darwish** [aio-libs/aiohttp#2216]
## Long story short

I'd like to iterate the lines of a text file which contains lines a bit bigger than DEFAULT_LIMIT. I could use `iter_chunked`, but then I'll have to make sure that I handle lines which are sliced in the middle of a chunk, so I want to take advantage of `aiohttp`'s line iterator.

However, the only way that I found to achieve this is to alter a private member in the following way:
```
response.content._limit = 100_000
```

## Expected behaviour
I'm not sure. Maybe add some public method for setting the limit.

## Actual behaviour
I have to alter a private variable

## Your environment

```
async with aiohttp.ClientSession() as session:
    async with session.get("http://url_for_file_with_long_lines") as response:
            response.raise_for_status()
            async for line in response.content:
                pass
```

**Comment by asvetlov** [comment]
`async for line in resp.content` calls https://github.com/aio-libs/aiohttp/blob/master/aiohttp/streams.py#L47
In turn it's a wrapper around `StreamReader.readline()` https://github.com/aio-libs/aiohttp/blob/master/aiohttp/streams.py#L242
Maybe we could override `limit` for every call but I definitely don't feel a motivation for implementing the change myself.
If you want it -- PR is welcome.

**Comment by r-darwish** [comment]
I think it would be simpler to implement a new method called `set_line_limit` for `AsyncStreamReaderMixin`. What do you think?

**Comment by kxepal** [comment]
I don't think we should encourage this via public API as it will cause cascade changes in all the line: middle mans proxies, clients, etc. It's very easy to make you client/server incompatible with the rest of the world.

What's the case you have that doesn't fits with default limit?

**Comment by r-darwish** [comment]
Some company internal tool. To be honest, I found a workaround using `iter_chunked` so we can close this ticket as far as I'm concerned.

**Comment by kxepal** [comment]
I would suggest fix that internal tool instead. Support of such causes nothing, but pain. Once we had one of that kind. Then we fixed it. Now we're happy (:

**Comment by asvetlov** [comment]
Let's close the issue.
The solution is very contraversional
