### ISSUE TITLE
Using aiohttp.web.run_app in a loop that does also other stuff with the loop

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [aio-libs/aiohttp#2219]
## Long story short

The code of web.run_app does not take into account that the loop could be shared with other tasks or funcitonalities.

## Expected behaviour

In particular, all the run_until_complete, run_forever and so one should be paired with create_task/wait when the loop is already running and the web interface is not the only owner and manager of the loop.

**Comment by asvetlov** [comment]
Duplicate for #2121
