### ISSUE TITLE
aiohttp.TCPConnector()

### ISSUE THREAD

**Issue by gjthompson1** [aio-libs/aiohttp#2224]
## Long story short

The aiohttp.TCPConnector() class no longer has a conn_timeout keyword

[https://github.com/buckket/twtxt/issues/126](https://github.com/buckket/twtxt/issues/126)

Related to this:

[https://stackoverflow.com/questions/45800857/aiohttp-error-rate-increases-with-number-of-connections](https://stackoverflow.com/questions/45800857/aiohttp-error-rate-increases-with-number-of-connections)

**Comment by fafhrd91** [comment]
https://github.com/aio-libs/aiohttp/blob/master/docs/migration_to_2xx.rst#client-connector
