### ISSUE TITLE
web.Response converts headers to uppercase

### ISSUE THREAD

**Issue by isaacl** [aio-libs/aiohttp#223]
HTTP headers are technically case insensitive but it might be nice to preserve input case for readability.

**Comment by kxepal** [comment]
Good point. I would say more: send headers titled instead of uppercased like they are defined in spec (Content-Type etc.). Turning them all into upper case looks as an ugly hack to simplify key lookup and further comparison.

**Comment by asvetlov** [comment]
Hmm. Nice to have, but requires deep multidict refactoring.
Please don't start to do it right now: I'm working on accelerated version of multidicts (optional, of course): https://github.com/KeepSafe/aiohttp/blob/cytonize_multidicts/aiohttp/_multidict.pyx

**Comment by kxepal** [comment]
@asvetlov looks cool, but does multidict is really needs in such optimization? I always thought that routing is far much more good candidate for that...anyway, look forward for your work on this!

**Comment by asvetlov** [comment]
I did profiling. 
Router is called once per request, regexps are fast.
But on every requests we have many reads and writes for headers (low-level server also operates with multidicts, BTW).

**Comment by isaacl** [comment]
As @kxepal suggested, we could default to title case instead of upper case.  That would avoid changing the actual storage structures, and can be done when formatting the response.

**Comment by asvetlov** [comment]
@isaacl it **requires** data structure changing.

**Comment by fafhrd91** [comment]
-1 for camel case. I like capitalized header
