### ISSUE TITLE
Unable to update to 2.2.5 with pip

### ISSUE THREAD

**Issue by gdselzer** [aio-libs/aiohttp#2233]
## Long story short

Using pip to upgrade from 2.2.3 to 2.2.5 fails due to a UnicodeDecodeError.  Seems to be similar [aio-libs/aiohttp/#1885](https://github.com/aio-libs/aiohttp/issues/1885), except that issue is with windows and I'm on a RPi3

## Expected behaviour

Clean upgrade to 2.2.5.

## Actual behaviour

Fails with:

```
$pip3 install --no-cache-dir --upgrade aiohttp
Collecting aiohttp
  Downloading aiohttp-2.2.5.tar.gz (788kB)
    100% |████████████████████████████████| 798kB 882kB/s
Requirement already up-to-date: chardet in /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages (from aiohttp)
Requirement already up-to-date: multidict>=2.1.4 in /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages (from aiohttp)
Requirement already up-to-date: async_timeout>=1.2.0 in /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages (from aiohttp)
Requirement already up-to-date: yarl>=0.11 in /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages (from aiohttp)
Installing collected packages: aiohttp
  Found existing installation: aiohttp 2.2.3
    Uninstalling aiohttp-2.2.3:
      Successfully uninstalled aiohttp-2.2.3
  Running setup.py install for aiohttp ... error
  Rolling back uninstall of aiohttp
Exception:
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/compat/__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 33: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/utils/__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/compat/__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 33: invalid start byte
```

## Steps to reproduce

Tried pip and pip3.  Also tried with and without using cached download.

## Your environment

This is on a Raspberry Pi 3, Raspbian Jessie.
Python 3.4.2 and GCC 4.9.1 running in venv.
LANG=en_US.UTF-8

**Comment by asvetlov** [comment]
Very mystic error.
We do run tests on windows machine by http://appveyor.com/
Tests don't fail.

Would you dig into deeper?
Simple script which iterates over all files in repo clone by trying read every file using UTF8 could point on problem.

**Comment by samuelcolvin** [comment]
This looks like an error with pip itself. 

What version of pip are you using `pip -V`, have you tried upgrading pip `pip install -U pip`?

**Comment by gdselzer** [comment]
Doesn't seem to be related to an older version of pip.  Version is 9.0.1 and pip install -U pip returns: Requirement already up-to-date

asvetlov, I am very new to python and do not understand how to implement your script suggestion.  Can you point me toward a similar script that does the same thing?

**Comment by socketpair** [comment]
It seems, you locale is not set up correctly. Please show us output of `locale` command.

**Comment by AraHaan** [comment]
The issue is pip, if I remember right pip did release an fix for this? try doing an ``pip install --upgrade pip`` or ``pip3.6 install --upgrade pip`` And yes, I recommend trying python 3.6.2 or so as I hear from somewhere that python 3.4.x has an ``yield from`` bug. Although not entirely sure on that either. 🤔

**Comment by gdselzer** [comment]
$ locale
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by AraHaan** [comment]
Maybe you can try to git clone the current pip commits and manually install it?

**Comment by gdselzer** [comment]
I think I had a corrupted file somewhere.  I did a clean install and now it seems to work.  I'll report back if the issue comes up again.  Thanks all for the help.
