### ISSUE TITLE
Welcome Samuel Colvin

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2234]
Hi is aiohttp committer since end of winter but we didn't officially pronounce it.
Shame on me, I've sent invitation to @samuelcolvin yesterday but only after his polite answer figured out that he is committer already.

By this message I'm apologizing for my confuse, I very respect Samuel's contribution.

@samuelcolvin please close the issue in about 3 days, I believe the period is enough for everybody to read and remember this text.

Sorry again, my memory is not such strong as I would like.

**Comment by samuelcolvin** [comment]
Thanks @asvetlov, looking forward to working with you guys lots more.

**Comment by kxepal** [comment]
Welcome, @samuelcolvin ! 🎉

**Comment by jettify** [comment]
Welcome!

**Comment by fafhrd91** [comment]
welcome!

**Comment by socketpair** [comment]
Welcome!

**Comment by AraHaan** [comment]
Welcome, and sorry about neglecting aiohttp recently as well, I been working on some other things. Not to mention I am thinking of something absolutely cool as well unrelated to aiohttp.

**Comment by asvetlov** [comment]
@AraHaan no problem, it is open source: do what you want.
