### ISSUE TITLE
Strange behaviour when passing params

### ISSUE THREAD

**Issue by Rapptz** [aio-libs/aiohttp#2235]
## Long story short

Doing something like this:

```py
async with session.get('https://httpbin.org/get', params={'test': 'foo;bar'}) as resp:
    print(await resp.json()['url'])
```

will print a strange URL.

## Expected behaviour

The URL should be `https://httpbin.org/get?test=foo%3Bbar`

## Actual behaviour

The URL is `https://httpbin.org/get?test=foo&bar=`

`requests` does what I expect:

```py
>>> import requests
>>> requests.get('https://httpbin.org/get', params={'test': 'foo;bar'})
<Response [200]>
>>> _.json()['url']
'https://httpbin.org/get?test=foo%3Bbar'
```

So I figure the current behaviour must be a bug.

## Steps to reproduce

See above.

## Your environment

- OS: Ubuntu 16.04
- Python version: 3.6.1
- aiohttp version: 2.2.5
- yarl version: 0.12.0

**Comment by Rapptz** [comment]
Upon further diving, I looked into the `yarl` implementation and found nothing too odd there.

`URL.query_string` did end up returning what I expected so there were no issues there.

However, when it came to `URL.query` to turn it into a `MultiDict` that's when things went awry. It turns out that the stdlib function, `parse_qsl` does not handle this case very well:

```py
>>> from urllib.parse import parse_qsl
>>> parse_qsl('test=foo;bar')
[('test', 'foo')]
```

Which is due to CGI purposes: https://github.com/python/cpython/commit/afde7e24b6c7cd75e1797a02fa6c3674f6419531

And this is what `yarl` uses to help construct.

**Comment by Rapptz** [comment]
There seems to be no way to bypass this behaviour using `params`:

```py
from urllib.parse import quote as _uriquote
params = {
    'test': _uriquote('foo;bar')
}

async with session.get('https://httpbin.org/get', params=params) as resp:
   print(await resp.json())['url']
```

This will print `https://httpbin.org/get?test=foo&bar=`

To get the proper behaviour you have to format the URL yourself.

**Comment by pfreixes** [comment]
There is an open discussion about that, more info following links

https://github.com/aio-libs/yarl/issues/91
https://github.com/aio-libs/yarl/pull/104

You can address this issue by your self just building your own URL and not using the params kw, for example

```python
from urllib.parse import urlencode, urlsplit, urlunsplit, SplitResult

def merge_params(url, params):
    """ Return a new URL composed by the `url` plus the
    params.
    """
    u = urlsplit(url)

    if u.query:
        qs = "{}&{}".format(u.query, urlencode(params))
    else:
        qs = urlencode(params)

    new = SplitResult(
        scheme=u.scheme,
        netloc=u.netloc,
        path=u.path,
        query=qs,
        fragment=u.fragment
    )

    return urlunsplit(new)
``` 

This is just a workaround. Not sure if there are other recipes or there is another way to skip that problem.

**Comment by asvetlov** [comment]
Fixed by yarl

**Comment by Rapptz** [comment]
Thanks for the quick fix!
