### ISSUE TITLE
response.json() in testing with pytest using uvloop

### ISSUE THREAD

**Issue by dennypenta** [aio-libs/aiohttp#2239]
## Long story short

while using py test with `test_client`and calling response.json() I got `aiohttp.client_exceptions.ClientResponseError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'`
So I tried set headers, content_type and so on, but with test() and json.loads() I didn't got error.

## Expected behaviour

Set mimetype: text/json;

## Steps to reproduce

```
from app import make_app


async def test_hello(test_client, loop):
    app = make_app()
    client = await test_client(app)
    # resp = await client.get('/', headers={'content-type': 'application/json'})
    # data = await resp.json(content_type='application/json')
    resp = await client.get('/')

    data = await resp.json()
    assert resp.status == 200
    assert data is not None
    assert type(data) is list
```

## Your environment

OS X 10.12.5, python 3.6.2, aiohttp 2.2.5, uvloop 0.8.0

**Comment by asvetlov** [comment]
You should set proper content type on server side (or just use `json_response()`: http://aiohttp.readthedocs.io/en/stable/web_reference.html#json-response)

**Comment by dennypenta** [comment]
Yes, my handler looks like:
`return web.json_response(data, dumps=dumps, status=status)`,

**Comment by dennypenta** [comment]
Reason is that if uvloop has been installed, then it will be used for pytest by default

**Comment by asvetlov** [comment]
I don't follow how uvloop is related to json response.
