### ISSUE TITLE
Need some help to optimize aiohttp.web for TechEmpower Web Framework Benchmarks

### ISSUE THREAD

**Issue by ludovic-gasc** [aio-libs/aiohttp#224]
Hi,

I don't know if you follow asyncio ML, but finally, the latest version of [API-Hour](http://www.api-hour.io) isn't a fork of aiorest anymore.
Now, we removed our aiorest fork to use directly aiohttp.web as JSON/REST framework + [a very small helper](https://github.com/Eyepea/API-Hour/blob/master/api_hour/plugins/aiohttp/__init__.py#L4) to return easily [JSON responses](https://github.com/Eyepea/API-Hour/blob/master/examples/http_and_ssh/http_and_ssh/endpoints/http.py#L21)

API-Hour is now a glue between Gunicorn and aiohttp.web to have directly Gunicorn features (multiprocessing, graceful reload, autoreload...) with aiohttp.web.

To validate objectively performances we have with this architecture, I've implemented the test suite of TechEmpower Web Framework Benchmarks for  [aiohttp.web+API-Hour](https://github.com/Eyepea/FrameworkBenchmarks/blob/API-Hour/frameworks/Python/API-Hour/hello/hello/__init__.py#L21)

In [benchmark_config JSON file](https://github.com/Eyepea/FrameworkBenchmarks/blob/API-Hour/frameworks/Python/API-Hour/benchmark_config), I've registered **aiohttp.web** as framework and **API-Hour** as plateform.

We are now in the same team "against" **93** frameworks ;-)
Can we be faster than all Python frameworks ? Can we be faster than some other frameworks in other languages ? I don't have the answer, but after my first tests, it's certainly true for Flask and Django.

The biggest part of this daemon is **aiohttp.web**.
If you have some ideas to boost performances, I'm very interested in.

I already use ujson for JSON encoding. I see you publish today a benchmark suite with cProfile embedded and a boosted reimplementation of multidict. I could use that in test suite when it will be ready.

A reimplementation of HTTP parser could help or not ? A stuff something like that: https://github.com/benoitc/http-parser ?

Thanks a lot for your help.

**Comment by asvetlov** [comment]
Just now I have no new ideas for performance.

You can write load test and profile it -- I don't know another way.

-1 for reimplementing HTTP parser, at least for now.
I have no evidence the parser is bottleneck.

**Comment by ludovic-gasc** [comment]
Ok, I will cherry-pick your idea to call cProfiler directly to push that in the API-Hour worker, I will see if I found something.
Ok for HTTP parser.

**Comment by fafhrd91** [comment]
Just a note, aiohttp has aiohttp.web gunicorn worker already

**Comment by ludovic-gasc** [comment]
@fafhrd91: thank you, but I already know, I've forked your worker for API-Hour: https://github.com/Eyepea/API-Hour/blob/master/api_hour/worker.py
BTW, thank you both for that, it helps me a lot to migrate API-Hour arbiter to Gunicorn.

I don't use your worker directly because I've made some customizations to launch any AsyncIO lib server.

**Comment by asvetlov** [comment]
Ok, let me close the issue.

**Comment by ludovic-gasc** [comment]
Ok, thank you.

Don't hesitate to contact me if you have some ideas in the future.

**Comment by ludovic-gasc** [comment]
Hello guys,

FYI, `aiohttp.web` is ready to be benchmarked by the TechEmpower Web Framework Benchmarks 11 round, all tests are green: https://travis-ci.org/Eyepea/FrameworkBenchmarks/jobs/46924973#L8343

Have a nice day.
