### ISSUE TITLE
Process urls like https://user:pass@example.com

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2243]
Extract user info from URL and construct proper auth header.

**Comment by sashgorokhov** [comment]
If you dont mind, I am going to implement this and provide a pull request

**Comment by asvetlov** [comment]
Please do

**Comment by sashgorokhov** [comment]
Seems like this is already implemented. 
There is a function `aiohttp.client_reqrep.ClientRequest.update_host` which creates a `aiohttp.helpers.BasicAuth` with username and password specified in url. Works on both http and https schemes.

**Comment by asvetlov** [comment]
Yep, I see.
Anyway, it would be nice to move the functionality into `ClientSession._request`.
Consider it as preparation for #2019

**Comment by sashgorokhov** [comment]
Ok, I'll see what i can do
