### ISSUE TITLE
[Question] Possible to pass arguments to underlying function, json.loads()?

### ISSUE THREAD

**Issue by jgayfer** [aio-libs/aiohttp#2247]
The underlying function, `json.loads()`, accepts a parameter called `parse_int`. This allows for different types of casting to be done, rather than just `str(int)`. I would like to use this argument with aiohttp's `json()` function, but I'm unsure how it would be done, since it looks like I can only pass in the function to do the encoding (default is `json.loads()`) and not the arguments that get passed to it.

Is there a way to accomplish this?

**Comment by asvetlov** [comment]
I assume you are talking about client API (while server uses the same approach).
http://aiohttp.readthedocs.io/en/stable/client_reference.html#aiohttp.ClientResponse.json accepts `loads` optional parameter.

You could do call like `await resp.json(loads=partial(json.loads, parse_int=int_parser))`.

The only disadvantage is passing `loads` parameter everytime for getting json data.
It could be solved by adding `loads` param to `ClientSession` for setting up new default behavior, I'm open for Pull Request. 

We have `json_serialize` option already (while now I think the name is inconsistent with others, `dumps` would be better).
On other hand amount of options on `ClientSession` blows up but I can live with it.

**Comment by jgayfer** [comment]
Thank you. I wasn't aware of how `partial` works, but it's just what I was trying to accomplish! I may consider opening up a pull request in the future.
