### ISSUE TITLE
Test only asyncio loop by default.

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2248]
aiohttp uses parametrized `loop` fixture which runs all test suite several times: one for asyncio itself and another ones for uvloop and tokio if they are installed.
It's good for aiohttp testing itself but bad for `pytest-aiohttp` users.
For example test suites for my jobs take about 15 mins, we don't like to double the time (we use uvloop, sure).
We could solve the problem by pushing custom `loop` fixture into our `conftest.py` but it is not obvious and robust solution.

I suggest moving `pytest_configure` from `pytest_plugin.py` into `tests/conftest.py` and using only asyncio loop for tests by default.
As an option we could add support for command line `--aiohttp-loops` option and `aiohttp-loops` in `pytest.ini` for helping people to run their tests on specific asyncio loop implementations.

**Comment by argaen** [comment]
If you go for this, I would strongly +1 for adding a parameter where you can specify with which loops you want to run and pick only one by default (at least for development).

However for travis builds, I would keep passing tests for all the loops (dunno if that was included already in your intentions)

**Comment by asvetlov** [comment]
@argaen  yep, it is my intention.
BTW, would you work share my duty and on PR? 
The code change is not very hard.

**Comment by argaen** [comment]
Sure can do

**Comment by argaen** [comment]
After checking, I see that the `--loop` option is already supported with the pytest_plugin. The behavior is the following:

1. If nothing is specified, it picks installed loops.
2. If --loop specified, only picks the specified one (you can specify multiple one separated by comma).

With this I have couple of proposals:

1. Leave current behavior

With this, I think its just a matter of updating the `Makefile` needed commands to just use one loop. From what I've seen: `test`, `vtest`, `cov-dev`. Not so sure about `cov` which ends up using tox.

Then I would leave `cov-ci-no-ext`, `cov-ci-aio-debug`, `cov-ci-run` which are the ones used by travis as they are

2. Change default behavior so by default it always picks one loop (no matter if uvloop or tokio are installed) and if you want to run tests with multiple loops, you have to use the `--loop` option. Ofc this requires updating the commands used by travis to use all loops

**Comment by asvetlov** [comment]
I'm talking not about aiohttp test suite (running all available loops is perfectly fine) but changing `pytest-aiohttp` default behavior. Now it shares `loop` fixture with internal `./tests`.

**Comment by samuelcolvin** [comment]
@asvetlov, why not just change the default to just use `pyloop`, then aiohttp  `setup.cfg` can include:

    addopts = --loop all

?
