### ISSUE TITLE
aiohttp 2.3 release schedule

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2250]
We have very long list of features implemented in master but not released yet.

`towncriyer --draft` generates 107 lines.

I've scheduled at least 40 working hours for PRs review and cleaning up all pending issues.

aiohttp committers, please help me.
We have https://github.com/aio-libs/aiohttp/milestone/16 for list of pending issues for 2.3 but the list is not full.
Feel free to add 2.3 milestone for valuable issues without milestone mark.
For other ones please assign 2.4 milestone.

I'd like iterate over all open aiohttp issues and sort them by selecting ones which are required in aiohttp 2.3 from my perspective.

**Comment by asvetlov** [comment]
Showstoppers:
* ~Disable DNS cache #2262~
* ~'None' in HTTP headers #2183~
* ~Insecure algorithm for determining remote/scheme/host #2171~
* ~Server request's state is not cloned. #2284~
* ~ssl.SSLError explicit support #2297~
* ~Client basic HTTP auth domain mismatch #1699~
* ~_RequestContextManager will not close connection if ClientConnectorError has happened #2189~
* ~Default Aiohttp request parser `HttpRequestParserC` fails, parsing URLs of allowed size. #2311~

Fill free to add a bullet to the list.

**Comment by fafhrd91** [comment]
I'd cleanup PRs, it is not good to hold on PRs

**Comment by asvetlov** [comment]
Sure, opened PRs are in my priority list tooo

**Comment by asvetlov** [comment]
'None' in HTTP headers #2183 solved, Server request's state is not cloned. #2284 added.
#2284 is trivial, have anybody a time for making a fix?

**Comment by asvetlov** [comment]
#2262 looks like a non-issue, but I should reread the conversation.
#2171 is going to be finished by #2299

The 2.3 release is coming.
Guys, if you want to merge something into 2.3 -- please hurry up.
At least left a comment here.

**Comment by hellysmile** [comment]
Hey, is there any chance to include https://github.com/aio-libs/aiohttp/pull/2297 into 2.3?

**Comment by asvetlov** [comment]
Sure. Showstoppers list is updated.

**Comment by asvetlov** [comment]
"Client basic HTTP auth domain mismatch #1699 " is a security issue too

**Comment by fafhrd91** [comment]
#2189

**Comment by asvetlov** [comment]
Good point

**Comment by fafhrd91** [comment]
#2311

**Comment by pfreixes** [comment]
I know that this might be kind of disruptive but could you consider this #2313?

**Comment by kxepal** [comment]
@pfreixes I think #2313 is quite cool, but big feature that will delay release for unknown time. While it's simple to just copy-paste server implemntation, there are a lot of details to think about.

**Comment by asvetlov** [comment]
I want to release 2.3 next Monday.
We have 3 showstoppers -- all are relative easy and have straightforward solutions.

I'd like to accept #2252 also after some polishing.

**Comment by socketpair** [comment]
During holidays, maybe I will fix PR about GET + Content-Length:0

**Comment by asvetlov** [comment]
Unfortunately I didn't make the release today.
Good news: all showstoppers are fixed.
Waiting for CI green, than merge #2331 #2329 #2328 tomorrow and finally release aiohttp 2.3

**Comment by asvetlov** [comment]
Everything is done, preparing to release
