### ISSUE TITLE
HTTPS test_client doesn't run app with SSL context

### ISSUE THREAD

**Issue by savv** [aio-libs/aiohttp#2255]
Instantiating a test client like this: `client = await test_client(app, scheme='https')` currently doesn't work as expected. It seems that the server isn't ran with an SSL context.

## Expected behaviour
test_client should run app with an auto-generated SSL context.

## Actual behaviour
It doesn't :-)
## Steps to reproduce

```
from aiohttp import web

async def hello(request):
    return web.Response(text='Hello, world')

async def test_hello(test_client, loop):
    app = web.Application()
    app.router.add_get('/', hello)
    client = await test_client(app, scheme='https')
    resp = await client.get('/')
    assert resp.status == 200
    text = await resp.text()
    assert 'Hello, world' in text
```

**Comment by asvetlov** [comment]
What do you mean by auto-generated SSL context?
Self-signed certificate is not very useful for testing purposes, auto-generating true ssl certs are bundled with domain etc.
What do you actually need?

**Comment by savv** [comment]
Hi, I would like to write tests for my auth flow. The libraries that I'm using rely on all requests to be https - so in this case, a self-signed certificate would do.

**Comment by asvetlov** [comment]
You should use another fixtures toolchain.
Try something like:
```
async def test_z(test_server, test_client):
    app = web.Application()
    # TODO: setup app
    server = await test_server(app, ssl=ssl_context) 
    client = await test_client(server)
```
