### ISSUE TITLE
Use http.cookiejar.LWPCookieJar in aiohttp session

### ISSUE THREAD

**Issue by jimbasquiat** [aio-libs/aiohttp#2259]
## Long story short

I have a LWPCookieJar that i saved using python requests:

```
import requests
import http.cookiejar
s = requests.session()
s.cookies = http.cookiejar.LWPCookieJar(filename="test.cookies")
s.post("https://stackoverflow.com/users/login", data= <here my username and password>)
s.cookies.save()
```

I would like to enter directly my session using aiohttp, by loading the saved cookie in it.

```
import asyncio
import aiohttp
async def test_urls():
    async with ClientSession(cookie_jar=http.cookiejar.LWPCookieJar("test.cookies")) as session:
        async with session.get("https://stackoverlow.com") as response:
            response = await response.text()
            soup = BeautifulSoup(response, 'html.parser')
            print(soup.prettify())

loop = asyncio.get_event_loop()
loop.run_until_complete(test_urls())
```

I receive error: AttributeError: 'LWPCookieJar' object has no attribute 'filter_cookies'

I think this is because [i dont understand how to set cookies to the aiohttp session](http://aiohttp.readthedocs.io/en/stable/client_reference.html#aiohttp.ClientSession.cookie_jar).

Anyone can help me?

## Your environment

python 3.6
linux debian

**Comment by asvetlov** [comment]
aiohttp's implementation is written from scratch, it is not compatible with cookie jars from stdlib because stdlib is too tightly coupled with `urllib.request`.

Cookies saving is not supported out-of-the-box.
Not very hard to implement it though.

**Comment by asvetlov** [comment]
`LWPCookieJar` saves it's content as a text file with `Set-Cookie3: xxx` lines.
Making a custom parser for the file is a trivial procedure.
Looks like as a good exercise for interview. 

Closing the issue.
