### ISSUE TITLE
RuntimeError: set_wakeup_fd only works in main thread

### ISSUE THREAD

**Issue by eteamin** [aio-libs/aiohttp#2265]
## Long story short

I'm trying to run an aiohttp `Application` in a deamon thread. I use `asyncio.get_child_watcher()` in the main thread so subprocesses will be allowed to run. but I get `RuntimeError: set_wakeup_fd only works in main thread`

## Expected behaviour

Running aiohttp Application in a worker thread 

## Actual behaviour

RuntimeError is raised

## Steps to reproduce

A little more of context:
I'm writing tests for an aiohttp application. This app calls an external rest-full API to get some data. Now I'm trying to create another aiohttp application in a daemon thread to mock that third-party application behaviour. 
This is my `MockServer` class:

    class MockingServer(object):
        def __init__(self, host, port):
        self.host = host
        self.port = port
        self.app = Application()
        r = Resource('/validate_get/{content_uid}/{user_uuid}', Route('GET', '/validate_get', self.mock_handler))
        resource = self.app.router.add_resource(r.path)
        resource.add_route(r.route.method, r.route.handler)

        async def mock_handler(self, request):
            return json_response({'ok': True})

        def start(self):
            asyncio.get_child_watcher()
            thread = Thread(target=self._start, daemon=True)
            thread.start()

        def _start(self, *args):
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            run_app(self.app, port=self.port, loop=loop)` 

## Your environment
Python 3.5.2
OSX
aiohttp

**Comment by asvetlov** [comment]
You don't need a separate thread for running mocking server.
Take a look on https://github.com/aio-libs/aiohttp/blob/master/examples/fake_server.py

**Comment by eteamin** [comment]
Thank you for the useful example!
