### ISSUE TITLE
Could not parse hostname from URL

### ISSUE THREAD

**Issue by ThreshHNS** [aio-libs/aiohttp#2278]
## Long story short

ValueError: Could not parse hostname from URL. 

I can't get  to work a script (https://github.com/Myzon/vk-sketal and https://github.com/VKBots/VBot)
All leads to aiohttp error. Can you help me with this error?
![image](https://user-images.githubusercontent.com/24918680/30584715-2b097bda-9d5d-11e7-8f5c-f2fb366e0718.png)

## Your environment
Windows 10 (64 bit)
Python 3.6.2
Aiohttp 2.2.0

**Comment by asvetlov** [comment]
But your `/login?act=...` URL is relative.
aiohttp explicitly reports that URL has not *host* part.
What do you expect?

**Comment by asvetlov** [comment]
Closing the issue
