### ISSUE TITLE
Test fails on ppc64le

### ISSUE THREAD

**Issue by lgbaldoni** [aio-libs/aiohttp#2280]
Could this be an endianness problem?

[aiohttp_test.txt](https://github.com/aio-libs/aiohttp/files/1318404/aiohttp_test.txt)

**Comment by fafhrd91** [comment]
it is very hard to debug problem without access to hardware :)
could you run tests with -v, 
tests/test_web_protocol.py:791 seems aiohttp problem

but second looks like asyncio problem, could you run asyncio tests suit?

**Comment by lgbaldoni** [comment]
Here's the log for the tests in verbose mode:
[aiohttp_test_v.txt](https://github.com/aio-libs/aiohttp/files/1319005/aiohttp_test_v.txt)

I'm encountering some difficulty in running tests for sphinxcontrib-asyncio, but please let me know if it's really important.

Also this problem appears to be intermittent. It fails 1 out of 4 times.

The only thing out of the ordinary in sphinxcontrib-asyncio is that my distro (openSUSE) supplies a separate `__init__.py` in sphinxcontrib to avoid a namespace clash, but I'm not sure this is a factor.

**Comment by fafhrd91** [comment]
I am afraid, without access to hardware I can not help. especially for transient errors.

**Comment by lgbaldoni** [comment]
That's unfortunate. I suppose I'll have to exclude the build for that target.

By the way, I couldn't find any test to run in the sphinxcontrib-asyncio tarball.

**Comment by asvetlov** [comment]
It is a very simple sphinx markup plugin, tests are not required.

**Comment by lgbaldoni** [comment]
@asvetlov
so you'd rule out the problem coming from there?

**Comment by asvetlov** [comment]
sphinxcontrib-asyncio is needed for docs generation only.
aiohttp test failure on ppc is not related to it.
Sorry, I have no ppc hardware too.

**Comment by asvetlov** [comment]
Closing, we don't have an access to failed hardware.
