### ISSUE TITLE
ClientSession.request unexpectedly cancels task on timeout

### ISSUE THREAD

**Issue by savv** [aio-libs/aiohttp#2286]
## Long story short
`await client.get('https://httpbin.org/delay/10', timeout=.1)`
This call throws an exception on timeout, and it cancels the task it's running in.
This makes it hard to handle timeouts locally, e.g. by catching the timeout and returning an alternate value.

It would at least be worth documenting this behavior.

## Expected behaviour
I would have liked/expected the sample below to print:
`Caught exception!
api_req was able to handle timeout.`

## Actual behaviour
`Caught exception!
aiohttp cancelled us`

## Steps to reproduce
```python
import aiohttp
import asyncio

loop = asyncio.get_event_loop()
client = aiohttp.ClientSession(loop=loop)

async def api_req():
    try:
        res = await client.get('https://httpbin.org/delay/10', timeout=.1)
    except asyncio.TimeoutError:
        print('Caught exception!')
        return False
    except:
        print('This should not happen.')
    return True

async def arun():
    done, not_done = await asyncio.wait([api_req()])
    done, = done
    try:
        assert done.result() == False
        print('api_req was able to handle timeout.')
    except asyncio.CancelledError:
        print('aiohttp cancelled us')
    except:
        print('This should not happen.')

loop.run_until_complete(arun())
client.close()
loop.close()
```

## Your environment
`python 3.6.2` on osx

**Comment by hellysmile** [comment]
can You use just `asyncio.TimeourError` instead of `asyncio.CancelledError`?

**Comment by savv** [comment]
That still won't let me handle the time out within `api_req`

**Comment by savv** [comment]
@hellysmile FYI I updated the code snippet to include `except: print('This should not happen.')`. It still prints exactly the same thing, but now it's clearer which part of the code throws which exception.

One solution would be _not_ to catch the TimeoutError inside of `api_req()` and let it propagate to `arun()`, then handle it there. I think this would be a suboptimal solution, because it prevents `api_req()` from gracefully handling the timeout and returning an alternate value (e.g. a default value).

**Comment by wojunnihou** [comment]
I meet the same issues!!!!! 
Python 3.5.2 on centos

```python
async def ceshi(request, *args, **kwargs):

    # url = "https://stackoverflow.com/jobs?med=site-ui&ref=jobs-tab"
    url = 'https://api.github.com/events'
    url = 'https://www.baidu.com'
    try:
        async with aiohttp.ClientSession(conn_timeout=5,read_timeout=10) as session:
            async with session.get(url,timeout=5) as resp:
                print(resp.status)
                data = await resp.text()
                return HTTPResponse(data)
    except:
        return HTTPResponse("error", status=400)
```

**Comment by argaen** [comment]
@savvopoulos @wojunnihou I cannot reproduce:

```
23:04 $ python timeout.py 
Caught exception!
api_req was able to handle timeout.
```

timeout.py is the script uploaded by @savvopoulos
