### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by dfee** [aio-libs/aiohttp#2288]
I built a GraphQL component for `aiohttp` named [aiohttp-graphql](https://github.com/dfee/aiohttp-graphql) (i.e. `pip install aiohttp-graphql`).

The premise is simple: Just provide a schema and attach the view to the route:

```
from aiohttp_graphql import GraphQLView
from .schema import Schema

# ... get an app from somewhere (i.e. app = web.Application())

GraphQLView(app, schema=Schema)
```

And then you'll be able to access both **GraphQL** and **Graph*i*QL** on `/graphql`. There are many configuration options, so RTFD.

I just wanted to put this here for future users. Thanks `aio-libs` folks for maintaining good libraries to build on top of. Cheers –

**Comment by kxepal** [comment]
What's wrong to have it as standalone extension which provides extras to integrate graphql with aiohttp?  You there depends on aiohttp in anyway. What kind of support aiohttp have to provide?

**Comment by dfee** [comment]
That’s exactly what it is. This project is not a fork and pull request, I just wanted the community to be aware of it. I’m not sure of what they best place to share this info, so I created this issue.

**Comment by kxepal** [comment]
Sorry, I took your issue a bit different way. How about docs? We have there section about [third parties](http://aiohttp.readthedocs.io/en/stable/third_party.html) and extensions. Feels like the best place to share.

**Comment by dfee** [comment]
Cool. As this project gets sucked into the `graphql-python` org (fingers crossed), I'll submit a PR to add it to the third parties section.

**Comment by asvetlov** [comment]
@dfee feel free to make a PR for mentioning the library in our *third parties*.

I'm closing the issue -- the tracker is overwhelmed by bug reports and feature proposals.
I'm striving to reduce opened issues counter. Sure, you do understand me.
