### ISSUE TITLE
Unused `response_factory` argument of `web.UrlDispatcher.add_static`/`web.StaticResource`

### ISSUE THREAD

**Issue by zemlanin** [aio-libs/aiohttp#2290]
## Long story short

[Argument `response_factory`](http://aiohttp.readthedocs.io/en/v2.2.0/web_reference.html#aiohttp.web.UrlDispatcher.add_static) doesn't affect static responses

## Expected behaviour

aiohttp should call custom class passed to `aiohttp.web.UrlDispatcher.add_static()`

## Actual behaviour

`response_factory` value is ignored

## Steps to reproduce

```python
class CORSStreamResponse(web.StreamResponse):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'Access-Control-Allow-Origin' not in self.headers:
            self.headers['Access-Control-Allow-Origin'] = '*'

# ...

app.router.add_static('/static', f'./static', name='static', response_factory=CORSStreamResponse)
```

```
$ curl -I http://localhost:8000/static/bundle.js
HTTP/1.1 200 OK
Content-Type: application/javascript
Last-Modified: Tue, 19 Sep 2017 10:08:45 GMT
Content-Length: 84833
Date: Mon, 25 Sep 2017 14:07:59 GMT
Server: Python/3.6 aiohttp/2.2.5
```

## Your environment

`aiohttp==2.2.5`

**Comment by asvetlov** [comment]
Not sure if  we need support the factory.
Initially it was exist for overriding default behavior.
After `aiohttp.web.FileResponse` introduction user can make own web-handler for sending custom files easy.

`FileResponse` is not documented though.
What we really should do is writing docs for the response.

@zemlanin @Axik what is your motivation for passing custom factory instead of using the proposed way?

**Comment by zemlanin** [comment]
@asvetlov As I wrote in "Steps to reproduce", I've wanted to add `Access-Control-Allow-Origin: *` header to static file responses (for development)

**Comment by asvetlov** [comment]
Did you try just setup https://github.com/aio-libs/aiohttp-cors globally for the whole app?

**Comment by zemlanin** [comment]
What do you mean by "globally for the whole app"? Something like this from `aiohttp-cors`'s [usage](https://github.com/aio-libs/aiohttp-cors#usage)?

```python
for route in list(app.router.routes()):
    cors.add(route)
```

If so, then this snippet results in

```
  File "/usr/local/lib/python3.6/dist-packages/aiohttp_cors/urldispatcher_router_adapter.py", line 331, in add_preflight_handler
    preflight_route = route.resource.add_route(
AttributeError: 'StaticResource' object has no attribute 'add_route'
```

**Comment by Axik** [comment]
I'm just a stranger passing by trying to help people.
Anyway we need either fix or remove `response_factory` argument, because right now it's not working.

**Comment by asvetlov** [comment]
`response_factory` dropeed by #2307 
The behavior should be supported by aiohttp-cors itself.
