### ISSUE TITLE
Docs still reference no-longer-existent BodyPartWriter

### ISSUE THREAD

**Issue by mikenerone** [aio-libs/aiohttp#2291]
Pretty straightforward problem: the docs at http://aiohttp.readthedocs.io/en/stable/multipart.html still reference the `BodyPartWriter` class that no longer exists. In particular, it's unclear how to set an explicit content-disposition filename currently.

**Comment by asvetlov** [comment]
@kxepal ?

**Comment by fafhrd91** [comment]
This is Payload related change, but I do t have time at the moment

**Comment by mikenerone** [comment]
I've actually noticed other related problems on that page, as well. It says `MultipartWriter.append*()` return the appended parts, but they don't. It says `MultipartWriter.serializer()` exists, but it doesn't. There are numerous examples given using both of these, which of course no longer work. It seems these docs have never been updated at all for the refactoring of `MultipartWriter` to use `Payload` nearly a year ago (caa6bdb2484bf821b52a65322efa98a889b593de).

**Comment by webknjaz** [comment]
@asvetlov there's a few linters you might want to integrate into CI:
https://pypi.python.org/pypi/rstcheck
https://pypi.python.org/pypi/restructuredtext_lint

**Comment by asvetlov** [comment]
Fixed by #2759
