### ISSUE TITLE
Nominate Victor Kovtun to aiohttp developer

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2296]
I'm working with @hellysmile together on https://ocean.io/
He understand our development process very well and hi has very deep knowledge of aiohttp source code.
Moreover, hi is an author of several OSS projects published on https://github.com/wikibusiness/
We have a strong intention for moving at least a subset of them into *aio-libs* organization after some polishing.

Now I discuss with Victor almost every change in aiohttp, his feedback is very valuable. 
Virtually Victor presents in very many of my PRs for last months but his activity is hidden from community because we usually do it offline in the company office.
My position allows me to work on OSS part time, Victor is mostly concentrated on rolling business tasks on -- that's his public activity is too low in aiohttp

Anyway, the proposal makes no harm.

Vote!
* -1 means a strong objection and the subject for discussion.
* +-0 -- agree but not sure. Please elaborate your opinion.
* +1 -- you are agree.

**Comment by fafhrd91** [comment]
Сложно отказать после такого представления :)

+1

**Comment by jettify** [comment]
+1

**Comment by asvetlov** [comment]
Thanks for very positive feedback!
Vote will be finished at 2017-10-04

**Comment by samuelcolvin** [comment]
+1, welcome

**Comment by asvetlov** [comment]
Done.
Welcome, @hellysmile

**Comment by kxepal** [comment]
+1
Welcome, @hellysmile!

**Comment by jettify** [comment]
wellcome!

**Comment by hellysmile** [comment]
Thanks guys!
