### ISSUE TITLE
cancel pending tasks on finish_connections

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#230]
I've added an exemple for aiohttp.web websockets: examples/web_ws.py

Everything is fine but on closing the server by Ctrl-C websocket connections are still open (obviously).

```
Someone disconnected.
^CFuture exception was never retrieved
future: <Future finished exception=ClientDisconnectedError()>
aiohttp.errors.ClientDisconnectedError
Task was destroyed but it is pending!
task: <Task cancelling coro=<start() running at /home/andrew/projects/aiohttp/aiohttp/server.py:240> wait_for=<Future finished exception=ClientDisconnectedError()>>
```

The question is: should we **cancel** tasks after (optional) timeout?

The tasks are `ServerHttpProtocol.start()` coroutines, we don't keep the reference to those BTW.

**Comment by fafhrd91** [comment]
we already cancel _request_handler task in connection_lost()
it seems request_handler is in ‘canceling’ mode and requires one extra event loop tick is required to complete cancel operation.

**Comment by asvetlov** [comment]
Extra loop iteration (7fa339e) in `finish_connections` helps a bit, but I see another issue:

```
Server started at http://127.0.0.1:8080
Someone joined.
^C--- Logging error ---
Traceback (most recent call last):
--- Logging error ---
Traceback (most recent call last):
Exception ignored in: <bound method Future.__del__ of <Future finished exception=CancelledError()>>
```

**Comment by fafhrd91** [comment]
it seems that at this point you already have partially terminated python process. i'm not sure it worth of handling that.

**Comment by asvetlov** [comment]
Hmm. I'd like to see no extra printouts, at least in aiohttp examples.
Those will confuse newbies I think.

On Tue, Jan 13, 2015 at 12:08 AM, Nikolay Kim notifications@github.com
wrote:

> it seems that at this point you already have partially terminated python
> process. i'm not sure it worth of handling that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KeepSafe/aiohttp/issues/230#issuecomment-69656190.

## 

Thanks,
Andrew Svetlov

**Comment by fafhrd91** [comment]
i think you have to put KeyboardInterrupt around run_forever or handle SIGINT signal
