### ISSUE TITLE
pyinstaller cannot import aiohttp

### ISSUE THREAD

**Issue by karamjaber** [aio-libs/aiohttp#2301]
## Long story short

I wrote some big software in Python and now i want to build a one executable file that will run it all.
To build this executable i used pyinstaller .
It worked fine until i used aiohttp module, for some reason it doesn't recognize it

## Expected behaviour

To build the aiohttp as part of the executable

## Actual behaviour

After creating the executable and trying to run it i get the message 
**"ImportError: No module named 'aiohttp'"**

## Steps to reproduce

A file that contains 
```
import aiohttp
print("hello word")
```
Then try to make an executable file from this python file

## Your environment

Python 3
Any windows

**Comment by asvetlov** [comment]
Sorry, but executable building is out of aiohttp scope.
The project has nothing special from this perspective.
IIRC you need enumerate missed top level packages in your `setup.py`. `cf_Freeze` supports `build_exe_options` for example.

**Comment by rckclmbr** [comment]
@karamjaber you could also add aiohttp to `hiddenimports` in your spec file.  ie

```
hiddenimports=['aiohttp'],
```
