### ISSUE TITLE
aiohttp.wep.Application.make_handler should support pluggable AccessLogger

### ISSUE THREAD

**Issue by hellysmile** [aio-libs/aiohttp#2315]
## Long story short

There is now way to use custom `aiohttp.helpers.AccessLogger` for `aiohttp.wep.Application.make_handler`

## Expected behaviour

`aiohttp.wep.Application.make_handler` support pluggable `aiohttp.helpers.AccessLogger`

## Actual behaviour

`aiohttp.web.Application.make_handler` do not support pluggable `aiohttp.helpers.AccessLogger`

**Comment by asvetlov** [comment]
Fixed by #2316
