### ISSUE TITLE
Move docs (at least partially) to netlify

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#2318]
The docs site should move to netlify under aiohttp's own domain.

Even if you're not keen to move the deployed docs, at least you should set up netlify to build pull requests so the docs can easily be checked for each PR.

Advantages of moving from readthedocs to netlify:
* aiohttp can have (would need) it's own domain, perhaps shared for other aiolibs projects
* deploying docs for new releases can be automated through CI
* No ads on the aiohttp docs, or if the project thinks it's worthwhile aiohttp docs could host our own
* netlify's feature for building all pull requests makes checking docs look right very easy for collaborators and reviewers

Disadvantages:
* someone needs to buy a domain for aiohttp
* a redirect would be required from the current site. How easy does readthedocs make this?

@asvetlov If you think this would be a good idea, I think I can setup a netlify site for my fork and see if it works? If it does you can setup the main site.

**Comment by samuelcolvin** [comment]
Ok, I have this working my fork, see https://github.com/samuelcolvin/aiohttp/pull/1

**Comment by kxepal** [comment]
Why?

**Comment by samuelcolvin** [comment]
did you read my issue?

**Comment by kxepal** [comment]
Yes, but I didn't found there anything about "what's wrong with readthedocs".

**Comment by samuelcolvin** [comment]
* It doesn't build and display docs for pull requests
* From what I found, it couldn't (or wasn't easy to) trigger readthedocs to update docs on a github release.
* readthedocs add their own ads to aiohttp's docs. without sharing the revenue which doesn't really make sense to me.

**Comment by kxepal** [comment]
Imho,

> It doesn't build and display docs for pull requests

That's a minor issue. Docs changes dramatically it quite rare and their content is pretty flat. For the rest bits there is [restructuredtext_lint](https://pypi.python.org/pypi/restructuredtext_lint) and sphinx build as a part of testing stage.

> From what I found, it couldn't (or wasn't easy to) trigger readthedocs to update docs on a github release.

IIRC, RTD has git hooks and updates docs on commit fashion. 

> readthedocs add their own ads to aiohttp's docs. without sharing the revenue which doesn't really make sense to me.

Really? It seems like Internet with AdBlock is too perfect. That's a sad news.

What's good in RTD is that you can toggle which docs for which versions and branches to show / build / rebuild, how and else what their config page says. Would we reimplement several of these bits with netlify approach?

**Comment by samuelcolvin** [comment]
I had forgotten about the separate directories for different versions because I never use it, I don't know how important others think this is?

I would say showing docs for pull requests is not "minor" - it's very useful, but depends what others think?

**Comment by amirouche** [comment]
> I had forgotten about the separate directories for different versions because I never use it

I use that feature, linking to someone else the relevant doc is a nice feature for the correct version.

I don't know if there is a lot of people like me, but at work we are still using Python 3.4 and aiohttp 2.0

**Comment by samuelcolvin** [comment]
The closest netlify has is "branch deploys" where each branch is deployed to a separate subdomain.

Overall, it sounds like netlify is not entirely suitable for aiohttp's main site. But personally I still think building and displaying PRs would be useful, but only if others think so too.

**Comment by asvetlov** [comment]
I think we need a business card styled static web site on aiohttp.org and docs on separate subdomain. 

I've already booked aiohttp.com aiohttp.io aiohttp.org aiolibs.com aio-libs.com aiolibs.org aio-libs.org a year and half ago but still not published these sites. All cobblers go barefoot, you know.

Good news: my company https://ocean.io/ promised me to make the site design. I expect it to be done in month or two -- the task in not in high priority list for the company.

I never heard about netlify yet, need to dig deeper. I thought about renting the cheapest server on digitalocean or AWS but open for suggestions. I'm looking for solution with low maintenance cost (both time and money) and ability to share server support burden with aiohttp committers.
Stay tuned.

Regarding to readthedocs -- it's set up for build docs for git tag releases already.
We could setup travis to trigger docs publishing on our own site if needed though.

@samuelcolvin and other committers -- feel free to ask for request on adding you to aiohttp rtfd maintainers. Current list is fafhrd91 kxepal asvetlov popravich
Just publish your rtfd login as a comment here.

**Comment by samuelcolvin** [comment]
No need since it's set up right.

Regarding deploy of "business card" site, I would strongly recommend netlify, it's free, fairly easy to use and once set up requires zero maintenance. Like github pages on steroids.

I would still say netlify was worthwhile for rendering pull request docs since it gives nice link on the PR, but no one else seems that bothered, so I'll take the hint and close this.

**Comment by jettify** [comment]
@asvetlov That is awesome news! We can start with simple static site generator like netlify or any other and deploy it via github pages, as far as I can tell it is possible to attach custom domain.
