### ISSUE TITLE
aiohttp and openssl

### ISSUE THREAD

**Issue by kxepal** [aio-libs/aiohttp#232]
There is a case when you need to communicate with some server by using personal certificate issues by the host which is also protected by the password. Quite common one for the banks and digital signature centres. Python stdlib isn't able to handle password protected certificates so we have to use pyopenssl for that. And here our adventure starts.

``` python
import asyncio
import ssl

import aiohttp
import OpenSSL

# monkey patch to use OpenSSL errors
ssl.SSLWantReadError = OpenSSL.SSL.WantReadError
ssl.SSLWantWriteError = OpenSSL.SSL.WantWriteError


class ConnectionWrapper:
    def __init__(self, conn):
        self.conn = conn

    def getpeercert(self):
        return self.conn.get_peer_certificate()

    def cipher(self): ...

    def compression(self): ...

    def do_handshake(self):
        return self.conn.do_handshake()

    def getsockname(self):
        return self.conn.getsockname()

    def getpeername(self):
        return self.conn.getpeername()

    def fileno(self):
        return self.conn.fileno()

    def send(self, buf, flags=0):
        if isinstance(buf, bytearray):
            # aiohttp sends data as bytearray
            # pyopenssl doesn't likes that
            buf = bytes(buf)
        return self.conn.send(buf, flags)

    def sendall(self, buf, flags=0):
        if isinstance(buf, bytearray):
            # aiohttp sends data as bytearray
            # pyopenssl doesn't likes that
            buf = bytes(buf)
        return self.conn.sendall(buf, flags)

    def recv(self, bufsiz, flags=None):
        return self.conn.recv(bufsiz, flags=None)

    def close(self):
        return self.conn.close()


class Context(OpenSSL.SSL.Context):

    # this should be disables. otherwise we'll fall into API incompatibility
    # between ssl module and OpenSSL.crypto.X509 object
    verify_mode = ssl.CERT_NONE

    def wrap_socket(self, rawsock,
                    server_hostname=None,
                    do_handshake_on_connect=False,
                    server_side=False):
        conn = OpenSSL.SSL.Connection(self, rawsock)
        if not server_side:
            conn.set_connect_state()
        return ConnectionWrapper(conn)


class OpenSSLConnector(aiohttp.TCPConnector):

    def __init__(self, *args, cert_file=None, priv_file=None, password=None,
                 **kwargs):
        super().__init__(*args, **kwargs)
        self._cert_file = cert_file
        self._priv_file = priv_file
        self._password = password

    @property
    def ssl_context(self):
        if self._ssl_context is None:
            ctx = Context(OpenSSL.SSL.SSLv23_METHOD)
            if self._password:
                ctx.set_passwd_cb(lambda *unused: self._password)
            ctx.use_privatekey_file(self._priv_file)
            ctx.use_certificate_file(self._cert_file)
            self._ssl_context = ctx
        return self._ssl_context

# And here we go!

def go():
    connector = OpenSSLConnector(priv_file='priv.crt', cert_file='cert.crt', password='s3cr1t')
    resp = yield from aiohttp.request('get', 'https://localhost/foo/bar/baz', connector=connector)
    # should release response correctly to not populate OpenSSL.SSL.ZeroReturnError errors
    yield from resp.release()  

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(go())
```

While problem looks to be solved I wonder if is there better way to handle it and should (and ever could?) aiohttp be friendly for OpenSSL users?

**Comment by fafhrd91** [comment]
i think best approach is to create custom asyncio ssl transport that uses openssl, so you can skip monkey patching. you can even publish it on pypi.

**Comment by fafhrd91** [comment]
also check http://bugs.python.org/issue22560

**Comment by fafhrd91** [comment]
also consider this https://code.google.com/p/tulip/issues/detail?id=218

**Comment by kxepal** [comment]
Thanks for the links, will inspect them. Changes from 22560 looks really promising so far. Making custom ssl transport may be a solution, but for now cannot see the full picture how to make it and let it work with aiohttp. Need to think about and play around.

**Comment by fafhrd91** [comment]
1. make a custom ssl transport for asyncio
2. create public method, something like "make_ssl_transport" that will basically copy/paste from create_connection
3. make connection that will use that new transport in `_create_connection()`

**Comment by kxepal** [comment]
Aha, looks simple. Ok, will try this way. Closing issue for now, will update later when I'll have something. Thanks for guidelines!

**Comment by aiQon** [comment]
I know this is closed for now, but any hints on how to accomplish this in 2018? I tried the above snippet but it seems pretty much has changed after that. Pointers to more information would be highly appreciated. Thanks.

**Comment by asvetlov** [comment]
If you want to load password-protected certificate -- use `ssl.load_cert_chain` https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_cert_chain

It accepts the password parameter since Python 3.3

**Comment by aiQon** [comment]
I want to use a private key which is hosted by an HSM. I already have a reference for the key in a format that pyopenssl can work with (`PKey`). However, Im struggling to get pyopenssl to work with aiohttp. OP's snippet looked promising, but the plumbing which is necessary to get an `OpenSSL.SSL.Context` to be usable with `aiohttp.TCPConnector` seems more complicated than assumed. I cannot find proper documentation regarding this matter either.

**Comment by asvetlov** [comment]
Sorry, aiohttp TLS support is based on asyncio as a low-level library for working with sockets.
In turn asyncio uses ssl context objects only.
Maybe hacking pyopenssl can help, maybe not -- the question is out of aiohttp scope.
