### ISSUE TITLE
Drop aiohttp.Timeout

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2348]
`async_timeout.timeout` should be used instead.

**Comment by oleksandr-kuzmenko** [comment]
I can help with this

**Comment by asvetlov** [comment]
Please do.
Also you could look on #2321 and #2267 -- both are trivial

**Comment by asvetlov** [comment]
Fixed by #2370

**Comment by unera** [comment]
вообще за такие вещи было бы неплохо рожу бить.

**Comment by asvetlov** [comment]
@unera I've deleted your message.
Please keep calm and be polite next time when you post something.
