### ISSUE TITLE
Nominate Pau Freixes to aiohttp committer

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2349]
@fafhrd91 and I suggest to give @pfreixes write access to the repo.

Hi improved DNS caching very much as well as other minor contributions.
His initiative for client tracing support is amazing.

Let's vote:

-1 for strong objection
+-0 for not sure
+1 for definitely yes

Vote is finishing in a week at 2017-10-26

**Comment by kxepal** [comment]
+0

**Comment by fafhrd91** [comment]
+1

**Comment by asvetlov** [comment]
The vote has finished.
I see no objections.

Welcome, @pfreixes

**Comment by pfreixes** [comment]
Thanks, I will try to do my best to help you guys!

**Comment by kxepal** [comment]
🎉 @pfreixes 🎉

**Comment by pfreixes** [comment]
do you have any protocol about the number of reviewers needed to accept a PR?

**Comment by kxepal** [comment]
I'm not aware about such, but one so far is enough. But you can always call for more if you want to gather more feedback. 

May be so project by law would be nice to have to make such processes transparent and clear.

**Comment by asvetlov** [comment]
No, our team is not such big to require 2-3 reviewers.
I don't follow the note about transparency, sorry.

**Comment by kxepal** [comment]
@asvetlov I was referenced in my mind to document like [this](http://couchdb.apache.org/bylaws.html) that we have in CouchDB. It detaily describe how project processes works. Quite handy for newcomers.

**Comment by asvetlov** [comment]
Looks pretty good!
Would you contribute something like this into our documentation?

**Comment by samuelcolvin** [comment]
welcome @pfreixes.
