### ISSUE TITLE
Add settings dict for web.Application class

### ISSUE THREAD

**Issue by lordent** [aio-libs/aiohttp#2354]
Hi, i want to set my settings for Application instance for use it in custom middlewares.
At now, i must to implement Application class, and get it at middleware function throught app parameter.
I think it`s bad way, beacause this approach is not declared.

For example, i created CORS middleware like this:
```python

async def middleware_cors(app, handler):
    access_control_allow_headers = ', '.join((
        hdrs.ORIGIN, hdrs.CONTENT_TYPE, hdrs.ACCEPT, hdrs.AUTHORIZATION, hdrs.WWW_AUTHENTICATE))
    access_control_methods = ', '.join((method for method in hdrs.METH_ALL if hasattr(handler, method.lower())))

    async def middleware_handler(request):
        if request.method == hdrs.METH_OPTIONS:
            response = web.Response()
        else:
            response = await handler(request)
        response.headers.update({
            hdrs.ACCESS_CONTROL_ALLOW_ORIGIN: request.headers.get(hdrs.ORIGIN, '*'),
            hdrs.ACCESS_CONTROL_ALLOW_HEADERS: access_control_allow_headers,
            hdrs.ACCESS_CONTROL_ALLOW_METHODS: access_control_methods,
            hdrs.ACCESS_CONTROL_ALLOW_CREDENTIALS: 'true',
        })
        return response
    return middleware_handler
```

And i want to get origins hosts from settings, etc

What do u think?

**Comment by asvetlov** [comment]
Also take a look on https://github.com/aio-libs/aiohttp-cors
Maybe you don't need the wheel invention?

**Comment by lordent** [comment]
@asvetlov thanks for answer
> Sorry, your snippet has no settings word.

Yes, because i dont knew how solve it better.
aiohttp-cors good solution, u right, i think i`ll use it, thanks.

About app['settings'], it's may be not worse, if fill it same as app[ .. middleware_settings_name .. ] = { .. } . May be u right

**Comment by samuelcolvin** [comment]
A few things to note here.
1. I would guess from your code that you're assuming the `access_control_allow_headers = ...` code is only run once, at startup. Actually it's run on every request, see the warning [here](http://aiohttp.readthedocs.io/en/stable/web.html#old-style-middleware). This code has nothing to do with your application code so you can safely run it out side the middleware completely.
2. For simple cases you can use `app[...]` for settings. No need for `app['settings'][...]` or `app.settings[...]`.

**Comment by kxepal** [comment]
A few more things to note here:
Predefined `app.settings` may be not good option if you need a bit more than have few key-values there. For instance, we use Consul to manage our web services configurations and we relay on runtime reconfiguration through subscriptions. In this case `app.settings` couldn't be just a dict for us and not even dict-like object.

**Comment by lordent** [comment]
@samuelcolvin thanks for notation, I`ve not worked with an aiohttp for a long time, i will be necessary to re-read what has changed during this time
