### ISSUE TITLE
add a way to run an app asynchron

### ISSUE THREAD

**Issue by hwmrocker** [aio-libs/aiohttp#2375]
## Long story short

It would be nice to have an async / coroutine that will take an app and run it. This is very usefull if you have an long running that wants to expose a rest interface.

## Steps to reproduce

go to the web.py file and look for run function that runs an app asynchron

**Comment by kxepal** [comment]
I didn't get the use case. Can you elaborate?

**Comment by cecton** [comment]
Actually I think we do it the other way around. Put your tasks in jobs with https://github.com/aio-libs/aiojobs then run your app with `web.run_app`. Do you have a particular reason to do it in the way you want (`Application` ran in background)?

**Comment by hwmrocker** [comment]
I have a long running application/job/process running and want to add a REST interface to expose some internals during the runtime

**Comment by cecton** [comment]
Then why not using the startup hooks to add those long running applications/jobs/processes?

Here is my use case where I have a microservice with an API running, but there is a background tasks that monitors events from the Docker API: https://github.com/big-data-europe/mu-swarm-admin-service/blob/master/muswarmadmin/main.py#L659

**Comment by hwmrocker** [comment]
@cecton thanks for your link. In fact I could with a very small change use aiohttp to spawn my "main" task and since both should all the time it is fine for me.

**Comment by cecton** [comment]
@hwmrocker I'm glad it helped. We're still discussing about it on #2121 I will propose some changes that will become handy (when I have time and motivation 😣  )
