### ISSUE TITLE
[notification] Looks like appveyor is out of service

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2382]
I've merged several PRs without waiting for appveyor approvement.

I hope the service will be fixed soon.

**Comment by eteamin** [comment]
It's odd as they report their [status](https://appveyor.statuspage.io/) as `operational`!

**Comment by jairhenrique** [comment]
I enable `appveyor` for my user, and it runs. 🤔 
Did you try to restarting the service? It's windows. 😂

**Comment by asvetlov** [comment]
I've cancelled hanged appveyor job.
Let's close the issue after appveyor rebuild all queued tasks

**Comment by asvetlov** [comment]
Fixed
