### ISSUE TITLE
Add support for setting cookies for individual request

### ISSUE THREAD

**Issue by p0lm** [aio-libs/aiohttp#2387]
## Long story short

A `cookies` kwarg that can be set with individual request providing cookies just for a single time.

## Expected behaviour

Aiohttp provides an interface that mimics requests, but lacks support for sending a dict of cookies with a single request. It's be nice to have an optional keyword argument `cookies` on sending a request, providing a way to pass in a dict of cookies that are added on top of the cookies stored in the cookiejar.

**Comment by p0lm** [comment]
I'll try to take a swing at it later this week. It seems not too hard to implement.

**Comment by blueyed** [comment]
This can be closed, https://github.com/aio-libs/aiohttp/pull/3396 was merged.
