### ISSUE TITLE
Routes added after `add_static` silently ignored

### ISSUE THREAD

**Issue by gjcarneiro** [aio-libs/aiohttp#2388]
## Long story short

This doesn't work, the URL `/v1/all` is ignored, I get 404 when I try to access it:
```python
    app = web.Application()
    app.router.add_static(
        '/',
        os.path.dirname(os.path.realpath(__file__)) + '/build',
        follow_symlinks=True,
        show_index=True
    )
    app.router.add_get('/v1/all', web_get_all)
```

Anything below the `add_static` call is ignored.  I have to reorder thus to get it working (after a lot of wasted time):
```python
    app = web.Application()
    app.router.add_get('/v1/all', web_get_all)
    app.router.add_static(
        '/',
        os.path.dirname(os.path.realpath(__file__)) + '/build',
        follow_symlinks=True,
        show_index=True
    )
```
## Your environment

aiohttp 2.3.1 and `aiohttp-devtools==0.5` (running inside `adev`, didn't test without it).  Python 3.6 standard docker image.

**Comment by kxepal** [comment]
Because your static route is too greedy while aiohttp default router iterates routes in the order they were added.

**Comment by gjcarneiro** [comment]
Closing because I'm stupid.

**Comment by kxepal** [comment]
No, you don't @gjcarneiro. There just few caveats with builtin router which are not oblivious for users. The rule of thumb is: first comes specific rules, later comes more generic. Then you'll be safe.

**Comment by gjcarneiro** [comment]
I guess I am tainted because of using a lot nginx ingress controller (kubernetes), for which order of URLs doesn't matter, longest prefix always wins.

**Comment by asvetlov** [comment]
IIRC nginx passes fixed routes first, then executes regex based routes in order of addition.
