### ISSUE TITLE
change the aiohttp server to sanic/flask style

### ISSUE THREAD

**Issue by CC10010** [aio-libs/aiohttp#2394]

**Comment by kxepal** [comment]
[This won't happens](http://aiohttp.readthedocs.io/en/stable/faq.html#are-there-any-plans-for-app-route-decorator-like-in-flask).

**Comment by asvetlov** [comment]
But there is a way to use decorators for route registering: http://aiohttp.readthedocs.io/en/stable/web.html#alternative-ways-for-registering-routes
