### ISSUE TITLE
Integrate literalinclude directive for tutorial snippets

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiohttp#2396]
This issue is a follow-up for https://github.com/aio-libs/aiohttp/pull/2390#issuecomment-339336312.

Action items:
- [x] Integrate [`literalinclude`](http://www.sphinx-doc.org/en/stable/markup/code.html#directive-literalinclude) to keep example/demos and docs in sync (PR #2400)
  Here's the result of changes: https://aiohttp.readthedocs.io/en/stable/tutorial.html
- [ ] Extend CI to have a separate job for testing specifically those demos and be sure that snippets in docs are working and refer exactly to the source we have in repo, not outdated version of it.

/cc: @asvetlov 

P.S. IDK whether I'd have time for this myself either, but at least it's properly documented now.

**Comment by jsoucheiron** [comment]
First time contributor here. I've added a PR with changes for the tutorials file in the docs. I didn't even try to do the CI part though, hopefully someone with more experience can do that.

Keep the good work, this project is very useful!

**Comment by asvetlov** [comment]
Thank you @jsoucheiron

**Comment by asvetlov** [comment]
Fixed by #2400

**Comment by webknjaz** [comment]
@asvetlov but it does not include demo testing part
