### ISSUE TITLE
Design good distribution extras support

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiohttp#2397]
Follow-up https://github.com/aio-libs/aiohttp/pull/2312#issuecomment-339335603: this issue is intended to encourage discussion about adding extras support.

There's several optional dependencies mentioned in docs, and they instruct users to do `pip install {{dep_name}}`.

Common practice is to add feature-flags allowing to depend on certain additional ability of the framework w/o having to install those dependencies manually.

For example, aiohttp could have `speedups` extra and then user's could've just `pip install aiohttp[speedups]` instead of `pip install aiodns aiohttp cchardet`.

Also, it is possible to use environment markers as extra names, in this case certain dependencies get installed automatically if the environment matches specific expression, which might be useful for windows-only crutches etc.

Please consider treating extras as a **public API**, because they are exposed to end-users.

/cc: @asvetlov

**Comment by asvetlov** [comment]
I like the proposal, please go ahead

**Comment by asvetlov** [comment]
Can we close it? 
#3412 is merged.

**Comment by webknjaz** [comment]
Let's keep it for discussion and close upon final edits. It's a public API, we'll end up maintaining it as accepted, remember?

**Comment by asvetlov** [comment]
Agree

**Comment by webknjaz** [comment]
`charset-guessing-speedup`, `async-dns` and `brotli-compression`?

cc @WouldYouKindly

**Comment by asvetlov** [comment]
Perhaps my type speed is not enough for `pip install aiohttp[charset-guessing-speedup,async-dns,brotli-compression]`.

I'm starting to wonder if we need separate entry points for every feature. One point for installing everything is better maybe? If a user wants something specific -- he can learn from `extra_requires` what to install.

**Comment by WouldYouKindly** [comment]
@webknjaz @asvetlov why not just `speedups`, `async-dns`, and `brotli`? 

`charset-guessing-speedup` / `speedups`
Those who want speed either don't really care where it comes from, or are willing to look into `setup.py` and see exact libraries — so I see no need for such a descriptive name. If later you add more speedups, extras API would not need to change.

`brotli` — the word is almost always used for a compression algorithm, so we may omit that part.

**Comment by kxepal** [comment]
I think it would be better to limit support of extras by two cases: all extras on and all extras off. Otherwise we'll be burried by exponential growing combinations of those which need to support. 

Is there a case when you need just some specific ones?

**Comment by webknjaz** [comment]
:-1: for `all` — it's too "pointing to nowhere", all is not descriptive.
:+1: for `speedups` — communicates intention to the user better.

**Comment by webknjaz** [comment]
PR: #3434

**Comment by webknjaz** [comment]
@asvetlov @kxepal @WouldYouKindly question: should we also all `uvloop` there?

**Comment by WouldYouKindly** [comment]
@webknjaz if you decide to do so, it would be nice to mention `uvloop` in readme (along with `brotlipy`). (:

**Comment by kxepal** [comment]
If we're going to make perfomance focused aiohttp installation, uvloop should be used and supported on code side as well. Not use that this is right decision since there could be different event loops, but I don't know any except uvloop and tokyo.

**Comment by asvetlov** [comment]
> uvloop should be used and supported on code side as well

Not sure if I understand the sentence

**Comment by webknjaz** [comment]
I guess he means that aiohttp should automatically activate it if it's installed. Otherwise adding it as an extra will do nothing (except it'll just install it)

**Comment by kxepal** [comment]
@asvetlov exactly what @webknjaz said.

**Comment by webknjaz** [comment]
@kxepal this comment explain why it's bad: https://github.com/aio-libs/aiohttp/pull/3434#issuecomment-445265528

**Comment by kxepal** [comment]
Yeap, it turns complicated /:
