### ISSUE TITLE
Change aiohttp.server default parameters

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#241]
`ServerHttpProtocol` is constructed with `keep_alive=None` and `timeout=15`.

From my understanding that means no keep-alive connections and 15 sec timeout for web handlers.

The both defaults are wrong: I'd like to have keep-alives enabled by default and no cancelling for slow requests: websocket technically is implemented as _very slow_ web-handler.

Thoughts?

**Comment by fafhrd91** [comment]
Slow request is different, it is not related to handler, it is just for
parsing status line and headers

**Comment by fafhrd91** [comment]
+1 for keepalive, -1 for timeout

**Comment by asvetlov** [comment]
Done in da972ad
