### ISSUE TITLE
How to access db connection stored in app from subapp

### ISSUE THREAD

**Issue by SoumenDass** [aio-libs/aiohttp#2412]
## Long story short

I'm trying to find a way to access the database connection details stored in app (via dict-like interface) from the subapp.

## Expected behaviour

There must be some access method like subapp.get_root_app() so that I can then use that to get the database connections stored via subapp.get_root_app()['db']

## Actual behaviour

I can't find anything in the documentation that shows a way to do this. So I'm using the following approach:

```
app = web.Application()
app['db'] = db

# sub application setup
subapp = web.Application()
subapp['parent'] = app

# add subapp to main app
app.add_subapp('/sub/', subapp)
```
Then in the subapp's request handler, I'm doing request.app['parent']['db'] - it works when I know that the subapp is just one level below main/parent app. But what if there are nested subapps?

## Steps to reproduce

As shown above.

## Your environment

CentOS / aiohttp 2.3 / Nginx

**Comment by asvetlov** [comment]
Answered in #2413

**Comment by SoumenDass** [comment]
thanks

**Comment by codedumps** [comment]
> Answered in #2413

давай встретимся раз на раз или зассал?

**Comment by mattrasband** [comment]
@asvetlov It seems like #2413 doesn't address this in the context of signals - as a lot of our connections are managed via a `cleanup_ctx` in the root app.

Are there any other recommended ways of sharing given that common usage?

**Comment by webknjaz** [comment]
Plz open a new issue, this is going to get lost.
