### ISSUE TITLE
Build fails on Alpine when building in not a x86 architecture

### ISSUE THREAD

**Issue by rgdoliveira** [aio-libs/aiohttp#2414]
## Long story short
When trying to build aiohttp version 2.3.1 in Alpine (ppc64le and s390x architectures) the build fails at Alpine stripping part because it tries to strip "_http_parser.cpython-36m-x86_64-linux-gnu.so" shared object that is shipped in source code and fail in any architecture different from x86.

I guess the "_http_parser.cpython-36m-x86_64-linux-gnu.so" should not be shipped in the source code

## Steps to reproduce
- Clone Alpine aports project
- build py3-aiohttp project (community/py3-aiohttp) with command `abuild -r`

## Your environment
Alpine Linux 3.6.2 (ppc64le or s390x)

**Comment by asvetlov** [comment]
Good catch!
@webknjaz could you take a look? Or maybe @rgdoliveira could find a time for fix?
Checking build in Alpine would be nice but we should remove `.so` from tarball at least.

The PR should be done against `2.3` branch, I want make a new bugfix release.

**Comment by webknjaz** [comment]
@rgdoliveira @asvetlov I think, including smth like `find -name *.so -type f -delete` into our release process would fix this. Still I'll need some time for testing other approaches as well. For example, we could exclude it from manifest (https://github.com/aio-libs/aiohttp/blob/ca575f9/MANIFEST.in#L12-L18) or/and improve integration with `setuptools-git`, which seems to be added at some point (https://github.com/aio-libs/aiohttp/blob/3b39eb3886d08c1ea16f495a214ea95deb355237/requirements/ci.txt#L1), but not configured completely.

**Comment by asvetlov** [comment]
Let's just add explicit exclusion rule in `MANIFEST.in` as hotfix.
We could return to discussion about  `setuptools-git` usage later.
I don't feel we need it but maybe @webknjaz is true.
He was true many times regarding to our deployment process.

Anyway let's fix manifest and discuss future improvements later.

**Comment by RemiCardona** [comment]
Just a friendly poke to let you guys know I had to locally fix this issue by re-uploading 2.3.1 in my private pypi repo as `2.3.1+custom`. This tar.gz was generated using `python setup.py sdist` in a fresh git clone and it works just great.

**Comment by asvetlov** [comment]
@RemiCardona thank for comment but we should fix our deployment process.

**Comment by asvetlov** [comment]
Fixed by 8622d6c5
Please wait for bugfix release
