### ISSUE TITLE
socket.gaierror (dns error) is not converted to ClientConnectorError

### ISSUE THREAD

**Issue by hellysmile** [aio-libs/aiohttp#2423]
## Long story short

`socket.gaierror` should be converted to `ClientConnectorError`

## Expected behaviour

raises `ClientConnectorError`

## Actual behaviour

raises `socket.gaierror` (for threaded resolver) or `OSError` (for aiodns resolver)

## Steps to reproduce

```python
import aiohttp
import asyncio


async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get('http://notexist.domain') as response:
            return await response.text()


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

## Your environment

MacOS 10.12.6
Python 3.6.2 from pyenv

**Comment by hellysmile** [comment]
What about to extract fix for this from https://github.com/aio-libs/aiohttp/pull/2410 to separate pull request?

**Comment by achimnol** [comment]
Similarly, when connecting to an invalid UNIX socket file (e.g., `"/var/run/non-existent-socket.sock"`), it raises `FileNotFoundError` which is not converted to `aiohttp.ClientOSError`.
(refs aio-libs/aiodocker#142)

**Comment by hellysmile** [comment]
According to unix connector internals, it is another issue. Please submit it separetelly. It requires another fix.

**Comment by hellysmile** [comment]
Fixed by https://github.com/aio-libs/aiohttp/pull/2442, it is not in master yet
