### ISSUE TITLE
Attempts to connect to multiple ips from dns response is broken

### ISSUE THREAD

**Issue by hellysmile** [aio-libs/aiohttp#2424]
## Long story short

If dns server return multiple ip records for same host, `aiohttp` should try to connect for all them one by one until connection is established

## Expected behaviour

`aiohttp` tries to connect to all ips one by one

## Actual behaviour

If first connection fails, non of the rest ips is used

It were broken at https://github.com/aio-libs/aiohttp/pull/2297

There will be fix after https://github.com/aio-libs/aiohttp/pull/2410 will be merged

**Comment by asvetlov** [comment]
Fixed by #2447
