### ISSUE TITLE
headers not copied in case of redirects

### ISSUE THREAD

**Issue by Akilesh1597** [aio-libs/aiohttp#2439]
## Long story short
In case of http redirects my headers are not copied to subsequent requests

If my original request had authorization headers and if the server responded with 301 then the subsequent request does not include the header

## Expected behaviour
When redirecting, the data and headers of original requests must be included

## Actual behaviour

My Authorization headers are not available in redirected request and server responds with 401

## Your environment
aiohttp==2.3.1

**Comment by asvetlov** [comment]
Authorization is stripped if redirection URL points on other site than initial request: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L334-L336
Is it your case?

**Comment by asvetlov** [comment]
I'm inclining to close the issue in a week as invalid if no update.

**Comment by tmendo** [comment]
@asvetlov by other site you mean other origin? So example.com:443 is considered a different site from example.com:80, for this purpose?

**Comment by asvetlov** [comment]
Yes, it is different.
