### ISSUE TITLE
test_connect_with_capacity_release_waiters is broken

### ISSUE THREAD

**Issue by hellysmile** [aio-libs/aiohttp#2457]
## Long story short

Test tests.test_connector:test_connect_with_capacity_release_waiters is broken

`check_with_exc` just creates python generator(not coroutine) and do not execute it

In addition `aiohttp.connector.BaseConnector`

```python
    self._waiters = defaultdict(list)
``` 

could be

```python
    self._waiters = defaultdict(set)
``` 

which can give some optimization at 

```python
    finally:
            # remove a waiter even if it was cancelled
            waiters.remove(fut)
````

I've played with fixing test_connect_with_capacity_release_waiters

```python
assert not conn._waiters
``` 
is not really possible right now, even with fixed `async` signature to `check_with_exc`

It leaves empty list for `ConnectionKey` anyway

## Expected behaviour

test_connect_with_capacity_release_waiters is working

## Actual behaviour

test_connect_with_capacity_release_waiters creates generators

## Steps to reproduce

pytest tests -k test_connect_with_capacity_release_waiters

## Your environment

MacOS 10.12.6
Python 3.6.2 from pyenv

**Comment by derlih** [comment]
Looks like this test is not failing. At least on my config.
