### ISSUE TITLE
TCPConnector when family == 0, should sort dns responses to try ipv4 first

### ISSUE THREAD

**Issue by hellysmile** [aio-libs/aiohttp#2458]
## Long story short

Most widely used scenario is resolving localhost to ipv6, https://github.com/aio-libs/aiohttp/issues/2402 , but it can produce similar issues. aiohttp silently tries all responses from dns response and fails on ipv6 then connection established on ipv4. 

My proposal to sort dns responses by family and use ipv4 first(if family is ipv6 there wouldn't be any ipv4 ip's at all)

## Expected behaviour

ipv4 tried before ipv6

## Actual behaviour

arbitrary order of dns responses tried one by one

**Comment by webknjaz** [comment]
I've got an additional note:

I've faced an issue when Travis's box has disabled IPv6 (detected via `sysctl -a | grep ipv6`), but `localhost` gets resolved to `::1` because of dual entries in `/etc/hosts`.

I think, `aiohttp` could additionally probe availability of INET families and filter out unsupported ones.

**Comment by asvetlov** [comment]
Probing in DNS resolver are too expensive.
On other hand we are trying to connect on all resolved families already.

**Comment by webknjaz** [comment]
I'm talking more about try/except around interfaces domain resolves to, not DNS resolver (we've already got all IPs it resolves into). Maybe some list of available addresses interfaces could give us an idea about IPv6 support, for example.

**Comment by asvetlov** [comment]
How is it different from https://github.com/aio-libs/aiohttp/blob/bff50e6f58307bfdb830d7c1658baa6eb1b3e69a/aiohttp/connector.py#L803-L817 ?

**Comment by asvetlov** [comment]
Happy Eyeball is needed. Python 3.8 is a reasonable limitation I believe.

**Comment by bdraco** [comment]
Happy eyeballs was implemented and it used by default. There should be no need to worry about sorting addresses manually anymore as they happen in the order defined in RFC 8305
