### ISSUE TITLE
Choice of either aio-libs/aiohttp/ or aaugustin/websockets for an unified cryptocurrency Websocket interface (CCXT)

### ISSUE THREAD

**Issue by samholt** [aio-libs/aiohttp#2470]
Hi All,

Taking the lead on the Websocket development of the large open source project: https://github.com/ccxt/ccxt.

Would anyone be so kind as to recommend whether we choose either:

- https://github.com/aaugustin/websockets/
- https://github.com/aio-libs/aiohttp/

Which one would be best suited to the task of interfacing with cryptocurrency exchange web sockets ?

(Comments here can go into the eventual projects documentation, detailing the reason for the choice).

Thank you all

**Comment by kxepal** [comment]
Well, _obliviously_, aiohttp! What else could be recommended you here? (:

I guess if you list your requirement to websocket implementation, API and etc. the answer could be more specific. _Like, definitely aiohttp!_

Beside jokes, quickly looking into websockets project I see it's just a websockets implementation for asyncio. aiohttp is a bit more than websockets - it's a framework to make web applications and other frameworks for the same goal. So picking aiohttp support you will get more than just websockets. However, if you need *just* websockets as transport and you don't ever plan to provide any integration of your project with aiohttp-based services...well, then aiohttp provides too much redundant features for you.

**Comment by samholt** [comment]
Great thanks for the quick reply.

Yes aiohttp looks excellent, can aiohttp handle backpressure correctly ?
"
Robustness: websockets is built for production; for example it was the only library to [handle backpressure correctly](https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/#websocket-servers) before the issue became widely known in the Python community. 
"
 (https://github.com/aaugustin/websockets)

**Comment by kxepal** [comment]
@samholt 
[Yes](https://github.com/aio-libs/aiohttp/commit/b3c80ee3f7d5d8f0b8bc27afe52e4d46621eaf99). It should be correctly handled.

**Comment by samholt** [comment]
And keeping connections alive ?
https://websockets.readthedocs.io/en/stable/cheatsheet.html#keeping-connections-open

Your comments are excellent, thank you !

**Comment by kxepal** [comment]
And [yes](http://aiohttp.readthedocs.io/en/stable/web_reference.html#websocketresponse) - we have autoping and heartbeat features to keep connections alive.

**Comment by samholt** [comment]
Fantastic thank you, we'll be integrating ccxt with aiohttp

**Comment by kxepal** [comment]
Cool! Don't forget to mention your project in [powered by](http://aiohttp.readthedocs.io/en/stable/powered_by.html) section when you'll done (:

**Comment by kxepal** [comment]
And feel free to open issues / prs if something will be missed. I guess, this one could be closed now?

**Comment by samholt** [comment]
Yes, thank you will do

**Comment by fafhrd91** [comment]
@kxepal good work 👍 :)

**Comment by asvetlov** [comment]
@kxepal would you upgrade http://aiohttp.readthedocs.io/en/stable/faq.html with a new QA section?

**Comment by kxepal** [comment]
@fafhrd91 10x (:

@asvetlov Not sure what should I add there?..

**Comment by asvetlov** [comment]
Just emphasize that we do support websockets with backpressure etc.
aiohttp is the best choice if user needs even websocket server only but it works pretty good if HTTP server is needed too (usually user needs both).

**Comment by kxepal** [comment]
Ah, ok. Will figure something!
