### ISSUE TITLE
Github labels

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2477]
Call for @aio-libs/aiohttp-committers 
Please mark new Issues and Pull Requests by appropriate labels.
Sorry, I'm too lazy and busy for this task -- in my mind all issues are *labeled*, I'm keeping all of them in my brain.
But proper labels help newbies for both figuring out what the issue is related to and selecting easy tasks for contributing.
I love colorized github bugtracker at the end :)
Please not hesitate to mark every issue/PR.
If you have doubts for proper label -- just add it or left a comment.
If there is no such label in the list -- just add it.
`easy` label for example could help us by attracting an attention from new contributors by making a Pull Request.

I hope on your help.

**Comment by kxepal** [comment]
Ack!

**Comment by asvetlov** [comment]
P.S.
Non-members cannot assign a label IFAIK.
We have proper permissions, we should do this job.
Please consider it as a part of your responsibilities for the project -- as well as others, PRs review at least.

P.P.S.
I hope the issue text is not rude. I appreciate your help anyway -- but taking part in labeling will help to the project very much

**Comment by asvetlov** [comment]
Thanks @kxepal

**Comment by kxepal** [comment]
I think we would need to have some document about some guidence into labels to easy pick them and be sure we all understand their purpose as one. 

Need to find some inspiration to write such doc (:

P.S. No worries, house keeping is important part of big project life (;

**Comment by asvetlov** [comment]
@kxepal can you make this document?
It should be a part of our docs, sure.
I very appreciate your help on review process, BTW.
You almost did't make a commits but very active in PRs review.
Very thank you very much!

**Comment by kxepal** [comment]
Yes, I can. Just need some inspiration.

**Comment by jettify** [comment]
This idea applies to other repositories too?

**Comment by asvetlov** [comment]
@jettify why not?

**Comment by kxepal** [comment]
Hm..in this case...what's the status of aio-lib.github.io? May be we could put these organization wide documents?

**Comment by jettify** [comment]
This question posted in aiohttp repo, just want to confirm that we want this in other places.

**Comment by jettify** [comment]
There is also https://github.com/MunGell/awesome-for-beginners this is sort of list of places where beginner can contribute. Once we agree on labels we need to advertise aio-libs there too

**Comment by jettify** [comment]
pytest has nice set of labels https://github.com/pytest-dev/pytest/issues
something like
type:bug
topic:client
status:easy

**Comment by webknjaz** [comment]
Hi, I'm already used to add labels to the issues/PRs I read (and understand) in all of projects I maintain. As for me, it's just a good common sense of maintaining OSS.

Still, I'd like to emphasize a few additional points I consider relevant:
- first of all, I _support_ the need to have all label meanings documented (sometimes it's not easy for me to understand meanings of some of them)
- second, it's important to focus on newbie-friendly labels better: github suggests having label called `good first issue`. Names like this tell them more than just `easy`, we probably need to focus on making existing labels better understandable outside of the committers circle
- also, I'd encourage everyone to pay attention on world-promoted activities like `Hacktoberfest` (although this year's one is over now). **I've tested this one in several places and a few of marked issues _got solved almost immediately_.**
  Oh.. and it would play the same role as that awesome list does

P.S. Here's a nice collection of articles, which might be helpful:
- https://opensource.guide/building-community/
- https://opensource.guide/best-practices/

First contribution projects list:
- https://roshanjossey.github.io/first-contributions/ (https://github.com/Roshanjossey/first-contributions/blob/master/app/src/components/ProjectList/listOfProjects.js)

**Comment by asvetlov** [comment]
I've created http://aio-libs.github.io and github repo for testing our domain http://aio-libs.org/
I've bought the DNS name almost two years ago, maybe we should use it now.
The same for aiohttp.org.
We need at least business cards on these domains.
Everything will be open and most likely hosted on github.
Please let me a time for setting everything up and running, wait for design etc.

**Comment by kxepal** [comment]
No worries, take you time! It's extremely important and awesome initiative, look forward for it!

**Comment by asvetlov** [comment]
Closing the issue.
If you have a feeling that new labels are needed -- add it or create a separate issue for discussion
