### ISSUE TITLE
How to pass query parameters to ws_connect function

### ISSUE THREAD

**Issue by cruxhoo** [aio-libs/aiohttp#2481]
Hello!
I would like to know how can I pass query parameter to the ws_connect function. My issue is that I have to connect to a web socket server that expect to receive some auth key in the url query, like this:
   `wss://mydomain.com/socket.io/?sessionID={cc}&transport=websocket&EIO=3`
where sessionID is a value that I get in some other external call.

This is my current code.
    url = f'wss://mydomain.com/socket.io/?sessionID={cc}&transport=websocket&EIO=3'

    # manually format the url
    url = f'wss://mydomain.com/socket.io/?sessionID={cc}&transport=websocket&EIO=3'
    async with client.ws_connect(url, autoping=True) as ws:
        data = ['room-join', {'rooms': ["models.alert", "models.reminder", "models.entry", "models.measurement"]}]
        await ws.send_str(json.dumps(data))
        while True:
            ws.ping()
            greeting = await ws.receive()
            if greeting.tp == aiohttp.WSMsgType.closed:
                print("Closing")
            else:
                print("< {}".format(greeting))

**Comment by asvetlov** [comment]
```
url = yarl.URL('wss://mydomain.com/socket.io').with_query(sessionID=cc, 
                                                          transport='websocket', 
                                                          EIO=3)
```

**Comment by cruxhoo** [comment]
Thank you very much this did the trick.
