### ISSUE TITLE
[Question] primarydomain for aiohttp project

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2482]
I've booked aiohttp.com, aiohttp.org and aiohttp.io
What name should be used: aiohttp.org or aiohttp.io?
aiohttp.com should be a redirection obviously.

**Comment by samuelcolvin** [comment]
I think `aiohttp.org`.

`.io` makes me think "tech business", also people could get confused between `aio` and `.io`.

**Comment by kxepal** [comment]
+1 for aiohttp.org.
`.io` is cool, but not [reliable](https://siliconangle.com/blog/2017/07/10/security-researcher-manages-take-control-io-nameservers-epic-security-fail/).

**Comment by fafhrd91** [comment]
+1 for .org

**Comment by cruxhoo** [comment]
aiohttp.io is hard to pronounce

**Comment by asvetlov** [comment]
Ok, thanks for answers
