### ISSUE TITLE
drop handle.cancel

### ISSUE THREAD

**Issue by larryclean** [aio-libs/aiohttp#2489]
Hi @asvetlov 
What's the effect of dropping the `handel.cancel()` in [aiohttp/web_protocol.py#244](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_protocol.py)

**Comment by asvetlov** [comment]
Web-handlers will never be cancelled.

**Comment by larryclean** [comment]
👌，i see.thanks
