### ISSUE TITLE
AioHTTPTestCase doesn't work with uvloop

### ISSUE THREAD

**Issue by aptiko** [aio-libs/aiohttp#2491]
I can't tell whether this is a shortcoming of `uvloop` or a bug of `aiohttp`, but here it goes:

8e76a4a89b added this statement:

    policy.set_child_watcher(watcher)

The problem is that `uvloop`'s event policy subclasses `asyncio.AbstractEventLoop`, which doesn't implement `set_child_watcher()` (it raises `NotImplementedError`). Maybe it should subclass `DefaultEventLoopPolicy`, but I don't really know. In any case, attempting to run any `AioHTTPTestCase` with `uvloop` results in a `NotImplementedError`.

`aiohttp` 2.2 apparently doesn't have this problem.

**Comment by asvetlov** [comment]
Reported to uvloop team.
`set_child_watcher` is a part of `AbstractEventLoopPolicy` public API, `uvloop` should implement the method IMHO.
@1st1 ?

**Comment by 1st1** [comment]
uvloop doesn't need watchers, it won't be able to use them at all. We can just implement an empty `set_child_watcher`, if that helps.

**Comment by asvetlov** [comment]
Please do.
Otherwise aiohttp need a check for uvloop policy which is a weird.

**Comment by 1st1** [comment]
It won't happen right away, so for now I suggest you to just ignore `NotImplementedError`.

**Comment by asvetlov** [comment]
Makes sense.

**Comment by asvetlov** [comment]
Fixed by 24459935
