### ISSUE TITLE
[Discussion] Make app object importable

### ISSUE THREAD

**Issue by argaen** [aio-libs/aiohttp#2495]
I know aiohttp is against singletons and global variables but I wanted to open a discussion to see what's the opinion on this.

-----------------

Right now we have `request` and `app` objects as MutableMappings so we can store data, instances of connectors (i.e. Redis, postgres, caching, etc.). on them.

If its something you have to use while the app is alive, you will store that something inside the app object doing `app['cache'] = MyCache`. Similarly, if there is data that needs to live through the request cycle, you will do `request['data'] = my_data`.

Problem is that the app object once you've bootstrapped the application, its only accessible through the `request` object with `request.app`. This for simple handlers/views is more than enough because everything happens in that function but, in case of very complex handlers there is no other way but propagating the `request` object everywhere. This is not ideal because you start coupling all your functions, classes, etc. to aiohttp flow of receiving the fat request object that contains the app with the objects needed to work with. Plus, you need to propagate this object to ALL parts of your code and its very painful both for coding and for testing.

My proposal is to make the app importable. Something like `from aiohttp import current_app` or something like that (can be discussed here). This way you could do something like:

```
from aiohttp import current_app

class MyService:
    def __init__(self):
        cache = current_app['cache']
```

This would also open the door of storing configuration in the app so it can be used anywhere.

I know it may go against some opinions but I sometimes miss a lot having objects easily accessible. Other frameworks do it:

- Flask (although Flask does it TOO much IMO)
- Django: `from django.core.cache import cache`, `from django import settings`, etc.
- Apistar although its quite different because of all the dependency injection and components.

So I'm just opening this to gather feelings/opinions around this and to see if I'm the only one feeling that way :)

**Comment by asvetlov** [comment]
Simple question.
You have mupltiple applications.
Nested applications aka subapps and several top level applications for serving on different ports.
aiohttp aloows it right now.
Which one should be related by `from aiohttp import current_app`?
Please take into account: https://www.python.org/dev/peps/pep-0550/ is not accepted yet, we have no task local variable.

You should not propagate `request` everywhere. You can propagate `request.app` -- technically it is the same level of uglyness as getting app on import.
Moreover you can propagate `request.app['db']` or even `request.app['settings']`. aiohttp is agnostic in sense of what objects could be pushed into application context.

**Comment by samuelcolvin** [comment]
-1 I'm afraid.

If it's possible people will use it everywhere and an entire new genre of potential mistakes will be created.
