### ISSUE TITLE
Default access log format is wrong

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#2506]
It is still uses `%u` and `%l`

**Comment by asvetlov** [comment]
Actually it replaces both `%u` and `%l` to dashes.
I love to have fixed default format but we don't need bugfix release ASAP -- the behavior exists for two years :)

**Comment by fafhrd91** [comment]
just for bookkeeping

**Comment by asvetlov** [comment]
Aaah, ok
