### ISSUE TITLE
Implement a better way of handling non-HTTP urls in client.ClientSession

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiohttp#2507]
## Long story short

This is a follow-up for https://github.com/aio-libs/aiohttp/issues/2479#issuecomment-343559915.
Currently, if one uses `ClientSession` and it reaches URL with custom schema the exception with insufficient metadata is being raised.

## Expected behaviour

There should be some way to give control back to the caller once we reach **valid URL**, which we cannot follow because of unsupported schema. @asvetlov suggested to implement a custom exception for this.

## Actual behaviour

```python
ValueError: Can redirect only to http or https
```

## Steps to reproduce

Query `https://steamcommunity.com/mobileconf/conf` or `steammobile://lostauth/`, or `twitter://webknjaz`

**Comment by asvetlov** [comment]
I'm going to close the issue

**Comment by berislavlopac** [comment]
I propose that we either reopen this or create a new issue with the goal to create a better exception than `ValueError` for URL schemas that Client can't handle.

**Comment by webknjaz** [comment]
@berislavlopac the problem is that nobody has time to implement it. Are you willing to send a PR?

**Comment by berislavlopac** [comment]
I'm certainly willing, I'll try to make some time. Just could use some guidance on which type of error would be most appropriate here -- my guess would be `InvalidURL`, unless there is something more appropriate?

**Comment by asvetlov** [comment]
`InvalidURL` sounds good

**Comment by asvetlov** [comment]
Sorry, closed accidentally.

**Comment by webknjaz** [comment]
@berislavlopac sounds great! Let's try out what you suggest and then have a discussion in the PR :)

**Comment by webknjaz** [comment]
@berislavlopac maybe call it `NonHttpUrl`?

**Comment by webknjaz** [comment]
It should have some attribute with `yarl.URL` instance attached, so that when users catch that they could process it accordingly. And it might be nice to have a helper function running `xdg-open`/`open` or its Windows analogue depending on the platform.

**Comment by webknjaz** [comment]
(however I'm not sure — maybe such helper should go to the `yarl` project and be `URL`'s method or so)

**Comment by dubs3c** [comment]
Any chance this will be implemented?

aiohttp doesn't support this kind of URL either: `\\example.com`

**Comment by webknjaz** [comment]
@mjdubell feel free to submit a PR.

**Comment by berislavlopac** [comment]
I'm due an apology for not implementing it even though I said I will. Life intervened, and I have recently moved away from `aiohttp` and more towards `httpx`. Sorry! :blush:

**Comment by mjdubell** [comment]
![image](https://user-images.githubusercontent.com/1545807/72112142-05b52280-333d-11ea-9197-92260df438b2.png)

i kid, life happens :)
