### ISSUE TITLE
server application crushes and throws Unhandled Exception - Cancelled Error

### ISSUE THREAD

**Issue by JesseRo** [aio-libs/aiohttp#2509]
I'm having a web server application using aio-http as web framework. 
It worked just fine for last few month but now crushes unexpectedly after 10-20 minutes running,
here's the errors:

Unhandled exception 
Traceback (nost recent call last): 
File • [root/ anaconda3/1ib/pyth0n3. 6/'ite-p&ckages/aiohttp/web_protocol.py•, line 436, in start yield fron resp. write_eof()
File • /t00t/anaconda3/iib/python3. 6/'ite-paåaees/aiohttp/web_response.py", line 583, in vrite_eof yield fron super(). write_eof(body)
File • /t00t/anaconda3/lib/pyth0n3.6/site-packages/aiohttp/web_response.py, line 420, in vrite_eof 
yield fron self. _payload_writer.write_eof(data)
File • [root/anaconda3/lib/pfihon3.6/site-packages/aiohttp/http_writer.py, line 282, in write_eof yield from self. drain(True) 
File • /r00t/anaconda3/lib/python3. 6/site-packages/aiohttp/http_writer.py•, line 295, in drain yield from self. _ stream drain() 
File •/root/anaconda3/lib/python3. 6(site-packaces/aiohttp/http_writer.pf, line 128, in drain yield from self._protocol._drain_helper_()
File • /t00t/anaconda3/1ib/python3.6/asyncio/streans.py•, line 211, in yield from self. _ protocol. _ yield fron waiter 
concurrent. futures. _base. CancelledError

**Comment by asvetlov** [comment]
Please read http://aiohttp.readthedocs.io/en/stable/web.html#web-handler-cancellation first.
I pretty sure the behavior was not changed.
Moreover, I pretty sure it is not a crash but just a log record.

**Comment by JesseRo** [comment]
Thank you @asvetlov 
Yes, that is not a crash. What actually happens is the application stops serving and does not response any requests.. have to restart it..
Anyway, i upgrade aiohttp to 2.3 and then it seems like the problem is solved temporarily..
I read that doc about web-handler-cancellation, i‘m trying to understand it..
