### ISSUE TITLE
Maintain compatibility between yarl and aiohttp

### ISSUE THREAD

**Issue by astaff** [aio-libs/aiohttp#2514]
## Long story short

After recent upgrade of `yarl` our build that uses `aiohttp==2.2.3` broke with `unexpected keyword argument 'strict' being passed from http parser`. Upon investigation turned out that `yarl>=0.11` is required, but a breaking change was introduced in `0.14`.

## Expected behaviour

One of the following:
1) During setup install the version of `yarl` that maintains a contract with the version of aiohttp being installed.
2) Raise depreciation warning when arguments are being removed in minor version update.

## Actual behaviour

`>=` requirement combined with a breaking change introduced in minor version update resulted in aiohttp being unable to handle any request.

## Steps to reproduce

Running unit tests on 2.2.3 should reproduce the issue:

```
Traceback (most recent call last):
  File "/Users/astaff/Development/opentrons/opentrons/.env/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 278, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 274, in aiohttp._http_parser.HttpParser.feed_data (aiohttp/_http_parser.c:4364)
  File "aiohttp/_http_parser.pyx", line 334, in aiohttp._http_parser.cb_on_url (aiohttp/_http_parser.c:5381)
  File "aiohttp/_http_parser.pyx", line 544, in aiohttp._http_parser._parse_url (aiohttp/_http_parser.c:8777)
  File "/Users/astaff/Development/opentrons/opentrons/.env/lib/python3.5/site-packages/aiohttp/http_writer.py", line 317, in __init__
    path = yarl.quote(path, safe='@:', protected='/', strict=False)
  File "yarl/_quoting.pyx", line 38, in yarl._quoting._quote
TypeError: _quote() got an unexpected keyword argument 'strict'
```

## Your environment

OSX, aiohttp 2.2.3

**Comment by samuelcolvin** [comment]
Makes sense. 

@asvetlov I think we need a release of `2.2` branch which pins `yarl<0.14`, or a release of yarl which allows the `strict` argument but ignores it and raises depreciation error, perhaps raieses exception if `strict=True`.

**Comment by asvetlov** [comment]
Thanks for raising the issue.
We have discussed the problem in aio-libs/yarl#123
I was pretty sure the change is backward compatible but forgot about not using `yarl.URL.build()` by aiohttp 2.2.
Shame on me.

**Comment by kxepal** [comment]
@asvetlov 
I also think the quickest way would be to restore `strict` param with a new release and later fight with build issues. In the end, that parameter requires not much maintenance so it could stay there for little bit longer. Some deprecation warning would help people to abandon it quickly unless they provide reasons to keep it.

**Comment by astaff** [comment]
Thanks for quick response and pointing at the original discussion. And thank you for all the amazing work you are doing

**Comment by fafhrd91** [comment]
@kxepal 2.2 should be fixed, otherwise it will be broken later

**Comment by asvetlov** [comment]
I hope it's done by `yarl==0.14.1'

**Comment by asvetlov** [comment]
I've followed @kxepal suggestion.

@astaff please close the issue after checking.

**Comment by asvetlov** [comment]
Done by a new `yarl` release.
