### ISSUE TITLE
A new design for docs.aiohttp.org

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2520]
The plan is :
 
* [ ]  I'm waiting for new design for docs.aiohttp.org.
  New theme should be amazing, I'll share screenshots soon.
  The task is quite challenging, it should fit to sphinx tool and alabaster theme especially.
  Alabaster is not satisfactory right now, see bitprophet/alabaster#124 as an attempt for improvement.
  Maybe we will finished with own theme based on alabaster but with aio-libs design overrides for styling etc.
* [ ] After changing the docs theme I want to make aio-libs.org and aiohttp.org sites.
  Both sites should be just business cards for our work. Most likely Single Page Applications with static only content. Suggestions for static page rendering engine are welcome.
  Definitely the design of these sites should be mimic to docs.aiohttp.org -- but not restricted to sphinx limitations.

**Comment by asvetlov** [comment]
Redesigning is not a rush target but I hope to get everything done at time of aiohttp 3.0 release.

**Comment by menduo** [comment]
Now the color looks bad, because the color of the text (`#482C0A`) is hard to read, it makes my eyes uncomfortable, I think both `#000000` and `#404040` are better.

**Comment by asvetlov** [comment]
Thanks for sharing your opinion.

**Comment by asvetlov** [comment]
Done
