### ISSUE TITLE
aiohttp.test_utils.TestClient doesn't work with async with

### ISSUE THREAD

**Issue by barrachri** [aio-libs/aiohttp#2525]
## Long story short
Testing websocket using a TestClient does not work as expected.

## Expected behaviour

```python
async with cli.ws_connect('http://localhost/ws') as ws:
```
should work, where cli is aiohttp.test_utils.TestClient

## Actual behaviour
```python
>       async with cli.ws_connect('/ws') as ws:
E       AttributeError: __aexit__
```
## Steps to reproduce
Use async with a TestClient.ws_connect

## Your environment
Python 3.6.3
aiohttp 2.3.2

**Comment by barrachri** [comment]
I'd like to send a PR but I am a little bit lost inside the code.

`TestClient.ws_connect` returns a ```ClientSession(loop=loop,
                                      cookie_jar=cookie_jar,
                                      **kwargs)``` instance

`ws_connect` in `ClientSession` returns ```_WSRequestContextManager(
            self._ws_connect```

`self._ws_connect` returns a `ws_response_class`

that is a `ClientWebSocketResponse` instance

and then wrapped inside a ```_WSRequestContextManager``` that seems to have a `aexit`:
```python
class _WSRequestContextManager(_BaseRequestContextManager):
    @asyncio.coroutine
    def __aexit__(self, exc_type, exc, tb):
        yield from self._resp.close()
```

Am I missing something?

**Comment by asvetlov** [comment]
I suggest the following trick:
1. Rename `TestClient.ws_connect` coroutine to `_ws_connect`.
2. Create `TestClient.ws_connect` *non-coroutine* function which returns a wrapped call to `self._ws_connect()` -- just like `ClientSession` does.

**Comment by asvetlov** [comment]
Supporting both `await` and `async with` in the same async function is a quite tricky.
