### ISSUE TITLE
ClientSession request can't be cancelled without RuntimeError in some cases

### ISSUE THREAD

**Issue by germn** [aio-libs/aiohttp#2529]
## Code to reproduce:
```
import asyncio
import aiohttp
from contextlib import suppress


async def request(url):
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as resp:
            return await resp.text()


async def main(url):
    task = asyncio.ensure_future(request(url))

    await asyncio.sleep(0.001)

    task.cancel()
    with suppress(asyncio.CancelledError):
        await task

    print('done')


loop = asyncio.get_event_loop()
try:
    url = 'http://httpbin.org/delay/1'
    # url = 'http://broken'

    loop.run_until_complete(main(url))
    loop.run_until_complete(loop.shutdown_asyncgens())
finally:
    loop.close()
```

## Actual behaviour

`RuntimeError: Event loop is closed`

Msg for normal url:
`exception calling callback for <Future at 0x1ad769f6f60 state=finished returned list>`

Msg for broken url:
`exception calling callback for <Future at 0x2cecb9dd2b0 state=finished raised gaierror>`

## Expected behaviour

We should be able to cancel request without unexpected exceptions/messages.

I discovered behavior trying to answer [this](https://stackoverflow.com/q/47353461/1113207) question. 

Google showes two year old [issue](https://github.com/aio-libs/aiohttp/issues/441) with same problem. Workaround [mentioned there](https://github.com/aio-libs/aiohttp/issues/441#issuecomment-130678262) doesn't work and anyway is not a fix.

## Your environment

Windows 10, Python 3.6.2, aiohttp==2.3.3

**Comment by ljluestc** [comment]
Use a timeout on the request:
```
import asyncio
import aiohttp

async def request(url):
    async with aiohttp.ClientSession() as session:
        try:
            async with session.get(url) as resp:
                return await resp.text()
        except asyncio.CancelledError:
            # Handle cancellation explicitly, if needed
            print('Request was cancelled')
            raise
        except aiohttp.ClientConnectionError:
            # Handle connection errors, if needed
            print('Connection error')
            return None

async def main(url):
    task = asyncio.ensure_future(request(url))

    await asyncio.sleep(0.001)

    task.cancel()
    try:
        await task
    except asyncio.CancelledError:
        print('Request cancelled successfully')
    except Exception as e:
        # Handle other exceptions, if needed
        print('Unexpected exception:', str(e))

    print('done')

loop = asyncio.get_event_loop()
try:
    url = 'http://httpbin.org/delay/1'
    # url = 'http://broken'

    loop.run_until_complete(main(url))
    loop.run_until_complete(loop.shutdown_asyncgens())
finally:
    loop.close()
```
In the request() function, we added explicit exception handling for asyncio.CancelledError and aiohttp.ClientConnectionError. You can add appropriate actions in the respective except blocks as needed.
In the main() function, we modified the try-except block to handle asyncio.CancelledError explicitly and added a general exception handling block to catch other exceptions.

**Comment by Dreamsorcerer** [comment]
I think this issue is just very old, and uses low-level asyncio APIs which shouldn't be used in a typical application today.
