### ISSUE TITLE
Handling WebSocket disconnects

### ISSUE THREAD

**Issue by saghul** [aio-libs/aiohttp#255]
When reading from a ws connection, the `receive_msg` function may raise `WSClientDisconnectedError`. The example in the documentation just returns the ws object once done:

```
@asyncio.coroutine
def websocket_handler(request):
    ws = web.WebSocketResponse()
    ws.start(request)

    while True:
        try:
            data = yield from ws.receive_str()
            ws.send_str(data)
        except web.WSClientDisconnectedError:
            return ws
```

However, when an error is produced the exception is also stored in the closing_fut: https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web.py#L833-L859 As a result, a warning is logged because nobody retrieves that exception. I guess one way to "solve" it is to do something like this:

```
@asyncio.coroutine
def websocket_handler(request):
    ws = web.WebSocketResponse()
    ws.start(request)

    while True:
        try:
            data = yield from ws.receive_str()
            ws.send_str(data)
        except web.WSClientDisconnectedError:
            try:
                yield from ws.wait_closed()
            except web.WSClientDisconnectedError:
                pass
            return ws
```

But it kinda feels wrong.

Am I missing something or should this be handled differently? Thanks a lot for aiohttp, I'm really liking it so far!

**Comment by asvetlov** [comment]
Got it, my wrong. Thanks for report, I'll publish 0.14.2 patch very shortly.

**Comment by fafhrd91** [comment]
@asvetlov wait with release

**Comment by fafhrd91** [comment]
should be fixed

**Comment by saghul** [comment]
Thanks, I'll give it a shot. I see you added `wait_eof` in https://github.com/KeepSafe/aiohttp/commit/c58734056827d5855bae9b82c1600f3a8d83d6ae, is that supposed to be used _after_ getting the error while reading or will it be used internally?

**Comment by fafhrd91** [comment]
`RequestHandler` always calls `response.write_eof()` and `ServerHttpProtocol` should handle `WSClientDisconnectedError` exception properly.

**Comment by saghul** [comment]
Thanks for clarifying!
