### ISSUE TITLE
Feature Request: Per message deflate configurable per message

### ISSUE THREAD

**Issue by FlorianLudwig** [aio-libs/aiohttp#2551]
## Long story short

It is called "per message compression" but is not configurable per message.

Suggested API change:

`coroutine send_str(data, compress=None)`

The `compress` argument allows to overwrite the value from `WebSocketResponse` on a per message basis.

Same for `send_bytes` and `send_json`

**Comment by asvetlov** [comment]
I like the proposal.
Would you work on Pull Request?

**Comment by FlorianLudwig** [comment]
@asvetlov I love to get into the inner workings of aiohttp but as of right now I don't have the time at hand. 

So at same later time I will :)

**Comment by azhpushkin** [comment]
@FlorianLudwig @asvetlov I would like to take on PR for  this feature, do you mind it?

**Comment by asvetlov** [comment]
Please do

**Comment by FlorianLudwig** [comment]
@maqquettex awesome, thanks!
