### ISSUE TITLE
Simplify stream classes

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2555]
- [x] drop `ChunksQueue` -- not used by aiohttp code
- [x] drop `FlowControlChunksQueue` -- not used by aiohttp code
- [x] Merge `FlowControlStreamReader` into `StreamReader`, drop `FlowControlStreamReader`. The reader without flow control is not used by aiohttp, `FlowControlStreamReader` is too long name. Getting rid of `await super()` calls may boost performance a little.
- [x] Add hysteresis to `StreamReader` to prevent flipping between paused and resumed states too often.

**Comment by kxepal** [comment]
FlowControlChuckQueue is useful when server emits item-per-chunk - that's quite handy to process. CouchDB does that for instance. Let me check if this approach is still actual.

**Comment by asvetlov** [comment]
If CouchDB needs `FlowControlChuckQueue` -- please copy the implementation into the project.
Supporting not used classes is a burden, you know.

**Comment by kxepal** [comment]
Not a problem, I know (: Probably, that even wouldn't be need after switching to ijson.

**Comment by kxepal** [comment]
Just wanted to describe the case when that flow was useful. Some else users eventually may use it as well.

**Comment by asvetlov** [comment]
Fixed by @2256
