### ISSUE TITLE
More information provided when errors raised

### ISSUE THREAD

**Issue by rightaway** [aio-libs/aiohttp#256]
I'm getting several ClientResponseErrors but there is no additional information in the error object to hint at why it might have failed. Would be helpful if errors include more detail and documentation includes descriptions of when various errors are raised.

**Comment by asvetlov** [comment]
`ClientResponseErrors` is raised on server side when client disconnects without proper shutdown procedure.
In general those errors are fine, with slight performance degradation comparing to well-formed client side shutdown.

**Comment by fafhrd91** [comment]
@asvetlov thats different exception, `ClientResponseError` is raised by http client, but we use `raise from exc` form so original exception should be visible.

**Comment by asvetlov** [comment]
Oops, sorry. @fafhrd91, you are right.

**Comment by fafhrd91** [comment]
closing.  ClientResponseError has exceptions chain.
