### ISSUE TITLE
how to get post data

### ISSUE THREAD

**Issue by reddi-upw** [aio-libs/aiohttp#2566]
## Long story short

hi guys,

I need to know how can I get raw form data (body) before making post-request. Is it possible?

Thanks!

**Comment by asvetlov** [comment]
Sorry, your question is too broad.

**Comment by reddi-upw** [comment]
Sorry, I just mean how can I get prepared request data without doing really request? So I find the method similar to [prepare](http://docs.python-requests.org/en/master/user/advanced/#prepared-requests) requests method.

Thanks!

**Comment by asvetlov** [comment]
Duplicate of #2516
