### ISSUE TITLE
URL Resolver methods should not reference private attributes of parameters passed in

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiohttp#2568]
in https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_urldispatcher.py there are a variety of places where `_method` is pulled from the request instead of `.method`.  This in particular is causing me an issue when I try to pass a `RawRequestMessage` to my custom resolver (resolving each request of a google batch API call) as it only has `method` and not `_method`

see for example: 
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_urldispatcher.py#L510
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_urldispatcher.py#L702
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_urldispatcher.py#L762

this is both bad design (referencing private attribute) and unneeded from what I see, they should just use `request.method`.

**Comment by asvetlov** [comment]
Make sense.
Would you create a Pull Request?

**Comment by thehesiod** [comment]
sure!

**Comment by thehesiod** [comment]
btw one other interesting tid-bit is the use of `rel_url` as it's not available on `RawRequestMessage`.  Will see if something from there can be used as well instead.  I got my customer resolver working with Batch support, pretty neat.  Will post something about it.

**Comment by asvetlov** [comment]
Technically resolver works with `web.Request`, not `RawRequestMessage`.
`RawRequestMessage` is very low level private API, the class is not exposed by `__all__`.

Maybe you are doing something wrong?

**Comment by thehesiod** [comment]
here's what I'm doing: 
```python
from aiohttp.test_utils import make_mocked_request
from aiohttp.multipart import MultipartWriter
from aiohttp.http_parser import HttpRequestParser
from aiohttp import web

class AiohttpRawRequestWrapper(wrapt.ObjectProxy):
    @property
    def _method(self):
        return self.method

    @property
    def rel_url(self):
        assert not self.url.scheme
        return self.url

class MockGmailUserService:
    def __init__(self)
        self.dispatcher = web.UrlDispatcher()
        self.dispatcher.add_get('/gmail/v1/users/me/labels', self.get_labels)
        self.dispatcher.add_post('/batch/gmail/v1', self.gmail_batch)

    async def resolve_req(self, req: web.Request) -> Union[web.UrlMappingMatchInfo, None]:
        match_info = await self.dispatcher.resolve(req)

        if isinstance(match_info, MatchInfoError):
            print("Error resolving req: {} exception: {}".format(req, match_info.http_exception))
            return None

        return match_info

    async def gmail_batch(self, req: web.Request):
        reader = await req.multipart()
        writer = MultipartWriter()

        async for part in reader:
            async for data in part:
                parser = HttpRequestParser(self, asyncio.get_event_loop())
                messages, upgraded, data = parser.feed_data(data)
                assert len(messages) == 1
                assert len(messages[0]) == 2
                assert messages[0][1].is_eof()

                parsed_req = messages[0][0]
                transport = MockAioHttpTransport()
                protocol = mock.Mock()
                protocol._drain_helper = mock.CoroutineMock()
                loop = asyncio.get_event_loop()
                stream = StreamWriter(protocol, transport, loop)
                payload_writer = PayloadWriter(stream, loop)
                part_req = make_mocked_request(parsed_req.method, parsed_req.url, parsed_req.headers, payload=payload.BytesPayload(data), writer=payload_writer, payload_writer=payload_writer)

                match_info = await self.resolve_req(part_req)
                if match_info is None:
                    assert False

                part_req._match_info = match_info

                try:
                    resp = await match_info.handler(part_req)
                except HTTPException as exc:
                    resp = exc

                await resp.prepare(part_req)
                await resp.write_eof()

                writer.append(transport.buf, part.headers)

        return web.Response(body=writer, headers=writer.headers)
```

to support: https://developers.google.com/google-apps/calendar/batch

**Comment by thehesiod** [comment]
ok, that's a fairly complete example...of course the full implementation is like 1k lines ;)

**Comment by asvetlov** [comment]
Maybe you need `parsed_req = make_mocked_request(...)` instead of `AiohttpRawRequestWrapper`?

**Comment by thehesiod** [comment]
nice, good catch, thanks!  Just re-ordering the code resolves that issue, updated above with HTTPException fix!  Going to close this.  Would be nice later to be able to specify the `match_info` to `make_mocked_request`

**Comment by asvetlov** [comment]
Please add a PR for `match_info` :)

**Comment by thehesiod** [comment]
ok created https://github.com/aio-libs/aiohttp/pull/2575 for the PEP related fixes, and looks like someone beat me to the `match_info` param :)
