### ISSUE TITLE
Access current app, current request outside handler

### ISSUE THREAD

**Issue by Reonaydo** [aio-libs/aiohttp#2569]
Hello!

Is it possible to access current request object or/and current application object outside handler?
p.s. For server

**Comment by asvetlov** [comment]
No, aiohttp has no global states like `flask.request` and `flask.currrent_app`.
Explicit is better than implicit, isn't it?

**Comment by Reonaydo** [comment]
So. How can I get remote ip in, for example, custom logging filter ?

**Comment by kxepal** [comment]
[`request.remote`](http://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.BaseRequest.remote) will give you that information. Once you get it just pass around for logging.

**Comment by Reonaydo** [comment]
I know about request.remote
I don`t know how pass ``request`` or remote ip to custom logging.Filter based class.

**Comment by Reonaydo** [comment]
With flask I can make something like this:

```
class RemoteAddrFilter(logging.Filter):
    def filter(self, record):
        try:
            record.remote = request.environ.get('REMOTE_ADDR', '0.0.0.0')
        except RuntimeError:
            record.remote = '127.0.0.1'
        return True


sh = logging.StreamHandler()
sh.setFormatter(logging.Formatter(fmt="%(remote)s: %(message)s"))
app.logger.addFilter(RemoteAddrFilter())
app.logger.addHandler(sh)
```

**Comment by kxepal** [comment]
I would did that via log extra argument since request remote ip is a context for log call, not a static / rare changed part to use filters. 

Or you would need dynamic filters for every request, which may not sounds like as a good idea.

But why not to use [access logger](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/log.py) for this case? It [knows](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/helpers.py#L226) how to work with requests.

**Comment by argaen** [comment]
Hi @Reonaydo, for cases like the one you mention it is quite annoying to be propagating the request object everywhere explicitly. We had the same problem and we developed https://github.com/Skyscanner/aiotask-context for this. In the README you have examples about setting the `request_id`.

DISCLAIMER: I would recommend to just store only the information you need though. Consider it a bad practice to store everything there unless you really need it

**Comment by nikhilk** [comment]
It would be nice if there was a Context member off of aiohttp.web.Application that addressed task-local storage with a more aiohttp-centric solution.

**Comment by asvetlov** [comment]
@nikhilk I don't follow. 
If you have a concrete proposal -- please open a new issue.
