### ISSUE TITLE
Header is prepended to actual file when uploading via PUT

### ISSUE THREAD

**Issue by hongquan** [aio-libs/aiohttp#2570]
## Long story short

I'm uploading file to [Yandex Disk](https://tech.yandex.com/disk/api/reference/upload-docpage/). Yandex API is abnormal because it requires to use PUT method to upload file.

## Expected behaviour

The file after upload should be the same as the file on local disk.

## Actual behaviour

The file is prepended 5 lines of content, which looks like HTTP header:

```sh
$ head -n 5 plantinghouse_20171129-163839.sql.gz   
--736ed73419b14e18aaa25da51b721c7d
Content-Disposition: form-data; name="file"; filename="tmpr935f7qc"; filename*=utf-8''tmpr935f7qc
Content-Type: application/octet-stream
Content-Length: 25070
```

## Steps to reproduce

I write a script to export database from PostgreSQL, gzip it to a file in _/tmp_. The name `tmpr935f7qc` in the example above is the name of generated gzip file.
The script then uses `aiohttp` to upload file to Yandex Disk, through Yandex REST API.

## Your environment
aiohttp client 2.3.3
Python 3.6, ARMv7
OS: Debian 9, for BeagleBone Black board.
No proxy

Tested file (after uploaded):
[plantinghouse_20171129-163839.sql.gz](https://github.com/aio-libs/aiohttp/files/1513275/plantinghouse_20171129-163839.sql.gz)

**Comment by kxepal** [comment]
You can upload file with PUT request without problems. Please share the code that reproduces the issue.

**Comment by hongquan** [comment]
Hi, my code is here: https://gitlab.com/agriconnect/Gateway-Tool/blob/master/database-backup/aibackup-db.py

**Comment by kxepal** [comment]
I would guess that you need to send file content as is, in binary form, not as multipart.

**Comment by hongquan** [comment]
@kxepal Based on the header prepended to the file, I think it was already sent as binary (`Content-Type: application/octet-stream`)?

```
$ head -n 5 plantinghouse_20171129-163839.sql.gz   
--736ed73419b14e18aaa25da51b721c7d
Content-Disposition: form-data; name="file"; filename="tmpr935f7qc"; filename*=utf-8''tmpr935f7qc
Content-Type: application/octet-stream
Content-Length: 25070
```

**Comment by asvetlov** [comment]
No. If you use `client.put(url, data={'file': open(local_path, 'rb')})` aiohttp sends the body as `multipart/mixed` `Content-Type` (multipart form data).
Looks like in your case you should use `client.put(url, data=open(local_path, 'rb'))` for sending plain `octet-stream`.

**Comment by hongquan** [comment]
Thank you @asvetlov 
I fixed, following your suggestion and it works.
