### ISSUE TITLE
test_client fixture broken with pytest==2.3.3

### ISSUE THREAD

**Issue by argaen** [aio-libs/aiohttp#2572]
DISCLAIMER: I don't know if this is a `pytest` or `pytest-aiohttp` problem, but I think its interesting to follow this here just in case other users ask about it. Pytest issue in https://github.com/pytest-dev/pytest/issues/2975

## Long story short

After upgrading to `pytest==2.3.3`, all tests that use the `test_client` fixture are skipped.

## Expected behaviour

Tests using `test_client` fixture should run

## Steps to reproduce

Super easy to reproduce:

```
async def test_whatever(test_client):
    pass
```
With

```
pytest==3.3.0
aiohttp==2.3.4
pytest-aiohttp==0.1.3
```

With `pytest<=3.3.0` runs fine

**Comment by asvetlov** [comment]
I think the issue is the duplicate for #2565

**Comment by argaen** [comment]
True, closing in favor of that one then
