### ISSUE TITLE
Drop OSX tests on travis

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2574]
`Test under OS X (last chance to fail before deploy available)` takes a long time and totally useless: appveyor uploads tarball and Windows wheels regardless to failures on OSX.

Let's just drop the stage.

**Comment by webknjaz** [comment]
Plz don't do this. If you want to disable it, keep at least `if: type = api` to preserve ability of running 'em manually. Or you could drop ` OR tag IS present` (cron runs would reveal unpinned env issues)

**Comment by webknjaz** [comment]
Ref: https://github.com/aio-libs/aiohttp/blob/master/.travis.yml#L273

**Comment by asvetlov** [comment]
Tests are disabled by a48ae665
