### ISSUE TITLE
Cross-domain problem

### ISSUE THREAD

**Issue by zhouxinsenGitHub** [aio-libs/aiohttp#2576]

**Comment by zhouxinsenGitHub** [comment]
hi ,   how  set cross-domain in  server?

**Comment by asvetlov** [comment]
Your issue is completely unclean.
Please try again.

**Comment by zhouxinsenGitHub** [comment]
yeh, I want to allow "Access-Control-Allow-Origin:*" , but  i  don't konw how to do it.

**Comment by asvetlov** [comment]
Use https://github.com/aio-libs/aiohttp-cors

**Comment by zhouxinsenGitHub** [comment]
thanks
