### ISSUE TITLE
Review pytest fixture names

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2578]
Perhaps we need to add `aiohttp_` prefix to all fixtures to prevent clashing with other libraries.
Existing names should be supported for sake of backward compatibility at least up to aiohttp 4.0.

Thoughts?

**Comment by fafhrd91** [comment]
Those just tests and I think should be used by third party packages. It was a not logical change, upgrade is just find and replace. I’d add prefixes for 3.0

**Comment by asvetlov** [comment]
The fixtures are used widespread, by `aio-libs/aiohttp-*` also.
I want to not break all these libs at moment of aiohttp 3.0 release.

**Comment by asvetlov** [comment]
Fixed by #2714
