### ISSUE TITLE
No way to mix WSGI code with rest of server code

### ISSUE THREAD

**Issue by etianen** [aio-libs/aiohttp#259]
At the moment, the WSGI support for aiohttp is implemented as a protocol. This means that it's impossible to have part of your server route to a WSGI app, with other parts being handled by the aiohttp framework.

For example:

``` python
import asyncio
from aiohttp import web

@asyncio.coroutine
def hello(request):
    return web.Response(body=b"Hello, world")

@asyncio.coroutine
def delegate_to_wsgi(request):
    pass  # HELP!

app = web.Application()
app.router.add_route('GET', '/', hello)
app.router.add_route('GET', '/wsgi', delegate_to_wsgi)

# Start the event loop.
loop = asyncio.get_event_loop()
f = loop.create_server(app.make_handler(), '0.0.0.0', 8080)
srv = loop.run_until_complete(f)
print('serving on', srv.sockets[0].getsockname())
try:
    loop.run_forever()
except KeyboardInterrupt:
    pass
```

Currently, the only way to use the aiohttp.wsgi support would be to start a brand new server on a different port, which seems like a shame.

**Comment by fafhrd91** [comment]
I am not really sure reason to use wsgi. Usability of existing wsgi libraries are very limited, even very basic ones like webob has problems with async data processing. In any case aiohttp.wsgi is a second class citizen and won't receive any new features except bug fixes from core developers. If you really need that bridge please make PR, otherwise it won't happen

**Comment by etianen** [comment]
The reason to do this is to allow a synchronous wsgi app to run on the same socket as an asynchronous aiohttp app, with the router determining which one should be invoked for a given request.

Use case: I have a django app that I want to add websockets to without having to start another server on another socket.

I can implement this as a pull request with a handler class that wraps a wsgi application.

**Comment by fafhrd91** [comment]
Technically it is not possible. Synchronous code will block asyncio event
loop.

**Comment by etianen** [comment]
Absolutely, the synchronous code would have to use a thread pool.

I see two scenarios here:

1) Adding websockets to an async wsgi app.
2) Adding websocketsc to a sync wsgi app.

Currently the codebase makes you choose between running websockets OR running a wsgi app on a given socket. It would be great if running both on the same socket could be supported.

**Comment by fafhrd91** [comment]
aiohttp.wsgi expects asyncio transport, which expects non blocking sockets.
instead of using aiohttp.wsgi i’d use existing sync wsgi server like waitress and modify it to use partially parsed requests and use bridge to pass aiohttp.web request.
but i will never accept this into main aiohttp package.

**Comment by etianen** [comment]
Is aiohttp.wsgi essentially deprecated then? You seem reluctant to add in additional wsgi functionality.

Having a sync wsgi app and an async web socket app working together on the same socket seems like a fairly reasonable use-case. It’s a use-case that’s supported by gevent and by Autobahn. Having aiohttp also support this use-case sounds useful to me.

At the simplest, a wsgi handler that buffers the input and output streams, and runs the wsgi app request in a thread, seems like a way to safely run any existing wsgi app alongside websockets.

**Comment by fafhrd91** [comment]
it is not deprecated, but i’m not planing to add any new features. Right now i’m very skeptical about mixing async and sync request processing.
But i am open to PR, and someone needs to be maintainer of such integration.

**Comment by etianen** [comment]
I think that maybe this belongs as a separate project, then. It can be nicely implemented as a handler callable, and bolted onto the existing aiohttp router.

**Comment by fafhrd91** [comment]
i agree. separate project is better approach. later it could included to aiohttp, it worked very well with aiorest, which is involved into aiohttp.web

**Comment by etianen** [comment]
For the record, here is the implementation I open-sourced:

https://github.com/etianen/aiohttp-wsgi

The WSGI application is implemented as a request handler. WSGI requests are run in an executor to avoid blocking the event loop. The request stream is buffered in memory, and the response iterator is output using a StreamResponse. From the point of view of the executor, the output stream is non-blocking, and will buffer in memory if the executor generates response data faster than the network supports.

https://github.com/etianen/aiohttp-wsgi#design
