### ISSUE TITLE
Server handler halts after client connection closed

### ISSUE THREAD

**Issue by ykvch** [aio-libs/aiohttp#2595]
Pre:
-----
Linux with curl installed.
Python 3.6.3 with aiohttp installed

Server script (server.py):
```
# coding: utf-8

from asyncio import sleep
from aiohttp import web


async def handle_stream(request):
    data = 'Їїїїї'
    resp = web.StreamResponse()
    resp.content_length = len(data)
    await resp.prepare(request)

    resp.write(data.encode("utf-8"))
    await sleep(1)  # if sleep present, handle ends here, next line not executed
    raise RuntimeError("this should happen")


app = web.Application()
app.router.add_get("/", handle_stream)
web.run_app(app)
```

Steps:
--------
1. Run server script: python server.py
2. On the same host run (bash): `curl -vv http://127.0.0.1:8080/`
3. Observe server.py script console output.

Expected:
-------------
3. RuntimeError("this should happen") message 1 second after client disconnects.

Actual:
---------
3. Server runs without messages (raise... line never executed)

_Note:_ If `await sleep...` line (above the `raise...`) removed then exception *does* get triggered.

**Comment by fafhrd91** [comment]
This is expected behavior, await sleep raises CancelledError

**Comment by ykvch** [comment]
Thanks.
Now it clearly looks like a duplicate/similar to https://github.com/aio-libs/aiohttp/issues/1430

Solution:
Explicitly use `shield` around anything that has to be executed independently of connection cancellation.
