### ISSUE TITLE
Fix examples in documentation: remove obsolete direct content-type specification for JSON

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#2598]
https://docs.aiohttp.org/en/stable/web.html#example

instead of specifying content-type in example, one should use `web.json_response(...)`.

**Comment by asvetlov** [comment]
Would you provide a Pull Request?

**Comment by socketpair** [comment]
Yes, sure

**Comment by asvetlov** [comment]
Fixed
