### ISSUE TITLE
Remove obsolete inheritance from `object`

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#2599]
Like this one: `class MultipartReader(object)` -> `class MultipartReader`.

Since Python 3.0 there is no difference between these two forms.

**Comment by asvetlov** [comment]
Pull Request is welcome.
The task is super easy, even no tests are needed.

**Comment by sheb** [comment]
I could try to do it as it's an easy task to begin to hack aiohttp :)

**Comment by asvetlov** [comment]
Fixed by #2602
