### ISSUE TITLE
EOF occurred in violation of protocol (_ssl.c:600)

### ISSUE THREAD

**Issue by ghost** [aio-libs/aiohttp#260]
Hi,

Since few days I have this error "EOF occurred in violation of protocol (_ssl.c:600)". Google said me that is an issue with openssl. The workaround is to force TLS V1. But how can I do that with aiohttp?

Thanks,

**Comment by asvetlov** [comment]
Hi. Are you talking about client or server API?
For client you can specify `sslcontext` parameter in `TCPConnector` constructor.

**Comment by ghost** [comment]
Hi asvetlov,

It's a client request:
response = yield from aiohttp.request('GET', 'https://example.com')

If I do that:

conn = aiohttp.TCPConnector(verify_ssl=False)
response = yield from aiohttp.request('GET', 'https://example.com', connector = conn)

It's simple but this should works, no?

**Comment by asvetlov** [comment]
You code disables all SSL validation checks.
See https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/connector.py#L259 for examples of `SSLContext` creation.

**Comment by ghost** [comment]
Thanks Asvetlov, it works well.

**Comment by asvetlov** [comment]
Sure!

On Wed, Jan 28, 2015 at 3:07 PM, matt75013 notifications@github.com wrote:

> Closed #260 https://github.com/KeepSafe/aiohttp/issues/260.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KeepSafe/aiohttp/issues/260#event-226054171.

## 

Thanks,
Andrew Svetlov
