### ISSUE TITLE
Run http server when event loop is already running.

### ISSUE THREAD

**Issue by stonemonk** [aio-libs/aiohttp#2608]
I am trying to use aiohttp to run an http server as part of a larger app that already manages the event loop.  If I run `web.run_app()` I get an error because its trying to run the loop itself.  As the http server in my case is just a small and **optional** feature, it doesn't make sense for me to allow aiohttp to manage it.

Is there a way to acomplish this, aside from duplicating all of the work that `web.run_app()` is doing in my own app?  That is what I have done for now as a workaround, but its obviously not ideal as my app shouldn't know about those kinds of aiohttp interals. (Including making a call to the protected `web._make_server_creators` function and having to watch for any changes to `web.run_app()` across versions.

Ideally, aiohttp could just restructure things as to return 2 coroutines to be run on the loop (one for startup, one for shutdown), along with a helper function that does it for you which would keep compatibility with the current `web.run_app()` behavior.

**Comment by pfreixes** [comment]
Have you considered to run it in another thread/process using an executor? How much friction does it imply in terms of passing data btw the main application flow and the Aiohttp one?

**Comment by fafhrd91** [comment]
Just set loop using asyncio.set_event_loop, aiohttp will use it

**Comment by pfreixes** [comment]
I wont considere it as a workarround, asyncio was designed to support many loop instances running in different executors. My mainly concern is about the supposed extra work to pass information btw your flow and the aiohttp one, do you have a real example ?

In any case regarding if aiohttp should support this entry point will be a good question for more experimentated aiohttp commiters such as @asveltov.

**Comment by stonemonk** [comment]
@fafhrd91:

The problem is that I am calling `web.run_app()` from a co-routine that is already running on the main thread's event loop and `web.run_app` calls `loop.run_until_complete()` which gives an error.

Do you mean I should create a new event loop on the main thread and pass that to aiohttp to monopolize?  I haven't tried to run more than one event loop per thread yet, I dunno how well it works in practice or what coordination efforts would be needed.

**Comment by stonemonk** [comment]
@pfreixes: 

I don't readily have a good (read: simple) example to give.  My http server needs to access data models to get and present information.  These models are part of a complex system (1000's of lines of code), and were not designed to be thread safe. 

It would require either extensive use of locks,  or extensive use of run_coroutine_threadsafe() with callbacks or more likely waiting the for response from the main event loop in order to produce the http response on the BG event loop...

**Comment by fafhrd91** [comment]
I see, forgot about that already.

You can do copy/paste, it relatively easy to start aiohttp server or wait for 3.0 release it has much nicer api

**Comment by stonemonk** [comment]
@fafhrd91:

As mentioned, my copy/paste work around works fine for now, especially considering my use case.  Its just a bit ugly and a maintence issue.  So this was more a feature request.

**Comment by fafhrd91** [comment]
This should be fixed in 3.0

**Comment by stonemonk** [comment]
Okay, I just tried adapting the aiohttp code for this and it runs well for me.  It should preserve the `web.run_app()` functionality **exactly** while exposing the coroutines for my use case.  I will just post it here for consideration rather than making a PR.  If you like the approach, feel free to adapt and include it.   `app_coroutine` would be better called `start_server` or something.

```
def run_app(app, *, host=None, port=None, path=None, sock=None,
            shutdown_timeout=60.0, ssl_context=None,
            print=print, backlog=128, access_log_format=None,
            access_log=access_logger, handle_signals=True, loop=None):
    """ Run an app locally, driving the event loop. This blocks the current thread until termination.
    """
    user_supplied_loop = loop is not None
    if loop is None:
        loop = asyncio.get_event_loop()

    app._set_loop(loop)

    starter = app_coroutine(
        app, host=host, port=port, path=path, sock=sock,
        shutdown_timeout=shutdown_timeout, ssl_context=ssl_context,
        backlog=backlog, access_log_format=access_log_format,
        access_log=access_log)

    try:
        stopper, uris = loop.run_until_complete(starter)

        if handle_signals:
            try:
                loop.add_signal_handler(signal.SIGINT, raise_graceful_exit)
                loop.add_signal_handler(signal.SIGTERM, raise_graceful_exit)
            except NotImplementedError:  # pragma: no cover
                # add_signal_handler is not implemented on Windows
                pass

        if print:
            print("======== Running on {} ========\n"
                  "(Press CTRL+C to quit)".format(', '.join(uris)))

        try:
            loop.run_forever()
        except (GracefulExit, KeyboardInterrupt):  # pragma: no cover
            pass
        finally:
            loop.run_until_complete(stopper)
    finally:
        loop.run_until_complete(app.cleanup())

        if not user_supplied_loop:
            if hasattr(loop, 'shutdown_asyncgens'):
                loop.run_until_complete(loop.shutdown_asyncgens())
            loop.close()


async def app_coroutine(app, *, host=None, port=None, path=None, sock=None,
            shutdown_timeout=60.0, ssl_context=None,
            backlog=128, access_log_format=None,
            access_log=access_logger):
    """ Starts up an app's HTTP server and returns a co-routine to shut it down.
    """
    loop = asyncio.get_event_loop()
    await app.startup()

    make_handler_kwargs = dict()
    if access_log_format is not None:
        make_handler_kwargs['access_log_format'] = access_log_format
    handler = app.make_handler(loop=loop, access_log=access_log,
                               **make_handler_kwargs)

    server_creations, uris = _make_server_creators(
        handler,
        loop=loop, ssl_context=ssl_context,
        host=host, port=port, path=path, sock=sock,
        backlog=backlog)

    servers = await asyncio.gather(*server_creations)

    async def stopper():
        server_closures = []
        for srv in servers:
            srv.close()
            server_closures.append(srv.wait_closed())
        await asyncio.gather(*server_closures)
        await app.shutdown()
        await handler.shutdown(shutdown_timeout)

    return stopper(), uris
```

You will note that unlike `run_app`, the coroutine does not take a loop argument as it should be run on the desired loop of choice and as such it makes sense for it to get the relevant loop from context (`asyncio.get_event_loop()`).  `run_app` of course still takes the same arguments as before and accepts a different loop which is still used correctly.

Also note that I am returning the shutdown co-routine from the startup co-routine. This is because it needs to have access to some the variables the startup creates, namely `servers` and `handler`. An alternative would be to store these somewhere such as a on the `app` object, then the shutdown co-routine could be a seperate global level function that just takes the `app` as its only argument. Maybe the co-routines should even be returned by the app itself rather than be global functions...

**Comment by stonemonk** [comment]
And for my use case, the usage would be simple also.  Barebones:

```
        app = web.Application()
        # setup routes, etc...
        stopper, uris = await web.app_coroutine(app, host=host, port=port)
        # ...
        await stopper
```

**Comment by asvetlov** [comment]
Please take a look on `run_app` in master: the code is rewritten to use `AppRunner` and sites.
Now starting/stopping application is easy and straightforward.

The API is not documented yet, I'll do it up to aiohttp 3.0 release.
