### ISSUE TITLE
web.run_app can not support custom access log class.

### ISSUE THREAD

**Issue by codeif** [aio-libs/aiohttp#2615]
I want to use custom access_log_class, but web.run_app can not support this param.

## Your environment

aiohttp==2.3.6 for server.

**Comment by asvetlov** [comment]
I'm ok with adding `access_log_class` parameter but in master branch only.
Would you create a Pull Request?

**Comment by codeif** [comment]
I am creating a Pull Request.

**Comment by asvetlov** [comment]
Fixed by #2616
