### ISSUE TITLE
Proxy connection keep-alive

### ISSUE THREAD

**Issue by systocrat** [aio-libs/aiohttp#2617]
## Long story short
Hello- I am writing a web automation tool with aiohttp.
This tool uses proxies whose outbound IP address is different each connection (a superproxy).

When I tested making several requests at once every few seconds to a service that would echo "my" IP address to me, the IP address was always the same, suggesting to me that the proxy connections were being kept alive across multiple sessions.

I would like to turn this behavior off or find a workaround to prevent it if there is no explicit flag. Does such a thing exist? What can I do here?

## Your environment
CPython 3.6.3
aiohttp 2.3.6

**Comment by asvetlov** [comment]
Create `TCPConnector` with `use_dns_cache=False` and `force_close=True`

**Comment by systocrat** [comment]
Perfect, it works, thanks

**Comment by strongbugman** [comment]
@asvetlov @systocrat 
Hi, `force_close=True` works, but look this example, it is strange:
```
import asyncio

import aiohttp 
from aiohttp import helpers


async def main():
    proxy = 'http://localhost:8080'
    #s = aiohttp.ClientSession(connector=aiohttp.TCPConnector(force_close=True))
    s = aiohttp.ClientSession()
    url = 'http://httpbin.org:80'
    async with s.request('GET', url, proxy=proxy) as res:
        await res.read()
        print(res.status)  # print 200
        await res.text()
    async with s.request('GET', url) as res:
        await res.read()
        print(res.status)  # print 400, this request reuse last proxy connection(without proxy protocol, so get 400 response)
        await res.text() 
    await s.close()

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

I located to `ConnectionKey` class, and add proxy information to `ConnectionKey`:
```
ConnectionKey = namedtuple('ConnectionKey', ['host', 'port', 'ssl', 'proxy'])
# or ConnectionKey = namedtuple('ConnectionKey', ['host', 'port', 'ssl', 'proxy_host', 'proxy_port'])
class ClientRequest:
...
    @property
    def connection_key(self):
        return ConnectionKey(self.host, self.port, self.is_ssl(), self.proxy)
...
```
Then the code works fun, aiohttp will reuse proxy connections in right way, but is it right and safe way?
