### ISSUE TITLE
Default access log format tries to include Referer header but spells it correctly and thus it doesn't work 

### ISSUE THREAD

**Issue by EdRowe** [aio-libs/aiohttp#2633]
The default access log format attempts to output the Referer HTTP request header, referring to it as "Referrer". The latter is the correct spelling of the _word_, but the inventors of the _header_ misspelled it as "Referer". To make this work as intended, the LOG_FORMAT and the logging docs (which show the default log format) should be updated to use the misspelled version of the word. 

```LOG_FORMAT = '%a %t "%r" %s %b "%{Referrer}i" "%{User-Agent}i"'```
vs
```LOG_FORMAT = '%a %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"'```

The docs for the default log format also do not match the actual default log format in that it shows %l and %u which don't actually exist and %t which doesn't appear to be in the default log format.

**Comment by asvetlov** [comment]
Thanks for report.
