### ISSUE TITLE
aiohttp.helpers.AccessLogger too difficult to extend

### ISSUE THREAD

**Issue by syrkuit** [aio-libs/aiohttp#2634]
Need to extend what can be logged, subclassing AccessLogger seems like the right thing to do, but couldn't get it working. Ended up with an ugly hack.

subclassing AccessLogger and adding _format_X static classes should be good enough or close to good enough, but is impractical:
- compile_format() refers to AccessLogger to find the format methods, and will not find any added to the subclass
- LOG_FORMAT also needs to be updated
- LOG_FORMAT_MAP adds complexity that I failed to understand. It seems completely unused. Seems unused in the end, the "extra" parameter when logging is pointless? Got me wondering if it was an attempt to not use %s but named arguments in the format string, but gave up. I probably missed something here. I should've looked at the tests early, now I'm out of time for today :/

**Comment by hellysmile** [comment]
Hey, what about just 

http://aiohttp.readthedocs.io/en/stable/logging.html?highlight=accesslogger

```python
from aiohttp.abc import AbstractAccessLogger

class AccessLogger(AbstractAccessLogger):

    def log(self, request, response, time):
        self.logger.info(f'{request.remote} '
                         f'"{request.method} {request.path} '
                         f'done in {time}s: {response.status}')
```

**Comment by syrkuit** [comment]
ah yes, here is the doc I was looking for and missed.

Thanks!
