### ISSUE TITLE
Unclosed client session Error in aiohttp.request

### ISSUE THREAD

**Issue by soulomoon** [aio-libs/aiohttp#2635]
## Long story short

using aiohttp.request from the example in [document](https://docs.aiohttp.org/en/stable/client_reference.html#basic-api) emit (Unclosed client session) error

## Steps to reproduce

```python
import aiohttp
import asyncio

async def fetch():
    async with aiohttp.request('GET', 'http://python.org/') as resp:
        assert resp.status == 200
        print(await resp.text())

if __name__=="__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(fetch())
```

## Your environment
python 3.6.3
Darwin
aiohttp==2.3.7

**Comment by asvetlov** [comment]
This is well-known behavior, fixed in aiohttp 3.0.
Cannot be backported -- the fix is not 100% backward compatible.

P.S.
Why do you recreate a session every time? If you need slowdown your program -- `sleep()` should be enough.

**Comment by soulomoon** [comment]
@asvetlov Thank you for the reminder , now I use ClientSession in my code now, but 
Probably should state that in the document too? It would be really confusing for those who are trying out examples from the document.

**Comment by asvetlov** [comment]
Is note from https://docs.aiohttp.org/en/stable/client.html#make-a-request not enough?
If it is -- please feel free to make Pull Request with documentation update.
