### ISSUE TITLE
UrlDispatcher error during constructing of url with regex parts

### ISSUE THREAD

**Issue by imbolc** [aio-libs/aiohttp#264]
```
>>> from aiohttp.web import UrlDispatcher
>>> disp = UrlDispatcher()
>>> disp.add_route('GET', '/{num:^\d+}', lambda x: x, name='name')
<DynamicRoute 'name' [GET] /{num:^\d+} -> <function <lambda> at 0x7f0223131840>
>>> disp['name'].url(parts={'num': '1'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/imbolc/.pyenv/versions/3.4.1/lib/python3.4/site-packages/aiohttp/web.py", line 1226, in url
    url = self._formatter.format_map(parts)
ValueError: Invalid format specifier



```

**Comment by fafhrd91** [comment]
@asvetlov stop making one change releases. it doesnt make sense right now.

**Comment by imbolc** [comment]
@fafhrd91 what is bad? At least I don't need to change pip requirements from `aiohttp` to `git+...`.

**Comment by fafhrd91** [comment]
release every couple days seems like spam. and do you have gcc and cython on your production servers?

**Comment by imbolc** [comment]
Yes, I do. But I don't think, I should to update my production servers for
each release :)

**Comment by asvetlov** [comment]
From my perspective making a bugfix release as soon as bug has fixed makes
no harm.

But, if you don't like it, I can wait for next month for new update.

On Thu, Jan 29, 2015 at 11:00 PM, Imblc notifications@github.com wrote:

> Yes, I do. But I don't think, I should to update my production servers for
> each release :)
> 
> On Fri, Jan 30, 2015 at 3:55 AM, Nikolay Kim notifications@github.com
> wrote:
> 
> > release every couple days seems like spam. and do you have gcc and
> > cython
> > on your production servers?
> > 
> > > On Jan 29, 2015, at 12:52 PM, Imblc notifications@github.com wrote:
> > > 
> > > @fafhrd91 https://github.com/fafhrd91 what is bad? At least I don't
> > > need to change pip requirements from aiohttp to git+....
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub <
> > > https://github.com/KeepSafe/aiohttp/issues/264#issuecomment-72101742>.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/KeepSafe/aiohttp/issues/264#issuecomment-72102148.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KeepSafe/aiohttp/issues/264#issuecomment-72103090.

## 

Thanks,
Andrew Svetlov
