### ISSUE TITLE
Aiohttp Client Unclosed session: using with

### ISSUE THREAD

**Issue by jtarang** [aio-libs/aiohttp#2643]
## Long story short

Aiohttp CleintSession : I am using it to get data off the web. Unclosed session warnings keep coming.

## Expected behaviour
No message should come since , there is a handler in the source to close the session if open.

## Actual behaviour

Messages are overloading the log files.
```python
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1051539b0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x104379278>, 12525.604936222)]']
connector: <aiohttp.connector.TCPConnector object at 0x1044ceba8>
```

## Steps to reproduce

[GIST](https://gist.github.com/jaytarang92/bc093f7ac18710944442f8d742da2d77) Click here to grab the example 
## Your environment
OSX: 10.12.3
Ubuntu: 16.14
Windows 10

Just run the script I have included and you will see .

Let me know if I am crazy too. Thanks.

If there is way to silence them that would work too. Only way I found was too `pass` the messages in aiohttp's sourc.

**Comment by strongbugman** [comment]
Maybe you should close the session by hand:
```
await session.close()
```

**Comment by asvetlov** [comment]
@6ugman is right

**Comment by thehesiod** [comment]
better to use a session context (with/async with)

**Comment by jtarang** [comment]
@thehesiod how so? 

@6ugman that won't do in my case . Since I create a session and use the session for all requests then close it.  If I do await session.close() it closes it immediately . At least in my current config.

**Comment by thehesiod** [comment]
@jaytarang92 something like this: https://gist.github.com/thehesiod/6bb9ec91d1334b019a0a0e024f2351f4  obviously there are a lot of ways you can do it depending on how you want to structure your code
