### ISSUE TITLE
Error with no stack trace

### ISSUE THREAD

**Issue by George3d6** [aio-libs/aiohttp#2644]
I'm running an aiohttp based server and occasionally I see the following error pop up:

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 271, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 295, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```

There's no trace relating it to my original code and I can't quite understand why this is happening.

Is this expected behavior ? What could be causing it ?

The code that I'm running is something along the lines of:

```
async def blah(request):
    # do stuff
    return web.Response(text="Got request")

app = web.Application()
app.router.add_post('/', blah)
web.run_app(app)
```

**Comment by socketpair** [comment]
1. `async def blah`
2. you defined POST handler, and seems you tried GET request.

**Comment by George3d6** [comment]
I send the data as:

`requests.post(endpoint, data={'data': to_send})`

And read it as:

`data = await request.post()` inside blah

Is there some other signature I should be using for post handlers ?

**Comment by asvetlov** [comment]
Your example snippet is literally works as expected.

Perhaps you have a silly error in your real code.

**Comment by mateuszdrwal** [comment]
i am getting the same error, with pretty much the same traceback:
```Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 231, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 297, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```
it seems to happen randomly, sometimes once, sometimes multiple times in a row, all at a times at which i would not expect any traffic to my server. i have no idea how to fix/debug this as it doesnt seem to have anything to do with my code

**Comment by asvetlov** [comment]
I suspect it is related to #2782:

**Comment by jeicoo** [comment]
I am experiencing this as well..

What client are you using to make request in your server? I am using `aiohttp` client.
