### ISSUE TITLE
Connections in TCPConnector pool will be held open indefinitely

### ISSUE THREAD

**Issue by alexmac** [aio-libs/aiohttp#2647]
## Long story short

We have an HTTP service (implemented in aiohttp) that makes outbound HTTP requests to other services that are hosted behind load balancers (AWS ALB). The TCPConnector is shared and so we take advantage of connection pooling from this service to the load balancer.

We see occasional cases where the connection is reset by the remote during an outbound request, we believe this is because the remote load balancer is resetting old connections even if they are actively being used (which seems reasonable if the connection is held open indefinitely)

## Expected behaviour

The TCPConnector should expose a timeout value that puts an upper bound on the lifespan of an underlying TCP connection after which the connection should be closed and a new one opened.

## Actual behaviour

The TCPConnector has a keepalive_timeout value, but this appears to be implemented as a client-side idle timeout, if the connector is repeatedly used (i.e. period of re-use is less than keepalive_timeout) then the connection will be held open indefinitely.

## Steps to reproduce

Here's a test case that makes repeated connections using the same TCPConnector - right now it makes requests every 2 seconds and the transport is never closed, if you alter the sleep between connections to exceed the keepalive_timeout then the transport will be closed each time

```
import aiohttp
import asyncio

class TestConnector(aiohttp.TCPConnector):
    async def _create_connection(self, req):
        print('_create_connection called')
        return await super()._create_connection(req)

    async def connect(self, request):
        con = await super().connect(request)
        print('connection {} using transport {}'.format(id(con), id(con.transport)))
        return con

async def test():
    connector = TestConnector(limit=1, keepalive_timeout=10)

    async with aiohttp.ClientSession(connector=connector) as client:
        n = 1
        while True:
            n += 1
            async with client.get('https://www.google.com') as r:
                print('get {}'.format(n))
                await asyncio.sleep(2)
            

asyncio.get_event_loop().run_until_complete(test())
```

**Comment by alexmac** [comment]
As a quick hack I implemented this TCPConnector wrapper - is this a viable work around until a real fix can be implemented? or is calling the close method within the connect method likely to lead to worse issues:

```
class TCPConnectorWithTimeout(aiohttp.TCPConnector):
    def __init__(self, *args, max_connection_lifetime=40, **kwargs):
        super().__init__(*args, **kwargs)
        self.__transports = WeakKeyDictionary()
        self.__max_connection_lifetime = max_connection_lifetime

    async def connect(self, request):
        while True:
            con = await super().connect(request)

            current_time = datetime.utcnow().timestamp()
            creation_time = self.__transports.get(con.transport, None)

            if not creation_time:
                self.__transports[con.transport] = current_time
            elif creation_time < (current_time - max_connection_lifetime):
                con.close()
                continue

            return con
```

**Comment by asvetlov** [comment]
HTTP request to other service can fail for too many reasons. Servers are not 100% reliable, network is not reliable at all.
Almost every robust system needs some kind of retry logic.
This task is out of aiohttp scope because retry logic is very domain specific. Some requests are safe for retrying, others are not.
Perhaps you need implementing retries **on top** of aiohttp instead hacking connector.

**Comment by fafhrd91** [comment]
I think this issue is reasonable. to solve this issue you need to reimplement connector which is not a good idea.

**Comment by alexmac** [comment]
@asvetlov I agree that such transport level issues can happen at any time, but the implementation right now makes it more likely that we'll be encountering this issue when using load balanced services that probably don't want very long lived connections.

I think I might actually work around this by simply discarding the whole tcp connector every N seconds

**Comment by asvetlov** [comment]
Yep, periodical session recreation should be enough.
I really don't dislike adding too many parameters to session/connector: it pollutes API with hard-to-describe options.
