### ISSUE TITLE
Implement client-side websocket

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#265]
The main idea is pretty simple:
1. `aiohttp.client` should have `ClientWebSocket` class and `start_ws_client` coroutine.
2. `start_ws_client` has very rough implementation in wsclient example: https://github.com/KeepSafe/aiohttp/blob/master/examples/wsclient.py#L22
3. But after websocket connection negotiation it should return `ClientWebSocket` instance
4. The class should look like `WebSocketResponse` https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web.py#L717 (have `ping()/pong()`, `send_xxx()` and `receive_xxx` functions etc. but the `ClientWebSocket` is _already started_ after creation.

See the snippet:

```
import aiohttp
import asyncio


@asyncio.coroutine
def go():
    ws = yield from aiohttp.start_ws_client('http://example.com/ws')
    print("Connected")
    try:
        resp = ''
        while True:
            ws.send_str("hello, " + resp)
            resp = yield from ws.receive_str()
            print(resp)
    except aiohttp.WSServerDisconnectedError:
        print("Disconnection")
```

**Comment by lorien** [comment]
@asvetlov Thanks! I'll start working on this.

**Comment by fafhrd91** [comment]
let's name coroutine `wsconnect()` or `ws_connect()`

**Comment by asvetlov** [comment]
+1 for `ws_connect()`

**Comment by fafhrd91** [comment]
closing #290
