### ISSUE TITLE
connector: Connection.detach() fails when calling BaseConnector._release_acquired()

### ISSUE THREAD

**Issue by chrthi** [aio-libs/aiohttp#2658]
## Long story short

A simple arguments mismatch in `connector.py`:
`Connection.detach()` calls `self._connector._release_acquired(self._protocol)`,
but `BaseConnector._release_acquired(self, key, proto)` expects two positional args.

## Expected behaviour

`Connection.detach()` works fine

## Actual behaviour
```
  File "/usr/lib/python3/dist-packages/aiohttp/connector.py", line 127, in detach
    self._connector._release_acquired(self._protocol)
TypeError: _release_acquired() missing 1 required positional argument: 'proto'
```

## Steps to reproduce
```python
import asyncio
import aiohttp
from yarl import URL

async def mwe():
    async with aiohttp.ClientSession() as session:
        req = aiohttp.ClientRequest("GET", URL('http://www.example.com/'))
        connection = await session.connector.connect(req)
        connection.detach()

loop = asyncio.get_event_loop()
loop.run_until_complete(mwe())
```

## Your environment

python3-aiohttp 2.3.6-1 (python3 3.6.4-1) on Debian buster, but affected line is still present in GitHub master.
No proxy.
aiohttp used as client, as shown in MWE above.

**Comment by Dreamsorcerer** [comment]
This method doesn't exist in current releases.
