### ISSUE TITLE
UrlDispatcher error during constructing of url with trailing slash

### ISSUE THREAD

**Issue by imbolc** [aio-libs/aiohttp#266]
It makes urls without trailing slash.It happened after fixing of regex error :)

```
>>> from aiohttp.web import UrlDispatcher
>>> disp = UrlDispatcher()
>>> disp.add_route('GET', '/hello/{name}/', lambda x: x, name='name')
<DynamicRoute 'name' [GET] /hello/{name} -> <function <lambda> at 0x7ffd8b47b840>
>>> disp['name'].url(parts={'name': 'foo'})
'/hello/foo'
```

**Comment by asvetlov** [comment]
Fixed in master. 
@fafhrd91 do you want to postpone a bugfix release for the issue?

**Comment by imbolc** [comment]
I'm really appreciated :)

**Comment by asvetlov** [comment]
:) Thanks for well-formed bug reports!

**Comment by fafhrd91** [comment]
@asvetlov 1-3 weeks between bug fix releases unless urgent fix. I'd prefer separate ticket for each release. Ticket and discussion for every major version change

**Comment by asvetlov** [comment]
Ok, sounds fine to me.

On Fri, Jan 30, 2015 at 6:51 PM, Nikolay Kim notifications@github.com
wrote:

> @asvetlov https://github.com/asvetlov 1-3 between bug fix releases
> unless urgent fix. I'd prefer separate ticket for each release. Ticket and
> discussion for every major version change
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KeepSafe/aiohttp/issues/266#issuecomment-72231705.

## 

Thanks,
Andrew Svetlov
