### ISSUE TITLE
if my handlers are in different file, my app gives 404 not found

### ISSUE THREAD

**Issue by Akshita6** [aio-libs/aiohttp#2671]
## Long story short

I was trying middlewares and was getting not found as coded by the middleware for the request even if the request was valid. Then I removed the middleware and tested if the request is working and it wasn't working. I am not sure what changed but AFAIR, these files were working. 
If I add back the handlers from `views.py` namely `index_view` and `subapp_view` back to `main.py`, the code works.

## Your environment

 
This is main.py

```
from aiohttp import web
import asyncio

app_routes = web.RouteTableDef()
subapp_routes = web.RouteTableDef()


def init():
    greet = web.Application()
    greet.router.add_routes(subapp_routes)

    app.router.add_routes(app_routes)

    app.add_subapp('/greet/', greet)
    web.run_app(app, host='127.0.0.1', port=8089)


async def shutdown(server, handler, app):
    server.close()
    await server.wait_closed()
    app.client.close() # db connection closed
    await app.shutdown()
    await handler.finish_connections(10.0)
    await app.cleanup()


loop = asyncio.get_event_loop()
app = web.Application(loop=loop)

serv_generator, handler, application = loop.run_until_complete(init())
serv = loop.run_until_complete(serv_generator)

try:
    loop.run_forever()
except KeyboardInterrupt:
    print(' Stop server begin')
finally:
    loop.run_until_complete(shutdown(serv, handler, application))
    loop.close()
print('Stop server end')
```

This is views.py

```
from aiohttp import web
from main import app_routes, subapp_routes

@app_routes.get('/')
async def index_view(request):
    return web.Response(text='index\n')


@subapp_routes.get('/{name}')
async def subapp_view(request):
    name = request.match_info.get('name', "Anonymous")
    txt = "Hello {}\n".format(name)
    return web.Response(text=txt)
```

**Comment by asvetlov** [comment]
1. Your code is not full: `import views` is missing.
2. Since you import `app_routes` and `subapp_routes` from `main.py` and perhaps import `views.py` from `main.py` back you have circular imports.

Or `import views` is just missing in your code maybe.

There is no aiohttp magic here, it is just standard Python behavior.

**Comment by Akshita6** [comment]
Tried `import views` too but didn't work. Also why is `import views` required here? I don't get any compiler error in the  above code.

**Comment by Akshita6** [comment]
The structure of the project is project->main.py and project->views.py

**Comment by asvetlov** [comment]
If you don't import module -- it is never executed, isn't it?
Let's stop the discussion, the question is not related to aiohttp

**Comment by Akshita6** [comment]
Solved it by moving the route decorators definition in views.py instead of defining term in main.py. Then in main.py, importing these decorators from views.
