### ISSUE TITLE
TLS Session Resumption with Tickets (RFC5077)

### ISSUE THREAD

**Issue by unixsurfer** [aio-libs/aiohttp#2673]
## Long story short

I would like to know if you plan to add support for TLS Session Resumption with Tickets (RFC5077) on the client side.

**Comment by asvetlov** [comment]
Sorry, I don't know how to work with SSL tickets in Python ssl API.
Any help with links to documentation and code examples is welcome.

**Comment by unixsurfer** [comment]
Your question made to realise that I may have asked the question to the wrong place. I've just searched for resumption in https://docs.python.org/3.6/library/ssl.html, and I found nothing. I guess I should open a ticket to python to add support for TLS session resumption with tickets.

TLS session resumption saves one SSL session handshake after the first SSL session. If you have RTT of 100ms between client and servers, then you will spend 200ms just to establish an SSL session to the server as an SSL session requires two handshakes. You can skip the second SSL handshake by resuming a previously established SSL session. There are two ways to use TLS session resumption, either with Session IDs or Tickets, the latter is the prefered way these days as it doesn't require to store on the server side a session for each client.

Please close this, and I am sorry for wasting your time.

**Comment by asvetlov** [comment]
No problem
