### ISSUE TITLE
Reimplement connection_lost handler cancellation

### ISSUE THREAD

**Issue by hellysmile** [aio-libs/aiohttp#2675]
## Long story short

New issue for https://github.com/aio-libs/aiohttp/issues/2098

Proposal is:

 * drop auto-cancellation for next major release 3.x
 * cancellation can be controlled by user by new `request` property, 
for example 
```python
async def handler(request):
    request.cancel_on_lost = False
```
As well on route level
```python
app.router.add_get('/', handle, cancel_on_lost=True)
```
Or even on application level
```python
app = web.Application(cancel_on_lost=True)
```

Default parameter for all ways should be `False`

https://github.com/aio-libs/aiohttp/blob/b348e0f47c8ad16f898fd0dffa00c814b259131e/aiohttp/web_protocol.py#L198 should check `request.cancel_on_lost` attribute

## Expected behaviour

Cancellation should be controlled by end user

## Actual behaviour

There is no way to disable cancellation

## Steps to reproduce

https://github.com/aio-libs/aiohttp/issues/2098

**Comment by Dreamsorcerer** [comment]
I don't the this particular API will be implemented. We've added an option to enable/disable globally, and as per the documentation, it is possible to use aiojobs.aiohttp.atomic to effectively disable on individual handlers.
