### ISSUE TITLE
Rewrite wrapping OsError/ssl.SslError as context managers

### ISSUE THREAD

**Issue by hellysmile** [aio-libs/aiohttp#2676]
## Long story short

https://github.com/aio-libs/aiohttp/blob/master/aiohttp/connector.py#L796

* is hard to extend
* can be easily rewritten to context manager
* new custom manager can be configurable for connectors, for example just throw real exceptions (proposed default change for version 4.x future releases)
* can help a bit to organize https://github.com/aio-libs/aiohttp/pull/2539/files

## Expected behaviour

Exception wrapping for connectors should be configurable

## Actual behaviour

Exceptions wrapped without any way to manage

**Comment by Dreamsorcerer** [comment]
It's unclear what this is meant to mean. The linked line, at the time of the issue being reported, appears to have been something about sslcontext, and I don't understand how that has anything to do with exceptions or context managers.

Needs more info.
