### ISSUE TITLE
Adding multiple sub_apps yield too many routes but doesn't register.

### ISSUE THREAD

**Issue by HiImJulien** [aio-libs/aiohttp#2677]
## Long story short
In my application, I am using a strategy, where each resource gets it's own subapp,
prefixed with '/api/v1/'.

Routes are present, when iterating through 
`subapp.router.resources()`. More interestingly, a get route is appearing twice.
(registered 4 routes; 5 appearing when iterating through).

Apparently the router seems only to find the routes of the subapp, that got registered first.

## Expected behaviour
Routes should be found, regardless of the sequence of their registration.

## Actual behaviour
The routes, registered by the subapplication are not found, making the whole application yield "404 Response".
```python
instance = aiohttp.web.Application()
instance.add_subapp('/api/v1', subapp_1)
instance.add_subapp('/api/v1', subapp_2)
```

Routes of subapp_1 are being found.
Switching the order, make the routes of subapp_2 available, but those of subapp_1 unavailble; i.e. like this
```python
instance = aiohttp.web.Application()
instance.add_subapp('/api/v1', subapp_2) # Now the routes of subapp_2 are available
instance.add_subapp('/api/v1', subapp_1) # but cannot resolve routes of subapp_1
```

## Steps to reproduce

Register multiple sub applications.

## Your environment
macOS High Sierra
Version 10.13.2

Aiohttp Version: 2.3.8 (installed in venv)
Running Python 3.6.4

**Comment by asvetlov** [comment]
Sorry, I don't follow.
Can you provide a minimalistic but full example to demonstrate your problem?

**Comment by HiImJulien** [comment]
Sorry, I guess my way to phrase things yesterday was quite, strange, indeed.

For my web application I use following approach:
```python
instance = aiohttp.web.Application()
resourceA.Controller(instance)
resourceB.Controller(instance)
```

The `Controller`-classes are derived from `aiohttp.web.Application()` and are nearly identical to the following snippet:
```python
import aiohttp.web
from aiohttp.web import route

class Conroller(aiohttp.web.Application):
    def __init__(self, parent: aiohttp.web.Application):
       super().__init__()
       
       self.router.add_routes([
           route('GET', '/some_route/', self.some_route_handler)
       ])

       if parent is not None:
           parent.add_subapp('/api/v1/', self)
```

Both controllers constructors are built up this way, only differing in the routes they register.

However, the problem is, that only the routes of the sub-application registered first are available, i.e.
```python
instance = aiohttp.web.Application()
resourceA.Controller(instance) # <- Routes of resourceA.Controller are now available
resourceB.Controller(instance) # <- Routes of resourceB.Controller are not available, yielding a HTTP 404 trying to reach them
```
When switching the order to the following, causes also that only one controllers routes are available.
```python
instance = aiohttp.web.Application()
resourceB.Controller(instance) # <- Now the routes of resourceB.Controller are available
resourceA.Controller(instance) # <- Routes of resourceA.Controller are not avaible on the contrary :-(
```

I tried to do some debugging (altough I am new to aiohttp and asynchronous io altogether). In order to verify, that all routes are being registered correctly, I iterated over every resource like this:
```python
    instance = aiohttp.web.Application()
    resourceA.Controller(instance)
    resourceB.Controller(instance)

    for route in instance.router.resources():
        print(route)
```

Judging by the output, all routes are present.

__Regarding routes that are present twice (as specified in original issue above):__
Let's pretend, that resourceA registers a get route like this
```

class Controller(aiohttp.web.Application):
    def __init__(self, parent):
        super().__init__()

        self.router.add_routes([
            route('GET','/some_route/{id:\d}', self.some_handler)
        ])

        if parent is not None:
            parent.add_subapp('/api/v1/', self) # Assume, that parent is not None here.

    @staticmethod
    async def some_handler(request: aiohttp.web.Request):
        return aiohttp.web.Response()
```

If we were to loop over the resources registered to the main application (`instance`), I'd get the following result:
> <DynamicResource  /api/v1/some_route/{id}
> <DynamicResource  /api/v1/some_route/{id}

Which strongly suggests, that the very same route, that was added only once, is present twice in the main application's resource table. However, I am not sure, wether this is intended behavior.

**Comment by HiImJulien** [comment]
I've made an additional observation, I missed out on yesterday.
Carefully looking on what's being printed by 
```python
for route in instance.router.resources():
    print(route)
```

It seems that all subsequent `parent.add_subapp` calls do contain the prefix twice or more times. Let's stick with *resourceA* and *resourceB* from the previous comment. Pretend that resourceA registers a route '/resourceA/' and resourceB route '/resourceB/'. Both classes use the same prefix '/api/v1/'.
This what I'd get as an output:
> <PlainResource  /api/v1/resourceA
> <PlainResource  /api/v1/api/v1/resourceB

Trying to access resourceB via */api/v1/api/v1/resourceB* apparently works (i.e. trying to access via [Insomnia](insomnia.rest)). However, it initially intended, that resourceB is available via */api/v1/resourceB* instead of the former.

When switching the order, in which the sub-applications are registered, the same effect can be observed on the routes, that we're added second.

Here again, is this intended behavior of aiohttp or a bug?

**Comment by asvetlov** [comment]
Sorry for long silence.

Please correct me if I'm wrong: you are trying to add 2 different subapps under the same prefix, right?
It sounds very weird to me.

**Comment by HiImJulien** [comment]
Haha no worries, glad you replied at all 👍 

Back then, I used to have one 'Application' per Controller (i.e. Resource), which seemed, due to my lack of experience, the way to go.
Now I just register all route handler against one 'Application', which has the prefix inside of it.

**Comment by asvetlov** [comment]
Good

**Comment by achimnol** [comment]
Maybe my PR #2756 could help you.
