### ISSUE TITLE
Inconsistent routes on subapps.

### ISSUE THREAD

**Issue by HiImJulien** [aio-libs/aiohttp#2678]
## Long story short
Not sure whether this is related to my previous issue, #2677 

My backend currently consists of 3 `aiohttp.web.Application`-instances:

```python
def main():
    instance = aiohttp.web.Application()
    app_1 = app_1.Controller(instance)
    app_2 = app_2.Controller(instance)
```

Where as the controllers work by the following scheme:
```python
    class App_1(aiohttp.web.Application):

        def __init__(self, parent):
            super().__init__()
            self.add_routes([
                route('VERB', 'ressource1', ...),
                ...
            ])

            if parent is not None:
                parent.add_subapp('/api/v1/', self)


    class App_1(aiohttp.web.Application):

        def __init__(self, parent):
            super().__init__()
            self.add_routes([
                route('VERB', 'ressource1', ...),
                ...
            ])

            if parent is not None:
                parent.add_subapp('/api/v1/', self)
```
If I change the prefix in both classes, to include the ressource name I get following output (when iterating through the routers):
For App1:

> /api/v1/resource1
> /api/v1/resource1/{id:\d}

For App2:

> /api/v1/resource2/resource2
> /api/v1/resource2/resource2{id:\d}

I made sure, that all routes are built up by the same scheme; still routes are concatenated differently?

## Expected behaviour
All routes should be concatenated by the same scheme.

## Actual behaviour
Routes of sub application added secondly do use a different scheme for the routes.

## Steps to reproduce
See Long Story Short

## Your environment
macOS High Sierra
Version 10.13.2

Aiohttp Version: 2.3.8 (installed in venv)
Running Python 3.6.4

**Comment by HiImJulien** [comment]
Just to clarify, this issue doesn't mean, that #2677 is being solved. It is solely based on observation.

Also, excuse me, if the issue is trivial to solve. It has been a long night.

**Comment by asvetlov** [comment]
Cannot reproduce.
Please note: subapplication routes should be filed **before** adding the subapp into parent.

aiohttp 3.0 will raise explicit exception for it but 2.3 has not such check unfortunately.

**Comment by HiImJulien** [comment]
Yep, sorry was problem with PyCharm, apparently the IDE didn't remove all Python compiled files properly. Calling 
```bash
find . -name __pycache__ -type d -print0|xargs -0 rm -r --
```
did the trick.

Sadly, this didn't solve #2677 :-(
