### ISSUE TITLE
Request ignore X-Forwarded-Proto

### ISSUE THREAD

**Issue by demmsnt** [aio-libs/aiohttp#2680]
## Long story short

I use https for my project but i see http in self.request.scheme.

In nginx i describe proxy_set_header X-Forwarded-Proto $scheme;

in self.request headers i see  'X-Forwarded-Proto': 'https'

Unfortunately I did not find where the request points X-Forwarded-Proto to like X-Forwarded-For  (also did not find it).

I use Ubuntu 16.04 and nginx.

**Comment by asvetlov** [comment]
Did https://docs.aiohttp.org/en/stable/web.html#deploying-behind-a-proxy work for you?

**Comment by demmsnt** [comment]
Yes i use scheme=self.request.headers.get('X-Forwarded-Proto', 'http') now. But this surprised me. Excuse for troubling
