### ISSUE TITLE
Head doesn't follow redirects by default but get does

### ISSUE THREAD

**Issue by pcolmer** [aio-libs/aiohttp#2684]
## Long story short

The documentation says that the default behaviour of the library when fetching URLs is to follow redirects (up to the defined redirect maximum). This doesn't seem to be the case - it is true if the fetch is a GET but it is not true if the fetch is a HEAD.

This is important because it isn't clear in the documentation that HEAD behaves differently. If it should behave differently, the documentation needs improving. If HEAD should behave the same as GET with regards to following redirects, this is a bug.

## Expected behaviour

Trying to GET a URL that returns a redirect follows that redirect. Trying to HEAD that same URL should also follow the redirect.

## Actual behaviour

Unless `allow_redirects=True` is explicitly specified, HEAD returns the redirect status rather than the status of following the redirect.

## Steps to reproduce

    import aiohttp
    import asyncio

    async def fetch(session, url):
        async with session.head(url) as response:
            return response.status, response.url

    async def fetch_all(session, urls, loop):
        results = await asyncio.gather(
            *[fetch(session, url) for url in urls],
        )

        for ret in results:
            print("status: %s url: %s" % (ret[0], ret[1]))
        return results

    if __name__ == '__main__':
        loop = asyncio.get_event_loop()
        urls = ['http://www.linaro.org/this-doesnt-exist']
        with aiohttp.ClientSession(loop=loop) as session:
            loop.run_until_complete(fetch_all(session, urls, loop))

## Your environment

aiohttp (client) - 2.3.9
OS - Ubuntu 16.04
No proxy server

**Comment by asvetlov** [comment]
The behavior is mimic to `requests` library: it disables redirect for HEAD on default.

Documentation explicitly mentions it: https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.head
