### ISSUE TITLE
Worker is broken with latest Gunicorn

### ISSUE THREAD

**Issue by mrdon** [aio-libs/aiohttp#269]
With Gunicorn 19.2.0, the aiohttp.worker.GunicornWebWorker and Application needs a few patches:
- Make Application callable as Gunicorn will error out if it isn't.  It doesn't seem to matter what **call** does or returns.
- The debug configuration setting doesn't exist any longer.  You'll get this:
  File "/home/mrdon/dev/tmp/foo/venv/lib/python3.4/site-packages/aiohttp/worker.py", line 43, in make_handler
    debug=self.cfg.debug,
  File "/home/mrdon/dev/tmp/foo/venv/lib/python3.4/site-packages/gunicorn/config.py", line 58, in **getattr**
    raise AttributeError("No configuration setting for: %s" % name)

Workarounds:
- Create a MyApplication(web.Application) class that defines a **call** function that is a no-op
- Change config.py:43 to debug=False, though clearly that is just a hack.

**Comment by asvetlov** [comment]
Fixed in benoitc/gunicorn#977

**Comment by fafhrd91** [comment]
I'd like to work on callable

**Comment by asvetlov** [comment]
@fafhrd91 ok, that's up to you.

**Comment by fafhrd91** [comment]
fixed
