### ISSUE TITLE
Discourage inheritance from some aiohttp classes

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2691]
In first line I see `web.Application` and `ClientSession`.
If user want to extend functionality -- I'd like to encourage aggregation, not inheritance.

It could be done easy by adding `__subclass_init__` thunder method, the method should generate a warning (`UserWarning` maybe).
The method is not called by Python 3.5 (but not generates a error too), on Python 3.6+ everything should work fine. Who cares about Python 3.5?

**Comment by HiImJulien** [comment]
Why would you prefer aggregation over inheritance in the special case of `web.Application`?

It seems to be a viable design decision, when creating simple applications. It helps to structure it.

**Comment by asvetlov** [comment]
It seems not.
1. Inheritance from Application pollutes both namespace: it adds user names for base application, application attributes  from future versions of aiohttp may clash with user ones.
2. `web.Application` is not designed as base class with overriding virtual methods in children. All inversed control flows are intentionally implemented as signals and registered callbacks, not overridden methods.
3. Nothing prevents building a new custom class with `web.Application` attribute, it makes roles and responsibilities clear and straightforward.

**Comment by asvetlov** [comment]
You can push the reference to your aggregating instance into the application as `app['MY_KEY'] = aggregator`, isn't it?

**Comment by eigenein** [comment]
I guessed that you will propose that solution, but of course I wanna argue. :)

So looking at it we have two objects referencing each other, just because inheritance is discouraged:
- `assert foo.app == app`
- `assert app['foo'] = foo`
- `assert request.app['foo'] is foo`

Which is a viable solution of course, but don't you find it to be a not-so-good OOP design?

Not to say, it breaks static type checking because tools don't know what is `app['foo']` whereas subclassing does allow annotating a custom attribute.

**Comment by aparamon** [comment]
@asvetlov 
In tests we use rewriting of netloc to always access tested service by canonical address, regardless if test is run against localhost or remote service:
````py
class AsyncTestSession(aiohttp.ClientSession):
    """
    Rewrites request netloc (host:port) and prepends base_path.
    """

    def __init__(self, netloc, base_path='', *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.netloc = netloc
        self.base_path = base_path

    def _request(self, method, url, *args, **kwargs):
        scheme, netloc, path, params, query, fragment = urllib.parse.urlparse(url)
        if path:
            path = '/'.join((self.base_path, path.lstrip('/')))
        url = urllib.parse.urlunparse((scheme, self.netloc, path, params, query, fragment))
        return super()._request(method, url, *args, **kwargs)
````
We store `netloc` and `base_path` attributes for logging and debugging. What is considered the appropriate solution to avoid `DeprecationWarning` and future breakage?
