### ISSUE TITLE
Errors installing on 3.7 beta

### ISSUE THREAD

**Issue by drpoggi** [aio-libs/aiohttp#2704]
When trying to install into a virtualenv running the python3.7 beta I get: 

`pip.exceptions.UnsupportedPythonVersion: idna-ssl requires Python '<3.7.0' but the running Python is 3.7 .0`. 

It looks like [the check](https://github.com/aio-libs/aiohttp/blob/master/setup.py#L69) for 3.7 in `setup.py` did not make it into the `2.3.10` files on PyPi. It *is* present in the `2.3.10` files on Github, however if you take a look at https://pypi.python.org/packages/c0/b9/853b158f5cb5d218daaff0fb0dbc2bd7de45b2c6c5f563dff0ee530ec52a/aiohttp-2.3.10.tar.gz#md5=0ad682f635a0392e26320b1ab7d6dd26 it is missing.

**Comment by asvetlov** [comment]
Build failure problem.
Why do you care about such early Python beta version?

**Comment by drpoggi** [comment]
I'm starting a new project and wanted to use PEP 567. It's not a big issue as I know there are ways to get the same thing on 3.6, but I ran into this so thought i'd report it.

**Comment by asvetlov** [comment]
Thanks for reporting.
As a workaround you can use aiohttp github master clone.
Please note: Python 3.7 is not 100% stabilized, minor API changes may happen in next two months

**Comment by drpoggi** [comment]
Thank you, I will keep that in mind, luckily it's a small toy project so anything breaking wouldn't be too serious :)
