### ISSUE TITLE
Proposal: change tracing signatures again

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2708]
@pfreixes sorry by touching the subject again but I'm striving to get the best before freezing the API.

Now signatures are `async def on_sig(session, ctx, data):...`
We can replace it with just `async def on_sig(data):...`, `session` and `ctx` will be available as `data.session` and `data.context`.

Opinions?

**Comment by pfreixes** [comment]
Im not against the changes 😉 , but do you think that its worth it? `data` has params that are coupled to a specific signal, meanwhile `session` and `context` are params that are part of the global scope. 

If at some point the global scope has to change, and a new first citizen class appears it would mean an enough breaking change for both, the server and the developer.

**Comment by asvetlov** [comment]
The proposal is not about possible future changes of global context but reducing amount of parameters passed to trace signal handler

**Comment by pfreixes** [comment]
If you believe that they can be annoying for developers lets go for it. But IMHO having both of them explicit in the signature it's not a pain :)

**Comment by asvetlov** [comment]
I have no strong preference, that's why I want to discuss the change first.

**Comment by pfreixes** [comment]
what do you think @jettify ?

**Comment by kxepal** [comment]
I don't have strong opinion here, but separated things looks better and explicit rather than single bag of holding. `data` is quite too generic to expect something specific within.

**Comment by asvetlov** [comment]
Ok, let's keep existing signatures
