### ISSUE TITLE
Timeout is not respected sometimes.

### ISSUE THREAD

**Issue by Urahara** [aio-libs/aiohttp#2710]
So i'm running a [Quart](https://pgjones.gitlab.io/quart/) server, with methods that use [Scrapy](https://scrapy.org/) (for scraping content and then return to client) and [aiohttp](https://aiohttp.readthedocs.io/en/stable/) to perform  actions on site (make login, orders, etc) and [gunicorn](http://gunicorn.org) on top of that to manage workers and stuff.

When i receive a request from server first thing i do is to try perfom a login:

```python
async def perform_login(self):
    self.session = aiohttp.ClientSession(loop=self.loop, headers=self.headers)

    payload = {
        'usr' : 'test',
        'pwd' : '123'
    }

    response = None

    for attempt in range(5):
        logger.warning("Try #{}".format((attempt + 1))

        try:
            async with async_timeout.timeout(10):
                async with self.session.post('http://example.com', data=payload) as resp:
                    response = resp
                    break
        except Exception as e:
            # code ommited
```

I currently using 2 workers:
> gunicorn --worker-class quart.worker.GunicornWorker -w 2 server:app -b 0.0.0.0:8080 -t 600

My problem is: Strangely behavior occurs, from reading my code i try 5 times to perfom login with 10 seconds of timeout tolerance, but somethings this code is not respected. I seens like my task is lost and then minutes later i see on log "Try #2, Try #3..." even though I have configured these attempts to be second-rate, that lead my request task timeout on worker and don't do anything at all on site. 

What is most strange is that Scrapy run smootly (i'm use scrapy to crawl the same site that i perfom action later). I can't figure out what is wrong. But it seens that my task "freeze" on attempt to login.

Mostly part of time my code work 100% but sometimes this behavior occurs. Generally on rush hour, the site that i perfom action is not slow or anything. This is drives me nuts i love the lib and i can't find what i'm doing wrong.

**Comment by asvetlov** [comment]
I don't see anything wrong with your code.
Reproducible example can help a lot.

**Comment by Urahara** [comment]
@asvetlov Yeap, the problem is because i using scrapy: https://github.com/pgjones/quart/issues/6#issuecomment-363880367
