### ISSUE TITLE
No content

### ISSUE THREAD

**Issue by Behoston** [aio-libs/aiohttp#2711]
## Long story short

I'm trying to fetch RSS but in aiohttp response there is no content. It works with curl and python requests.

## Expected behaviour

response with content 

## Actual behaviour

response without content 

## Steps to reproduce
```python
import aiohttp
import asyncio
import requests

URL = 'https://menorca.info/feed.rss'


async def main_aio():
    async with aiohttp.ClientSession() as session:
        response = await session.get(URL)
        print('Aiohttp:', response.content)


def main_requests():
    response = requests.get(URL)
    print('Requests:', response.content)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main_aio())
    main_requests()
```

## Your environment

OS: Linux Mint 18.3 x64
Python: 3.6.3 (venv)
aiohttp: 2.2.5

**Comment by hellysmile** [comment]
```python 
print(await response.text())
```

**Comment by Behoston** [comment]
with await response.text() same behavior

**Comment by Behoston** [comment]
I've bumped aihttp version to 2.3.10 and nothing changed

**Comment by hellysmile** [comment]
show output please

**Comment by Behoston** [comment]
https://gist.github.com/Behoston/3c28f52517b0a6ded60f50ecdad737b4

**Comment by hellysmile** [comment]
This issue is related to https://github.com/aio-libs/aiohttp/issues/2277

aiohttp do not support h2 right now

**Comment by Behoston** [comment]
k, thx
