### ISSUE TITLE
3.0 release and async-timeout v2.0

### ISSUE THREAD

**Issue by popravich** [aio-libs/aiohttp#2724]
@asvetlov , 
async-timeout is currently v2.0 (for a long time), but you've pinned it to be `<2.0` in `install_requires`,
I guess its a typo, no?

https://github.com/aio-libs/aiohttp/commit/d3738070e854caabe59c0eb0352f027b9c69a450#diff-2eeaed663bd0d25b7e608891384b7298R68

**Comment by asvetlov** [comment]
Fixing

**Comment by asvetlov** [comment]
Fixed by 7f1be90b

**Comment by popravich** [comment]
@asvetlov , Tag release?

**Comment by asvetlov** [comment]
Sure.
Please wait for new build finishing

**Comment by popravich** [comment]
Ah, ok, I was just wondering
