### ISSUE TITLE
3.0.0 vs 3.0.1

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#2728]
Both [pypi](https://pypi.python.org/pypi/aiohttp/3.0.1) and the docs reference version 3.0.1 but github releases has no reference to 3.0.1, only 3.0.0. Also pypi body doesn't give any details on 3.0.1.

Before people get confused it might be worth explaining the difference somewhere.

**Comment by asvetlov** [comment]
github actually points on 3.0.1: https://github.com/aio-libs/aiohttp/releases/tag/v3.0.1
I didn't make release notes for 3.0.0 because the release had two minor bugs: #2724 and #2726 
3.0.1 is a quick bugfix and the version recommended for usage.

**Comment by samuelcolvin** [comment]
Ok thanks. Maybe I'm just being blind but that fact that v3.0.1 has title "aiohttp 3.0 release" could confuse people.

Maybe it would be worth changing the title or adding a prominent note to the body?

**Comment by asvetlov** [comment]
Added a note to the end of release message body
