### ISSUE TITLE
400 milliseconds delay using aiohttp

### ISSUE THREAD

**Issue by karamjaber** [aio-libs/aiohttp#2729]
## Long story short
I'm using hangups python module to build a solution that leverage messages between client and server.
Hangups uses aiohttp, and it seems like that in the following line in aiohttp it takes him up to 400 milliseconds to perform it:

`session.request(method,url,param=param,headers=headers, data=data,proxy=None)
`
Which eventually calls the function **_request** in **aiohttp\client** which calls **_wrap_create_connection** in **aiohttp\connector.py** .
The line that causes the delay is 

`return (yield from self_loop.create_connection(*args,**kwargs))
`

In **connector.py.**
## Expected behaviour

The maximum time to be less than 50 milliseconds

## Actual behaviour

The time it takes can reach 400 milliseconds

## Steps to reproduce

run send_message.py under hangups/exampels :  ( **https://github.com/tdryer/hangups** )

Put timer before and after the command 

`return (yield from self_loop.create_connection(*args,**kwargs))
`
**https://github.com/tdryer/hangups**

## Your environment

aiohttp version: 2.3.10
     
     IMPORTANT: aiohttp is both server framework and client library.
     For getting rid of confusing please put 'server', 'client' or 'both'
     word here.
     --> both

**Comment by asvetlov** [comment]
You see DNS resolving and TCP connection establishment timeout, aiohttp has no special sleeps for it.

The time can be huge, it depends on client node, server and network between.
I don't see how to fit in 50 ms if, say, your network is slow.

P.S.
After upgrading to aiohttp 3.0 you can use [client tracing][1] for timeout measurement, no need for patching aiohttp code anymore.

[1]: https://docs.aiohttp.org/en/stable/client_advanced.html#client-tracing

**Comment by karamjaber** [comment]
My network speed is over 100MBs which I assume is fast enough.
So, If I understand right, This is something related to DNS resolving and it can't be improved?

**Comment by webknjaz** [comment]
@karamjaber you could deploy a caching DNS in your network or locally next to the app. Have you tried analysing your network traffic by dumping it via tcpdump (viewable via Wireshark, for example)?

**Comment by karamjaber** [comment]
As far as I know, I think that Windows does a caching DNS and that's why I don't need to implement it by myself.

**Comment by asvetlov** [comment]
Anyway I'm going to close the issue.
Reports like "something is slow on my local machine" are helpless

**Comment by karamjaber** [comment]
Tried it on 3 different machines in 3 different networks.
Same behavior.

**Comment by webknjaz** [comment]
Still no traffic dump or at least a distilled reproducible example.
/fortune_teller_mode off
