### ISSUE TITLE
websocket fails to connect (except on localhost)

### ISSUE THREAD

**Issue by chuck1** [aio-libs/aiohttp#2734]
I run the following program

```
from aiohttp import web

async def websocket_handler(request):

    print('create websocket response')

    ws = web.WebSocketResponse()

    print('await prepare')
    await ws.prepare(request)

    print('prepare complete')

    async for msg in ws:
        print(msg)

    print('websocket connection closed')

    return ws

app = web.Application()

app.router.add_get('/ws', websocket_handler)

web.run_app(app, host='*', port=8080)
```

On another computer on my network, I open a javascript console and type

```
socket = new WebSocket("ws://192.168.1.101:8080/ws")
socket.onopen = function(e) {console.log(e);}
```

as expected the webserver reports:
```
======== Running on http://*:12000 ========
(Press CTRL+C to quit)
create websocket response
await prepare
prepare complete
```

but the onopen event on the client is never triggered and when I inspect the socket object, it sayings its still connecting. When I press ctrl+c on the webserver, the server closes normally and the onopen event on my client is called and then the socket immediately closes.

If I run the client on the same computer as the server and connect the websocket to localhost, everything works fine.

**Comment by asvetlov** [comment]
I very doubt if it is aiohttp problem.
BTW `host='*'` looks bogus.

**Comment by chuck1** [comment]
Yeah, that could be the case, how might I find out?

And I use host="*" to allow connection via any address that points to the host computer. Its not very secure, but this is just for testing. If you use host="127.0.0.1" you can only connect from the same computer.

**Comment by asvetlov** [comment]
`'0.0.0.0'` is for accepting on all IPv4 network interfaces.

**Comment by asvetlov** [comment]
Please take a look on https://github.com/aio-libs/aiohttp/blob/master/examples/web_ws.py

I've just checked it out -- everything works as expected when connecting from different host
