### ISSUE TITLE
Accept a coroutine in web.run_app

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2739]
The proposal allows to execute async IO before creating an application

**Comment by samuelcolvin** [comment]
How does this differ from on_startup?

Surely too many options will for the default way to run a server will confuse new users?

**Comment by asvetlov** [comment]
It follows new asyncio API: https://docs.python.org/3.7/library/asyncio-task.html#asyncio.asyncio.run

**Comment by webknjaz** [comment]
Sounds reasonable, I'd like to see the implementation draft for it.

**Comment by asvetlov** [comment]
The change is easy:
```
if asyncio.iscoroutine(app):
    app = await app
```
in very beginning of `run_app` function.

Any volunteer?

**Comment by webknjaz** [comment]
it's say try/except instead

**Comment by asvetlov** [comment]
```
try:
     app = await app
except TypeError:
     pass
```
looks really strange for me

**Comment by webknjaz** [comment]
but follows EAFP

**Comment by asvetlov** [comment]
It is not forgiveness/permission problem but overloading accepted types.
In static typed language it should be two functions with the same name but different parameter types.

**Comment by webknjaz** [comment]
yeah, and there's `functools.dispatch()` for that it Python

**Comment by asvetlov** [comment]
singledispatch actually - that's the problem

**Comment by chuck1** [comment]
would this feature allow you to *run* the app asynchronously? in other words an async equivalent of the aiohttp.web.run_app function?

**Comment by asvetlov** [comment]
@chuck1 no. `run_app` instantiates and closes an event loop instance.

But you can run an app from in a coroutine by three lines of code, 2 for initializing and 1 for shutdown: https://docs.aiohttp.org/en/stable/web_advanced.html#application-runners

**Comment by asvetlov** [comment]
Done by #2765
