### ISSUE TITLE
setup failed PosixPath' object has no attribute 'read_text'

### ISSUE THREAD

**Issue by ThePsyjo** [aio-libs/aiohttp#2741]
## Long story short

setup of version 3.0.1 fails with
`AttributeError: 'PosixPath' object has no attribute 'read_text'`
using Python 3.4 because pathlib.Path.read_text is introduced in Python 3.5.

https://docs.python.org/3/library/pathlib.html#pathlib.Path.read_text

## Expected behaviour

successful setup/update

## Actual behaviour

Exception
```
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-lpnp1yr9/aiohttp/setup.py", line 59, in <module>
        txt = (here / 'aiohttp' / '__init__.py').read_text('utf-8')
    AttributeError: 'PosixPath' object has no attribute 'read_text'
```

## Steps to reproduce

pip3 install aiohttp -U

## Your environment

Python 3.4.5

**Comment by asvetlov** [comment]
The minimal supported Python version is 3.5.3
