### ISSUE TITLE
Extremely slow download

### ISSUE THREAD

**Issue by khavishbhundoo** [aio-libs/aiohttp#2744]
## Long story short

It takes a huge amount of time to download files with my implementation.It currently take like 16 secs just to download 2 image from flickr

https://pastebin.com/2DXuzVtZ

P.S i haven't added exception handling at this point as i am trying to get it work first and then i will add the necessary code for it. the `download` and `fetch_content` is where the interesting bits are

Thanks in advance for the help

## Your environment 
Client
OS : Windows
Python version : 3.6.4
aiohttp server version: 3.0.1

**Comment by webknjaz** [comment]
This is not related to aiohttp.
You're doing blocking writes to file, which block ioloop. Try using smth like https://pypi.python.org/pypi/aiofiles instead.
