### ISSUE TITLE
GunicornWebWorker: worker_abort not called on WORKER TIMEOUT event

### ISSUE THREAD

**Issue by NotSqrt** [aio-libs/aiohttp#2753]
## Long story short

In #1420, code was added to call the `worker_abort` callback when receiving the `SIGABRT` signal.

It works correctly, except when the worker is *blocked by a sync call*, which is typically the case on `WORKER TIMEOUT` event.

Thus, it is hard to catch such timeouts and send an error report.

## Expected behaviour

* In its loop running every second, Gunicorn's `Arbiter.murder_workers` detects a worker that was silent for too long (`timeout` setting)
* the arbiter calls `self.kill_worker(pid, signal.SIGABRT)` which should be received by `GunicornWebWorker.handle_abort`
* the `worker_abort` callback defined in the gunicorn config file should be called

## Actual behaviour

* the arbiter calls `self.kill_worker(pid, signal.SIGABRT)` on a blocked worker, nothing happens immediately
* the arbiter runs its loop 1 second later, and calls `self.kill_worker(pid, signal.SIGKILL)`
* the `GunicornWebWorker` worker is killed without calling any callbacks

## Idea to fix

Around the following code:
 https://github.com/aio-libs/aiohttp/blob/74810c2f9fdd459fadde0ae3d43c06dcae58064f/aiohttp/worker.py#L136-L137

Using `signal.signal(signal.SIGABRT, self.handle_abort)` instead of `self.loop.add_signal_handler(signal.SIGABRT, self.handle_abort, signal.SIGABRT, None)` may help, but I don't know how important it is to keep the signal handling attached to the event loop.

## Steps to reproduce

server.py:
```python
from aiohttp import web
import time

async def index(request):
    time.sleep(5)
    return web.Response(text='Hello Aiohttp!')

app = web.Application()
app.router.add_get('/', index)
```

gunicorn_config.py:
```python
worker_class = "aiohttp.GunicornWebWorker"
accesslog = "-"
errorlog = "-"

def worker_abort(worker):
    worker.log.info("CONFIG: worker received SIGABRT signal")
```

* run `gunicorn server:app --timeout 2  --config gunicorn_config.py`
* open the / url
* `worker_abort` is not called despite the `WORKER TIMEOUT` event

## Your environment

* ubuntu 14.04
* python 3.6
* gunicorn (19.7.1), aiohttp (3.0.2) (both up-to-date)

Thanks !

**Comment by NotSqrt** [comment]
I hoped to have at least one of the gunicorn server hooks to be called : none of the hooks are called in that situation, neither `worker_abort` nor `worker_exit`.

I have to do some computations with `numpy` that I have to `await`, so I must have some blocking calls ..
Even with `spawn` from `aiojobs`, if I await the results, it is blocking.

Am I forced to use `request.app.loop.run_in_executor(None, func, *args)` ?

Thanks !

**Comment by asvetlov** [comment]
If your code performs CPU bound tasks like `numpy` computations -- you must run this code inside an executor.

`aiojobs` is for spawning asynchronous code, it doesn't prevent running blocking sync one or execute a task inside an executor.

I recommend switch on [asyncio debug mode](https://docs.python.org/3/library/asyncio-dev.html#asyncio-debug-mode) to catch all problematic places.

The worker is running in main thread, if it is blocked -- you are in problem.
I don't want using signal handlers directly, they are moved to event loop for a good reason.

**Comment by NotSqrt** [comment]
Thanks for your ideas !
