### ISSUE TITLE
python crashes on aiohttp import

### ISSUE THREAD

**Issue by badgh** [aio-libs/aiohttp#276]
I installed aiohttp (and also chardet, cython as required):

> pip install aiohttp
> Collecting aiohttp
>   Using cached aiohttp-0.14.4.tar.gz
>     Compiling aiohttp/_multidict.pyx because it changed.
>     Cythonizing aiohttp/_multidict.pyx
> Installing collected packages: aiohttp
>   Running setup.py install for aiohttp
>     building 'aiohttp._multidict' extension
>     C:\Anaconda3\Scripts\gcc.bat -mdll -O -Wall -IC:\Anaconda3\include -IC:\Anac
> onda3\include -c aiohttp/_multidict.c -o build\temp.win-amd64-3.4\Release\aiohtt
> p_multidict.o
>     C:\Anaconda3\Scripts\gcc.bat -shared -s build\temp.win-amd64-3.4\Release\aio
> http_multidict.o build\temp.win-amd64-3.4\Release\aiohttp_multidict.def -LC:\A
> naconda3\libs -LC:\Anaconda3\PCbuild\amd64 -lpython34 -lmsvcr100 -o build\lib.wi
> n-amd64-3.4\aiohttp_multidict.pyd
> Successfully installed aiohttp-0.14.4

Whenever i try to import aiohttp python crashes without any output in cmd:
![image](https://cloud.githubusercontent.com/assets/10549729/6318239/e6e24824-ba97-11e4-8977-9238cc36c142.png)

I tried to uninstall and reinstall everything, tried to install with different installers, but without success.
Can you, please, help?

**Comment by fafhrd91** [comment]
could you try to find and remove this file "aiohttp_multidict.pyd" and then try again

**Comment by badgh** [comment]
well i deleted my anaconda completely, reinstalled python without anaconda, now aiohttp works. However, i usually encounter this problem when using aiohttp: 'Attempt to decode JSON with unexpected mimetype'.

**Comment by kxepal** [comment]
> However, i usually encounter this problem when using aiohttp: 'Attempt to decode JSON with unexpected mimetype'.

This happens when you tries to read JSON from the response that didn't announce that it actually contains JSON data. That's not an error, but a warning to alert you that data here suddenly may not be a valid JSON.

**Comment by Arttii** [comment]
I also seem to have this problem for Anaconda with python 3.4. Not sure how to debug it to see what the issue is. The problem seems to lie in the cython compiled extensions. I am not sure why its not working though.

**Comment by Arttii** [comment]
I downloaded the devel version and ran setup build then copied the built files into site-packages and now it works. Mystical stuff I guess.

**Comment by asvetlov** [comment]
Looks like we need deploy Windows 32 and 64 bit wheels.

On Wed, Apr 22, 2015 at 6:03 PM, Arttii notifications@github.com wrote:

> I downloaded the devel version and run setup build then copied the built
> files into site-packages and now it works. Mystical stuff I guess.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KeepSafe/aiohttp/issues/276#issuecomment-95223826.

## 

Thanks,
Andrew Svetlov
