### ISSUE TITLE
Typo in documentation.

### ISSUE THREAD

**Issue by HuberTRoy** [aio-libs/aiohttp#2760]
## Long story short

I am trying to translate the documentation and found some typo in it. 

:blush:I want to help improve the documentation.

## Typo in documentation

1. I think the parameter(enable_cleanup_close) on [TCPConnector](https://aiohttp.readthedocs.io/en/stable/client_reference.html#aiohttp.TCPConnector.family) (please scroll up slightly) should be a bool not a tuple. Its default value is `False`.

2.  In the source [`class aiohttp.ClientProxyConnectionError`](https://aiohttp.readthedocs.io/en/stable/client_reference.html#aiohttp.ClientProxyConnectionError), `class aiohttp.ServerConnectionError` and `class aiohttp.ClientSSLError` respectively derived from [`ClientConnectorError`](https://aiohttp.readthedocs.io/en/stable/_modules/aiohttp/client_exceptions.html#ClientProxyConnectionError), `ClientConnectionError`, `ClientConnectorError`,  I cannot find `ClientConnectonError` that documentation written.  

3. If 2 is right, I think [`class aiohttp.ServerDisconnectedError`](https://aiohttp.readthedocs.io/en/stable/client_reference.html#aiohttp.ServerDisconnectedError), `class aiohttp.ServerTimeoutError`, `class aiohttp.ServerFingerprintMismatch` have the same [typo](https://aiohttp.readthedocs.io/en/stable/_modules/aiohttp/client_exceptions.html#ServerDisconnectedError).

4. I think the parameter (compress) on [WebSocketResponse](https://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.WebSocketResponse) should be a bool not a float.

5. I think the behavior of this [function (aihttp.web.route)](https://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.route) decided by its parameter `method` and in documentation it equal to [aiohttp.web.post](https://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.post)

6. In the [source](https://aiohttp.readthedocs.io/en/stable/_modules/aiohttp/web_urldispatcher.html#AbstractResource.resolve), the method `resolve` on the [`class aiohttp.web.AbstractResource`](https://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.AbstractResource) just accepted one parameter `request` and in the documentation it accepts two parameters (method, path).

7. In the [source](https://aiohttp.readthedocs.io/en/stable/_modules/aiohttp/web_response.html#StreamResponse.prepare) (please scroll up slightly) and the description in the documentation, property `last_modified` of `StreamResponse` has one parameter(value). In the [documentation](https://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.StreamResponse.last_modified) the parameter was lost.

8. In the [source](https://aiohttp.readthedocs.io/en/stable/_modules/aiohttp/web_response.html#Response) the parameters of `class aiohttp.web.Response` are `Response(*, body=None, status=200, reason=None, text=None,headers=None, content_type=None, charset=None)` and in the [documentation](https://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.Response) those are `Response(*, status=200, headers=None, content_type=None, charset=None, body=None, text=None)`

**Comment by asvetlov** [comment]
Would you create a pull request (or a set of PRs -- up to you) with requested changes?
It is the fast and convenient way to fix docs.

**Comment by HuberTRoy** [comment]
@asvetlov :blush: Have created.
