### ISSUE TITLE
pip installs old version

### ISSUE THREAD

**Issue by flip111** [aio-libs/aiohttp#2771]
python version: 3.5.2
pip version: 9.0.1

When i read the docs https://aiohttp.readthedocs.io/en/stable/ it says latest aiohttp version is 3.0.4 but when i issue the command `pip install aiohttp` pip installs 2.3.10 instead. Perhaps a new version of aiohttp needs to be pushed to the package repository?

**Comment by kxepal** [comment]
It always does: https://pypi.python.org/pypi/aiohttp/3.0.4

The problem is that modern aiohttp [requires](https://github.com/aio-libs/aiohttp/blob/master/setup.py#L119) Python 3.5.3+. pip sees that requirement and prevents you to get incompatible with your environment packages.

**Comment by flip111** [comment]
This was indeed the problem. I upgrade my python to 3.6.4 and it's fixed now. Not even sure how i got python 3.5.2 as i use ubuntu 16.04 which is stuck at 3.5.1 at the moment https://packages.ubuntu.com/xenial/python3 Thanks for the help
