### ISSUE TITLE
Adding dict interface to Response may accidentally break "if response:" check

### ISSUE THREAD

**Issue by hubo1016** [aio-libs/aiohttp#2772]
When solving #2246, a dict-like interface is added to Response (and StreamResponse). It is convenient, but there is a side effect: a response object was previous `True`, but now an empty response object is `False`. This is quite surprising for developers who are not reading the documents carefully, so I think warnings should be added to document that these kind of objects must be tested with `is None`.

Considering this piece of code:
```python
response = await call_middle_ware()
if not response:
    return await default_response()
else:
    return response
```

This piece of code call a middle ware, using its returning value as the final return value. If the middle_ware returns nothing, provides a default response.

But this breaks on 3.x because Response object is now a dict-like object, it contains a `__len__` method, so a newly created Response object is actually `False`. The code must be modified to:

```python
response = await call_middle_ware()
if response is not None:
    return await default_response()
else:
    return response
```

**Comment by asvetlov** [comment]
I don't think we can do anything here.
If your function returns either response or ``None`` (aiohttp itself has no such API calls BTW) you have check it for ``is None`` or ``is not None``.

**Comment by hubo1016** [comment]
@asvetlov Yes, I mean maybe we should provide more warnings about this change, since this is just released a few days ago. Some old code may appear to be working except middle-ware return values are always discarded. It is bad because some middle-wares are doing security checks, if this change accidentally bypass the security check, there will be serious security issues.

I think a special warning in the document and the next release note is necessary?

**Comment by asvetlov** [comment]
The change is a part of aiohttp 3.0 release (2 weeks old).
A time for release note update is gone, the ship has sailed.
But if you have a feeling what documentation update can help -- please make a Pull Request.

**Comment by hubo1016** [comment]
It looks like nothing could be done so I'm closing this.
