### ISSUE TITLE
set_tcp_cork not available on RHEL 6.2

### ISSUE THREAD

**Issue by ajdavis** [aio-libs/aiohttp#2777]
## Long story short

My MongoDB Driver, Motor, integrates with aiohttp. Starting in aiohttp 3.x, Motor's test suite has begun to fail on RHEL 6.2, apparently because set_tcp_cork is not implemented there.

## Expected behaviour

Tests that worked with aiohttp 2.x on RHEL 6.2 continue succeeding.

## Actual behaviour

```
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Stderr:
Error handling request
Traceback (most recent call last):
  File ".../python3.5/site-packages/aiohttp/web_protocol.py", line 376, in start
    resp = await self._request_handler(request)
  File ".../python3.5/site-packages/aiohttp/web_app.py", line 310, in _handle
    resp = await handler(request)
  File ".../python3.5/site-packages/aiohttp/web_urldispatcher.py", line 136, in handler_wrapper
    result = await result
  File ".../__init__.py", line 222, in __call__
    resp.set_tcp_cork(True)
AttributeError: 'StreamResponse' object has no attribute 'set_tcp_cork'
```

## Steps to reproduce

Run [any of the aiohttp integration tests in Motor's test suite](https://github.com/mongodb/motor/blob/6f8e7c138282a8ffeec0761480dcb6a2ede0043e/test/asyncio_tests/test_aiohttp_gridfs.py#L83).

## Your environment

RHEL 6.2, Python 3.5 or 3.6, aiohttp server.

**Comment by asvetlov** [comment]
Thanks for report.
Perhaps we don't need CORK support at all, adding it was my mistake.
But why do you need RHEL 6.2? It is from 2012, isn't it?

**Comment by asvetlov** [comment]
@ajdavis please double check your environment.
aiohttp 3.0 has no `set_tcp_cork` name in source code at all.

**Comment by ruslux** [comment]
Same problem

**ENVIRONMENT**
python 3.6
motor==1.2.1
aiohttp==3.0.0-b4

**CODE**
I was try interact with motor.AIOHTTPGridFS
```
async with self.client as session:
    async with session.get('{url}'.format(url="/fs/{filename}".format(filename=_filename))) as _response:
        self.assertEqual(200, _response.status)
        self.assertEquals('image/png', _response.headers['Content-Type'])

         _payload = await _response.text() # or content.read() or something else
        with open(img_path, 'rb') as file:
        self.assertEqual(type(file.read()), type(_payload))
```

**Comment by ajdavis** [comment]
Apologies! This is a Motor bug.

**Comment by asvetlov** [comment]
No problem

**Comment by ajdavis** [comment]
Motor had been using the APIs deleted in this change: https://github.com/aio-libs/aiohttp/pull/2612/ Maybe add the change to the aiohttp release notes?

**Comment by asvetlov** [comment]
It is here: "Drop access to TCP tuning options from PayloadWriter and Response classes"

**Comment by ajdavis** [comment]
Motor fix in progress: https://jira.mongodb.org/browse/MOTOR-202
