### ISSUE TITLE
Discourage ClientSession.requote_redirect_url changing

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2778]
The property setting affects all upcoming requests, which looks dangerous.

Better to make it read-only property at least with setting by client session constructor only.
Dropping the property in aiohttp 4.0 is even better: user always can pass `yarl.URL()` instance with `encoded=True`.

On transition period we should convert the `client.requote_redirect_url` into property.
Next step is varies upon our decision.
If we want to drop it: raise the warning and wait for aiohttp 4.0.
If we will decide to keep the functionality: 
- add `requote_redirect_url` parameters to both `ClientSession` constructor and `client.request` and family.
- raise a warning on modification of `requote_redirect_url` property.
- Finally disable the property modification in aiohttp 4.0

@fafhrd91 you are the author of these lines. What do you prefer?

**Comment by fafhrd91** [comment]
I would remove this property, but problem is you can not use "encoded=True" during redirect.
I am fine with property

**Comment by asvetlov** [comment]
Aha, got you.
If I understood correctly aiohttp internals should use `encoded=True` for redirection URLs.
This change will close all redirection problems, we don't need the property anymore (but will support it with a deprecation warning up to aiohttp 4.0)

**Comment by fafhrd91** [comment]
Do you remember, re-quoting for redirect was the reason for yarl in first place. In most cases we need re-quote, but sometimes we don’t

**Comment by asvetlov** [comment]
If we need it *sometimes* maybe better to add `requote_redirect_url=False` argument to `session.request`?
