### ISSUE TITLE
Speedup aiohttp web server

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2779]
The typical web handler looks like:
```
async def handler(request):
    ...  # do business logic
    return web.Response(text=..., content_type=...)

Unfortunately construction of `web.Response` is relative slow, `resp.prepare()` is even slower.
The code has too many checks for overlapping `content_type` with `headers['Content-Type']`, response length with `headers['Content-Length']`, HTTP chunk processing etc. etc.

We can speed up the situation if we assume that `web.Response` is constructed with well knows single text or binary data.

The suggestion is:
- Introduce `web.text_response()` and `web.bin_response()` like already present `web.json_response()`. Functions will just make `web.Response` instances on this first step. The main point is teaching people to use the new API.
- `web.Response` should be kept as is for backward compatibility.
- After that we can refactor our response classes hierarchy by making a `BaseResponse` as parent for `StreamResponse` and deriving private classes for binary and text responses from `BaseResponse`. Obviously `BaseResponse.prepare()` should exist, not sure about other API attributes.
- These private classes can do as minimal job as possible, they don't need to pass redundant checks for conflicting HTTP headers.

We should forbid the following HTTP headers in `web.text_response()` / `web.bin_response()`:
-  Connection
-  Keep-Alive
-  Trailer
-  Transfer-Encoding
-  Content-Length
-  Upgrade

The check for headers is quite expensive, let's do it in debug mode only (`loop.get_debug() is True` or `PYTHONASYNCIODEBUG=1`.

That's it.

Discussion is welcome.
PR for the first step (adding `web.text_response()` and `web.bin_response()`) is even more welcome.

**Comment by hubo1016** [comment]
I think it's OK to ignore any content-length and transfer-encoding settings for these responses, and always use the content-type specified by user if there is any. 

But I don't quite understand the speedup, I thought building the headers are always slower...

**Comment by spcharc** [comment]
the check for headers is quite expensive  <- I don’t understand
It’s just some comparing work and it’s fast. Looking up in a multidict is also fast

**Comment by asvetlov** [comment]
`response.prepare()` (and `response._start()`) take much longer time for simple responses in comparison as it should be.
I've created a gist for demonstration my steps to get profile results: https://gist.github.com/asvetlov/13295efdc1301bea241d7d35496e6f81
I hope you can reproduce snakeviz output by following the gist instructions (just snapshot in not informative because of interactive nature of the tool).
Actually it points to `StreamResponse._start()` and `StreamResponse.content_length`.
`StreamWriter.write_headers()` should be optimized too.

P.S.
Multidict could be much faster as well, see https://github.com/aio-libs/multidict/issues/97
But it is "good enough" for now.

**Comment by asvetlov** [comment]
Also `web.Response.__init__` is relative expensive.
My striving to support both `text` and `binary` responses in the same class was a mistake, as result we have too many checks in a constructor, just read the code.

**Comment by asvetlov** [comment]
How is json encoding related to the issue?

**Comment by hubo1016** [comment]
If it costs far less than json encode, it may not worth it.

**Comment by asvetlov** [comment]
Say again, why should I care about JSON encoding cost at all? 
JSON is not the onlly possible data structure for HTTP payload.
Following this way should I compare reponse sending with making a request to database as well? To which database? With what network connections? (The same is true for JSON BTW, encoding cost depends from incoming data size, types, JSON library and passed flags).

**Comment by hubo1016** [comment]
Take it easy... When optimising, we begin from the slowest part. I have tested the performance of aiohttp before, It is about 4000qps/CPU core, that is 250us per request. We must reduce 50us or more to make a difference. And if I remember It correctly, encoding of a JSON response takes about 10us. So I was wondering if doing checks are really a bottleneck now.

I don't have a testing environment with me until next week. I will look at your gist after that.

**Comment by kxepal** [comment]
@hubo1016 
You can always use third-party fast json library like ujson, rapidjson or else in-place of stdlib ones today. That's out of scope of overall aiohttp optimizations which you couldn't replace with something faster today.

**Comment by hubo1016** [comment]
@kxpal understood. I am just using it as a benchmark baseline, since different hardware produces very different numbers.

**Comment by asvetlov** [comment]
4000 RPS?
On my laptop I have 12000 RPS (using the single thread/process), see test files/params in gist above.

**Comment by thomaszdxsn** [comment]
8200 RPS on my laptop

**Comment by asvetlov** [comment]
@thomaszdxsn python debugger is off, access log is off, uvloop is used?

**Comment by thomaszdxsn** [comment]
https://gist.github.com/asvetlov/13295efdc1301bea241d7d35496e6f81

I take this gist, and not use cProfile.

> python debugger is off

what mean? I know python have a debugger call `pdb`

**Comment by asvetlov** [comment]
Sorry, my mistake -- should be "profiler".
Python uses the same low-level tracing API for both debugging and profiling.
The question was about using`python run_aiohttp.py 8080` to run server (no `-m cProfile` usage).

**Comment by thomaszdxsn** [comment]
yes, this is my command:

`$ pipenv run python run_aiohttp.py 8888`

wrk command:

`$ wrk -t 10 http://localhost:8888`

output:

```
Running 10s test @ http://localhost:8888
  10 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.17ms  358.79us   9.55ms   85.53%
    Req/Sec     0.86k    94.33     1.73k    81.85%
  85793 requests in 10.10s, 12.35MB read
Requests/sec:   8491.46
Transfer/sec:      1.22MB
```

another wrk:

`$ wrk -t8 -c200 -d30s --latency http://localhost:8888`

output:

```
Running 30s test @ http://localhost:8888
  8 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    26.25ms   20.63ms 263.13ms   94.34%
    Req/Sec     1.06k   272.09     1.44k    82.98%
  Latency Distribution
     50%   22.36ms
     75%   27.56ms
     90%   36.88ms
     99%  125.95ms
  252024 requests in 30.05s, 36.29MB read
  Socket errors: connect 0, read 3, write 0, timeout 0
Requests/sec:   8387.49
Transfer/sec:      1.21MB
```

my computer:

```
MacBook Pro 2015
2.7 GHz Intel Core i5
8 GB 1867 MHz DDR3
```

maybe reason is MacOS

**Comment by hubo1016** [comment]
@asvetlov ah, I didn't turn off the access log. I just use the default settings.

It makes sense if you are targeting 20k+qps. Shall we rewrite the whole class with Cython first? That might be easier.

**Comment by fafhrd91** [comment]
from my experience, biggest win in term of performance is related to ability to run async code in place
and return early if async function does not execute actual async operations or async result available immediately. at the moment aiohttp always run one task, I'd run handler as soon as full http message available in `data_received` callback and would start task only if handler returns not completed future.
that would require some low level generators code, but speedup should be significant, especially for benchmarks. we had such code on client side before 2.0, but I am not sure if it would work with async/await.

**Comment by asvetlov** [comment]
Good point

**Comment by pfreixes** [comment]
interesting @fafhrd91! Will be nice to see if the naive code path that has a completed response without needing a loop iteration exists right now in the current implementation, plenty of awaits that might be breaking the execution.

**Comment by asvetlov** [comment]
Are you volunteering for the task?

**Comment by novoxd** [comment]
Maybe. If it will be requirement for my current project (we have some performance issues against heavy application level ddos). This task is interesting for me, but I cant give any promises about my part in it because there are always some factors that may break promises.

**Comment by bdraco** [comment]
There has been a lot of improvement, but there is still a lot that could perform better

![resolve](https://github.com/user-attachments/assets/b6e5f475-52ec-4529-849a-9690e4730e4b)
![_handle_request](https://github.com/user-attachments/assets/3aa69357-505b-4290-a157-a1d1b1e14c6e)
![prepare](https://github.com/user-attachments/assets/c1a89c37-4812-42cd-9bc1-f639203350fa)

**Comment by bdraco** [comment]
Without profiler
% wrk -t 10 http://localhost:8080
Running 10s test @ http://localhost:8080
  10 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   237.23us   22.55us   1.12ms   84.31%
    Req/Sec     4.20k    56.62     4.54k    78.81%
  421797 requests in 10.10s, 63.56MB read
Requests/sec:  41763.44
Transfer/sec:      6.29MB

With profiler
% wrk -t 10 http://localhost:8080
Running 10s test @ http://localhost:8080
  10 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   454.83us   34.72us   1.99ms   86.39%
    Req/Sec     2.20k    32.69     2.32k    75.64%
  220865 requests in 10.10s, 33.28MB read
Requests/sec:  21867.62
Transfer/sec:      3.30MB

**Comment by bdraco** [comment]
I didn't expect add_app to be called every request

![add_app](https://github.com/user-attachments/assets/fbab1532-e99b-4c74-8293-90ce8756e7da)

**Comment by Dreamsorcerer** [comment]
> I didn't expect add_app to be called every request

I'm guessing that's UrlMappingMatchInfo.add_app(), which would make sense, because you get a new match info for each request and you want the app available on there. It just sets it as the current_app and adds it to an empty list (when routing through sub apps, then I think you end up with a list representing the chain of apps).

**Comment by bdraco** [comment]
There seem to be some more isinstance calls somewhere as well
![isinstance_before](https://github.com/user-attachments/assets/b40236f8-f4bc-4aff-bae1-445c09d9c37c)

![isinstance](https://github.com/user-attachments/assets/00437eb9-e860-40c0-b73f-cec93f10a0ae)

**Comment by bdraco** [comment]
It also looks like `content_length` is being called 2x as much as well in `web_response`

**Comment by bdraco** [comment]
Looks to be all little changes that added up.

- duplicate property calls
- use of `isinstance`
- checking for empty body
- checking to see if we should remove content length

**Comment by bdraco** [comment]
The web server performance isn’t something I look at very often as Home Assistant mostly switches to the websocket once the front page is loaded. 

I expect the client and the websocket performance is much better in newer versions.

I don’t see any obvious easy wins so something to look at when I get back from holiday

**Comment by bdraco** [comment]
3.10 - with pending PRs

Requests/sec:  48086.88

**Comment by bdraco** [comment]
3.10 - with pending PRs

Requests/sec:  43767.33

Closer to where 3.9.5 was but likely faster for many real world use cases since the benchmark is weighted towards the single static case

**Comment by Dreamsorcerer** [comment]
You mentioned isinstance() checks, I'm guessing a bunch of these are in asserts (mostly for type checking). How does the performance compare with `-O`?

**Comment by bdraco** [comment]
I’ll check when I get back to a laptop. I did a diff against 3.9.5 and found a few more places where a variable check was replaced with isinstance.  If I recall correctly isinstance is fast on a hit and much slower on a miss.

**Comment by bdraco** [comment]
It looks like the only new ones hit are from #6485 / #8938

**Comment by bdraco** [comment]
```diff
diff --git a/aiohttp/web_response.py b/aiohttp/web_response.py
index d2f056299..8a475f081 100644
--- a/aiohttp/web_response.py
+++ b/aiohttp/web_response.py
@@ -646,7 +646,10 @@ class Response(StreamResponse):
             return None
 
         if hdrs.CONTENT_LENGTH in self._headers:
-            return super().content_length
+            cl = self._headers[hdrs.CONTENT_LENGTH]
+            if cl is not None:
+                return int(cl)
+            return None
 
         if self._compressed_body is not None:
             # Return length of the compressed body
```

It looks like all the super super calls to get `content_length` can be sped up.  This should be safe since its already checking the content length exists in the headers.

Requests/sec:  46683.39

**Comment by bdraco** [comment]
https://github.com/aio-libs/aiohttp/pull/5197 introduced a small performance regression. 

We could avoid creating the cookie objects if there are no cookies which is a more likely case for a web response

**Comment by bdraco** [comment]
3.11 is now ~47233.87/s with the latest yarl

**Comment by bdraco** [comment]
> #5197 introduced a small performance regression.
> 
> We could avoid creating the cookie objects if there are no cookies which is a more likely case for a web response. Need to benchmark to see if its worth the change.
> 
> [aio-libs/aiohttp/pull/new/cookie_pref](https://github.com/aio-libs/aiohttp/pull/new/cookie_pref)
> 
> ```diff
> diff --git a/aiohttp/helpers.py b/aiohttp/helpers.py
> index 55b363003..555d53113 100644
> --- a/aiohttp/helpers.py
> +++ b/aiohttp/helpers.py
> @@ -914,14 +914,18 @@ class CookieMixin:
>      # slot themselves.
>      __slots__ = ()
>  
> +    _cookies: Optional[SimpleCookie]
> +
>      def __init__(self) -> None:
>          super().__init__()
>          # Mypy doesn't like that _cookies isn't in __slots__.
>          # See the comment on this class's __slots__ for why this is OK.
> -        self._cookies = SimpleCookie()  # type: ignore[misc]
> +        self._cookies = None
>  
>      @property
>      def cookies(self) -> SimpleCookie:
> +        if self._cookies is None:
> +            self._cookies = SimpleCookie()
>          return self._cookies
>  
>      def set_cookie(
> @@ -942,6 +946,8 @@ class CookieMixin:
>          Sets new cookie or updates existent with new value.
>          Also updates only those params which are not None.
>          """
> +        if self._cookies is None:
> +            self._cookies = SimpleCookie()
>          old = self._cookies.get(name)
>          if old is not None and old.coded_value == "":
>              # deleted cookie
> @@ -996,6 +1002,8 @@ class CookieMixin:
>          Creates new empty expired cookie.
>          """
>          # TODO: do we need domain/path here?
> +        if self._cookies is None:
> +            return
>          self._cookies.pop(name, None)
>          self.set_cookie(
>              name,
> diff --git a/aiohttp/web_response.py b/aiohttp/web_response.py
> index d2f056299..941df85fd 100644
> --- a/aiohttp/web_response.py
> +++ b/aiohttp/web_response.py
> @@ -383,7 +383,8 @@ class StreamResponse(BaseClass, HeadersMixin, CookieMixin):
>          version = request.version
>  
>          headers = self._headers
> -        populate_with_cookies(headers, self.cookies)
> +        if self._cookies:
> +            populate_with_cookies(headers, self._cookies)
>  
>          if self._compression:
>              await self._start_compression(request)
> ```

Turned out not to be significant

**Comment by Ok3ks** [comment]
A lot of time is spent in _prepare_headers(), here's the line by line profile of it

`
File: /Users/emmanuel/Code/aiohttp/aiohttp/web_response.py
Function: _prepare_headers at line 375

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   375                                               @profile
   376                                               async def _prepare_headers(self) -> None:
   377    102689       8898.0      0.1      1.8          request = self._req
   378    102689       8577.0      0.1      1.7          assert request is not None
   379    102689       9890.0      0.1      2.0          writer = self._payload_writer
   380    102689       8091.0      0.1      1.6          assert writer is not None
   381    102689       8034.0      0.1      1.6          keep_alive = self._keep_alive
   382    102689       8597.0      0.1      1.7          if keep_alive is None:
   383    102689      36084.0      0.4      7.1              keep_alive = request.keep_alive
   384    102689       8813.0      0.1      1.7          self._keep_alive = keep_alive
   385
   386    102689      31547.0      0.3      6.2          version = request.version
   387
   388    102689       7875.0      0.1      1.6          headers = self._headers
   389    102689      54548.0      0.5     10.8          populate_with_cookies(headers, self.cookies)
   390
   391    102689      10093.0      0.1      2.0          if self._compression:
   392                                                       await self._start_compression(request)
   393
   394    102689      10166.0      0.1      2.0          if self._chunked:
   395                                                       if version != HttpVersion11:
   396                                                           raise RuntimeError(
   397                                                               "Using chunked encoding is forbidden "
   398                                                               "for HTTP/{0.major}.{0.minor}".format(request.version)
   399                                                           )
   400                                                       if not self._must_be_empty_body:
   401                                                           writer.enable_chunking()
   402                                                           headers[hdrs.TRANSFER_ENCODING] = "chunked"
   403                                                       if hdrs.CONTENT_LENGTH in headers:
   404                                                           del headers[hdrs.CONTENT_LENGTH]
   405    102689       9507.0      0.1      1.9          elif self._length_check:  # Disabled for WebSockets
   406    102689      55916.0      0.5     11.1              writer.length = self.content_length
   407    102689      13966.0      0.1      2.8              if writer.length is None:
   408                                                           if version >= HttpVersion11:
   409                                                               if not self._must_be_empty_body:
   410                                                                   writer.enable_chunking()
   411                                                                   headers[hdrs.TRANSFER_ENCODING] = "chunked"
   412                                                           elif not self._must_be_empty_body:
   413                                                               keep_alive = False
   414
   415                                                   # HTTP 1.1: https://tools.ietf.org/html/rfc7230#section-3.3.2
   416                                                   # HTTP 1.0: https://tools.ietf.org/html/rfc1945#section-10.4
   417    102689      11371.0      0.1      2.2          if self._must_be_empty_body:
   418                                                       if hdrs.CONTENT_LENGTH in headers and should_remove_content_length(
   419                                                           request.method, self.status
   420                                                       ):
   421                                                           del headers[hdrs.CONTENT_LENGTH]
   422                                                       # https://datatracker.ietf.org/doc/html/rfc9112#section-6.1-10
   423                                                       # https://datatracker.ietf.org/doc/html/rfc9112#section-6.1-13
   424                                                       if hdrs.TRANSFER_ENCODING in headers:
   425                                                           del headers[hdrs.TRANSFER_ENCODING]
   426    102689      16783.0      0.2      3.3          elif (writer.length if self._length_check else self.content_length) != 0:
   427                                                       # https://www.rfc-editor.org/rfc/rfc9110#section-8.3-5
   428    102689      15609.0      0.2      3.1              headers.setdefault(hdrs.CONTENT_TYPE, "application/octet-stream")
   429    102689      68129.0      0.7     13.5          headers.setdefault(hdrs.DATE, rfc822_formatted_time())
   430    102689      12891.0      0.1      2.5          headers.setdefault(hdrs.SERVER, SERVER_SOFTWARE)
   431
   432                                                   # connection header
   433    102689      11914.0      0.1      2.4          if hdrs.CONNECTION not in headers:
   434    102689      10092.0      0.1      2.0              if keep_alive:
   435    102689      68461.0      0.7     13.5                  if version == HttpVersion10:
   436                                                               headers[hdrs.CONNECTION] = "keep-alive"
   437                                                       else:
   438                                                           if version == HttpVersion11:
   439                                                               headers[hdrs.CONNECTION] = "close"
`

**Comment by bdraco** [comment]
`   435    102689      68461.0      0.7     13.5                  if version == HttpVersion10:`

Thats a bit unexpected that the tuple compare is slow

**Comment by bdraco** [comment]
If there are no cookies we might be able to save time by guarding `populate_with_cookies` with an `if self.cookies:` ... assuming no cookies are the common case

`   389    102689      54548.0      0.5     10.8          populate_with_cookies(headers, self.cookies)`

**Comment by bdraco** [comment]
`rfc822_formatted_time` might be faster as a `f-string`. Would need to verify with `pyprof`

**Comment by bdraco** [comment]
3.11.2 Requests/sec:  59789.94

**Comment by bdraco** [comment]
![start](https://github.com/user-attachments/assets/81499f7c-8b94-4a8b-b091-2faa0f9d86c9)

I don't see many opportunities to optimize left.  I feel like we are close to being able to close this out, but there might be something else I'm missing so it would be good to get some more 👀 on it.

**Comment by bdraco** [comment]
Should look at that `_write` call in `write_eof` .... if `content-length` is set we shouldn't see another one

**Comment by bdraco** [comment]
Its expected since there is an `OK` payload

**Comment by bdraco** [comment]
```diff
diff --git a/aiohttp/web_response.py b/aiohttp/web_response.py
index 73063890f..a7c37c121 100644
--- a/aiohttp/web_response.py
+++ b/aiohttp/web_response.py
@@ -93,7 +93,7 @@ class StreamResponse(BaseClass, HeadersMixin):
         self._compression = False
         self._compression_strategy: int = zlib.Z_DEFAULT_STRATEGY
         self._compression_force: Optional[ContentCoding] = None
-        self._cookies = SimpleCookie()
+        self._cookies: Optional[SimpleCookie] = None
 
         self._req: Optional[BaseRequest] = None
         self._payload_writer: Optional[AbstractStreamWriter] = None
@@ -209,6 +209,8 @@ class StreamResponse(BaseClass, HeadersMixin):
 
     @property
     def cookies(self) -> SimpleCookie:
+        if self._cookies is None:
+            self._cookies = SimpleCookie()
         return self._cookies
 
     def set_cookie(
@@ -230,6 +232,9 @@ class StreamResponse(BaseClass, HeadersMixin):
         Sets new cookie or updates existent with new value.
         Also updates only those params which are not None.
         """
+        if self._cookies is None:
+            self._cookies = SimpleCookie()
+        else:
             old = self._cookies.get(name)
             if old is not None and old.coded_value == "":
                 # deleted cookie
@@ -277,6 +282,7 @@ class StreamResponse(BaseClass, HeadersMixin):
         Creates new empty expired cookie.
         """
         # TODO: do we need domain/path here?
+        if self._cookies:
             self._cookies.pop(name, None)
         self.set_cookie(
             name,
```

https://github.com/aio-libs/aiohttp/issues/2779#issuecomment-2461282412 should have skipped some of the pop operations if nothing set.

Can get another 2% out of it with the above

**Comment by Dreamsorcerer** [comment]
> I don't see many opportunities to optimize left.

My only question is whether the proposal in the original issue (i.e. basically replacing direct web.Response() instantiation with helper functions) is something we want to look at implementing, or will it not make a difference?

**Comment by bdraco** [comment]
Maybe `_prepare_headers` could be optimized a bit more, but I'm not sure its needed to split it. Would need to experiment a bit with it

**Comment by bdraco** [comment]
Profile above shows more time is spent in the tuple compares. https://github.com/aio-libs/aiohttp/issues/2779#issuecomment-2466308401

https://github.com/aio-libs/aiohttp/pull/9896 is a test to see if that makes a difference to unpack them

**Comment by bdraco** [comment]
Tried a few methods but nothing made it faster in a meaningful way.  All the time is spent in these 3 places 

<img width="376" alt="Screenshot 2024-11-14 at 10 08 38 PM" src="https://github.com/user-attachments/assets/01797d25-8814-4352-b112-dccd4799da30">
<img width="245" alt="Screenshot 2024-11-14 at 10 08 28 PM" src="https://github.com/user-attachments/assets/890578cd-8434-4e33-ae34-9eef48385010">
<img width="248" alt="Screenshot 2024-11-14 at 10 08 25 PM" src="https://github.com/user-attachments/assets/674431d1-68ec-45f1-8c22-35932a362d4b">

**Comment by bdraco** [comment]
and the bulk is really the time syscall to make the rfc822_formatted_time

<img width="314" alt="Screenshot 2024-11-14 at 10 11 09 PM" src="https://github.com/user-attachments/assets/e8395fe0-8820-4fee-bbe8-d1aab79a3ac9">

**Comment by bdraco** [comment]
I don't see a way to speed any of those up

The extra super() property call in https://github.com/aio-libs/aiohttp/blob/5ab2d47351dc83da925d7295af98ffcfa7c91fe4/aiohttp/web_response.py#L214 is likely why content_length is coming up as a bit slower

**Comment by bdraco** [comment]
even if we clean that all up a bit more its likely still less than everything we would get from https://github.com/aio-libs/aiohttp/issues/2779#issuecomment-2477770763

**Comment by bdraco** [comment]
I can't come up with anything to make it faster that doesn't significantly hurt readability or make the code much less dry, and definitely nothing worth that kind of trade off. Could benefit from a second set of eyes looking at the codspeed flame graphs

**Comment by bdraco** [comment]
> and the bulk is really the time syscall to make the rfc822_formatted_time
> 
> <img alt="Screenshot 2024-11-14 at 10 11 09 PM" width="314" src="https://private-user-images.githubusercontent.com/663432/386454436-e8395fe0-8820-4fee-bbe8-d1aab79a3ac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDU5NTgsIm5iZiI6MTczMTY0NTY1OCwicGF0aCI6Ii82NjM0MzIvMzg2NDU0NDM2LWU4Mzk1ZmUwLTg4MjAtNGZlZS1iYmU4LWQxYWFiNzlhM2FjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNDQwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDFmY2I5MzVjYWJiYTk3NjU0MWJhYzFmMGJkMWEyM2NlOGQwM2U5ZDZlMmMwYWU4OTI5MDhkMjllZjUxZDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d32QT34WLCZUaGeByh9zAPNo9pryenlsKWJ7hx081tw">

While that going to be painfully slow on older arm systems that have errata that prevents using the vdso call, on most modern linux systems its going to use vdso for time and its not that bad

**Comment by bdraco** [comment]
Resource.resolve shows up in the profile.. https://github.com/aio-libs/aiohttp/pull/9899 attempt to make it faster

**Comment by bdraco** [comment]
Maybe `Response.__init__` and `StreamResponse.__init__` could be optimized a bit more
<img width="707" alt="Screenshot 2024-11-14 at 11 24 28 PM" src="https://github.com/user-attachments/assets/4068da5b-9e37-4fc8-a795-b81e2db8616e">

**Comment by asvetlov** [comment]
Another interesting optimization would be in using https://pypi.org/project/hyperscan/ for route path search.
It could scan over all registered routes at once instead of looping.
The library support a limited set of CPU architectures, thus it should be optional.
Also, it doesn't provide an API for getting `match` object, thus it would require additional `re.pattern.match()` call for extracting match_info dict for variable patterns.
Good news, it seems that hyperscan supports unicode and could compile all regex patterns that we use in aiohttp.

**Comment by Dreamsorcerer** [comment]
> Another interesting optimization would be in using https://pypi.org/project/hyperscan/ for route path search.

Interesting. I would note that while you were away we did a big refactor in #7829. For an application with 5000 routes, this reduced route resolution from ~5s to ~100ms. So, we've already seen a substantial improvement on that front, though if there's more to be had, then great.

**Comment by Dreamsorcerer** [comment]
I think if @asvetlov agrees that the original proposal is not worth doing, then we can probably close this issue. If there are any more specific suggestions for optimisations anyone has, then a new issue can be opened for each suggestion (or just a PR).

**Comment by asvetlov** [comment]
Everything looks good now. 
Thank to everybody who took a part in working on it.
