### ISSUE TITLE
Provide a way to retrieve 5xx error codes

### ISSUE THREAD

**Issue by ramalho** [aio-libs/aiohttp#279]
I am testing an aiohttp client using the Mozilla vaurien proxy which produces random errors for testing (highly recommended!). Using aiohttp I get a ClientResponseError with a **context** reference to ServerDisconnectedError() but no error code or reason string. 

In contrast, using the requests package I get requests.exceptions.HTTPError exceptions and can verify the error code and reason.

**Comment by fafhrd91** [comment]
we chain all exceptions, you should get original exception from `__cause__`

**Comment by ramalho** [comment]
Thanks for you response. Yes, I actually can get the original exception from `__cause__` or `__context__`, and I get a ServerDisconnectedError() but no HTTP error code.

**Comment by fafhrd91** [comment]
ServerDisconnectedError() is for transport level exceptions, aiohttp doesnt have complete response from server yet. otherwise you would get proper `Response` object

**Comment by ramalho** [comment]
Thanks for the reply. What you say is interesting, but somehow the requests library manages to post an HTTP error for those cases as well. I test some sequential code using requests and asyncio code using aiohttp against the same server, and requests never fails to give me a 5XX errror. I'll investigate further.
