### ISSUE TITLE
Docs of from make_mocked_request still refer to FlowControlStreamReader

### ISSUE THREAD

**Issue by hynek** [aio-libs/aiohttp#2797]
The current docs at https://github.com/aio-libs/aiohttp/blob/master/docs/testing.rst are outdated, however I have no idea how to use StreamReader in testing since it's without any docs…

Could you provide an example on how to simple push a string into a mocked request? I know you want me to use the higher-level facilities but as mention in the other ticket, I cannot use them since they conflict with pytest-asyncio which is a essential to me.

**Comment by asvetlov** [comment]
I'll manage it, thanks for pointing out.

aiohttp test suite has examples of sending data through `make_mocked_request`, but they are too cumbersome maybe.

**Comment by hynek** [comment]
Maybe a test helper class with a StringStreamReader would be nice? I tried to use feed_data but it just hang so I gave up and monkey patched request.read because I’m terrible. ;)

**Comment by asvetlov** [comment]
It's strange that `feed_data()` didn't work for you, we use it in tests many times.
A reader-like helper initialized by bytes buffer is a good idea maybe but not very big improvement against `feed_data()` call.

**Comment by asvetlov** [comment]
Doc is fixed.
I suspect you had a hang because `pytest-asyncio` and `pytest-aiohttp` uses two different event loop instances.
pytest-aiohttp is going slowly to friend with pytest-asyncio but after cutting out Python<3.5.3 I can master something. Stay tuned.

**Comment by hynek** [comment]
Sounds great!
