### ISSUE TITLE
Querying aiohttp test_server with third party clients freezes

### ISSUE THREAD

**Issue by panovitch** [aio-libs/aiohttp#2799]
## Long story short

Hi all! 

I am trying to set up some tests that would query aiohttp test server with a 3rd party client (bravado in my case).

The example code would look something like this:

```
@pytest.fixture()
async def server(aiohttp_server) -> TestServer:
    app = create_app()
    server = await aiohttp_server(app, port=TEST_PORT)
    return server

async def test_get_all_bravado(self, server, headers):
    await server.start_server()
    response = swagger_client_sync.entity.getAll(
        _request_options={"headers": headers}).result()
    await server.close()
    assert response == []
```
## Actual behaviour

When I try to run this test, the execution freezes (pytest command execution never finishes).
The behavior is the same if I use another 3rd party client to query the test server, for example, `requests`.
If I use the aiohttp test client,  the test runs correctly.

## Your environment

aiohttp==3.0.5
asynctest==0.12.0
pytest==3.4.1
pytest-aiohttp==0.3.0

**Comment by asvetlov** [comment]
1. You should not call `await server.start_server()`, the server is started already.
2. `swagger_client_sync...` blocks event loop, aiohttp server has no chance to process swagger request. I suggest `loop.run_in_executor(swagger_client_sync.entity.getAll, ...)`
