### ISSUE TITLE
cannot change proxy

### ISSUE THREAD

**Issue by gpfei** [aio-libs/aiohttp#280]
ProxyConnector does not have a method to change proxy address. Thanks!

**Comment by asvetlov** [comment]
Do you really need that?
Maybe better to create new ProxyConnector with updated address?

**Comment by gpfei** [comment]
You know ... spider needs ;P
But if I want to use the same cookie, it will be a little inconvenient.
And I think multi-proxies support would be a nice feature.

**Comment by popravich** [comment]
I believe it is a case for custom `ProxyConnector`.
Otherwise we'll stuck on question how to switch between multiple proxies.

**Comment by fafhrd91** [comment]
@asvetlov @popravich do we need to do anything before 0.15 release or we just close it?

**Comment by asvetlov** [comment]
The issue is really about sharing cookies between connectors, not switching connector's host/port.
The task can be done on released aiohttp 0.14: connector.cookies is public read-write attribute.

**Comment by fafhrd91** [comment]
idea, we can extract something like CookieStorage and make it possible to pass cookies storage object as a constructor's parameter.

**Comment by asvetlov** [comment]
I think we need something like requests.Session which operates on Connector(s) internally. Maybe I'll try to implement something like that soon.
