### ISSUE TITLE
Whether `close()` in `ClientSession` should be a normal function?

### ISSUE THREAD

**Issue by HuberTRoy** [aio-libs/aiohttp#2800]
## Long story short

Before that I have a question:
I created a `ClientSession` outside coroutine and I got a warning "UserWarning: Creating a client session outside of coroutine is a very dangerous idea". And I read source  trying to figure out why it is a dangerous idea.  It seems just because `loop` is not running. (Why it is a dangerous idea that `loop` is not running?)

---

I created class
```
class MyAioClientSession(object):
    session = aiohttp.ClientSession()

    def __del__(self):
        self.session.close()        
    .....
```
When execute `__del__`, it will raise an exception of "RuntimeWarning: coroutine 'ClientSession.close' was never awaited". 
And in [source](http://aiohttp.readthedocs.io/en/stable/_modules/aiohttp/client.html#ClientSession.close) of `ClientSession` it seems do not have codes to `await`. In source of `TCPConnector`  and [source](http://aiohttp.readthedocs.io/en/stable/_modules/aiohttp/connector.html#BaseConnector.close) of `BaseConnector` are also not having codes to `await`. 

I have to written:
```
     ...
    def __del__(self):
        # copy from close() in ClientSession
        if not self.session.closed:
            if self.session._connector_owner:
                self.session._connector.close()
            self.session._connector = None        
```

## Expected behaviour

I want use `close()` in `__del__` to close underlying connector that `ClientSession` opened.
Could make two methods?
One for asynchronous method, another for normal method.

## Actual behaviour
```
..\seen\asrequests.py:107: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
2018-03-06 00:59:32 Unclosed client session
```

## Steps to reproduce
```
class MyAio:
    session = aiohttp.ClientSession()

    def __del__(self):
        self.session.close()

test = MyAio()
```

## Your environment
```
Windows 7 64bit
Python 3.5.4
aiohttp 3.0.6
```

**Comment by asvetlov** [comment]
Probably I should add a section to FAQ for comprehensive explanation.
Until I do it please solve the exercise:
1. Your *steps to reproduce* snippet is error-prone. Why?
2. Hint: tests are usually make a loop per test function.

P.S.
`Connector.close()` should be converted to coroutine, we'll do it in upcoming releases.
Just after `transport.close()` call a paired protocol is not in finished state (`connection_lost()` is no called).
For plain TCP transport it will happen on next event loop iteration, with SSL transport the situation is much worse: TLS shutdown requires passing data over TLS socket.

**Comment by HuberTRoy** [comment]
@asvetlov 
em, sorry, forget it...
I just want to know what will happen if I created `ClientSession` outside of coroutine and manually close it without using `async with`?

This is a simple example: 
```
import aiohttp
import asyncio

Queue = asyncio.Queue

class MyAio:
    session = aiohttp.ClientSession()

    
    def __init__(self, urls:iter):

        self.workQueue = Queue()

        for i in urls:
            self.workQueue.put_nowait(i)

    def __del__(self):
        if not self.session.closed:
            if self.session._connector_owner:
                self.session._connector.close()
            self.session._connector = None

    async def getGithubEvent(self, url):
        result = await self.session.get(url)
        return await result.text(encoding='utf-8')

    async def fetch(self, url):
        text = await self.getGithubEvent(url)
        print(text[:10])

    async def worker(self):
        try:
            while 1:
                url = await self.workQueue.get()
                await self.fetch(url)
                self.workQueue.task_done()
        except asyncio.CancelledError:
            pass

    async def run(self):
        workers = [asyncio.Task(self.worker()) for _ in range(3)]
        asyncio.gather(*workers)

        await self.workQueue.join()

        for i in workers:
            i.cancel()

    def start(self):
        try:
            event_loop = asyncio.get_event_loop()
            event_loop.run_until_complete(self.run())
        except KeyboardInterrupt:
            for task in asyncio.Task.all_tasks():
                task.cancel()
                event_loop.run_forever()
        finally:
            event_loop.close()

test = MyAio(['https://api.github.com/events']*9)
test.start()
```

**Comment by asvetlov** [comment]
Please write tests for `MyAio` methods (doesn't matter will you use `unittest` or `pytest` approach).

**Comment by HuberTRoy** [comment]
@asvetlov 
Thanks a lot.
I think I have figured out it.
