### ISSUE TITLE
Document exceptions 

### ISSUE THREAD

**Issue by Suor** [aio-libs/aiohttp#2817]
## Long story short

Now it's non-obvious what each exception means. E.g. I get `ClientResponseError`, looking at the code it seems that it means code >= 400, but it can also be caused by `HttpProcessingError`. Also, all the fields should be documented otherwise people will look into code and use everything they find, making all that everything a subject to API stability.

Another thing I would love to have is a way to easily separate permanent from temporary (retriable) errors.  

## Expected behaviour

A section in the docs with list, meanings/causes and public attributes.

## Actual behaviour

Nothing in the docs on exceptions.

**Comment by asvetlov** [comment]
Concrete PRs are welcome

**Comment by asvetlov** [comment]
There is http://docs.aiohttp.org/en/stable/client_reference.html#client-exceptions

Closing
