### ISSUE TITLE
Graceful shutdown FAILS - RuntimeError: Event Loop is closed: coroutine 'BaseRunner.setup' was never awaited

### ISSUE THREAD

**Issue by jaredvacanti** [aio-libs/aiohttp#2821]
## Long story short
Attempting to cleanup gracefully on shutdown (`Ctl+C`) returns `RuntimeError: Event Loop is closed`, `RuntimeWarning: coroutine 'BaseRunner.setup' was never awaited`.

My application is making requests to another application over a [`TCP Socket`](https://docs.python.org/3/library/asyncio-protocol.html) and this connection instance is stored in the `aiohttp.web.Application` context. So I am sharing the event loop, making requests to other instance in my views, and returning results RESTfully with aiohttp.

## Expected behaviour
I am trying to gracefully shut down my aiohttp server  https://docs.aiohttp.org/en/stable/tutorial.html#graceful-shutdown on `Ctl+C` and cleanup all pending tasks.

## Actual behaviour
On shutdown, I get the error 
```
Traceback (most recent call last):
  File "/home/jayjo/aspire/ib-rest/venv/bin/ptbnl", line 9, in <module>
    load_entry_point('ptbnl', 'console_scripts', 'ptbnl')()
  File "/home/jayjo/aspire/PTBNL/ptbnl/main.py", line 74, in main
    port=app['config']['server']['port'])
  File "/home/jayjo/aspire/ib-rest/venv/lib/python3.6/site-packages/aiohttp/web.py", line 54, in run_app
    loop.run_until_complete(runner.setup())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 443, in run_until_complete
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'BaseRunner.setup' was never awaited
```

I am not able to track down this pending task even with the `asyncio.get_event_loop().set_debug(True)` enabled. **Could it be that I have several event loops initialized?** I have seen in other posts that using `asyncio.get_event_loop` is preferred to ensure the correct event loop is always being used, but also that explicit passing of the loop if preferred for testing purposes. Currently I am using `asyncio.get_event_loop`. 

## Steps to reproduce

I have followed generally the [`aiohttppolls`](https://github.com/aio-libs/aiohttp/blob/master/demos/polls/aiohttpdemo_polls/main.py) example in structuring the server startup and shutdown. My instance of `tws = PTBNL()` in this example connects with the TCP Socket `asyncio.Protocol` implementation.

```
async def connect_tws(app):
    conf = app['config']['tws']['dev']
    tws = PTBNL()
    await tws.connect_async(host=conf['host'], port=conf['port'], client_id=conf['client_id'])

    app['tws'] = tws


async def disconnect_tws(app):
    tws = app['tws']

    if tws.client.pending_conn_task is not None:
        tws.client.pending_conn_task.cancel()
    tws.disconnect()

    # print(asyncio.Task.all_tasks())
    # try:
    #     pending = asyncio.Task.all_tasks()
    #     await asyncio.gather(*pending)
    # except ConnectionRefusedError as e:
    #     print(e)
    #     pass
    # print(asyncio.Task.all_tasks())


def init(loop):
    app = web.Application(loop=loop)

    with open("./conf/conf.toml") as conffile:
        config = toml.loads(conffile.read())

    app['config'] = config
    app.on_startup.append(connect_tws)
    app.on_cleanup.append(disconnect_tws)

    return app


def main():
    logging.basicConfig(level=logging.DEBUG)
    loop = asyncio.get_event_loop().set_debug(True)
    app = init(loop)
    web.run_app(app, host=app['config']['server']['host'], port=app['config']['server']['port'])
```

Is there a way to coordinate or exclude `aiohttps` cleanup tasks from all other pending tasks in the process, so I could cancel/finish running them with `asyncio.Task.all_tasks()` and then still pass to the aiohttp cleanup? Now if I cancel or run all the tasks with `asyncio.Task.all_tasks()` it also cancels or runs the cleanup tasks so the program will not end.

## Your environment
aiohttp SERVER framework
Ubuntu 16.04 LTS
Python 3.6.3
aiohttp==3.0.7

**Comment by asvetlov** [comment]
`Task.all_tasks()` is for introspection only, changing it can lead to very strange and dangerous code easy as you  see.
Like you should not kill or wait for finishing all processes on your Ubuntu box.

Attached error traceback points that you do something wrong. 
Sorry, but your example is not succinct and reproducible at all, I'm going to close the issue.
