### ISSUE TITLE
Update TechEmpower benchmark

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#2834]
Benchmark still uses 2.1 version

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Python/aiohttp

**Comment by fafhrd91** [comment]
They run it regularly, so it is possible to see difference in human readable form

https://tfb-status.techempower.com

**Comment by asvetlov** [comment]
Looks like the issue is addressed to me.
If nobody will pick it up I'll find a time but not sure when.
Will be pretty busy next two weeks.

**Comment by fafhrd91** [comment]
doesn't really matter, someone need to update requirements. maybe ill be able to do this next week.

**Comment by fafhrd91** [comment]
TechEmpower/FrameworkBenchmarks#3421

**Comment by fafhrd91** [comment]
merged

**Comment by fafhrd91** [comment]
3.0 is consistently slower than 2.x

**Comment by pfreixes** [comment]
Do you have two URLs to compare them in that site? I'm feeling a bit stupid browsing through this site, I didn't manage to get that kind of comparison.

**Comment by asvetlov** [comment]
I suspect it is a result of my change: d0e6e72947a70dea3b0b25be5fe3ad4875f6f0c6

The intention was forbidding a wild assignment a custom attrs to app and request.
I didn't want converting classes to `__slot__` based but pass through a deprecation period.
We can do support `__setattr__` only if the code is executed under `PYTHONASYNCIODEBUG=1` if it is very slow.

I should measure performance first.
Looks like a blocker for aiohttp 3.1 release

**Comment by fafhrd91** [comment]
Results are available on this site https://tfb-status.techempower.com
You need to check commit id

**Comment by fafhrd91** [comment]
here is link to previous results https://tfb-status.techempower.com/results/1dfecb5c-16ff-4622-aa14-d02987749f52
