### ISSUE TITLE
Client DNS start/end events not fired

### ISSUE THREAD

**Issue by MykolaPolovyi** [aio-libs/aiohttp#2841]
## Long story short

Unable to track dns timing via TraceConfig using client with TcpConnector, since `None` intead of `traces` arg passed to direct and proxy connections methods

```
    async def _create_connection(self, req, traces=None):
        """Create connection.

        Has same keyword arguments as BaseEventLoop.create_connection.
        """
        if req.proxy:
            _, proto = await self._create_proxy_connection(
                req,
                traces=None
            )
        else:
            _, proto = await self._create_direct_connection(
                req,
                traces=None
            )

        return proto
```
## Expected behaviour

working DNS tracing with TCP

## Actual behaviour

dns events missed

## Your environment
aiohttp: 3.0.9
OS X

**Comment by asvetlov** [comment]
That's sad but the fix looks easy.
Would you provide a patch?

**Comment by MykolaPolovyi** [comment]
yes

**Comment by pfreixes** [comment]
shame of me, the integration test that wires all of the tracing does not cover this signal [1] ... if its not a big deal would be nice if we can add these signals to that test. That would help in the future to avoid the same mistake.

[1] https://github.com/aio-libs/aiohttp/blob/master/tests/test_web_functional.py#L1641

**Comment by MykolaPolovyi** [comment]
Thanks for pointing the test. I actually wrote a different one and seems like in a wrong place. Will do there.

**Comment by pfreixes** [comment]
Well this just checks the happy path an upper level, if you have others at function level please commit them as well!
