### ISSUE TITLE
Cookie retention/handling does not work when using `ClientSession`

### ISSUE THREAD

**Issue by vmalloc** [aio-libs/aiohttp#2846]
## Long story short

Using ClientSession to have aiohttp manage login credentials/session through cookies does not work as expected

## Expected behaviour

When logging in through an aiohttp ClientSession, it is expected to automatically update cookies set by the server and send them again for authentication... This is more or less the number 1 use case for ClientSession (see reproduction below for more details)

## Actual behaviour

ClientSession either does not store the cookies or fails to send them as expected by the server

## Steps to reproduce

Create a server using the code below (run using `fades`, which will help with the dependencies):
```python
#! /usr/bin/fades
from flask import Flask, render_template, request # fades
from flask_sqlalchemy import SQLAlchemy # fades
from flask_security import Security, SQLAlchemyUserDatastore, UserMixin, RoleMixin, login_required, login_user # fades

# Create app
app = Flask(__name__)
app.config['DEBUG'] = True
app.config['SECRET_KEY'] = 'super-secret'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/testme.sql'

# Create database connection object
db = SQLAlchemy(app)

# Define models
roles_users = db.Table('roles_users',
        db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
        db.Column('role_id', db.Integer(), db.ForeignKey('role.id')))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime())
    roles = db.relationship('Role', secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))

# Setup Flask-Security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore, register_blueprint=False)

# Create a user to test with
@app.before_first_request
def create_user():
    db.create_all()
    user_datastore.create_user(email='test@user.com', password='password')
    db.session.commit()

@app.route('/secret')
@login_required
def secret():
    return 'ok'

@app.route('/login', methods=['POST'])
def login():
    auth_data = request.json
    user = user_datastore.get_user(auth_data['email'])
    login_user(user)
    return 'ok'

if __name__ == '__main__':
    db.drop_all()
    db.create_all()
    app.run()
```

Now create a client using aiohttp with the code below:
```python
#! /usr/bin/env fades
import aiohttp # fades
import asyncio


async def main():
    async with aiohttp.ClientSession() as session:
        async with session.post('http://127.0.0.1:5000/login', json={'email': 'test@user.com', 'password': 'password'}) as response:
            assert response.status == 200

        async with session.get('http://127.0.0.1:5000/secret') as response:
            assert (await response.text()) == 'ok' #<-- this step fails


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

When run together, the second request to `/secret` fails since the serve rejects it.
However, writing an equivalent code in `requests` works as expected:
```python
#! /usr/bin/env fades
import requests # fades

if __name__ == '__main__':
    session = requests.Session()
    session.post('http://127.0.0.1:5000/login', json={'email': 'test@user.com', 'password': 'password'}).raise_for_status()
    resp = session.get('http://127.0.0.1:5000/secret')
    assert resp.status_code == 200
    assert resp.text == 'ok' #<-- succeeds

```

**Comment by asvetlov** [comment]
`ClientSession` **does** save cookies in CookieJar.
But in your case something looks broken.
The issue needs more investigation.
Figuring out what cookies are received from server and what are sent back is much more informative message that just "my code doesn't work" :)

**Comment by vmalloc** [comment]
@asvetlov while I agree that my description could have been improved, having so many moving parts here makes it hard for me to pin-point it.

However, since the code above reproduces easily, stands by its own, and works as expected with another popular http client lib, I was hoping it would be enough to convince you guys that there *is* an issue. I understand you prefer receiving issue summaries which are easily converted to patch diffs, but I'm not sure I can provide that in this case. Once someone can direct me or deduces more info about it I will gladly change the summary to something more specific or constructive. Also, of course, if you find a flaw with my client code I will be happy to stand corrected :-)

The server code was just to demonstrate the issue - it originally happened to me with a 3rd party service which I initially suspected, but then decided to open this issue once I saw that it reproduces with a well-known library for authentication management (i.e. `Flask-Security`), and does not happen with `requests`. Once again - if you have an equivalent example using another mechanism that shows that it does work I will gladly dive deeper to discover the difference and where my example goes bad...

P.S. the examples in the docs for dealing with cookies discuss the case of using `GET` requests to obtain them (specifically from httpbin) - in my case they are obtained using a `POST` - that is the only difference I could glean between what I'm doing and what is documented in your docs...

**Comment by asvetlov** [comment]
I'm convinced that aiohttp has a problem, it was clean from your very first message.
If you need a fix quickly -- please help with investigation.
That's how Open Source works :)
Otherwise I'll keep the issue in my mind but have no estimation / priority for it, sorry.

**Comment by vmalloc** [comment]
@asvetlov oh, of course I wasn't expecting any ETA on a fix - that was perfectly clear. In case my initial message hinted at that, that was not my intention.

Assuming you acknowledge it's a bug I'm ok with it hanging for now. I will also try to investigate deeper once I have some free time for it.

Thanks!

**Comment by popravich** [comment]
This is an intended behavior, please see this lines (of `CookieJar.update` method):
https://github.com/aio-libs/aiohttp/blob/c3c1e3ade57274ccaf12c4673413af27a6191baf/aiohttp/cookiejar.py#L99-L101
and this documentation section:
http://aiohttp.readthedocs.io/en/stable/client_advanced.html#cookie-safety

So, in your case you should create CookieJar explicitly initializing it with `unsafe=True` argument:
```python
async def main():
    cookie_jar = aiohttp.CookieJar(unsafe=True)
    async with aiohttp.ClientSession(cookie_jar=cookie_jar) as session:
        # ...
```
This should work.

**Comment by asvetlov** [comment]
@popravich thanks.
Sorry, I've missed the fact that @vmalloc uses IP address for making a HTTP request.

**Comment by vmalloc** [comment]
Oh... my bad then. Somehow I missed that fact, and indeed the 3rd party service was using its IP as well. Thanks and sorry for the hassle!
