### ISSUE TITLE
Normalize path middleware throws errors and doesn't work

### ISSUE THREAD

**Issue by borisnaidis** [aio-libs/aiohttp#2848]
## Long story short

Normalize path middleware is unusable, because it throws exceptions on every request.

## Expected behaviour

As described in the [docs](https://docs.aiohttp.org/en/stable/web_reference.html#normalize-path-middleware).

## Actual behaviour

When trying to use the middleware it throws a TypeError
```
Error handling request
Traceback (most recent call last):
  File "C:\Git\_temp\.venv\Lib\site-packages\aiohttp\web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "C:\Git\_temp\.venv\Lib\site-packages\aiohttp\web_app.py", line 308, in _handle
    handler = await m(app, handler)
TypeError: normalize_path_middleware() takes 0 positional arguments but 2 were given
```

## Steps to reproduce

1. Start application:
```python
from aiohttp import web

async def hello(request):
    return web.Response(text="Hello, world")

app = web.Application(
    middlewares=[web.normalize_path_middleware]
)
app.router.add_get('/hello/', hello)

web.run_app(app)
```

2. Go to http://localhost:8080/hello

## Your environment

*
  * Windows 10 Pro x64
  * Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
  * aiohttp 3.0.9 (same behaviour for 2.3.4).
*
  * Docker image `python:3.6-slim-stretch`
  * Python 3.6.4 (default, Mar 14 2018, 17:46:38)
  * aiohttp 3.0.9.

**Comment by spcharc** [comment]
Tested. Nothing wrong.
You are using it in a wrong way.
please try:
app = web.Application(middlewares=[web.normalize_path_middleware()])

**Comment by asvetlov** [comment]
@spcharc thank you for investigation.
Agree with your conclusion.
Closing the issue

**Comment by borisnaidis** [comment]
You are right. I used example from [docs](https://docs.aiohttp.org/en/stable/web_advanced.html#middlewares) and assumed that it should work for `normalize_path_middleware` too. What I didn't realize is that `normalize_path_middleware` is a factory function and middlewares in examples are just regular functions. Sorry for bothering you guys.

**Comment by asvetlov** [comment]
Thank you for raising the docs problem.
Bug tracker exists not only for finding/fixing bugs in code but for improvement documentation also.
I've created #2852 
Would you make a PR for it?

**Comment by borisnaidis** [comment]
I'm quite busy at the time and not familiar with ReST syntax, but I could try to do it during this weekend.

**Comment by asvetlov** [comment]
Cool! Please let me know if you'll stick with problems
