### ISSUE TITLE
Allow middlewares to hook into StreamResponses

### ISSUE THREAD

**Issue by flying-sheep** [aio-libs/aiohttp#285]
i want to write a LiveReload middleware, but `StaticRoute` returns `StreamResponse`s.

`StreamResponse.write` basically calls `StreamResponse._resp_impl.write` (aka `protocol.HttpMessage.write`) on the chunk, so the data ends up in the `StreamWriter` before the middlewares see it.

there should be a way to access it.

**Comment by asvetlov** [comment]
Please elaborate what LiveReload middleware should do.

**Comment by flying-sheep** [comment]
insert `<script src="//localhost:35729/livereload.js"></script>` before `</head>` in every served `text/html` document.

but that’s irrelevant: middlewares should be able to modify the data of `StreamResponse`s, that’s the important part.

**Comment by fafhrd91** [comment]
-1 for middlewares, it will degrade performance significantly.

It is easier to customize write method of response.

**Comment by flying-sheep** [comment]
> It is easier to customize write method of response.

…and how do you imagine us to do that? where can i do something with a response after it was created but before it was written to?

note that i _only want to do this if i already know the mime type_, without having to rewrite `StaticRoute`…

**Comment by asvetlov** [comment]
Sorry, your wish is very strange.
You want to modify data returned by static file handler.
Why don't make correct file on disk before starting web application?
Or, if you need complex logic, why do you use static handler at all?

**Comment by flying-sheep** [comment]
maybe how live reload works is strange, but that wasn’t my choice.

it is however the most straightforward way to get reload-on-change functionality into the development version of a website. the idea is that your build script watches files for changes, and on change triggers both e.g. CSS preprocessors and sends a message to all clients listening to some port. the clients are HTML pages with that script loaded.

the part the file server has to do:
1. in development, use a development server which inserts the livereload script tag to both “static” and dynamic html sites (and does other debugging things)
2. in production, use e.g. nginx to serve static files unchanged

**Comment by asvetlov** [comment]
Make your own version of StaticRoute for you complicated use case.

StaticRoute handles not only html files but also images etc.
You cannot just insert `<script>` tag everywhere.

**Comment by flying-sheep** [comment]
> Make your own version of StaticRoute for you complicated use case.

actually i can’t even subclass and use `StaticRoute` without calling `UrlDispatcher._register_endpoint` (where the _dash implies a private API)

`add_route` is married to `path.split('/')` and `PlainRoute`/`DynamicRoute`, and `add_static` to `StaticRoute`.

there’s no way to give additional parameters to the factories or replace them.

> You cannot just insert `<script>` tag everywhere.

lol which is of course why i only do it on `text/html` files.

**Comment by fafhrd91** [comment]
Let's add api for adding routes directly

**Comment by fafhrd91** [comment]
In general, static route from aiohttp is bad choice for production

**Comment by asvetlov** [comment]
Just making `UrlDispatcher._register_endpoint` public is enough, if you agree with function name.

**Comment by fafhrd91** [comment]
maybe `register_route()`

**Comment by flying-sheep** [comment]
> In general, static route from aiohttp is bad choice for production

i’m not sure how this is relevant.
1. i want to use it specifically _not_ in production but for dev
2. no way to use own `Route` subclasses of _any_ kind without private APIs makes no sense

> Just making UrlDispatcher._register_endpoint public is enough, if you agree with function name.

makes sense.
- pro `register_route`: the things are called routes
- pro `register_endpoint`: people will get less confused about which is which (does `add_route` take string arguments? or was it `register_route` and `add_route` takes `Route` instances?)

also the docs should be clear about `add_route` and `add_static` being shortcuts for `Dynamic`/`PlainRoute` and `StaticRoute`, respectively.

**Comment by fafhrd91** [comment]
i added `register_route()` but i didn't add docs, so we can change name in next release.
i don't like `register_endpoint()` because it sounds to me like singular. while route can cover set of endpoints.

**Comment by fafhrd91** [comment]
closing for now

**Comment by flying-sheep** [comment]
for the record: this is my current LiveReloadRoute:

``` python
class LiveReloadRoute(StaticRoute):
    async def _sendfile(self, request, resp, f, file_size):
        logging.info('%s', request)
        if resp.content_type == 'text/html':
            count = file_size
            chunk_size = self._chunk_size

            chunk = f.read(chunk_size)
            while chunk and count > chunk_size:
                if b'</head>' in chunk:
                    chunk = chunk.replace(b'</head>', b'\t<script src="//localhost:35729/livereload.js"></script>\n</head>')
                resp.write(chunk)
                await resp.drain()
                count = count - chunk_size
                chunk = f.read(chunk_size)

            if chunk:
                resp.write(chunk[:count])
                await resp.drain()
        else:
            await super()._sendfile(request, resp, f, file_size)
```

**Comment by asvetlov** [comment]
That's fine but you use private api. Your `LiverReloadRoute` may be broken eventually.

**Comment by flying-sheep** [comment]
sure, so how can we make what i do easier?

make sendfile public?

or create an async chunk iterator which can be hooked into to modify chunks. something like

``` py
class StaticRoute(...):
    chunk_transformer = None
    ...
    # TODO: has to be done at instantiation or via metaclass
    if chunk_transformer is not None:
        _sendfile = _sendfile_dispatch
    elif hasattr(os, "sendfile"):
        _sendfile = _sendfile_system
    else:
        _sendfile = _sendfile_fallback

class LiveReloadRoute(StaticRoute):
    def chunk_transformer(self, req, resp, chunks):
        if not resp.content_type == 'text/html':
            return  #or raise something
        async for chunk in chunks:
            if b'</head>' in chunk:
                async yield chunk.replace(b'</head>', b'\t<script src="//localhost:35729/livereload.js"></script>\n</head>')
            else:
                async yield chunk
```

(using hypothetical async yield syntax, has to be done via normal async iterator now)

the idea is that if `chunk_transformer` is defined it gets called with an async chunk iterator as argument. if it returns nothing (or maybe raises an exception), `_sendfile_dispatch` uses `_sendfile_fallback` or `_sendfile_system`. else it works like`_sendfile_fallback` with difference that it transform chunks via `chunk_transformer`
