### ISSUE TITLE
Drop old-styled middlewares

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2851]
Let's do it in aiohttp 4.0

**Comment by asvetlov** [comment]
Good question.
As of 4.0 we can support *new-style* by default I guess if no other middleware design will come up.

**Comment by samuelcolvin** [comment]
I doubt we'll need another type of middleware, so we should allow middleware without the decorator.

Shall we remove the decorator, deprecate it with a warning or keep it as "no-up"?

I think people might be annoyed if they were previously told to use the decorator and are now told not to use the decorator?

**Comment by asvetlov** [comment]
Why not?
Let's postpone the decision up to 4.0
We are on 3.0 right now, I'm expecting about a year of 3.X active development.

**Comment by spcharc** [comment]
The decorator does literally nothing but giving decorated function an attribute __middleware_version__ = 1. Getting rid of it is a good change.

**Comment by asvetlov** [comment]
@spcharc 
@samuelcolvin created this decorator, I was the PR reviewer.

We both have a deep understanding what the decorator does, how it works and why it exists :)

**Comment by spcharc** [comment]
@asvetlov Oh fine then. Looking forward for future changes in aiohttp

**Comment by asvetlov** [comment]
Superseded by #3569
