### ISSUE TITLE
Improve middleware documentation

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2852]
Current docs are not exhausting clean (#2848 for example).

https://docs.aiohttp.org/en/stable/web_advanced.html#middlewares section should have an example for *middleware factory* (a function that creates a middleware with passed arguments).

*middleware factory* conflicts with a factory for old-style middlewares, I think dropping *old-styles* from docs is ok (but we should support this old style for a while, #2851)

Document that *normalize path middleware* https://docs.aiohttp.org/en/stable/web_reference.html#normalize-path-middleware is actually a factory.

**Comment by asvetlov** [comment]
The issue is very easy, it is documentation update only.
We are looking for newbie for making a Pull Request

**Comment by code-cro** [comment]
Hi, 
"https://docs.aiohttp.org/en/stable/web_advanced.html#middlewares section should have an example for middleware factory (a function that creates a middleware with passed arguments)."

Is not that already explained here?

https://docs.aiohttp.org/en/stable/tutorial.html#middlewares

Or you mean on something else?

**Comment by asvetlov** [comment]
I think `web_advanced.rst` should contain comprehensive description of *middleware factory* (a separate section maybe).
Mentioning in *tutorial.rst* is too brief and it's... tutorial, a different view on documentation.

**Comment by borisnaidis** [comment]
@asvetlov please have a look on #2874.

**Comment by asvetlov** [comment]
Fixed by #2874
