### ISSUE TITLE
Is there any way to not re-encode url passed to ClientSession._request() ?

### ISSUE THREAD

**Issue by dangusev** [aio-libs/aiohttp#2861]
## Long story short

Hi! I faced the problem when I pass already encoded url like this:
```
session.get("http://test.com?phrase=acceptez+l%27utilisation")
```
the ClientSession._request() actually re-encodes url and calls the different url:
```
http://test.com?phrase=acceptez+l'utilisation
```
Is there any workaround for it in aiohttp/yarl?
Thanks.

## Expected behaviour

Do not re-encode directly passed "url" param in ClientSession._request()

## Steps to reproduce

```python
resp = await session.get("http://test.com/?phrase=acceptez+l%27utilisation", allow_redirects=False)
print(resp.url)
# http://test.com/?phrase=acceptez+l'utilisation
```
## Your environment
python 3.6.3
aiohttp==3.0.9
yarl==1.1.1

**Comment by asvetlov** [comment]
`await session.get(yarl.URL(encoded_url, encoded=True))`.
https://docs.aiohttp.org/en/stable/client_quickstart.html#passing-parameters-in-urls

**Comment by dangusev** [comment]
Thank you for such a fast response! My bad, issue is closed.

**Comment by asvetlov** [comment]
Welcome!

**Comment by dangusev** [comment]
Perhaps it would be more naive to control this behaviour via parameter in .get()? Like:
```python
session.get(encoded_url, encoded=True)
```

**Comment by asvetlov** [comment]
`session.get()` already has a very long list of supported flags.
Every new argument is
1. A maintenance burden
2. Documentation burden, which is more important. We are trying to reduce a set of supported *options*, no to blow it to the wild. 

Anyway, the feature is documented in very beginning of `quickstart` section. 
If you have an idea how to improve our docs -- PR is welcome!
