### ISSUE TITLE
Session objects / connection pulls are worthless

### ISSUE THREAD

**Issue by ghost** [aio-libs/aiohttp#2862]
## Long story short

Most realistic webservers don't act the way you may imagine, so, in practice, every request in this library made through session object ends up invalidating this session.  So, not only session object introduces a lot of complication (one would need to use some sort of mutual exclusion to ensure single session object is created to deal with multiple requests), but it also doesn't do what it's supposed to: on every server I've tried so far, after every request, successful or not, I get `aiohttp.client_exceptions.ServerDisconnectedError`.

## Expected behaviour

Just deal with life the way it is.  The problems your library has with maintaining connection pull need to be swept under your carpet. They are absolutely of no interest to your users.

## Actual behaviour

Tons of meaningless exceptions which require a lot of intricate handling with zero benefit to the user.

## Steps to reproduce

Write any code that reuses session object, run it through some arbitrary selection of sites and see how often you get server disconnect errors.

## Your environment

Unimportant.

**Comment by fafhrd91** [comment]
Pretty useless description, no actionables.
