### ISSUE TITLE
Deprecate app.make_handler() in favor of runners API

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2875]
Don't change internal logic a lot but add `app._make_handler()` internal method and reuse it by runners.
More intrusive changes can be done after `app.make_handler()` removal.
Document `app.make_handler()` as deprecated, drop the usage from `logging.rst` and `testing.rst`.

**Comment by asvetlov** [comment]
The issue is mostly about documentation update (and a little coding).
A volunteer is welcome!

**Comment by asvetlov** [comment]
The step-by-step instruction is:
1. Rename `.make_handler()` to `._make_handler()`
2. Fix tests and code to use `app._make_handler()`
3. Add `Application.make_handler()` back, the method should raise `DeprecationWarning` like here https://github.com/aio-libs/aiohttp/blob/80c0e5fd164f1cf0d35ada8cfaae19de3d55787d/aiohttp/payload_streamer.py#L47-L49 and call `._make_handler()`.
4. Add `.. deprecated:: 3.2` to documentation.
5. Add `xxx.removal` file to `CHANGES`.

**Comment by xstrengthofonex** [comment]
Thank you for the clarification. I'll get to work

**Comment by asvetlov** [comment]
Fixed by #2938
