### ISSUE TITLE
Add argument 'raise_for_status' to 'ClientSession' request method.

### ISSUE THREAD

**Issue by Vestrond** [aio-libs/aiohttp#2878]
We can create **ClientSession** with the argument '*raise_for_status*'.
But what about making two **request** from one application, when first will be with '*raise_for_status* = **True**', second with '*raise_for_status* = **False**'?

In this case we should to append two ClientSession to application.
```python
application['client_session'] = ClientSession()  # default is False
application['other_client_session'] = ClientSession(raise_for_status=True)
```
 I think that this way isn't good.

To solve this problem you can expand '**request**' method with '_raise_for_status_' argument who will redefine ClientSession's '_raise_for_status_' state for this **request**.
```python
async with client_session.request(method, url, raise_for_status=True) as r:
    ...
```

**Comment by asvetlov** [comment]
Too many flags, isn't it?
Please use already existing api:
```
async with client.get(url) as resp:
     resp.raise_for_status()
```

**Comment by Vestrond** [comment]
Indeed...
Thanks.
