### ISSUE TITLE
TestClient should expose app attribute

### ISSUE THREAD

**Issue by thomaszdxsn** [aio-libs/aiohttp#2891]
## Long story short

I wrote my first test today, use `pytest-aiohttp`, fixture: `aiohttp_client`.

I don't want to follow doc by use hardcode URL, I think it is not a good practical pattern. I want to use `app.route[].url_for()`.

And I found it need long access chain. like `cli.server.app.route[].url_for().with_query()`.

Maybe should expose `app` attribute/property in `TestClient` instance?

## Expected behaviour

can access `app` in client by `client.app`.

## Actual behaviour

must access `client.server.app`

**Comment by asvetlov** [comment]
I not sure.
The test client could be used for testing low-level server (https://docs.aiohttp.org/en/stable/web_lowlevel.html) where `.app` is not exist.

We can assign `cli.app` to `None` in this case but the behavior should be properly tested and documented.
If you want to make a fix for it -- you are welcome but please don't forget about low-level server testing.

**Comment by thomaszdxsn** [comment]
I will fix it on weekend

**Comment by asvetlov** [comment]
Fixed by #2901
