### ISSUE TITLE
Encoding detection error

### ISSUE THREAD

**Issue by decaz** [aio-libs/aiohttp#2892]
## Long story short

Encoding detection at the client is broken.

## Expected behaviour

No errors.

## Actual behaviour

```
Traceback (most recent call last):
  File "test_aiohttp.py", line 10, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "test_aiohttp.py", line 7, in main
    resp.get_encoding()
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 839, in get_encoding
    encoding = chardet.detect(self._body)['encoding']
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/chardet/__init__.py", line 34, in detect
    '{0}'.format(type(byte_str)))
TypeError: Expected object of type bytes or bytearray, got: <class 'NoneType'>
```

## Steps to reproduce

```python
import asyncio
import aiohttp

async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get('http://olympic.ru/rubric/lenta/') as resp:
            await resp.text()
            print(resp.get_encoding())

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

## Your environment

aiohttp==3.1.1

**Comment by decaz** [comment]
My bad =/ At my project I fetch url by chunks and after that I change `resp._content` attribute to result of fetching so `resp.get_encoding()` can work with it. But since 3.1.0 `ClientResponse._content` was renamed (https://github.com/aio-libs/aiohttp/commit/3b048362b65b6c728b894c0202fdd4b53fdcd32d).

**Comment by asvetlov** [comment]
I can reproduce the problem, thank you for filing it.

The bugfix should land into 3.1 branch, sure.
Personally I have no estimation for the fix (next week maybe).
If anybody want to pick up the issue -- you are welcome.
aiohttp bugfix release will be published just after merging the PR.
