### ISSUE TITLE
Raise an exception on request body reading after sending response

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2895]
See #2893 for the issue motivation

**Comment by hubo1016** [comment]
If the POST data is not read when respond ends, what should be done? Read the entire post data to make the connection ready for the next request, or close it forcely? The post data might be very large, but forcely close the connection may break the "Connection: keep-alive" in the previous response.

A mark could be set after that to stop further reads.

**Comment by hubo1016** [comment]
It should be "read the entire post data" and "do nothing". The connection cannot be forcely closed, or the response might be lost due to connection reset (client write to a closed connection resets the connection)

**Comment by asvetlov** [comment]
From my perspective we have two cases: 
1. POST data is not consumed by user's code but placed into `StreamReader`.
Nothing to do here but forbid a fetching from `StreamReader` after response sending to fix a logical error.
2. The data is not in `StreamReader` buffer because the data size is too big. In this case we cannot gracefully release the connection but should force-close it. Because we cannot read the whole huge body (it can take an infinite amount of time).

**Comment by hubo1016** [comment]
@asvetlov after reading the code, I found it already implemented

https://github.com/aio-libs/aiohttp/blob/c5d39998d3ea3d34bccdfac64b7171544b612a36/aiohttp/web_protocol.py#L422-L434

Seems that it reads for `lingering_time` (by default 10s) and forcely close the connection after that. This is a reasonable solution.

**Comment by asvetlov** [comment]
Yes.  The only thing is left: close payload as well. Now it is possible to read payload (StreamReader) data after sending response, which is weird and error prone. I thing `request.content.set_exception()` should be enough.

**Comment by asvetlov** [comment]
Fixed by #2927
