### ISSUE TITLE
Documentation does not build on Windows platform

### ISSUE THREAD

**Issue by code-cro** [aio-libs/aiohttp#2898]
## Long story short
Windows platform - cannot build documentation.
Reason was that the build script was unable to find __version__ string with re.search
due to Windows line ending style.

## Expected behaviour

Build documentation on Windows

## Actual behaviour

Error is thrown and no documentation build process starts.

## Steps to reproduce

make doc

## Your environment

Windows 8.1
Python 3.6.4
aiohttp 3.1.1

**Comment by asvetlov** [comment]
Fixed I hope.
