### ISSUE TITLE
Patching internal functions in unittesting

### ISSUE THREAD

**Issue by d21d3q** [aio-libs/aiohttp#2904]
I am trying to write unit test of endpoint which uses [`aiohttp_security`](https://github.com/aio-libs/aiohttp-security) and mock call to [`authorized_userid`](https://github.com/aio-libs/aiohttp-security/blob/6e0cedaac762fdbd8ee8f3857506c1d2d40837ff/aiohttp_security/api.py#L49) in order to simulate logged in user. 

So here is what I am doing:
```python
from aiohttp.test_utils import AioHTTPTestCase, unittest_run_loop
from my_app import make_app
from mock import patch

async def fake_authorised_userid(request):
    return 1

class AppTest(AioHTTPTestCase):
    async def get_application(self):
        return make_app()

    def setUp(self):
        super().setUp()
        # here I am setting up db

    @unittest_run_loop
    @patch('aiohttp_security.authorised_userid', side_effect=fake_authorised_userid)
    # @patch('aiohttp_security', return_value=1)
    async def test_foo(self, mock):
        # endpoint is marked with login_required
        # and also makes call to authorised_userid
        request = await self.client.get('/some/endpoint')
        assert mock.called
        assert request.status == 200
```
and patch doesn't work as expected.
I am running tests with `pytest`.
Is that issue related to `aiohttp` or `asyncio` in general or just to `aiohttp_security`?

**Comment by asvetlov** [comment]
I have several questions.
1. If you use `pytest` why do you write tests in `unittest` style?
2. Why do you need mocking at all? Does creation a test app with custom test [authorization policy] (http://aiohttp-security.readthedocs.io/en/latest/reference.html#aiohttp_security.AbstractAuthorizationPolicy) and use it everywhere. Mock overusage is a strong smell of bad design decisions.

**Comment by d21d3q** [comment]
That is very good question (1).
It seems that at the beginning I've started to write unittest style (and stick to `AioHTTPTestCase`) and then discovered pytest and I didn't notice that there are fixture for it... I will switch to using it. 

With mocking it seems to be easier to control from test level eg which user should it return.

**Comment by asvetlov** [comment]
By mocking you are testing your mocks, not the real code.
Anyway replacement `@patch(...)` with `with patch(...)` can help

**Comment by d21d3q** [comment]
I switched to `pytest`, but in this case
```python
@patch('aiohttp_security.authorized_userid`, return_value='user`)
async def test_foo(cli):
    request = await cli.get('/endpoint')
    assert request == 200
```
test_foo is never awaited, and here
```python
async def test_foo(cli):
    with patch('aiohttp_security.authorized_userid`, return_value='user`) as mock:
        assert mock.called
        request = await cli.get('/endpoint')
    assert request == 200
```
mock is not called.

I managed to bypass login by having alternate `AbstractIdentityPolicy` for testing.

**Comment by asvetlov** [comment]
Looks like you've mocked the wrong name.
Suppose I have module `mod_a` with the following content:
```
from aiohttp_security import authorized_userid
from aiohttp import web

async def handler(request):
    if not await auntorized_userid(request):
        raise web.HTTPForbidden()
```
In this case patched name should be `mod_a.authorized_userid`, not `aiohttp_security.authorized_useriid`.
