### ISSUE TITLE
ClientResponse.raise_for_status() should include the url that was connected to in the message

### ISSUE THREAD

**Issue by jamesqo** [aio-libs/aiohttp#2918]
## Long story short

The title. It would be very useful for apps that are making a lot of different HTTP requests (which is often the reason why aiohttp is used in favor of requests).

## Expected behaviour

Include the url

## Actual behaviour

Not including the url

**Comment by asvetlov** [comment]
Sorry for late reply but it is already implemented a long time ago.
Use https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientResponseError.request_info property.
