### ISSUE TITLE
Call method to clean middleware class

### ISSUE THREAD

**Issue by Pajinek** [aio-libs/aiohttp#2919]
## Long story short

I try to create middleware as class that need to have connection to Redis. But I can't find way to call async method for destroy connection (call method cleanup in middleware). 

Example for imagine:

```
    app = web.Application(
        middlewares=(
            ExampleMiddleware(...),
        ),
        loop=loop
    )
```
And middleware is implemented following way:

```
class ExampleMiddleware:

    def __init__(self,  **kwargs):
        self._redis_pool = None

   ## destroy connection during clean up service
    async def cleanup(self):
        if self._redis_pool is not None:
            self._redis_pool.close()
            await self._redis_pool.wait_closed()

    async def _connect_redis(self):
        if self._redis_pool is None:
            self._redis_pool = await aioredis.create_redis_pool(self._redis_url)

    async def __call__(self, app, handler):
        return partial(self.middleware, handler)

    async def middleware(self, handler, request):
        response = await handler(request)
        await self._connect_redis()
        . . .
        return response
```

## Expected behaviour

Call some async method of middleware for clean up.

I created temporary patch: https://github.com/Pajinek/aiohttp/commit/646b0bddde1292874384d063ced25ad9b8473639 but I am not sure that it is correct way how to resolve it. 

## Actual behaviour

My midleware class is not correct destroy.

## Steps to reproduce

1. Create middleware class
 - init
 - call 
 - destroy (problem)

## Your environment
aiohttp==3.1.0

**Comment by samuelcolvin** [comment]
You should use `on_startup` to create your redis connection, then add a reference to the redis connection/pool to the app so you can use it in middleware. You can then close the connection using `on_cleanup`.

See [here](https://github.com/tutorcruncher/socket-server/blob/master/tcsocket/app/main.py#L22) for an example of roughly the same thing.

Closing this as it isn't an issue with aiohttp, but feel free to ask any follow-up questions.
