### ISSUE TITLE
speedup module for websocket masking

### ISSUE THREAD

**Issue by methane** [aio-libs/aiohttp#293]
WebSocket masking is heavy for pure Python when frame is large.
[Here](https://github.com/tornadoweb/tornado/blob/master/tornado/speedups.c#L4-L27) is tornado's speedup.
Could aiohttp have same speedup module?

**Comment by ludovic-gasc** [comment]
+1

**Comment by asvetlov** [comment]
I'll take a look.

**Comment by asvetlov** [comment]
Fixed in #296

**Comment by methane** [comment]
Thanks!

**Comment by ludovic-gasc** [comment]
Thanks Andrew, I'll test that with one of my daemons on production.
