### ISSUE TITLE
make_mocked_coro should be enchanced

### ISSUE THREAD

**Issue by POD666** [aio-libs/aiohttp#2930]
## Long story short

I'm trying to write test for custom http service client.
My custom client uses `aiohttp.ClientSession`.
For each request my custom client checks if the same request is already waiting for response and wait for result instead of creating new request. 

Here is fragment of my test:
```
response = mock.Mock(json=make_mocked_coro(expected_json_data))
with mock.patch.object(my_client.session, 'get', new=make_mocked_coro(response)):
    tasks = [
        my_client.get_by('query'),  # task1
        my_client.get_by('query'),  # task2
        my_client.get_by('query')   # task3
    ]
    results, pending = await asyncio.wait(tasks)
    my_client.session.get.assert_called_once_with(...)
```
Here is idea of my client code:
```
async def get_by(key)
    while key in self.pending_downloads:
        await asyncio.sleep(0.1)
    try:
        result = self.cache[key]
    except KeyError:
        self.pending_downloads.add(key)
        response = await self.session.get(url+key, ...)
        data = await response.json()
        self.cache[key] = data
        self.pending_downloads.remove(key)
```

## Expected behaviour

I've expected to see switches between task1, task2, task3 when `ClientSession.get` or `response.json` called(+awaited) while debugging.

## Actual behaviour

task1 was executed without switches on `ClientSession.get` or `response.json` call(+awaiting).
So task2 and task3 didn't wait for task1 to be finished and just get cached result from task1.

## Fix

To achieve expected behaviour I have added `yield from asyncio.sleep(0)` to `mock_coro`(inside `make_mocked_coro`).

Is my fix correct? I will make PR if so.

**Comment by asvetlov** [comment]
`await` doesn't imply the task switch. The switch is performed on awaiting pending future only.
That's why I think the current implementation is correct.

**Comment by POD666** [comment]
@asvetlov Then can you suggest me a way to write this test? Maybe 'sleep' for `make_mocked_coro` should be optional? How to mock `ClientSession.get` and `response.json`?

**Comment by asvetlov** [comment]
Use a custom mock with side_effect pointing on your implementation with `asyncio.sleep()`.
Or `aresponses` library.
I have a feeling that sleeping on awaiting is out of the scope of relative simple `make_mocked_coro()` function.

**Comment by POD666** [comment]
@asvetlov Looks like `aresponses` meets my needs. I will try it.
But I still think `aiohttp.test_utils` should provide utility to create awaiting pending future mock.
