### ISSUE TITLE
Documentation for adding routes out of sync with interface

### ISSUE THREAD

**Issue by daniel-j-h** [aio-libs/aiohttp#2939]
The `web` documentation shows the following for adding routes to the application:

```python
routes = web.RouteTableDef()

@routes.get('/')
async def index(req):
    return web.Response(text='Hello')

app = web.Application()
app.add_routes(routes)  # <--
```
For example here in the quickstart docs:
https://github.com/aio-libs/aiohttp/blob/master/docs/web_quickstart.rst#run-a-simple-web-server

But it seems like `Application` does not provide an `add_routes` function:

> AttributeError: 'Application' object has no attribute 'add_routes'

Instead it looks like we have to go through the app's router at `web.router.add_routes(routes)`.

Is this a recent change and should get documented properly or is this a regression in the API?

## Expected behaviour

Quickstart examples for adding routes to the app work.

## Actual behaviour

Quickstart examples for adding routes to the app does not work, has to go through app's router property.

## Steps to reproduce

Follow first steps in docs for the `aiohttp.web` package.

## Your environment

Python 3.5, latest aiohttp (2.3.10) from pip

**Comment by drpoggi** [comment]
`2.3.10` is not the latest version, the documented method for adding routes was added in `3.1`

**Comment by daniel-j-h** [comment]
Oops, hm at least it's the latest version I get when `pip install aiohttp`.

I just tried it again in a completely new local virtualenv

```
(env) $ pip install aiohttp
Collecting aiohttp
  Downloading aiohttp-2.3.10-cp35-cp35m-manylinux1_x86_64.whl (649kB)
```

I can definitely see 3.1 on https://pypi.python.org/pypi/aiohttp though :thinking: 

Any idea what's going on here?

I'm closing this ticket already since it's fixed in 3.1.

**Comment by drpoggi** [comment]
Possibly pip installing a cached version, what if you do `pip install --upgrade aiohttp`?

**Comment by daniel-j-h** [comment]
Does not help either; I tried that already and I also removed the pip cache:

```
daniel@x1c5 /t/test> virtualenv -p python3 .env
daniel@x1c5 /t/test> . .env/bin/activate
(.env) daniel@x1c5 /t/test> pip install --upgrade aiohttp
Collecting aiohttp
  Using cached aiohttp-2.3.10-cp35-cp35m-manylinux1_x86_64.whl
..
(.env) daniel@x1c5 /t/test> deactivate 
daniel@x1c5 /t/test> rm -rf ~/.cache/pip/
daniel@x1c5 /t/test> rm -rf .env/
daniel@x1c5 /t/test> virtualenv -p python3 .env
daniel@x1c5 /t/test> . .env/bin/activate
(.env) daniel@x1c5 /t/test> pip install aiohttp
Collecting aiohttp
  Downloading aiohttp-2.3.10-cp35-cp35m-manylinux1_x86_64.whl (649kB)
..
```

**Comment by scubbx** [comment]
I tried the following after receiving the same error. For whatever reason the current version is not found on pypi.

```
$ pip install aiohttp==3.3.1
Collecting aiohttp==3.3.1
Could not find a version that satisfies the requirement aiohttp==3.3.1 (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.21.4, 0.21.5, 0.21.6, 0.22.0a0, 0.22.0b0, 0.22.0b1, 0.22.0b2, 0.22.0b3, 0.22.0b4, 0.22.0b5, 0.22.0b6, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.22.4, 0.22.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.6.post1, 2.0.7, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0a1, 2.3.0a2, 2.3.0a4, 2.3.0, 2.3.1a1, 2.3.1, 2.3.2b2, 2.3.2b3, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 3.0.0b0)
No matching distribution found for aiohttp==3.3.1
```

**Comment by asvetlov** [comment]
Perhaps your python version is < 3.5.3, maybe 3.5.1 or 3.5.2

**Comment by scubbx** [comment]
I also tried with pip3 explicitly, but the pip command is linked to python3 anyways:
```
$ pip --version
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)
```

**Comment by jerblack** [comment]
FWIW, I just saw the exact same behavior installing through PyCharm. I added the package through that interface which is just a wrapper for python3 pip and it gave me the old version by default.  It then showed me an upgrade was available to the current one.

**Comment by asvetlov** [comment]
Sorry, teaching to `pip` and `PyCharm` usage is out of the project mission.

**Comment by teror4uks** [comment]
@jerblack @scubbx Check yours python version, If it < 3.5.3 then you should upgrade your intrepretator. In pypi page that version showing in requirements. In ubuntu 16.04 by default using 3.5.2. https://pypi.org/project/aiohttp/

**Comment by nekrasovp** [comment]
This problem happens when you are trying to use older then 3.5.3 version of python. Easiest way is to create new venv with new python version. If you are using PyCharm go to File -> Settings -> Project interpreter and create a new one with new python version.
