### ISSUE TITLE
Weird exception in close() (maybe incompatible gunicorn version

### ISSUE THREAD

**Issue by mpaolini** [aio-libs/aiohttp#294]
Just came around this one:

`File "/usr/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete#012    return future.result()#012  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result#012    raise self._exception#012  File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step#012    result = coro.send(value)#012  File "/usr/local/lib/python3.4/dist-packages/aiohttp/worker.py", line 91, in _run#012    yield from self.close()#012  File "/usr/local/lib/python3.4/dist-packages/aiohttp/worker.py", line 68, in close#012    yield from self.wsgi.finish()#012TypeError: finish() missing 1 required positional argument: 'self'`

**Comment by fafhrd91** [comment]
that's strange. what version of  aiohttp do you use? how do you start app?

**Comment by fafhrd91** [comment]
is that still an issue?

**Comment by fafhrd91** [comment]
reopen, if it still a problem

**Comment by mpaolini** [comment]
This one was master from roughly 2 weeks ago on python 3.4.3
