### ISSUE TITLE
Proxy port

### ISSUE THREAD

**Issue by vtenq** [aio-libs/aiohttp#295]
I'm using aiohttp to send requests to a specific site through proxy servers
but I didn't manage to find in the documentation how to set proxy port?

**Comment by fafhrd91** [comment]
does this work?  `ProxyConnector(proxy="http://some.proxy.com:8080")`

**Comment by vtenq** [comment]
no

**Comment by vtenq** [comment]
try:
        conn = aiohttp.ProxyConnector(proxy=proxy)   #proxy = 113.105.224.87:80
        r = yield from asyncio.wait_for(aiohttp.request('get', url, connector=conn), 6)
        raw = yield from r.text()
        good += 1
        print(good)
except aiohttp_errors as e:
        print('error')

all the time a have error
but if i try without port it sends request, but as i think without using proxy

**Comment by fafhrd91** [comment]
@asvetlov @popravich could you guys look into this problem?

**Comment by popravich** [comment]
Hi, guys!
You should use proxy connector like this:

``` python
conn = ProxyConnector(proxy='http://1.2.3.4:5678')
yield from aiohttp.request('get', url, connector=conn)
```

The only thing is that proxy must be http proxy, ie must start with `http://`

**Comment by popravich** [comment]
...name resolving also works as it uses aiohttp ClientRequest to create connection to proxy
