### ISSUE TITLE
Show requests log in terminal

### ISSUE THREAD

**Issue by cyantarek** [aio-libs/aiohttp#2952]
## Long story short

I want the log display in terminal feature like django

## Expected behaviour

When running "python main.py", any hit on URL endpoint should log the info in the terminal.

For example:

======== Running on http://0.0.0.0:8095 ========
(Press CTRL+C to quit)
[21:36:52] 127.0.0.1 [23/Apr/2018:15:36:52 +0000] "GET / HTTP/1.1" 200 183 "-" "PostmanRuntime/6.4.1"

## Actual behaviour

No log info display

## Your environment

Windows 8.1, 64 Bit, Python 3.6

**Comment by asvetlov** [comment]
You need to setup access logger: https://docs.aiohttp.org/en/stable/logging.html#access-logs

All-logging-by-default is too annoying, that's why aiohttp has a separate API for it

**Comment by cyantarek** [comment]
Well, after that, will it be shown in terminal for each requests?

**Comment by asvetlov** [comment]
The question is out of aiohttp scope.
Perhaps you should learn about Python logging: https://docs.python.org/3/library/logging.html#logging.basicConfig

**Comment by scherrey** [comment]
For debugging purposes, I made this little bash command that will run my app (listing_server.listing_app) with debug logging turned on. It should make it obvious how to use basic logging in an aiohttp server context.

python -c "import logging; from aiohttp import web; from listing_server import *; logging.basicConfig(level=logging.DEBUG); web.run_app(listing_app);"

**Comment by xen** [comment]
Actually, access log to the stdout is standard for any HTTP servers.

**Comment by asvetlov** [comment]
Really?
IIRC flask requires explicit logging system setup like aiohttp: http://flask.pocoo.org/docs/1.0/logging/

**Comment by webknjaz** [comment]
AFAIR flask prints out access logs too

**Comment by asvetlov** [comment]
Aha, http://flask.pocoo.org/docs/1.0/logging/#default-configuration
Flask adds `StreamHandler` to application logger if the logger has no handlers at the moment of application startup.
We can do the same in `web.run_app`. `AppRunner` should be configured explicitly.

**Comment by sjatkins** [comment]
No real answer is given.  Or none that is intelligible to this reader.  Give clear minimal instructions for running your web app with access logging please.

**Comment by ixje** [comment]
Here's an example that worked for my situation
```python
import logging

stdio_handler = logging.StreamHandler()
stdio_handler.setLevel(logging.INFO)
_logger = logging.getLogger('aiohttp.access')
_logger.addHandler(stdio_handler)
_logger.setLevel(logging.DEBUG)
```

```python
app = web.Application(logger=_logger)
runner = web.AppRunner(app)
await runner.setup()
site = web.TCPSite(runner, args.host, args.port_rpc)
await site.start()
```

and the output now includes lines like
```
127.0.0.1 [09/Apr/2019:10:59:18 +0000] "POST / HTTP/1.1" 200 272 "-" "PostmanRuntime/7.6.1"
```

**Comment by NewUserHa** [comment]
hope there's a document enhancement or an aiohttp enhancement for this.
thanks you

**Comment by asvetlov** [comment]
Champion is welcome!

**Comment by NewUserHa** [comment]
I have no idea how to modify aiohttp to behavior like others like `flask`. maybe use ixje's comment?
if you don't mind, I can PR a document enhancement about 'logging.basicConfig()' that you comment in another issue.

ps. the PR for debug flag to run_app cant pass test. do you have any idea?
thanks
