### ISSUE TITLE
[client] Using connection pool without session or session without cookies

### ISSUE THREAD

**Issue by saabeilin** [aio-libs/aiohttp#2953]
## Long story short

Sometimes one needs to make requests to a number of external http resources, some of them being client-facing API providing cookies you do not really need. The Session manages cookies by default and there's no simple way to easily switch it off. In fact, in many situations only connection pooling is required. Creating a session for every request does not look as a good approach.

A typical use case is a BFF, orchestrating multiple microservices.

## Expected behaviour

1) `aiohttp.ClientSession(disable_cookies=True)`
2) `aiohttp.ClientConnPool()` and then just `pool.get()` with same syntax as session.

If there is a simple way to achieve one of these, an example in the docs would be awesome.

Thanks in advace!

**Comment by asvetlov** [comment]
https://docs.aiohttp.org/en/stable/client_advanced.html#dummy-cookie-jar

**Comment by saabeilin** [comment]
Thanks a lot @asvetlov - I completely missed it somehow!
