### ISSUE TITLE
functools.partial breaks new-style middleware

### ISSUE THREAD

**Issue by dragos-vlad** [aio-libs/aiohttp#2959]
## Long story short

Applying `functools.partial` on a new-style middleware forces the application to treat it as an old-style middleware which sends the `application` and `handler` parameter to the middleware function instead of `request` and `handler`

## Expected behaviour

Applying `functools.partial` on the new-style middleware should not "convert" it to an old style one

## Steps to reproduce

``` python3
from functools import partial
from aiohttp import web


@web.middleware
async def test_middleware(request, handler, *, config):
    print(request.headers, config)
    return await handler(request)


async def hello_word(request):
    return web.Response('Hello World')


def build_app():
    app = web.Application()
    app.middlewares.append(partial(test_middleware, config=1))

    app.router.add_route('GET', '/', hello_word)

    return app

if __name__ == '__main__':
    web.run_app(build_app())
```

Accessing `http://127.0.0.1:8080` will throw:
```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 320, in _handle
    handler = await m(app, handler)
  File "test.py", line 7, in test_middleware
    print(request.headers, config)
AttributeError: 'Application' object has no attribute 'headers'
```

## Your environment
python = 3.6.5
aiohttp = 3.1.3

**Comment by asvetlov** [comment]
`functools.partial` doesn't copy argument's dict, that's why new middleware detection doesn't work.
Unfortunately, aiohttp cannot fix `partial` implementation.
Dropping old-style middlewares (and new-style middleware check) is postponed to aiohttp 4.0 because it is the backward incompatible change.
The only thing you can do now is avoiding `functools.partial` using.

**Comment by dragos-vlad** [comment]
Ahh didn't knew that. Thanks for the quick reply.
