### ISSUE TITLE
Question: is it possible to transfer aiohttp ClientSession settings to a valid requests.Session?

### ISSUE THREAD

**Issue by kootenpv** [aio-libs/aiohttp#2960]
I would like to use `ClientSession` to keep a session alive asynchronously, but then have a synchronous loop that does not allow any code to run in between (for me miliseconds are important).

Two ideas:

1. Be able to do a HTTP post synchronously with ClientSession.

2. Transfer the settings of a ClientSession (e.g. domain loopup, TCP connection etc) and allow a requests.Session to take it over (unlikely?)

What can I do?

**Comment by kootenpv** [comment]
@pfreixes But then I need multiple threads right? I would incur thread switching then.

**Comment by pfreixes** [comment]
Yes, but while you have this in mind IMO is an option that you can explore.

**Comment by hubo1016** [comment]
I think you may also use a lock to synchronize the requests
