### ISSUE TITLE
websocket server: sending right after prepare() doesn't work

### ISSUE THREAD

**Issue by gjcarneiro** [aio-libs/aiohttp#2961]
## Long story short

A server that creates a websocket response.  If I send a message to the client as soon as the client connects, it doesn't work.  I have to wait for some message from the client before sending it data. 

Basically, sending messages only works inside the `async for msg in ws` loop.  Before it, it triggers a protocol error.

It sounds like there needs to be some hand-shaking between server and client before we can send messages to the client.  But I see no way to synchronise, to wait for this hand-shaking to happen.  My websocket protocol is supposed to send a bunch of messages to the client as soon as the client connects, without waiting for the client to send any request.

## Expected behaviour

I'd expect that, as soon as I connect, I'd receive a message:

```
> $ wscat -c 10.102.248.99:5000/v1/streamer?token=c3baacb76aa48bc32dd3a700cc5876d9
connected (press CTRL+C to quit)
< "xxxx"
```

## Actual behaviour

I get this error in wscat:

```
$ wscat -c 10.102.248.99:5000/v1/streamer?token=c3baacb76aa48bc32dd3a700cc5876d9
connected (press CTRL+C to quit)
error: Error: no handler for opcode 6
```

(with compression enabled, the invalid opcode changes to 12)

## Steps to reproduce
```python
from aiohttp import web
import aiohttp
import uvloop


async def web_stream(request: web.Request) -> web.Response:
    ws = web.WebSocketResponse(compress=False)
    await ws.prepare(request)
    await ws.send_json('xxxx')  # moving this statement to inside the the async for loop below "fixes" it
    async for msg in ws:
        print(msg)
        if msg.type == aiohttp.WSMsgType.TEXT:
            print(msg.data)
            if msg.data == 'close':
                await ws.close()
            else:
                await ws.send_json(msg.data + '/answer')
    return ws


def main() -> None:
    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
    app = web.Application()
    app.router.add_get('/v1/streamer', web_stream)
    web.run_app(app, host="0.0.0.0", port=80)


if __name__ == "__main__":
    main()

```

## Your environment

both

Server is uvloop, aiohttp 3.1.3, Python 3.6.5.
Client is wscat 1.1.0:
```
||/ Name                                                 Version                         Architecture                    Description
+++-====================================================-===============================-===============================-=============================================================================================================
ii  node-ws                                              1.1.0+ds1.e6ddaae4-3build1      amd64                           RFC-6455 WebSocket implementation module for Node.js
```

There is no proxy involved.

**Comment by asvetlov** [comment]
The first WS message is `0x81 0x06 0x22 0x78 0x78 0x78 0x78 0x22`.
It means `0x81 0x06` header and `"xxxx"` data.
0x81 means a single text message (FIN + TEXT flags), 0x06 means 6 bytes of data.
The message is correct according to RFC: https://tools.ietf.org/html/rfc6455#section-5.2

I have no idea why `wscat` assumes that `0x6` is *opcode*, the opcode is stored in the first byte and it is 0x1 (TEXT).

Please note that browsers process sending a message just after WS handshake correctly: https://github.com/aio-libs/aiohttp/blob/master/examples/web_ws.py#L22

I'm marking the issue as "invalid", will close it in a few days if no status update.

**Comment by gjcarneiro** [comment]
Thanks for looking.  So you think it's really a client bug...  I have no opinion either way.  Just reporting what I saw.  If it's not a bug, it's not a bug.
