### ISSUE TITLE
aiohttp doesn't use system settings

### ISSUE THREAD

**Issue by lc-thomas** [aio-libs/aiohttp#2963]
## Long story short

aiohttp doesn't use system proxy settings

## Expected behaviour

aiohttp should use system proxy settings

## Actual behaviour

aiohttp doesn't use system proxy settings

## Steps to reproduce

Set a system proxy : export http_proxy="your_proxy"
Make a request using aiohttp 

## Your environment

aiohttp client - Debian

**Comment by asvetlov** [comment]
aiohttp shouldn't use system proxy settings. It is insecure.
Use `trust_env=True` explicitly: https://docs.aiohttp.org/en/stable/client_advanced.html?highlight=trust_env#proxy-support
