### ISSUE TITLE
Add canonical name for the route

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiohttp#2968]
## Long story short

For third party libraries sometimes it is useful to know canonical name of the route from request, for example https://github.com/aio-libs/aiozipkin/issues/115. 

Something  like `/foo/bar/{name:\d+}` could be exposed with property:  `request.match_info.route.canonical_name`

**Comment by asvetlov** [comment]
Let's use a formatter pattern from `.url_for()` implementation.

The issue is easy to implement, looking for a champion.
