### ISSUE TITLE
Reloading Gunicorn does not read the new code

### ISSUE THREAD

**Issue by aptiko** [aio-libs/aiohttp#2976]
The system is running with Gunicorn. I make a change to the code, then I send HUP to the master process. Gunicorn does create new workers and stop the old ones, however the changes in the code do not take effect. If I stop Gunicorn and restart it, then the changes do take effect.

This is aiohttp 2.3.10 on Gunicorn 19.8.1, Python 3.5.2, on Ubuntu 16.04 amd64.

**Comment by asvetlov** [comment]
If gunicorn *recreates* workers -- how it cannot reload worker's code?
Please double check your environment.

**Comment by aptiko** [comment]
All I know is it doesn't reload the code. I checked many times. Of course it's always possible I'm doing something very stupid.

Assuming I'm right, what would you like? Create a docker container that demonstrates the problem?

**Comment by asvetlov** [comment]
I've just checked -- gunicorn reload works as expected.
Closing the issue.
`run_gunicorn.py`:
```
# Run with python3 simple_server.py PORT

from aiohttp import web


async def handle(request):
    return web.Response(body=b'OK')

print("RELOADED")

app = web.Application()
app.router.add_route('GET', '/', handle)
```
Gunicorn execution command:
`$ gunicorn run_gunicorn:app --worker-class aiohttp.GunicornWebWorker -b 127.0.0.1:8080`
Reload command:
`$ kill -HUP 24926`

**Comment by aptiko** [comment]
For the record, I found what the problem was. It seems to be a Gunicorn issue and not an `aiohttp.GunicornWebWorker` issue, and it's probably not a bug. I was using the `--config` option, like this:

    gunicorn --config=python:settings_gunicorn myapp.gunicorn_module:app

with `settings_gunicorn.py` being something like this:

    import some_minor_details_from_my_app

    worker_class = 'aiohttp.GunicornWebWorker'
    ...

The problem is that the import statement, although deceptively simple, resulted in some (in fact most) files of the app being (recursively) imported. This importing is done by the Gunicorn master process (which does not reload `settings_gunicorn.py` on HUP). Apparently whenever the Gunicorn master process starts a child process, the child process "inherits" whatever the master process has already imported. Therefore child processes do not really load the app in this case, they get it from the master.
