### ISSUE TITLE
Allow to mount subapp without prefix

### ISSUE THREAD

**Issue by kreopt** [aio-libs/aiohttp#2979]
## Long story short

In our project we have two backends: api and web site. Both of them inherits common middleware from base application and have some customization (like default response renderer, session engine, etc).
Only way to implement such architecture is to mount website to /web/ prefix and mobile api to /api/ prefix. But it is more desirable for web site to locate in root url instead of /web/. 

 
       RootApp(common middleware, config, etc)
        /                                  \
     "/web/" (jinja2, cookie auth)         "/api/" (json, token-based auth)

## Expected behaviour

Ability to mount subapp to root url like app.add_subapp('/', subapp)

 
       RootApp(common middleware, config, etc)
        /                                  \
      "/" (jinja2, cookie auth)            "/api/" (json, token-based auth)

**Comment by asvetlov** [comment]
It sounds like you want to attach middlewares to concrete web handler, not to the whole application/sub-application.

I understand your desire to have short URL paths but logically it looks weird. 
You can use redirections or URL rewriting on NGINX though.

**Comment by kreopt** [comment]
Not exactly right. I have common middleware and setup for web and mobile (database, geoip etc), then I inherit these middlewares in backends and extend with some backend-specific logic: template renderer, cookies, csrf check for website and token-based authentication for mobile.
If i use website as root application, then mobile subapp will inherit undesired middleware like csrf etc. If there is a way to avoid such inheritance - it will be solution too. But according to the docs, there is no way to do this.

**Comment by asvetlov** [comment]
My vision is: if you need a custom middleware for an URL -- you have to push the URL under some prefix.

If you disagree -- please try to make a Pull Request with your proposal.
