### ISSUE TITLE
Plugin for making restful APIs.

### ISSUE THREAD

**Issue by alexpantyukhin** [aio-libs/aiohttp#2987]
## Long story short

I'm inspired by the [flask-restful](http://flask-restful.readthedocs.io/en/latest/). I think it would be very good to have some similar plugin for the `aiotthp`. Any thoughts? I would start the work if it could be interesting.

**Comment by asvetlov** [comment]
It can be done in a separate library, isn't it?

UPD: there is https://github.com/atbentley/aiohttp-rest (I never used the plugin though).

**Comment by alexpantyukhin** [comment]
Oh I see. It really exists already :) thank you!
