### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yjqiang** [aio-libs/aiohttp#2992]
I have several different requests on different urls, like google.com, facebook.com, twitter.com. Should I just use one aiohttp.ClientSession for 3 requests or I use 'async with' to create 3 new different ClientSession and then close it at once? Because I wonder if the aiohttp.ClientSession is like the requests.Session, which should be used for the same host according to the doc.
"The Session object allows you to persist certain parameters across requests. It also persists cookies across all requests made from the Session instance, and will use urllib3’s connection pooling. So if you’re making several requests to the same host, the underlying TCP connection will be reused, which can result in a significant performance increase (see HTTP persistent connection)."

**Comment by yjqiang** [comment]
And if I use those three request in a loop and will be executed for many times, would it be better to create 3 ClientSession first, and use them for 3 different hosts or just create one ClientSession and use it for those 3 hosts.

**Comment by asvetlov** [comment]
Client session shared cookies and uses a connection pool under the hood.
The session can be used for calling different hosts as well.

Consider it as a browser window. How many open windows do you have?
Do you create a new window for every request or reuse the same one for browsing different sites?
The rule of thumb is the same.

**Comment by yjqiang** [comment]
@asvetlov "So if you’re making several requests to the same host, the underlying TCP connection will be reused, which can result in a significant performance increase (see HTTP persistent connection)."
So I think if I used one host frequently, I should new one ClienSession for it (keep open without using 'async with'). And for others, I can new another ClientSession for all of them (also keep open without using 'async with'). Am I right? Because the script may be kept running for 24h, so I think that would be a good solution.

**Comment by asvetlov** [comment]
Yes, this is a working plan
