### ISSUE TITLE
Uses class methods with aiohttp.web.RouteTableDef

### ISSUE THREAD

**Issue by modelmat** [aio-libs/aiohttp#2996]
## Long story short
Whenever you place a route as part of a class, it does not allow this to be possible, unless you remove te response argument, leaving just self (which creates problems as self is actually response).

## Expected behaviour
Provide the webpage as it would like this: 
```py
from aiohttp import web
import asyncio

routes = web.RouteTableDef()
app = web.Application()

@routes.get("/")
async def root(response):
    return web.Response(text="5")

app.add_routes(routes)
web.run_app(app)
```

## Actual behaviour
Errors with
```py
Error handling request
Traceback (most recent call last):
  File "D:\Program Files\Python3\lib\site-packages\aiohttp\web_protocol.py", line 385, in start
    resp = await self._request_handler(request)
  File "D:\Program Files\Python3\lib\site-packages\aiohttp\web_app.py", line 338, in _handle
    resp = await handler(request)
TypeError: root() missing 1 required positional argument: 'response'
```

## Steps to reproduce
Create and run this script
```py
from aiohttp import web
import asyncio

routes = web.RouteTableDef()
app = web.Application()

class Example:
    @routes.get("/")
    async def root(self, response):
        return web.Response(text="5")

app.add_routes(routes)
web.run_app(app)
```

## Your environment
Latest version of aiohttp (3.2.1)
Windows 10

**Comment by asvetlov** [comment]
In your example, web handler is not instantiated on decorator appliance time.
The decorated function is just a function, not bound method.

Maybe we can master something but I don't see a clean implementation yet.
Any idea is welcome.

**Comment by asvetlov** [comment]
Closing the issue.
If somebody wants to propose a robust implementation -- please open a new one.

**Comment by modelmat** [comment]
I have been thinking of an implementation, I just haven't got round to implementing it yet. Here's the basic outline:
- Create an alternative ClassRouteTableDef which returns a RouteTableDef class object
- You can add this by doing something along the lines of `add_routes(ClassWhichContainsTheRouteObjects())`
- Which can be run through and instantiated normally (as they now have a class)

Sorry for the late reply.

**Comment by asvetlov** [comment]
Feel free to make a PR with an implementation of your idea.

**Comment by modelmat** [comment]
I will when done 😜!

**Comment by phdowling** [comment]
Did anyone ever end up working on this? Would be a nice feature for sure.

**Comment by modelmat** [comment]
I've got a working implementation, will attempt some documentation (and possibly tests) and then do a PR.
The dask/dask#3317 issue only appears to be an issue for decorators that are classes and when actually replacing the decorated function.
