### ISSUE TITLE
codecov integration is broken

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2997]
I've tried both `bash` script and `codecov` package from PyPI.
Both ways are failing on uploading data to codecov server.

Looks like it is a result of migration to travis-ci.com but I don't sure.

Any ideas?

**Comment by webknjaz** [comment]
Show me the log link. I'd probably be able to fix it.
`codecov` script relies on certain env vars to identify whether it's running in CI and uses a shared token to upload reports, but this only happens if it identifies itself as running in a known CI env.

**Comment by asvetlov** [comment]
https://travis-ci.com/aio-libs/aiohttp/jobs/123752683 for bash script
https://travis-ci.com/aio-libs/aiohttp/jobs/123750170 for codecov plugin

**Comment by webknjaz** [comment]
It's weird, this https://codecov.io/gh/aio-libs/aiohttp/settings says that:
> GitHub Integration is installed. However, this repository is not enabled.
>
> Click here to your installation listings
Find Repository access and add aiohttp to the list.
May take a couple minutes for our system to get notices of new projects added.

And I don't have enough privileges to check/fix this. It suggests you to go to https://github.com/organizations/aio-libs/settings/installations/175267 and add aiohttp there. I don't have rights to do this.

**Comment by asvetlov** [comment]
The page reports that codecov is enabled for **all** repos :(

**Comment by webknjaz** [comment]
Try doing reset @ https://codecov.io/gh/aio-libs/aiohttp/settings

**Comment by webknjaz** [comment]
It looks like you're right and codecov's backend supposingly tries to go to the old platform's API (.org) and  fails (but that's just a guess).
Have you tried resetting it yet?

**Comment by asvetlov** [comment]
Just did it.
> Sorry, there was an issue: Authorization declined by github to create a webhook

**Comment by webknjaz** [comment]
I've emailed them.

**Comment by asvetlov** [comment]
I've tried to uninstall codecov and install it back again a couple days ago -- no luck.
Will do uninstalling now and install next day -- maybe the tool needs time to sync internal data.

**Comment by asvetlov** [comment]
Thanks

**Comment by asvetlov** [comment]
Recreated codecov project.
The history has gone away but nothing is fixed: https://travis-ci.com/aio-libs/aiohttp/jobs/124021867

**Comment by webknjaz** [comment]
@asvetlov Let's try https://coveralls.io instead. It's functionally equivalent, lots of cool projects seem to use it and I just love their UI

**Comment by webknjaz** [comment]
I've posted a question about whether they support new platform: lemurheavy/coveralls-public#1119

**Comment by asvetlov** [comment]
The project used coveralls.io but switched too codecov for better UI/UX

**Comment by webknjaz** [comment]
Anyway let's try it out while codecov doesn't work for us. They say we need:
```yaml
service_name: travis-pro
```
in `.coveralls.yml`.

**Comment by asvetlov** [comment]
Maybe we need to provide a secret key for codecov.
The documentation says that it is not needed for open sourced projects but maybe the tool assumes that `.com` means commercial support.

**Comment by samuelcolvin** [comment]
coveralls was much worse, no way to compare PRs, no diff coverage, harder to navigate code coverage.

@stevepeak has always been very helpful in the past for me. Perhaps he could help on this?

**Comment by stevepeak** [comment]
Looks like it's the new Travis-CI.org to .com switch. Let me see if we can patch that up quickly.

**Comment by stevepeak** [comment]
Waiting to get news from Travis-CI. Their old API endpoint on .org was public, which we used to confirm uploads. Now it's private on .com which broke our process and requiring the upload token.

**Comment by asvetlov** [comment]
Fixed by the service provider
