### ISSUE TITLE
Change appveyor account

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2998]
https://github.com/aio-libs/aiohttp/pull/2990#discussion_r187559585:

> This requires owner privileges AFAIR, so I can't. It's a bit tricky, but the bottom line is that you create a team there mapped to the team in GitHub and give it some access there. Also you need to somehow create an org link there.

> Here you go: https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization
Create a separate account called aio-libs and then add your personal account as its administrator. You can also create team mapped to some team in GitHub, allowing its members to cancel/rerun builds.

**Comment by webknjaz** [comment]
* https://ci.appveyor.com/project/aio-libs/aiohttp
* https://ci.appveyor.com/project/aio-libs/aiohttp-devtools
* https://ci.appveyor.com/project/aio-libs/multidict
