### ISSUE TITLE
Ctrl+C not work as excepted for aiohttp on windows

### ISSUE THREAD

**Issue by LanceLovereading** [aio-libs/aiohttp#3004]
## Expected behaviour
When the aiohttp standalone server is running, pressing Ctrl + C should stop it.
## Actual behaviour
It seems nothing has happend when I press Ctrl + C. However, after I press Ctrl + C, if I try to open the url in browser, the server will stop.
So I supposed Ctrl+C does not work immediately, it is just registered and need to be triggered by an http request to the server.

## Your environment
Windows 10
Python 3.6.5
aiohttp 3.2.1

**Comment by asvetlov** [comment]
It is a well known asyncio problem, nothing aiohttp specific and nothing that could be done on the project side.
