### ISSUE TITLE
Docs on WS messages iteration

### ISSUE THREAD

**Issue by decaz** [aio-libs/aiohttp#3006]
Within the docs (http://aiohttp.readthedocs.io/en/stable/client_quickstart.html#websockets) we have:
```python
...
async for msg in ws:
    ...
    elif msg.type == aiohttp.WSMsgType.CLOSED:
        ...
```
But within the code (https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_ws.py#L268) we have the following check:
```python
class ClientWebSocketResponse:
    ...
    async def __anext__(self):
        msg = await self.receive()
        if msg.type in (WSMsgType.CLOSE,
                        WSMsgType.CLOSING,
                        WSMsgType.CLOSED):
            raise StopAsyncIteration  # NOQA
        return msg
```
So we cannot get message of `WSMsgType.CLOSED` type - iteration would stop.

Does it mean that docs are incorrect concerning the check of closed websocket?

**Comment by asvetlov** [comment]
Sure doc is wrong.
Would you make a PR with documentation update?
