### ISSUE TITLE
Secure Websockets?

### ISSUE THREAD

**Issue by jnurmine** [aio-libs/aiohttp#301]
Do you have plans to support Secure Websockets? (wss://)

**Comment by ludovic-gasc** [comment]
I've on production some aiohttp servers with Web sockets. I use HAproxy 1.5 as reverse proxy for TLS layer (wss) and distribute load between several aiohttp daemons.
Moreover, if you want an all-in-one solution, it should be possible, one of aiohttp server examples permits to use TLS.

**Comment by asvetlov** [comment]
Secure websockets are supported. If you have found a bug with `'wss://'` connections please open more specific issue.

**Comment by jnurmine** [comment]
This is closed, but for the record, this was my bad, wss:// is indeed supported.

**Comment by sonicaj** [comment]
Apologies for not getting a thorough understanding of how wss is supported with aiohttp. Could you please refer some article/documentation/code which highlights it's usage ? Thank you

**Comment by MyNameIsCosmo** [comment]
@sonicaj Did you check the docs?
https://docs.aiohttp.org/en/stable/web_quickstart.html#aiohttp-web-websockets
https://docs.aiohttp.org/en/stable/client_quickstart.html#websockets
https://docs.aiohttp.org/en/stable/websocket_utilities.html#
