### ISSUE TITLE
Make TCPSite accept an already existing loop

### ISSUE THREAD

**Issue by sxpert** [aio-libs/aiohttp#3016]
this makes it trivial to use aiohttp inside an existing larger app

**Comment by asvetlov** [comment]
Why?

**Comment by sxpert** [comment]
so as to be able to integrate aiohttp within a much larger app, and use the already setup loop
I did add an example program in the PR

**Comment by sxpert** [comment]
when you have multiple threads, you need one loop per thread. hence you need to specify which loop is used

**Comment by asvetlov** [comment]
Why do you need multiple threads with a loop in each?

And why do you need passing a loop explicitly? 
Create a site in a thread which will use it. Simple and obvious.

**Comment by sxpert** [comment]
because some of the tasks I need would block the main loop (they are compute bound, not IO bound), so I'd send those task into their own thread, which will create it's own loop.

**Comment by sxpert** [comment]
> Create a site in a thread which will use it. Simple and obvious

wasn't so clear from the documentation...

**Comment by asvetlov** [comment]
If your tasks block the main loop -- you have an architectural problem.
You are trying to fix it by a workaround which introduces new potential problems.
`aiohttp` is not involved in this way.
Sorry, I'm closing the issue and PR
