### ISSUE TITLE
Setting response body using middleware leads to inconsistent Content-Length

### ISSUE THREAD

**Issue by alternativehood** [aio-libs/aiohttp#3025]
## Long story short

I am using a simple middleware handler that changes response body. `'CONTENT-LENGTH'` header is being set before response hits the middleware. There is a code in body setter that prevents this header from being changed if it was already set:

```python
     @body.setter
    def body(self, body,
             CONTENT_TYPE=hdrs.CONTENT_TYPE,
             CONTENT_LENGTH=hdrs.CONTENT_LENGTH):
            ...
            # set content-length header if needed
            if not self._chunked and CONTENT_LENGTH not in headers:
                size = body.size
                if size is not None:
                    headers[CONTENT_LENGTH] = str(size)
            ...
```

So, after a new body being applied to response, headers still have an old value. This causes issues on a client side - response body being cut, for example.

It is possible to workaround this issue by adding `response.headers.pop(hdrs.CONTENT_LENGTH)` before setting a new body.

## Expected behaviour

Being able to set body during a middleware handling properly.

## Actual behaviour

`'CONTENT-LENGTH'` header not being updated - causes issues on a client side.

## Steps to reproduce

Using aiohttp.test_utils. This example fails with `json.decoder.JSONDecodeError` due to reponse.content being `'{"my_new": "bo'`

```python
import http

from aiohttp import web, hdrs,  PAYLOAD_REGISTRY, JsonPayload
from aiohttp.test_utils import AioHTTPTestCase, unittest_run_loop
from aiohttp.web_app import Application
from aiohttp.web_middlewares import middleware
from aiohttp.web_request import Request


PAYLOAD_REGISTRY.register(JsonPayload, (dict, frozenset))


def body_setter_middleware():

    @middleware
    async def middleware_handler(request: Request, handler: web.View):
        response = await handler(request)
        # response.headers.pop(hdrs.CONTENT_LENGTH)
        response.body = {'my_new': 'body'}
        return response

    return middleware_handler


class HandlerOK(web.View):

    async def get(self):
        return web.Response(body={'test': 'ok'})


class TestBodyChanging(AioHTTPTestCase):

    def make_application(self):
        app = Application(loop=self.loop, debug=True)
        app.middlewares.append(body_setter_middleware())

        app.router.add_route('get', '/api/1/ok', HandlerOK)
        return app

    async def get_application(self):
        return self.make_application()

    @unittest_run_loop
    async def test_body_changes(self):
        response = await self.client.request('GET', '/api/1/ok')
        self.assertEqual(response.status, http.HTTPStatus.OK)
        result = await response.json()
        self.assertDictEqual(result, {'my_new': 'body'})

```

## Your environment

aiohttp==3.2.1
MacOS High Sierra 10.13.1
Python 3.6.3

**Comment by asvetlov** [comment]
Not sure if I want to fix this.
Modifying a body in by middleware is not a safe operation.
Consider streaming responses for example.
Even returning a new response is not safe if the current response has been started (streamed).
As a workaround, you can return a new response if the current one is not prepared.

**Comment by alternativehood** [comment]
Thanks. I would consider returning a new response.
