### ISSUE TITLE
allow partial payload to be returned

### ISSUE THREAD

**Issue by scotloach** [aio-libs/aiohttp#3026]
## Long story short

I'm querying a server that seems to be buggy; it returns a Content-Length header that is longer than the actual response, and the server disconnects once it has sent the response body.  The aiohttp client throws the following error when I try to read the response:
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

## Expected behaviour

There should be a way to get at the payload that's been read.  For example, curl outputs a useful warning but still returns the full body.

## Actual behaviour

This error is raised:
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
and there is no way (as far as I can tell) to get the body.

## Steps to reproduce

Do a GET request from a server that returns a body and closes the connection, after sending a Content-Length header that is larger than the actual body it sends.

## Your environment

Python 3.6.4, aiohttp 3.2.1.

**Comment by asvetlov** [comment]
How `requests` processes this case?
What to do for gzipped content?

**Comment by and800** [comment]
surprisingly, `requests` returns fetched payload without any error

**Comment by socketpair** [comment]
@scotloach try read body in streaming mode (https://docs.aiohttp.org/en/stable/streams.html#aiohttp.StreamReader.iter_any ) until you get error (and ignore it)

**Comment by scotloach** [comment]
To follow up: that worked as a workaround.
I still think the library should allow this though, without throwing an error, even if it's an extra config option to allow it.

**Comment by asvetlov** [comment]
Every config option has a maintenance cost.
If a buggy server can be processed -- that's fine, nothing to do more.
An error as a sign of partial payload is perfectly fine from my perspective.

**Comment by luvvien** [comment]
solved by [response payload is not completed](https://vien.tech/article72)
