### ISSUE TITLE
Defer opening ClientSession until __aenter__ is called

### ISSUE THREAD

**Issue by frederikaalund** [aio-libs/aiohttp#3028]
## Long story short

I kept getting warnings about [unclosed connections](https://github.com/aio-libs/aiohttp/blob/4a3cfb3250f91d4726408f9aa26b51c4ec088fde/aiohttp/client.py#L209). Turns out that a `ClientSession` is opened in the `__init__` function and not in the `__aenter__` function. I did not expect that.

## Expected behaviour

I expect that if you simply construct a `ClientSession`, it should not be considered `opened` yet. I think that the connection should first be considered `open` when `__aenter__` has been called. Just like a `file` object is not open before `__enter__` is called.

## Actual behaviour

I was surprised to find that `ClientSession`s are "opened" in `__init__` (because `_connector` is set there and that is the `opened` criterion).

I usually create my handles (be it files, connections, or the like) up front, and then open them later with the `with` statement.

## Proposed solution

Either:

 * Change the `ClientSession.opened` criterion to take into account whether `__aenter__` has been called or not.
 * Don't set `ClientSession._connector` in `__init__` but do it instead in `__aenter__`. You can store the connector temporarily in a new variable, say `ClientSession.__connector`, until `__aenter__` is called.

## Your environment

This applies to all recent version of aiohttp and python.

**Comment by asvetlov** [comment]
A warning about unclosed connections means that you did not use `await close()` *or* `async with`.

From the issue, I cannot figure out why you cannot do it.

**Comment by frederikaalund** [comment]
> A warning about unclosed connections means that you did not use await close() or async with.
> From the issue, I cannot figure out why you cannot do it.

Thanks for the reply. Let me try to clarify.

Here is an example of a context manager taken directly from PEP 343 (comments are mine):

```
class locked:
   def __init__(self, lock):
       # Construction does *not* open handles/acquire resources/etc.
       # It's only used for simple initialization.
       self.lock = lock
   def __enter__(self):
       # Enter is used to open handles/acquire resources/etc.
       self.lock.acquire()
   def __exit__(self, type, value, tb):
       # Exit is used to close handles/release resources/etc.
       self.lock.release()
```

Following this, I should be able to construct (init, not enter/exit) any context manager and and discard it *without* ever touching the underlying resources. That is, the following should be completely valid:

```
my_lock = locked(lock) # Only simple initialization. No resources are acquired.
other_initialization_that_raises()
# Oops, other_initialization_that_raises() raised an Exception.
# We never get to the with statement.
# No worries, since my_lock was never __entered__, no warnings or errors are raised.
with(locked):
    do_something()
```

This, however, is not possible with aiohttp's `ClientSession`:

```
my_session = aiohttp.ClientSession() # Erroneously considered `opened` already.
# my_session.opened == True: 'Session is already `opened` even though __enter__ hasn't been called.'
other_initialization_that_raises()
# Oops, other_initialization_that_raises() raised an Exception.
# We never get to the with statement.
# We get 'unclosed connection' warnings even though we haven't called __enter__ yet!
with(my_session):
    do_something()
```

**Comment by asvetlov** [comment]
The session becomes ready to use after constructor call.
The following example is 100% correct.
```
sess = aiohttp.ClientSession()
async with sess.get(url) as resp:
    pass
await sess.close()
```
`async with session` is a syntax sugar around `await sess.close()` call.

I don't see why should we change the current code. A session is "opened and ready to use" just after constructor call. like `ThreadPoolExecutor` and many other objects.

That's it.
