### ISSUE TITLE
Link changelog/changes.html from homepage?

### ISSUE THREAD

**Issue by hynek** [aio-libs/aiohttp#3029]
So just got a bunch of warnings around make_handler being deprecated and I’ve completely failed at finding any information on it until I looked into GitHub and switched to the 3.2 branch or searched for Changelog in the docs.

Am I missing something or is there no canonical way to find it? I would suggest to put the link right next to `Current version is 3.2.1.` at the top, like I do with [my projects](http://www.attrs.org/en/stable/).

**Comment by asvetlov** [comment]
Isn't https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst enough?
If you are looking for a link to docs from README page -- it's present twice, at the very top and as docs badge.
Changelog is present in docs as well: https://docs.aiohttp.org/en/stable/changes.html

**Comment by hynek** [comment]
Yeah well I overlooked CHANGES.rst because HISTORY.rst caught my eye first. And yeah https://docs.aiohttp.org/en/stable/changes.html exists but it is *very* hard to find: you have to click on “Miscellaneous” first since it seems to be missing from the Table of Contents.

It would be nice if https://docs.aiohttp.org/en/stable/changes.html would be easier to find.
