### ISSUE TITLE
Web server example leaves pending tasks

### ISSUE THREAD

**Issue by catlee** [aio-libs/aiohttp#303]
If I run the code from this example http://aiohttp.readthedocs.org/en/v0.14.4/web.html#run-a-simple-web-server, I end up with some errors in the console after hitting Ctrl-C:

``` python
serving on ('0.0.0.0', 8080)
^CTask was destroyed but it is pending!
task: <Task pending coro=<start() running at /home/catlee/.virtualenvs/proxxy2/lib/python3.4/site-packages/aiohttp/server.py:211> wait_for=<Future pending cb=[Task._wakeup()]>>
Future exception was never retrieved
future: <Future finished exception=ClientDisconnectedError()>
aiohttp.errors.ClientDisconnectedError
```

I only seem to get these if I've made requests to the server first. If I simply start the server and kill it before making any requests, I don't get these warnings.

**Comment by asvetlov** [comment]
Example from the docs is too trivial for implementing well-formed shutdown procedure.
Please take a look on full example at https://github.com/KeepSafe/aiohttp/blob/master/examples/web_ws.py
