### ISSUE TITLE
Doc: signals

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#3032]
https://docs.aiohttp.org/en/stable/web_advanced.html#aiohttp-web-signals

![default](https://user-images.githubusercontent.com/1157412/40615686-3d2bf414-62a1-11e8-8ebe-58fd05f49ecd.png)

signal handlers are always asynchornous now, so text is useless. Instead of this, we should write somthing like "All handlers must be asynchronous since version xxx"

**Comment by asvetlov** [comment]
Would you make a PR?

**Comment by socketpair** [comment]
Yes, maybe

**Comment by asvetlov** [comment]
Fixed by 530c726b
