### ISSUE TITLE
Multipart file form data with name

### ISSUE THREAD

**Issue by MattIPv4** [aio-libs/aiohttp#3034]
## Long story short

So I want to post a file as multipart data to a file uploading site.
The request payload needs to have the name 'files[]'.
I frankly have no idea how to do this and the documentation really isn't helping.

## Current code

```
# Generate multipart
mpwriter = MultipartWriter('form-data')
mpwriter.append(open(path, 'rb'), {'name': 'files[]', 'filename': os.path.split(path)[1]})

# Go, go, go
headers = {'Accept':'application/json'}
async with self.bot.session.post("https://rokket.space/upload",
                                                      data=mpwriter, headers=headers) as resp:
    print((await resp.text()))
```

This gives me a success from the uploader but the uploader never detects the file, which suggests the multipart file doesn't actually get given the name `files[]` as it should.

## Valid request example

This is an example of a valid request done through their site.
Headers: https://i.dabbitpri.me/azrr4yk7on.png
The beginning of the multipart file payload, containing the all important `name` and `filename`: https://i.dabbitpri.me/x2s2xie8dw.png

### Requests

This code, using requests, works perfectly: https://hastebin.com/ecemitilat.py

**Comment by eLvErDe** [comment]
Excuse me guy but why all ticket related to multipart key name are closed without a solution ?
I'm hitting exactly the same bug.

**Comment by asvetlov** [comment]
I guess if the issue creator closed it in the same day when opened -- he found the solution.

**Comment by MattIPv4** [comment]
@eLvErDe @asvetlov The issue was actually due to the bug I described in https://github.com/aio-libs/aiohttp/issues/3035 which people claim is now fixed. I haven't tested this as by the time it was fixed, I had already created a new solution to my issue.

**Comment by asvetlov** [comment]
#3035 bugfix is not released yet IIRC

**Comment by MattIPv4** [comment]
@asvetlov Following the PR chain, you end at https://github.com/aio-libs/aiohttp/pull/3479 which was merged before the release of 3.5.4?

**Comment by eLvErDe** [comment]
I ywasn't able either to create a multiform payload with file content attached and a specific name.

I ended up using: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/formdata.py which seems to be undocumented but worked, not sure about the drawbacks...

Regards

**Comment by asvetlov** [comment]
`FormData` is the *official* way to do it.
Sadly, it was not documented until #3755 and #3786

**Comment by eLvErDe** [comment]
So there's still something wrong because I cannot figure out reading the official documentation. Or maybe, these two PR are not released yet ?

**Comment by asvetlov** [comment]
Yes, PRs are not released. It is a new addition
