### ISSUE TITLE
Access to socket information when using AppRunner

### ISSUE THREAD

**Issue by hynek** [aio-libs/aiohttp#3036]
## Long story short

Sometimes I like to listen on port 0 to allow for any and need to access the actual port after binding.

## Expected behaviour

A public way to access socket information like the port number.

## Actual behaviour

I have to reach into the private `TCPSite._server`.

**Comment by asvetlov** [comment]
`TCPSite` works with IPv4/IPv6 addresses, `UnixSite` operates with Unix sockets.
The address format is different. Moreover, one *site* can have several sockets for dual IPv4/IPv6 stack.
I think we need a simple but robust solution that covers all cases.
Exposing `AbstractServer` is not the best idea may be: it opens `close()` method etc.

Perhaps the best approach is adding `addresses` property to *site* object which exposes a list of socket addresses in the same form as returned by `socket.getsockname()`.

**Comment by webknjaz** [comment]
> adding `addresses` property

I'd call it `bound_sockets`.

Also, it might be a good idea to have a data struct (class) for different socket binding types. Imagine if one would want their server to be bound to TCP socket, and then to UNIX file socket, and to abstract socket. It would be handy if one could `isinstance()` those sockets.

**Comment by asvetlov** [comment]
@webknjaz you can serve the single app on both Unix and TCP sockets right now: just create two sites with the same runner.

Let's postpone sockets exposing up to a concrete use case. I doubt if we need to expose the whole socket object, it is a leaking abstraction.

**Comment by webknjaz** [comment]
@asvetlov that's it. I was actually talking about that missing abstraction layer ;)
