### ISSUE TITLE
multipart tests

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#304]
@kxepal is that intentional? https://github.com/KeepSafe/aiohttp/blob/master/tests/test_multipart.py#L1260

**Comment by kxepal** [comment]
[Yes](http://greenbytes.de/tech/tc2231/#attwithfn2231utf8comp)

**Comment by fafhrd91** [comment]
What is the reason? If you do not use it mark it as skip or remove

**Comment by fafhrd91** [comment]
Ok, I see. Mark it as skip

**Comment by kxepal** [comment]
Are we're talking about the same test? Since those you pointed is used.

**Comment by kxepal** [comment]
Aaaa, sorry. Now I see. Definitely a typo (:

**Comment by kxepal** [comment]
Fixed in 68ad56a.
