### ISSUE TITLE
The Websocket Server can't disconnect when the client exit.

### ISSUE THREAD

**Issue by HolynnChen** [aio-libs/aiohttp#3043]
## Long story short
When i kill a client which have connected the server, the server can't catch it.

## Expected behaviour
The heartbeat or receive_timeout can make a closed msg, that i can catch it.

## Actual behaviour
The Server just keep waiting for msg, catch nothing

## Steps to reproduce
This is the Server side code.
```python3
@routes.get('/ws')
async def webscoket(request):
    ws=web.WebSocketResponse(heartbeat=1, receive_timeout=5)
    await ws.prepare(request)
    name=None
    async for msg in ws:
        if msg.type == aiohttp.WSMsgType.CLOSED:
            print('offline',name)
            break
        if msg.type == aiohttp.WSMsgType.ERROR:
            print('error', name)
            break
        json=msg.json()
        print(json)
        if(json['command']=='info'):
            name = json['name']
            await ws.send_json({'command':'test','mod_name':'command'})
```

## Your environment
Python 3.6.1
aiohttp 3.1.3
Win10

**Comment by asvetlov** [comment]
Catching `asyncio.CancelledError` could help

**Comment by asvetlov** [comment]
You should return a rwebsocket response object from web-handler, not `None`

**Comment by HolynnChen** [comment]
it work.Thanks a lot 👍
