### ISSUE TITLE
Uvloop raises a warning when I use aiohttp.test_utils.loop_context

### ISSUE THREAD

**Issue by JoseKilo** [aio-libs/aiohttp#3044]
## Long story short

I'm getting a warning when I combine the latest version of `uvloop` with the test utils from aiohttp (`aiohttp.test_utils.loop_context`).

The PR that added the warning in uvloop: https://github.com/MagicStack/uvloop/pull/156/files

The line that triggers the warning in `aiohttp`: https://github.com/aio-libs/aiohttp/blob/0933b6c3eaf679b0b7b0ba46b97f25f1f55f4b87/aiohttp/test_utils.py#L421

I have tried to remove that line from aiohttp and it doesn't seem to break any tests.

The warning message:

```
test_aiohttp_uvloop.py::test_aiohttp_uvloop
  /usr/lib/python3.6/asyncio/unix_events.py:815: RuntimeWarning: !!! asyncio is trying to install its ChildWatcher for SIGCHLD signal !!!
  
  This is probably because a uvloop instance is used with asyncio.set_event_loop(). The correct way to use uvloop is to install its policy: `asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())`
  
  
    loop.add_signal_handler(signal.SIGCHLD, self._sig_chld)
```

## Expected behaviour

No warning 

## Actual behaviour

A warning is raised from uvloop

## Steps to reproduce

I have prepared a small test to reproduce the problem, I run it using `pytest`.

```python
import asyncio

from aiohttp.test_utils import loop_context
import uvloop


def test_aiohttp_uvloop():
    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

    with loop_context():
        pass
```

## Your environment

SO: Ubuntu 16.04.4 LTS

I'm using Python 3.6

My `pip freeze`

```
aiohttp==3.2.1
async-timeout==3.0.0
atomicwrites==1.1.5
attrs==18.1.0
chardet==3.0.4
idna==2.6
idna-ssl==1.0.1
more-itertools==4.2.0
multidict==4.3.1
pkg-resources==0.0.0
pluggy==0.6.0
py==1.5.3
pytest==3.6.0
six==1.11.0
uvloop==0.10.0
yarl==1.2.4
```

**Comment by asvetlov** [comment]
@1st1 aiohttp installs a new test loop as default by `asyncio.set_event_loop()` before every test execution.
IFAIK `pytest-asyncio` does the same.
`uvloop==0.10` raises a warning on this call.
What is the recommended workaround for it?

**Comment by 1st1** [comment]
Just as the warning suggests: setting a uvloop event loop policy before using uvloop with `asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())`

**Comment by 1st1** [comment]
uvloop does not use or support child watchers, so don't try to call `watcher.attach_loop(loop)` on it.

**Comment by asvetlov** [comment]
Fixed by #3046

**Comment by JoseKilo** [comment]
Thank you both for the quick reply and the fix :+1:

**Comment by 1st1** [comment]
Thanks!
