### ISSUE TITLE
Raised warning when running specs following the spec documentation (although the docs are potentially out of date)

### ISSUE THREAD

**Issue by Rambatino** [aio-libs/aiohttp#3061]
## Long story short

Following the testing docs here: https://aiohttp.readthedocs.io/en/v0.22.3/testing.html

Specifically the `Unittest example`

I've recreated it (although without the loop part as I believe that's been deprecated).

Here:

``` python
import json
from aiohttp.test_utils import AioHTTPTestCase, unittest_run_loop
from aiohttp import web
from app import app

class MyAppTestCase(AioHTTPTestCase):
    def get_app(self):
        return app

    @unittest_run_loop
    async def test_healthz(self):
        request = await self.client.get("/healthz")
        assert request.status == 200
        text = await request.text()
        assert '{"status": "OK"}' == text

    @unittest_run_loop
    async def test_data_1(self):
        test_dict = {
            'survey_response_id': '10',
            'responses': [
                {'type': 0, 'data': 'love it'},
                {'type': 0, 'data': 'ugly colour label'},
            ],
            'response_time': 9,
            'benchmark_time': 9
        }

        request = await self.client.post(
            "/quality/rate_respondent",
            json=test_dict,
            headers={'Content-Type': 'text/json', 'Accept': 'text/json'}
        )
        assert request.status == 200
        text = await request.text()
        assert {"survey_response_id": "10", "quality_score": "GOOD"} == json.loads(text)
```

It's a simple enough spec. Individually they both pass, but I can't run both. It returns: `RuntimeError: web.Application instance initialized with different loop`

If i comment out the if block (https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_app.py#L123) it works as expected, although I imagine there is some inefficiency with regards too loop creation.

## Expected behaviour

My specs don't break at web_app.py#L123

## Actual behaviour

``` bash
self = <Application 0x106637a20>, loop = <_UnixSelectorEventLoop running=False closed=False debug=False>

    def _set_loop(self, loop):
        if loop is None:
            loop = asyncio.get_event_loop()
        if self._loop is not None and self._loop is not loop:
            raise RuntimeError(
>               "web.Application instance initialized with different loop")
E           RuntimeError: web.Application instance initialized with different loop
```

## Steps to reproduce

Add two @unittest_run_loop decorators

## Your environment

aiohttp (3.3.1)

**Comment by Rambatino** [comment]
N.B it's actually to do with the reference of 'app'. I think it's expecting a new app each time. E.g. web.Application(), rather than the imported app...

**Comment by asvetlov** [comment]
You are referring to documentation of aiohttp version 0.22.3.
It's quite old and outdated.

**Comment by Rambatino** [comment]
Yeah I figured. I imagine there's not newer documentation? I've tried to modify the code so it works with version 3.3.1, but I can't figure it out.

**Comment by Rambatino** [comment]
I think it's specifically this bit:

``` python
from app import app

class MyAppTestCase(AioHTTPTestCase):
    def get_app(self):
        return app
```

Which is called multiple times with different loops.

**Comment by Rambatino** [comment]
Okay, my current workaround is to reload the module. Let me know what the correct way of doing this is:

``` python
import app
import importlib

class MyAppTestCase(AioHTTPTestCase):
    def get_app(self):
        importlib.reload(app)
        return app.app
```

**Comment by asvetlov** [comment]
aiohttp discourages application creation at module level.
See https://demos.aiohttp.org/en/latest/ (and demos code from https://github.com/aio-libs/aiohttp-demos) for recommended practices of project structure.

**Comment by Rambatino** [comment]
Okay thanks! 👍
