### ISSUE TITLE
'UrlDispatcher' object has no attribute 'add_options'

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#3062]
with

```py
web.route(METH_OPTIONS, '/foo/', foo, name='foo'),
```

https://github.com/aio-libs/aiohttp/blob/d8831f36d0ba1c7e2ffa7f5442e14d020de98bb8/aiohttp/web_routedef.py#L35-L41

`OPTIONS` is included in `METH_ALL`, however [`UrlDispatcher`](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_urldispatcher.py#L785) has no `add_options` method.

I believe this is a bug.

**Comment by asvetlov** [comment]
Yes, indeed!
Would you fix it?

**Comment by samuelcolvin** [comment]
done.
