### ISSUE TITLE
multipart BodyPartReaderPayload filename wrong

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#3064]
https://github.com/aio-libs/aiohttp/blob/d8831f36d0ba1c7e2ffa7f5442e14d020de98bb8/aiohttp/multipart.py#L446-L448

Maybe I'm missing something, but this looks wrong, shouldn't it be `value.filename`?

**Comment by asvetlov** [comment]
I don't know.
@kxepal could you take a look?
I'm pretty busy now. Will have a time next week.

**Comment by samuelcolvin** [comment]
happy to correct and write unit tests, but I need to check I'm not missing something before I go any further.

**Comment by asvetlov** [comment]
For me it looks like a typo which should be fixed.

**Comment by kxepal** [comment]
Yeah. Definitely a copy-paste typo.

**Comment by samuelcolvin** [comment]
ok, I'm manic this week, but will try to provide a fix next week. I noticed it because this function doesn't have very good coverage, so will try to improve that too.

**Comment by asvetlov** [comment]
Cool!

**Comment by asvetlov** [comment]
Fixed by #3094
