### ISSUE TITLE
Question: What's timeout?

### ISSUE THREAD

**Issue by yjqiang** [aio-libs/aiohttp#3066]
" class aiohttp.ClientSession(*, connector=None, loop=None, cookies=None, headers=None, skip_auto_headers=None, auth=None, json_serialize=json.dumps, version=aiohttp.HttpVersion11, cookie_jar=None, read_timeout=None, conn_timeout=None, timeout=sentinel, raise_for_status=False, connector_owner=True, auto_decompress=True, proxies=None)

timeout – a ClientTimeout settings structure, 5min
total timeout by default. "
This is from https://docs.aiohttp.org/en/stable/client_reference.html. But I don't understand if it means that the timeout for each get/post request or the timeout for the connection pool. And if it is for the connection pool, how can I set the timeout for each request? Like, http://docs.python-requests.org/en/master/user/quickstart/#timeouts.

**Comment by asvetlov** [comment]
Is https://docs.aiohttp.org/en/stable/client_quickstart.html#timeouts enough?

**Comment by yjqiang** [comment]
Sorry, maybe it is because my English is not good enough, but I'm still not sure about that.

**Comment by yjqiang** [comment]
For example, I use one clientsession to make several requests. And because the programme will run for hours, I won't close the session. I want to set the timeout for each request, so that if I don't get the response in 3s, I will try this again. So how can I make it?

**Comment by asvetlov** [comment]
`async with session.get(url, timeout=...)`

**Comment by yjqiang** [comment]
Although I have differents requests, but I want to set the same timeout for each request. So can I write like aiohttp.ClientSession(timeout=3)?

**Comment by asvetlov** [comment]
Yes, you can.

I think we can close the issue.
