### ISSUE TITLE
Example http server not work on Windows 7

### ISSUE THREAD

**Issue by xukku** [aio-libs/aiohttp#307]
I use ActiveState Python 3.4.1
I install asyncio and aiohttp adn chardet
Trying to start server example from http://aiohttp.readthedocs.org/en/v0.14.4/

python httpserver.py

I got:

Traceback (most recent call last):
  File "C:\bin\Python\lib\asyncio__init__.py", line 16, in <module>
    from . import _overlapped
ImportError: cannot import name '_overlapped'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "httpserver.py", line 1, in <module>
    import asyncio
  File "C:\bin\Python\lib\asyncio__init__.py", line 18, in <module>
    import _overlapped  # Will also be exported.
ImportError: No module named '_overlapped'

**Comment by fafhrd91** [comment]
That is not aiohttp related. You need to install asyncio from binary package or compile c extension

**Comment by xukku** [comment]
Thanks.
i install other python from https://www.python.org/downloads/
and problem solved.
