### ISSUE TITLE
AJAX request fails to certain route

### ISSUE THREAD

**Issue by jsandovalc** [aio-libs/aiohttp#3071]
Hi everyone, and thanks for the amazing work with aiohttp.
## Long story short

I have an aiohttp.web application with a subapp named `api` under `/api/v1`. In `api` y have two routes defined like this:

```python
def setup_routes(app):
    app.router.add_post('/ads', views.upload_img, name='images')
    app.router.add_get('/ads/{place_id}', views.get_images, name='get-images')

```
From ajax, I try to query the a url like `/api/v1/ads/1` like this:

```javascript
         $.get({
             url: ' /api/v1/ads/1?page=1',
         }).done(function (data) {
             console.log(data);
         }).fail(function (xhr, status, error) {
             console.log('Error');
         });
```

## Expected behaviour
I expect the request to reach the view  `get_images` so that the javascript client code gets the json with the ads objects.
## Actual behaviour
The ajax request fails and it does not show up in the network tab of the developer tools. I don't see any logs in the server side and the javascript code only says `error` and status code is 0.

But, if I try the same query with `curl`, it works ok! (`curl localhost:8080/api/v1/ads/1`).

If I change the routes to something like:

```python
def setup_routes(app):
    app.router.add_post('/ads', views.upload_img, name='images')
    app.router.add_get('/images/{place_id}', views.get_images,
                       name='get-images')
```
and update the js code, it works!. This is the way I solved the problem, but I think it should work fine with `/api/v1/ads/1`.

## Steps to reproduce

I have not isolated the problem, but I described the problem in the other sections of this issue. I just would like some pointers in how to debug this problem. I tried setting `debug=True` in the app but there is no any kind of output.  The logging module level is set to DEBUG.

## Your environment

aiohttp: 3.3.1
python: 3.6.4
OS: Debian GNU/Linux (testing)

Thanks for any help.

**Comment by asvetlov** [comment]
Maybe you need to read something about [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) ?

**Comment by jsandovalc** [comment]
Thanks for your answer.

Not completely sure, but I'd say it isn't CORS. I have no multiple origins and I have more ajax requests to the subapp `api` similiar to this one that work fine.

And the weirdest thing for me is that it gets "fixed" by changing the route from /ads/{place_id} to /images/{place_id} (or other name different to ads). The only other similar route to `/ads/{place_id}` is `/ads` that I showed in the code example.

**Comment by asvetlov** [comment]
Sounds really strange.
If you can fetch a resource with curl and has no CORS protection problem -- browser should work fine.

**Comment by livercat** [comment]
Do you by chance have an adblocker enabled in your browser? It might have a rule to block all /ads/* requests.

**Comment by jsandovalc** [comment]
@livercat That's it!. Sorry for the silly question. Anyway, I'll change those routes to have no future problems in production environments.

Thanks and to you to @asvetlov .
