### ISSUE TITLE
trust_env doesn't works

### ISSUE THREAD

**Issue by cartosco-hub** [aio-libs/aiohttp#3075]
## Long story short

Passing trust_env=True in ClientSession doesn't works

## Expected behaviour

Try to connect to proxy

## Actual behaviour

Doesn't connect to proxy

## Steps to reproduce

trust_env=True

env Vars setted http_proxy HTTP_PROXY https_proxy and HTTPS_PROXY
client connect directly to endpoint instead to connect with proxy

If I set proxy=http://myproxy.es the client works and try to connect with proxy but with trust_env method doesn't work

**Comment by asvetlov** [comment]
What `aiohttp.helpers.proxies_from_env()` returns on your box?

**Comment by cartosco-hub** [comment]
--------- CODE ---------
print (os.environ.get('HTTP_PROXY'))
print(os.environ.get('HTTPS_PROXY'))
helpers = aiohttp.helpers.proxies_from_env()
print(helpers)
print(self._session._trust_env)

--------- OUTPUT ---------
http://myproxy.es
https://myproxy.es
{'http': ProxyInfo(proxy=URL('http://myproxy.es'), proxy_auth=None)}
True

**Comment by asvetlov** [comment]
The problem is https://myproxy.es proxy for `HTTPS_PROXY` env var. 
aiohttp doesn't support it.
If you enable logging you'll see `"HTTPS proxies %s are not supported, ignoring"`.
Use `http://myproxy.es` as the value.

**Comment by cartosco-hub** [comment]
ok, this is exactly the problem, thanks for your quick response :-)
