### ISSUE TITLE
PyPI archive does not contain vendor/http-parser/http_parser.h

### ISSUE THREAD

**Issue by moubctez** [aio-libs/aiohttp#3076]
## Long story short
The archive distributed on PyPI.org does not contain `vendor/http-parser/http_parser.h`, so compilation fails with:
```
aiohttp/_http_parser.c:589:10: fatal error: '../vendor/http-parser/http_parser.h' file not found
```

## Expected behaviour
aiohttp package on PyPI.org contains `vendor/http-parser/http_parser.h`

## Actual behaviour
The file is missing, but required by `vendor/http-parser/http_parser.c:
```
#include "http_parser.h"
```

## Steps to reproduce
Download aiohttp-3.3.1.tar.gz from https://pypi.org/project/aiohttp/#files and build.

**Comment by asvetlov** [comment]
Thank you for the report
