### ISSUE TITLE
Remove reader parameter from request.multipart()

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3090]
The parameter exists from the very beginning, it is declared as:
```
    async def multipart(self, *, reader=multipart.MultipartReader):
```
I found that we can drop it: `reader` is always `multipart.MultipartReader`, aiohttp doesn't provide an alternative multipart reader implementation.

I have a problem with adding type hints to the method. Now it can return anything which is returned by `reader(headers, content)` call.  Dropping the parameter allows specifying the method return type without any functionality lose.

@kxepal maybe you have a comment?

**Comment by kxepal** [comment]
IIRC it was made exactly for alternative implementations which the end user may have (something special, patched or fixed, but he's unable to upgrade aiohttp) and tests when you may be need eventually some mocked MultipartReader. 

Personally, I'm not user of this one, but may be someone found it useful. If nobody argue - let's do that. Not all features are useful as their authors were thought.
