### ISSUE TITLE
HTTPException should retain cause information

### ISSUE THREAD

**Issue by jcjf** [aio-libs/aiohttp#3096]
## Long story short

I would like to use a pattern like:
```python
try:
    do_something()
except SomeException as e:
    raise HTTPInternalServerError(reason='My message') from e
```
with cause information retained. Does it make sense to implement `HTTPException.__bool__()` to always `True`?

## Expected behaviour

Two tracebacks separated by `The above exception was the direct cause of the following exception:`

## Actual behaviour

The cause information is lost, because `traceback.TracebackException` evaluates the [truthiness of the exception value](https://github.com/python/cpython/blob/de86073a761cd3539aaca6f886a1f55effc0d9da/Lib/traceback.py#L464) to determine whether cause lines are produced. For `HTTPException`, [truthiness is resolved](https://github.com/aio-libs/aiohttp/blob/7cf5785f5383ee67756d0f8d86ea3516b823b940/aiohttp/web_response.py#L426) via `StreamResponse.__len__()` which returns 0.

**Comment by asvetlov** [comment]
Yes, looks like `__bool__` is the best we can do in the situation.
Would you make a Pull Request?
