### ISSUE TITLE
aiohttp middleware and replacing a request in flight

### ISSUE THREAD

**Issue by jerblack** [aio-libs/aiohttp#3097]
Hi, I am trying to build a middleware that attempts to automatically add slashes to the end of uris that are missing them to avoid having to double-define all my routes with and without a trailing slash to ensure no one 404s. I saw your normalize_path_middleware and started with that, but I can't use anything that's going to force a redirect on the client. I need to be able to accomplish the same thing entirely on the server side.

Here's my attempt at that middleware, which just clones the request with a new rel_url and passes that along, but I still am getting 404s when I don't include a trailing backslash in my uris. Any ideas? Thanks.

```python
from aiohttp.web_urldispatcher import SystemRoute

def middleware(f):
    f.__middleware_version__ = 1
    return f

def trailing_slashes():
    @middleware
    async def impl(request, handler):
        if isinstance(request.match_info.route, SystemRoute):
            rel_url = str(request.rel_url)
            if '?' in rel_url:
                path, query = rel_url.split('?', 1)
                query = f'?{query}'
            else:
                path = rel_url
                query = ''
            if not path.endswith('/'):
                rel_url = f'{path}/{query}'
                request = request.clone(rel_url=rel_url)

        return await handler(request)

    return impl
```
And here is a sample class that implements it.
```python
from aiohttp import web
import slashes_mw

class ClassName(object):
    def __init__(self):
        self.app = web.Application(middlewares=[slashes_mw.trailing_slashes()])
        self.app.add_routes(self.get_routes())
        web.run_app(self.app, port=80, host='0.0.0.0')

    def get_routes(self):
        return [
            web.get('/', self.handler),
            web.get('/{name}/', self.handler)
        ]

    def handler(self, request):
        return web.Response(text='hello')

ClassName()
```

**Comment by asvetlov** [comment]
There is something wrong if you cannot use redirects on your site.

**Comment by jerblack** [comment]
It's not a site, it's an API that will be exposed to IoT devices that won't be able to redirect to another url.

**Comment by asvetlov** [comment]
I see nothing bad with registering a handler twice than.
It works faster than middleware processing BTW.

**Comment by jerblack** [comment]
Can I get a yes or no answer on whether or not the technical question I am asking is possible?

**Comment by asvetlov** [comment]
Well, if you insist.
You need to call `app.router.resolve()` to find a new `match_info` and call a new handler.
Not sure if there are no pitfalls (another middlewares for a new route, API forward compatibility etc) -- it touches a private API.
Anyway reading https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_app.py#L313-L352 can help you to master something.
