### ISSUE TITLE
Question: Raising exception before awaiting response body skips its download?

### ISSUE THREAD

**Issue by sonirico** [aio-libs/aiohttp#3109]
Let's say I have a piece of code like this:

```python
    async with session.get(url, **http_request_config) as response:
        if response.headers['Content-Length'] > 1024:
            raise Exception("Max body size exceeded!")

        body = await response.text()

        if 400 <= response.status < 500:
            if not body:
                raise general_exceptions.TargetNotFound
        elif response.status > 499:
            raise general_exceptions.TargetInternalServerError
```

Would the body actually downloaded from the server? I could make use of a `HEAD` request and perform the check there, but I want to cover the case where responses may be tricked to display an arbitrary number on `Content-Length` header based on HTTP verbs.

**Comment by asvetlov** [comment]
The body is not downloaded.
Part of it could be in the internal buffer already on the moment of raising the exception but if the body is huge -- the tail is not fetched.

**Comment by sonirico** [comment]
Ok! I thought that response body might still be temporary stored in an internal buffer at socket level or whatever, in detrimental of performance as synchronous clients do. Do you know a good reading to better understand the request/response lifecycle? Thanks!
