### ISSUE TITLE
Publish OS-specific binary wheels for Python 3.7 @ PYPI

### ISSUE THREAD

**Issue by wwqgtxx** [aio-libs/aiohttp#3111]
the Python3.7 was released, would the py37 wheels add to pypi.org?

**Comment by Victor-Savu** [comment]
Just ran into a problem with `poetry` due to this. It would be great to have the wheel now :) especially since aiohttp has the classifier `Programming Language =  Python :: 3.7`

**Comment by webknjaz** [comment]
We'll have to wait until we actually can do it within the current test infrastructure.
