### ISSUE TITLE
Every request object is equal

### ISSUE THREAD

**Issue by frmdstryr** [aio-libs/aiohttp#3116]
It seems the `==` operator evals to `True` for every request object.

```python
from aiohttp.test_utils import make_mocked_request

def test_path_equals():
    req = make_mocked_request('GET', '/a/')
    req2 = make_mocked_request('GET', '/b/')
    assert req.path != req2.path
    assert req != req2

def test_method_equals():
    req = make_mocked_request('GET', '/a/')
    req2 = make_mocked_request('POST', '/a/')
    assert req.method != req2.method
    assert req != req2
    
def test_equals():
    req = make_mocked_request('GET', '/this/isnot/evenclose')
    req2 = make_mocked_request('OPTIONS', '/search?query=what')
    assert req.path != req2.path
    assert req.method != req2.method
    assert req != req2
```

Is this intentional?

**Comment by asvetlov** [comment]
The problem is exactly the same as #3107 for response
Comparison and hashing should be disabled for request objects.
I very curious what is your use case for requests comparison.

**Comment by frmdstryr** [comment]
The [template engine](https://github.com/codelv/enaml-web) I use builds a dom and automatically updates necessary parts of the page (form fields or user specific content) when the request changes.  

Since all the requests were equal, it wasn't updating automatically.  I just patched requests to use the id for comparison.

```python
from aiohttp.web_request import BaseRequest

#: Equals returns true even though the requests are completely different
BaseRequest.__eq__ = lambda self, other: id(self) == id(other)

```

**Comment by asvetlov** [comment]
Understood. Thanks.
