### ISSUE TITLE
3.4.0 release

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#3118]
Please can we have a new release.

In particular, I need #3062, since it's a bug and there's no easy workaround for it.

~~The 3.3 milestone has a lot of stuff on it, if there's no plan to release for a while, perhaps #3062 would be backported as a patch?~~

**Comment by kxepal** [comment]
We already have 3.3.2 release. Did you mean 3.4.0?

**Comment by samuelcolvin** [comment]
sorry, yes.

**Comment by samuelcolvin** [comment]
@asvetlov?

**Comment by asvetlov** [comment]
Sorry, was pretty busy last weeks.
Yes, it's time for aiohttp 3.4
Please let me review open issues first. 
Maybe we can close some of them quickly.

**Comment by samuelcolvin** [comment]
Great, sorry to hassle.

**Comment by webknjaz** [comment]
I think I've adjusted CIs to produce wheels for 3.7 as well ;)

**Comment by apatrushev** [comment]
Please take care of #3162

**Comment by samuelcolvin** [comment]
bump, any update on this? I'm still waiting on #3062.

**Comment by asvetlov** [comment]
The showstopper is: I'd like to publish a new multidict release with Python 3.7 wheels first.
Now we have problems with building macosx wheels on Travis.
@webknjaz is working on it but still no success (after that I expect the same fix for aiohttp itself is needed).
As an alternative, we can drop MacOSX wheels entirely (very tempting solution BTW)

**Comment by webknjaz** [comment]
@asvetlov that issue is related to me breaking Travis config during migration to tox. This one should be good to go.

**Comment by kxepal** [comment]
@webknjaz offtopic a bit, but why tox? No trolling, just curiouosity.

**Comment by kxepal** [comment]
Thanks! Going to join on watching this experiment. I had tried tox once upon a time, but things turned too much complicated with no oblivious profit /: May be today will be different picture or I'd missed something.

**Comment by webknjaz** [comment]
@kxepal tox still tends to be complicated :(
However, it would let us achieve the long-term goal of unification, where users will be able to run the same envs/tests as CIs.
Also, this makes it better portable across CIs whenever you want to migrate/add new ones.
Among nice things: virtualenv caching/reuse/isolation (different env for each task by default, can be changed; reuse of settings from other envs; env matrix generation (so-called factors).

**Comment by samuelcolvin** [comment]
Released

**Comment by samuelcolvin** [comment]
No problem, we all have busy lives.
