### ISSUE TITLE
Using client sessions without a context manager

### ISSUE THREAD

**Issue by aliceh75** [aio-libs/aiohttp#3119]
It would be useful to be able to use ClientSession without a context manager.

Looking at the code:
- `ClientSession.__aenter__` does not do anything (See https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L827 );
- `ClientSession.__aexit__` only does `await self.close()` (See https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L830).

So the following currently works:

```python
    session = ClientSession()
    async with session.get('...'):
        # ...
    await session.close()
```

However the documentation doesn't specify whether we can rely on this behaviour. I can see three options:

1. Make the current behaviour official by documenting it;
2. Add a different way to use ClientSession without a context manager (I would guess the main change would be to add an async `ClientSession.start()` even if it currently does nothing for future-proofing);
3. Do nothing, and document the fact people shouldn't rely on the current behaviour (people can always call `__aenter__` and `__aexit__` directly, I understand it's an accepted thing to do).

I'm happy to help and do a PR for whichever solution you prefer.

**Comment by asvetlov** [comment]
@aliceh75 sorry for delay.
Your snippet is correct, it is the *official* way for working with `ClientSession` without async context manager.
I thought it is obvious but looks like we need to document it explicitly.
Please feel free to make a PR with docs update.

The only neat: `client = aiohttp.ClientSession()` should be called from an async function, the session creation without active (running) event loop raises a user warning.
