### ISSUE TITLE
Can StreamReader replace FlowControlStreamReader ???

### ISSUE THREAD

**Issue by kzinglzy** [aio-libs/aiohttp#313]
From the source code, I found that the only difference between FlowControlStreamReader and StreamReader is  each method at FlowControlStreamReader is a  simple wrapper from StreamReader.

For example, here is the `read` method at FlowControlStreamReader:

```
self._stream.resume_stream()
 try:
        return (yield from super().read(n))
    finally:
        self._stream.pause_stream()
```

I also found  that the FlowControlStreamReader is use to be a `request payload`

My confusion is that, why we have to `resume_stream` first and finally `pause_stream` at the end, can't we just use `StreamReader` to replace `FlowControlStreamReader` as a `request payload` ?

Thanks a lot !

**Comment by fafhrd91** [comment]
it is not possible to replace FlowControlStreamReader, it is required for flow control on socket transport. without it upload or download of big payloads would use all memory.
