### ISSUE TITLE
Template Not found on testing.

### ISSUE THREAD

**Issue by mawaishanif** [aio-libs/aiohttp#3130]
## Long story short

When testing the app the jinja template does not get found.

## Expected behaviour

I want the templates to be found so the apps can be tested.

## Actual behaviour

I get template not found error, when testing otherwise its working fine. I'm running the app on dev server from aiohttp-devtools

## Steps to reproduce

Make route whom handler returns a template using aiohttp-jinja2

## Your environment

windows
aiohttp 3.3.2

**Comment by asvetlov** [comment]
Sorry, looks like `aiohttp` bug tracker is a wrong place for template problem reports.

I can say that `aiohttp-jinja2` has nothing special, it is just a thin wrapper around `jinja2` itself.
I guess you have a configuration problem in a part of specifying a path to templates.

Without looking at the code I cannot say more.
