### ISSUE TITLE
Too many 301 redirects

### ISSUE THREAD

**Issue by amarynets** [aio-libs/aiohttp#3132]
## Long story short

`aiohttp.ClientSession.get()` does 10 301 redirection and return empty text response

## Expected behaviour

Passing the URL, get a not empty response

## Actual behaviour

I make a request and in `history` of the `response` object I see 10 redirections with status code 301 and text of response is empty, I tried to make this request with `curl` and `requests` and the result was successful. got this result for `url1 and url2`

## Steps to reproduce

```
import asyncio
import aiohttp

url1 = 'https://www.jonathanadler.com/art/by-artist/slim-aarons/slim-aarons-andldquo%3Bverbier-vacationandrdquo%3B-photograph/19135.html'
url2 = 'https://www.jonathanadler.com/furniture/by-category/benches-and-ottomans/x-bench/24-1900005.html?dwvar_24-1900005_base=NoBase&dwvar_24-1900005_quickShip=custom&dwvar_24-1900005_fabric=AntwerpSea&dwvar_24-1900005_fabricType=TexturedWoven'

async def request(url):
    async with aiohttp.ClientSession() as session:
        async with session.get(url, allow_redirects=True) as response:
            return response, await response.text()

async def check(url):
    response, text = await request(url)
    print(response.history)

loop = asyncio.get_event_loop()
loop.run_until_complete(check(url1))
```

## Your environment
ubuntu 16.04, Python 3.6, Client
aiohttp==2.3.2
Also, tried aiohttp==3.3.2, and got exception `line 418, in _request
    history[0].request_info, tuple(history))
aiohttp.client_exceptions.TooManyRedirects: 0, message=''`

**Comment by amarynets** [comment]
I increased num of redirects to 30, but it doesn't help. I've checked the history of `requests` response and it is empty

**Comment by asvetlov** [comment]
aiohttp 2.3 is not supported, aiohttp 3.x should raise an exception on redirection limit exceeding.
If you have no exception but empty response only -- the problem is not related to redirection but a server returns an empty response somehow.

**Comment by amarynets** [comment]
thanks
