### ISSUE TITLE
Is there an equivalent of Retry in requests?

### ISSUE THREAD

**Issue by kootenpv** [aio-libs/aiohttp#3133]
```python
from requests.packages.urllib3.util.retry import Retry

def get_session():
    # ... example code, does not run ...
    session = requests.Session()
    retry = Retry(
        total=retries,
        read=retries,
        connect=retries,
        backoff_factor=backoff_factor,
        status_forcelist=status_forcelist,
    )
    adapter = HTTPAdapter(max_retries=retry)
    session.mount('http://', adapter)
    session.mount('https://', adapter)
    return session
```

**Comment by butla** [comment]
I'm not sure if there is something like that in AioHTTP, but what I'm using is decorating small async functions that issue HTTP calls with `tenacity.retry` (https://github.com/jd/tenacity). A great retrying library with a ton of functionality for tweaking the retries however you want.

**Comment by asvetlov** [comment]
https://github.com/hellysmile/async_retrying is another option

**Comment by thehesiod** [comment]
so many, see http://allyouneedisbackend.com/blog/2017/09/15/how-backend-software-should-retry-on-failures/, I'm currently using backoff

**Comment by butla** [comment]
@kootenpv I guess you got your answer :) Nothing in AioHTTP itself, but there are options.
