### ISSUE TITLE
aiohttp-master failing to build on macOS High Sierra 10.13.5.

### ISSUE THREAD

**Issue by germanjoey** [aio-libs/aiohttp#3138]
## Long story short

We have some nightly tox tests that run against the latest aiohttp release on pypi as well as the master branch pulled directly from github. In the past few weeks, the master branch tests have been breaking because `aiohttp` wouldn't build. The error was like this:

```
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c aiohttp/_websocket.c -o build/temp.macosx-10.9-x86_64-3.6/aiohttp/_websocket.o
    clang: error: no such file or directory: 'aiohttp/_websocket.c'
    clang: error: no input files
    error: command 'gcc' failed with exit status 1
```

Investing the issue today, it appears that this problem is related to #3095. Reverting the change on [this line](https://github.com/aio-libs/aiohttp/pull/3095/files#diff-2eeaed663bd0d25b7e608891384b7298L59) to add `CCompilerError` back into the caught exceptions list now allows `aiohttp` to build again. It does generate this warning:

```
************************************************************
Cannot compile C accelerator module, use pure python version
************************************************************
```

At any rate, I figured I'd raise this as an issue first before annoying y'all with a trivial PR.

## Expected behaviour

`aiohttp` master will successfully build.

## Actual behaviour

`aiohttp` master does not successfully build.

## Steps to reproduce

```
python3 -m pip install git+https://github.com/aio-libs/aiohttp.git
```

## Your environment

macOS High Sierra 10.13.5
Python 3.6.5

**Comment by webknjaz** [comment]
It looks like sdist is missing C-sources. Or if you are compiling from master they might be not produced by Cython.

**Comment by webknjaz** [comment]
Also tell us version of your python and stuff.

**Comment by germanjoey** [comment]
Oh, right! Python 3.6.5.

**Comment by webknjaz** [comment]
@asvetlov isn't it about missing c-file? shouldn't we include it in the manifest?

**Comment by asvetlov** [comment]
'aiohttp/_websocket.c' is generated from `'aiohttp/_websocket.pyx'` on complation stage.
Have no idea why it is not present on @germanjoey box

**Comment by webknjaz** [comment]
I think we need to inspect our OS X build job logs to find out whether it still works for us.

**Comment by webknjaz** [comment]
@germanjoey you have to do `git clone` with `--recurse-submodules` argument to also grab a vendored http client in C.

**Comment by webknjaz** [comment]
I assume that the issue has been figured out.

**Comment by webknjaz** [comment]
JFYI this is tracked in a duplicate issue #3162 and PR #3164.
