### ISSUE TITLE
Where to put X-Request-ID

### ISSUE THREAD

**Issue by schlitzered** [aio-libs/aiohttp#3139]
Hello,

i am used to use wsgi-request-id middleware, which will create a request id for every request and put it into "environ".

i am currently trying to implement a middleware for aiohttp:

i currently have this:

```
from aiohttp.web import middleware
from uuid import uuid4


@middleware
async def request_id(request, handler):
    _request_id = request.headers.get('X-Request-ID', None)
    if not _request_id:
        _request_id = str(uuid4())
    response = await handler(request)
    response.headers['X-Request-ID'] = _request_id
    return response
```

this will correctly set X-Request-ID in the response header. but how do i make it available to the handler?

what i was trying to use was this, but did not work, because of read only headers property:

```
from aiohttp.web import middleware
from uuid import uuid4


@middleware
async def request_id(request, handler):
    _request_id = request.headers.get('X-Request-ID', None)
    if not _request_id:
        _request_id = str(uuid4())
        request.headers['X-Request-ID'] = _request_id
    response = await handler(request)
    response.headers['X-Request-ID'] = _request_id
    return response
```

Kind Regards

**Comment by asvetlov** [comment]
Please RTFM.
https://docs.aiohttp.org/en/stable/web_advanced.html#request-s-storage
