### ISSUE TITLE
Q: possible to set Server header with web.Server?

### ISSUE THREAD

**Issue by jaddison** [aio-libs/aiohttp#3140]
I'm starting a low level `web.Server()` aiohttp server - so, I'm not using Apps, Middlewares, or Routes. I obviously have a single handler. This is working fine - I can set the Server header on a Response in my handler and it shows up in the response in the client. 

As expected, if an exception is raised in my handler, aiohttp handles it by creating its own 500 `Response` instance, and sets the default `Server: Python/3.6 aiohttp/3.3.2`. Is there a way for me to reliably set that header myself for ALL kinds of responses?

I know I could do this in nginx or something similar, but the software I am writing will likely have many kinds of deployment configurations, including NOT having something like nginx upstream.

Thanks!

**Comment by asvetlov** [comment]
No, aiohttp has no such option.
As a workaround you can catch all exceptions in the handler and return a custom error page.
I believe it should be enough for all cases.
Consider default error page handler as the last chance to return error to browser, feel free to render the page on your own.

**Comment by jaddison** [comment]
>No, aiohttp has no such option.
As a workaround you can catch all exceptions in the handler and return a custom error page.
I believe it should be enough for all cases.

That was my thought as well. It just feels cleaner to let aiohttp handle it IF it could - but thank you, that's the answer here.
