### ISSUE TITLE
Fatal read error on socket transport 

### ISSUE THREAD

**Issue by yjqiang** [aio-libs/aiohttp#3141]
omz/Pythonista-Issues#555
Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x1177ce940>
transport: <_SelectorSocketTransport fd=47 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
File "/var/containers/Bundle/Application/9F565D30-C54B-4210-902B-874D7A5AB814/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/selector_events.py", line 725, in _read_ready
data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out

**Comment by yjqiang** [comment]
Is it a bug?

**Comment by samuelcolvin** [comment]
Looking at the traceback this code doesn't use aiohttp. So at least this is the wrong place to post.

**Comment by yjqiang** [comment]
But the "Fatal read error on socket transport" message comes from asyncio.selector_events when it encounters an exception that it doesn't know how to handle:  https://github.com/python/cpython/blob/v3.6.1/Lib/asyncio/selector_events.py#L723-L728,
