### ISSUE TITLE
docs.aiohttp.org down "Error 1014: CNAME Cross-User Banned"

### ISSUE THREAD

**Issue by wolph** [aio-libs/aiohttp#3142]
As the description says, the documentation site is down: http://docs.aiohttp.org/

A temporary workaround might be to change the link to: https://aiohttp.readthedocs.io/en/stable/

**Comment by kxepal** [comment]
:scream_cat: 
ping @asvetlov

**Comment by webknjaz** [comment]
IIUC the error message is basically saying that someone else's account has the same domain added. Which is weird.

cc @asvetlov can you ping CF's support about it?

**Comment by wolph** [comment]
Is docs.aiohttp.org cnamed to GH? I kind of assumed it'd CNAME to RTD instead.

**Comment by webknjaz** [comment]
Oh, my bad. Right, it's RTD.

**Comment by webknjaz** [comment]
Yeah, that's right. RTD is on CF:

```shell
$ dig readthedocs.io ns

; <<>> DiG 9.12.1 <<>> readthedocs.io ns
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26068
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;readthedocs.io.                        IN      NS

;; ANSWER SECTION:
readthedocs.io.         86400   IN      NS      ivan.ns.cloudflare.com.
readthedocs.io.         86400   IN      NS      tegan.ns.cloudflare.com.
```

And CNAMEing there causes the issue. They've probably just moved.

**Comment by wolph** [comment]
We're not the only ones with issues: https://github.com/rtfd/readthedocs.org/issues/4395

**Comment by webknjaz** [comment]
Yep, was just going to link it :)

**Comment by webknjaz** [comment]
Same for https://cheroot.cherrypy.org

**Comment by kxepal** [comment]
Wow. That's massive.

**Comment by wolph** [comment]
Not sure who has access to the cloudflare account but I would think it can be fixed by disabling the cloudflare proxying (click on the orange cloud) and simply use the cname alone.

**Comment by webknjaz** [comment]
That's DDDoS (Docs DDoS :D)

**Comment by webknjaz** [comment]
@WoLpH the problem is that we'd also loose SSL/https. I'd say that switching to A-record might also work.
Anyway, I think only @asvetlov has access. So let's wait for him or maybe for resolution of the report @ RTD repo.

**Comment by wolph** [comment]
You're right, that would be an issue

Switching to an A record won't work either unless you can link to the RTD load balancers directly.
I think the only correct solution is for RTD to disable the proxying but that was probably the point of the switch :P

**Comment by webknjaz** [comment]
Yep, the point was to have free SSL basically. Also, since it went global, the correct solution is for RTD to fix it.

**Comment by webknjaz** [comment]
After re-reading that issue it looks like disabling proxying is a right thing to do.
cc @asvetlov

**Comment by wolph** [comment]
That depends, if you're using HSTS right now that would make the site unavailable for anyone that already visited the site through HTTPS in the past.

It's annoying to say the least...

**Comment by webknjaz** [comment]
Not necessarily. AFAICS RTD tries to provide SSL to third-party domains through their own CF account. And in this case, pure CNAME w/o proxying would work.
However, it doesn't seem to help in case of cheroot. I've also noticed that it works fine with `.org` RTD doman.

**Comment by webknjaz** [comment]
@asvetlov is it possible to enforce https redirect on RTD side?

**Comment by asvetlov** [comment]
Not yet

**Comment by webknjaz** [comment]
@asvetlov JFYI https://github.com/rtfd/readthedocs.org/issues/4395#issuecomment-406725662
