### ISSUE TITLE
issue of the keyword argument "text" in post()

### ISSUE THREAD

**Issue by edwwlui** [aio-libs/aiohttp#3160]
the doc mentioned
"To send text with appropriate content-type just use text attribute

async with session.post(url, text='Тест') as resp:
    ...
"
but i failed to find the keyword argument of "text" in _request() in client.py. i wonder if it is a typo in the doc?

**Comment by socketpair** [comment]
Yes, It's a bug. At least for the `master` branch. I will make a fix.

**Comment by asvetlov** [comment]
Fixed by #3160
