### ISSUE TITLE
pytest plugin's async fixtures don’t work with pytest 3.7.0

### ISSUE THREAD

**Issue by hynek** [aio-libs/aiohttp#3169]
## Long story short

Tests that rely on

```python
@pytest.fixture
async def x():
    yield …
```

stopped working with pytest 3.7.0. Instead of the fixture you get an `async_generator`.

I’ve been told that some fixture handling code in pytest changed so I’m opening the bug here. Happy to redirect to pytest if necessary.

## Expected behaviour

That it keeps working. :)

## Actual behaviour

It passes an `async_generator` instead of the fixture.

## Steps to reproduce

Define an async fixture that yields itself and try to use it.

## Your environment

Python 3.7.0, pytest 3.7.0, aiohttp 3.3.2.

**Comment by asvetlov** [comment]
Thanks for the report

**Comment by hynek** [comment]
Looks like they reverted that changes in 3.7.1 – sorry for the noise.

**Comment by asvetlov** [comment]
Oh, cool!
