### ISSUE TITLE
RequestHandler._task_handler cancellation is never awaited

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiohttp#3172]
in `connection_lost`, if there is an active `self._task_handler`, it is cancelled, however it is then never awaited resulting in the warning: `Task was destroyed but it is pending`

I did a simple change to:
```
        if self._task_handler and not self._task_handler.done():
            self._task_handler.cancel()
            asyncio.ensure_future(self._task_handler, loop=self_loop)
```

and the warning went away, not sure if this is the right thing to do.

There's another problem though, if you have an expired certificate, the `task_handler` will be thrown a `GeneratorExit` with a different task and can cause all kinds of weird problems in client code that has context handlers after `start()`.  Would be nice to pinpoint where its coming from so it can be handled lower-level

**Comment by asvetlov** [comment]
aiohttp 3.7+ doesn't cancel the web handler anymore but raises ConnectionErro on I/O to closed peer.
