### ISSUE TITLE
Make chardet dependency mandatory

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#318]
Why not?
aiohttp should be installed from PyPI anyway.
chardet is pretty stable.
We can add extra dependency to setup.py, cleanup code a bit and drop redundant tests.

**Comment by fafhrd91** [comment]
Ok. I am fine with that

**Comment by asvetlov** [comment]
I'll do then

**Comment by ludovic-gasc** [comment]
It's a good idea.

**Comment by asvetlov** [comment]
Done in b38fdf5
