### ISSUE TITLE
request.content.iter_chunks() stalls when content is empty.

### ISSUE THREAD

**Issue by ArthurKantor** [aio-libs/aiohttp#3186]
## Long story short
The title says it all.

Shouldn't [EmptyStreamReader.readchunk](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/streams.py#L470) on its face `return (b'', True)` and not `return (b'', False)` ?

Without it, the special EOS chunk is never sent...

**Comment by webknjaz** [comment]
Could you please describe your scenario in more detail?

**Comment by asvetlov** [comment]
The feature request makes sense.
