### ISSUE TITLE
504, message='Gateway Time-out'

### ISSUE THREAD

**Issue by vgoklani** [aio-libs/aiohttp#3187]
I get this error after calling a web-service, continuously, for several hours. The function runs correctly for several hours, breaks, and then just throws this error: 504, message='Gateway Time-out'. Every subsequent request then just throws this exception.

I then killed the function, restarted, and everything worked correctly. 

I suspect the solution would be to *reset* the session object after receiving the first exception (perhaps I need to clear the keep-alive). How would I do this?  Here is a simplified version of my code:

	def get_session(self):
		resolver = AsyncResolver(nameservers=["1.1.1.1", "1.0.0.1"])
		return aiohttp.ClientSession(loop=self.loop, connector=aiohttp.TCPConnector(limit=100, ssl=False, force_close=False, keepalive_timeout=90, ttl_dns_cache=900, resolver=resolver, family=socket.AF_INET), timeout=aiohttp.ClientTimeout(total=5))

	async def fetch(self, url, params):
		async with self._session.get(url, params=params) as response:
			response.raise_for_status()
			return await response.json()

	async def worker(self):
		response = await self.fetch(self.url, self.params)
		self.do_work(response)

	def worker(self):
		loop = asyncio.get_event_loop()
		loop.run_until_complete(self.work())

**Comment by asvetlov** [comment]
Most likely you've got limit rates on the server.
There is no way to *reset* the cline session, you need to recreate it
