### ISSUE TITLE
Big god, look at this question. Thank you

### ISSUE THREAD

**Issue by wangyi1998** [aio-libs/aiohttp#3190]
I installed aiohttp, no problem, all correct.
And these two libraries, cchardet and aiodns, are okay.
However, when importing aiohttp, the following tips appear!
I hope to receive your reply, thank you

![snip20180812_1](https://user-images.githubusercontent.com/17868020/44002747-78edd28c-9e7a-11e8-985d-bbc796097071.png)

**Comment by Harmon758** [comment]
[`typing.TYPE_CHECKING`](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING) was added in Python 3.5.2.
As the README states, aiohttp requires Python >= 3.5.3:
https://github.com/aio-libs/aiohttp/blob/2a165dbdaaa0306ad6ebb0f6f0d2af8d6393bb2b/README.rst#L152

**Comment by asvetlov** [comment]
@Harmon758 you are right
