### ISSUE TITLE
[Cleanup Context] on_startup and cleanup_ctx execution order.

### ISSUE THREAD

**Issue by Maillol** [aio-libs/aiohttp#3191]
## Long story short

The initialization code of Cleanup Context is alway executed before any startup signal handler.

In this code:
```
from aiohttp import web

async def startup_1(app):
    print('init 1')

async def cleanup_ctx_2(app):
    print('init 2')
    yield
    print('cleanup 2')

async def startup_3(app):
    print('init 3')

app = web.Application()
app.on_startup.append(startup_1) 
app.cleanup_ctx.append(cleanup_ctx_2)
app.on_startup.append(startup_3)

web.run_app(app)
``` 

I would execute `startup_1` before `cleanup_ctx_2` initialization code.

Note: Perhaps `on_startup.append` can become a shortcut for:

```
async def cleanup_ctx(app):
    await start_up_handler(app)
    yield
    # Do nothing

app.cleanup_ctx.append(cleanup_ctx)
``` 

## Expected behaviour

on_startup signal handlers added before cleanup context is executed before initialization code of Cleanup Context.

The example code above displays:
 ```
init 1
init 2
init 3
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
^Ccleanup context
```

## Actual behaviour

The example code above displays:

```
init 2
init 1
init 3
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
^Ccleanup context
```

## Steps to reproduce

Add startup hander to the `app` before  `Cleanup Context`.
launch the `app`

## Your environment

aiohtpp=3.3.2

**Comment by asvetlov** [comment]
It is the design decision.
`on_cleanup` order is also affected.
You can try to prepare a patch but I doubt if elegant and clean solution for mixing cleanup contexts and `on_startup`/`on_cleanup` exists.

**Comment by asvetlov** [comment]
The proposed patch breaks several existing contracts, the idea cannot be implemented with the current aiohttp design
