### ISSUE TITLE
Applications stops with second Ctrl+C press if websocket session is active

### ISSUE THREAD

**Issue by livrrr** [aio-libs/aiohttp#3192]
I have a very simple example of websocket server. When I have no connected clients server stops on pressing Ctrl+C and prints output from on_cleanup callback, but when I have connected websocket clients first press of Ctrl+C does not stop app and second press of Ctrl+C stops app, but there is no output from on_cleanup callback.

Here is my code:

```python
from aiohttp import WSCloseCode
import weakref
import aiohttp.web

HOST = '127.0.0.1'
PORT = 7777

class SimpleTerminal:
    def __init__(self, app):
        self._app = app
        self._ws = weakref.WeakSet()

    async def on_stop(self, app):
        print ('stop')
        for ws in self._ws:
            print (1)
            await ws.close(code=WSCloseCode.GOING_AWAY, message='Server shutdown')

    async def websocket_handler(self, request):
        print('Websocket connection starting')
        ws = aiohttp.web.WebSocketResponse()
        await ws.prepare(request)
        print('Websocket connection ready')

        self._ws.add(ws)
        try:
            async for msg in ws:
                print(msg)
                if msg.type == aiohttp.WSMsgType.TEXT:
                    print(msg.data)
                    if msg.data == 'close':
                        await ws.close()
                    else:
                        await ws.send_str(msg.data + '/answer')
        finally:
            print('Websocket connection closed')
            self._ws.discard(ws)

        return ws

def main():
    app = aiohttp.web.Application()
    simple_terminal = SimpleTerminal(app)
    app.router.add_route('GET', '/ws', simple_terminal.websocket_handler)
    app.on_cleanup.append(simple_terminal.on_stop)
    aiohttp.web.run_app(app, host=HOST, port=PORT)

if __name__ == '__main__':
    main()
```

I use Fedora 27 with Python 3.6.5 and aiohttp 3.3.2

**Comment by asvetlov** [comment]
Thanks for the report.
Ctrl+C handling is complicated in asyncio.
We have a plan for improving the situation in next Python release.
Unfortunately, I don't see how to fix it right now.

**Comment by webknjaz** [comment]
*Remark:* I'm going to guess that `taskGroup`s suggested by @1st1 (aka nurseries from trio) are going to improve this dramatically.

**Comment by asvetlov** [comment]
It's coupled but Ctrl+C is another issue.

**Comment by aquamatthias** [comment]
I still see this behaviour. Is there any update here? Or any recommendation on how to work around this? 
Thanks in advance.

**Comment by Dreamsorcerer** [comment]
This is covered by the documentation now (and needs on_shutdown, rather than on_cleanup):
https://docs.aiohttp.org/en/stable/web_advanced.html#websocket-shutdown
