### ISSUE TITLE
Question: Do I need to close the response by hand?

### ISSUE THREAD

**Issue by yjqiang** [aio-libs/aiohttp#3195]
```
async with aiohttp.ClientSession() as session:
    async with session.get('http://httpbin.org/get') as resp:
        print(resp.status)
        print(await resp.text())
```
This is an example in https://aiohttp.readthedocs.io/en/stable/client_quickstart.html. But I don't understand the "async with session.get('http://httpbin.org/get') as resp", does it mean that I have to close the resp by hand?

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/6
I met that problem, and it seems that I used too many sockets but I did not release them after I finished the job. I only use 3 sessions in my programme, so I wonder if the reason why it happened is that I did not close the resp immediately.

**Comment by asvetlov** [comment]
`async with` returns a connection to connections pool on `__aexit__`

**Comment by yjqiang** [comment]
```
async with aiohttp.ClientSession() as session:
    resp = session.get('http://httpbin.org/get')
    print(resp.status)
    print(await resp.text())

    resp = session.get(url)
    print(resp.status)
    print(await resp.text())

    # many other codes which use the session many times but without "async with"
```
So if my code were like that, the connections pool would not close the connections immediately? And it is a wasteful.

**Comment by asvetlov** [comment]
Generally speaking no. 
`await resp.release()` should be called.

**Comment by yjqiang** [comment]
Thanks a lot. I did not realise it, but now I get it. Thank you.
