### ISSUE TITLE
SafeChildWatcher is not reinstalled properly after the second test is loop fixture is not used

### ISSUE THREAD

**Issue by tardyp** [aio-libs/aiohttp#3199]
## Long story short

When moving to aiohttp 3.3+, my tests suddently hang at await process.wait()
but only after one test has run previously

## Expected behaviour

process.wait() returns when the process finishes

## Actual behaviour

process.wait() never returns 

## Steps to reproduce

```
pip install aiohttp pytest pytest-aiohttp pytest-asyncio
```

run the following test suite:
```
import asyncio


async def test_basic():
    sleep_proc = await asyncio.create_subprocess_exec("sleep", '0.1',)
    await sleep_proc.wait()


async def test_basic2():
    sleep_proc = await asyncio.create_subprocess_exec("sleep", '0.1',)
    await sleep_proc.wait()
```
The second test will fail.

## Your environment

macos python3.7 from brew.

## Rootcause start

if I change SafeChildWatcher installer in test_utils.py:setup_test_loop to following code, the test will work 
```
    if sys.platform != "win32" and not skip_watcher:
        policy = asyncio.get_event_loop_policy()
        if not policy.get_child_watcher():
            watcher = asyncio.SafeChildWatcher()
            watcher.attach_loop(loop)
            with contextlib.suppress(NotImplementedError):
                policy.set_child_watcher(watcher)
    return loop
```

**Comment by tardyp** [comment]
looks like this comes from this commit:
https://github.com/aio-libs/aiohttp/commit/8e76a4a89b04abf7d05da2d360867d6a7d531788

if I look at the code, I don't see why it is needed.

asyncio.get_child_watcher() will always automatically create the default safe childwatcher

https://github.com/python/cpython/blame/master/Lib/asyncio/unix_events.py#L1097

**Comment by tardyp** [comment]
Another fix is to use loop in my test fixtures

**Comment by tardyp** [comment]
Forgot to update on this.
This issue is fixed by adding ``loop`` in the fixture list for each test.

**Comment by Dreamsorcerer** [comment]
I believe all this code has moved to pytest-asyncio, so I'm assuming this is not an issue anymore or should be filed against pytest-asyncio. Please comment if not.
