### ISSUE TITLE
run_in_executor in handle_request blocking I/O

### ISSUE THREAD

**Issue by tonyazzimov** [aio-libs/aiohttp#32]
Hi !

I've tried to use your module to handle slow requests.
What I've done is that in the handle_request coroutine, I yield from loop.run_in_executor a function that just does a time.sleep(10) and return a "test" string, and then send the response with the return run_in_executor string.

``` output
def slow_func():
  time.sleep(10)
  return "test"

class HttpProtocol(aiohttp.server.ServerHttpProtocol):
  def __init__(self, ppexecutor, loop):
    self.loop = loop
    self.ppexecutor = ppexecutor

  ...

  @asyncio.coroutine
  def handle_request(self, message, payload):
    # ppexecutor is a ProcessPoolExecutor instance
    data = yield from self.loop.run_in_executor(self.ppexecutor, slow_func)
    response = aiohttp.Response(self.transport, 200, http_version=message.version, close=True)

    response.add_headers(
      ('Content-Type', 'text'),
      ('Content-Length', str(len(data)))
    )
    response.send_headers()
    response.write(data.encode())
    self.keep_alive(False)
```

The problem is that the server doesn't accept any request until the function given in the run_in_executor hasn't returned.
Is that normal or I' m doing something wrong ?

Notice that it works perfectly well with a asyncio.start_server in the request's handler.

**Comment by gzeronet** [comment]
Thx guys, I just realized that the browser block the same requests, aiohttp works as expected in different clients.
