### ISSUE TITLE
websocket client: when the network is bad, it shows fatal read error message

### ISSUE THREAD

**Issue by yjqiang** [aio-libs/aiohttp#3202]
This is a msg in PYTHONISTA on ios (python 3.6.1). So maybe it is a bug in pythonista.

Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x1177ce940>
transport: <_SelectorSocketTransport fd=47 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
File "/var/containers/Bundle/Application/9F565D30-C54B-4210-902B-874D7A5AB814/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/selector_events.py", line 725, in _read_ready
data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out

**Comment by kxepal** [comment]
Definitely, not a bug of aiohttp nor Pythonista, but remote server which couldn't respond within specified timeout interval. There is nothing to do from aiohttp side.

**Comment by yjqiang** [comment]
@kxepal "remote server which couldn't respond within specified timeout interval"? I wrap timeout with the receive function like https://github.com/yjqiang/bilibili-live-tools/blob/master/bilibiliCilent.py#L92 .

**Comment by asvetlov** [comment]
I cannot understand how did you get `TimeoutError` (not `asyncio.TimeoutError`)?
The former is never used by `asyncio` nor `aiohttp`.
Bare `TimeoutError` with errno 60 is for synchronous sockets only.

**Comment by yjqiang** [comment]
Can I handle the error "TimeoutError: [Errno 60] Operation timed out" by myself? I used try and exception, but it did not work at all.

**Comment by yjqiang** [comment]
Sorry my English is not good so I think maybe I misunderstood your words. You mean why the msg is TimeoutError instead of asyncio.TimeoutError? I can't get it too. Maybe it is a bug in pythonista?

**Comment by asvetlov** [comment]
@yjqiang yes. I mean that `TimeoutError` is never raised by asyncio/aiohttp in normal usage.
It *could* be raised if a blocking socket was passed into event loop but this case is definitely an error.

I know nothing about pythonista thogh

**Comment by yjqiang** [comment]
https://github.com/omz/Pythonista-Issues/issues/563
Looks like it is not a bug in pythonista, asyncio raises timeout error. Maybe aiohttp should catch and handle it?

**Comment by jsbain** [comment]
To be clear, this should reference

**Comment by yjqiang** [comment]
@asvetlov

**Comment by yjqiang** [comment]
The reason why it raises TimeoutError is that the code in https://github.com/omz/Pythonista-Issues/issues/563#issuecomment-434926193  
And 3 years ago, people discussed about that in https://github.com/python/asyncio/issues/135

**Comment by asvetlov** [comment]
`TimeoutError` builtin is raised when a syscall returns `ETIMEDOUT` status code.
`man errno` says that this error code is for "Connection timed out (POSIX.1-2001)".

From my understanding, the error should be never raised for a nonblocking socket, only `EAGAIN` and `EWOULDBLOCK` are possible values if the socket is not ready.

**UPD**.
Looks like TCP keepalive facility can return `ETIMEDOUT`: https://stackoverflow.com/questions/16772519/socket-recv-on-selected-socket-failing-with-etimedout

I need to investigate more.

**Comment by yjqiang** [comment]
> `TimeoutError` builtin is raised when a syscall returns `ETIMEDOUT` status code.
> `man errno` says that this error code is for "Connection timed out (POSIX.1-2001)".
> 
> From my understanding, the error should be never raised for a nonblocking socket, only `EAGAIN` and `EWOULDBLOCK` are possible values if the socket is not ready.
> 
> **UPD**.
> Looks like TCP keepalive facility can return `ETIMEDOUT`: https://stackoverflow.com/questions/16772519/socket-recv-on-selected-socket-failing-with-etimedout
> 
> I need to investigate more.

"a NAT gateway could time out after some minutes of not doing anything" So the server does not work well or the network is not normal, after I setup the connection. If it is that reason, maybe aiohttp/asyncio should raise this exception when I use recv() and let us handle it?  But maybe they would hold the exception for a long time if I did not  use recv() immediately.

**Comment by asvetlov** [comment]
The current behavior is:
1. `TimeoutError` is received on socket operation.
2. asyncio closes transport and logs the error by `loop.call_exception_handler()`.

The logging can be suppressed in next Python release (as we do it for `ConnectionError` and several other exceptions).
But I see no reason to change the main reaction: close the socket and call `protocol.connection_lost(exc)` with exception info.

**Comment by yjqiang** [comment]
Thanks.

**Comment by asvetlov** [comment]
Move discussion to Python bug tracker

**Comment by yjqiang** [comment]
> Move discussion to Python bug tracker

No response yet for 2 months. 
https://github.com/python/cpython/pull/11576
