### ISSUE TITLE
Connection tracking with aiohttp.web.Application seems complicated with the current API

### ISSUE THREAD

**Issue by ewasser** [aio-libs/aiohttp#3214]
## Long story short

I'm looking for a way to have access to the methods `aiohttp.web_server.Server.connection_made(self, handler, transport)` and `aiohttp.web_server.Server.connection_lost(self, handler, exc=None)` because I want to execute some code if a connection is lost or closed from the client side.

I found no "easy" way to do this, my current implementation looks like this:

    class MyServer(aiohttp.web_server.Server):
        def connection_made(self, handler, transport):
            super().connection_made(handler, transport)
            # My Code

        def connection_lost(self, handler, exc=None):
            super().connection_lost(handler, exc)
            # My Code

...and...

    class MyApp(aiohttp.web.Application):
        def _make_handler(...):
            # Copied the whole code from aiohttp.web.Application._make_handler
            # except for the last line.

            # Here is my reference to my new class from above.
            return MyServer(self._handle, request_factory=self._make_request,
                      access_log_class=access_log_class,
                      loop=self.loop, **kwargs)

That seems a little bit complicated for a simple connection tracking. Or are there any better ways for a connection tracking?

**Comment by asvetlov** [comment]
Could you describe your use case?
Why do you need to track connection establishment and disconnection?

**Comment by ewasser** [comment]
Thanks for the question. Here's my use case in short form:

* My `asyncio` process generates some data from time to time.
* This data will be served to some long running requests. These requests are waiting on the generated data.
* Some of this requests will timeout from the client perspective if no data arrives.
* The application has to serve the data to other clients.

Here's some pseudocode:

    async def handle_get(request):
        # This is the waiting condition.
        # This waiting can be affected by a timeout because the 
        # the client closes the connection.
        a = await queue.get()

       return web.json_response(a)

And I want to be notifed about the ending of the connection from the client to serve data to other clients.

**Comment by arthurdarcet** [comment]
I'm not sure I understand why you need to track the connection lost event for this use case, or the connection made (the pseudo code you posted seems to be doing what you describe?)

anyway: you can do something like this, which avoids a custom Server:

```python
async def handle():
    connection_made_hook()
    try:
        a = await queue.get()
        return web.json_response(a)
    except asyncio.CancelledError:
        connection_lost_hook()
```

**Comment by ewasser** [comment]
Thank you. That is exactly what I was looking for.
