### ISSUE TITLE
Unable to build RPM package

### ISSUE THREAD

**Issue by fabaff** [aio-libs/aiohttp#3217]
## Long story short

On Fedora 30 the source shipped as `aiohttp-3.4.0.tar.gz` leads to a build error which could be related to the changes around nodejs/http-parser in #3209.

## Expected behaviour

Able to build the package.

## Actual behaviour

```bash
creating build/temp.linux-x86_64-3.7/vendor/http-parser
gcc -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -DHTTP_PARSER_STRICT=0 -I/usr/include/python3.7m -c aiohttp/_http_parser.c -o build/temp.linux-x86_64-3.7/aiohttp/_http_parser.o
aiohttp/_http_parser.c:590:10: fatal error: ../vendor/http-parser/http_parser.h: No such file or directory
 #include "../vendor/http-parser/http_parser.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
```

Full log: https://kojipkgs.fedoraproject.org//work/tasks/6055/29286055/build.log

## Steps to reproduce

- On the Fedora build server: `fedpkg scratch-build`
- Local: `fedpkg local`

## Your environment

Fedora 30

**Comment by webknjaz** [comment]
Your archive is missing http-parser submodule. Ask the packager to include it as well.

**Comment by fabaff** [comment]
Our builds are done with the [archive](https://github.com/aio-libs/aiohttp/archive/v3.4.0.tar.gz) which is publish under [releases](https://github.com/aio-libs/aiohttp/releases).

Worked till 3.3.2.

**Comment by asvetlov** [comment]
Github archive is autogenerated github snapshot, the project does nothing with it.
The **official** release tarball is hosted on PyPI: https://pypi.org/project/aiohttp/#files

**Comment by webknjaz** [comment]
@fabaff We *might* add some dists to GitHub Releases in future, but currently, *please don't rely on them now*. It's just git archives, which don't include Git submodules.

**Comment by fabaff** [comment]
Thanks for the quick responses. We will switch back to the archives which are available at PyPI.

As a sidenote: The bundling of `http-parser` is an issue in regard to comply with the guidelines for Fedora/EPEL packages. This is another point to address but I will open a new issue if needed to not pollute this one.

**Comment by asvetlov** [comment]
Yes, better to have one issue for one problem
