### ISSUE TITLE
RTD is still showing docs for 3.3

### ISSUE THREAD

**Issue by hynek** [aio-libs/aiohttp#3221]
https://aiohttp.readthedocs.io/ is currently showing the docs for “Current version is 3.3.2.”

**Comment by webknjaz** [comment]
Apparently, this is failing because of #3189: https://readthedocs.org/projects/aiohttp/builds/

**Comment by webknjaz** [comment]
Probably adding `requirements_file: requirements/cython.txt` to [`.readthedocs.yml`](https://docs.readthedocs.io/en/latest/yaml-config.html) will fix docs build.

**Comment by asvetlov** [comment]
Hrr.

Looks like readthedocs ignores  `Install your project inside a virtualenv using setup.py install` option
Technically docs build doesn't need aiohttp installed but this mode is not supported by rtfd.

Will fix it. Thanks for pointing on readthedocs yaml config.

**Comment by webknjaz** [comment]
No, it doesn't ignore that, it just has different defaults. Are you referring to the yaml config?

**Comment by webknjaz** [comment]
Fixed by disabling `pip install .` in RTD: https://readthedocs.org/projects/aiohttp/builds/7699754/

**Comment by webknjaz** [comment]
Probably needs to be backported to `3.4`

**Comment by webknjaz** [comment]
@asvetlov backported, but it didn't trigger the build for `stable` in RTD. Any settings missing?

**Comment by webknjaz** [comment]
@asvetlov this probably needs another version pushed: https://docs.readthedocs.io/en/latest/versions.html
maybe `3.4.0.post0`?

**Comment by asvetlov** [comment]
Thank you.
I'll publish 3.4.1

**Comment by asvetlov** [comment]
I did try to disable `pip install .` by RTD web interface without success.
Config file is obviously much better option

**Comment by webknjaz** [comment]
I guess the config's priority is higher (probably)
