### ISSUE TITLE
NameError during WebSockets example in Web Server quickstart docs

### ISSUE THREAD

**Issue by kaganjd** [aio-libs/aiohttp#3234]
## Long story short

Thanks for the very awesome lib! I just wrestled with the [WebSockets quickstart docs](https://docs.aiohttp.org/en/stable/web_quickstart.html#aiohttp-web-websockets) for a long time and wanted to report a solution that worked for me in case others run into this:

```
async def websocket_handler(request):

    ws = web.WebSocketResponse()
    await ws.prepare(request)

    async for msg in ws:
        if msg[0].value == 1:  # TEXT according to here: https://github.com/aio-libs/aiohttp/blob/3a65252aa4c822056b408caa883fbdbf78311fa6/aiohttp/http_websocket.py#L41
            if msg[1] == 'close':
                await ws.close()
            else:
                await ws.send_str(msg[1] + '/answer')
        elif msg[0].value == 102: # ERROR according to here: https://github.com/aio-libs/aiohttp/blob/3a65252aa4c822056b408caa883fbdbf78311fa6/aiohttp/http_websocket.py#L41
            print('ws connection closed with exception %s' %
                  ws.exception())

    print('websocket connection closed')

    return ws
```

The way the docs are currently written led me to this error, I think because the `msg` attributes are accessed differently than described:
```
    if msg.type == aiohttp.WSMsgType.TEXT:
NameError: name 'aiohttp' is not defined
```
## Your environment
aiohttp 3.4.2- server on localhost
python 3.6

**Comment by kxepal** [comment]
You should make `import aiohttp` to resolve this issue.  Eventually, you did `from aiohttp import web`, but this bit is missing.

**Comment by kaganjd** [comment]
Ah, you're totally right! Thanks, closing.
