### ISSUE TITLE
Document application freezing

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3238]
- [ ] Mention `freeze` / `frozen` in application reference
- [ ] Write a narrative doc page for describing the concept

**Comment by nilp0inter** [comment]
Hi,

I am trying to understand the code in `aiohttp/web_urldispatcher.py` to dynamically add routes to my application. I came across the `freeze()` method and `_frozen` property in the `UrlDispatcher` class and I am a little concerned about it. 

Can you briefly explain to my why aiohttp needs to freeze the UrlDispatcher after app startup? Is it possible/safe to add new URLs at runtime?

Thank you!

**Comment by asvetlov** [comment]
aiottp has separate *configuration* and *serving* stages.
Registering new routes is allowed in the configuration stage only.
Use [greedy consumer](https://docs.aiohttp.org/en/stable/faq.html#how-do-i-create-a-route-that-matches-urls-with-a-given-prefix) to organize dynamic routes on your own.

**Comment by nilp0inter** [comment]
Is it possible to reuse aiohttp's routing machinery inside of the sink_handler to avoid making a new one? If so, any examples out there?

**Comment by asvetlov** [comment]
No, it is a black box
