### ISSUE TITLE
Missing type annotations in pyi files

### ISSUE THREAD

**Issue by tailhook** [aio-libs/aiohttp#3240]
Mypy's errors are:
```
aiohttp/frozenlist.pyi:10: error: Missing type parameters for generic type
aiohttp/frozenlist.pyi:17: error: Function is missing a type annotation
aiohttp/frozenlist.pyi:19: error: Function is missing a type annotation
aiohttp/frozenlist.pyi:21: error: Function is missing a type annotation
aiohttp/frozenlist.pyi:29: error: Function is missing a type annotation for one or more arguments
aiohttp/frozenlist.pyi:30: error: Function is missing a type annotation for one or more arguments
aiohttp/frozenlist.pyi:31: error: Function is missing a type annotation for one or more arguments
aiohttp/frozenlist.pyi:32: error: Function is missing a type annotation for one or more arguments
aiohttp/frozenlist.pyi:33: error: Function is missing a type annotation for one or more arguments
aiohttp/frozenlist.pyi:34: error: Function is missing a type annotation for one or more arguments
aiohttp/signals.pyi:18: error: Function is missing a type annotation for one or more arguments
```
My `mypy.ini`:
```
[mypy]
check_untyped_defs = True
disallow_any_generics = True
disallow_untyped_defs = True
follow_imports = silent
strict_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
```
I would make a PR, but I'm not sure how to test it. I see these errors in project using mypy and aiohttp. When I run mypy against aiohttp itself I get lots of errors, much more than what I'm willing to fix in a single PR :)

**Comment by tailhook** [comment]
While fixing this, I have noted that Signal can't be type-safe in the current form, as far as I understand. The only way to make signal type-safe I've found is to only allow single argument. I.e. like this:

```python
from typing import Any, Generic, TypeVar, Callable

from aiohttp.frozenlist import FrozenList


__all__ = ('Signal',)


_T = TypeVar('_T')


class Signal(FrozenList[Callable[[_T], None]], Generic[_T]):

    def __init__(self, owner: Any) -> None: ...

    def __repr__(self) -> str: ...

    async def send(self, arg: _T) -> None: ...

```

From quick grepping it looks like Signal is only used with a single argument in the aiohttp codebase, so it might make sense to fix it. What do you think?

**Comment by asvetlov** [comment]
`on_response_prepare` accepts two arguments: https://docs.aiohttp.org/en/stable/web_reference.html?highlight=on_response_prepare#aiohttp.web.Application.on_response_prepare

**Comment by tailhook** [comment]
Hm. Is there any chance that this will be fixed in mypy/typing? (and even if it is, will it be backported to previous python versions?)


> on_response_prepare accepts two arguments: https://docs.aiohttp.org/en/stable/web_reference.html?highlight=on_response_prepare#aiohttp.web.Application.on_response_prepare


Note, that while unergonomic (and breaking change) tuple will work for this signal.

Otherwise, it looks like we're stuck with non-type-safe signals.
