### ISSUE TITLE
Enable stdout logging in run_app by default

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3243]
Flask adds StreamHandler to application logger if the logger has no handlers at the moment of application startup.
We should do the same in web.run_app. AppRunner should be configured explicitly.

http://flask.pocoo.org/docs/1.0/logging/#default-configuration

See https://github.com/aio-libs/aiohttp/issues/2952#issuecomment-418994782 for motivation

**Comment by 0az** [comment]
Mind if I have a go at this?

If I understand this issue correctly, all that needs to be done is add a check at the start of `run_app` in [web.py](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web.py#L43) before the AppRunner is created. Is this correct?

**Comment by asvetlov** [comment]
Please do.
Your understanding is correct.
