### ISSUE TITLE
`history` tuple on ClientResponseError empty with raise_for_status() or ClientSession(raise_for_status=True)

### ISSUE THREAD

**Issue by brettdh** [aio-libs/aiohttp#3248]
## Long story short

When using a `ClientSession` created with `raise_for_status=True`, the resulting `ClientResponseError` does not have its `history` field populated, making it difficult to get the response data.

**Update**: this is also true when calling `.raise_for_status()` explicitly.

At a glance, it appears that `.raise_for_status()` is called before `._history` is set on the response object: https://github.com/aio-libs/aiohttp/blob/03d83b082fce200ddece85de1dbcb2232bcb885c/aiohttp/client.py#L471-L493

## Expected behaviour

The `history` field should be a tuple of `ClientResponse` objects.

## Actual behaviour

The `history` field is an empty tuple.

## Steps to reproduce

```python
import asyncio

import aiohttp
import pytest
from aiohttp.client_exceptions import ClientResponseError


@pytest.fixture(scope='session')
def event_loop():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    return loop


def test_missing_history(event_loop):
    async def inner():
        session = aiohttp.ClientSession()

        try:
            async with session.get('http://httpbin.org/status/404') as r:
                r.raise_for_status()
                assert False
        except ClientResponseError as e:
            assert e.history

    event_loop.run_until_complete(inner())


def test_missing_history_with_session_var(event_loop):
    async def inner():
        session = aiohttp.ClientSession(raise_for_status=True)

        try:
            async with session.get('http://httpbin.org/status/404') as r:
                assert False
        except ClientResponseError as e:
            assert e.history

    event_loop.run_until_complete(inner())
```

## Your environment

- Python: 3.6.1
- aiohttp: 3.3.2
- Usage: client

**Comment by brettdh** [comment]
Or perhaps I am misunderstanding what `history` is. I am looking for some way to get the `ClientResponse` from the `ClientResponseError` object, and I thought `history` filled that purpose. Am I mistaken?

**Comment by asvetlov** [comment]
Nice catch!
`raise_for_status` should be processed after all code, just before `return resp`.

Would you make a Pull Request for the fix?

**Comment by brettdh** [comment]
Problem: this doesn't appear isolated to the `ClientSession(raise_for_status=True)` case; see the updated test above. Both versions fail.

**Comment by brettdh** [comment]
Perhaps this simply means that `raise_for_status` should add `self` to the `history` tuple of the `ClientResponseError` it raises?

**Comment by brettdh** [comment]
I'm looking for the `ClientResponse` object, from which I can get e.g. the response payload via `.text()` or `.json()`.

**Comment by brettdh** [comment]
Basically the equivalent of this in requests:
```python
import requests

try:
    r = requests.get('http://httpbin.org/status/404')
    r.raise_for_status()
except requests.exceptions.RequestException as e:
    print(e.response.status_code)
    print(e.response.text)
```
which prints
```
404

```
(the response body is empty in this case, but imagine it wasn't)

**Comment by asvetlov** [comment]
Consider response as closed after raising an exception.
Technically it can contain a partial body but there is no any guarantee.
There is no reason to read it, the body could be very huge, 1GiB is not a limit.
If you need a response content for non-200 -- read it explicitly.

**Comment by socketpair** [comment]
I vote for that. It also prevent forced closing of keep-alive connections since they can not be put to ClientSession’s pool due to unread body.
