### ISSUE TITLE
Deployment recommendation for a restful api

### ISSUE THREAD

**Issue by waghanza** [aio-libs/aiohttp#3249]
Hi,

On https://github.com/the-benchmarker/web-frameworks/pull/350, we are trying to compare `python` **frameworks**

@greed2411 Added `aiohttp`.

However, I can see that there is plenty way to deploy `aiohttp`
https://aiohttp.readthedocs.io/en/stable/deployment.html

Is there any recommandation for a restful api ?

With `gunicorn` (running on a `docker`) I have thos results

| Gunicorn worker    |         Average |  50th percentile |  90th percentile |  99th percentile | 99.9th percentile | Standard deviation |Requests / s |      Throughput |
|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|---------:|
| aiohttp.GunicornWebWorker                   | 45.79 ms | 43.31 ms | 62.73 ms | 121.39 ms | 298.51 ms | 18824.67 | 22116.00 | 50.16 MB |
| aiohttp.GunicornUVLoopWebWorker | 49.10 ms | 42.52 ms | 84.85 ms | 142.40 ms | 286.00 ms | 27636.67 | 21090.67 | 47.76 MB |

Regards,

**Comment by kxepal** [comment]
It depends on your system and setup, not of which kind of API you're trying to build.  You can also go with aiohttp + systemd if you have that one to avoid unnecessary services in your setup.  I don't think we could strongly recommend some way.

What problem are you trying to solve?

**Comment by waghanza** [comment]
@kxepal This deployment will be done on `cloud` (**aws** or so) and just running one **1** instance (no `NginX` only gunicorn)

This app is for benchmark, not facing customer ((I know **production-ready** platform should use `NginX` or an `ALB`)

**Comment by kxepal** [comment]
I see. Sorry, couldn't help here since I'm not familiar with any clouds, but may be others will.

**Comment by waghanza** [comment]
@kxepal no problem, I've merge this. Just keeping it here for information. I just use `uvloop` since more performing

**Comment by asvetlov** [comment]
If you have chosen to use gunicorn as load balancer -- the solution is up to you

**Comment by waghanza** [comment]
`gunicorn` will not be used as a loas balancer, there could be a NginX or Haproxy on top
