### ISSUE TITLE
json decode error with the colr.org website

### ISSUE THREAD

**Issue by PumPum7** [aio-libs/aiohttp#3250]
## Long story short

When I make an API call to this website: http://www.colr.org/json/color/random and transform the response to json I get this error: `Command raised an exception: ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=iso-8859-1'`

## Expected behaviour
I expected to get the data as json like I did when I used the requests library

## Actual behaviour

I get an error and nothing gets returned

## Steps to reproduce

```python
async def request(url, data=None, params=None, headers=None):
    valid_responses = [200, 201, 202]
    async with aiohttp.ClientSession() as session:
        async with session.get(
            url, data=data, params=params, headers=headers
        ) as response:
            if response.status in valid_responses:
                return await response.json()
            return None
```
the url is `http://www.colr.org/json/color/random` in this case

## Your environment
I don't use a proxy server
I use Windows 10
My aiohttp version is 3.3.2

 client

**Comment by webknjaz** [comment]
Hm.. It looks like charset doesn't get separated from type. Have you tried newer version of aiohttp? It this reproducible under Linux?
Did you log HTTP request and response? It might be useful to use that in integration tests

**Comment by PumPum7** [comment]
1. I can't update my aiohttp because a different library requires this version
2. I didn't try it with Linux
3. How can I do that?

**Comment by webknjaz** [comment]
tcpdump/Wireshark

**Comment by MyNameIsCosmo** [comment]
Try throwing `content_type='text/plain; charset=iso-8859-1'` into the `r.json()`:
```python
async def request(url, data=None, params=None, headers=None):
    valid_responses = [200, 201, 202]
    async with aiohttp.ClientSession() as session:
        async with session.get(
            url, data=data, params=params, headers=headers
        ) as response:
            if response.status in valid_responses:
                return await response.json(content_type='text/plain; charset=iso-8859-1')
            return None
```

Reference:
https://github.com/aio-libs/aiohttp/blob/9c30840f3cb54d428264aa90319a44845c5bc5fa/aiohttp/client_reqrep.py#L923-L925

Edit:
Optionally, it seems like you can set `content_type=None` to disregard the content type check.

**Comment by asvetlov** [comment]
thanks @MyNameIsCosmo
