### ISSUE TITLE
Signature of HttpRequestParserC doesnt defaiults first two paramters   

### ISSUE THREAD

**Issue by majkrzak** [aio-libs/aiohttp#3253]
When trying to create instance of `HttpRequestParserC` following exception is raised. `None,None` have to be passed explicitly to create it

    File "aiohttp/_http_parser.pyx", line 539, in aiohttp._http_parser.HttpRequestParser.__init__
    TypeError: __init__() takes at least 2 positional arguments (0 given)

`HttpRequestParserPy` works as excepted

**Comment by asvetlov** [comment]
How did you get it?

**Comment by majkrzak** [comment]
from aiohttp.http_parser import HttpRequestParser
    parser = HttpRequestParser()

on

    Name: aiohttp
    Version: 3.4.2

**Comment by asvetlov** [comment]
`HttpRequestParser` is a private class, it should not be instantiated by a user.
The library provides no API stability guarantee for it.
However, if you still want to use it -- please learn the signature: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/_http_parser.pyx#L539

**Comment by majkrzak** [comment]
That's why i written. It doesn't match pythonic implementation.
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/http_parser.py#L73

And I'm using it cause i didn't find a way to use library with stream based interface.
`web.Server` is not suitable in my case, cause it probably can not be used with `asyncio.start_server`

**Comment by asvetlov** [comment]
The whole library cannot be used with `asyncio.start_server`. I wonder why do you need it for aiohttp


Parser is tightly coupled with aiohttp protocols from `web_protocol.py` and `client_proto.py`.
The recommended way to start `web.Server` is `ServerRunner` (unfortunately I've missed to document it but the usage is pretty close to `AppRunner`)

**Comment by majkrzak** [comment]
We went little oftopic. But my case was so simple (200 with octetstream or 301 depending on path of request) that I've decided to not use any library for that. But due to that I had to implement some request to letsencrrypt I get back to aiohttp to use client from there. I will check how ServerRunner runner fits my needs

**Comment by majkrzak** [comment]
My request handler is very simple

    async def handler(request: Request) -> Response:
	    if request.method == 'GET' and request.path == 'foo':
            return Response(body='foo')
        else:
            return HTTPMovedPermanently(f'https://{request.host}{request.path_qs}')

and I would like to not make to much code overhead to start it. It would be the best to just:

    start_server(handler, '', 80)

**Comment by asvetlov** [comment]
Low-level server doesn't need one-liner to get it running.
But 5 lines of code is not too much, isn't it?

```
async def handler(request: Request) -> Response:
    if request.method == 'GET' and request.path == 'foo':
        return Response(body='foo')
    else:
        raise HTTPMovedPermanently(f'https://{request.host}{request.path_qs}')

async def init():
    server = web.Server(handler)
    runner = web.ServerRunner(server)
    await runner.setup()
    site = web.TCPSite(runner, 'localhost', 8080)
    await site.start()    

```

**Comment by majkrzak** [comment]
More that twice mopre :P

**Comment by asvetlov** [comment]
mopre?

**Comment by asvetlov** [comment]
Only in docs for copy-paste :D

**Comment by asvetlov** [comment]
Done by #3254
