### ISSUE TITLE
CONNECT method is never matched

### ISSUE THREAD

**Issue by gera2ld** [aio-libs/aiohttp#3257]
## Long story short

CONNECT method can never be matched in code below.

```py
from aiohttp import web

def handle(request):
    print(request.method)
    return web.Response(text='ok')

app = web.Application()
app.router.add_route('*', '/{path:.*}', handle)
# or
# app.router.add_route('CONNECT', '/{path:.*}', handle)
web.run_app(app)
```

Send a `CONNECT` request and got 404.

```
CONNECT www.google.com:443 HTTP/1.0
...
```

## Expected behaviour

It should be matched.

## Actual behaviour

It is never matched because of the path.

When declaring routes, `path` is required to start with `/`. But `path` of `CONNECT` requests will be something like `www.google.com:443` with no prefixed `/`. As a result, 404 is raised.

**Comment by asvetlov** [comment]
Aiohttp web app was never supposed to handle CONNECT. 
Low-level api can handle it. 

But supporting CONNECT in web-handlers violates the router design structure. 
Zero chance to support the feature on web app level

**Comment by gera2ld** [comment]
OK, can we update the document about this?
Thanks anyway.

**Comment by asvetlov** [comment]
Feel free to write a pull request for docs update.
For now, you are the only person who requested it.
