### ISSUE TITLE
What takes request.task so long to complete (server)?

### ISSUE THREAD

**Issue by dfee** [aio-libs/aiohttp#3259]
## Long story short
Using aiohttp.web (i.e. "server"), I want to close websockets associated with a session on signin/signout. To avoid a race condition, I moved the websocket-closing code from the signin handler to a callback on `request.task`. However, it's taking 90+ seconds for the "done callbacks" to be called. What's taking so long?

## Expected behaviour
The task future is completed immediately following the connection termination.

## Actual behaviour
The task hangs for more than a minute before completing

## Steps to reproduce

```python
import asyncio
from datetime import datetime

from aiohttp import web

print_now = lambda name: print(
    f"{name}: {datetime.now().isoformat()}", flush=True
)


async def handle_root(request):
    async def aio_printcb():
        await request.task
        print_now("aio_printcb")

    def io_printcb(fut):
        print_now("io_printcb")

    asyncio.ensure_future(aio_printcb())
    request.task.add_done_callback(io_printcb)

    print_now("responding")
    return web.Response(text="Done", content_type="text/html")


if __name__ == "__main__":
    app = web.Application()
    app.router.add_get("/", handle_root)
    web.run_app(app)
```

```
$ python dummy.py
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
responding: 2018-09-09T23:36:39.468984
io_printcb: 2018-09-09T23:37:54.477136
aio_printcb: 2018-09-09T23:37:54.477185
```

## Your environment
aiohttp 3.4.4
python 3.7.0
MacOS 10.13.6

**Comment by webknjaz** [comment]
Also ref https://docs.python.org/3/library/asyncio-dev.html

**Comment by asvetlov** [comment]
The task is created not for serving the single request but for the whole connection from a peer.
It means for keep-alive mode the task exists longer (75 secs at least by default).

Side note: please consider futures/tasks callbacks as low-level API. Better to leave it to libraries on;y and avoid the usage in app-level business logic.

**Comment by dfee** [comment]
I was hoping for something that would be called after the request has been completed, is this possible?

In more detail, I have a `POST /login` and a `POST /logout`, and if I terminate websocket connections...
```python
asyncio.gather(*[ws.close() for ws in app['session_websockets']])
```

Then it's quite possible that a re-connecting websocket will be terminated and will reconnect with the old session before a new session cookie (using `aiohttp_security` and `aiohttp_session`) is returned from the (e.g.) `/login` path.

Is there a better way of doing this?

**Comment by webknjaz** [comment]
You might be seeking for https://github.com/aio-libs/aiojobs

**Comment by dfee** [comment]
@webknjaz I don't *think* `aiojobs` would solve this problem, as I still can't tell it to execute **after** the request has completed.

Imagine the following code:
```python
async def logout(request):
  old_session_id = await get_session(request).identity
  await new_session(request)
  await asyncio.gather(*[ # termination of websockets begins on next await
    ws.close()
    for ws in app['session_websockets'][old_session_id]
  ])
  # the updated session cookie could be delayed by middleware,
  # this would allow for a reconnecting websocket to reconnect with the
  # old session cookie (the browser hadn't received the new session, yet)
  return web.Response(text='Done', content_type='text/html')
```

**Comment by dfee** [comment]
Ah. I think I might have found the solution. @asvetlov maybe you can provide insight here.

I'm continuing to use `request.task`, but now I'm also using `response.force_close()` to immediately terminate the response after it's completed. (are there negative consequences to this...?)

```python
import asyncio
from datetime import datetime
import sys
import ipdb

from aiohttp import web

print_now = lambda name: print(
    f"{name}: {datetime.now().isoformat()}", flush=True
)

sys.breakpointhook = ipdb.set_trace


async def handle_root(request):
    async def aio_printcb():
        await request.task
        print_now("aio_printcb")

    def io_printcb(fut):
        print_now("io_printcb")

    asyncio.ensure_future(aio_printcb())
    request.task.add_done_callback(io_printcb)

    print_now("responding")
    resp = web.Response(text="Done", content_type="text/html")
    resp.force_close()  # ** Our new addition **
    return resp


if __name__ == "__main__":
    app = web.Application()
    app.router.add_get("/", handle_root)
    web.run_app(app)
```

```
$ python dummy.py
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
responding: 2018-09-10T13:19:52.782614
aio_printcb: 2018-09-10T13:19:52.783214
io_printcb: 2018-09-10T13:19:52.783286
```

**Comment by dfee** [comment]
And here is a fully packaged solution:
```python
def disconnect_session_websockets(app: web.Application, sid: str) -> None:
    if sid in app["session_websockets"]:
        wsrs = app["session_websockets"][sid]
        asyncio.gather(*[wsr.close() for wsr in wsrs])


async def reset_session(
    request: web.Request, response: typing.Union[web.Response, web.HTTPFound]
) -> None:
    sid = (await get_session(request)).identity

    async def onclose() -> None:
        await request.task
        disconnect_session_websockets(request.app, sid)

    session = await new_session(request)
    touch_session(session)

    asyncio.ensure_future(onclose())
    response.force_close()


async def handle_login(request: web.Request) -> None:
    response = web.HTTPFound("/")
    await reset_session(request, response)

    await remember(request, response, "jack")
    session = await get_session(request)
    session.max_age = 60 * 60 * 24 * 30  # 30 days

    raise response
```

**Comment by asvetlov** [comment]
`force_close()` disables HTTP keepalive feature.
If it's ok for you -- feel free to keep the call.

Could you be more clear in describing a race condition if you call websockets closing immediately in `handle_login()` or `reset_session()`?

**Comment by dfee** [comment]
This is a solved issue for me. I created https://github.com/dfee/aiohttp_session_ws from it.

Anyway, the problem is that if `handle_login` drops the websocket upon the request finishing, and that request takes 90 seconds to finish, that gives plenty of time for new websockets to connect (those that couldn't have been scheduled for closure), with the outdated session.

**Comment by asvetlov** [comment]
Ok, solved means solved.
