### ISSUE TITLE
Deprecate stream.unread_data

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3260]
`stream.unread_data()` is a leaking abstracton: it violates chunk boundaries at least.
Aso, it prevents some optimizations.

The call is used in multipart. We already have `MultipartBodyReader._unread` buffer, replacement `stream.unread_data()` wit appending to `self._unread` looks feasible.

**Comment by asvetlov** [comment]
@kxepal I need your help
Can you spend a bit of your spare time on replacement `stream.unread_data()` with adding a read chunk into `self._unread` in multipart?

aiohttp 3.5 is going to be the latest 3.x release; I'd like to deprecate the method now and remove it entirely in aiohttp 4.0

**Comment by kxepal** [comment]
Ok, will do that, tomorrow (6.12).

**Comment by asvetlov** [comment]
Thanks!

**Comment by kxepal** [comment]
That seems wouldn't be too easy. We relay too much on that stream `unread_data` in different places and it serves a little bit different purpose than internal `_unread` - those one holds whole lines, while we have to unread arbitrary chunks of data. Mixing them breaks a lot.

I feel that I would have just to reimplement those stream unread logic on multipart side, what may be no very cool, but at least it will hold all the bits and not depend on foreign state.

**Comment by asvetlov** [comment]
@kxepal thanks for the status update.

I need your opinion: can we live with #3439 for a while? I don't want to block the release on the issue

**Comment by asvetlov** [comment]
@kxepal thanks!

**Comment by asvetlov** [comment]
Fixed by #3439
