### ISSUE TITLE
Requesting https://fiverr.com gives ClientPayloadError

### ISSUE THREAD

**Issue by Hemable1** [aio-libs/aiohttp#3263]
Simply put, you get a `aiohttp.client_exceptions.ClientPayloadError: 400, message='deflate'` error when trying to request certain sites. Sending the request through a proxy to analyze the traffic works and doesn't throw an error, possibly because the proxy is decoding the response properly. An example site that is broken is sending a request to `https://fiverr.com`.

```python
import asyncio
import aiohttp

async def req(url):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36'
    }

    async with aiohttp.ClientSession(headers=headers) as session:
        async with session.get(url) as resp:
            print(resp.status)
            print(await resp.text())

loop = asyncio.get_event_loop()
loop.run_until_complete(req("https://fiverr.com"))
```

Returns:
```python-traceback
  File "[...]\site-packages\aiohttp\streams.py", line 325, in readany
    raise self._exception
aiohttp.client_exceptions.ClientPayloadError: 400, message='deflate'
```

Tested on:
Windows 7x64
Python 3.7.0
aiohttp 3.3.2

**Comment by webknjaz** [comment]
You need to send us full traceback and traffic/headers/request/response capture.

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
Feel free to create a new issue with the necessary information if you're still encountering this issue.
