### ISSUE TITLE
Deprecation warnings in 3.8

### ISSUE THREAD

**Issue by wumpus** [aio-libs/aiohttp#3273]
/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/aiohttp/multipart.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, Sequence, deque

This is a safe change to make, collections.abc was introduced in 3.3.

**Comment by asvetlov** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/aio-libs/aiohttp/issues/3252 (False-positive deprecation warning for partial async handlers), https://github.com/aio-libs/aiohttp/issues/1575 (Deprecation policy), https://github.com/aio-libs/aiohttp/issues/130 (Multiple Test Warnings on Python 3.4 (ResourceWarning / DeprecationWarning)), https://github.com/aio-libs/aiohttp/issues/2670 ([injection] 2.3.8 broke certain regex match patterns), and https://github.com/aio-libs/aiohttp/issues/1603 (1.3 Release).

**Comment by augustogoulart** [comment]
I'm getting the same  warnings while writing tests for an application using Python 3.7 and pytest 3.8.0.
@wumpus do you have plans to work on that? If not, I would like to work on a patch for it. Thanks.

**Comment by wumpus** [comment]
Please do the patch! It's quite easy.

**Comment by Harmon758** [comment]
This specific line should already be fixed with #3258 (https://github.com/aio-libs/aiohttp/commit/c8c05677a3113264f8701e83ce0b8b10d378e8e7).
