### ISSUE TITLE
Css doesn't load - Nginx Deployment

### ISSUE THREAD

**Issue by merlinfuchs** [aio-libs/aiohttp#3283]
## Long story short

Im trying to deplo my aiohttp server with nginx. This is my configuration of nginx:
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;

  server {
    listen 80;
    client_max_body_size 4G;

    server_name bots.discord.club;

    location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect off;
      proxy_buffering off;
      proxy_pass http://aiohttp;
    }

    location /static {
      root /var/www/html;
    }

  }

  upstream aiohttp {
    # fail_timeout=0 means we always retry an upstream even if it failed
    # to return a good HTTP response

    # Unix domain servers
    # server unix:/tmp/example_1.sock fail_timeout=0;
    # server unix:/tmp/example_2.sock fail_timeout=0;
    # server unix:/tmp/example_3.sock fail_timeout=0;
    # server unix:/tmp/example_4.sock fail_timeout=0;

    # Unix domain sockets are used in this example due to their high performance,
    # but TCP/IP sockets could be used instead:
    server 127.0.0.1:8081 fail_timeout=0;
    # server 127.0.0.1:8082 fail_timeout=0;
    # server 127.0.0.1:8083 fail_timeout=0;
    # server 127.0.0.1:8084 fail_timeout=0;
  }
}
```
Everything works fine, beside that css from the static route isnt working.

![image](https://user-images.githubusercontent.com/33966852/45930223-bf785c00-bf5d-11e8-8597-6ce0b96457ef.png)

It seems like nginx returns it as text/plain. I know this is probably a problem with nginx, but they wasnt able to help me, so I ask here.

## Expected behaviour

Css should load.

## Actual behaviour

Css doesn't load.

## Steps to reproduce

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;

  server {
    listen 80;
    client_max_body_size 4G;

    server_name bots.discord.club;

    location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect off;
      proxy_buffering off;
      proxy_pass http://aiohttp;
    }

    location /static {
      root /var/www/html;
    }

  }

  upstream aiohttp {
    # fail_timeout=0 means we always retry an upstream even if it failed
    # to return a good HTTP response

    # Unix domain servers
    # server unix:/tmp/example_1.sock fail_timeout=0;
    # server unix:/tmp/example_2.sock fail_timeout=0;
    # server unix:/tmp/example_3.sock fail_timeout=0;
    # server unix:/tmp/example_4.sock fail_timeout=0;

    # Unix domain sockets are used in this example due to their high performance,
    # but TCP/IP sockets could be used instead:
    server 127.0.0.1:8081 fail_timeout=0;
    # server 127.0.0.1:8082 fail_timeout=0;
    # server 127.0.0.1:8083 fail_timeout=0;
    # server 127.0.0.1:8084 fail_timeout=0;
  }
}
```

## Your environment

Ubuntu 16.04 LTS 64bit,
Nginx 1.10.3,
aiohttp 3.4.4

**Comment by asvetlov** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/aio-libs/aiohttp/issues/552 (More information about deployment?), https://github.com/aio-libs/aiohttp/issues/1842 (Can not load response cookies...), https://github.com/aio-libs/aiohttp/issues/3075 (trust_env doesn't works), https://github.com/aio-libs/aiohttp/issues/234 (Add note about production deployment), and https://github.com/aio-libs/aiohttp/issues/139 (Cookies doesn't shared between requests).

**Comment by kxepal** [comment]
This isn't aiohttp issue, but nginx misconfiguration. Check you nginx error log for any file read errors.  Make sure request for static location hit nginx, but not aiohttp. Your configuration perfectly works for me (1.12.2).

**Comment by merlinfuchs** [comment]
I already checked all nginx logs. The only thing I have is the output of the chrome console. (Screenshot above). 
The file gets loaded from nginx but with the wrong header "text/plain" (should be text/css)

**Comment by kxepal** [comment]
What the response will be if you request your css via curl? Will nginx send you correct Content-Type header?

**Comment by merlinfuchs** [comment]
Ok, wtf. Now it randomly works. Did not change anything ...
Thank You anyway!

**Comment by MyNameIsCosmo** [comment]
Perhaps it's a cache issue?
I'd check nginx proxy caching configurations.

Maybe relevant:
https://stackoverflow.com/questions/6236078/how-to-clear-the-cache-of-nginx

**Comment by merlinfuchs** [comment]
Yeah that was probably the issue. Thank You all.
