### ISSUE TITLE
ImportError: cannot import name 'hdrs'

### ISSUE THREAD

**Issue by sbhadr** [aio-libs/aiohttp#3285]
## Long story short

Aiohttp is unusable when imported on Python 3.5.

## Expected behaviour

Normal usage.

## Actual behaviour

``ImportError: cannot import name 'hdrs'`` when importing aiohttp.

## Steps to reproduce

``import aiohttp``

## Your environment

Windows 10, Python 3.5

## Error Log
```
Traceback (most recent call last):
  File "cc.py", line 1, in <module>
    from pyblox import *
  File "C:\Users\sanja\AppData\Local\Programs\Python\Python35\lib\site-packages\pyblox\__init__.py", line 16, in <module>
    from .api.assets import Assets
  File "C:\Users\sanja\AppData\Local\Programs\Python\Python35\lib\site-packages\pyblox\api\assets.py", line 9, in <module>
    from .http import Http
  File "C:\Users\sanja\AppData\Local\Programs\Python\Python35\lib\site-packages\pyblox\api\http.py", line 11, in <module>
    import aiohttp
  File "C:\Users\sanja\AppData\Roaming\Python\Python35\site-packages\aiohttp\__init__.py", line 9, in <module>
    from . import hdrs  # noqa
ImportError: cannot import name 'hdrs'
```

**Comment by asvetlov** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/aio-libs/aiohttp/issues/849 (Example Server Fails to Run with "ImportError: cannot import name 'InvalidURL'"), https://github.com/aio-libs/aiohttp/issues/843 (ImportError: No module named 'aiohttp'), https://github.com/aio-libs/aiohttp/issues/2662 (ImportError: cannot import name 'unquote'), https://github.com/aio-libs/aiohttp/issues/1447 (ImportError: cannot import name 'quote'), and https://github.com/aio-libs/aiohttp/issues/936 (ImportError: No modile named 'http.server' when I try to run pytests).

**Comment by asvetlov** [comment]
The minimal supported version is Python 3.5.3
If you have it at least -- aiohttp works, we run tests for Python 3.5 on Windows box explicitly

**Comment by sbhadr** [comment]
Import Error on call is not exactly my conception of "working". Any reason as to why Python 3.5.3 is supported but not Python 3.5 ?

**Comment by asvetlov** [comment]
aiohttp relies on features introduced in Python 3.5.3
Do you use older Python?

**Comment by asvetlov** [comment]
Python 3.5.X
What is X on your box?
If your `pip` version is not too old the tool cannot install aiohttp 3.x on not compatible Python, e.g. 3.5.2

**Comment by sbhadr** [comment]
``Python 3.5.X What is X on your box?``
Python 3.5.0

``If your pip version is not too old the tool cannot install aiohttp 3.x on not compatible Python, e.g. 3.5.2``
Pip is up to date. 

Could you be specific as to which features introduced in Python 3.5.3 ?

**Comment by asvetlov** [comment]
Up-to-date pip means `pip --version` is something like `18.0`.
It respects `python-requires` argument from metadata: https://github.com/aio-libs/aiohttp/blob/master/setup.py#L148

There are many changes: `transport.set_protocol()` and `__aiter__` signature for example.
The most notable change is: `asyncio.get_event_loop()` is reliable.
If called from async function the returned value is an active (running) loop, not the loop specified by `asyncio.set_event_loop()` call.
