### ISSUE TITLE
ability to not output Server header

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiohttp#3288]
## Long story short

It may be desirable to hide which server is running to avoid making it easy to target vulnerabilities.  Currently the "server" header is populated without any mechanism to disable/change it.

## Expected behaviour

Ability to disable/change the server header value

## Actual behaviour

server header populated with current aiohttp/python version

## Steps to reproduce

Start server and curl endpoint, look at headers returned.

**Comment by thehesiod** [comment]
I'll work on a PR today to parameterize this.

**Comment by asvetlov** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/aio-libs/aiohttp/issues/1958 (Possibility to disable Server header), https://github.com/aio-libs/aiohttp/issues/2022 ([enhancement] ability to return redirect responses which don't have 'location' header), https://github.com/aio-libs/aiohttp/issues/2637 (Stop server error), https://github.com/aio-libs/aiohttp/issues/3140 (Q: possible to set Server header with web.Server?), and https://github.com/aio-libs/aiohttp/issues/1652 (Trailer headers).
