### ISSUE TITLE
Missing raise_for_status parameter to aiohttp.request

### ISSUE THREAD

**Issue by artslob** [aio-libs/aiohttp#3290]
## Missing raise_for_status parameter to aiohttp.request
Well the title stands for itself.
Documentation on [aiohttp.request](https://docs.aiohttp.org/en/stable/client_reference.html#basic-api) stands, that this method have argument `raise_for_status`, which was added in version 3.4. 
But looking into [current code](https://github.com/aio-libs/aiohttp/blob/044996a59ad574c101bb4fe5c47a78f6dc0067cc/aiohttp/client.py#L892) of file `aiohttp.client.py` shows that this method do not have such argument.

## Expected behaviour

Expected that this code will work like a charm:
```python
import aiohttp
async with aiohttp.request('GET', 'www.example.com', raise_for_status=True, ) as response:
    pass
```

## Actual behaviour

Get type error:
```python
TypeError: request() got an unexpected keyword argument 'raise_for_status'
```

## Steps to reproduce
```python
import aiohttp
import asyncio

async def fetch():
    async with aiohttp.request('GET', 'http://python.org/', raise_for_status=True) as resp:
        assert resp.status == 200
        print(resp.status)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(fetch())
```

## Your environment
aiohttp==3.4.4
Client

**Comment by asvetlov** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/aio-libs/aiohttp/issues/432 (asyncio.wait_for throwing a timeout error on aiohttp.request?), https://github.com/aio-libs/aiohttp/issues/168 (aiohttp.web missing), https://github.com/aio-libs/aiohttp/issues/1403 ([QUESTION] aiohttp.ClientSession.request('GET') issue), https://github.com/aio-libs/aiohttp/issues/2878 (Add argument 'raise_for_status' to 'ClientSession' request method.), and https://github.com/aio-libs/aiohttp/issues/2920 (AIOHttp failing after some requests).

**Comment by asvetlov** [comment]
Makes sense.
Would you provide a Pull Request?

**Comment by artslob** [comment]
Yep. Will try to do something on this holidays
