### ISSUE TITLE
Add type annotations everywhere, help needed

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3293]
I'm working on adding type hints.
The hints are useless until their correctness is checked by `mypy` in strong mode.

The problem is: enabling the mode for the whole codebase generates too many errors.
Basically, it is the all-or-nothing situation.

The plan is: let's convert file by file.
To enable strong mode please uncomment mypy options from the settings file: https://github.com/aio-libs/aiohttp/blob/master/setup.cfg#L42-L48
Before submitting a Pull Request please make sure that uncommented config is not landed (revert settings back).

The job is trivial but requires updating too many source code lines, that's why I need a help from the community. Even small PRs are valuable.

**Comment by YuvalPruss** [comment]
@asvetlov If I want to contribute to this, which PR should I use?

**Comment by asvetlov** [comment]
aiohttp master branch as usual.
I quite don't understand the question about PR but assume you are asking for code branch to start work from.

**Comment by asvetlov** [comment]
Hint:
For `MultiDict`, `CIMultiDict`, `Signal` and `FrozenList` classes use forward declarations like `"CIMultiDict[str]"` or `aiohttp.typedefs._CIMultiDict` to avoid runtime errors.

**Comment by asvetlov** [comment]
`tracing.py` looks like an easy file to start.
One file per PR is a pretty good modularity for this meta-issue.

**Comment by asvetlov** [comment]
Finished
