### ISSUE TITLE
can it suit wsgi

### ISSUE THREAD

**Issue by lateautunm** [aio-libs/aiohttp#3297]

**Comment by hellysmile** [comment]
Do You wanna to server wsgi application via aiohttp?
https://github.com/etianen/aiohttp-wsgi might help You.
If You want to get wsgi interface to aiohttp - then no, similar interface calls https://channels.readthedocs.io/en/latest/asgi.html , but aiohttp do not support it https://github.com/aio-libs/aiohttp/issues/2902

**Comment by hellysmile** [comment]
If You have more detailed questions, please open new issue
