### ISSUE TITLE
Server logging code is very slow

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#330]
Code log access log generation is very slow.

**Comment by ludovic-gasc** [comment]
Hi,

**Warning: My experimentations below based on my experimentations 1-2 years ago, when I started to use heavily AsyncIO, I was less experimented than now**.

About logging, when I've benchmarked, I've remarked that when I use a file or console handler, I'd some performances impacts. The less consuming manner I've found is to use a SyslogHandler that uses UNIX socket, and configure correctly rsyslog to write the log file.

Config example with a [logging.ini](https://github.com/Eyepea/cookiecutter-API-Hour/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/etc/%7B%7Bcookiecutter.app_name%7D%7D/api_hour/logging.ini#L21).
A [rsyslog.conf](https://github.com/Eyepea/cookiecutter-API-Hour/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/etc/rsyslog.conf#L73) example.

I thought to implement some logging handlers with AsyncIO to reduce the impact.
No time to do that, if somebody else wants to do that, take the candy ;-)

If you find something else, I'm interested in.

**Comment by fafhrd91** [comment]
this issue is not really related to python logging facility, it is about code in aiohttp that generates log messages for access_log. in my benchmarks turning off logging usually gives 25-30% increase.
and by turning off i mean pass None as access_log parameter to ServerHttpProtocol.

**Comment by ludovic-gasc** [comment]
You loose 25-30% even if you reduce the log level to ERROR ?

**Comment by fafhrd91** [comment]
yes, it is not python logging package problem. it is how we generate strings for access log.

**Comment by fafhrd91** [comment]
problem is here
https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/helpers.py#L216
https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/helpers.py#L251

**Comment by fafhrd91** [comment]
close by #572
