### ISSUE TITLE
Work with files asynchronously

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3313]
There is a very old tech debt in aiohttp: the library uses blocking synchronous calls to work with files.

It should be fixed by replacement such direct calls by `loop.run_in_executor()`.

Affected parts:
- [x] `web_fileresponse.py`
- [x] `payload.py`

Splitting the task into two pull requests makes sense in term of easier review.

The issue is pretty easy and straightforward, it waits for a champion.

**Comment by socketpair** [comment]
Do not forget to `open()` files also in a thread.

I think, internal API should be the following:

```python
import aiofiles

file = await aiofiles.open()
result = await file.read()
result = await file.write()
await file.chmod()
await file.fsync()
...
```

UPD: https://github.com/Tinche/aiofiles  buth this solution is overingeneered. I would write my own with implementing each method explicitly.

**Comment by asvetlov** [comment]
I don't want to use aiofiles.
`run_in_executor` is just enough for the library needs.
aiohttp calls `open()` in `file_response.py` only, client API accepts already opened regular IO objects.
Wrapping them into aiofiles looks more complex than explicit thread pool usage.

**Comment by chirgjn** [comment]
👋 would love to pick this up, if not fixed already

**Comment by asvetlov** [comment]
Please go ahead!

**Comment by kxepal** [comment]
This could raise a holywar, but I'll risk to ask you: why not aiofiles?

**Comment by asvetlov** [comment]
Did you read messages above?
I can send a ball back: why aiofiles despite the fact that we need only run in executor a couple IO calls?

**Comment by kxepal** [comment]
Yes, I did, but some abstraction may be useful to not care about that bit if it will eventually have changed. If that's the only reason than it satisfied my curiousity (:

**Comment by asvetlov** [comment]
Changes will not touch the public API.
Choosing an abstraction layer for async files support is the subject for future discussion, let's do it in another issue if you want to.

**Comment by asvetlov** [comment]
Done
