### ISSUE TITLE
Deprecate accepting bool in resp.enable_compression()

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3318]
bool is discouraged for very long time (3 years?) but we need a formal deprecation before the feature removing.

**Comment by OisinA** [comment]
Done in the following PR: [https://github.com/aio-libs/aiohttp/pull/3322](url)

**Comment by gyermolenko** [comment]
proper link to PR https://github.com/aio-libs/aiohttp/pull/3322
