### ISSUE TITLE
Nginx Deployment | Post Requests

### ISSUE THREAD

**Issue by merlinfuchs** [aio-libs/aiohttp#3327]
## Long story short

I'm trying to use nginx as a reverse proxy for my aiohttp server. That works fine with get requests, but it seems like nginx overwrites all post requests to get requests. 

For example I make a post request to my nginx server and it passes it to the aiohttp server. But the aiohttp server gets a get request instead of post.

I know this is a nginx problem, but I wasn't able to find a solution somewhere else ...

## Expected behaviour

Aiohttp should get a post request when making a post request to the nginx server.

## Actual behaviour

Aiohttp gets a get request.

## Steps to reproduce

Run a aiohttp server on the port 8082 and create a post route. 
Configure your nginx server like this:

```
server {
  listen 80;
  listen 443 ssl;

  ssl_certificate /etc/nginx/ssl/nginx.crt;
  ssl_certificate_key /etc/nginx/ssl/nginx.key;

  server_name api.discord.club;

  underscores_in_headers on;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass http://localhost:8082;
  }

}
```

## Your environment

Ubuntu 16.04 LTS 64bit,
Nginx 1.10.3,
aiohttp 3.4.4

**Comment by MyNameIsCosmo** [comment]
Try the Nginx configuration in the aiohttp docs:
https://docs.aiohttp.org/en/stable/deployment.html#nginx-configuration

**Comment by merlinfuchs** [comment]
Still the same problem ...

**Comment by merlinfuchs** [comment]
Looks like, the problem doesn't occur if I make the request over https.

**Comment by paxswill** [comment]
If you follow the individual requests, I'd guess you're going to see a 301 or 302 redirect from http to https. Those redirects will commonly change the request method to GET.

**Comment by rascalking** [comment]
Pretty sure @paxswill is on to something.  Something that's returning a 301/302 should be returning a 307/308 (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections for a discussion of the difference).

**Comment by asvetlov** [comment]
@rascalking  perhaps you right, but hard to confirm without looking on the source code.

Closing the issue, nothing to do here without more info.
I see nothing bad in nginx config, pretty similar configuration works for me perfectly fine.
