### ISSUE TITLE
Fix flake8 dependency for dev environment

### ISSUE THREAD

**Issue by dbohomiakov** [aio-libs/aiohttp#3345]
## Long story short
There is an inconsistency in the requirements files. In the `requirements/ci-wheel.txt` explicitly defined `pyflakes` with version `2.0.0` but `flake8` which uses `pyflakes` as dependency requires version from the range `>= 1.5.0, < 1.7.0`. The newest version overwrites the required one.
## Steps to reproduce
`pip install -r requirements/dev.txt`
## Your environment
MacOS 10.14, python 3.6.5, aiohttp 3.4.4
both

**Comment by asvetlov** [comment]
Fixed by #3346
