### ISSUE TITLE
ClientDisconnectedError should be a subclass of ClientError

### ISSUE THREAD

**Issue by tdryer** [aio-libs/aiohttp#335]
With the current exception hierarchy it's necessary to catch `ClientError` and `ClientDisconnectedError` separately when calling `aiohttp.client.request`. If `ClientDisconnectedError` inherited from `ClientError` as well as `DisconnectedError`, exception checking could be simplified.

**Comment by fafhrd91** [comment]
could you explain your use case. use case for ClientError and ClientDisconnectedError is totally different.

**Comment by asvetlov** [comment]
From my perspective ClientError is for errors on making connection to server side, but ClientDisconnectedError is for server which got disconnection from client. 
Those are totally different, as @fafhrd91 mentioned.

**Comment by fafhrd91** [comment]
we may rename ClientDisconnectedError to something more friendly

**Comment by asvetlov** [comment]
The name is confusing me too a bit (as my coworkers), but I cannot guess the better.

**Comment by fafhrd91** [comment]
`ServerClientDisconnectedError` ?

**Comment by asvetlov** [comment]
Too long and still not comprehensive.
DisconnectedByClientError?
Maybe better but I not like it very well :(

On Mon, Apr 20, 2015 at 9:41 PM, Nikolay Kim notifications@github.com
wrote:

> ServerClientDisconnectedError ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KeepSafe/aiohttp/issues/335#issuecomment-94535160.

## 

Thanks,
Andrew Svetlov

**Comment by kxepal** [comment]
ServerClientDisconnectedError clashes with ServerDisconnectedError.

How about to use good old ConnectionResetByPeer and show the context in it message?

**Comment by asvetlov** [comment]
I like ConnectionResetByPeer but it should be ServerConnectionResetByPeer and ClientConnectionResetByPeer isn't it?

**Comment by fafhrd91** [comment]
i do not like ConnectionResetByPeer, but i like ServerConnectionResetByPeer and ClientConnectionResetByPeer

**Comment by kxepal** [comment]
Ok with ServerConnectionResetByPeer and ClientConnectionResetByPeer (:

**Comment by ludovic-gasc** [comment]
I've a suggestion: If you have several errors in the same category but you try to avoid long names, maybe you should use the same trick as socket: a more generic error and you have details inside exception:
http://stackoverflow.com/a/5161286/1211023

**Comment by kxepal** [comment]
@GMLudo I'd tried that with just ConnectionResetByPeer, but you see how it ended (:

P.S. First thought was that you suggest to return back to error codes and the magic enum deep inside the source code that explains them properly ((:

**Comment by fafhrd91** [comment]
i think ServerConnectionResetByPeer and ClientConnectionResetByPeer names are not solve problem with naming. i think main problem is that we need to use ClientDisconnected on service side and ServiceDisconnected on client side. so we should not use `Client` as prefix.

**Comment by tdryer** [comment]
> The name is confusing me too a bit (as my coworkers), but I cannot guess the better.

Yeah, the naming made me think that `ClientDisconnectedError` should be a kind of `ClientError`.

It would be convenient if there was a base exception for all the exceptions that aiohttp raises, like how Requests has [RequestException](http://docs.python-requests.org/en/latest/api/#requests.exceptions.RequestException).

**Comment by asvetlov** [comment]
Let's close it until somebody suggest better naming.
