### ISSUE TITLE
window10 ProactorEventLoop does't not exit normally when task has finished

### ISSUE THREAD

**Issue by woshimanong1990** [aio-libs/aiohttp#3359]
## Expected behaviour
`# coding:utf-8

import aiohttp
import asyncio

async def fetch(session, url):
    async with session.get(url) as response:
        return await response.text()

async def main():
    async with aiohttp.ClientSession() as session:
        html = await fetch(session, 'http://python.org')
        print(html)

loop = asyncio.ProactorEventLoop()
asyncio.set_event_loop(loop)
loop = asyncio.get_event_loop()
loop.run_until_complete(main())`

It exits normalley; However, when I use SelectorEventLoop, it works!
## Actual behaviour
In face ,the program does't not exit; When I write result to a file, the content is not written to file;

It does't exit; when I attempt to close the loop, Error happen;
`Exception ignored in: <bound method _ProactorBasePipeTransport.__del__ of <_ProactorSocketTransport closing fd=836 read=<_OverlappedFuture cancelled>>>
Traceback (most recent call last):
  File "d:\software\programe\python35\Lib\asyncio\proactor_events.py", line 96, in __del__
    self.close()
  File "d:\software\programe\python35\Lib\asyncio\proactor_events.py", line 84, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\software\programe\python35\Lib\asyncio\base_events.py", line 572, in call_soon
    self._check_closed()
  File "d:\software\programe\python35\Lib\asyncio\base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <bound method _ProactorBasePipeTransport.__del__ of <_ProactorSocketTransport closing fd=876 read=<_OverlappedFuture cancelled>>>
Traceback (most recent call last):
  File "d:\software\programe\python35\Lib\asyncio\proactor_events.py", line 96, in __del__
    self.close()
  File "d:\software\programe\python35\Lib\asyncio\proactor_events.py", line 84, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\software\programe\python35\Lib\asyncio\base_events.py", line 572, in call_soon
    self._check_closed()
  File "d:\software\programe\python35\Lib\asyncio\base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
`
## Steps to reproduce
run the code 
`# coding:utf-8

import aiohttp
import asyncio

async def fetch(session, url):
    async with session.get(url) as response:
        return await response.text()

async def main():
    async with aiohttp.ClientSession() as session:
        html = await fetch(session, 'http://python.org')
        print(html)

loop = asyncio.ProactorEventLoop()
asyncio.set_event_loop(loop)
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()`

## Your environment
window10 +  python 3.5.3

**Comment by woshimanong1990** [comment]
Now try to run the same code on python 3.7.1. Unbelievably, it seem to run normally. Maybe it's a python bug!

**Comment by woshimanong1990** [comment]
# python 3.6.5 also works!

**Comment by woshimanong1990** [comment]
I think it's a bug!

**Comment by asvetlov** [comment]
Several proactor problems were fixed in 3.6
You report definitely is not related to aiohttp itself, closing it.
