### ISSUE TITLE
wrong cookies when i use aiohttp.ClientSession(cookies=cookies)

### ISSUE THREAD

**Issue by kcorlidy** [aio-libs/aiohttp#3371]
I try to update my eBay watch list with the code , i try many time but all failed. btw i use same cookies on `requests` and it done.

	product_link = "https://www.ebay.com/itm/PlayStation-4-1TB-Console-Call-of-Duty-Black-Ops-3-Limited-Edition-PS4-w-game/253956457448?epid=218347966&hash=item3b20fc03e8:g:uh0AAOSwQrVb190x:rk:11:pf:0"

	async def main():
		async with aiohttp.ClientSession(cookies=cookies,headers=headers) as sessions:
			async with sessions.get(product_link) as resp:
				r = await resp.text()
				watch_link = soup(r, "lxml").find("div", {"id": "vi-atl-lnk"}).a.get("href")
				print(watch_link)
				
			async with sessions.get(watch_link) as resp:
				pass
			async with sessions.get(watch_link) as resp:
				pass

But i successfully update my watch list with `aiohttp.ClientSession(headers=headers)` , the cookies contain in variable `heades`. 

I compared the get request between them , problem may be that cookies convert ; to \073.

**Comment by kcorlidy** [comment]
It does not related to #2867 because i just change the cookies position then it succeed, also it response 200 so not #975

**Comment by blueyed** [comment]
Please check if cookies are just not being recognized (https://github.com/aio-libs/aiohttp/issues/2502#issuecomment-488864745).

**Comment by kcorlidy** [comment]
> Please check if cookies are just not being recognized ([#2502 (comment)](https://github.com/aio-libs/aiohttp/issues/2502#issuecomment-488864745)).

It works

**Comment by kcorlidy** [comment]
But i remain a question that i built a simple asyncio server to check the difference between aiohttp's request and requests's request. Then i got this. First one came from aiohttp.

	b'GET / HTTP/1.1\r\nConnection: \r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nHost: 127.0.0.1:8991\r\nUser-Agent: Python/3.7 aiohttp/3.4.4\r\nCookie: Cookie="_ga=GA1.2.808\\073fg_=weaeawe\\073"\r\n\r\n'
	GET / HTTP/1.1
	Connection:
	Accept: */*
	Accept-Encoding: gzip, deflate
	Host: 127.0.0.1:8991
	User-Agent: Python/3.7 aiohttp/3.4.4
	Cookie: Cookie="_ga=GA1.2.808\073fg_=weaeawe\073"


	b'GET / HTTP/1.1\r\nHost: 127.0.0.1:8991\r\nUser-Agent: python-requests/2.20.1\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nCookie: Cookie=_ga=GA1.2.808;fg_=weaeawe;\r\n\r\n'
	GET / HTTP/1.1
	Host: 127.0.0.1:8991
	User-Agent: python-requests/2.20.1
	Accept-Encoding: gzip, deflate
	Accept: */*
	Connection: keep-alive
	Cookie: Cookie=_ga=GA1.2.808;fg_=weaeawe;

**Comment by blueyed** [comment]
@kcorlidy 
> It works

Can you elaborate, please?

**Comment by kcorlidy** [comment]
I found ebay has changed its cookie format(may be this why your post works for me). And i can not trigger the error again. So i can not keep opening this question longer.


----------------The process that i tried to find the question----------------
 I ever tried to build a simple server to check the difference. First i chose `asyncio`, and i got the strange letter `\073` instead of `;` at the end of cookie(which like `b"user=abc\073user2=efg\073..."`), but nothing wrong when i put it into header. 
Today morning i try again by using tornado, but i did not get the same testing result(asyncio testing result). The header is totally correct, whether using cookie parameters or using header directly.
