### ISSUE TITLE
Example code from client quickstart not working

### ISSUE THREAD

**Issue by caliph007** [aio-libs/aiohttp#3376]
I hope I am not fully making a fool of myself. 
I am not able to get to work the few lines of the client [quickstart](https://docs.aiohttp.org/en/stable/client_quickstart.html) code:

```
import aiohttp
async with aiohttp.ClientSession() as session:
    async with session.get('http://httpbin.org/get') as resp:
        print(resp.status)
        print(await resp.text())
```

in Python 3.6. I get:

```
async with aiohttp.ClientSession() as session:
SyntaxError: invalid syntax
```

That I understand, because `async` became a reserved work in 3.7.
But the doc states as dependency `Python 3.5.3+`

in Python 3.7 I get:

```
async with aiohttp.ClientSession() as session:
SyntaxError: 'async with' outside async function
```

What am I doing wrong?
Thank you in advance.

**Comment by levkovskyi** [comment]
@caliph007 You can't use async code without loop.

Full example of code in Python 3.5-3.6:
```python
import asyncio
import aiohttp


async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get('http://httpbin.org/get') as resp:
            print(resp.status)
            print(await resp.text())

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Full example of code in Python 3.7
```python
import asyncio
import aiohttp


async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get('http://httpbin.org/get') as resp:
            print(resp.status)
            print(await resp.text())

asyncio.run(main())
```

**Comment by asvetlov** [comment]
`await` can be used inside `async def` function only.
This is not an aiohttp issue at all

**Comment by UtahDave** [comment]
I think this issue should be reopened.  The client quickstart https://docs.aiohttp.org/en/stable/client_quickstart.html  has examples that don't work, as @caliph007 noted above

**Comment by asvetlov** [comment]
Please feel free to open a Pull Request with docs update
