### ISSUE TITLE
[server] Feature request: Allow custom routing

### ISSUE THREAD

**Issue by jepotter1-archive** [aio-libs/aiohttp#3377]
## Long story short
I am creating a package based on `aiohttp` (https://github.com/jwinnie/maglev). This package implements custom routing behaviors based on middleware.

## Expected behaviour
I am able to disable the routing mechanism and jump straight to the `handle` function for all routes.

## Actual behaviour
I currently use a workaround which probably impacts performance:
```
app.add_routes([web.route("*", "/{tail:.*}", handle)])
```

**Comment by asvetlov** [comment]
Please consider low-level API: https://aiohttp.readthedocs.io/en/stable/web_lowlevel.html#
