### ISSUE TITLE
Docs rewriting

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#338]
I don't like the current state: we have mixin of autodocs and hand-written ones.

I guess to translate autodocs for `aiohttp.client` into separate `client_reference.rst` alike `web_reference.rst`.

@fafhrd91 do you have objections?

**Comment by fafhrd91** [comment]
no objections

**Comment by asvetlov** [comment]
Close the issue: `client_reference.rst` has been born, I'm working on improve the doc.
