### ISSUE TITLE
Disable body parameter in HTTPException constructor

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3385]
Now the exception can be created with either `body` or `text`.
It over complicates things in a light of removing inheritance from `web.Response`.

Let's deprecate `body` before changing the inheritance hierarchy.

**Comment by eirnym** [comment]
Does it mean, that I can't send back a binary here? I have a requirement to communicate using binary protocol and this change is breaking my ability to use exceptions

**Comment by kxepal** [comment]
Why do you need to use exceptions for such communication?

**Comment by eirnym** [comment]
I don't need to check very-special-values when return from the function and able to throw an HTTP error. 
Such exceptions in `aiohttp` and other frameworks (including other languages) are used interchangeable with `Response` objects to indicate an HTTP error in more clear way than using plain `Response` object. aiohttp is not an exception to this.

I agree, that not every http response require/accept a body at all.

**Comment by eirnym** [comment]
In my case I want to provide client with some additional contextual information where the error occurred.
