### ISSUE TITLE
How to get the IP of a web page visitor

### ISSUE THREAD

**Issue by LeeYuze** [aio-libs/aiohttp#3386]
My English is not good. I hope you can give the code directly. If someone visits the website I built with aiohttp, how can I get his IP address?
还有如何限制一个IP访问多次

**Comment by asvetlov** [comment]
[request.remote](http://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.BaseRequest.remote).
Please use https://github.com/aio-libs/aiohttp-remotes if an aiohttp application is deployed behind a reverse proxy.
