### ISSUE TITLE
Server Keep-alive and timeout redesign

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#339]
Right now we register keep-alive and timeout timers for each connection. And that is very expensive. Also both timers are in seconds. So instead we should use one global timer, seconds base. And manage keep-alive and timeout ourselfs. 

It might be useful to use same approach for client as well.

**Comment by fafhrd91** [comment]
I personally switched all my production systems to SO_KEEPALIVE

**Comment by fafhrd91** [comment]
basically we should register one timer and manage callbacks in `RequestHandlerFactory`

**Comment by asvetlov** [comment]
Pushing timer into `RequestHandlerFactory` sounds good.
Also I guess rename  `RequestHandlerFactory` to ``RequestManager` for avoiding clashes with `web-handler` term (with keeping old alias of course).

**Comment by fafhrd91** [comment]
-1 for `RequestManager`, misleading name.

**Comment by asvetlov** [comment]
Fixed by #702
