### ISSUE TITLE
Allow app state to be changed after joining

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#3397]
`DeprecationWarning: Changing state of started or joined application is deprecated` should be removed. 

Changing the state after an app has been join can be very useful, sometimes required.

For example [here](https://github.com/aio-libs/aiohttp-devtools/blob/master/aiohttp_devtools/runserver/serve.py#L63), in aiohttp-devtools we change the state on a running app. Since this requires the host to be known we can't set the state before this.

Also the check is never hard since
```py
app['foobar'] = 'different'
```
would be caught, but
```py
app['foobar']['x'] = different
```
would not.

So this warning (or future exception?) provies a false sense of security.

**Comment by samuelcolvin** [comment]
sorry, this is a duplicate of #1947

**Comment by samuelcolvin** [comment]
sorry, this is slightly different from #1947. I'm suggesting we don't freeze state at all.

**Comment by asvetlov** [comment]
I have a feeling that the clear app states separation allows getting of rid of a potential mess.
As a workaround you can store a *mutable* object in an application: `app['state'] = {}` as you've mentioned.

**Comment by samuelcolvin** [comment]
Ok, I strongly disagree with this, but I accept your point of view. 

I guess others agree with you since others haven't complained. Closing.
