### ISSUE TITLE
Rebuild aiohttp using cython 0.29

### ISSUE THREAD

**Issue by Callek** [aio-libs/aiohttp#3399]
I'm hitting the import warning issue described in

https://github.com/aio-libs/multidict/issues/304

I should note that I have not yet vetted that cython 0.29 fixes the issue, but I expect it does based on the research done there

I suspect bumping cython to 0.29 on the 3.4 branch and building a 3.4.5 would be low-risk and works for me, as would a sooner than later push of a 3.5 version.

**Comment by asvetlov** [comment]
The problem exists for 3-4 years.
I think it can wait for aiohttp 3.5

**Comment by asvetlov** [comment]
Please, don't rush.
Import warning is not a critical security bug, but just a very minor unhandiness.

**Comment by asvetlov** [comment]
Master already uses cython==0.29
Please wait for aiohtttp==3.5.0
