### ISSUE TITLE
Any way to declare type of path parameters ?

### ISSUE THREAD

**Issue by buxx** [aio-libs/aiohttp#3400]
## Story

When declare a path with regex, parameters can't be delcared with a type.

## Actual behaviour

All path parameters are string.

## Steps to reproduce

``` python
from aiohttp import web


async def handle(request):
    name = request.match_info.get('id', 42)
    text = str(type(name))
    return web.Response(text=text)

app = web.Application()
app.add_routes([web.get('/', handle),
                web.get(r'/{id:\d+}', handle)])

web.run_app(app)
```

``` bash
$ http :8080/42
HTTP/1.1 200 OK
Content-Length: 13
Content-Type: text/plain; charset=utf-8
Date: Tue, 20 Nov 2018 16:33:58 GMT
Server: Python/3.7 aiohttp/3.4.4

<class 'str'>
```
## My question/issue

It exist a way to declare the type of path parameters ? I would like obtain an `int` in this example.

**Comment by asvetlov** [comment]
`match_info` always contains strings. URL path is a string, path part is a string too.

If you need to cast a parameter to another type -- please do it (and handle conversion errors) explicitly.
Like 
```
str_id = request.match_info.get('id', '42')
try:
   int_id = int(str_id)
except ValueError:
   ...
```
Extra benefit is that explicit type casting works very well with mypy type checker.

**Comment by buxx** [comment]
Okay. Thank's for your time @asvetlov .
