### ISSUE TITLE
Readd aiohttp.{get,post,...} shortcuts

### ISSUE THREAD

**Issue by slice** [aio-libs/aiohttp#3427]
having these shortcuts in the `requests` library is very useful. they feel natural. having them in `aiohttp` would be even better. 😄

**Comment by asvetlov** [comment]
I not sure should we resurrect these functions or not.
Perhaps reasons for removal are gone today but I want to think carefully about it.

Maybe `aiohttp.request('GET', url)` can satify your needs?

**Comment by webknjaz** [comment]
I'm :-1: on this: `aiohttp` doesn't identify just an HTTP client, I'd rather not mix different namespaces into a spaghetti soup.

**Comment by asvetlov** [comment]
Looks like the decision is to reject the proposal, at least for aiohttp 4.x
