### ISSUE TITLE
Revert changes made when fixing #177

### ISSUE THREAD

**Issue by Hooksie** [aio-libs/aiohttp#343]
Hi all,

I recently noticed the behavior of the gaiohttp worker in gunicorn was behaving inconsistently with some of the others.  Specifically, it wasn't unquoting escape characters in PATH_INFO.  Looking back, I can see this behavior is intentional because of #177.

A change was made then to remove the call to `unquote` on PATH_INFO.  The justification was that the WSGI spec doesn't require it.  While the original PEP isn't entirely clear, if you check the `wsgiref` module, you'll see that PATH_INFO is indeed unquoted.  

I propose reverting the changes in 0813710 and returning to the previous behavior in order to follow the wsgi reference implementation.

I'll open a pull request for this in a few moments.  Are there any objections or thoughts on this change?

**Comment by asvetlov** [comment]
I've no idea about the issue.
@Hooksie may you provide a code which fails with the current behavior?
