### ISSUE TITLE
Remove Codecov from PR merge required list

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3441]
Codecov doesn't look stable now.
I've dropped the check from required-to-merge steps (but the app integration is still in place, the tool sends coverage reports when available).

We had #2997 issue before.
I love codecov tool and want to use it.
The check removal is temporary I hope.

We need somebody to investigate the problem.
@webknjaz could you take a look?

P.S.
The real problem is: I was continuously forced to use my administrative privileges to merge a PR when everything was green except a yellow codecov mark. Travis jobs restart didn't help, pushing a new merge from master branch did not help too.
Maybe it is our configuration problem again, codecov works just fine on my job for private source projects.

**Comment by webknjaz** [comment]
@asvetlov any examples of faulty behavior in PRs?

I've triggered reinstall of GitHub app for repos but I don't whether it'll help. I don't see CodeCov posting anything via Checks API though. The required check thing refers to old statuses API identifier, I don't know whether they still use it.

The other thing I see is that it looks like only Travis CI sends coverage data to the service: https://codecov.io/gh/aio-libs/aiohttp/commit/0b4530608fd8720f4b6becd938df05e4e849dc0f/build

AFAIR codecov is smart enough to know that there's also AppVeyor CI present here and normally it waits for all other CI statuses to be green before posting its own status.

**Comment by webknjaz** [comment]
Codecov settings state that integration is installed, but repos ain't added. I removed it and added back.
It looks like a bug on their side.

**Comment by webknjaz** [comment]
It's odd but the bot has just posted to https://github.com/aio-libs/aiohttp/pull/3442 and set a status there

**Comment by webknjaz** [comment]
But I'm still seeing:
```
GitHub Integration is installed. However, this repository is not enabled.

Click here to your installation listings
Find Repository access and add aiohttp to the list.
May take a couple minutes for our system to get notices of new projects added.
```

**Comment by asvetlov** [comment]
@webknjaz I'm curious where did you find this text?
Is it from github settings or CI logs?

**Comment by webknjaz** [comment]
It's at https://codecov.io/gh/aio-libs/aiohttp/settings and https://codecov.io/gh/aio-libs/multidict/settings which implies that something is still wrong.

**Comment by webknjaz** [comment]
Codecov settings are still looking odd. We should probably contact them.

**Comment by asvetlov** [comment]
Please do

**Comment by asvetlov** [comment]
Looks like fixed on codecov side.
In rare case the check fails, PR reopening can help
