### ISSUE TITLE
Route is not set to None when resolving fails

### ISSUE THREAD

**Issue by jnurmine** [aio-libs/aiohttp#345]
(Relevant version 0.15.3)

When resolving an URL fails, the route should become None, according to the documentation:

> The method (UrlDispatcher.resolve) never raises exception, but returns AbstractMatchInfo instance with None route ...

However, when UrlDispatcher.resolve returns _NotFoundMatchInfo(), the _route is not set to None. Instead, route = SystemRoute('').  Accessing the route property will give a valid SystemRoute instance instead of None.

**Comment by fafhrd91** [comment]
We need to update docs

**Comment by asvetlov** [comment]
Fixed
