### ISSUE TITLE
Beta release is failed on Python 3.7 bot for Linux

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3458]
Travis job is here: https://travis-ci.com/aio-libs/aiohttp/jobs/166684135
Job restart doesn't help
@webknjaz do you have any idea?

**Comment by yjqiang** [comment]
https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-425859109
Looks like the same reason?

**Comment by asvetlov** [comment]
But we have `dist: xenial` and `sudo: required` in travis config already: https://github.com/aio-libs/aiohttp/blob/master/.travis.yml#L6-L7

**Comment by webknjaz** [comment]
Hi, I'll check this today in the evening 🌃. Flying ✈ currently.

**Comment by webknjaz** [comment]
What @yjqiang is very close to our problem: Travis CI tries to grab Python 3.7 archive for Ubuntu 14.04 while it should be downloading one for Xenial. So something may be wrong with overriding global settings on the job level.
It doesn't seem to be related to @asvetlov's changes to `.travis.yml` either.

**Comment by webknjaz** [comment]
Should be fixed by 4bad3dc. @yjqiang's guess was correct after all.
