### ISSUE TITLE
Recommended way to run background tasks

### ISSUE THREAD

**Issue by arlyon** [aio-libs/aiohttp#3459]
https://github.com/aio-libs/aiohttp/blob/3a65252aa4c822056b408caa883fbdbf78311fa6/examples/background_tasks.py#L46

The loop property on the `Application` class is now deprecated (https://github.com/aio-libs/aiohttp/pull/3374), but [the docs](https://docs.aiohttp.org/en/latest/web_advanced.html#background-tasks) still reference adding background tasks to the loop via this property. What is the recommended way to do that now?

**Comment by kxepal** [comment]
[aiojobs](https://github.com/aio-libs/aiojobs) perfectly handles this problem.

**Comment by arlyon** [comment]
Great, should I update the docs to make mention of this, and remove the current (deprecated) method?

**Comment by kxepal** [comment]
I don't think that the current method should be removed since it's works out of the box, but it might be good to mention how aiojobs may help there and why it's better. @asvetlov, what do you think about that?

**Comment by asvetlov** [comment]
aiojobs is referenced at the begin of https://docs.aiohttp.org/en/stable/web_advanced.html

Deprecated `app.loop` usage should be removed from docs, sure.
The question is what is a replacement?
In Python 3.7+ there is a bare `asyncio.create_task()` but older pythons should use `loop.create_task()` with getting a loop instance by `asyncio.get_event_loop()`.
I prefer Python 3.7 approach personally but will we confuse people?

**Comment by hound672** [comment]
Excuse me, what about "DeprecationWarning: Changing state of started or joined application is deprecated
"
`    connection = await aio_pika.connect_robust(
        "amqp://user:pass@127.0.0.1/"
    )
    app['rabbit'] = connection
`
I want to use rabbit connector for declare unique queue for each connected client.
When I try to write in app object I gettings deprecation warining.

**Comment by asvetlov** [comment]
Doc is fixed by #3529
