### ISSUE TITLE
Deprecation warning in web_response.py with Python 3.7

### ISSUE THREAD

**Issue by dmajda** [aio-libs/aiohttp#3480]
## Long story short

When warnings are enabled, a warning like this is printed on importing `aiohttp.web` with Python 3.7:

```
/Users/dmajda/tmp/warnings/aiohttp/.venv/lib/python3.7/site-packages/aiohttp/web_response.py:33: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  BaseClass = collections.MutableMapping
```

This pullutes the output of our test suite (for which we have warnings enabled).

## Expected behaviour

No warning gets printed when importing `aiohttp.web`.

## Actual behaviour

A warning gets printed when importing `aiohttp.web`.

## Steps to reproduce

```console
$ python3 --version
Python 3.7.0
$ python3 -m venv .venv
[...]
$ . .venv/bin/activate
$ pip3 install aiohttp
[...]
$ python3 -Wall -c 'import aiohttp.web'
/Users/dmajda/tmp/warnings/aiohttp/.venv/lib/python3.7/site-packages/aiohttp/web_response.py:33: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  BaseClass = collections.MutableMapping
```

## Your environment

aiohttp version: 3.5.1
Python version: 3.7.0
OS: macOS Mojave

**Comment by webknjaz** [comment]
@dmajda feel free to send a PR :)

**Comment by dmajda** [comment]
Looks like @asvetlov was faster :-) Thanks for a quick fix and a fantastic library!
