### ISSUE TITLE
Don't replace empty BODY with empty dict on resp.json() call

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3482]
See https://github.com/aio-libs/aiohttp/pull/3362#issuecomment-451442605 note.

The change breaks backward compatibility but now the great chance to do it in aiohttp 4.0 :)

**Comment by socketpair** [comment]
Instead of empty dict it respond with None.

**Comment by socketpair** [comment]
Well, just curious... backward compatibility with what ?

**Comment by asvetlov** [comment]
Yes.
My point is: the PR should be a part of next aiohttp 4.0 but cannot be backported into 3.5 bugfix branch
