### ISSUE TITLE
raise exception to close connection without response (aka nginx 444)

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#3495]
### Feature request

(or perhaps this already possible, but I can't find where it's documented?)

Would be useful occasionally to be able to close a connection without a response, roughly equivalent to nginx's [444 pseudo response](http://nginx.org/en/docs/http/request_processing.html).

I guess best implemented as another exception similar to `HTTPInternalServerError` except closing the connection instead of return `500`. 

eg. `ServerCloseConnection`.

Is this possible cleanly and if so would it be useful?

**Comment by kxepal** [comment]
Today you can just raise `asyncio.CancelledError` from request handler to close connection without response. Do we need another one for this case? It named quite clean and it acts the same way as if client closes connection on their side before server returned any response.

**Comment by samuelcolvin** [comment]
Agree with both of you.

`CancelledError` should suffice, if someone wanted a different exception (eg. to tell error logging middleware that the server cancelled the response) they could just subclass `CancelledError`.
