### ISSUE TITLE
204 keep-alive client connections not handled properly

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiohttp#3507]
## Long story short

Using the https://api.weather.com endpoint, some APIs return 204s with Connection: keep-alive, which immediately closes the keep-alive after the response.  What we've found is that aiohttp will incorrectly use the connection again from the pool and trigger either a `ClientOSError` or `ServerDisconnectedError` depending on if SSL is used or not.

## Expected behaviour

no error when re-using the connection pool after a 204

## Steps to reproduce

```python
#!/usr/bin/env python3
from aiohttp import web
import threading
import asyncio
import time
import aiohttp
import ssl
import traceback

SSL = False


if SSL:
    URL = 'https://127.0.0.1:8080/'
else:
    URL = 'http://127.0.0.1:8080/'


async def web_index(request: web.Request) -> web.Response:
    response = web.Response(status=204, headers={"Connection": "Keep-Alive"})
    # response.enable_compression(True)
    response.force_close()
    return response


def server():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)

    app = web.Application()
    app.add_routes([web.get('/', web_index)])

    ssl_context = None
    if SSL:
        ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
        ssl_context.load_cert_chain('/Users/amohr/python-debug/yourpemfile.pem', '/Users/amohr/python-debug/yourpemfile.pem')

    web.run_app(app, port=8080, handle_signals=False, ssl_context=ssl_context)


async def amain():
    async with aiohttp.ClientSession() as session:
        while True:
            try:
                async with session.get(URL, verify_ssl=False) as response:
                    print('.', end='.', flush=True)
            except:
                traceback.print_exc()
                await asyncio.sleep(1)


def main():
    thread = threading.Thread(target=server)
    thread.start()

    time.sleep(2)

    asyncio.get_event_loop().run_until_complete(amain())


if __name__ == '__main__':
    main()
```

## Your environment

aiohttp 3.5.2 and 4.0.0a0
OSX 10.14.2

**Comment by thehesiod** [comment]
hmm, this may be as-designed, I just tried with requests as the client and it happens, but way less often:

```python
def rmain():
    with requests.session() as session:
        while True:
            try:
                session.get(URL, verify=False)
                print('.', end='.', flush=True)
            except:
                traceback.print_exc()
                time.sleep(1)
```

this occasionally yields `requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))`

**Comment by kxepal** [comment]
Why do you have this line: `    response.force_close()`? This actually instructs server to not use keep-alive and close connection. At the same time client receives header with keep-alive instruction and doesn't closes connection assuming it could be reused. Suddenly, it couldn't. Removing that line solves the issue.

UPD. Sorry, I miss read the description thinking that this is your server.

**Comment by kxepal** [comment]
I think there is nothing much left to do since the only reliable way to detect that connection is broken is to interact with it. However, this server looks as broken one: it declares keep-alive, but it explicitly doesn't support it.

Workaround here is to disable keep-alive on client side as well via `aiohttp.ClientSession(connector=aiohttp.TCPConnector(force_close=True))`. 

Does it makes sense to redraw connection from a pool if drawed one occurs broken? That sounds reasonable in general, but no for case you described.

**Comment by thehesiod** [comment]
@kxepal so there is at least one client bug, in that if you call `response.close()` it will attempt re-using the connection and generate the disconnect error.

UPDATE: we'd prefer this workflow because we make a ton of calls (hundreds of thousands) and only some of then will result in 204s (hundreds), so we don't want to throw away the keep-alive for all of them.

**Comment by thehesiod** [comment]
ok, doing some research, it seems like during the request:
```
  File "/Users/amohr/Library/Preferences/PyCharm2018.3/scratches/scratch.py", line 48, in amain
    async with session.get(URL, verify_ssl=False) as response:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 995, in __aenter__
    self._resp = await self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 487, in _request
    await resp.start(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 860, in start
    payload.on_eof(self._response_eof)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/streams.py", line 490, in on_eof
    callback()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 894, in _response_eof
    self._connection.release()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 178, in release
    should_close=self._protocol.should_close)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 621, in _release
    self._release_acquired(key, protocol)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 613, in _release_acquired
    self._release_waiter()
```

The connector for a 204 gets put back in the pool before the `get` even returns, so there's no way for the caller to inform aiohttp that the connection should be removed.  I think the connector shouldn't be released until the `__aexit__` to give the caller a chance to let aiohttp know what to do with the connector.

**Comment by thehesiod** [comment]
hah, seems like I had this issue before: https://github.com/aio-libs/aiohttp/issues/3507  at least now I think it would be good if we could close the connector when we know the server is going to disconnect us.

**Comment by Dreamsorcerer** [comment]
@thehesiod Can you retest this? We have some retry logic now, so if the connection is closed by the server just after the connection is reused then it should retry with a new connection (assuming it's a safe method such as GET).

> I think the connector shouldn't be released until the `__aexit__` to give the caller a chance to let aiohttp know what to do with the connector.

This would be a breaking change, and I think there's a fair amount of code that seems to depend on this behaviour (a lot of code that fails to use `async with` for example).

> I think it would be good if we could close the connector when we know the server is going to disconnect us.

Aiohttp doesn't know the server is going to disconnect. If you know that ahead of time, then you can use `TCPConnector(force_close=True)`.
