### ISSUE TITLE
Get rid of weakref-based resource cleanup in aiohttp.client and aiohttp.connector

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#352]
I want to drop all weakref-based garbage and switch to using `__del__`.

Yes, I bring that weakref shit into aiohttp.

So please let me explain why it **was** needed and why we don't need weakrefs any more.
- In Python 3.3 objects with `__del__` was not able to be garbage collected.
- Python 3.4.0 has a crashing bug: http://bugs.python.org/issue21435

Now the crash is fixed in Python 3.4.1+ (I pretty sure nobody use 3.4.0 now). 
Python 3.3 is very rare, users still may close all resources explicitly.

My proposal is:
- add `__del__` everywhere we use weakrefs with checking for python version, like:
  
  ```
  if PY_34:
      def __del__(self):
         ...
  ```
- in `__del__` do check for unclosed resources, raise `ResourceWarning` if needed and close everything.

The proposal is pretty close to current `asyncio` behavior.

If nobody object I'll prepare a Pull Request.

**Comment by fafhrd91** [comment]
+1

**Comment by kxepal** [comment]
Interesting. +1

**Comment by asvetlov** [comment]
Thanks, guys.

**Comment by ludovic-gasc** [comment]
+1

A yocto remark: as a library, I understand that you want to run on most python versions, nevertheless I'm pretty sure that python 3.3 isn't used on production: the latest stable versions on main Linux distributions are 3.4. On the previous stable versions, like debian wheezy, it was 3.2.
On Windows, no problems to install the version you want.
For this particular case, it doesn't seem to be a big effort, but if one day you need a big effort to maintain python 3.3 compatibility, it's your personal time, but as least to me, it will acceptable to drop python 3.3 compatibility.

**Comment by julien-duponchelle** [comment]
We have the same discussion at GNS3

The only potential issue we found is Fedora 20 shipped with Python 3.3:
https://apps.fedoraproject.org/packages/python3

But Fedora 21 and Fedora 22 use Python 3.4

**Comment by asvetlov** [comment]
Fixed in #354
