### ISSUE TITLE
Raise an Exception when route is not resolved

### ISSUE THREAD

**Issue by mikaeilorfanian** [aio-libs/aiohttp#3524]
## Long story short

When a requested route is not resolved, the framework sets `request.match_info.route` to an  instance of `SystemRoute`. This means I have to check this in a middleware before I setup db connections, etc. 

## Expected behaviour

Why doesn't the framework raise some kind of exception when the route is not resolved?

## Actual behaviour

I have to check every request to make sure the route was matched.
My middlewares assume that `request.match_info[<sth>]` won't throw a KeyError if the route is not even matched. When I inspect `request.match_info.route` I get `<SystemRoute 404: Not Found>`.
Is there a convenient way of not having to deal with this manually?
My experience with other frameworks is that the framework return 404 by default and if I have to do some custom error handling (especially in the case of the route being wrong) then I'd have to manually intercept what the framework does.

**Comment by asvetlov** [comment]
You can check `request.match_info.http_exception is not None` or run `await handler(request)` and catch a error:
```
async def middleware(request, handler):
    if request.match_into.http_exception is not None:
         return await handle_error(request.match_into.http_exception)
    try:
         return await hander(request)
    except HTTPException as exc:
         return await handle_error(exc)
```

**Comment by mikaeilorfanian** [comment]
Thanks for the info. My main question here is why does `request.match_info` raise a `KeyError` if the route was not even matched.

**Comment by asvetlov** [comment]
Is your question: Why `request.match_info['some_arg']` raises `KeyError` for 404 route when called from a middleware?

**Comment by mikaeilorfanian** [comment]
Yes, the last part (from a middleware) is just what happens in my case. My concern is that this behavior (`KeyError` is raised when there's a 404 route) caught me by surprise. I assumed that when there's a 404 route, some specific exception - as opposed to `KeyError` which is also raised when route has been matched- would be raised.

**Comment by asvetlov** [comment]
For the note: 404 is technically *a response*, middlewares and signals are able to process it as any regular answer.
That's why a system route is returned instead of just raising an exception
