### ISSUE TITLE
Add limit for connections to the same host:port pair to BaseConnector

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#353]
Now `aiohttp.Connector` creates new connection if there are no free one for specific host:port pair. Strictly speaking `key` is a `(host, port, ssl)` tuple but it doesn't matter.

We can get unlimited connections to the same site if the site responds slowly but client requests very quickly.

Browsers has a limit for number of parallel connections to unique endpoint. AFAIK the number is in range 10-15.

I propose to add `limit` parameter to `connector` constructor (`None` by default to keep backward compatibility) and wait for free connection returned to pool if limit was exhausted.

**Comment by fafhrd91** [comment]
+1

**Comment by kxepal** [comment]
Good idea. If the limit will be hitted, coroutine that made a yield from aiohttp.request (basically) call will just get blocked until free slot will be available?

**Comment by asvetlov** [comment]
@kxepal yes, exactly

**Comment by fafhrd91** [comment]
Low/high water marks? Or too complex?

**Comment by kxepal** [comment]
@asvetlov +1. That's almost what I just had done with semaphore, loop and done callback (:

Btw, what you think about special flag for the request in order to overcome that limit? The case: you have a stream (one long polling request) and batch of readers that process that stream. You want to limit amount the readers, but you don't want to loose ability to repeat a request to the streaming resource in case if connection with it get broken. 

Or for such case should I use special connector instance for readers in order to limit them?

**Comment by asvetlov** [comment]
another side-effect: connector should count _used_ connections, not only _released_.
Thus `connector.close()` should close all underlying transports, not only returned to free pool.

I think it's fine for `ClientSession` API -- session should close everything which it opens.
For bare `aiohttp.request()` without `connector` parameter we unfortunately have to not close session (https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L352), it should be `session.close(keep_running=True)` or something like that.

**Comment by asvetlov** [comment]
@fafhrd91 what behavior do you want speaking about watermarks?

Relax `keepalive_timeout` for connector? 
Connections may be closed quickly if the number of connections is high and slowly if not?

It's really looks over complicated, at least for now.

**Comment by asvetlov** [comment]
@kxepal for your case the native scenario is using two `ClientSession` objects (or two connector instances if you are old-style guy).

Using two connection pools is the most obvious way to split long-running connections and quick requests to the same server, isn't it?

**Comment by kxepal** [comment]
@asvetlov It is, but from the first sight. On second one, that strategy means, that I have somehow pass two sessions to my function (what makes it API a bit awkward), or expose knowledge about aiohttp internals inside by explicit creation second session inside that function. Things starts to be more complicated if I start (and I have) to work not with aiohttp objects, but with the proxies behind which there could be aiohttp, aiopg, aiomysql or whatever.

Thought, may be when the morning come all the problems will fade away with some better idea of how to manage two sessions for my case (:

Anyway that are just a details. +1 for your proposal.

**Comment by fafhrd91** [comment]
@asvetlov i'm about number of connections, but i agree about overcomplication

**Comment by asvetlov** [comment]
@kxepal you have to add a _weight_ to call for connection creation (say, number between 0.0 and 1.0).
Splitting to two groups maybe is not enough.

I think weighted connections is **too** complicated for library users.

**Comment by asvetlov** [comment]
@fafhrd91 let's just add high-watermark (_limit_ parameter) and see do we need low-water later.

You may set low limit and high timeout -- isn't this satisfies you needs?

**Comment by asvetlov** [comment]
See PR #358 for issue implementation,

**Comment by asvetlov** [comment]
Done
