### ISSUE TITLE
Disable github actions

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3537]
Now any PR fails on manylinux1 github action check.
It is very annoying.
@webknjaz can we temporarily disable the feature until it will work?

**Comment by webknjaz** [comment]
I made container run but it fails for some reason: https://github.com/aio-libs/aiohttp/runs/52842050

So I've temporarily added a filter to prevent this action from running on branches except for my experiments, now it looks like https://github.com/aio-libs/aiohttp/runs/52845231 and produces canceled neutral status. It's not red anymore.

Closing #3566 therefore.

**Comment by asvetlov** [comment]
Thanks, @webknjaz 
Feel free to experiment but please don't break our main workflow until your work is not done.

**Comment by webknjaz** [comment]
That manylinux action should only be triggered for branches containing `webknjaz` substring so it should be good enough for experimenting and after it's green I'll merge that back to master
