### ISSUE TITLE
Replace tmpdir fixture with tmp_path in tests

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3551]
I always stumble on `py.path` methods.
A new `pytest` supports `tmp_path` fixture https://docs.pytest.org/en/latest/tmpdir.html#the-tmp-path-factory-fixture to work with `pathlib.Path`.

The issue is easy and waits for a champion.

**Comment by gyermolenko** [comment]
I found it relevant to current issue, adding for context: ref https://github.com/pytest-dev/pytest/issues/4680  and two other `tmp_path` defects were fixed in pytest 4.2.
And pytest 4.2 has just beed released.
