### ISSUE TITLE
Inconsistent behavior when merging params

### ISSUE THREAD

**Issue by brunsgaard** [aio-libs/aiohttp#356]
This is best illustrated by the code snippet below, which will print `http://localhost:5000/test?key1=value1`, but the server log tells me that the params was actually merged in the request.

I am not sure what the decided behavior should be, when the url contains params and the param keyword argument also is given. But at least the `url` variable in the response object should be consistent with the actual request.

```
127.0.0.1 - - [10/May/2015 23:39:13] "GET /test?key1=value1&key2=value2 HTTP/1.1" 404
```

``` python
import asyncio
import aiohttp

@asyncio.coroutine
def test_para():
    url_with_params = 'http://localhost:5000/test?key1=value1'
    more_params = {'key2': 'value2'}
    req = aiohttp.request('get', url_with_params, params=more_params)
    resp = yield from req
    print(resp.url)

loop = asyncio.get_event_loop()
loop.run_until_complete(test_para())
loop.close()
```

**Comment by asvetlov** [comment]
Good point! What is precedence order for query-string in url and `params`? 
I have no intuitive answer.
Should we forbid to mix url with query string and `params`?

**Comment by kxepal** [comment]
I think we need extract all possible information from url (query params, basic auth credentials, path, params) and use it as the base one for further update_\* calls.

**Comment by asvetlov** [comment]
@kxepal  `params` _may_ be merged, but _auth_ definitely not -- it overlaps data.

`ClientSession` has explicit check for passing `auth` together with `Authorization` header -- it raises `ValueError` in the case.

Maybe we need same for `params`? 

Path is not merged as well as other URL parts. 
`compress`, `chunked` etc. should be not merged but raise explicit error in case of conflict with `headers`.

**Comment by kxepal** [comment]
@asvetlov sure, if auth was specified multiple times (via url, headers, `.request()` params) that's a conflict and exception is what could be produced here.

But I was about extracting BasicAuth credentials from URL (`http://foo:bar@localhost`) as well as what we extract it from headers. I also was wrongly assumed that aiohttp doesn't extract it, but so far it seems we just not checking for conflicts if credentials were specified both inline and via headers/auth:

```
    def test_basic_auth_conflicts(self):
        req = ClientRequest('get', 'http://nkim:1234@python.org',
                            headers={'AUTHORIZATION': 'Basic bmtpbToxMjM0NQ=='})
        self.assertIn('AUTHORIZATION', req.headers)
        self.assertEqual('Basic bmtpbToxMjM0', req.headers['AUTHORIZATION'])

        req = ClientRequest(
            'get', 'http://nkim:1234@python.org',
            auth=aiohttp.helpers.BasicAuth('nkim', '12345'))
        self.assertIn('AUTHORIZATION', req.headers)
        self.assertEqual('Basic bmtpbToxMjM0NQ==', req.headers['AUTHORIZATION'])
```

If the other things are not being merged in case of conflict, then params shouldn't be either - that will be at least consistent behaviour.

**Comment by ovnicraft** [comment]
This issue is old, there is any update about it ?

**Comment by asvetlov** [comment]
I believe it should be fixed already by switching to `yarl` library usage.
Isn't it?

**Comment by ovnicraft** [comment]
IMO this must be closed until get feedback from reporter.

**Comment by fafhrd91** [comment]
agree.
