### ISSUE TITLE
Switch http_parser to llhttp

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#3561]
Nodejs decide to move from their hard-coded C parser to this one.

https://github.com/nodejs/http-parser/pull/285#issuecomment-456025694

*Upd:* 
proposed parser is https://llhttp.org

**Comment by samuelcolvin** [comment]
Seems too good to be true, but must be worth trying.

Might be worth putting the link in the body of the issue so it's rendered as a link.

**Comment by socketpair** [comment]
https://llhttp.org

**Comment by asvetlov** [comment]
It worth to try.
API seems the same but I expect complications of our build process.
Don't have any personal estimation of the issue:
1. It *would be nice to have* but not urgent, existing parser *just works*
2. I have a long list of higher priority items in my todo list

**Comment by socketpair** [comment]
Interesting, suricata decide to write their own HTTP-parser on Rust :) https://redmine.openinfosecfoundation.org/issues/2787#change-10814

**Comment by derlih** [comment]
I found a problem with this port to llhttp: there is no API in llhttp that parses url.
These functions are needed by `cdef class HttpRequestParser(HttpParser)`
Does anyone have an idea how to workaround it?

[my llhttp branch](https://github.com/derlih/aiohttp/tree/llhttp)

**Comment by asvetlov** [comment]
They are not required I guess, `yarl.URL` can be constructed directly as we do for pure-Python parser.

**Comment by socketpair** [comment]
https://github.com/pallas/pyllhttp ?

**Comment by derlih** [comment]
@socketpair 
I saw this project, but

> This project is a toy, started to reacquaint myself with Python c-api modules.

**Comment by socketpair** [comment]
@derlih That's why I removed the link :) before your comment.

**Comment by socketpair** [comment]
https://github.com/pallas/pyllhttp
