### ISSUE TITLE
Time to make new style middlewares default

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3569]
@samuelcolvin you was the author of `@middleware` syntax (thank you so much for it by the way).

Now we are in the middle of a migration to aiohttp 4.0.

We can drop old-styled middlewares entirely. 
`@middleware` decorator should exist until 5.0 but its functionality must be *default* I believe.

Would you prepare the PR?

**Comment by samuelcolvin** [comment]
Will do.

**Comment by asvetlov** [comment]
Fixed by #3710
