### ISSUE TITLE
Minimal deviation from quick-start example fails

### ISSUE THREAD

**Issue by aparamon** [aio-libs/aiohttp#3592]
## Long story short

Minimal client example @https://aiohttp.readthedocs.io/en/stable/#getting-started works fine for me. However a minimal deviation printing only status code fails.

## Steps to reproduce

````py
import aiohttp
import asyncio

async def fetch(session, url):
    async with session.get(url) as response:
        return response.status

async def main():
    async with aiohttp.ClientSession() as session:
        status = await fetch(session, 'http://python.org')
        print(status)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
````
````pytb
200
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f104a8ea6d8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2605)
````

## Your environment

Reproducible both on Debian GNU/Linux and Windows, Python 3.7, aiohttp 3.5.4.

**Comment by samuelcolvin** [comment]
Works fine for me, this is nothing to do with adding the `print()`.

Looking at the traceback it appears to be something to do with SSL. Perhaps you have some kind of proxy in place or an issue with your certificates?

**Comment by samuelcolvin** [comment]
This seems to be a duplicate of #3535

**Comment by aparamon** [comment]
@samuelcolvin I doubt the problem is in my set-up: the original minimal example using `await response.text()` works fine for me.
What additional info might be helpful to debug?

**Comment by aparamon** [comment]
Ah indeed, mine is a duplicate.
Thanks for pointing it!
