### ISSUE TITLE
Cannot send GET request with url-encode

### ISSUE THREAD

**Issue by ZeroTworu** [aio-libs/aiohttp#3601]
Request string before 359 client.py
![default](https://user-images.githubusercontent.com/17995677/52434449-26736780-2b31-11e9-8d10-01c140ea0c84.png)
And after 369 i see
![default](https://user-images.githubusercontent.com/17995677/52434526-5ae72380-2b31-11e9-952f-ed1cf26e73ae.png)
How this work?
inb4: i read docs, and see sources

**Comment by asvetlov** [comment]
RTFM again please: http://docs.aiohttp.org/en/stable/client_quickstart.html#passing-parameters-in-urls

**Comment by ZeroTworu** [comment]
I think it is better to write here than to open a new issue.

Python 3.6, aiohttp 3.5.4, requests 2.21.0 I got a problem
I have a website which should be parsed, if I throw GET request through
requests.Session() I get content and can process it.
If I throw GET through aiohttp.ClientSession(), the system detected me like some bot after moment.
 
I used different cookies and user agents, nothing changed. The question: how is aiohttp different from another one? How can I solve it?
Code for aiohttp:
```
    def __init__(self):
        self.session = aiohttp.ClientSession(requote_redirect_url=False)
```
```

    async def get(self, url, **kwargs):
        res = await self.session.get(url, **kwargs)
        return res
```

```
url = URL('domain.com/checkcaptcha?%s' %
                          urlencode({'key': key, 'retpath': ret_path, 'rep': user_answer['captchaSolve']}), encoded=True)
 res = await self.get(url)
```
