### ISSUE TITLE
Access log and multiple headers of the same name

### ISSUE THREAD

**Issue by haverins** [aio-libs/aiohttp#3618]
## Long story short

I have aiohttp behind haproxy and I'd like to see clients IP in aiohttp access log. Haproxy can forward client IP in (X-Client) http header and I can log that. However, there is edge case where request already has X-Client header. Aiohttp logs 1st occurrence of X-Client and I'd like to log last occurrence.

**Comment by hellysmile** [comment]
Hey You can try https://aiohttp.readthedocs.io/en/stable/logging.html with custom `aiohttp.helpers.AccessLogger`

**Comment by samuelcolvin** [comment]
Are you really sure haproxy doesn't override the `X-Client` header? That's what most reverse proxies do when they encounter an existing "protected" header.

**Comment by haverins** [comment]
@hellysmile What do you mean? I'm already supplying custom log format but `%{FOO}i` allows me to log only 1st occurrence of the header.

@samuelcolvin From haproxy configuration manual:

> Since HAProxy works in reverse-proxy mode, the servers see its IP address as
their client address. This is sometimes annoying when the client's IP address
is expected in server logs. To solve this problem, the well-known HTTP header
"X-Forwarded-For" may be added by HAProxy to all requests sent to the server.
This header contains a value representing the client's IP address. Since this
header is always appended at the end of the existing header list, the server
must be configured to always use the last occurrence of this header only.

It might be possible to overwrite headers with haproxy (it can do lot of things) but that's a bit hacky solution.

**Comment by samuelcolvin** [comment]
@hellysmile, means write your own `AccessLogger` rather than using the default one, as documented at that link.

Example [here](https://github.com/aio-libs/aiohttp-devtools/blob/master/aiohttp_devtools/runserver/log_handlers.py#L11) but that's much more complicated than yours needs to be.

**Comment by haverins** [comment]
@samuelcolvin I see. Seems easy enough. Thanks.
