### ISSUE TITLE
Allow creating and connecting to named pipes in windows

### ISSUE THREAD

**Issue by hackrush01** [aio-libs/aiohttp#3629]
## Long story short

We need to use named pipes in windows in our project([lbry](https://github.com/lbryio/lbry))

## Expected behaviour

aiohttp should provide the functionality of creating and connecting to named pipes in windows

## Actual behaviour

No such functionality present

## Additional Comments

I have already "almost" implemented it. I have opened this issue for discussion regarding the feasibility and potential issues.

**Comment by asvetlov** [comment]
Would you work on pull request?

**Comment by hackrush01** [comment]
Yes, I should have one by the night.

**Comment by asvetlov** [comment]
Fixed by #3632
