### ISSUE TITLE
TypeError: Can not serialize value type: <class 'int'>

### ISSUE THREAD

**Issue by hfldqwe** [aio-libs/aiohttp#3652]
## Long story short

When using a post request, I want to upload both file and form data. Now I have a problem. When I am working at the same time, there will be an error that the integer cannot be serialized, and I can't find the cause of the problem. Although the integer is replaced by a string, this problem is solved. I suspect that the code in the process of encoding or converting data data is not very robust.

## Expected behaviour

```
Traceback (most recent call last):
  File "/home/py/.virtualenv/youka/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 482, in update_body_from_data
    body = payload.PAYLOAD_REGISTRY.get(body, disposition=None)
  File "/home/py/.virtualenv/youka/lib/python3.7/site-packages/aiohttp/payload.py", line 106, in get
    raise LookupError()
aiohttp.payload.LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/py/.virtualenv/youka/lib/python3.7/site-packages/aiohttp/formdata.py", line 126, in _gen_form_data
    value, headers=headers, encoding=self._charset)
  File "/home/py/.virtualenv/youka/lib/python3.7/site-packages/aiohttp/payload.py", line 63, in get_payload
    return PAYLOAD_REGISTRY.get(data, *args, **kwargs)
  File "/home/py/.virtualenv/youka/lib/python3.7/site-packages/aiohttp/payload.py", line 106, in get
    raise LookupError()
aiohttp.payload.LookupError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/py/project/chd_youka/async_spider/chaojiying.py", line 65, in <module>
    loop.run_until_complete(main())                 #1902 验证码类型  官方网站>>价格体系 3.4+版 print 后要加()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/home/py/project/chd_youka/async_spider/chaojiying.py", line 54, in main
    code = await chaojiying.PostPic(im, 4004,session)
  File "/home/py/project/chd_youka/async_spider/chaojiying.py", line 38, in PostPic
    async with session.post(url='http://upload.chaojiying.net/Upload/Processing.php', data=params, headers=self.headers) as response:
  File "/home/py/.virtualenv/youka/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/home/py/.virtualenv/youka/lib/python3.7/site-packages/aiohttp/client.py", line 466, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/home/py/.virtualenv/youka/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 294, in __init__
    self.update_body_from_data(data)
  File "/home/py/.virtualenv/youka/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 484, in update_body_from_data
    body = FormData(body)()
  File "/home/py/.virtualenv/youka/lib/python3.7/site-packages/aiohttp/formdata.py", line 148, in __call__
    return self._gen_form_data()
  File "/home/py/.virtualenv/youka/lib/python3.7/site-packages/aiohttp/formdata.py", line 131, in _gen_form_data
    type(value), headers, value)) from exc
TypeError: Can not serialize value type: <class 'int'>
 headers: {}
 value: 4004
```

## Actual behaviour

When the form data contains both file objects (perhaps binary objects) and integers

```
    async def PostPic(self, im, codetype, session):
        """
        im: Picture byte
        codetype: http://www.chaojiying.com/price.html
        """
        params = {
            'codetype': codetype,
        }
        params.update(self.base_params)
        files = {'userfile':im}
        params.update(files)
        print(params)
        async with session.post(url='http://upload.chaojiying.net/Upload/Processing.php', data=params, headers=self.headers) as response:
            return await response.text()
```
![image](https://user-images.githubusercontent.com/35399781/54467796-6b3e8e00-47c2-11e9-9ce1-e4292338b472.png)

## Your environment

Linux version 4.4.0-116-generic (buildd@lgw01-amd64-021) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018

Python3.7

aiohttp3.5.4

**Comment by hfldqwe** [comment]
@aio-libs-bot 

This is not a header, but just a form. I tried to upload a form with no integers and strings (no files) and upload the files separately. The results are all workable, but there is a problem with uploading file objects along with forms that contain integers. I think this is a hidden bug and I hope to get a more detailed reply.

**Comment by samuelcolvin** [comment]
I can reproduce this error with a simple example:

```py
import aiohttp
import asyncio


async def main():
    data = {
        'a': 1,
        'b': b'a'
    }
    async with aiohttp.ClientSession() as session:
        async with session.post('https://httpbin.org/post', data=data) as response:
            print(response.status)
            c = await response.text()
    print(c)


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

raises:

```
Traceback (most recent call last):
  File "/home/samuel/code/aiohttp/env/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 482, in update_body_from_data
    body = payload.PAYLOAD_REGISTRY.get(body, disposition=None)
  File "/home/samuel/code/aiohttp/env/lib/python3.7/site-packages/aiohttp/payload.py", line 106, in get
    raise LookupError()
aiohttp.payload.LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samuel/code/aiohttp/env/lib/python3.7/site-packages/aiohttp/formdata.py", line 126, in _gen_form_data
    value, headers=headers, encoding=self._charset)
  File "/home/samuel/code/aiohttp/env/lib/python3.7/site-packages/aiohttp/payload.py", line 63, in get_payload
    return PAYLOAD_REGISTRY.get(data, *args, **kwargs)
  File "/home/samuel/code/aiohttp/env/lib/python3.7/site-packages/aiohttp/payload.py", line 106, in get
    raise LookupError()
aiohttp.payload.LookupError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test.py", line 11, in main
    async with session.post('https://httpbin.org/post', data=data) as response:
  File "/home/samuel/code/aiohttp/env/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/home/samuel/code/aiohttp/env/lib/python3.7/site-packages/aiohttp/client.py", line 466, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/home/samuel/code/aiohttp/env/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 294, in __init__
    self.update_body_from_data(data)
  File "/home/samuel/code/aiohttp/env/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 484, in update_body_from_data
    body = FormData(body)()
  File "/home/samuel/code/aiohttp/env/lib/python3.7/site-packages/aiohttp/formdata.py", line 148, in __call__
    return self._gen_form_data()
  File "/home/samuel/code/aiohttp/env/lib/python3.7/site-packages/aiohttp/formdata.py", line 131, in _gen_form_data
    type(value), headers, value)) from exc
TypeError: Can not serialize value type: <class 'int'>
 headers: {}
 value: 1
```

**Comment by samuelcolvin** [comment]
Weirdly while the `1` definitely refers to the value of `'a'`, the error does not occur if `'b'` (and it's value) is removed

**Comment by hfldqwe** [comment]
This is also the place that makes me wonder.

**Comment by hfldqwe** [comment]
Why is there no one to answer this question?

**Comment by hfldqwe** [comment]
Why is there no one to answer this question?

**Comment by webknjaz** [comment]
Because this project is maintained by unpaid volunteers who still need to go to work and earn money, and spend quality time with their families, and even just rest.
We don't have any SLA on responding but we follow best effort policy. We reply if and when we can. And it also depends on whether a specific person knows the referred part of the code base well or not.

**Comment by newmanifold** [comment]
@webknjaz 
It seems that numeric types are not added to PAYLOAD_REGISTERY, 
Can you tell me if support for numeric type is intended in FormData? If not then this issue doesn't seem to be a bug but a feature request.

**Comment by newmanifold** [comment]
@webknjaz
It seems that numeric types are not added to PAYLOAD_REGISTERY,
Can you please tell me if support for numeric type is intended in FormData? If not then this issue doesn't seem to be a bug but a feature request.

**Comment by kxepal** [comment]
This is not a first issue about support numerics serialization for FormData.
https://github.com/aio-libs/aiohttp/issues/920
It's intendent behaviour - FormData tries to know as least as it's possible about data serialization. `int` is just a easy case which is easy to handle. Then will come other types and here we'll face real issues. Like `bool` one - it's `int` subtype, but the ways of it serialization are numerious.

**Comment by newmanifold** [comment]
@kxepal 
sorry but from #920 it seems raising TypeError for numeric types is intended right? since as you've mentioned serialization issue for bool type, 
However i am just wondering can't we just follow what aiohttp does in www-form-urlencoded for serialization of numeric types ?

**Comment by kxepal** [comment]
@newmanifold 
Yes. Multipart and urlencoded FormData shares the same logic here.

**Comment by newmanifold** [comment]
@kxepal
please correct me if i am wrong, for urlencoded it seems urllib.urlparse.urlencode is used after determining correct encoding and checking if any param is instanceof io.IOBase in that case multipart encoding is used right?

If this is true then urlencode seems to use str on the type if type not bytes or string right?
So if my understanding above is correct then we can just use str on numeric types. so that multipart and urlencoded FormData are consistent. what do you think?

**Comment by webknjaz** [comment]
FTR. Shorter reproducer is:
```python-traceback
$ ipython
Python 3.7.1 (default, Jan 28 2019, 08:25:13) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from aiohttp.client_reqrep import FormData                                                                                                                                             

In [2]: FormData({'a': 1, 'b': b'a'})()                                                                                                                                                        
---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
~/src/github/aio-libs/aiohttp/aiohttp/formdata.py in _gen_form_data(self)
    125                     part = payload.get_payload(
--> 126                         value, headers=headers, encoding=self._charset)
    127             except Exception as exc:

~/src/github/aio-libs/aiohttp/aiohttp/payload.py in get_payload(data, *args, **kwargs)
     62 def get_payload(data: Any, *args: Any, **kwargs: Any) -> 'Payload':
---> 63     return PAYLOAD_REGISTRY.get(data, *args, **kwargs)
     64 

~/src/github/aio-libs/aiohttp/aiohttp/payload.py in get(self, data, _CHAIN, *args, **kwargs)
    105 
--> 106         raise LookupError()
    107 

LookupError: 

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-2-7ef1f2f80edc> in <module>
----> 1 FormData({'a': 1, 'b': b'a'})()

~/src/github/aio-libs/aiohttp/aiohttp/formdata.py in __call__(self)
    146     def __call__(self) -> Payload:
    147         if self._is_multipart:
--> 148             return self._gen_form_data()
    149         else:
    150             return self._gen_form_urlencoded()

~/src/github/aio-libs/aiohttp/aiohttp/formdata.py in _gen_form_data(self)
    129                     'Can not serialize value type: %r\n '
    130                     'headers: %r\n value: %r' % (
--> 131                         type(value), headers, value)) from exc
    132 
    133             if dispparams:

TypeError: Can not serialize value type: <class 'int'>
 headers: {}
 value: 1
```

**Comment by webknjaz** [comment]
@kxepal according to the traceback, it doesn't take urlencoded code path.

**Comment by webknjaz** [comment]
@newmanifold let's you look at the RFC 7478: 

>5.3.  Interoperability with Web Applications
>
>   Many web applications use the "application/x-www-form-urlencoded"
   method for returning data from forms.  This format is quite compact,
   for example:
>
>      name=Xavier+Xantico&verdict=Yes&colour=Blue&happy=sad&Utf%F6r=Send
>
>   However, there is no opportunity to label the enclosed data with a
   content type, apply a charset, or use other encoding mechanisms.
   Many form-interpreting programs (primarily web browsers) now
   implement and generate multipart/form-data, but a receiving
   application might also need to support the
   "application/x-www-form-urlencoded" format.

This hints us about encoding. First of all, when multipart payload in HTTP is simply a bunch of bytes between boundary markers represented in ASCII with some encoding metadata.
Now, when using `str` in Python (3) there's encoding metadata attached to them so it's quite straightforward how that can be turned into bytes.
We can also send raw bytes. It's easy as well.
But what should we do with an integer? Well, bytes are integers without encoding. So if you go for putting it as a byte it might be weird:
```python
In [26]: chr(1)                                                                                                                                                                                
Out[26]: '\x01'
```
Same if you'd go for `str()`: why is it better? What if this number will point to some non-existing code pointin the target encoding? And so on...
If you take a look at browsers, they have forms with inputs but any data except for file fields is treated as strings.

Based on that, I'd say that one mustn't expect non-string form data to work or be valid.

**Comment by newmanifold** [comment]
@webknjaz 
Thank You for the response, 
I guess i misunderstood when @kxepal said that FormData and urlencoded shares same logic,
and yeah it makes sense to not to serialize non-string or non-bytes data, sorry i wasn't able to realize that there can be de serialization issue with it, just trying to help!.

**Comment by linpan** [comment]
TypeError: Can not serialize value type: <class 'int'>， still exits， goto httpx instead
