### ISSUE TITLE
Does logging module have impact on aiohttp performance?

### ISSUE THREAD

**Issue by sc-syf** [aio-libs/aiohttp#3663]
I noticed that the [aiohttp uses standard logging for tracking the library activity](https://docs.aiohttp.org/en/stable/logging.html), But the logging module is threading safe, namely it contains many acquire and release lock operations. will this cause a bad performance to aiohttp in  high concurrency environment?

**Comment by hleb-albau** [comment]
https://trio.readthedocs.io/en/latest/reference-io.html#asynchronous-filesystem-i-o great article about your question
