### ISSUE TITLE
Question: Difference between ClientResponse.url and .real_url

### ISSUE THREAD

**Issue by buhtz** [aio-libs/aiohttp#3664]
Sorry, for using _Issues_ as Q&A board but there was no response on the mailinglist.
X-Post: https://groups.google.com/forum/#!msg/aio-libs/ibZkny12BpM/ci7sEQjlAQAJ

My question is about [ClientResponse class](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientResponse).

What is the difference between `ClientResponse.url`and `ClientResponse.real_url`?

I can not find any.

e.g. I tried to get this URL
https://www.fsf.org/static/fsforg/rss/news.xml
which is redirected to
https://static.fsf.org/fsforg/rss/news.xml

**Comment by buhtz** [comment]
I hate bots.

**Comment by kxepal** [comment]
Well, as you can see by code difference is about fragment part:
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_reqrep.py#L651-L652
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_reqrep.py#L668-L674
and that's what about documentations states on.
