### ISSUE TITLE
ClientResponse.json() should support support object_hook callback

### ISSUE THREAD

**Issue by raees-khan** [aio-libs/aiohttp#3667]
Adding support for object_hook callback in `json` method of ClientResponse object should be considered (i.e. `response.json(object_hook=mycallback)`).

EDIT:
Basically what I am asking is that the `json` method should allow us to pass any optional arguments that the JSONDecoder accepts.

**Comment by asvetlov** [comment]
Please use `await response.json(loads=JSONDecoder(object_hook=mycallback).decode)`
`loads` is a callback that accepts a string and returns decoded python object.
Any implementation can be used, e.g. ujson or rapidjson. Not all alternatives have `JSONDecoder` class which accepts `object_hook` parameter.
