### ISSUE TITLE
Feature request: host parameter for aiohttp_server fixture

### ISSUE THREAD

**Issue by ykvch** [aio-libs/aiohttp#3671]
## Long story short
To test client connection to multiple hosts. The proposed fixture is aiohttp_server.
Unfortunately it accepts only port parameter.

## Expected behaviour
`host` parameter added to and passed over to TestServer (same as port) here:
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/pytest_plugin.py#L240-L241

## Actual behaviour
No host parameter

**Comment by asvetlov** [comment]
I suggest implementing your own fixture which can do everything you need.
`aiohttp_server` covers a server executed on local host only.

**Comment by ykvch** [comment]
Got it, thanks.
