### ISSUE TITLE
StreamReader.read(n) returns less than n bytes when more data available

### ISSUE THREAD

**Issue by raees-khan** [aio-libs/aiohttp#3681]
## Long story short

If the chunk size is greater than the chunk of data received by the server, the StreamReader.read returns whatever size chunk of data was received by the server.

## Expected behaviour

StreamReader.read(n) should return n bytes when n is not -1.

## Steps to reproduce

```
async def download(large_file):
    async with aiohttp.ClientSession() as session:
        async with session.get(large_file) as resp:
            while True:
                 chunk = await resp.content.read(10 * (1024 * 1024)) # Read 10MB
                  if not chunk:
                      break
                  print(len(chunk)) # the data chunk returned by streamreader is a few hundred KBs
```

**Comment by socketpair** [comment]
read vs read_exactly ?

**Comment by socketpair** [comment]
I don't see any bugs here.

**Comment by raees-khan** [comment]
> I don't see any bugs here.

- Go to https://docs.aiohttp.org/en/stable/streams.html.
- Read the description of `StreamReader.read`.
- Then download a large file and use `StreamReader.read` to read data in chunks of 10MB.
- You should be able to reproduce the behaviour I described in my original post.

As per the document, `StreamReader.read` should read N bytes passed when N is not -1. Either documentation is wrong or StreamReader has a bug.

**Comment by socketpair** [comment]
@cpython-rocks Accroding to docs: `Read up to n bytes`. So if `n` is not `-1` it returns `n` bytes **or less**. Internally, it does not even try to accumulate buffers, but it will split big buffer to return `up to n bytes`.

Please explain why you need 10MB exactly. Internally Aiohttp receives data in small chunks. Merging them into pieces of, say, 10MB is typically useless work. Merge them in your application if you want to.

**Comment by raees-khan** [comment]
@socketpair Wouldn't it read until EOF if `n is -1` and return all bytes? 10MB is just an example. What I am trying to highlight is the fact that when `n` is passed as an argument, then `read` should return `n` bytes no less (unless it reaches EOF) otherwise if it just returns the chunk received from server, then there is no point in having an optional param `n`.

```
while True:
    chunk = await resp.content.read(1048576) # Read 1 MB chunk
        if not chunk:
            break
        print(len(chunk)) # I expect `chunk` to be 1MB and it must be 1MB otherwise the `n` param is pointless.
```

**Comment by socketpair** [comment]
@asvetlov I can fix code so `read(xxx!=-1)` would read exactly as requested, or less (in case of EOF). Should I ? this will not break API, but may break applications that rely on old logic.

**Comment by socketpair** [comment]
I've done fix. Now there are no functionality like "read any block but no more than n bytes". I'm unusre if it is OK. It may be possible that some applications do not want to block until exactly n bytes read in that cases.

**Comment by socketpair** [comment]
Well, I thought more thoroughly, and came to this idea:

![изображение](https://user-images.githubusercontent.com/1157412/55964635-7df79600-5c8e-11e9-899c-438131f5f4a3.png)

So, I can change behavior of `read()` as topic starter asks, and implement `readany(n)` to return n or less bytes (as previously `read(n)` did). This change also will not break documented API.

**Comment by samuelcolvin** [comment]
I would say the current functionality is absolutely fine. As @socketpair says, if you want an exact size this can be achieved in the application.

**Comment by gjcarneiro** [comment]
I think it is fine as it is.  "block until n bytes read" is not what we want, we should not block.

Suppose you are reading a progressively encoded image file.  You ask to read 1MB because that is what a reasonable buffer size would work for you (before it starts causing memory / latency problems).  But you do not want to block until you get the full 1MB.  Instead, you want to just process whatever data is in the socket, so that the image can be progressively rendered in real time.

What you propose "block until n bytes read" is detrimental to real-time communications.  It's fine to offer it as an option, but please don't just change the existing behaviour.

**Comment by darkdragon-001** [comment]
I think it is exactly the same behavior as [`asyncio.StreamReader.read()`](https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamReader.read) and the synchronous [`io.RawIOBase.read()`](https://docs.python.org/3/library/io.html#io.RawIOBase.read) and an turn totally works as expected.

The reason for this is that the [POSIX `read()`](https://linux.die.net/man/3/read) behaves exactly like this.

When you want to read exactly `n` bytes, there are convenience functions like [`asyncio.readexaclty()`](https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamReader.readexactly) or synchronous [`io.BufferedReader(io.RawIOBase).read()`](https://docs.python.org/3/library/io.html#io.BufferedReader.read).

NB: It is exactly the same behavior on other programming languages like golang: [`os.File.read()`](https://pkg.go.dev/os#File.Read) returns _up to len(buffer) bytes_ but a convenience function [`io.ReadFull(reader, buffer)`](https://pkg.go.dev/io#ReadFull) exists to return _exactly n bytes_ :wink:

**Comment by Dreamsorcerer** [comment]
Looks like consensus is that current behaviour is correct.

I assume in the original example, the code returned <10MB of code, as that was what was available in the buffer. If data had been downloaded faster than the application processed it, then the chunks would be 10MB as requested. The goal appears to be to provide access to data rapidly as it arrives, rather than waiting until the chunksize has been reached.
