### ISSUE TITLE
How to invoke View constructor with additional parameters?

### ISSUE THREAD

**Issue by vit1251** [aio-libs/aiohttp#3682]
How to invoke View constructor with additional parameters?

**Comment by asvetlov** [comment]
Please elaborate.

**Comment by vit1251** [comment]
Example pseoudo code (write from memory a week later):
```
class WelcomeView
    def __init__(self, context):
        self._context = context

    def on_get(...):
        ...

class App()
    def run()
        # Setup some per server instance parameters
        context = {
            'db_pool': ...,
            'models': ...,
            'mappers': ...,
        }
        # Create server instance
        s = aiohttp.Server()
        s.add_route(path='/'. view=WelcomeView)
        s.serve()
```

How to set additional parameters for ```View``` creator and pass ```context``` variable in ```WelcomeView``` without using ```lambda``` or ```closure```. Do u have some additionall params (i.e. *args and **kwargs for ```View``` creator) in ```add_route``` or I should implement my own router with the custom ```View``` creator? Do u have any underline ideology with that restriction?

**Comment by asvetlov** [comment]
The provided snippet doesn't look like aiohttp code at all. There is no such thing as `aiohttp.Server` and `s.add_route()` / `s.serve()`

**Comment by vit1251** [comment]
@asvetlov please review class ```App``` code and in ```run()``` you may found `aiohttp.Server` in variable ```s```.

**Comment by asvetlov** [comment]
```
>>> import aiohttp
>>> aiohttp.Server
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aiohttp' has no attribute 'Server'
```

**Comment by vit1251** [comment]
You right. This example is pseudo code write only for shown idea (i.e. not a working code).

```
from aiohttp import web
app = web.Application()
 app.router.add_get('/', index)   # TODO - How to add constructor additional parameters on create new view instance?
web.run_app(app)
```

**Comment by asvetlov** [comment]
So, you need an application-wide configuration parameter: http://docs.aiohttp.org/en/stable/web_advanced.html#application-s-config

Put all you need into `app["context"]` and access it from a view by `self.request.config_dict["context"]` call.
