### ISSUE TITLE
Scrapping CONTENT_TYPE in multipart HTTP POST

### ISSUE THREAD

**Issue by elsampsa** [aio-libs/aiohttp#3697]
## Long story short

- I'm rewriting **client** side in a legacy javascript client/server system
- I'm using aiohttp at the **client** side
- The server has some legacy-bullshit javascript code that does not want the **CONTENT_TYPE** string in the HTTP POST multipart form messages

## Expected behaviour

- I **should be able to create** the following HTTP POST multipart form message (this is what the server wants from me):

![scott](https://user-images.githubusercontent.com/13978980/56141376-6168a000-5fa5-11e9-934b-f0fc63f72d4b.png)

## Actual behaviour

-  After doing some tricks, **I'm only able** to produce this message:

![current2](https://user-images.githubusercontent.com/13978980/56141456-7e9d6e80-5fa5-11e9-9130-0309a7c86e5e.png)

Q : **How can I get rid of the CONTENT_TYPE header field?**  (is this even implemented into aiohttp?)

## Steps to reproduce

(not relevant)

## Your environment

ubuntu 18, using aiohttp as a **client**

**Comment by Dreamsorcerer** [comment]
Is this still relevant? If so, please provide some sample code for what you've attempted so far.
