### ISSUE TITLE
get_encoding: make looking at body optional

### ISSUE THREAD

**Issue by blueyed** [aio-libs/aiohttp#3705]
I would like to use the `ClientResponse.get_encoding` method, but without having it look at the body (via chardet).

Could this be made optional with a keyword argument?

Code reference: https://github.com/aio-libs/aiohttp/blob/c0b681cd66f9301a5895d9be8af5126a24adf591/aiohttp/client_reqrep.py#L935-L954

**Comment by blueyed** [comment]
It is also a problem with StreamingResponses, where only `content` is being read, and therefore `_body` is `None`.

My workaround is setting `_body` to the `content` before calling it now.

**Comment by Dreamsorcerer** [comment]
Chardet is no longer used unless explicitly enabled with a custom function in current releases. So, I think this is no longer relevant.
