### ISSUE TITLE
FileResponse doesn't work on windows

### ISSUE THREAD

**Issue by tehKost** [aio-libs/aiohttp#3706]
Windows 10. After #3476 FileResponse throws `TypeError: cannot serialize '_io.BufferedReader' object` when trying to run_in_executor filepath.open: 
`with (await loop.run_in_executor(None, filepath.open, 'rb')) as fobj:`

**Comment by Tolmachofof** [comment]
Can you provide more information about your environment? 
Sample code example would also be very helpful.

**Comment by asvetlov** [comment]
Closing, @tehKost did not provide the required context.
