### ISSUE TITLE
Wrong return type annotathion for json of WSMessage in http_websocket.py

### ISSUE THREAD

**Issue by olned** [aio-libs/aiohttp#3707]
The json method of the WSMessage class returns parsed JSON data but declared as return None.

[aio-libs/aiohttp/http_websocket.py](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/http_websocket.py#L86)
> Line 86 
```
85    def json(self, *,  # type: ignore
86             loads: Callable[[Any], Any]=json.loads) -> None:
87        """Return parsed JSON data.
88        .. versionadded:: 0.22
89        """
90        return loads(self.data)
```

May be it would be better if it return type was absent?

**Comment by asvetlov** [comment]
Yes, it is an error.
Return type should be `Any`.
