### ISSUE TITLE
Sending web socket message to specific room or channel

### ISSUE THREAD

**Issue by britisharmy** [aio-libs/aiohttp#3712]
According to the examples, i can only see this code that sends a message to an unnamed channel

    await ws.send_str("Hello, {}".format(msg.data))

However,  would like to send  message to a named channel or room and subscribe to that room or channel on the client side which is a html page.

How can i send a message to a specific channel or room?

Thanks.

**Comment by amikrop** [comment]
I am not positive sure about this, but I am under the impression web socket "rooms" or channels is not explicitly a web socket spec structure, but it is implemented by each system with basic web socket features (include some "room name" in their json messages and server handle it at will). Maybe you were looking for something like this? https://stackoverflow.com/questions/11098514/python-websocket-and-socket-io-namespace
If this is the case, then something similar can be easily done with aiohttp (send_json etc).

**Comment by britisharmy** [comment]
Thanks for your answer.
