### ISSUE TITLE
Question about router sub routes

### ISSUE THREAD

**Issue by ElusiveSpirit** [aio-libs/aiohttp#3715]
Hello, is there any ability to create sub routes with custom middleware something like this:

```python
router = AppRouter()

posts_router = Router('/posts')
posts_router.add_route('GET', '/', posts_get_handler)      # GET /posts
posts_router.add_route('POST', '/', posts_create_handler)  # POST /posts

detail_posts_router = Router('/{id}')
detail_posts_router.add_context_handler(post_context_handler) # Find post by id and other staff
detail_posts_router.add_route('GET', '/', post_get_handler)        # GET /posts/{id}
detail_posts_router.add_route('PUT', '/', post_put_handler)        # PUT /posts/{id}
detail_posts_router.add_route('DELETE', '/', post_delete_handler)  # DELETE /posts/{id}

posts_router.add_router(detail_posts_router)

router.add_router(posts_router)

```

**Comment by asvetlov** [comment]
Sorry, no.
Middlewares are intentionally applied to the whole application (or sub-app), not to a part of application routes.

**Comment by ElusiveSpirit** [comment]
Is the core idea using class views with various mixins?

**Comment by asvetlov** [comment]
Personally, I don't use class based views at all.
If you need to do something before or after request -- just call a function explicitly.
Or wrap a handler with decorator.
There are very many techniques, mixins are on the last step in my mind.
