### ISSUE TITLE
session.get params don't support sequence

### ISSUE THREAD

**Issue by light4** [aio-libs/aiohttp#3716]
## Long story short

session.get params don't support sequence

## Expected behaviour

```python
# requests
import requests
params = {
    'test': [1, 2, 3]
}
resp = requests.get('http://httpbin.org/get', params=params) 
resp.url ==  'http://httpbin.org/get?test=1&test=2&test=3'

# aiohttp

import aiohttp

params = {
    'test': [1, 2, 3]
}

async with aiohttp.ClientSession() as session:
    async with session.get('http://httpbin.org/get', params=params) as resp:
        print(resp.status)
        print(await resp.text())
```

## Actual behaviour

```python
TypeError: Invalid variable type: value should be str or int, got [1, 2, 3] of type <class 'list'>
```

## Steps to reproduce

```python
import aiohttp

params = {
    'test': [1, 2, 3]
}

async with aiohttp.ClientSession() as session:
    async with session.get('http://httpbin.org/get', params=params) as resp:
        print(resp.status)
        print(await resp.text())
```

## Your environment
```
os: archlinux
python 3.7.3
aiohttp == 3.5.4
```

**Comment by light4** [comment]
Ok, I find this.
```python
from multidict import MultiDict
params=MultiDict([('q', 'test'), ('q', 'test2')]
```
But it's not that `"ergonomic"`, should we make `params` accept `list`?

**Comment by asvetlov** [comment]
Sorry, but no.
You can pass multiple values for the key already.
Also, how to emulate `MultiDict([('a', '1'), ('b', '2'), ('a', '3')]` to get `a=1&b=2&a=3`?
Note, arguments order matters in GET parameters by definition, even if you don't need the feature.

**Comment by light4** [comment]
I just pass `params` to `session.get`, sample codes in [/tests/test_client_functional.py#L982](https://github.com/aio-libs/aiohttp/blob/master/tests/test_client_functional.py#L982)

**Comment by asvetlov** [comment]
Eah, that's fine
