### ISSUE TITLE
Parameters not shown in response url

### ISSUE THREAD

**Issue by danielnelson** [aio-libs/aiohttp#372]
The documentation says you can inspect the response url attribute to see that the query parameters were encoded correctly, but this does not seem to be the case:

```
$ cat tmp.py 
import asyncio
import aiohttp

def run():
    payload = {'key1': 'value1', 'key2': 'value2'}
    r = yield from aiohttp.request('get', 'http://httpbin.org/get', params=payload)
    print(r.url)

asyncio.get_event_loop().run_until_complete(run())
$ python3.4 tmp.py 
http://httpbin.org/get
```

I expected it to print `http://httpbin.org/get?key2=value2&key1=value1`

**Comment by asvetlov** [comment]
Thanks for bug report.
We should override `.url` in `ClientResponse.update_path` as well as `self.path`.

@danielnelson would you prepare Pull Request with code and test?
