### ISSUE TITLE
Do not require running loop with CookieJar constructor?

### ISSUE THREAD

**Issue by blueyed** [aio-libs/aiohttp#3724]
`CookieJar.__init__` requires a running loop in the constructor, but that is only needed/used for expiration.

I think the loop should still get passed in, but not required to be running (checked via `get_running_loop` in `AbstractCookieJar`), and only retrieved when during expiration (via a property maybe?).

This would make it less difficult to debug issues with it / prototyping - where getting a `loop` is always a bit cumbersome.

Code reference: https://github.com/aio-libs/aiohttp/blob/9504fe2affaaff673fa4f3754c1c44221f8ba47d/aiohttp/cookiejar.py#L53-L60

**Comment by asvetlov** [comment]
What is your *real* use case?

**Comment by blueyed** [comment]
Prototyping to look how it (mis)behaves (https://github.com/aio-libs/aiohttp/issues/2502#issuecomment-488864745).
So not really a real-world use case, but thought it could be made simpler to use in this regard.

Feel free to close this though - I can also see that using a property etc would make it more complicated code-wise.
