### ISSUE TITLE
Question: If pong is not received in websockect client, should we just call close() in ClientWebSocketResponse?

### ISSUE THREAD

**Issue by yjqiang** [aio-libs/aiohttp#3739]
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_ws.py#L98
It is strange since I think if pong is not received, then we should just close the connection like what we did in https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_ws.py#L209 . But now it look like rewrite a simple [close](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_ws.py#L162) function? I'm not sure whether it is a feature or not, so I send this issue.

**Comment by asvetlov** [comment]
Sorry, I tried to re-read the question several times but still have no idea what are you asking for?

**Comment by yjqiang** [comment]
I mean why don't define `_pong_not_received` like this
```python
    def _pong_not_received(self) -> None:
        await self.close()
```
Now you are using this.
```python
    def _pong_not_received(self) -> None:
        if not self._closed:
            self._closed = True
            self._close_code = 1006
            self._exception = asyncio.TimeoutError()
            self._response.close()
```

**Comment by asvetlov** [comment]
Because you cannot use `await` in regular `def` function.
Making `_pong_not_received()` async function is doable but it requires rewriting pong checker to use a background pong task instead of simple `loop.call_later()` callbacks.

**Comment by yjqiang** [comment]
Got it.
