### ISSUE TITLE
CLA Assistant

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3741]
I've added a CLA Assistant tool to enforce contributors to sign the Licence Agreement before merging their PRs.

This is a common practice, e.g. CPython uses a custom CLA bot (but have a plan to switch to CLA Assistant).

The Developers Documentation should be updated to describe what CLA is, how to sign it and why it is important.
I think we can borrow this section from Python ( https://devguide.python.org/committing/#contributor-licensing-agreements )
A help with docs update is welcome!

**Comment by webknjaz** [comment]
Can we use a GitHub App for this? There's a few of those already existing and ready to use: https://discuss.python.org/t/using-cla-assistant-for-python/990/23?u=webknjaz

**Comment by asvetlov** [comment]
Sorry, forgot to note: I used https://cla-assistant.io/

**Comment by webknjaz** [comment]
That one doesn't use GitHub Apps, does it?

**Comment by webknjaz** [comment]
It just uses a bot user: https://github.com/cla-assistant/cla-assistant/issues/430

**Comment by webknjaz** [comment]
My suggestion is to use https://github.com/apps/cla-bot which would require more granular permissions not bound to users. I, as a user, would not like to give this thing permissions to access a bunch of other orgs I maintain.

**Comment by asvetlov** [comment]
So, if I install cla-bot I should select repositories where the bot requires CLA?

**Comment by webknjaz** [comment]
@asvetlov yes, or you could enable it for all repos

**Comment by asvetlov** [comment]
Installed cla-bot.
Still don't understand how to configure it properly.
@webknjaz could you help?

**Comment by webknjaz** [comment]
Sure, we need to add `.clabot` to the repo.

**Comment by webknjaz** [comment]
https://colineberhardt.github.io/cla-bot/#installing-cla-bot

**Comment by webknjaz** [comment]
Alright, it seems like we should have a file with contributors. I'll look closer on how to set it up a bit later.

**Comment by asvetlov** [comment]
In my mind, the bot should ask for CLA sign and support a list of signed users automatically.
Like the bot for Python itself does.

**Comment by asvetlov** [comment]
Temporary disabled a bot

**Comment by kxepal** [comment]
Just for history: why and how it would affect current contributors? Should they assign CLA as well?

**Comment by asvetlov** [comment]
In my mind, the singup process should be pretty simple.
Open a link with CLA form and press "submit" button (or something like this).
A new CLA bot most likely will require signing CLA from new and existing contributors. I believe there is not a problem if it can be done in two clicks.

**Comment by webknjaz** [comment]
I'm okay with that as long as there's a way to not authorize that thing with too broad privileges.

**Comment by webknjaz** [comment]
@kxepal your previous contributions are usually not subjects of CLAs unless one explicitly states this. I believe it only applies to contributions submitted after signing (that's why CPython requires it before accepting the first contribution). That's because you've already submitted all previous contributions under different conditions.
Another thing with CLA is that it may conflict with the agreement you've signed with your employer in which case it may make sense to check that it doesn't override your right to give up your code to the project.

#NotALawerDisclaimer
