### ISSUE TITLE
Support raw http responses on per-request basis

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3751]
There is a part of the conversation on gitter channel:

> Is there a way to disable content decoding in aiohttp?
> Ah, nevermind, I see the auto_decompress parameter for a ClientSession(). It would be great to be able to do this on a per-request basis. Or the ability to get the raw content from any response.

I think #3440 can solve the issue (along with many others).
Stay tuned.

**Comment by aaronst** [comment]
A specific example I'm dealing with now is that sometimes the response content does not match the `Content-Type` header. My current solution is to catch the exception that is raised by `Response.read()`, create an entirely new `ClientSession` with `auto_decompress=False`, and resend the request.

**Comment by asvetlov** [comment]
Not sure if layered stream readers can help in your specific case.
If `stream.read()` raises an exception the stream content has undefined state I think.
Data can be *partially* read and consumed from the underlying `.raw` stream.
Raw stream cannot keep the whole body, this approach has very high memory footprint.
Instead, the stream has only a part of the unread data buffer.

**Comment by gasinvein** [comment]
Hello. Is adding this feature still considered?
If not (or not in foreseeable future), can you please point me to the right direction how to implement per-request `auto_decompress` without altering `aiohttp` code? Currently I've came up with creating a new `ClientSession` instance, sharing  with the "parent" session the connector, cookie_jar, etc. whenever I need `auto_decompress` mode flipped; is this valid approach?

**Comment by asvetlov** [comment]
I can propose adding `auto_decompress` argument to `ClientSession.request()` method.

The change is relatively simple, a champion is wanted.

**Comment by Daste745** [comment]
I'll work on implementing this.

**Comment by ranisalt** [comment]
Shouldn't this be closed now that it's been implemented?
