### ISSUE TITLE
if __name__ == '__main__' for main examples.

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#3775]
https://github.com/aio-libs/aiohttp-devtools/issues/229

Would be useful if we wrapped `web.run_app(app)` if a main check:

```py
if __name__ == '__main__':
    web.run_app(app)
```

To work with aiohttp-devtools and other such tools.

If you're happy with this I'll submit a PR.

**Comment by asvetlov** [comment]
I quite don't follow what exact code should be wrapped?
Is it part of documentation?

**Comment by samuelcolvin** [comment]
sorry, yes in the documentation the server example should become:

```py
from aiohttp import web

async def handle(request):
    name = request.match_info.get('name', "Anonymous")
    text = "Hello, " + name
    return web.Response(text=text)

app = web.Application()
app.add_routes([web.get('/', handle),
                web.get('/{name}', handle)])

if __name__ == '__main__':
    web.run_app(app)
```

So that importing the module doesn't run the server.

[here](https://docs.aiohttp.org/en/stable/#getting-started)

**Comment by asvetlov** [comment]
I'm fine with the proposal

**Comment by samuelcolvin** [comment]
will do next week and fix my other PR.
