### ISSUE TITLE
Use aiohttp client to request multiple servers

### ISSUE THREAD

**Issue by faheem-nadeem** [aio-libs/aiohttp#3778]
## Long story short
Use aiohttp client to request multiple servers.

Just wanted to ask whether aiohttp clientsession supports client side loadbalancing. Something similar to how grpc does. A client can open a pool of tcp channels to multiple servers regularly discovered through dns (headless or A records) and do some basic client side round robin loadbalancing. I have some latency sensitive microservices where even injecting a proxy in between the request path and using it for load balancing can be a no go.
 
## Expected behaviour
At least roundrobin loadbalancing across multiple server, discovered through regular dns resolutions.

## Actual behaviour
Client requests only go to one server.

## Steps to reproduce
If you gave access to a kubernetes cluster. Just spawn two simple server web applications and create a client from another application. The servers can be exposed through k8s services and headless service. Giving the dns record of any service does not result in proper balancing.

## Your environment

Kubernetes
aiohttp==3.5.4

**Comment by asvetlov** [comment]
Basically yes.
See `_DSNCacheTable` and its usage: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/connector.py#L648-L685
