### ISSUE TITLE
Ubuntu 14.04 LTS has python3.4.0 and old asyncio

### ISSUE THREAD

**Issue by popravich** [aio-libs/aiohttp#378]
Hi guys!
v0.16.1 release is nice, but we have a problem)

LTS ubuntu (which is 14.04.2) has python 3.4.0 and old asyncio module with event loop missing `is_closed` method.
So we need to, atleast, mention that aiohttp v0.16 requires python 3.4.2+

**Comment by asvetlov** [comment]
Ohh crap!
I'll make new minor release with support for asyncio 3.4.0 a bit later (not sure about today but definitely before end of the week).

**Comment by popravich** [comment]
meanwhile we have dirty hack):

``` shell
pip install asyncio   # install fresh asyncio
export PYTHONPATH=$WORKON_HOME/lib/python3.4/site-packages:$PYTHONPATH  # override import lookup priorities
```

so I'm +1 for "Ohh crap!" ))

**Comment by asvetlov** [comment]
aiohttp 0.16.2 released :)
