### ISSUE TITLE
does aiohttp.web need `on_startup` if it can't support appending dynamiclly?

### ISSUE THREAD

**Issue by NewUserHa** [aio-libs/aiohttp#3781]
https://github.com/aio-libs/aiohttp/blob/4eecbcf603c6f7c19ffdf675b54098fdab07f7e9/aiohttp/signals.py#L34

the former one in `on_startup fronzenlist` might block the latter tasks. and creating background task could also work by asyncio.create_task anywhere in context, without `on_startup`'s help.

so what's the point of `on_startup`? do we actually need it?

update:
  there was a mistake in my app. it won't block app. **above is wrong, ignore it and see third comment.**

**Comment by asvetlov** [comment]
`on_startup` is a signal that executes registered callbacks on application starting (before serving incoming connections).
User can do arbitrary work in these callbacks.
One can *create* a background task but don't wait for the task finishing immediately. `on_cleanup` can be used for stopping long activities.

**Comment by NewUserHa** [comment]
my mistake. it will not block the app. updated the issue.

I meant users may create background tasks without on_startup. it also can not help start background tasks by a request handler. why need it(for proposals?) and so may upgrade to start tasks on the fly?

**Comment by asvetlov** [comment]
There are many scenarios.
Extract from documentation demonstrates a usage:
```
from aiopg.sa import create_engine

async def create_aiopg(app):
    app['pg_engine'] = await create_engine(
        user='postgre',
        database='postgre',
        host='localhost',
        port=5432,
        password=''
    )

async def dispose_aiopg(app):
    app['pg_engine'].close()
    await app['pg_engine'].wait_closed()

app.on_startup.append(create_aiopg)
app.on_cleanup.append(dispose_aiopg)
```

If you don't need it -- feel free to not use :)

**Comment by NewUserHa** [comment]
by the way. aiohttp seems that it will hide Exception and Traceback sometimes(most times) (like simple `TypeError: list indices must be integers or slices, not str` in the only one background task) making debug hard even all loggers are setting to DEBUG.
is it true? should I open a new issue?

**Comment by samuelcolvin** [comment]
That's no my experience, it's likely the real reason is that you're not getting the result of tasks which means code is failing properly.

Can you provide a reproducable example of aiohttp hiding exceptions?

**Comment by NewUserHa** [comment]
```
import asyncio
from aiohttp import web
import logging

app = web.Application()

async def main(app):
    hello

async def start_background_tasks(app):
    app['main_croutie'] = asyncio.create_task(main(app))

app.on_startup.append(start_background_tasks)

loop = asyncio.get_event_loop()
loop.set_debug(True)
logging.basicConfig(level=logging.DEBUG)
for name in logging.root.manager.loggerDict:
    logging.getLogger(name).setLevel(logging.DEBUG)

web.run_app(app)
```

**Comment by samuelcolvin** [comment]
That's nothing to do with aiohttp, but a fundamental of asyncio. As I said above, this is because you're not awaiting `main` or getting the task result so the exception doesn't propagate (or get printed).

Same thing without aiohttp:

```py
import asyncio

async def main(app):
    hello

async def start_background_tasks(app):
    app['main_croutie'] = asyncio.create_task(main(app))
    await asyncio.sleep(10)

loop = asyncio.get_event_loop()
loop.run_until_complete(start_background_tasks({}))
```

The exception in main won't be visible until the sleep finishes and the loop is cleaned up.

**Comment by NewUserHa** [comment]
Thanks!
