### ISSUE TITLE
Allow to skip header autogeneration

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#379]
I guess to skip generation of headers like `CONTENT-TYPE` etc. if `headers['CONTENT-TYPE'] = None`.

It may be implemented on both client and server sides.

**Comment by jettify** [comment]
+1 for this, I've encountered this issue porting library from `requests` to `aiohttp`. 

In my case `CONTENT-TYPE` is used for request signing, and for some REST api, it is useful not add this header at all. From other side `tornado` does not include this header by default too.

**Comment by fafhrd91** [comment]
+1 for skip, -1 for `headers['CONTENT-TYPE'] = None`

**Comment by asvetlov** [comment]
@fafhrd91 would you propose another schema for skipping headers?

**Comment by fafhrd91** [comment]
just keyword argument

**Comment by mpaolini** [comment]
why not reusing the `skip_auto_headers` kwarg? like

`aiohttp.client.get(skip_auto_headers=['Content-type'])`

**Comment by mpaolini** [comment]
This one got fixed by pull request #507 IMO

**Comment by asvetlov** [comment]
Sure, thanks
