### ISSUE TITLE
RuntimeWarning: coroutine 'noop2' was never awaited when closing any connector.

### ISSUE THREAD

**Issue by synchronizing** [aio-libs/aiohttp#3790]
## Long story short

As the title describes, aiohttp returns `RuntimeWarning: coroutine 'noop2' was never awaited` whenever closing a connector -- even if there is absolutely nothing running. 

![Screen Shot 2019-05-21 at 6 03 20 PM](https://user-images.githubusercontent.com/2829082/58133773-bf1a8880-7bf2-11e9-9859-a0aef9672ad4.png)

Asynchronous functionalities still seem to run without a problem within the application I am working on, but the error is still displayed regardless when closing the connector. 

## Expected behavior

No errors or warning when closing an empty connector -- or, a more detailed error report. From Googling it seems that `noop2` is an NPM package, which confused me even more as to why it is being brought up as an error on a Python package. 

## Actual behavior

Error occurs:

```
>>> import aiohttp
>>> import asyncio
>>> connector = aiohttp.TCPConnector(limit=100)
>>> print(connector.close())
<aiohttp.connector._DeprecationWaiter object at 0x7f0a17b517f0>
__main__:1: RuntimeWarning: coroutine 'noop2' was never awaited
>>>
```

## Steps to reproduce

Utilizing Docker:

### Dockerfile
```Dockerfile
FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y python3-pip python3-dev
RUN cd /usr/local/bin
RUN ln -s /usr/bin/python3 python
RUN pip3 install --upgrade pip
RUN pip3 install aiohttp

ENTRYPOINT ["python3"]
```

### Running
```bash
docker build -t foo . && docker run -it foo
```

### Doing

```
import aiohttp
import asyncio
connector = aiohttp.TCPConnector(limit=100)
print(connector.close())
```

## Your environment

* Mac OSX Mojave
* Python 3.7.2
* Running `aiohttp` inside clean `virtualenv` with _only_ `aiohttp` and `asyncio` installed.

However, this also happens with a fresh install of Ubuntu on Docker, as detailed above.

**Comment by asvetlov** [comment]
Use `await connector.close()` instead.

**Comment by synchronizing** [comment]
🤦🏼‍♂️ Makes complete sense. Thank you @asvetlov! Solved above.
