### ISSUE TITLE
Add debug argument to web.run_app()

### ISSUE THREAD

**Issue by NewUserHa** [aio-libs/aiohttp#3793]
```
500 Internal Server Error
Traceback:
Traceback (most recent call last):
   ...
NameError: name '...' is not defined
```
need a simple debug=False in web.run_app() like flask for security?

**Comment by asvetlov** [comment]
@NewUserHa sorry.
The tracker is not the helpdesk but a site for discussing bugs and future improvements.

Please stop using the bug tracker as Q&A resource like StackOverflow.
I respect your self-learning but the issue definitely is not a bug report or feature request.

I apologize if my response is not very friendly but please respect the project maintainers time.

P.S.
The same rule is applied for Python itself.
https://bugs.python.org/ exists for *working on Python*, not for asking *Python usage questions*.

**Comment by NewUserHa** [comment]
sorry, I might not explain well.
I was not asking a question, but try to open a future improvement issue. Is my English so crap?

Or, did the issue tracker already have a discussion on this?

shouldn't the traceback be hidden in a production environment like what flask does? no?
do you want to say 'go to use the `implement custom error pages`' next for every user from like flask?

**Comment by asvetlov** [comment]
Well, by default the traceback is printed in debug mode only.
Application debug mode is inherited from asyncio debug mode: https://docs.python.org/3/library/asyncio-dev.html#debug-mode

**Comment by samuelcolvin** [comment]
it might be worth documenting this better, currently the only thing I can see in the docs is that the `debug` kwarg is deprecated.

**Comment by asvetlov** [comment]
Please create an issue.
Pull Request would be even better!

**Comment by NewUserHa** [comment]
ok. Please let me reclaim my issue.
might you maintainers consider that aiohttp's web.run_app() might need a `debug=True` to control some settings easily, like the switch of `Flask` to give the users `friendly` convenient.

by the way, aiohttp-dev-tools will force changing `loop.set_debug()` without notifying users, that's what makes me open this issue. thanks for it

**Comment by samuelcolvin** [comment]
1. that's an issue with aiohttp-devtools, so please create the issue there.
2. aiohttp-devtools as the name clearly describes is for development where you always want tracebacks.

**Comment by asvetlov** [comment]
In asyncio code usually you need debug mode on when development to see useful warnings (they are most likely signs of programming errors).
Debug mode is relative slow, that's why these checks cannot be switched on permanently.
Thus, aiohttp debug mode is usually used in conjunction with asyncio debug mode.
Hint: in python 3.7 there is very useful `python -X dev prog.py` option which is highly recommended for development.

Is there a reason for using asyncio and aiohttp debug modes separately?
I don't think so, but maybe I missed some use case?

**Comment by NewUserHa** [comment]
'aiohttp's web.run_app() might need a debug=True to control some settings easily', just a parameter of `web.run_app()` to set `loop.set_debug(True)`, even `logging.basicConfig(level=logging.DEBUG)` that's what I meant.
as for me(maybe others well), that the times use `debug=True` flag is more ofen than other parameters since the only time use the other seems is once putting/moving the final version on the server.

I never say `using asyncio and aiohttp debug modes separately`.
This also is a small suggest, not a big deal. for convenient. even not accepted if you don't think it is needed, the document can also have space to improve. of course, after you would like

**Comment by asvetlov** [comment]
Are you talking about `web.run_app()` only, not `web.Application`?
That makes sense, especially after having `debug=False` parameter in `asyncio.run()`: https://docs.python.org/3/library/asyncio-task.html#asyncio.run

I think `web.run_app()` should operate with loop, debug mode and exceptions in exactly the same manner as `asyncio.run()` does.
Now they are pretty similar but still different.

**Comment by asvetlov** [comment]
@NewUserHa would you prepare a pull request for adding `debug` keyword argument to `web.run_app()`?

**Comment by NewUserHa** [comment]
no problem.
what about 'add debug into run_app() as the last one parameter and apply loop.set_debug(True) just in run_app() as well'?
need pytest for it? I don't think it need

**Comment by asvetlov** [comment]
Rather I propose to add `debug` as the first keyword-only argument (but honestly I don't care too much about the parameter position unless it is keyword-only).

Agree with `loop.set_debug()`
Also I'm asking to replace `get_event_loop()` with `new_event_loop()` as `asyncio.run()` does.

Regarding tests: there is `test_run_app.py`.  Adding a new test is not a big deal.
Documentation should be updated as well.
I'll help you on review if needed.

**Comment by NewUserHa** [comment]
https://github.com/aio-libs/aiohttp/pull/3796

**Comment by NewUserHa** [comment]
does aiohttp need `logging.basicConfig(level=logging.DEBUG)` ?

**Comment by asvetlov** [comment]
I think aiohttp don't need to override the global logging configuration.
User can want to setup logging on his own (or use `INFO` level for example).
Calling `basicConfig()` before starting `run_app()` is pretty easy and straightforward.

**Comment by NewUserHa** [comment]
then if there's any helpful info about logging for aiohttp, more info in documents would be helpful

**Comment by asvetlov** [comment]
https://docs.aiohttp.org/en/stable/logging.html?highlight=logging
