### ISSUE TITLE
use azure pipelines rather than appveyor

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#3794]
appveyor is slooooow. 

This makes contributing to aiohttp time consuming and more difficult because the feedback loop when developing is extended - particularly for those (most of us?) not using windows so relying on appveyor for windows tests.

Instead perhaps we should use [azure pipelines](https://github.com/marketplace/azure-pipelines/)? I haven't used them personally but by the looks of [a build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=36832&view=logs&jobId=01f6b188-2925-5845-531a-07cc5b572146), jobs aren't queued for very long.

**Comment by asvetlov** [comment]
Maybe. I'm open to suggestions but have no capacity to setup Azure now

**Comment by webknjaz** [comment]
We could do it additionally to AppVeyor. I'd now replace it completely. From what I saw, Azure Pipelines are a bit messy and potentially leak certain features.

**Comment by samuelcolvin** [comment]
I've just been trying them (not helped by the github webhook outage), they're not perfect but they look a lot easy to use than appveyor, see an example [here](https://github.com/samuelcolvin/pydantic/pull/538/files#diff-fec826feae04e51c0d94076385408bdc).

I'd be happy to help set it up if you'd like?

**Comment by webknjaz** [comment]
@samuelcolvin I'm open to reviewing a PR. Let's ask @asvetlov to add you to the proper "organization" entity there.

**Comment by asvetlov** [comment]
We use GitHub Workflows now
