### ISSUE TITLE
@ symbol in cookies error happend.

### ISSUE THREAD

**Issue by cxapython** [aio-libs/aiohttp#3797]
hello,there have an error
when i get cookies expamle "a=123;b=456",the will be become 'a=123;b="@"456'
@ symbol in cookies，will become "@".

**Comment by kxepal** [comment]
`@` is not a valid character in cookies. As per [RFC 6265](https://tools.ietf.org/html/rfc6265#section-4.1.1):
```
cookie-header = "Cookie:" OWS cookie-string OWS
--
cookie-string = cookie-pair *( ";" SP cookie-pair )
cookie-pair   = cookie-name "=" cookie-value
cookie-name   = token
token         = 1*<any CHAR except CTLs or separators>
separators    = "(" \| ")" \| "<" \| ">" \| "@"
\| "," \| ";" \| ":" \| "\" \| <">
\| "/" \| "[" \| "]" \| "?" \| "="
\| "{" \| "}" \| SP \| HT
```

**Comment by cxapython** [comment]
ok,thx,but i wanna use @ in cookie,how can i use it?


------------------ 原始邮件 ------------------
发件人: "Alexander Shorin"<notifications@github.com>;
发送时间: 2019年5月24日(星期五) 中午11:23
收件人: "aio-libs/aiohttp"<aiohttp@noreply.github.com>;
抄送: "小清新Discoᵖʸᵗʰᵒⁿ"<1598828268@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [aio-libs/aiohttp] @ symbol in cookies error happend. (#3797)




@ is not a valid character in cookies. As per RFC 6265:
 cookie-header = "Cookie:" OWS cookie-string OWS -- cookie-string = cookie-pair *( ";" SP cookie-pair ) cookie-pair   = cookie-name "=" cookie-value cookie-name   = token token         = 1*<any CHAR except CTLs or separators> separators    = "(" \| ")" \| "<" \| ">" \| "@" \| "," \| ";" \| ":" \| "\" \| <"> \| "/" \| "[" \| "]" \| "?" \| "=" \| "{" \| "}" \| SP \| HT

**Comment by asvetlov** [comment]
Do the same as aiohttp (Python standard library actually) does -- quote unallowed symbols :)

**Comment by cxapython** [comment]
ok thank you.
