### ISSUE TITLE
loop.is_closed() needs python > 3.4.2

### ISSUE THREAD

**Issue by bamthomas** [aio-libs/aiohttp#382]
in request.close() there is a call _loop.is_closed()

https://docs.python.org/3/library/asyncio-eventloop.html#run-an-event-loop mention that this method is new since python 3.4.2.

So the http client example with yield response.read() is broken with (ubuntu 14.04LTS) :
Traceback (most recent call last):
  File "/home/bruno/src/DomoPyc/venv/lib/python3.4/site-packages/aiohttp/connector.py", line 59, in **del**
    if self._loop.is_closed():
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'is_closed'

**Comment by asvetlov** [comment]
Hi. I've fixed the issue in #378 
Please use fresh aiohttp 0.16.2

**Comment by bamthomas** [comment]
Thank you, and sorry for the double issue

**Comment by asvetlov** [comment]
No problem

On Fri, May 29, 2015 at 9:56 AM, Bruno Thomas notifications@github.com
wrote:

> Thank you, and sorry for the double issue
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KeepSafe/aiohttp/issues/382#issuecomment-106713155.

## 

Thanks,
Andrew Svetlov
