### ISSUE TITLE
Concurrent requests are getting hung in multithreading

### ISSUE THREAD

**Issue by zero1386** [aio-libs/aiohttp#3839]
## Long story short
Concurrent requests are getting hung in multithreading.
My code
```python
import aiohttp
import asyncio
import time
from threading import Thread

async def fetch():
    url = 'https://api.scryfall.com/cards/random'   
    timeout = aiohttp.ClientTimeout(total=0.1, connect=0.1,
                      sock_connect=0.1, sock_read=0.1)         
    while 1:
        async with aiohttp.ClientSession() as session: 
            print('cant run')
            async with session.get(url,timeout = timeout) as response:
                print(await response.json())                  
            await asyncio.sleep(10) 

def start_loop(loop):
    asyncio.set_event_loop(loop)
    loop.run_forever()

if __name__ == '__main__':

    new_loop = asyncio.new_event_loop()
    t = Thread(target=start_loop, args=(new_loop,))
    t.start()
    asyncio.run_coroutine_threadsafe(fetch(), new_loop)
    while 1:
        time.sleep(1)
```
I run this code,and requests are getting hung at 
`async with session.get(url,timeout = timeout) as response:`
and I set 
```python
timeout = aiohttp.ClientTimeout(total=10, connect=10,
                      sock_connect=10, sock_read=10)
```
it can run .But it runs for 20min or I link down network,it will be getting hung.

## Actual behaviour

I change my code,let concurrent requests run in mainthreading,it will be able to report timeout errors.

## Your environment
windows 7 , python 3.7.1 , aiohttp3.5.4

**Comment by webknjaz** [comment]
1) Why would you do that?
2) What about GIL?

**Comment by asvetlov** [comment]
I see that ssl transport is broken when I'm trying to run the snippet.
It is asyncio problem, not aiohttp.
Please keep the issue open for a while, maybe the reproducible example can help me with making SSL fixed.
