### ISSUE TITLE
Connections are not released

### ISSUE THREAD

**Issue by elsampsa** [aio-libs/aiohttp#3845]
## Long story short

When there is no network interface, ```ClientConnectorError```does not return connection automatically to the connection pool.

Instead, connections (and threads..!) start to pile up.  See this ```htop``` screenshot:

![Screenshot_20190614_121800](https://user-images.githubusercontent.com/13978980/59499395-ff8ebe80-8e9f-11e9-8cf6-1c63c29d4ebb.png)

## Expected behaviour

Threads should not pile up.

## Steps to reproduce
1. Save this script as ```threading_myster.py```:
```
import asyncio
import aiohttp

async def run():
    session = aiohttp.ClientSession()
    
    """# doing this instead, makes no difference:
    connector = aiohttp.TCPConnector(limit = 2)
    session = aiohttp.ClientSession(connector = connector)
    """
    
    print("Hello.  My connector is", session.connector)
    while True:
        try:
            print("GETting")
            resp = await session.get("http://google.com")
        except Exception as e:
            print("get failed with", str(e))
        else:
            print("got response", resp)
        await asyncio.sleep(1)
    
asyncio.get_event_loop().run_until_complete(run())
```
2. In a terminal, start ```htop```.  Press F5 for tree view, then press F4 & filter by "mystery"  (your htop should be configured to show user threads [thats the default], if its not, then google is your friend)
3. Disable your network interface (i.e., in network manager, cut the connection)
4. In another terminal, type
```
python3 threading_mystery.py
```
5. Observe how the number of threads grows each second in htop

## Your environment
aiohttp 3.5.4.  Ubuntu 18.04 LTS.

### Bonus

When waiting for sockets, one can use either (a) blocking socket + a system thread or alternatively, (b) a list of file descriptors, waited with select.

I thought asyncio & aiohttp use the latter (b) aproach, but it seems to be the former (a)!

P. S. Remember that what you're seeing in that htop screenshot are *threads* pertaining to a certain *process*..  just not to think there are lots of processes, each consuming memory (the total memory consumption is that 0.2%)

**Comment by yjqiang** [comment]
https://github.com/aio-libs/aiohttp/issues/3815

**Comment by hh-h** [comment]
I wonder whether either wrap `get` into `async with` or adding `finally: resp.close()` will solve the problem?

**Comment by asvetlov** [comment]
aiohttp doesn't spawn a thread for a new connection.
I think you see default thread pool which is used for DNS resolving unless `aiohttp.AsyncResolver` is used

**Comment by Dreamsorcerer** [comment]
Are you still able to reproduce this on latests releases? I can't seem to reproduce.
