### ISSUE TITLE
Version 3.5.4 Getting "405 Method Not Allowed" on all POST.  GET's are fine. 

### ISSUE THREAD

**Issue by dev-ns8** [aio-libs/aiohttp#3847]
## Long story short
I have tried different ways of registering routes within my app, however I can not perform any HTTP POST requests.  All of my GET requests work flawlessly.  Saw an old Stackoverflow Article that hinted towards a problem  with "multidict" library so I upgraded that and still having the same issue.

Working from my Macbook, trying to create a server API service.  I've attached my short python file so you can see my code. 

[app copy.txt](https://github.com/aio-libs/aiohttp/files/3293509/app.copy.txt)

**Comment by asvetlov** [comment]
`/` route shades all subsequent definitions.
Put it at the end.

**Comment by dev-ns8** [comment]
@asvetlov I removed the `/` Route all together and I'm still receiving a 405 Not allowed on my `POST` routes....

**Comment by rysson** [comment]
Wait, @dev-ns8, do you test API with `curl -x post`? See #3233, method should be in uppercase.
I had the same effect. I know, it was a year ago, I comment it for people with the same problem.

```
curl -X post http://localhost:8080/post
405: Method Not Allowed
curl -X POST http://localhost:8080/post
post /post
```

Testing code:
```python
from aiohttp import web 
 
routes = web.RouteTableDef() 
 
@routes.get('/') 
async def get_handler(request): 
    return web.Response(text='get /\n') 
 
@routes.post('/post') 
async def post_handler(request): 
    return web.Response(text='post /post\n') 
 
@routes.put('/put') 
async def put_handler(request): 
    return web.Response(text='put /put\n') 
 
app = web.Application() 
app.add_routes(routes) 
web.run_app(app) 
```

I used:
- Python 3.8.3
- aiohttp-3.6.2
