### ISSUE TITLE
pls help me i have exception

### ISSUE THREAD

**Issue by ghost** [aio-libs/aiohttp#3849]
`# -*- coding: utf-8 -*-
import asyncio
import aiohttp
from aiosocksy.connector import ProxyConnector, ProxyClientRequest
URLS = 'http:/ONINON SITE' # here url onion site which uses br and utf8
# version of brotli is : 1.0.7  version of aiohttp 4.0.0.a.0 python 3.7.3 on windows 10 x64 1903 and this site use title smile like  ❤  ❂   *
# and i have # aiohttp.client_exceptions.ClientResponseError: 400, message='invalid character in header' error pls help me sorry for  my bad eng

async def fetch(url):
    connector = ProxyConnector()
    Tor_Proxy = 'socks5://192.168.0.4:9050' # just tor proxy in my local network
    async with aiohttp.ClientSession(connector=connector, request_class=ProxyClientRequest) as session:
        async with session.get(url, proxy=Tor_Proxy, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 6.0; rv:11.0) Gecko/11.0 Firefox/11.0', 'Accept-Encoding': 'br'}) as response:
            print(await response.text())

loop = asyncio.get_event_loop()
loop.run_until_complete(fetch(URLS))
`

**Comment by samuelcolvin** [comment]
I'm afraid this question is not at all clear.

If you would like to get help, please take the time to [format your questions](https://github.github.com/gfm/) properly so it's easy for those reading it to understand. 

I understand that english might not be your first language, but you can still take the time to give a reproducible demonstration of your problem that's properly formatted.
