### ISSUE TITLE
Add explicit initialization and running stages to web.Application

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#385]
Now we have read-only `tuple` property named `middlewares` for `web.Application`.

It's inconvenient a bit, see example from [aiohttp_debugtoolbar]():

```
import aiohttp_debugtoolbar
app = web.Application(loop=loop,
                       middlewares=[aiohttp_debugtoolbar.middleware])
aiohttp_debugtoolbar.setup(app)
```

I guess to allow modify `app.middlewares` on setup stage (make it readwrite `list` property) but after first `app.make_handler()` call it should be converted to readonly `tuple` property.

Perhaps we need `app.freeze()` and even `app.unfreeze()` methods as well as `app.frozen` property.

`router` API also may be extended to allow for adding new routes only in non-frozen stage.

**Comment by fafhrd91** [comment]
-1, it is way too complicated

**Comment by fafhrd91** [comment]
just make it list
