### ISSUE TITLE
mypy thinks that instance of ClientSession() is None (under certain conditions)

### ISSUE THREAD

**Issue by haizaar** [aio-libs/aiohttp#3858]
Good day,
First, I'm not sure if this is aiohttp or mypy issue, but I'll start here.

The below code produces very strange mypy error (it's a reproduction ripped of a much bigger codebase, so please excuse a mild lack of purpose)
```python
import asyncio
from typing import Type, TypeVar
import aiohttp

ResponseType = TypeVar("ResponseType", str, bytes)
# ResponseType = TypeVar("ResponseType")  <- This works, but it's not what I need in real life

async def post(response_type: Type[ResponseType]) -> None:
    async with aiohttp.ClientSession() as session:
        async with session.get("https://google.com") as res:
            res.raise_for_status()

asyncio.run(post(str))
```

```
$ mypy bug.py 
bug.py:13: error: "None" has no attribute "get"
```

The code runs find, so `session` is definitely not `None`.
Interestingly enough, if I define `ResponseType` just as `ResponseType = TypeVar()`, it works fine!

Any ideas?

## Environment
* aiohttp 3.5.4, client side
* mypy==0.710, mypy-extensions==0.4.1
* python 3.7
* ubuntu 16.04, amd64

**Comment by asvetlov** [comment]
No idea.
Please file an issue on mypy GitHub tracker.

**Comment by haizaar** [comment]
Did so. Thanks for having a look.

**Comment by haizaar** [comment]
Let's see if they acknowledge it and then I assume this issue can be closed.
