### ISSUE TITLE
timeout behave is mis understood? or maybe timeout errors?

### ISSUE THREAD

**Issue by aohan237** [aio-libs/aiohttp#3859]
i encounter some problem. which will throw a timeout exception.
but i read the timeout implement, and found something.

the aiohttp time out used is async time out context manager, which is mainly the task execution time's time out, not a http request's time out.  

take the official doc example  as an example:
```python
import aiohttp
import asyncio
import time

async def fetch(session, url):
    async with session.get(url,timeout=5) as response:
        return await response.text()

async def main():
    async with aiohttp.ClientSession() as session:
        html = await fetch(session, 'http://python.org')
        print(html)

async def test():
    print(loop.time())
    time.sleep(8)
    print(loop.time())
    
loop = asyncio.get_event_loop()
loop.create_task(main())
loop.create_task(test())
loop.run_forever()
```

this code will raise a timeout exception. but i think it is a task timeout error. 

mostly,the http request body has been arrived, as to http request time out ,this will be in good.

so ,what is timeout in aiohttp? how to right use it?

**Comment by aohan237** [comment]
https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientTimeout

client timeout option seems fail to complish this,either.

**Comment by Dreamsorcerer** [comment]
I'm not clear what you're asking. ClientTimeout provides different timeout options depending on what you need.
