### ISSUE TITLE
Fix error with too long Header

### ISSUE THREAD

**Issue by serjshevchenko** [aio-libs/aiohttp#3862]
I got error "Got more than 8190 bytes (11194) when reading Header value is too long."
It would be nice to be able to pass additional args into RequestHandler (max_line_size, max_field_size)  via `web.run_app`

**Comment by serjshevchenko** [comment]
Fixed in PR #3861

**Comment by Dreamsorcerer** [comment]
Judging by the linked PR, interest was lost for this.
