### ISSUE TITLE
Customising raise_for_status

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#3864]
It would be great if it was possible to customize `raise_for_status` to:
* add more information to the exception
* log the error/warning (with `extra_info`) to sentry etc.
* make the response check more specific, eg. require `200`
* adapt the error, eg. to make it picklable, see https://github.com/aio-libs/multidict/issues/340

Adding all this to aiohttp would obviously be infeasible, but it would be possible to add another kwarg when creating a client session `response_check` - a coroutine called when `raise_for_status=True` to check if a response is valid.

This approach would be backwards compatible.

It would also be useful if `check_response` were also called for request timeouts, but maybe that's more complicated and would not be backwards compatible.

Information which might be useful when debugging http client requests:
* request url
* redirects
* request headers
* request body
* response headers
* response body
* response time

I don't want to add all these to the standard error, but allowing a coroutine to check responses would allow all this to added if I wanted.

**Comment by asvetlov** [comment]
The feature request sounds reasonable.

Should `response_check` parameter to be added for every `request()` / `get()` / `post()` method or to `ClientSession` constructor only?

The real question is: want we add yet another *callback* into our API?
*Inversion of Control* is hard to debug.
Are there alternative approaches?

Don't get me wrong: I'm not strongly against the proposal but want to discuss it carefully first.

**Comment by samuelcolvin** [comment]
I understand.

Technically this is not another callback, just overwriting `_raise_for_status` with a custom method I think.

**Comment by samuelcolvin** [comment]
`response_check` should definitely be added to `ClientSession`, if I want custom logic on a request I can do it after response as usual.

**Comment by asvetlov** [comment]
Fixed by #3892
