### ISSUE TITLE
A way to detect on runtime that C version of multidict is used ?

### ISSUE THREAD

**Issue by ludovic-gasc** [aio-libs/aiohttp#387]
Hi,

I'm working to upgrade aiohttp.web benchmarks in FrameworkBenchmarks.
I've applied performance tips you gave me in #314.

However, I don't control the environment where the daemon will be launched, it should be possible that Cython compilation doesn't run during the automatic setup, even if gcc and Python headers should be installed.

Do you have an idea how I could check that it's the C version of multidict is used ? I wish to check that in Python just before to launch aiohttp.web Application.

Moreover, if since our last discussion about performances, you've found other tips, I'm interested in, especially around aiopg. BTW, I've planned to test Cython support of coroutines.

Regards.

**Comment by asvetlov** [comment]
You can do check:

```
try:
   from aiohttp import _multidict
   has_c_accel = True 
except ImportError:
   has_c_accel = False
```
