### ISSUE TITLE
Sharing cleanup_ctx data with sub-apps

### ISSUE THREAD

**Issue by mattrasband** [aio-libs/aiohttp#3876]
There is a documented approach of sharing resources from parent apps to nested apps in #2413. However that does not work for the common case of using CleanupContext managed resources (such as a database or redis pool).

Is there a recommended way of sharing resources provided by a root application's context signals?

_Originally posted in https://github.com/aio-libs/aiohttp/issues/2412#issuecomment-505492678_

**Comment by mattrasband** [comment]
I ask mostly to know if there is a planned design for that, as there are a few options:

1. Add the resource to a sub-application in the signal
1. Create the resources at the app creation phase and have signals manage the cleanup or other lifecycle things (not too fond of this)
1. Pass the parent app to a nested app (definitely don't like this)

Item 1 seems the most likely to be a good approach, and then nested apps could have their signal check for a resource or create their own to make it more pluggable.

**Comment by asvetlov** [comment]
Do you have an idea of how the usage code should look like?

**Comment by vladarefiev** [comment]
Faced the same issue. I want to initialise db variable in main app in `cleanup_ctx` and pass it to sub_apps, but can't find out how to do it properly.

**Comment by mattrasband** [comment]
I ended up deciding that a parent app knowing about subapps is 100% ok, so for one app we are just explicity setting the properties on a subapp. With testing they are easy enough to set by just testing the nested apps on their own merit.

Here's a sample from [ours](https://github.com/pyslackers/website/blob/eb0d992a265919dc1991a1402c5029fcab1f9d75/pyslackersweb/contexts.py#L9-L35) (option #1 above):

```python
async def postgresql_pool(app: web.Application) -> AsyncGenerator[None, None]:
    async with asyncpg.create_pool(dsn=app["POSTGRESQL_DSN"]) as pool:
        app["db"] = app["website_app"]["db"] = pool
        yield
```

Where `app["website_app"]` is our nested application.

There may be merit in just having a last-signal register them all (`async def register_nested_dependencies(app: web.Application):`), but I wanted to keep the usages close to the declaration/lifecycle managed in the cleanup contexts.
