### ISSUE TITLE
request.GET ignores blank values

### ISSUE THREAD

**Issue by fangpenlin** [aio-libs/aiohttp#388]
When you pass blank query value like

```
foo=
```

then `request.GET` will be empty instead of having `{'foo': ''}`

**Comment by fangpenlin** [comment]
should pass `keep_blank_values=True` for `parse_qsl` 

https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web_reqrep.py#L184

**Comment by asvetlov** [comment]
1. There is impossible to pass parameter to `.GET` property.
2. `keep_blank_values=False` is reasonable default.
3. There is `request.query_string` request's property which allow to manually parse query string preserving blank values.

As result I suggest to close the issue as _wontfix_.

**Comment by fangpenlin** [comment]
@asvetlov I am okay with this, but is it possible to assign a custom request class while creating application? so that I can inherit the request class, define my own stuff, including a override GET with blank values.

**Comment by asvetlov** [comment]
@victorlin I don't want to allow web.Request customization. At least for now.
1. I don't see strong reasons for that.
2. The constructor parameters are not part of public API now, and they are changed very quickly between releases. I don't want to publish those unstable API parts.
