### ISSUE TITLE
New routing changes are undocumented and/or difficult to customize

### ISSUE THREAD

**Issue by mwfrojdman** [aio-libs/aiohttp#389]
I made a custom AbstractRouter and AbstractMatchInfo instance to support Werkzeug URL routing. It worked well in aiohttp 0.12, but now that I upgraded to 0.15.3 (because Debian stretch packages it) AbstractMatchInfo has a new abstract property route.

The aiohttp.abc module does not contain an ABC for route, but there is aiohttp.web_urldispatcher.Route which has two abstract methods (url and match). The Route class also has a method named handle_expect_header, which is called from aiohttp.web.RequestHandler.handle_request.

For me specifically, the problem is that the role of the route attribute is obscure and has to be deduced by reading the source code. Also, a "route" has no ABC for it's complete API like the classes in aiohttp.abc. At a first glance it seems like it was introduced to support other functionality, but in the same go made the routing API more tightly coupled with the instance classes included in aiohttp.

**Comment by mwfrojdman** [comment]
PS: I checked 0.16.3 and it doesn't seem different from 0.15.3 in the relevant parts

**Comment by fafhrd91** [comment]
Let's wait with docs until 0.17, I'd like to do some refactoring on routing

**Comment by mwfrojdman** [comment]
It's also that Route does not seem to have any other utilization than the handle_expect_header call from web.py, outside the built-in router classes. Are there some future dependencies planned or could the abstract property route for AbstractMatchInfo be dropped? That would require handle_expect_header to be called from something else - maybe the match_info object itself?

**Comment by asvetlov** [comment]
Please also take a look on https://github.com/zzzsochi/aiotraversal/ -- alternative router implementation based on resource traversal.
I want to have abstract api which satisfies both default and alternative router implementations.

**Comment by mwfrojdman** [comment]
The aiohttp routing API is really clean (well now slightly less clean, at least temporarily :) ) enabling plugging in your own implementation or adapting pre-existing ones. For my project, we already have a lot of routing functionality implemented with Werkzeug (http://werkzeug.pocoo.org/docs/0.10/routing/) and especially the custom converters have been useful. Aiohttp made adapting the werkzeug based routing trivial, while many other frameworks are more or less impossible. Tornado is a perfect example of the latter - it lures you to think there are actual API's and adaptability, but the whole framework is full of references to every other module, everywhere making it a monolith.
