### ISSUE TITLE
Some cookies not getting saved in ClientSession

### ISSUE THREAD

**Issue by bwright1558** [aio-libs/aiohttp#3895]
## Long story short

I'm requesting a page from a website to get cookies stored in an instance of `aiohttp.ClientSession`. One of the `Set-Cookie` headers has a value that looks like the following:

    token=secret; Domain=.testdomain.com; Path=/; Expires=Mon, 08-Jul-69 21:39:08 UTC; HttpOnly

This cookie is not getting stored in the session. After digging around, the cause is from the `UTC` part of the expiration date in the cookie. `http.cookies.SimpleCookie.load` will not parse the cookie because it uses a regex that only searches for `GMT`. Looks like there's already a ticket for it [here](https://bugs.python.org/issue35824). In short, `aiohttp.ClientSession` is not able to store the cookie due to a problem in the standard library.

## Expected behaviour

Store the cookie in `aiohttp.ClientSession` regardless if the cookie expiration is GMT, UTC, or any other timezone.

## Next steps

Was hoping I could get some suggestions for a workaround on this issue. I know I could manually parse the `Set-Cookie` headers myself, but was wondering if there is a simpler solution I might have overlooked. I'm on a deadline and don't have time to wait for the next python release that may or may not have this issue resolved.

**Comment by socketpair** [comment]
https://tools.ietf.org/html/rfc6265#section-4.1.1 : sane-cookie-date  = <rfc1123-date, defined in [RFC2616], Section 3.3.1>

https://tools.ietf.org/html/rfc2616#section-3.3.1

All HTTP date/time stamps MUST be represented in Greenwich Mean Time
   (GMT), without exception. For the purposes of HTTP, GMT is exactly
   equal to UTC (Coordinated Universal Time). This is indicated in the
   first two formats by the inclusion of "GMT" as the three-letter
   abbreviation for time zone

**Comment by socketpair** [comment]
It's not a bug by design. We will not parse non RFC-compliant data.

Possibly http.cookiejar could parse that. It uses less strict parser. But still, "UTC" is an error in the web-server. Please contact its author.
