### ISSUE TITLE
404 on http://aiohttp.readthedocs.org/en/v0.16.3/

### ISSUE THREAD

**Issue by wiygn** [aio-libs/aiohttp#390]
Hello, when I had opened [link](http://aiohttp.readthedocs.org/en/v0.16.2/) to docs from README.MD, I got notice on site:

> Note:
> You are not using the most up to date version of the library. 0.16.3 is the newest version.

So there are no docs by the link in this alert.

**Comment by asvetlov** [comment]
Fixed.
Switched readthedocs to use stable (the latest tagged) build.
