### ISSUE TITLE
aiohttp.web.DynamicResource._match could be a very useful public method..

### ISSUE THREAD

**Issue by zokrezyl** [aio-libs/aiohttp#3924]
I use the method in a custom url decoding piece of code. Why is it marked as privet with underscore?

**Comment by asvetlov** [comment]
What do you mean by "custom url decoding"?

**Comment by zokrezyl** [comment]
Tried to keep my description short. Important is that the _match method could be useful as standalone method. I am using it in the following use-case:

-> I have a legacy system that is providing a swagger API description file that contains the endpoint definitions in form from /api/foo/{bar}/detail and the body DTO's that must be provided with the calls to these endpoints
-> The same system is providing as results of the calls to the endpoints something like /api/foo/a_bar/detail and I am matching this url against endpoints listed in the swagger description and for this purpose the _match method was  perfect match :)

**Comment by Dreamsorcerer** [comment]
This could do with some code example of how you're using it.
