### ISSUE TITLE
Auto detection of response body encoding fails

### ISSUE THREAD

**Issue by Tom-Brouwer** [aio-libs/aiohttp#3936]
## Long story short

A request to 'https://researchdata.ands.org.au/registry/services/oai?verb=ListRecords&resumptionToken=eyJsaW1pdCI6MTAwLCJzZXQiOm51bGwsIm9mZnNldCI6NDUxMDAsImZyb20iOm51bGwsInRvIjpudWxsLCJ2ZXJiIjoiTGlzdFJlY29yZHMiLCJtZXRhZGF0YVByZWZpeCI6Im9haV9kYyJ9' fails with a UnicodeError, because the detection of the encoding by chardet (https://github.com/aio-libs/aiohttp/blob/ddba4657162b23de7bca916460486e79c2dfdcfa/aiohttp/client_reqrep.py#L942) is erroneous.

Not only does the chardet function take a long time to run, hampering performance, but it detects 'cp1254' encoding from the body. When the .decode is run in response.text, it raises an error:

```
Traceback (most recent call last):
  File "temp.py", line 19, in <module>
    asyncio.run(do_request())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "temp.py", line 15, in do_request
    text = await resp.text()
  File "/home/brouwer/venvs/dataclopedia/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1012, in text
    return self._body.decode(encoding, errors=errors)  # type: ignore
  File "/usr/lib/python3.7/encodings/cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 19504: character maps to <undefined>
```
## Expected behaviour

As a personal prefence, I'd expect content to be decoded as 'utf-8' by default if no encoding was found, but this may work badly in other cases. Therefore I'd be in favor of making the chardet detection optional, as described here: https://github.com/aio-libs/aiohttp/issues/3705 .

However, it may be better to be in line with the python requests package. There they use the errors='replace' option when decoding, which means the same request works with the python-requests package: https://github.com/psf/requests/blob/589a82256759018a7e5e289302898dae32544949/requests/models.py#L861

## Actual behaviour

It detects the wrong encoding (even though the encoding is even stated in the XML response), and uses errors='strict' (default), meaning a UnicodeDecodeError is raised

## Steps to reproduce
The basic script to reproduce was:
```python
import aiohttp
import asyncio

async def do_request():
    async with aiohttp.ClientSession() as session:
        async with session.get('https://researchdata.ands.org.au/registry/services/oai?verb=ListRecords&resumptionToken=eyJsaW1pdCI6MTAwLCJzZXQiOm51bGwsIm9mZnNldCI6NDUxMDAsImZyb20iOm51bGwsInRvIjpudWxsLCJ2ZXJiIjoiTGlzdFJlY29yZHMiLCJtZXRhZGF0YVByZWZpeCI6Im9haV9kYyJ9') as resp:
            print(resp.status)
            text = await resp.text()
            print(text[:600])
            
if __name__ == "__main__":
    asyncio.run(do_request())
```
However, since the above URL is dynamic, I've saved the bytes response to a
[chardet_fail.txt](https://github.com/aio-libs/aiohttp/files/3427853/chardet_fail.txt). To reproduce the chardet failure:
```python
import chardet

with open('chardet_fail.txt', 'rb') as responsefile:
    response_body = responsefile.read()

encoding = chardet.detect(response_body)['encoding']
# encoding = 'Windows-1254'
response_body.decode(encoding)
# Gives the UniDecodeError
```

## Your environment
Using aoihttp as a client on Ubuntu 18.04, With python 3.7.4, following is pip freeze output:

```
aiohttp==3.5.4
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==19.1.0
certifi==2019.3.9
chardet==3.0.4
dateparser==0.7.1
html2text==2018.1.9
idna==2.8
importlib-metadata==0.18
metadata-ingestion==0.5.8
more-itertools==7.1.0
multidict==4.5.2
packaging==19.0
pluggy==0.12.0
py==1.8.0
pyconvenience==0.3.5
pyparsing==2.4.0
pytest==5.0.1
python-dateutil==2.8.0
pytz==2018.9
PyYAML==5.1.1
regex==2019.3.12
requests==2.21.0
Shapely==1.6.4.post2
six==1.12.0
tzlocal==1.5.1
Unidecode==1.0.23
urllib3==1.24.1
wcwidth==0.1.7
xmltodict==0.12.0
yarl==1.3.0
zipp==0.5.2
```

**Comment by socketpair** [comment]
@asvetlov I would remove encoding guessing. I think, it is wrong way in any case. If sender does not specify encoding -- it's his problem. We may consider utf8. If receiver knows, that sender is wrongly coded or set up, let him to specify expected encoding. Guessing anything is wrong and slow, let it crash if third party components of communications are too stupid.

**Comment by asvetlov** [comment]
`requests` uses `chardet`, that's why aiohttp uses it too.
I suspect if we drop it people start blaming that we don't handle their situation.
`ClientResponse` read accepts `encoding` and `errors` parameters already. 
You can pass `utf-8` explicitly if you are aware of content-encoding.

Switching error mode from `strict` to `replace` implicitly corrupts data without user code notification.
I believe this behavior is wrong.

**Comment by Tom-Brouwer** [comment]
OK, that's clear! I didn't see that 'errors' was a parameter for the .text() function, since it's not (yet?) documented: https://github.com/aio-libs/aiohttp/blob/master/docs/client_reference.rst . For my use case it works to set the errors parameter to 'replace'. 

Given the performance implication of using Chardet, I'd still be in favor of https://github.com/aio-libs/aiohttp/issues/3705. However, my question was answered. Thanks for your response!

**Comment by alonme** [comment]
@asvetlov 
I just encountered this issue when moving one of my components from requests to aiohttp.
I might be wrong to do that, however i look at aiohttp as a drop-in replacement for requests.

Are there many behaviours which are different between the 2 libraries?
For me this is the first point where i feel that they behave differently, as requests uses `errors='replace'` as a default.

I Understand your concern about corrupting the data, however i think that staying in line with requests has its merits.

Also - this is such a main function, with a different behaviour, It might help to have this point stressed out in the documentation.
