### ISSUE TITLE
[TODO] Switch to using tokens for uploading to PyPI

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiohttp#3941]
## Long story short

It is now possible to create an API token at https://pypi.org/manage/account/token/. CI autoreleases should switch to that.

Use `__token__` for a username and the token itself for a password when using Twine: https://github.com/pypa/warehouse/issues/994#issuecomment-512634222

Ref: https://discuss.python.org/t/pypi-security-work-multifactor-auth-progress-help-needed/1042/31

## Expected behaviour

auth token is used for dist upload

## Actual behaviour

user password is used for dist upload

## Steps to reproduce

N/A

## Your environment

N/A

**Comment by webknjaz** [comment]
Showstopper: https://github.com/pypa/warehouse/issues/6262

**Comment by asvetlov** [comment]
Nice! Could you update appveyor config as well?

**Comment by webknjaz** [comment]
Oh, completely forgot about that.
