### ISSUE TITLE
Discussion: drop Python 3.5 support

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3947]
Now aiohttp is Python 3.5 compatible.

The latest Debian Buster (released about 2 weeks ago) has Python 3.7 by default.
RHEL 8 (released on May 7th, 2019) has Python 3.6 by default.

I believe there is no sense in Python 3.5 support for aiohttp 4.0

In #3928 @AMDmi3 expressed an opinion that he is not interested in a contribution for legacy Python version.
In #3946 @ayushkovskiy  used Python 3.6 syntax.
IIRC @samuelcolvin asked for dropping 3.5 a half year ago.

Python 3.5 is in security-fixing mode and going to EOL soon.
 
Do somebody object for Python 3.5 support dropping?
Opinions?

**Comment by kxepal** [comment]
+1 to drop 3.5. Quite soon there will be 3.8, so having 4 Python releases on the support board will be quite expensive (and demotivating).

**Comment by webknjaz** [comment]
Let's drop it w/ aiohttp==4.0. Fedora also has Python 3.7 almost since the day of its release. Ubuntu/Debian will always be PITA. Let the users figure out their problems on their own.

**Comment by yjqiang** [comment]
So the next release would be aiohttp==4.0?

**Comment by webknjaz** [comment]
@yjqiang next *major* release. We'll probably still backport some bugfixes to 3.5, just not features.

**Comment by asvetlov** [comment]
Hmm, there is a blocker called `PyPy`.
PyPy3 3.6 is in beta phase still. aiohttp supports PyPy now, so we cannot drop 3.5 until PyPy3 3.6 will be released :(

**Comment by webknjaz** [comment]
I don't think it's a big deal. PyPy users can keep using `aiohttp<=3.5` until it's ready.

**Comment by asvetlov** [comment]
Do you propose dropping PyPy from travis build matrix for now?

**Comment by webknjaz** [comment]
It should work under pypy3 3.6 beta, which is actually available on Travis
