### ISSUE TITLE
Requests with long responses hang when await is used instead of async with

### ISSUE THREAD

**Issue by ozankabak** [aio-libs/aiohttp#3953]
## Long story short

Requests seem to hang when the response is long.

## Steps to reproduce

Try this code:
```python
import json
import asyncio
import aiohttp

async def get_data(level: int):
    API_URL = 'https://api.pro.coinbase.com'
    async with aiohttp.ClientSession() as session:
        response = await session.get(f'{API_URL}/products/BTC-USD/book',
                                     params = {'level': level})
    content = await response.read()
    if response.status != 200:
        raise RuntimeError()
    return json.loads(content)

print(asyncio.run(get_data(1))) # works
print(asyncio.run(get_data(2))) # works
print(asyncio.run(get_data(3))) # hangs
```
This snippet returns the BTC-USD orderbook from the exchange Coinbase Pro. The `level` parameter controls the amount of data. The calls work for `level` values `1` and `2`, but not `3`. If you do the same request via a browser (or any synchronous library like `requests`), you'll see that it returns a similar type of data (but a much larger amount).

## Your environment

OS: Mac OS X High Sierra
Python version: 3.7.4
aiohttp version: 3.5.4

**Comment by ozankabak** [comment]
Interestingly, if I replace the `await session.get(...)` call with an `async with` block, it works. So the problem only seems to happen if one uses the `await` form.

**Comment by asvetlov** [comment]
Look again on your code:
```
    async with aiohttp.ClientSession() as session:
        response = await session.get(f'{API_URL}/products/BTC-USD/book',
                                     params = {'level': level})
    content = await response.read()
```
You effectively close a session (along with response) on exit from `async with` block.
After that, you are doing `response.read()` which is incorrect.

**Comment by ozankabak** [comment]
Thanks for identifying the issue; my code is clearly not correct. However, I think the proper behavior would be to throw an exception in this case, instead of just hanging.

**Comment by jhaenchen** [comment]
We're seeing hanging when running AWS Lambda across invocations. We suspect the connection is closing when python isn't running. Has there been any progress on throwing an error when a closed connection is used instead of hanging? That's a pretty rough behavior.
