### ISSUE TITLE
Create single ClientSession when use aiohttp as pure client

### ISSUE THREAD

**Issue by lnshi** [aio-libs/aiohttp#3954]
First i read the FAQ and got: [Why is creating a ClientSession outside of an event loop dangerous?](https://docs.aiohttp.org/en/stable/faq.html#why-is-creating-a-clientsession-outside-of-an-event-loop-dangerous)

Then i found something in the docs say: [Persistent session](https://github.com/aio-libs/aiohttp/blob/master/docs/client_advanced.rst#persistent-session)
```
app.cleanup_ctx.append(persistent_session)

async def persistent_session(app):
   app['PERSISTENT_SESSION'] = session = aiohttp.ClientSession()
   yield
   await session.close()

async def my_request_handler(request):
   session = request.app['PERSISTENT_SESSION']
   async with session.get("http://python.org") as resp:
       print(resp.status)
```

But that approach requires me to create `app = Application()`, but my use case is a middleware, **where the aiohttp only perform as a pure HTTP client** (this middleware will run along with some other apps, and other apps will call functions from this middleware, but for processing these function call it needs to do HTTP call to some external services).

So, in this case how should i create and maintain one single `aiohttp.ClientSession`?

**Comment by asvetlov** [comment]
You initialize middleware somewhere anyway, creating a session on initialization stage is a good idea usually.

**Comment by lnshi** [comment]
@asvetlov maybe I shouldn't use the term middleware, it is more like a lib, it will not facing any http/grpc/ws call, just pure direct function call.

I guess I have to init it in the lib initialization phase and use it very carefully with different asyncio event loops?

**Comment by asvetlov** [comment]
> I guess I have to init it in the lib initialization phase and use it very carefully with different asyncio event loops?

Yes.

If you use your library with multiple asyncio loops -- please use a ClientSession per loop at least, everything hangs otherwise.

A session per request is an option if some performance degradation is acceptable for you.

**Comment by lnshi** [comment]
ok, thank u.

**Comment by riaqn** [comment]
Is there some easier way than creating a `Application`? I just need to use the HTTP client, not a whole web server...

**Comment by gorkem2020** [comment]
Hello,

I did not want to create a new issue for this. For some reason I can not get my head around this cleanup_ctx.append feature. I'm using aiohttp purely as a client and making api calls. How can I implement cleanup_ctx into my class here;

```
class AioClient():
    def __init__(self, api_key=None, api_secret=None):
        self.api_key = api_key
        self.api_secret = api_secret
        self.session = self._init_session()
    
    @classmethod
    async def create(cls, api_key=None, api_secret=None):
        self = cls(api_key, api_secret)
        return self
    
    def _get_headers(self):
        return {
            'Accept': 'application/json',
            'Content-Type': 'application/json;charset=utf-8',
        }
    
    def _init_session(self) -> aiohttp.ClientSession:
        return aiohttp.ClientSession(headers=self._get_headers())
    
    async def close_connection(self):
        if self.session:
            await self.session.close()
    
    async def _handle_api_call(self, endpoint, params=None):
        url = f'{_BASE_URL}{endpoint}'
        async with self.session.get(url=url, params=params) as r:
            return await r.json()
    
    async def ping(self):
        endpoint = '/api/ping'
        return await self._handle_api_call(endpoint)
    
    async def get_server_time(self):
        endpoint = '/api/time'
        return await self._handle_api_call(endpoint)
```

So, I replaced '__init_session_' with '_persistent_session'_ and '__handle_api_call_' with '_my_request_handler_'. I have to pass endpoint and parameters so it become '_my_request_handler(self, request, endpoint, params=None)_'

as stated in the documents we are passing a **request** argument. This is where I'm getting confused. what is this request object I'm suppose to pass into function? How do I call request_handler? Below is where I'm at right now, really confused.

```
app = web.Application()

class AioClient():
    def __init__(self, api_key=None, api_secret=None):
        self.api_key = api_key
        self.api_secret = api_secret
        app.cleanup_ctx.append(self.persistent_session)
    
    @classmethod
    async def create(cls, api_key=None, api_secret=None):
        self = cls(api_key, api_secret)
        return self
    
    def _get_headers(self):
        return {
            'Accept': 'application/json',
            'Content-Type': 'application/json;charset=utf-8',
        }
    
    async def persistent_session(self):
        app['PERSISTENT_SESSION'] = session = aiohttp.ClientSession(headers=self._get_headers())
        yield
        await session.close()
    
    async def my_request_handler(self, request, endpoint, params=None):
        url = f'{_BASE_URL}{endpoint}'
        session = request.app['PERSISTENT_SESSION']
        async with session.get(url=url, params=params) as resp:
            return await resp.json()
    
    async def ping(self):
        endpoint = '/api/ping'
        return await self.my_request_handler(endpoint)
    
    async def get_server_time(self):
        endpoint = '/api/time'
        return await self.my_request_handler(endpoint)
```

**Comment by Dreamsorcerer** [comment]
> So, I replaced '__init_session_' with '_persistent_session'_ and '__handle_api_call_' with '_my_request_handler_'. I have to pass endpoint and parameters so it become '_my_request_handler(self, request, endpoint, params=None)_'
> 
> as stated in the documents we are passing a **request** argument. This is where I'm getting confused. what is this request object I'm suppose to pass into function?

Now I'm confused. Are you even writing a web application? A request handler is called to handle a request. It must be registered with the app object using a route, then aiohttp will call the function when handling an incoming request, and will pass a request object. All of this is explained in the tutorial and quickstart for the server side. `my_request_handler()` is not handling a request, it is making a request...

If you're not writing a web application, then none of this is relevant, and I'm not sure what you are trying to do.

-----

If you are writing a web application, then here's a bit more feedback, starting with a recommendation that you read the tutorial: https://demos.aiohttp.org/en/latest/#contents

> For some reason I can not get my head around this cleanup_ctx.append feature.

It's really simple, when the application starts up it will call the functions in here, upto the `yield`. When it shutdowns, it resumes from after the `yield`. It is essentially the same as splitting into 2 functions and putting them on `app.on_startup`/`app.on_cleanup`. The advantage is that the code is kept together, and, e.g. if starting a redis connection fails before the DB connection is started then the app won't try to cleanup the DB connection that doesn't exist yet (which it would if using `app.on_cleanup` as there is no link from the startup task to the cleanup task).

https://docs.aiohttp.org/en/stable/web_advanced.html#cleanup-context

> ```
> app = web.Application()
> 
> class AioClient():
>     def __init__(self, api_key=None, api_secret=None):
>         app.cleanup_ctx.append(self.persistent_session)
> ```

I'd recommend not modifying the app object like this, within the class, or using a global app object at all. Compare the code in our tutorial and demos, and I'd come up with something more like:

```
def init_app():
    app = web.Application()
    app["client"] = AioClient()
    app.cleanup_ctx.append(app["client"].cleanup_ctx)
```

And, as you are trying to encapsulate everything in a class, attach `ClientSession` within the class, not on the app object:

```
    async def cleanup_ctx(self, app):
        self.session = aiohttp.ClientSession(...)
        yield
        await self.session.close()
```

**Comment by gorkem2020** [comment]
thank you! it is more clear now.
