### ISSUE TITLE
Allow gzip compression in high-level server response interface

### ISSUE THREAD

**Issue by danielnelson** [aio-libs/aiohttp#396]
This is a feature request.  The StreamResponse class only allows deflate compression and requires setting the header manually.  It would be useful to allow the use of gzip and perhaps set the header automatically.

I could work on this if you like.  Maybe just a new encoding kwarg to StreamResponse.enable_compression?

**Comment by asvetlov** [comment]
Sounds good!

**Comment by asvetlov** [comment]
Fixed in #403
