### ISSUE TITLE
Cannot get timeout to work consistently

### ISSUE THREAD

**Issue by ebanner** [aio-libs/aiohttp#3963]
## Long story short

Hello! I cannot get timeouts to reliably timeout, as per the code example in [this section](https://docs.aiohttp.org/en/stable/client_quickstart.html#timeouts). Apologies if this turns out to be a user error!

## Expected behaviour

A timeout to be raised when I pass in a very small number for the timeout total value.

## Actual behaviour

Sometimes a timeout is raised and sometimes not.

## Steps to reproduce

Sometimes this script raises a timeout and sometimes it doesn't.

```python
import aiohttp
import asyncio

timeout = aiohttp.ClientTimeout(total=0.00000000000000000001)

async def f():
    async with aiohttp.ClientSession(timeout=timeout) as session:
        await session.get('http://www.google.com')

asyncio.get_event_loop().run_until_complete(
    f()
)
```

I ran the following script and got it to timeout 17/100 times.

```python
import aiohttp
import asyncio
import tqdm

timeout = aiohttp.ClientTimeout(total=0.00000000000000000001)

async def f():
    async with aiohttp.ClientSession(timeout=timeout) as session:
        await session.get('http://www.google.com')

i = 0
async def outer():
    global i
    for _ in tqdm.tqdm(range(100)):
        try:
            await f()
        except Exception as e:
            i += 1

asyncio.get_event_loop().run_until_complete(
    outer()
)

print(i)
```

## Your environment

client

```
aiohttp==3.5.4
```

macOS High Sierra 10.13.6

## Additional notes

I have a production service which specified a timeout value of .2 seconds for http.post calls that took upwards of 2.5 seconds before timing out, so if the timeout value I specified in this issue seems comically small, then please do not dismiss it right away. :)

**Comment by thehesiod** [comment]
It will help them investigate if you specify the version of Python and if this is a regression by testing a couple old minor versions of aiohttp like 3.2 + 3.3. may want to try Python 3.6 + 3.7 due to tight integration between the two.

**Comment by wumpus** [comment]
Looks like the timeout implementation is a "best effort" sort of thing, so if your event loop is very busy, it won't be called anywhere near the expected time. And your test is very unlike your actual program.

To see how busy your event loop is, set up an extra asyncio task and have it call `await asyncio.sleep(1.0)` while measuring the elapsed time. If you see that take 2.5 seconds, then you should expect the aiohttp timeout to also take 2.5 seconds.

**Comment by webknjaz** [comment]
https://github.com/aio-libs/aiohttp/issues/4037#issuecomment-528752565

**Comment by ebanner** [comment]
Thanks! This is probably not an issue with `aiohttp` and rather a limitation of the event loop itself, as you say, so I'll close it.
