### ISSUE TITLE
Raising exceptions from View class constructor cause hanging database session

### ISSUE THREAD

**Issue by remort** [aio-libs/aiohttp#3969]
## The issue
I need check some request parameters on a group of handlers. If request data is wrong I need to send REST API response to frontend with error message. Usually I do this via `return json_response()` in View handlers. But I am unable to return or await fron View constructor. So I extended `HTTPClientError` to raise it and return a REST-like JSON HTTP response to frontend. Here's the code:

```
class ForbiddenError(HTTPClientError):
    status_code = 542

    def __init__(self, body):
        super(ForbiddenError, self).__init__(
            text=json.dumps({'error': body}),
            headers={'content-type': 'application/json'}
        )
```

But my unit tests failed after I implemented this. Tests fail because data won't be cleaned fron DB. There are no db errors (commit failures or SQL issues). Database seems to be clean between running tests. But some tests fail because of pre-existing data from previous tests.

Digging deeper I spotted the `bad unit test` which somehow breaks the DB things. This test was checking this API error based on raising exception in View constrictor.

Constructor code:
```
class SomeBaseHandler(View):
    def __init__(self, request):
        super().__init__(request)
        self.user: User = self.request['user']
        self.db: DBSession = self.request.app['db_session']

        ...some sanity checks are being made here...
            raise ForbiddenError('error_message_for_frontend')
```
Long story short - problem gone when I put `self.db.close()` right before the exception raising. It seems that View somehow holds DB connection, not freeing it upon raising.

## Expected behaviour

Free database connection (and may be other resourses) upon raising HTTPError based exception from View constructor not causing this resourses to hang.

## Actual behaviour

Database connection seems to hang without any errors in logs but provide old data.

## Steps to reproduce
See issue description above

## Your environment
aiohttp server under gunicorn in python 3.7 debian-slim docker container
postgres in `11-alpine` container

Basic packages in python container:
aiohttp 3.5.4
sqlalchemy 1.2.14
psycopg2-binary 2.8.3
gunicorn 19.9.0
pytest 5.0.1

Unitests do not use aiohttp application, are synchronous and use `requests` library to make http-requests to real application run in container with clean DB adding and removing fixtures from one test class to another (via unittest's setUpClass, tearDownClass)

**Comment by remort** [comment]
Update:
Issue is reproducible with a following minimum View constructor code: 
```
class SomeBaseHandler(View):
    def __init__(self, request):
        super().__init__(request)
        self.request.app['db_session'].close() # DB Session hangs or whatsoever if I remove this string.
        raise ForbiddenError('error_message_for_frontend')
```

Making and returning app for gunicorn:
```
async def http_app_factory()
    loop = asyncio.get_event_loop()
    app['db_session']: DBSession = db_session
    app: Application = Application(loop=loop, middlewares=[
        session_middleware(RedisStorage(redis_pool)),
    ])
    ... route definitions ...
    return app
```

Connecting to postgres via sqlalchemy (yes, synchronously)
```
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm.session import Session

db = create_engine(DB_URI)
Session = sessionmaker(bind=db)
db_session = Session()
```

**Comment by socketpair** [comment]
1. log current PID and `threading.get_ident()` both from the constructor and from the handler. They should match.
2. log these values also from the place where you connect to DB.

Note: It's not allowed to use the same TCP connection to Postgres/Redis/e.t.c. from cloned processes.

**Comment by remort** [comment]
thread id: 139824510596864, pid: 0 at handler, it's constructor and database connector.
At application runner code, where I put DB connector to app object, thread id is the same (139824510596864) but pid is 43 which is gunicorn. Process tree inside of container:

![изображение](https://user-images.githubusercontent.com/1863452/62760944-b7a2a700-ba9e-11e9-86a0-c3baa4af3d39.png)

**Comment by remort** [comment]
I moved the code with exception raise to handler itself. Got rid of constructor for a while. The issue still persists: I steel need to close db connection manually before raise. In the same View I can just return `json_response` or `Response` without closing database connection.

I suppose the thing is about how raise works, despite that all Aiohttp exceptions subclasses `HTTPException` which subclasses `Response` and **should** work in the same manner.

**Comment by socketpair** [comment]
It's not allowed to work with DB if it's connection made in different process.

**Comment by remort** [comment]
So, now it seems that the question is: what is the proper way to share DB connection between handlers if handlers are being spawned under subprocesses by wsgi server (such as gunicorn).

Gunicorn set to use native `aiohttp.GunicornWebWorker` workers, which *states* that Gunicorn aiohttp compatible.

Thank you, @socketpair. Nice to hear from you ))

**Comment by socketpair** [comment]
It depends. For example, prefork + init db in each fork. I'm not familiar with gunicorn, but sharing one db connection between coroutines of a single process is also a bad idea. You need some form of connection pooling. Before starting a transaction, app should ask pool for the connection. You have to make a pool per process.

Or, better, ask someone who has better experience in that.
