### ISSUE TITLE
aiohttp.get returns None, while requests.get returns JSON

### ISSUE THREAD

**Issue by amosbastian** [aio-libs/aiohttp#3973]
## Long story short

Trying to get a JSON object by sending a GET request to e.g. [this url](https://fantasy.premierleague.com/api/entry/91928/), but it returns `None`.

## Expected behaviour

I expect JSON object to be returned instead of `None`.

## Actual behaviour

`None` is returned.

## Steps to reproduce

For example:

```python
import aiohttp
import asyncio


async def fetch(session, url):
    async with session.get(url) as response:
        return await response.json()


async def main():
    async with aiohttp.ClientSession() as session:
        url = "https://fantasy.premierleague.com/api/entry/91928/"
        entry = await fetch(session, url)

        print(entry)


if __name__ == "__main__":
    asyncio.run(main())
```

The above code prints `None`, but should print whatever you see when visiting [the URL](https://fantasy.premierleague.com/api/entry/91928/) in a browser for example.

Using Requests it works fine and the correct response is printed:

```python
import requests


def main():
    url = "https://fantasy.premierleague.com/api/entry/91928/"
    entry = requests.get(url)

    print(entry.json())


if __name__ == "__main__":
    main()
```

Not sure what is going on -- have been on holiday recently and my programming is a bit rusty, which could mean I'm missing something obvious, so bear with me. Substituting the URL in the examples with e.g. https://api.github.com/events makes it work fine, so my guess there is something iffy going on that is specific to the Fantasy Premier League API.

## Your environment

Using aiohttp version 3.5.4 with Python 3.7.3 on Ubuntu 18.04.3 LTS.

**Comment by amosbastian** [comment]
Just needed to set User-Agent header...

**Comment by 14iq** [comment]
> Just needed to set User-Agent header...

Не работает сука! Ебаный пендос опять напиздел...
