### ISSUE TITLE
 File URI scheme support?

### ISSUE THREAD

**Issue by etingof** [aio-libs/aiohttp#3978]
In my application, I want to read local files alongside the REST API calls against networked servers. Looking at the code, I do not think that `file://` schema (as per RFC8089) is supported by `aiohttp`, is that correct?

In `requests`, there is a way to "mount" custom handlers what would be a way to implement local file reading. I am wondering, what would be the best approach to achieve similar functionality with `aiohttp`?

I understand that reading local files has nothing to do with async I/O, though.

Thanks!

**Comment by asvetlov** [comment]
`mount` feature is awesome.
aiohttp has no competitive functionality yet, unfortunately.

**Comment by Yay295** [comment]
Why was this closed? Is there no plan to add this feature?
