### ISSUE TITLE
Use sendfile in StaticHandler

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#398]
see tornadoweb/tornado#1448

**Comment by GomZik** [comment]
Can I try to make this task?

**Comment by asvetlov** [comment]
Please do. But keep in mind: 
1. RANGE support #165 should be implemented first 
2. sendfile should be optional, if the function is not supported by platform (e.g. Windows) fallback to conventional way.

**Comment by jashandeep-sohi** [comment]
I'm working on this in https://github.com/KeepSafe/aiohttp/pull/503. Feedback welcome.

**Comment by asvetlov** [comment]
Fixed by #503
