### ISSUE TITLE
How do you catch errors from aiohttp client?

### ISSUE THREAD

**Issue by tedivm** [aio-libs/aiohttp#4001]
## Long story short

I've tried everything but it seems like aiohttp errors are impossible to catch.

```python
    try:
        return await infer.health()
    except aiohttp.ClientConnectorError as e:
        raise HTTPException(status_code=503, detail="Tensorflow Serving is still loading.")
```
I've tried every possible combination of `aiohttp.ClientConnectorError`, (including `aiohttp.client_exceptions.ClientConnectorError` and `aiohttp.ClientError`) but nothing catches this exception.

## Expected behaviour

That the exception is caught.

## Actual behaviour

The connection is not caught, and instead `aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:8501 ssl:None [Connection refused]` gets pushed to the top.

## Steps to reproduce

Code is above.

## Your environment

python3.7 with a fresh install of aiohttp in a docker container.

**Comment by webknjaz** [comment]
@tedivm have you tried doing `except Exception as exc:` block and putting a breakpoint there in order to inspect the type of `exc`?

**Comment by mjpieters** [comment]
Can you provide a more complete example that reproduces the problem? Please include a full traceback. You did restart Python to rub with the updated source code, right?

**Comment by tedivm** [comment]
@mjpieters could you share an example of any working code that catches a client connection error (such as a timeout)?

**Comment by mjpieters** [comment]
The syntax you showed is the correct way to catch exceptions so something else is wrong. Without a more complete reproducible example and traceback we can’t determine what exactly is going wrong on your side. Sorry.

**Comment by tedivm** [comment]
For anyone else who finds this issue via Google I've gone ahead and opened a new issue with the requested stack traces and test scripts. You can find that issue at #4064.
