### ISSUE TITLE
ws:// scheme

### ISSUE THREAD

**Issue by Ripmycode** [aio-libs/aiohttp#4003]
## Long story short
I've read the whole documentation and I don't find anyway to serve websockets using ws:// url scheme.

Why is this important? 
When you're building a server for a specific client (e.g. proxy) and the client requires you to use ws:// (e.g. ws://username:password@127.0.0.1:54321) scheme we can't implement this kind of application using aiohttp

## Your environment
Python 3.7

**Comment by asvetlov** [comment]
In what aiohttp API calls do you want to support `ws` scheme?

**Comment by asvetlov** [comment]
Closing the issue due the lack of interest from @Ripmycode
