### ISSUE TITLE
why is aiohttp fast when writing bytes is blocking?

### ISSUE THREAD

**Issue by EltonZhong** [aio-libs/aiohttp#4007]
## Long story short
Question: 
why is aiohttp fast when writing bytes is blocking?
When I trace the source code of aiohttp, I find that when sending bytes, it calls `self._transport.write(chunk)`, which is blocking.
Since I'm new to python asyncio, I don't know why the system io is blocking, unlike node.js

Node.js use libuv to impl async operations, like fs.open('file', callback)
which is asynchronous.
But code like `self._transport.write(chunk)` is obviously blocking, and async io share same thread when executing tasks in queque, so I don't know why aiohttp is faster than multi-thread programing.

![image](https://user-images.githubusercontent.com/20570738/63739195-fe760680-c8be-11e9-86cf-e3cc59229582.png)

Also I don't know why other asyncio fast when io operations are blocking, not using system apis like epoll & select. Is there any points I'm missing?
Thank you.

**Comment by socketpair** [comment]
For sockets, there is so-called non-blocking IO. Asyncio/aiohttp both use it with select/poll/epoll. In Linux, it's impossible to make non-blocking IO with plain files. That's why NodeJS uses threads to implement asynchornous IO with files.

**Comment by EltonZhong** [comment]
> For sockets, there is so-called non-blocking IO. Asyncio/aiohttp both use it with select/poll/epoll. In Linux, it's impossible to make non-blocking IO with plain files. That's why NodeJS uses threads to implement asynchornous IO with files.

`Asyncio/aiohttp both use it with select/poll/epoll` As I see, even though the bot io uses epoll, it's still blocking when a coroutine waits for the socket file descriptor to be ready. So it's synchronize programmably,  right?
Thanks.

**Comment by LiangZZZ123** [comment]
> > For sockets, there is so-called non-blocking IO. Asyncio/aiohttp both use it with select/poll/epoll. In Linux, it's impossible to make non-blocking IO with plain files. That's why NodeJS uses threads to implement asynchornous IO with files.
> 
> `Asyncio/aiohttp both use it with select/poll/epoll` As I see, even though the bot io uses epoll, it's still blocking when a coroutine waits for the socket file descriptor to be ready. So it's synchronize programmably, right?
> Thanks.

1. On socket level, you write data to cache in RAM, which is really fast, so called "non-blocking IO", it is actually blocking, but so fast, like the blocking time is negilible.
2. On system level, you write data to harddisk, blocking and slow.
