### ISSUE TITLE
How to send/post encoded image to server side and extract the same?

### ISSUE THREAD

**Issue by SaddamBInSyed** [aio-libs/aiohttp#4008]
Hi.
 I am new to AIOHttp library

I am trying to send encoded image using the below code, but I couldn't get back the same at the aioHttp server side.

**CLIENT SIDE**
```python
import asyncio
import random
import requests

async def sendreq(buffer):   
    jpg_as_text = base64.b64encode(buffer)
    async with session.post(url, json=json.dumps({'img': str(jpg_as_text)})) as resp:
        print(resp.status)
        print(await resp.text())

async def main():
    tasks = []
   b64buffer = ' opencv will fill this value.'
    for i in range(10):
        tasks.append(asyncio.ensure_future(sendreq(b64buffer)))

    await asyncio.gather(*tasks)


loop = asyncio.get_event_loop()
try:
    loop.run_until_complete(main())
finally:
    loop.close()
```
**SERVER SIDE:**
```python
async def identify_faces(request):
    try:
        jpg_as_text = await request.json()
**# I AM GETTING ERROR HERE. I DONT KNOW HOW TO READ THE B64IMAGE DATA**
        imdata = json.load(jpg_as_text)
        jpg_original = base64.b64decode(imdata['img'])
        jpg_as_np = np.frombuffer(jpg_original, dtype=np.uint8)

    except Exception as e:
        print(e)
        # Bad path where name is not set
        response_obj = { 'status' : 'failed', 'reason': str(e) }
        # return failed with a status code of 500 i.e. 'Server Error'
        return web.Response(text=json.dumps(response_obj), status=200)
```
please advise me, HOW TO SEND A ENCODED IMAGE and RX AT THE SERVER SIDE?

Please help me, bcz since 2 days I am hitting my head.

**Comment by webknjaz** [comment]
> json=json.dumps(

You don't have to pass a string there. Just pass an object. 

> **# I AM GETTING ERROR HERE. I DONT KNOW HOW TO READ THE B64IMAGE DATA**

https://docs.python.org/3/

**Comment by SaddamBInSyed** [comment]
Thanks for the reply.

but How do I unpack the same at Server side? ( I am getting an error there, even after sending object instead of string)

highly appreciated your sample code on this

I am using this library first time.  In  the same concept working fine with FLASK.

**Comment by asvetlov** [comment]
I'm sorry but this bug tracker is not a Q/A site like https://stackoverflow.com
Looking on the code I see that instead of `jpg_as_text = await request.json()` should be
```
imdata = await request.json()
b64buffer = dct['img']
```
