### ISSUE TITLE
Maybe deprecate all HTTP 2xx responses that inherit from HTTPException?

### ISSUE THREAD

**Issue by atemate** [aio-libs/aiohttp#4017]
## Long story short

By name, `HTTPOk` is a valid HTTP response with status code 200, thus a user expects to `return web.HTTPOk()` in a handler:
```
async def test_http_ok(aiohttp_client) -> None:
    async def handler(request: web.Request) -> web.Response:
        return web.HTTPOk()

    app = web.Application()
    app.router.add_get("/", handler)

    app_client = await aiohttp_client(app)
    async with app_client.get("/") as resp:
        assert resp.status == 200, await resp.text()
```

However, the exception is thrown here:
```
...
>       async with app_client.get("/") as resp:
...
aiohttp.client_exceptions.ServerDisconnectedError: None
...
```
And since `HTTPOk` inherits from `HTTPException`, the user gets also the deprecation warning, which might confuse until one digs into implementation of `HTTPOk`:
```
DeprecationWarning: returning HTTPException object is deprecated (#2415) and will be removed, please raise the exception instead
```

I think, it's better to deprecate all `HTTPException` subclasses of `2xx` status codes.

## Expected behaviour
In server's handler: `return web.HTTPOk()` either behaves same as `return web.Response()` or is deprecated with reasonable message.

## Actual behaviour

`return web.HTTPOk()` does not work and unclear deprecation warning received.

## Steps to reproduce

see code snippet above

## Your environment
```
$ uname -a
Linux archlinux 5.2.6-arch1-1-ARCH #1 SMP PREEMPT Sun Aug 4 14:58:49 UTC 2019 x86_64 GNU/Linux
$ pip list | grep aiohttp
aiohttp            3.5.4                         
pytest-aiohttp     0.3.0  
```

**Comment by asvetlov** [comment]
1. What do you propose to do with *202 Created* or *206 Partial Content*?
2. Following your logic *303 See Other* is also a valid response (and it is).
3. On aiohttp master returning http exception is forbidden entirely, please check the code.

**Comment by webknjaz** [comment]
For the reference: in CherryPy we inherit only 4xx/5xx from HTTPError but 3xx are still implemented via exception raising, they just have a different exception base.

https://github.com/cherrypy/cherrypy/blob/b68087d/cherrypy/_cperror.py

**Comment by webknjaz** [comment]
Flask, OTOH, implements redirects via returning a helper-constructed response object while errors use a generic exception class.

- https://github.com/pallets/werkzeug/blob/e197df1/src/werkzeug/utils.py#L490-L531
- https://github.com/pallets/werkzeug/blob/e197df1/src/werkzeug/exceptions.py#L746-L789

**Comment by webknjaz** [comment]
The advantage is using exceptions for errors and redirects is that they can bubble up the stack making it possible to terminate request processing from the middle of some deeply nested logic.

**Comment by asvetlov** [comment]
@webknjaz you are right, raising redirection bubbles up, that's why we use this design.
Since HTTPException is not inherited from a response since aiohttp 4.0 the issue is gone I think.

We can add helpers like
```
def found(location):
    raise HTTPFound(location)
```
I doubt if blowing up the API worth it.

**Comment by samuelcolvin** [comment]
> I doubt if blowing up the API worth it.

Agree, any other approach would be more complex and opaque .

**Comment by webknjaz** [comment]
> I doubt if blowing up the API worth it.

Yeah. It's not worth it...
