### ISSUE TITLE
i686 manylinux build fails due to missing cryptography wheel

### ISSUE THREAD

**Issue by mjpieters** [aio-libs/aiohttp#4018]
The manylinux build step fails for arch="i686", as there is no `manylinux1_i686` wheel for `cryptography` version 2.7.

I filed pyca/cryptography#4978 to ask why no wheel is available.

This ticket is mostly to track the issue on the aiohttp side, but it may be that cryptography has to be downgraded to 2.6.1 if new aiohttp wheels need to be built (the cryptography dependency is only needed to run the tests, I think).

**Comment by mjpieters** [comment]
The project dropped support for 32 bit wheels on purpose. So the options are

- beef up the docker image so cryptography can be compiled on it
- find an alternative source for i686 wheels
- accept that tests are run with an older version of cryptography 
- drop i686 wheel support for aiohttp

**Comment by webknjaz** [comment]
We don't depend on cryptography directly.

**Comment by webknjaz** [comment]
Also, if cryptography has its metadata properly set up, Pip will just pick a previous version matching the env.

**Comment by mjpieters** [comment]
> We don't depend on cryptography directly.

No, but the build process *does*. This is about the aiohttp Travis build process being affected, because the `ci-wheel.txt` requirements file pins the version:

https://github.com/aio-libs/aiohttp/blob/4a2308a64af8c4aa704286a2f490d411c84588b6/requirements/ci-wheel.txt#L16

So *at the very least* that should be unpinned, if pip should be picking up a previous version.

**Comment by webknjaz** [comment]
Ah, yeah. Env deps are pinned which is controlled by dependabot. I'd use env markers for this case. Not sure whether the bot knows how to ignore certain lines.

**Comment by mjpieters** [comment]
The lines with environment markers appear to be ignored already; dependabot hasn't made a suggestion to upgrade typing_extensions to 3.7.4 either, for example.

**Comment by webknjaz** [comment]
Okay, mind sending a PR with markers?

https://github.com/dependabot/feedback/issues/658
