### ISSUE TITLE
kwargs for add_route -> Custom attributes for the route

### ISSUE THREAD

**Issue by lennart-k** [aio-libs/aiohttp#4019]
## Long story short

I'd like to give my API routes a scope attributes so that I can have a middleware check for authorization.

## Actual behaviour

My current approach would be either to create a wrapper for the handler with a decorator or to fork web_urldispatcher.py.
I feel like both approaches are pretty horrible.

## Steps to reproduce

Imagine something like this:
```py
r = web.RouteTableDef()

@r.get("GET", "/ping", scopes=["no_authentication"])
async def ping(request: web.Request) -> web.Response:
	...

# Middleware
async def middleware(request: web.Request, handler) -> web.Response:
    scopes = request.route.scopes
    # or maybe
	scopes = request.route.data.scopes
```

Btw I'm aware that this issue is quite similar to #2038 but I think while `functools.partial` is a fine solution to pass arguments to the handler,
a wrapper is quite a bad solution in my case as this solution does not let me add my middleware to the app's middleware chain.

**Comment by asvetlov** [comment]
I have a bad guts-feeling on adding random named fields as proposed here.

The problem can be solved with current aiohttp release though:
```
r = web.RouteTableDef()

@r.get("GET", "/ping")
async def ping(request: web.Request) -> web.Response:
	...

ping.scopes=["no_authentication"]

# Middleware
async def middleware(request: web.Request, handler) -> web.Response:
    scopes = getattr(request.match_info.handler, [])
```
