### ISSUE TITLE
Travis OS X builds: Avoid relying on old XCode images and PyEnv

### ISSUE THREAD

**Issue by mjpieters** [aio-libs/aiohttp#4028]
I'm extracting this from #4020 into a separate issue, where I should have put it to begin with.

(When unbroken, e.g. by #4020) the OS X jobs are both slow and rely on using no-longer-supported XCode images (the Travis banner intones that 6.4 is to go away in January 2019, so 8 months ago).

There is not real need to use old XCode versions, newer XCode versions are quite happy to use older SDK versions to build against. In fact, the SDK release defaults to the SDK that was used for the Python binary that is running the build.

If you download an official Python.org OS X build then you end up building a corresponding wheel version, without the need to switch XCode images. See the [*Wheel Building* page](https://github.com/MacPython/wiki/wiki/Wheel-building) on the MacPython Wiki. The [multibuild project](https://github.com/matthew-brett/multibuild) follows this approach and outputs *combined* wheels. For a given Python version, a single wheel bundling all SDK variants is created, e.g. the matplotlib project has [`..._macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl` wheels](https://pypi.org/project/matplotlib/3.1.1/#copy-hash-modal-17ab0ed9-407a-4334-bac3-1447b7ef8745).

Moreover, this would also be faster than having PyEnv build Python for us.

Next, the `multibuild` project would also make integrating OS X into a matrix (with or without a separate stage) easier as it already has all the scripts to distinguish between platforms. The For examples of this, see how the travis configs of other Python projects use this:

* [Pillow](https://github.com/radarhere/pillow-wheels/blob/d5f36a1544fe0fd47e5209fe033f50abed2d9425/.travis.yml#L183-L195)
* [Matplotlib](https://github.com/MacPython/matplotlib-wheels/blob/73a9f41f9050d3f9f452ea04cf1b939dadaf1ca5/.travis.yml#L78-L107)
* and [many, many more](https://github.com/search?q=multibuild%2Fcommon_utils.sh+filename%3A.travis.yml&type=Code)

@webknjaz also pointed to `dukpy/.travis.yml` as it too downloads Mac Python builds, see [these lines](https://github.com/amol-/dukpy/blob/69f56f3/.travis.yml#L41-L120). My personal view is that using `multibuild` means we'd share the maintenance burden of keeping this working with loads of other Python projects. That said, I like the way that piece of code uses github tags to guide what Python versions to probe for where `multibuild` has hardcoded these.

**Comment by asvetlov** [comment]
@mjpieters I very appreciate your contribution.
Personally I have no MacOSX available, I'm Linux guy who can execute Windows in VirtualBox if needed.
I don't know MacOS infrastructure etc. If *multibuild project* can help us a lot -- please feel free to use it.

**Comment by webknjaz** [comment]
@asvetlov I'm aware of multibuild and was trying to experiment with it. It looks like an overkill currently. Yet, it may be interesting to extract some techniques from there. My main concern is that it has too much logic which is hidden by a few levels of file includes and I prefer to see all the config right in `.travis.yml` where it's easier to reason about. Also, this is a dependency on something that we don't control meaning that it's hard to combine it with customizations.

@mjpieters we have an example of such "combined" wheels @ https://github.com/aio-libs/multidict/blob/e496ecf/setup.py#L117-L218. I have a lot of improvements in my mind but haven't had time to implement those.
Currently, I'm not ready to drop-in multibuild here but it's on my list to explore its source and see how it fits. And yes, I implemented a better Python version lookup there in dukpy so that'd need to be contributed to multibuild too, before usage :)
One more note on the combined osx wheels: I've hit certain file name length limits, that's why I've implemented wheel splitting in multidict.

P.S. One of the things missing is that we currently don't use `delocate` for OS X as we do with auditwheel for manylinux. It'd be interested in seeing that implemented.

In general, the idea with all of these improvements is first to battle-test them on multidict and yarl repos. @mjpieters would you be interested in trying to help with those first?

**Comment by mjpieters** [comment]
> In general, the idea with all of these improvements is first to battle-test them on multidict and yarl repos. @mjpieters would you be interested in trying to help with those first?

I’ve been doing just that over in [mjpieters/frozenlist](/mjpieters/frozenlist), and it has [successfully built and uploaded wheels](https://travis-ci.com/mjpieters/frozenlist/builds/125329092). The only thing missing on my pull request here is the explicit pip upgrade (see mjpieters/frozenlist@3fa72c60b552eb20d66472b7780edced23e567e8).

I’ll be away next week and have to prep for PyCon UK so don’t have more time right now to hack on more travis builds unfortunately.

> My main concern is that it has too much logic which is hidden by a few levels of file includes and I prefer to see all the config right in .travis.yml where it's easier to reason about. Also, this is a dependency on something that we don't control meaning that it's hard to combine it with customizations.

I much prefer the encapsulation actually. The scripts are clearly named and so help make the it much easier for novices to help out with simpler maintenance tasks.

Next, it is being used by projects with very complex dependencies [like numpy](https://github.com/MacPython/numpy-wheels). And last but not least is gets a lot more eyeballs so future build challenges can be solved all the more effectively. 

> One more note on the combined osx wheels: I've hit certain file name length limits, that's why I've implemented wheel splitting in multidict.

Interesting, what kind of limits? Do you think these would affect multibuild wheels?

**Comment by webknjaz** [comment]
> what kind of limits

Look at https://pypi.org/project/multidict/#files. There's three wheels per each Python version under macOS:
* `multidict-4.5.2-cp37-cp37m-macosx_10_12_intel.macosx_10_12_x86_64.macosx_10_13_intel.macosx_10_13_x86_64.whl`
* `multidict-4.5.2-cp37-cp37m-macosx_10_6_intel.macosx_10_6_x86_64.macosx_10_7_intel.macosx_10_7_x86_64.macosx_10_8_intel.macosx_10_8_x86_64.whl`
* `multidict-4.5.2-cp37-cp37m-macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.macosx_10_11_intel.macosx_10_11_x86_64.whl`

I tried creating a single wheel with all the tags in it (`multidict-4.5.2-cp37-cp37m-macosx_10_6_intel.macosx_10_6_x86_64.macosx_10_7_intel.macosx_10_7_x86_64.macosx_10_8_intel.macosx_10_8_x86_64.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.macosx_10_11_intel.macosx_10_11_x86_64.macosx_10_12_intel.macosx_10_12_x86_64.macosx_10_13_intel.macosx_10_13_x86_64.whl`) but hit some error raised by setuptools of maybe some fs operations (I don't remember exactly, it was a year ago)

**Comment by mjpieters** [comment]
I think you are targeting too many SDK versions. You really only need 10.6 (intel), 10.9 (intel and x86_64), to be useful to 99.9% of Mac / Python combos. Multibuild [splices in a 10.10 tag to support pip <= 6](https://github.com/matthew-brett/multibuild/blob/951b6c64f01853cf2569000bb30ecd01a16bba0b/osx_utils.sh#L321-L328) but that’s clearly overkill nowadays. 

Scanning through the https://pythonwheels.com projects multidict appears to be the only project with that much SDK coverage. Numpy now [only builds 10.9 64-bit wheels even](https://github.com/MacPython/numpy-wheels/commit/d97e7bf7dcd7d50eb9813f8c659b5fbdd89839eb#diff-354f30a63fb0907d4ad57269548329e3) and there are one or two projects with an unusual SDK choice  (e.g. uvloop has only 10.11 64-bit wheels) but the majority stick to some combination of 10.6 and 10.9.

**Comment by webknjaz** [comment]
Yeah, I know. But I also got an impression that not everyone was thinking about supporting that much cases. I think that I decided to go this way after some testing on macs available to me. Also, I've found out that tags would also depend on the way the Python interpreter was installed. Like official package from python.org vs. brew vs. pyenv.
I don't remember the exact details but I found some corner cases in some of those envs. So I decided that it's better safe than sorry, especially given that macs are usually a weapon of choice for a lot of devs and dev env better have good UX.
I hope this makes sense.

**Comment by mjpieters** [comment]
> But I also got an impression that not everyone was thinking about supporting that much cases.

They did, see the [_Spinning Wheels_ page](https://github.com/MacPython/wiki/wiki/Spinning-wheels). They cover the various platform options too.

The `multidict-4.5.2-cp37-cp37m-macosx_10_12_intel.macosx_10_12_x86_64.macosx_10_13_intel.macosx_10_13_x86_64.whl` wheel is really no different from the `multidict-4.5.2-cp37-cp37m-macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.macosx_10_11_intel.macosx_10_11_x86_64.whl` wheel, and the latter will work perfectly fine on OSX 10.9, 10.10, 10.11, 10.12, 10.13 and 10.14.

> I don't remember the exact details but I found some corner cases in some of those envs. So I decided that it's better safe than sorry, especially given that macs are usually a weapon of choice for a lot of devs and dev env better have good UX.

We don't need to build wheels for every possible combination. Rather, we should make sure `aiohttp` installable from the source distribution given a reasonable compilation toolchain. If you have a developer mac with homebrew, you have such a toolchain.

And indeed, it can be installed like that:

```sh
$ pip install --no-binary=aiohttp aiohttp
Collecting aiohttp
  Using cached https://files.pythonhosted.org/packages/0f/58/c8b83f999da3b13e66249ea32f325be923791c0c10aee6cf16002a3effc1/aiohttp-3.5.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting chardet<4.0,>=2.0 (from aiohttp)
Collecting async-timeout<4.0,>=3.0 (from aiohttp)
  Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp)
Collecting multidict<5.0,>=4.0 (from aiohttp)
  Using cached https://files.pythonhosted.org/packages/0e/64/39b167d63e292cc2336d09c4d3577089db82cd7886ed535b6100fc7c7966/multidict-4.5.2-cp37-cp37m-macosx_10_12_intel.macosx_10_12_x86_64.macosx_10_13_intel.macosx_10_13_x86_64.whl
Collecting attrs>=17.3.0 (from aiohttp)
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp)
Skipping bdist_wheel for aiohttp, due to binaries being disabled for it.
Installing collected packages: chardet, async-timeout, idna, multidict, yarl, attrs, aiohttp
  Running setup.py install for aiohttp ... done
Successfully installed aiohttp-3.5.4 async-timeout-3.0.1 attrs-19.1.0 chardet-3.0.4 idna-2.8 multidict-4.5.2 yarl-1.3.0
```

**Comment by webknjaz** [comment]
In this case, they'll catch weird toolchain-related bugs because something's different on their side. I really don't think that users should care about compiling stuff unless it's their goal.

**Comment by mjpieters** [comment]
I do think that the number of users in that situation is far smaller than you think it is, and we should not try to provide wheels for every possible combination and scenario.

**Comment by webknjaz** [comment]
Alright, makes sense.

**Comment by webknjaz** [comment]
Closing since we abandoned Travis CI.
