### ISSUE TITLE
Trying to mimic a Postman POST with formData, can't get it to work

### ISSUE THREAD

**Issue by emptyopen** [aio-libs/aiohttp#4038]
## Long story short

I'm trying to send form data to Strapi with Python and aiohttp, but get a 400 error. Not sure how my Python code is different than my Postman request. Basically wondering what the difference is between my Python code and my Postman request. 

## Expected behaviour

200 response. (I can get a 200 response with Postman). 

## Actual behaviour

400 response. 

## Steps to reproduce

I can successfully send a file with Postman. The header is just an Authentication token. 
![image](https://user-images.githubusercontent.com/18575100/64280290-a1ed9980-cf05-11e9-96b3-26913206a201.png)

However, when I try and mimic this request in Python, I get a 400 response: 

> [2019-09-04T17:55:24.552Z] error Error: invalid JSON, only supports object and array
>     at parse (/home/ubuntu/project.strapi/node_modules/co-body/lib/json.js:60:13)
>     at /home/ubuntu/project.strapi/node_modules/co-body/lib/json.js:45:22
>     at process._tickCallback (internal/process/next_tick.js:68:7)

Here's my code:

```
async with aiohttp.ClientSession() as session:
            if not path.exists(filepath):
                self.logger.log('Invalid filepath.')
                raise Exception('Invalid filepath.')
            body = aiohttp.formdata.FormData()
            body.add_field('files', filepath, filename=f'{filepath}', content_type='application/json')
            resp = await session.post(url=self.ip_address + '/upload',
                                      headers={'Content-Type': 'application/json',
                                               'Authorization': f'Bearer {self.jwt}'},
                                      data=body)
            resp.raise_for_status()
            html = await resp.text()
            return html
```

I've tried a number of variations trying to load/dump the data/body with json, but nothing has worked so far. 

## Your environment

aiohttp==3.5.4
MacOS

**Comment by asvetlov** [comment]
Sorry, I never used Postman.
Your question is out of aiohttp project scope.
Looking on the error and can guess that you have to pass json for `application/json`, not multipart encoded body.
See http://docs.aiohttp.org/en/stable/client_quickstart.html#json-request for instructions how to do that.

If you need multipart actually -- use proper content type for this.

**Comment by thaikoh** [comment]
Hi
I'm having similar problem. I have API endpoint which accepts POST and requires some params in request body and also a file. When I try yo send like this:
```
form_data = aiohttp.FormData()
form_data.add_field('store_id', store_id)
async with self.session.post(url, data=form_data) as response:
    if response.status == 200:
      return True
```
all works fine, on the server side I've got `store_id` in request body. But when I add file like this:
```
form_data = aiohttp.FormData()
form_data.add_field('store_id', store_id)
form_data.add_field('image', image_data, filename='image.jpg', content_type='image/jpeg')
async with self.session.post(url, data=form_data) as response:
    if response.status == 200:
      return True
```
`store_id` is removed from body and encoded as a file, on server side I see this in request:
```
"files":{
"image":{"filepath":"/tmp/durceaudx9d13adcq9h7de39m.jpg","mimetype":"image/jpeg","mtime":"2025-07-01T19:36:56.520Z","newFilename":"durceaudx9d13adcq9h7de39m.jpg","originalFilename":"image.jpg","size":658139},
"store_id":{"filepath":"/tmp/zem2j6rkkh9er8gf1580dewtm","mimetype":"text/plain","mtime":"2025-07-01T19:36:56.505Z","newFilename":"zem2j6rkkh9er8gf1580dewtm","originalFilename":null,"size":24}}
```

I've tried to use `MultipartWriter` like this
```
with aiohttp.MultipartWriter('form-data') as mpwriter:
    json_data = {
        'store_id': store_id
    }
    mpwriter.append_json(json_data)  # tried as well: mpwriter.append_form(json_data)
    part = mpwriter.append(image_data)
    part.set_content_disposition('form-data', name='image', filename='image.jpg')
```
but also no luck. JSON data included in request as a file.

Btw, with Postman I can accomplish this like on the screenshot and it sends `store_id` in body and image as multipart/form-data.
<img src="https://i.ibb.co/LhYGn9f5/Screenshot-2025-07-02-at-10-00-22.png" alt="Screenshot-2025-07-02-at-10-00-22" border="0">

The question: how to keep `store_id` in request body with included file using aiohttp?

**Comment by webknjaz** [comment]
JSON is not form data: https://docs.aiohttp.org/en/stable/client_quickstart.html#json-request

**Comment by thaikoh** [comment]
Thanks, I've tried `mpwriter.append_form(json_data)` as well.

**Comment by EuleMitKeule** [comment]
@thaikoh Did you find a solution? Currently experiencing the same problem.

**Comment by Dreamsorcerer** [comment]
If somebody records that actual data that aiohttp sends and the data they want to be sent, we might be able to provide more help.

**Comment by EuleMitKeule** [comment]
They did: `"files":{
"image":{"filepath":"/tmp/durceaudx9d13adcq9h7de39m.jpg","mimetype":"image/jpeg","mtime":"2025-07-01T19:36:56.520Z","newFilename":"durceaudx9d13adcq9h7de39m.jpg","originalFilename":"image.jpg","size":658139},
"store_id":{"filepath":"/tmp/zem2j6rkkh9er8gf1580dewtm","mimetype":"text/plain","mtime":"2025-07-01T19:36:56.505Z","newFilename":"zem2j6rkkh9er8gf1580dewtm","originalFilename":null,"size":24}}`

**Comment by Dreamsorcerer** [comment]
That's a piece of JSON. Not an HTTP request, nor a comparison with an expected HTTP request.

**Comment by EuleMitKeule** [comment]
`aiohttp` doesn't seem to have a mechanism to log the actual request that is being sent.

**Comment by Dreamsorcerer** [comment]
I doubt Postman does either. You could use netcat (e.g. `apt install netcat-openbsd`), for example. If I remember correctly, you'd just run `nc -l 8080` and then send your request to `http://localhost:8080`.
