### ISSUE TITLE
[Vote] Commit rights for Martijn Pieters

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#4042]
I want to propose @mjpieters to aiohttp Core team.
He expressed an intention to help with the project distribution and provided some help already.
Looks like Martijn has experience with MacOS wheels building. This is highly important for the project because of @webknjaz and I am are Linux guys (and because of Apple doesn't provide an *officially supported* way to run their OS inside a virtual machine).

Also, Martjin is active on Gitter chat in Q/A sessions.

Anyway, fresh blood doesn't harm but motivates for more contributions :)

The vote is ended in a week, on Saturday of September 14.

**Comment by samuelcolvin** [comment]
:+1: 

Sounds good to me, welcome @mjpieters.

**Comment by webknjaz** [comment]
+1

**Comment by masudr4n4** [comment]
can anyone check the comment i did there
#1455

**Comment by asvetlov** [comment]
Done.
Congratulations, @mjpieters

**Comment by kxepal** [comment]
:slowpoke: :+1:
