### ISSUE TITLE
Client errors are uncatchable

### ISSUE THREAD

**Issue by tedivm** [aio-libs/aiohttp#4064]
## Long story short

I can't catch exceptions. This is exactly the same as #4001, which was marked as invalid.

Test script, using Python3-

```python
import aiohttp
import asyncio


async def test():
    try:
        timeout = aiohttp.ClientTimeout(total=60)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            # Using 8.8.8.8 because no web server will respond there, forcing an error.
            async with session.get('http://8.8.8.8') as resp:
                print(resp.status)
                print(await resp.text())
    except aiohttp.ClientConnectorError as e:
        print('An exception has occurred.')

if __name__ == "__main__":
    asyncio.run(test())
```

## Expected behaviour

I expect it to print "An exception has occurred".

## Actual behaviour

When no timeout is present in the script I get this stack trace-

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    if __name__ == "__main__":
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "test.py", line 8, in test
    async with aiohttp.ClientSession() as session:
  File "/Users/robert/Working/testing/env/lib/python3.7/site-packages/aiohttp/client.py", line 1013, in __aenter__
    self._resp = await self._coro
  File "/Users/robert/Working/testing/env/lib/python3.7/site-packages/aiohttp/client.py", line 505, in _request
    await resp.start(conn)
  File "/Users/robert/Working/testing/env/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 848, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/Users/robert/Working/testing/env/lib/python3.7/site-packages/aiohttp/streams.py", line 592, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer
```

After shortening the timeout I instead receive this error-

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    asyncio.run(test())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "test.py", line 9, in test
    async with session.get('http://8.8.8.8') as resp:
  File "/Users/robert/Working/testing/env/lib/python3.7/site-packages/aiohttp/client.py", line 1013, in __aenter__
    self._resp = await self._coro
  File "/Users/robert/Working/testing/env/lib/python3.7/site-packages/aiohttp/client.py", line 505, in _request
    await resp.start(conn)
  File "/Users/robert/Working/testing/env/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 861, in start
    self._continue = None
  File "/Users/robert/Working/testing/env/lib/python3.7/site-packages/aiohttp/helpers.py", line 585, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

According to @mjpieters in #4001 I am using the correct way to catch exceptions, but they are still not being caught.

## Steps to reproduce

Run the script above.

## Your environment

There is no proxy server. I'm running on a fully up to date install of OSX, with Python 3.7.4.

**Comment by asvetlov** [comment]
If you have a timeout -- please catch `asyncio.TimeoutError`, not `aiohttp.ClientConnectorError`.

BTW, this issue reminds me of a long-awaited wish: drop `ClientOSError`, `ClientSSLError` and other exception wrappers.

The attempt for wrapping all existing exceptions that can be raised by client code into `ClientError` derived was a design mistake.
We shouldn't want to do it.

I propose dropping exception proxies in 4.0.

**Comment by mjpieters** [comment]
You are catching the wrong exception. The two tracebacks show what exceptions are being thrown:

```python
aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer
```

and 

```python
concurrent.futures._base.TimeoutError
```

Neither of which is a subclass of `aiohttp.ClientConnectorError`. That exception actually subclasses `ClientOSError`, see the [documentation for `ClientConnectorError`](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientConnectorError). `ClientConnectorError` is thrown for *`Connector` related exceptions*, and it or a subclass is only raised when there is a problem establishing a proxy connection or when SSL verification fails somewhere. A timeout or a socket connection reset is not such a problem.

When matching exceptions to an exception handler, Python will look at the exception class named in the expression of the `except <expression>` part, and it has to be the same class or a super class of the exception being thrown. In other words, the test `isinstance(exception, <expression>)` must be true. That's not the case in your examples.

One exception is a translation of the [`OSError` exception](https://docs.python.org/3/library/exceptions.html#OSError) thrown for socket issues. Here the low-level socket connection was closed by the other side without a higher-level protocol message telling you why. With a timeout, the standard [`asyncio.TimeoutError` exception](https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.TimeoutError) is thrown.

Take a look a the [aiohttp exception hierarchy](https://docs.aiohttp.org/en/stable/client_reference.html#hierarchy-of-exceptions), and decide what exceptions you want to catchfrom there. Then add [`asyncio.TimeoutError`](https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.TimeoutError) to your handler. 

E.g. for an application that deals with a wide range of remote services, I have defined a tuple of exceptions that are all handled the same way:

```python
client_exceptions = (
    aiohttp.ClientResponseError,
    aiohttp.ClientConnectionError,
    aiohttp.ClientPayloadError,
    asyncio.ServerTimeoutError,
)
```

and use that as `except client_exceptions:` or `except (*client_exceptions, asyncio.TimeoutError):` as appropriate. You could also decide to catch [`aiohttp.ClientError`](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientError) together with `TimeoutError` (e.g. `except (aiohttp.ClientError, asyncio.TimeoutError):` and handle these all the same.
