### ISSUE TITLE
use request handler into decorator

### ISSUE THREAD

**Issue by diyelise** [aio-libs/aiohttp#4074]
I haven't found an explicit way to pass request to the decorator I created to work with later

I expect that as soon as I get a request, I will extract remote_ip from it, make a check and return the function (`return web.json_response({'api': '1.0'})`)
or `return web.json_response({'response': 'Access denied'}))`

How to do it?
`peername = request.transport.get_extra_info('peername')`

```python
def whois():
	def wrapper(func):
		def wrapped(*args):
			return func(*args)
		return wrapped
	return wrapper

```
```python
@whois()
async def api_version(request):
       return web.json_response({'api': '1.0'})
```

в *args передается <Request GET /api >

**Comment by webknjaz** [comment]
This is a basic Python question what is totally unrelated to aiohttp. Please use corresponding forums for asking questions (StackOverflow, Gitter, mailing list) instead of a **bug** tracker.
```python
def whois():
	def wrapper(handler_coro):
		async def wrapped(request):
			return handler_coro(request)
		return wrapped
	return wrapper
```
