### ISSUE TITLE
i can't set the Accept-Encoding

### ISSUE THREAD

**Issue by orleven** [aio-libs/aiohttp#4085]
i can't set the Accept-Encoding

env:
python3.6
aiohttp-3.6.1

**Comment by webknjaz** [comment]
Not a question.

**Comment by orleven** [comment]
async with ClientSession() as session:
                headers = {
                    'Accept-Encoding': '11111',
                }
                async with session.get(url=url, headers=headers) as res:
                    if res!=None :
                        text = await res.text()

but, Accept-Encoding is gzip,deflate
