### ISSUE TITLE
repr(CIMultiDictProxy(CIMultiDict())) clears current exception

### ISSUE THREAD

**Issue by zware** [aio-libs/aiohttp#410]
Reproducer:

``` python
from aiohttp.multidict import CIMultiDictProxy, CIMultiDict
import sys

try:
    raise Exception
except Exception:
    print(sys.exc_info())
    repr(CIMultiDictProxy(CIMultiDict()))
    print(sys.exc_info())
```

Results:

```
(<class 'Exception'>, Exception(), <traceback object at 0x101a3d048>)
(None, None, None)
```

This is fairly serious; if you stick an 'as e' at the end of 'except Exception' and a 'raise' at the end of the except block, you wind up with a segfault.

Discovered in version 0.14.4, confirmed in 0.16.3.

**Comment by asvetlov** [comment]
Thanks for report!
It's Cython side effect.
Working on it.

**Comment by asvetlov** [comment]
Fixed in 0.16.4 release

**Comment by asvetlov** [comment]
Reported to Cython development list.

**Comment by zware** [comment]
Thanks for the quick response!  I suspected it might be a Cython issue, but I'm completely unfamiliar with Cython.

**Comment by asvetlov** [comment]
@zware sure!
