### ISSUE TITLE
Update docs  to say `aiohttp` doesn't support HTTPS proxies

### ISSUE THREAD

**Issue by bbkane** [aio-libs/aiohttp#4100]
## Long story short

The [docs](https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support) say `aiohttp` supports HTTPS proxies, but the [library](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_reqrep.py#L467) raises an exception on HTTPS proxies, and there is [issue](https://github.com/aio-libs/aiohttp/issues/3816) to add support for them.

## Expected behaviour

The [docs](https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support) shouldn't say HTTPS proxies are supported.

## Actual behaviour

The [docs](https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support) say HTTPS proxies are supported.

**Comment by asvetlov** [comment]
It doesn't support proxies that require `https://` for connection to.
But proxy that can be connected by `http://` with upgrade to HTTPS by [CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) HTTP method is supported.

**Comment by bbkane** [comment]
YES THATS WORKING!!! Please do update the docs to specify that though.

**Comment by asvetlov** [comment]
Would you prepare a pull request?
I believe now you can rephrase the text to avoid any misunderstanding.

**Comment by bbkane** [comment]
Yes, I'll try to do that tomorrow.

**Comment by bbkane** [comment]
Created https://github.com/aio-libs/aiohttp/pull/4101
