### ISSUE TITLE
Problem running test suite if Cython is not installed

### ISSUE THREAD

**Issue by btimby** [aio-libs/aiohttp#4105]
## Long story short
I followed the instructions here:

https://aiohttp.readthedocs.io/en/stable/contributing.html

I was unable to run tests without manually installing Cython.

```bash
(venv) $ pip install Cython
```

After the above, tests ran as expected.

Perhaps the documentation expects Cython to be installed already? I would be happy to fix this by either updating the documentation or `requirements.txt`. Please give me an indication of your preference and I will open a PR.

## Expected behaviour

I expected the test suite to run.

## Actual behaviour

```
  Running setup.py develop for aiohttp
    ERROR: Command errored out with exit status 1:
     command: /home/btimby/Code/aiohttp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/btimby/Code/aiohttp/setup.py'"'"'; __file__='"'"'/home/btimby/Code/aiohttp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/btimby/Code/aiohttp/
    Complete output (32 lines):
    **********************
    * Accellerated build *
    **********************
    running develop
    running egg_info
    writing aiohttp.egg-info/PKG-INFO
    writing dependency_links to aiohttp.egg-info/dependency_links.txt
    writing requirements to aiohttp.egg-info/requires.txt
    writing top-level names to aiohttp.egg-info/top_level.txt
    reading manifest file 'aiohttp.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'aiohttp' anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.lib' found anywhere in distribution
    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.a' found anywhere in distribution
    warning: no previously-included files matching '*.obj' found anywhere in distribution
    warning: no previously-included files found matching 'aiohttp/*.html'
    no previously-included directories found matching 'docs/_build'
    writing manifest file 'aiohttp.egg-info/SOURCES.txt'
    running build_ext
    building 'aiohttp._websocket' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/aiohttp
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/btimby/Code/aiohttp/venv/include/python3.6m -c aiohttp/_websocket.c -o build/temp.linux-x86_64-3.6/aiohttp/_websocket.o
    x86_64-linux-gnu-gcc: error: aiohttp/_websocket.c: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/btimby/Code/aiohttp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/btimby/Code/aiohttp/setup.py'"'"'; __file__='"'"'/home/btimby/Code/aiohttp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

## Steps to reproduce

Check out git master on a machine sans Cython and do:

```bash
$ cd aiohttp
$ virtualenv --python=`which python3` venv
$ . venv/bin/activate
$ pip install -r requirements/dev.txt
$ make test
```

## Your environment

Ubuntu 18.04, checked out git master.

**Comment by webknjaz** [comment]
This guide is probably outdated. The problem arised when Pip released more complete support for PEP517. So we switched to running cython build as a separate command before invoking `setup.py`. See the `Makefile` for details.

**Comment by btimby** [comment]
@webknjaz Thanks for the reply.

I am having similar fits installing my fork of aiohttp using pip / pipenv from git or from a package. I keep getting failures related to Cython. I found the environment variable `AIOHTTP_NO_EXTENSIONS=1`, which allows me to install aiohttp, but it does not work.

I have tried:

```
$ AIOHTTP_NO_EXTENSIONS=1 pipenv install git+https://github.com/btimby/aiohttp.git#egg=aiohttp
```
and
```
$ AIOHTTP_NO_EXTENSIONS=1 python setup.py bdist
$ pipenv install aiohttp-4.0.0a0.linux-x86_64.tar.gz
```

What are the proper steps to install my fork? I need this fix to continue my project.

**Comment by btimby** [comment]
Sorry, what I mean is that aiohttp does not work if I build it with that environment variable set.

**Comment by asvetlov** [comment]
Direct installation from github, e.g. `pip install git+https://github.com/btimby/aiohttp.git#egg=aiohttp`, was never officially supported even if it used to work by accident. Use distributions published on PyPI (`pip install aiohttp`).

*Development of* aiohttp is a different thing.
Development build requires Cython for running the test suite.
The following commands sequence works for me:
```
git clone git@github.com:aio-libs/aiohttp.git
cd aiohttp
git submodule update --init
mkvirtualenv aiohttp
make test
```

Currently, `make test` installs cython and all other dependencies, generates `.c` files from cython sources, compiles everything and installs aiohttp in editable mode before running tests.

I very appreciate a pull request that reflects the current workflow.

The only thing: perhaps the PR should mention triangle git workflow. https://gist.github.com/anjohnson/8994c95ab2a06f7d2339 is the first reference provided by google but I recall that github or git book has a better explanation.

**Comment by webknjaz** [comment]
@btimby what's `bdist`? the command for wheels is `bdist_wheel`

**Comment by btimby** [comment]
@webknjaz `bdist` is just a binary tarball as opposed to a wheel.
@asvetlov actually, `make test` did NOT install Cython for me, that is the reason for this issue.

**Comment by webknjaz** [comment]
`make cythonize` manually then. or maybe re-clone your repo.

**Comment by asvetlov** [comment]
I've tested on a fresh clone, BTW

**Comment by asvetlov** [comment]
Works on my side, @btimby didn't provide more info
