### ISSUE TITLE
requests with non-standard HTTP methods are ignored

### ISSUE THREAD

**Issue by jelmer** [aio-libs/aiohttp#4109]
## Long story short

The server silently ignores HTTP requests with an unknown method (anything not listed in the _http_method enum in aiohttp/_cparser.pxd as far as I can tell). e.g. the method "BLAH" doesn't work, but "MKCALENDAR" does.

The client simply doesn't get a reply, but the connection is kept open.

## Expected behaviour

Either that the request is passed through to whatever handler is registered, or that the aiohttp server responds with a 405 Method Not Allowed.

## Actual behaviour

The server ignores the request but keeps the connection open.

## Steps to reproduce

e.g. run "python3 server_simple.pyl" (from the source distribution), and then "curl -X BLAH http://localhost:8080/test" to reproduce.

## Your environment

Debian unstable. aiohttp 3.6.1 (SERVER), python 3.7.4

**Comment by asvetlov** [comment]
Interesting.
I think http parser fails but `web_protocol.py` doesn't reflect it.
Would you work on the fix?

**Comment by jelmer** [comment]
I was going to, but it appears to work correctly in the master branch.

**Comment by asvetlov** [comment]
Cool!
Sorry, I don't remember all bug fixes applied, only the most annoying ones maybe.

**Comment by jelmer** [comment]
No worries, glad to find it's already fixed :-)
