### ISSUE TITLE
DynamicResource support for subapp prefix 

### ISSUE THREAD

**Issue by matutter** [aio-libs/aiohttp#4135]
## Long story short

I'd like the subapp prefix to support `DynamicResource`. [This Gist](https://gist.github.com/matutter/a1d7726cf0c16bf847c75eaf2b62ae46) shows what I'd like to do. Unsure if this is a bug or intentional. I believe its intentional - so this is a feature request.

## Expected behaviour

Sub app would be properly routed to and have access to the `request.match_info` for the dynamic resource declared in the sub-apps prefix.

## Actual behaviour

Requests to the sub-app get a `404 Not Found`.

## Steps to reproduce

More complete example in the gist linked above.

```python
  root = web.Application()
  root.router.add_get('/1', handle_1)
  child = web.Application()
  child.router.add_get('/2', handle_2)
  root.add_subapp('/child/{key}', child) # dynamic resource "key" is in prefix
```

## Your environment

OS: Ubuntu Bionic
Python: 3.7
Versions

- pytest==5.0.1
- pytest-aiohttp==0.3.0
- aiohttp==3.5.4

aiohttp server

**Comment by matutter** [comment]
**Longer explanation**

I'm aware that declaring the routes like this...

```python
  child.router.add_get('/{key}/2', handle_2)
  root.add_subapp('/child/', child)
```

...makes the gist work. But I think having the dynamic resource declared in the subapp prefix better suits the use-case I have for using sub-apps. In the service I'm writing I have a endpoints which are accessible at a namespace. So the url paths look like `/api/name/name/name/leaf`. 
Each `name` in that URL has an optional authorization check and I've been using middleware to enforce these auth checks.

However the way I have to write it currently requires the `leaf` app to be aware of the auth check for the `leaf - 1` namespace. And I have to put that middleware on the `leaf` app to get and enforce the `leaf - 1` auth check.

With the ability to declare routes with dynamic resources in the sub-app prefix I would be more able to keep portions of my API logically separate.

**Comment by asvetlov** [comment]
#2756 has an information of a problem.

Dynamic subapps should provide a way for restoring an url from it by `url_for()`.
It is possible but nobody proposed a robust solution yet.
I love to review a PR but have no time for make it myself, sorry.

**Comment by matutter** [comment]
Looks like there's already a lot of work on this if maybe a bit stale. Should this be closed as duplicate?

**Comment by asvetlov** [comment]
agree
