### ISSUE TITLE
Import fails with SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by aydwi** [aio-libs/aiohttp#4136]
## Long story short

When trying to import `aiohttp`, it fails with `SyntaxError: invalid syntax`

## Expected behaviour

Should import without an error

## Actual behaviour

Import fails with `SyntaxError: invalid syntax`

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ayush/hn/vnev/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/Users/ayush/hn/vnev/lib/python3.7/site-packages/aiohttp/client.py", line 3, in <module>
    import asyncio
  File "/usr/local/lib/python3.7/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.7/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                       ^
SyntaxError: invalid syntax
```

## Steps to reproduce

`import aiohttp`

## Your environment

macOS Mojave 10.14.6
Python 3.7.4
aiohttp 3.6.1
asyncio 3.4.3
virtualenv 16.7.5

Although I was able to import it earlier, it started failing suddenly.

**Comment by aydwi** [comment]
Update: I was able to get it working after a clean install. Will close the issue if it doesn't reoccur.

**Comment by asvetlov** [comment]
I guess you had used older aiohttp version.

**Comment by tpiekarski** [comment]
I am getting the same error when building at Travis CI, so I hope I am getting a *clean* install there. 
Will try to deactivate any caching I set up earlier

For details see the log at: https://travis-ci.org/github/tpiekarski/derl/jobs/708033613#L733

@aydwi How did you *clean* install it again?
@asvetlov What do you mean exactly with an older version? Did this bug have been around in old versions?

Thanks in advance, do you have any idea how to fix this issue? Should we reopen it?

**Comment by tpiekarski** [comment]
It turned out that asyncio should not be listed in requirements.txt nor in setup.cfg and installed with pip.
Sorry to bother, thanks anyway :blush:
