### ISSUE TITLE
docs: explain why all setups we set to app

### ISSUE THREAD

**Issue by Arfey** [aio-libs/aiohttp#4137]
Add in documentation part (maybe into tutorial) where explaining why all connection, settings and etс, we add to the instance of application.

example:

```python
async def init_pg(app):
    conf = app['config']['postgres']
    engine = await aiopg.sa.create_engine(
        database=conf['database'],
        user=conf['user'],
        password=conf['password'],
        host=conf['host'],
        port=conf['port'],
        minsize=conf['minsize'],
        maxsize=conf['maxsize'],
    )
    app['db'] = engine
```

Please don't forget:

- add screenshot with your part of documentation
- write below that u want to take it to work

**Comment by oktak** [comment]
I wonder there exists a website https://demos.aiohttp.org/en/latest/tutorial.html 
Is it serving similar purpose? Does this issue aim to merge the two?
Indeed, I am willing to work on this, may be add some screenshots :)
Please let me know more about the direction.

**Comment by Arfey** [comment]
Tutorial is story about show how may looks project on aiohttp and how u need to design it. The main documentation is about how work and why.

The main goal of this issue it's describe why we choose  this way to share settings  and etc.

**Comment by asvetlov** [comment]
Can be a part of #4078 work

**Comment by sha016** [comment]
@Arfey @asvetlov I'd like to contribute, seems like a good start.

**Comment by asvetlov** [comment]
Please do
