### ISSUE TITLE
docs: add to documentation part about `deploy with SSL`

### ISSUE THREAD

**Issue by Arfey** [aio-libs/aiohttp#4138]
A lot of people have problem when deploy `aiohttp` with `SSL`. So this is a good reason to cover this part into documentation (deploy).

The proposed topics:

- `aiohttp` + `gunicorn` + `nginx` +/- `SSL`
- `aiohttp` + `gunicorn` + `apache` +/- `SSL`

Please don't forget:

- add screenshot with your part of documentation
- write below that u want to take it to work

**Comment by asvetlov** [comment]
@Arfey is the issue done by #4201 ?
If yes -- please close it
