### ISSUE TITLE
Binary data posted seems to get b appended to it

### ISSUE THREAD

**Issue by emacsen** [aio-libs/aiohttp#4154]
## Long story short

Data from a binary request gets b appended to the result on response.read()

## Expected behaviour

The expected behavior is that when you have a binary data, it should not have this extra byte appended to it. This is often due to not correctly encoding the binary result.

## Actual behaviour

Somewhere in the chain, python is decoding the binary object improperly and adding the b, as if it was a string. This happens if the data is converted to a string, rather than .encode() -ed.

## Steps to reproduce

This is challenging to reproduce without having a server that speaks a binary protocol. I can supply code if requested.

## Your environment

Python 3.7 on Ubuntu using aiohttp version 3.6.1.

client

**Comment by socketpair** [comment]
Please provide sample code that reproduces the bug.

**Comment by asvetlov** [comment]
Heh, I do send binary data without appended `b` on my job :)

**Comment by emacsen** [comment]
Yes, this was a mistake in the framework. Sorry!
