### ISSUE TITLE
Error while installing dependency using the contributing guide

### ISSUE THREAD

**Issue by icmpecho** [aio-libs/aiohttp#4160]
## Long story short

I cloned the repo and follow the contributing guide [here](https://docs.aiohttp.org/en/stable/contributing.html) then run into a dependency installation error.

## Expected behaviour

By following the guide I should be able to start development.

## Actual behaviour

During the `$ pip install -r requirements/dev.txt` step I got this error
```
    clang: error: no such file or directory: 'aiohttp/_websocket.c'
    clang: error: no input files
    error: command 'clang' failed with exit status 1
    ----------------------------------------
```

After taking a look into `Makefile` I just found out that if I skip the dependency installation step and run `make test` it will correctly install everything for me. I'm going to create a PR to update the document.

## Steps to reproduce

Just freshly clone the repo then follow the contributing guide step by step

## Your environment

aiohttp version: master
OS: macos 10.14.6
python version: 3.7.4

**Comment by meetmangukiya** [comment]
Had same issue, https://docs.aiohttp.org/en/stable/contributing.html doesn't reflect the changes.
