### ISSUE TITLE
Sending text file hangs on Windows

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#4178]
```
    with fname.open('r') as f:
        resp = await client.post('/', data=f)
```

A file opened in binary mode (`fname.open('r')`) works well.

**Comment by asvetlov** [comment]
The best fix is forbidding text mode on Windows (and emitting a warning on other systems).

Opinions?

**Comment by pwuertz** [comment]
I'm seeing a similar problem on windows + jupyter lab, unrelated to text file reading. I was simply trying to post a json encoded object, but the server never receives any request and the jupyter cell just hangs forever.

The same application works fine when running as standalone script (asyncio run until complete).
Never had any issues on linux + jupyter lab.

Also the amount of data being sent seems to have some impact as well.

**Comment by asvetlov** [comment]
Maybe Jupiter on Windows has some spikes?
aiohttp was never tested to work with Jupiter, I have no idea does it work at all or not (and how).

**Comment by pwuertz** [comment]
Oh ok, so your text file issue didn't occur while running within jupyter? Could be a different bug then.. or maybe not, I couldn't exactly pinpoint the exact requirements to reproduce or avoid it.

Jupyter nowadays supports running `async` statements in cells,  having a asyncio loop running in the background. I'm seeing `_UnixSelectorEventLoop` and `_WindowsSelectorEventLoop` for `asyncio.get_running_loop()` on my Linux and Windows machines.

**Comment by asvetlov** [comment]
Thanks for letting me know that Jupiter works with aiohttp.

Do I understand correctly: you code with sending json data works fine on Windows as a standalone script but fails in Jupiter?

**Comment by pwuertz** [comment]
Ah, sorry for the noise.. I didn't notice that some of the notebooks had `%matplotlib qt5` defined somewhere (or did implicitly set it). This seems to impact `await` in general, unrelated to `aiohttp`.

Bug was reported elsewhere -> https://github.com/jupyter/notebook/issues/4895

**Comment by asvetlov** [comment]
Let's close then.
