### ISSUE TITLE
Can't install dependencies from master after cloning

### ISSUE THREAD

**Issue by paulefoe** [aio-libs/aiohttp#4179]
## Long story short

In a commit `ab0e956b2952462a4ca132c5ee13284719bffe7e` the cythonize function was removed from `setup.py` and now I can't install dependencies unless I do `make cythonize` before installing which is not documented anywhere as far as I can see.

## Expected behaviour

`pip install -r requirements/dev.txt` installs the dependencies or documentation includes `make cythonize` part

## Actual behaviour

An exception that there is no file aiohttp/_websocket.c

## Steps to reproduce

1. `git clone git@github.com:aio-libs/aiohttp.git --recurse-submodules`
2. create venv
3. `pip install -r requirements/dev.txt`

## Your environment

Kernel: x86_64 Linux 5.3.5-arch1-1-ARCH
python: 3.7,  3.6
aiohttp version: master

Would be glad to provide a pr.

Should we just add make command to the docs in contributing?

**Comment by webknjaz** [comment]
Yes, that's by design. Feel free to send a PR against the docs.

**Comment by paulefoe** [comment]
I just noticed it's already in the latest docs, so I'm closing it.

https://docs.aiohttp.org/en/latest/contributing.html
