### ISSUE TITLE
StreamResponse.write typing issue

### ISSUE THREAD

**Issue by willmcgugan** [aio-libs/aiohttp#4181]
## Long story short

The docs for [StreamResponse.write](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.StreamResponse.write) claim the method can accept bytes, bytearray, or memoryview, but the [signature](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_response.py#L402) is typed as accepting `bytes` only. Similar issue with write_eof.

Naturally mypy complains if you give it anything other than bytes.

I'm assuming this is an oversight and all that needs to be changed is the signature. Happy to submit a PR for that and any other instances I find.

## Your environment

Present in master branch.

**Comment by asvetlov** [comment]
Please read https://docs.python.org/3/library/typing.html#typing.ByteString

Doesn't mypy follow this shorthand for `bytes` meaning?

**Comment by willmcgugan** [comment]
Huh, that's interesting.

> Doesn't mypy follow this shorthand for bytes meaning?

Doesn't look like it. I filed https://github.com/python/mypy/issues/7714 

I suspect an explicit union of bytes/bytearray/memoryview may be the way to go in the meantime, so Mypy would at least work as originally intended.

**Comment by asvetlov** [comment]
If mypy behavior doesn't follow documentation I suggest using `typing.BytesString` explicitly.

Would you make a patch?

**Comment by willmcgugan** [comment]
> If mypy behavior doesn't follow documentation I suggest using typing.BytesString explicitly.

ByteString doesn't work either I'm afraid. With `ByteString` it works with `bytes` and `bytearray`, but not `memoryview`.

> Would you make a patch?

Happy to. How about I replace `bytes` with the following type where appropriate:

```python
ByteLike = Union[bytes, bytearray, memoryview]
```

**Comment by asvetlov** [comment]
Deal!
I suspect that `StreamResponse.write()` is not the only method that suffers from the problem.
The process is iterative, you can start from something obvious and simple though.
No need to fix everything at once.

**Comment by willmcgugan** [comment]
Looks like the mypy folks already have a [fix](https://github.com/python/mypy/issues/7714#issuecomment-542150840) in the works.

I'm assuming this negates the need for any changes here? I'm happy to ignore the typing error and wait for the fix to land in mypy.

**Comment by asvetlov** [comment]
Ok. I'm happy to have a fix in the upstream.
