### ISSUE TITLE
Implement BaseRequest.get_extra_info()

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#4189]
It is a simple shortcut for `request.transport.get_extra_info()`.

`request.transport` will go eventually.

Documentation update and a simple test are required.

**Comment by rbialon** [comment]
Hi @asvetlov ,
I'd like to work on this.
To clarify, while `request.transport` will go eventually, `request._protocol.transport` will stay and is still the right resource to invoke `get_extra_info()` on?

**Comment by asvetlov** [comment]
Correct.
It `request._protocol.transport` will go as well but the test suite will have a test for `request.get_extra_info()` -- we'll fix it immediately.

I don't like using `request.transport.get_extra_info()` because I want to raise deprecation warning for `.transport` property soon, much earlier before the actual removal.

**Comment by asvetlov** [comment]
Fixed by #4196
