### ISSUE TITLE
Docs: Mention that timeouts are in seconds

### ISSUE THREAD

**Issue by polcak** [aio-libs/aiohttp#4190]
The docs such as https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientTimeout does not mention what are the units for the timeout, are these second, miliseconds, minutes?

Looking at https://docs.aiohttp.org/en/stable/client_quickstart.html#aiohttp-client-timeouts I figured out that timeouts are specified as seconds but only after reading to the very botom. Even there the units are not mentioned but rather the docs mention "By default aiohttp uses a total 5min timeout" and "Thus the default timeout is: aiohttp.ClientTimeout(total=5*60, connect=None,
                      sock_connect=None, sock_read=None)"

## Expected behaviour

Please specify the units explicitely, e.g.: "Total number of seconds for the whole request." rather than "Total timeout for the whole request."

**Comment by asvetlov** [comment]
Pull request is welcome!

**Comment by codepr** [comment]
Hello, thanks for the great work with the library, addressed the issue on #4194 .

**Comment by polcak** [comment]
Pull request #4197 addresses more occurrences of the missing unit than #4194.

**Comment by asvetlov** [comment]
Fixed I guess
