### ISSUE TITLE
Where did the 4.0.0a0 package go?

### ISSUE THREAD

**Issue by StingyJack** [aio-libs/aiohttp#4198]
4.0.0a1 broke code that was working with 4.0.0a0.  Where can I get the 4.0.0a0 package from if I cant figure out a workaround for the code?

Specifically the broken part is that the `verify_ssl` parameter is no longer available.

**Comment by asvetlov** [comment]
`4.0.0a1` means: version `4.0.0, alpha 1`.
This is expected that alpha releases can make backward-incompatible changes.
I highly recommend to not use alpha versions in production code.

Speaking about `verify_ssl` -- the parameter was deprecated for a long and scheduled for removal in 4.0. What did you expect?

**Comment by StingyJack** [comment]
I have a setup.py that says aiohttp should be >= 3.6.2 and <4.0.0, yet pip has been installing the a0 package for some period time. Until the other day when the build pipeline decided to install a1 and everything started complaining about the verify_ssl param 

This is probably pip or environment related.

**Comment by webknjaz** [comment]
@StingyJack you probably used `--pre` flag with `pip` which is highly discouraged in production.

**Comment by asvetlov** [comment]
By default, pip doesn't install pre-release packages until `--pre` flag is used.
I have no idea why pip installs pre-released versions. 
Maybe you use outdated pip?
`4.0.0` is greater than `4.0.0a1`, sure. To explicitly forbid 4.x line you need `aiohttp>=3.6.2,<4.0.0a0`

**Comment by webknjaz** [comment]
(was reopened accidentally)

**Comment by webknjaz** [comment]
P.S. Answering the original question: it's @ https://pypi.org/project/aiohttp/4.0.0a0/. But just to reiterate: **don't use alpha-quality code in production**.

**Comment by StingyJack** [comment]
>  To explicitly forbid 4.x line you need aiohttp>=3.6.2,<4.0.0a0

That doesn't make a bit of sense. Is the a0 a common suffixing for pip prerelease? I don't know, I have many years of programming but only a few months with python.

> don't use alpha-quality code in production

Yeah, I wasn't trying to. We told pip "don't use 4.anything" and it's installing the prerelease without using --pre. IIRC the command in the venv is something like `pip install -e . [collection,dev,test]`

**Comment by Harmon758** [comment]
https://www.python.org/dev/peps/pep-0440/#pre-releases
Using `a` after a version number to indicate an alpha release is not uncommon syntax or unique to Python though.

If you're installing from a source directory that contains alpha release code, then that's what it will install.

**Comment by webknjaz** [comment]
@Harmon758 I think he is installing their own app like this, aiohttp doesn't have such extras.

**Comment by webknjaz** [comment]
@StingyJack if you show the exact code and the console output, somebody may be able to help you. But generally speaking, you likely have something messed up in how you work with packaging in your project which is out of the scope of aiohttp.

To learn more about packaging in Python, check out this website by Python Packaging Authority: https://packaging.python.org/.

**Comment by webknjaz** [comment]
P.S. This may also be happening if you use decade-deprecated versions of pip/setuptools.

**Comment by StingyJack** [comment]
OMG. This also happens when the requirement line says 
```
'aiohttp>=3.4.4<4.0.0',
```
instead of 
```
'aiohttp>=3.4.4,<4.0.0',
```

Edit: This was only intended to share what the actual cause for the problem was in case anyone was/will be curious.

**Comment by webknjaz** [comment]
@StingyJack please report this @ https://github.com/pypa/pip/issues/new?template=bug-report.md
