### ISSUE TITLE
Contradiction between documentation and annotation of the secure parameter of set_cookie()

### ISSUE THREAD

**Issue by serhiy-storchaka** [aio-libs/aiohttp#4204]
The `secure` parameter of `StreamResponse.set_cookie()` is [documented](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.StreamResponse.set_cookie) as `bool`, but is [annotated](https://github.com/aio-libs/aiohttp/blob/62365364889981a2e5d3cd36a25240c9c38693fe/aiohttp/web_response.py#L172) as `Optional[str]`.

What is right?

**Comment by asvetlov** [comment]
There is #3836
Since https://github.com/python/typeshed/issues/3059 is fixed and new mypy is released we need to update `set_cookie` annotation.

**Comment by serhiy-storchaka** [comment]
#3836 does not touch the `secure` parameter.
