### ISSUE TITLE
The definition of LooseCookies is too narrow

### ISSUE THREAD

**Issue by serhiy-storchaka** [aio-libs/aiohttp#4205]
Seems both `CookieJar.update_cookies()` and `ClientRequest.update_cookies()` accept also `Iterable[Tuple[str, Union[Morsel, str]]` and `Mapping[str, Union[Morsel, str]]`.

The definition of `LooseCookies` which does not include the above types is not compatible with existing user code.

**Comment by asvetlov** [comment]
Agree. Good first-time issue.
Any volunteer?

**Comment by serhiy-storchaka** [comment]
Would be nice to add test cases for `update_cookies()` with different types of arguments.

**Comment by asvetlov** [comment]
@serhiy-storchaka thanks for the note.
@AtomsForPeace would you create a follow-up PR?

**Comment by AtomsForPeace** [comment]
Sure thing

**Comment by AtomsForPeace** [comment]
So I added the extra two types mentioned and added a test for CookieJar.update_cookies. Should I add a test for ClientRequest.update_cookies too or is that unnecessary?

**Comment by serhiy-storchaka** [comment]
They use similar but independent code, so testing ClientRequest.update_cookies is not redundant.

**Comment by AtomsForPeace** [comment]
Ok, I'll try find time to add it this evening. Thanks for the feedback

**Comment by asvetlov** [comment]
Fixed, I think.
Please feel free to open a new issue if something is not covered still
