### ISSUE TITLE
aiohttp 3.6 breaks my oauth

### ISSUE THREAD

**Issue by nicfit** [aio-libs/aiohttp#4239]
## Long story short

Changes to `aiohttp.web_exceptions.HTTPMove` have broken my oauth redirects (using
aiooauth-client)

## Expected behaviour

The location I pass to HTTPMove contains an escaped URL, and the oauth server expects this to be "quoted".  Prior to aiohttp 3.6 the URL passes was untouched and the oauth redirect worked as expected.

## Actual behaviour

Now, the URL is parsed that the quoting/escaping is lost and OAUTH now fails.

## Steps to reproduce

The OAUTH server is Cisco Teams.

## Your environment

Currently I'm pinning to aiohttp<3.6 to not break my library.

**Comment by asvetlov** [comment]
Please provide examples of actual and expected Location header

**Comment by nicfit** [comment]
The problem seems to be that the location header passed in the redirect in not quoted (as are the values that the object is constructed with), whereas this was preserved in aiohttp 3.5.

```
https://idbroker.webex.com/idb/oauth2/v1/authorize?redirect_uri=http%3A%2F%2F127.0.0.1%3A8080%2Fhds&scope=spark-admin%3Akms_read+Identity%3AOAuthKeyService+spark%3Aall+spark-admin%3Amemberships_read+spark-admin%3Ateam_memberships_write+Identity%3AOrganization+Identity%3AConfig+spark-admin%3Arooms_write+spark-admin%3Aevents_read+spark-admin%3Amemberships_write+webex-squared%3Acallback+spark-admin%3Amessages_write+compliance%3Aspark_conversations_read+spark-compliance%3Arooms_read+webexsquare%3Aget_conversation+spark-admin%3Arooms_read+spark-admin%3Ateam_memberships_read+spark-compliance%3Aspark_conversations_read+spark-admin%3Amessages_read+Identity%3ASCIM+spark-admin%3Akms_write+webex-squared%3Aadmin+webexsquare%3Aadmin&client_id=C58b720f6074e778c963db015405c10f52b5fba543ede7c1790ff1430e80134bb&response_type=code
```
HTTPMove.location matches the quoted input, but the header['location'] on that object is unquoted and the OAUTH server expects it to be quoted.

**Comment by nicfit** [comment]
Here is my current work-around:

```python
if tuple([int(n) for n in aiohttp.__version__.split(".")[:2]]) >= (3, 6):
    # aiohttp >= 3.6 constructs a Url from location and then sets the location
    # header to the serialized str, this loses the quoting that is in the orig
    # URL and it MUST remain quoted for WebEx oauth.
    redirect.headers["location"] = redirect.location
```

**Comment by Dreamsorcerer** [comment]
Sorry for the delay, you just need to use a pre-encoded URL:
```
web.HTTPMovedPermanently(location=URL(..., encoded=True))
```
