### ISSUE TITLE
Getting 404s on sub app routes

### ISSUE THREAD

**Issue by thebpmgroup** [aio-libs/aiohttp#4248]
## Long story short

I have created an app (which works) and a sub app which doesn't work. It launches and I can see the routes of the sub app when I iterate through the routes of the main app using print, but all attempts to call a url of the sub app give a 404

## Expected behaviour

Sub app works as per the example

## Actual behaviour

Sub app loads and routes load into routing table but all attempts to load the routes in a browser result in a 404

## Steps to reproduce

**server.py**
```
import aiohttp_jinja2
import jinja2
import asyncio
from aiohttp import web
import subapp #This is the source file containing the sub app

@aiohttp_jinja2.template('helloworld.jinja2')
async def helloworld(request):
    return {'hw': 'Hello World'}

app = web.Application()
    aiohttp_jinja2.setup(app,
    loader=jinja2.FileSystemLoader('templates'))

 app.add_subapp('/admin',subapp.admin_app)
 app['admin'] = subapp.admin_app #Tried with and without this line as I have seen examples both with and without

for r in app.router.routes():
        print(r.resource.get_info()) #This successfully lists my routes including sub app routes

web.run_app(app, port=8000)
```
**subapp.py**
```
import aiohttp_jinja2
import jinja2
import asyncio
from aiohttp import web

@aiohttp_jinja2.template('subapproute1.jinja2')
async def subapproute1(request):
    return {'hw': 'Hello World'}

admin_app = web.Application()
admin_app.add_routes([web.get('/subapproute1, subapproute1, name='subapproute1')])
```
## Your environment

Python 3.7
Ubuntu 18.04 LTS

**Comment by asvetlov** [comment]
At least you didn't setup jinja2 engine for sub-app.
What errors do you see in logs?

**Comment by thebpmgroup** [comment]
Just the 404 error. I found that by adding the sub app before the parent app routes, it works. Not tried with multiple sub apps.

Setting up jinja2 for the sub app would just be weird ;)

**Comment by thebpmgroup** [comment]
Works with multiple sub apps, provided you add the sub apps **before** adding the routes to the parent app.

`
app.add_subapp('/admin',admin.admin_app) #Set up the routes in this file for this subapp
app.add_subapp('/api',api.api_app) #Set up the routes in this file for this subapp

    app.router.add_get("/", parent)
    app.router.add_get("/parentroute1", parentroute1)
`

**Comment by asvetlov** [comment]
Your first message contains an incomplete example (I cannot just run it and see what's wrong).
Moreover, you didn't provide the important info, the second message has a completely different URL map.
Sorry, help is impossible in this case.
