### ISSUE TITLE
How to get server ip in aiohttp

### ISSUE THREAD

**Issue by shmilylty** [aio-libs/aiohttp#4249]
## Long story short

I want to get resolve ip from server 

## Detail

Code demo:
```py
import aiohttp
import asyncio

async def fetch(session, url):
    async with session.get(url) as response:
        return await response.text()

async def main():
    async with aiohttp.ClientSession() as session:
        html = await fetch(session, 'http://python.org')
        print(html)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```
How I can get resolve ip of  python.org in aiohttp?

**Comment by asvetlov** [comment]
I'm curious why do you need it?

**Comment by shmilylty** [comment]
I have a list of URL to be requested, maybe a million, and I want to record their resolved IP, in the HTTP request. Of course, I can use the dns library that comes with Python to resolve to get the IP, before the HTTP request, but resolve it twice.

**Comment by asvetlov** [comment]
Builtin resolver caches calls

**Comment by shmilylty** [comment]
@asvetlov Thx, I have debug demo code in pycharm, I have saw all var，but I don't find any related server ip information. Could you give me some code, please?

**Comment by asvetlov** [comment]
Sorry, I don't follow what code are you asking.
You wrote:
> Of course, I can use the dns library that comes with Python to resolve to get the IP, before the HTTP request, but resolve it twice.

My answer is: please do; if you use the system DNS resolver it caches all data at the system level instead of sending DNS request twice.
The penalty is zero.

**Comment by shmilylty** [comment]
I've implemented it with the dns library, but I still want to know if aiohttp is available?
```py
import asyncio
import dns.resolver
import config
from config import logger

def dns_resolver():
    """
    dns解析器
    """
    resolver = dns.resolver.Resolver()
    resolver.nameservers = config.resolver_nameservers
    resolver.timeout = config.resolver_timeout
    resolver.lifetime = config.resolver_lifetime
    return resolver


async def dns_query_a(hostname):
    """
    查询A记录

    :param str hostname: 主机名
    :return: 查询结果
    """
    resolver = dns_resolver()
    try:
        answer = resolver.query(hostname, 'A')
    except BaseException as e:
        logger.log('DEBUG', e.args)
        answer = None
    return answer
```

**Comment by asvetlov** [comment]
aiohttp has no such functionality yet

**Comment by shmilylty** [comment]
Does aiohttp have any plans to implement this feature?

**Comment by shmilylty** [comment]
Could you tell me how long it will take for aiohttp 4.x stable version to be released?

**Comment by asvetlov** [comment]
No idea
