### ISSUE TITLE
Very explicitly describe the URL dispatcher sequential search nature

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#4256]
aiohttp tries to match URL to web-handler in the order of resources (routes) addition.
Documentation should be very clear at this point.

For example `/{name}`, `/info` always matches to `/{name}`, `/info` router has no chance to be called.
On the opposite, `/info`, `/{name}` calls web handler for `/{name}` only if `name!='info'`, inother words if `/info` handler didn't match.

The same is true for sub-apps; `app.add_subapp('/pre', subapp)` matches all `/pre/*` paths.
```
app.add_subapp('/pre', subapp)
app.add_routes('/pre/path', handler)
```
In the example above a handler for `/pre/path` is never matched.

A champion for documentation upgrade is needed. I don't know where we should put this chapter; this is a subject for discussion.

Related: #4078

**Comment by xypnox** [comment]
Hi, I would like to add the documentation for this issue. 

An apt place where we can add this would be where we introduce [variable routes](https://docs.aiohttp.org/en/stable/web_quickstart.html#variable-resources).

**Comment by asvetlov** [comment]
Agree, please use a separate chapter next to `Variable Routes`.

**Comment by Dreamsorcerer** [comment]
This behaviour doesn't happen since we rewrote the routing algorithm for better performance in #7829.
