### ISSUE TITLE
Queries 

### ISSUE THREAD

**Issue by corporatepiyush** [aio-libs/aiohttp#426]
i could not find the any group to put my questions. so asking here.
1. Is one instance of python app using aiohttp for multicore machine ? or we need to span multiple process to effectively make use of multiple cores just like in case of WSGI servers ?
2. How to handle blocking connections to DB?

**Comment by krkd** [comment]
Didn't understand first question.
As for blocking connections on db:
1. You can connect and execute query in separate thread 
OR
2. Or use libraries that handle connection to DB in non-blocking mode. You can find library that match your case here https://github.com/aio-libs

**Comment by asvetlov** [comment]
@corporatepiyush perhaps you want to utilize your multicore machine.
That's fine.
You may use gunicorn or setup your nginx to use upstream connection pool: http://nginx.org/en/docs/http/ngx_http_upstream_module.html#upstream

**Comment by corporatepiyush** [comment]
Thanks @krkd and @asvetlov for prompt answers.

i understood that gunicorn can help me scale it vertically on multiple cores.
 but i am still confused/skeptical about my first question. would Janus( https://github.com/aio-libs/janus ) be any help in this regard ?  in other words what if i am making use of DB or library which are not supported for asyncio ? any working example  would be greatly appreciated.

**Comment by jettify** [comment]
@corporatepiyush could you name your target database? Most popular ones have been already ported. Anyway you always can use [run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.BaseEventLoop.run_in_executor) asyncio api, put you blocking operation to separate thread pool.

**Comment by corporatepiyush** [comment]
@jettify  I am trying out MongoDB and Neo4J

**Comment by jettify** [comment]
@corporatepiyush there is mongo connector to asyncio https://bitbucket.org/mrdon/asyncio-mongo , not best one, but working. Not sure about Neo4J.

**Comment by jettify** [comment]
Looks like Neo4J supports REST api. So you can use [aiohttp client](http://aiohttp.readthedocs.org/en/latest/client.html) as result you will have non blocking calls to this database too.

**Comment by corporatepiyush** [comment]
asyncio-mongo site says its not production ready yet ?
Accessing Neo4J through REST is slower..
So i guess "run_in_executor" on "service" level in my web app (REST controller <=> service <=> ORM) would be good choice.

Thanks for your time.

**Comment by asvetlov** [comment]
Sure!
