### ISSUE TITLE
Use loop.starttls() on Python 3.7+

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#4268]
Now TCPConnector has a custom code for upgrading proxy from HTTP to HTTPS on `CONNECT` http verb.

I think we should start using `loop.starttls()` on Python 3.7+ to fix the issue.

_Originally posted by @asvetlov in https://github.com/aio-libs/aiohttp/issues/2245#issuecomment-546409157_

**Comment by aivrar** [comment]
@asvetlov Hello sir.

I was wondering what you are referring to with `loop.starttls()`? Do you think this something that can help my current issue here? This is my comment link in the issues thread for aiohttp.

https://github.com/aio-libs/aiohttp/issues/4429#issuecomment-564038500

I have been getting some help:
https://pastebin.com/atLw1hC7
![image](https://user-images.githubusercontent.com/42790594/70697962-1fa30d00-1c8c-11ea-856a-ee2a4b30e506.png)

I'd really like to get this working, I'm not sure if this is a problem on my end and how to remedy it.

Thanks

**Comment by Allexio** [comment]
Hi is there any update on this issue? Any planned upgrade to fix the fact that http proxies don't work anymore on windows?
This is a problem for me because it breaks the slackclient library when using a proxy :/
( https://github.com/slackapi/python-slackclient/issues/642 )

**Comment by asvetlov** [comment]
It will be possible starting from aiohttp 4.0 only at least.
`loop,starttls()` doesn't work together with our home-made workaround.

**Comment by aivrar** [comment]
Wow, I'm glad I stayed subscribed because I'm raring to go here.  Looking forward to update.

**Comment by munding** [comment]
python 3.9 there are still such problem

**Comment by HMaker** [comment]
@webknjaz I tried using HTTP proxy with aiohttp 3.7.4 and `ProactorEventLoop` on Windows 10 but it faiils with `OSError(22, 'The parameter is incorrect', None, 87, None))` on proxy connection. Same error reported by #2245.

**Comment by webknjaz** [comment]
This has been implemented and will be available with hacks under aiohttp 3.8+ (and Python 3.7+). The 3.7 stream is EOL and will not get any updates.
