### ISSUE TITLE
TCPConnector ttl_dns_cache type hint

### ISSUE THREAD

**Issue by humkanet** [aio-libs/aiohttp#4270]
Hello,

```
class TCPConnector
def __init__(
....
ttl_dns_cache: int=10
...)
```

but documentation (and code so):

> ttl_dns_cache (int) –
> 
> expire after some seconds the DNS entries, None means cached forever. By default 10 seconds.

Can you annotate as Optional[int], please?

**Comment by asvetlov** [comment]
Pull Request is welcome!

**Comment by haneybarg** [comment]
Can I take this?

**Comment by webknjaz** [comment]
@haneybarg sure! Got ahead!
