### ISSUE TITLE
Implement HTTPException set_cookie() and del_cookie() methods

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#4277]
See https://github.com/aio-libs/aiohttp-session/issues/396 for the context.

Implementation thoughts:
1. `.cookies` property is also needed
2. `set_cookie()` and `del_cookie()` should update headers immediately, `HTTPException` has no `.prepare()` method and should not have it.
3. Backport is not needed, in 3.x HTTPException is derived from Response and have all mentioned methods already.

**Comment by derlih** [comment]
@asvetlov 
> set_cookie() and del_cookie() should update headers immediately,

Is this requirement strict? Even if `HTTPException` will have no `prepare()`?

**Comment by asvetlov** [comment]
Do you mean that `headers['Cookie']` is not updated before `StreamResponse.prepare()` call?

You are right, perhaps we should keep the consistency here.

**Comment by derlih** [comment]
I mean in the code:
https://github.com/aio-libs/aiohttp/blob/488b375a86e02bc55587550e2360e154acd55131/aiohttp/web_protocol.py#L447-L463

The data is copied from `HTTPException` to `Response`. Cookies can be copied as well. And `prepare()` will be called on that response instance.

**Comment by asvetlov** [comment]
Ok.

**Comment by derlih** [comment]
@asvetlov can this issue be closed?
