### ISSUE TITLE
How to detach/(re)attach AppRunner to a Site ?

### ISSUE THREAD

**Issue by rmedaer** [aio-libs/aiohttp#4304]
I would like to detach an application (actually its runner) from a given site. Then attach a new Application to the same site **without closing it**.

The purpose is to implement a kind of "reload" of my daemon by killing the current Application and create a new one that I can attach to my server.

Currently I was using `make_handler` API to create an handler that I can connect to my server. However `make_handler` has been removed.

**Comment by asvetlov** [comment]
`site.stop()` / `site.start()` could make what do you want.
I didn't test this approach though.

**Comment by rmedaer** [comment]
> site.stop() / site.start() could make what do you want.

Actually I **don't** want to kill my site (aka TCP/UNIX/... server). By stopping the site it will kill my listening socket.

**Comment by asvetlov** [comment]
got you.
Not sure if it is in the aiohttp scope.
How other python frameworks solve this kind of reloading without shutting down the listening socket?

**Comment by rmedaer** [comment]
> Not sure if it is in the aiohttp scope.

Because aiohttp is now managing the sockets "exclusively" through the `Site` abstraction, I guess it's in the scope of aiohttp. Here "exclusively" means: I'm not able anymore to use aiohttp without `Site`s since `make_handler` disappeared.

IMO we should have APIs in `Site`s to implement this kind of feature.

**Comment by asvetlov** [comment]
What other frameworks support this mode?

**Comment by rmedaer** [comment]
Tornado for instance. You can create an `Application` and use it as `handler` for any transport.
Indeed there is some helpers to create and connect easily a socket. Otherwise it's up to you (as user) to   connect the handler (here the Application) and one (or multiple) sockets (transport in Python async "terminology").

**Comment by rmedaer** [comment]
Good news, I found a way to implement it without any changes in aiohttp!

[On `runner.setup()`, you create the "Server" itself](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_runner.py#L239) which is the handler I need to assign to my socket.

So the procedure I implemented is:

1. Create a `AppRunner` with the `Application`
2. Call `runner.setup()`
3. Use `runner.server` reference for `loop.create_server`

#### If I want to (re)start a (new) socket with the `Application`

1. I can "detach" the app by stopping my server socket without killing the Application it-self
2. I can "reattach" my application with `runner.server` to a new server socket

#### If I want to reload a new `Application` without killing the socket

1. I can assign a proxy function to the server which will switch between the previous and the new application
