### ISSUE TITLE
aiohttp 0.17 release plan

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#431]
I believe we have big enough list in our `CHANGES.txt` for publishing new release.
What open issues do you want implement before releasing?
Let's make a list if needed.

**Comment by fafhrd91** [comment]
Let's do that by the end of next week, I'd like to work on routing subsystem

**Comment by asvetlov** [comment]
@fafhrd91 ok, let me know when you will be ready.

**Comment by asvetlov** [comment]
As I see new routing system and signals are not ready yet but we have a lot of pending changes waiting for new release.

I suggest making cut-off and release implemented bugfixes/features right now.

**Comment by fafhrd91** [comment]
ok

**Comment by asvetlov** [comment]
Done
