### ISSUE TITLE
Not able to post files and data at the same time and 'FormData' object is not subscriptable

### ISSUE THREAD

**Issue by sathia-musso** [aio-libs/aiohttp#4316]
## Long story short

I need to post files along with data

## Actual behaviour

I can't get to post anything because i get "FormData' object is not subscriptable"
also, I'm not sure if that's the correct way to send data along with files. 
any help appreciated 

## Steps to reproduce

        from aiohttp import FormData

        try:

            if files:
                d = FormData()
                for i in files:
                    d.add_field(i, files[i], content_transfer_encoding='base64')

                for i in data:
                    d.add_field(i, data[i])
                    data = d

            async with aiohttp.ClientSession() as session:
                async with session.post(url,
                                        data=data,
                                        headers=headers,
                                        proxy=self.proxy_url,
                                        proxy_headers=self.lpm_proxy) as res:

`

## Your environment

aiohttp: 3.6.2 python  3.7.4, osx catalina

**Comment by webknjaz** [comment]
I'm pretty sure that you just don't understand what you do here:
```python
            for i in data:
                d.add_field(i, data[i])
                data = d
```

**Comment by sathia-musso** [comment]
oh my... 
sorry i was blind 

anyways, is this the correct way to send files and data? 
thank you and sorry again

**Comment by asvetlov** [comment]
yes

**Comment by sathia-musso** [comment]
thanks for the reply, i was being carried away because I was sending not str headers. that gave an error and in turn i became code blind. is it correct that all headers must be strings? it seems to be true only if you're using FormData. cheers and thanks for the great library

**Comment by asvetlov** [comment]
Thanks.
Headers are always strings in aiohttp
