### ISSUE TITLE
Does web.FileResponse prevent sending some Content-Type's?

### ISSUE THREAD

**Issue by XCanG** [aio-libs/aiohttp#4319]
I have a function, what return several file types, however if file is javascript, ~~FileReader~~ FileResponse send header mime type as `plain/text` and that script won't load in browser (error in console about mime type). Other files such as images, css return with proper mime type (or I don't find any in particular with this issue).

**Comment by asvetlov** [comment]
aiohttp has no `FileReader` object.

**Comment by XCanG** [comment]
Oh, I typo in description, as I said in title, it `web.FileResponse`

**Comment by hh-h** [comment]
Please check this example, it works as expected.
```python
from aiohttp import web


async def download(request):
    return web.FileResponse("test.js")


def main():
    app = web.Application()
    app.add_routes([web.get('/download', download)])
    web.run_app(app, port=8090)


if __name__ == '__main__':
    main()
```

![image](https://user-images.githubusercontent.com/8166963/68201829-92590280-ffd3-11e9-9e2f-9d31b4de8267.png)

**Comment by asvetlov** [comment]
aiohttp uses `mimetypes.guess_type()` to select Content-Type.
Some OS can have this table not full.

You always can pass `headers={'Content-Type': 'text/awesome'}` argument to override the default behavior.

I guess the issue can be closed.

**Comment by XCanG** [comment]
Oh, that what the problem what causing this, `mimetypes` have problem with detecting proper extension:
```python
>>> mimetypes.guess_type("upload.css")
('text/css', None)
>>> mimetypes.guess_type("upload.js")
('text/plain', None)
```
That's weird issue. It looks like I will need to write my own wrapper instead.
