### ISSUE TITLE
DeprecationWarning: Changing state of started or joined application is deprecated

### ISSUE THREAD

**Issue by albertodonato** [aio-libs/aiohttp#4326]
## Long story short

I'm seeing something very similar as #1947.

In my app setup I connect to the database in an `on_startup` signal (which is what https://docs.aiohttp.org/en/stable/web_advanced.html#background-tasks suggests).

Is this no longer the right way to perform tasks at application startup?

## Expected behaviour

No warning should be raised.

## Actual behaviour

When running tests I get a warning like:

```python-traceback
DeprecationWarning: Changing state of started or joined application is deprecated
    app["db"] = engine
```

## Steps to reproduce

```python
def create_app():
    app = web.Application()
    app.on_startup.append(_create_db)
    app.on_cleanup.append(_close_db)
    return app

async def _create_db(app: Application):
    app["db"] = await create_engine(DSN)
```

## Your environment

- Ubuntu 18.04
- Python 3.6.8
- aiohttp 3.6.2

**Comment by webknjaz** [comment]
Of the top of my head, you could try doing smth like:
```python
async def _setup_db_cm(app: Application):
    app['mutable_state']['db'] = await create_engine(...)
    yield
    app['mutable_state']['db'].close()
    await app['mutable_state']['db'].wait_closed()
    del app['mutable_state']['db']

app = web.Application()
app['mutable_state'] = {}
app.cleanup_ctx.append(_setup_db_cm)
```
(which uses a [cleanup context] that's recommended for implementing setup+tear down combos)

But let's wait what Andrew has to say about it.

P.S. There's also "latest" docs from newer/devel aiohttp versions: https://docs.aiohttp.org/en/latest/web_advanced.html#background-tasks (but this section isn't different there).

[cleanup context]: https://docs.aiohttp.org/en/latest/web_advanced.html#cleanup-context

**Comment by asvetlov** [comment]
No, the code should not generate a warning

**Comment by albertodonato** [comment]
@webknjaz ah, TIL about `cleanup_ctx`, that's nicer than having separate functions.
Still, the `"mutable_state"` key is a bit of a hack, IIUC it should be possible to set keys directly on the app?
if pre-setting a key is the preferred way, maybe an `app.mutable_state` dict could be added as a place for setting runtime attributes?

**Comment by webknjaz** [comment]
Well, as Andrew said above, the old way is still supported so what you're facing is probably a bug and it'd be helpful if you provided more details/traceback so that we could locate where this is happening and why. PR is also welcome.

**Comment by albertodonato** [comment]
A simple reproducer is the following:

```
from aiohttp import web
import warnings

warnings.simplefilter("always")


async def ctx(app):
    app["foo"] = "bar"
    yield
    del app["foo"]


app = web.Application()
app.cleanup_ctx.append(ctx)

web.run_app(app)
```
which produces
```
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
^Cw.py:10: DeprecationWarning: Changing state of started or joined application is deprecated
  del app["foo"]
```
(after Ctrl-c is pressed)

**Comment by asvetlov** [comment]
The last example is invalid: there is no reason to call `del app["foo"]`.
Implicit `del app` call will eliminate the whole application context.

**Comment by asvetlov** [comment]
An example for reproducing the problem with `on_startup` / `on_cleanup` would help a lot with pinning the problem

**Comment by albertodonato** [comment]
It seems if I don't `del` the attribute I can't reproduce the issue anymore niether with `cleanup_ctx` nor with `on_startup`/`on_cleanup`. Closing the issue. thanks

**Comment by CMCDragonkai** [comment]
I'm seeing this error with dask distributed. If I don't explicitly delete with `del app["dask_client"]` it results in an error later with dask complaining that the loop no longer exists. So I have to do an explicit deletion ahead of time.

This is the message I get:

```
Exception ignored in: <function Client.__del__ at 0x7f7c8f6237a0>
Traceback (most recent call last):
  File "/nix/store/lppchp3d9hmpav0g14c5xgaldl2kgfg5-python3.7-distributed-2.23.0/lib/python3.7/site-packages/distributed/client.py", line 1189, in __del__
    self.close()
  File "/nix/store/lppchp3d9hmpav0g14c5xgaldl2kgfg5-python3.7-distributed-2.23.0/lib/python3.7/site-packages/distributed/client.py", line 1402, in close
    if self.asynchronous:
  File "/nix/store/lppchp3d9hmpav0g14c5xgaldl2kgfg5-python3.7-distributed-2.23.0/lib/python3.7/site-packages/distributed/client.py", line 802, in asynchronous
    return self._asynchronous and self.loop is IOLoop.current()
  File "/nix/store/svhjdxqhi8izmdh6ncgxhmycxwal7bzx-python3.7-tornado-6.0.4/lib/python3.7/site-packages/tornado/ioloop.py", line 265, in current
    loop = asyncio.get_event_loop()
  File "/nix/store/cpzs1hpwzs23c41haa4dap0zjfx6xych-python3-3.7.9/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.
```
