### ISSUE TITLE
Will there be support for anything other than regular expressions in url?

### ISSUE THREAD

**Issue by heckad** [aio-libs/aiohttp#4347]
UUID support is very necessary because write `'[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}'` in url very ugly.

**Comment by asvetlov** [comment]
I don't think that UUID requires special dedicated support.
Regex solves it perfectly fine.
To reduce the redundancy feel free to use a constant, e.g.
```
UUID = '[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}'

@route_def.get('/{param:'+UUID+'}'}
async def handler(request):
    ...
```

**Comment by heckad** [comment]
Linter does not allow the use of + for concat strings. Use the format method for it, not useful because `{}` need duplicate base `{}`. Perhaps for these reasons frameworks add support types in URL.

**Comment by asvetlov** [comment]
Add a complex logic with types support (I don't see the full proposal yet, BTW) to satisfy some linter?
Are you kidding?
Please find a more weighty argument.

**Comment by asvetlov** [comment]
won't fix, sorry
