### ISSUE TITLE
Request.GET drops empty params

### ISSUE THREAD

**Issue by sk-** [aio-libs/aiohttp#436]
Currently `Request.GET` drops empty params. That is if the path is `/get?foo=&bar`, I won't be able to see either `foo` or `bar`

This could be fixed by adding `keep_blank_valus=True` to `parse_qsl` in `Request.GET`, just like it is done for `Request.post`.

**Comment by asvetlov** [comment]
See also #388

**Comment by fafhrd91** [comment]
maybe `keep_blank_valus=True` should be default? what does pyramid do for blank values?

**Comment by sk-** [comment]
Why is `False` a reasonable default for `keep_blank_values` in the `GET` method and `True` a reasonable default in the `post` method?

We should at least be consistent.

Pyramid does return the empty params. See `parse_qsl_text` in https://github.com/Pylons/webob/blob/master/webob/compat.py#L103.

**Comment by asvetlov** [comment]
I'm inclined to making `keep_blank_values=True` without providing a way to change new behavior.

**Comment by kxepal** [comment]
@sk- 
What's the use case for empty query params? If value doesn't matter, why not accept any? Especially if RFC clearly defines query part as carrying _identifying information in the form of "key=value" pairs_. Keyword _pairs_.

The use case of empty params for POST is HTML form submission where not all the fields may be filled by user.

**Comment by asvetlov** [comment]
@kxepal I may want to pass empty string for parameter

**Comment by sk-** [comment]
The same could be argued then for GET, you can also have forms using get (like search forms). In that case, the value is the empty string `?key=` (I'm not that concerned about the alternative without the `=` sign, `?key`).

If you not allow the case `?key=`, then how would you express that the value is empty?

Note also, that the RFC does not specify any format for the query string. It says:
`... query components are often used to carry identifying information in the form of "key=value" pairs ...`. See https://tools.ietf.org/html/rfc3986#section-3.4

In my particular use case I'm not checking for presence in which any value could do the trick. Rather I have a middleware that will log the request only if there's a specific field set (It could be empty).

**Comment by asvetlov** [comment]
Done. 
I believe it doesn't bring backward incompatibilities.
