### ISSUE TITLE
Make `async def web._run_app` public.

### ISSUE THREAD

**Issue by jonathanslenders** [aio-libs/aiohttp#4367]
I wonder whether it would make sense to make the `web._run_app` function public. (This would require renaming.)

In my situation, I'm unable to call `run_app` (without underscore), because running the server requires a database, which is an async context manager. Something like this:

```python
async with database() as db:
    server = MyServer(db)
    await server.serve()  # This calls `_run_app`
```

That works well, but it doesn't sound right having to call an internal API for this.

Thanks!

**Comment by asvetlov** [comment]
I wonder if you want to modify logs and do other top-level things.

Maybe https://github.com/aio-libs/aiohttp/issues/2746 fits your needs good enough?
Usually, people know pretty well what host/port they want to server, using a runner for configuring things is not a complex task.

**Comment by jonathanslenders** [comment]
Hi @asvetlov, thanks for the quick reply.
I do modify the logs, and start a few other background tasks as well.

#2746 would do it. Closing this as duplicate.
