### ISSUE TITLE
how to parse the param from url？

### ISSUE THREAD

**Issue by wsshopping** [aio-libs/aiohttp#437]
Now，this is handler in my server：

```
@get('/test/getAssetHot')
def api_get_blog(request, *, m):
    print (request._match_info)
    return 0
```

and my url request is ：http://192.168.1.1:9000/test/getAssetHot?num=1&page=2

how can i get the param （num and page） from url？
any answer will be useful  thanks

**Comment by popravich** [comment]
Hi,
In your case use `request.GET` (see [request reference](http://aiohttp.readthedocs.org/en/stable/web_reference.html#aiohttp.web.Request.GET))

``` python
def api_get_blog(request, *, m):
    print(request.GET.items())

```

**Comment by wsshopping** [comment]
thank you very much，that is exactly what i need
