### ISSUE TITLE
web.Request and web.Response are no longer weak referenceable

### ISSUE THREAD

**Issue by Fogapod** [aio-libs/aiohttp#4370]
## Long story short

https://github.com/aio-libs/aiohttp/pull/3942 added `__slots__` to request and response classes. This made it impossible to create weak references to them.
In some cases this might be useful. Example: https://github.com/getsentry/sentry-python/issues/560

Possible solution is adding `__weakref__` to `__slots__` in `web.BaseRequest` and `web.StreamResponse`.

## Expected behaviour

web.Request and web.Response to be valid targets for weak references.

## Actual behaviour

web.Request and web.Response are no longer valid targets for weak references.

## Steps to reproduce

```python
import weakref

wekref.ref(request)
# TypeError: cannot create weak reference to 'Request' object
```

**Comment by frederikaalund** [comment]
Duplicate of #4368.
