### ISSUE TITLE
Deflate compatibility issue with websocket-sharp

### ISSUE THREAD

**Issue by CaledoniaProject** [aio-libs/aiohttp#4381]
## Long story short

I just moved from [https://websockets.readthedocs.io/en/stable/intro.html](websockets) to aiohttp, then I found aiohttp is not fully compatible with [websocket-sharp](https://github.com/sta/websocket-sharp)

I'm using the [websocket handler example here](https://docs.aiohttp.org/en/stable/web_quickstart.html#websockets), it prints every message received:

```
async for msg in ws:
            if msg.type == aiohttp.WSMsgType.TEXT:
                print(msg.data)
```

When I enable deflate Compression in websocket-sharp, all message received is EMPTY, the msg.data length is zero:

```
WebSocket tmp   = new WebSocket(url);
tmp.Compression = CompressionMethod.Deflate;
```

The websockets library has totally no issue with it. 

If I don't enable Deflate, both websockets and aiohttp library works fine.

## Questions

1. Is compression enabled by default in aiohttp? There's no document about it
2. Was it a bug?

**Comment by asvetlov** [comment]
1. WebSocket compression is supported by aiohttp by default
2. I don't know is it aiohttp bug or not. Need a hero for investigation.

**Comment by CaledoniaProject** [comment]
@asvetlov Is compression is enabled by default? Then I don't need to set Deflate explicitly in websocket4sharp.

**Comment by asvetlov** [comment]
I assume you are asking about aiohttp server.
The server supports https://tools.ietf.org/html/rfc7692 If a client enables it during a handshake.
