### ISSUE TITLE
is there a way to read proxy-headers after a request?

### ISSUE THREAD

**Issue by carogno** [aio-libs/aiohttp#4382]
Hi, i've been looking thru the code and haven't found anything about it. the proxy I'm using has some headers after any request that I should be able to read. i only saw headers() and raw_headers() 

thanks!

**Comment by asvetlov** [comment]
No.
I'm curious what tool supports the requested feature?

**Comment by webknjaz** [comment]
@carogno is this question about the client or the server side?

@asvetlov if the question is about the client connecting to an aiohttp app, they should be able to just grab the request headers, right?

**Comment by asvetlov** [comment]
I assume the question is about client API.
@carogno knows better, sure!

**Comment by carogno** [comment]
hello, yes, this is about the client API. I'm using a proxy server that adds some headers when returning a request. let's say it's something like `X-proxy-request_nr: 3425`, I wish to retrieve this value along with other proxy headers returned. I don't know if any other library supports this but it would be definitely good to have for my project. 
thanks again

**Comment by asvetlov** [comment]
A proxy server returns a request to who?
I'm lost.
What exact headers are you trying to find?
What are you did try already?

**Comment by carogno** [comment]
So I've investigated a little more on the issue and it seems it's something more difficult and probably out of scope for this library. I'm using a local proxy server which in turn uses another proxy. This second server returns the headers I'm looking for to the first, but then they are not forwarded to the python client. I'm a bit at loss but I'll keep looking. Sorry if I didn't catch this first but I just thought they were proxy headers

**Comment by asvetlov** [comment]
If a response header is swallowed by the proxy server the library cannot see it sure :)
Perhaps we can close the issue.

**Comment by webknjaz** [comment]
@carogno unless your proxy server attaches those headers to the HTTP response (given that no proxy in the chain in between strips them off) there's nothing we can do. If the information isn't transmitted over HTTP, the client cannot magically expose it to you.
OTOH you should have full access to everything that is transmitted over HTTP already. Therefore, I'm closing this issue.

**Comment by carogno** [comment]
let's say I need to read these headers, any chance? 

```
For HTTPS the IP is in the CONNECT response header x-hola-ip Example for Proxy Peer IP of 5.6.7.8:
Request
CONNECT example.com:80 HTTP/1.1
Host: example.com:80
Accept: */*
Response:
HTTP/1.1 200 OK
Content-Type: text/html
x-hola-ip: 5.6.7.8
```

https://luminati.io/faq#knowing-ip

**Comment by asvetlov** [comment]
CONNECT doesn't belong to the wrapped HTTP message, it is just another message that upgrades the protocol. So, it is a connection property.
I doubt if you can extract this from aiohttp structures.
