### ISSUE TITLE
Aiohttp.web unsupported for 3.8

### ISSUE THREAD

**Issue by XuaTheGrate** [aio-libs/aiohttp#4390]
## Long story short

Aiohttp.web servers on 3.8 appear to refuse all requests. Tested with 3.7 and it works fine.

## Expected behaviour

For it to handle requests normally.

## Actual behaviour

The server doesn't even receive the request, and the client returns with a ServerDisconnectedError

## Steps to reproduce

```python
from aiohttp import web


routes = web.RouteTableDef()


@routes.get("/")
async def hello(request):
    return web.Response(text="Hi!")


app = web.Application()
app.add_routes(routes)
web.run_app(app)
```
## Your environment

- Aiohttp 3.6.2 on both ends
- Python 3.8.0
- Debian 9.11

**Comment by webknjaz** [comment]
It works in our CI. You should provide a full reproducer so that we could understand what the problem is for you.

Your current message seems to imply that the issue is on the client-side but the snippet you provided implements a server. This doesn't make sense to me at all.

**Comment by XuaTheGrate** [comment]
The client is just making a request. With aiohttp, it raises a ServerDisconnectedError, with requests it raised some other disconnection error. Having the server on 3.7 fixes the problem. I don't see what I'm missing.

**Comment by webknjaz** [comment]
Does the client or the server raise that exception?

**Comment by webknjaz** [comment]
It'd be more useful if you posted logs here

**Comment by XuaTheGrate** [comment]
Unsure what logs you are referring to here. Setting the level to `logging.DEBUG` yields nothing from aiohttp.

And it is the client that raises the error.

**Comment by webknjaz** [comment]
Does the same client version raise this error with a different aiohttp version on the server?

**Comment by XuaTheGrate** [comment]
Yes, all versions of aiohttp raise this error.
Side note that requests also raises its own error too.

**Comment by webknjaz** [comment]
Could you please provide a reproducer in a docker container?

**Comment by XuaTheGrate** [comment]
I'm afraid not, I have never used any kind of docker container before, and also do not have access to my computer for a while.
If you don't mind waiting approx. two weeks I can get back to you on the docker thing.

**Comment by rugleb** [comment]
We already use `aiohttp 3.6.2` with `python 3.8` in production.
Everything's fine.

**Comment by XuaTheGrate** [comment]
Sorry for the late reply, but during setup I had re-installed Python 3.8 and the issue appears to have been fixed. Unsure if it was a bad Python install or otherwise, but I can't seem to reproduce the issue anymore.
