### ISSUE TITLE
Http exception with list on body

### ISSUE THREAD

**Issue by rafa-acioly** [aio-libs/aiohttp#4403]
## Long story short
I've created the middleware to handle errors and i'm "catching" every instance of `web.HTTPException` so i can format the response payload.
In a point of my code i raise an `HTTPBadRequest` and i want to pass a list to it but it doesn't work.

>ValueError: Unsupported body type <class 'list'>

## Expected behaviour

Can i get the errors list and retrieve it on my json response?

## Actual behaviour

>ValueError: Unsupported body type <class 'list'>

## Steps to reproduce

```py
@middleware
async def error_middleware(request, handler):
    try:
        return await handler(request)
    except web.HTTPException as error:
        error_response = {
            'error_message': error.text,
            'error_reason': error.reason,
            'error_detail': error.body
        }

        return json_response(
            data=error_response,
            status=_error.value,
            reason=_error.description
        )
    except Exception as generic_error:
        logger.exception(f'Generic erro:{generic_error}')
        raise
```

```py
raise HTTPBadRequest(body=["key x needs to be greater than 0", "key y Invalid datetime format"])
```

## Your environment

aiohttp==3.5.4
python==3.7

IMPORTANT: server

**Comment by asvetlov** [comment]
`body` is for **bytes**, it doesn't accept arbitrary Python object by design.
The same is for `text`.
Please use the proper argument type.

**Comment by rafa-acioly** [comment]
@asvetlov looking the docs. i didn't see anything about this, the only parameters that exist only accept `str`. which argument are you referring?

**Comment by asvetlov** [comment]
You used the deprecated `body` argument, this parameter was dropped from docs.
Anyway, `list` is acceptable nowhere.
