### ISSUE TITLE
Task was destroyed but it's pending

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#4408]
On master, I see outputs from `run_app()` like follows:
```
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<RequestHandler.start() done, defined at /home/andrew/.virtualenvs/multidict/lib/python3.8/site-packages/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f8822ffef10>()]>>
```
I suspect it happens on errors and keepalive closing in `web_protocol.py`.
The message should go.

**Comment by marco-c** [comment]
Is there a way for us to avoid this error? Or is a fix in aiohttp strictly needed?

**Comment by asvetlov** [comment]
This is the regression of unreleased aiohttp version.

**Comment by marco-c** [comment]
Thanks for making me notice we were using 4.0.0a1... :P

**Comment by MaxIakovliev** [comment]
Same issue happens to me:
Running python 3.7
aiohttp -latest

```shell
[2020-03-18 11:39:36,763] [ERROR] [decoder.py:353 - raw_decode() ] Task was destroyed but it is pending!

task: <Task pending coro=<RequestHandler.start() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f02025e2850>()]>>

[2020-03-18 11:39:36,763] [ERROR] [decoder.py:353 - raw_decode() ] Task was destroyed but it is pending!

task: <Task pending coro=<RequestHandler.start() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f0202606a10>()]>>

[2020-03-18 11:39:36,763] [ERROR] [decoder.py:353 - raw_decode() ] Task was destroyed but it is pending!

task: <Task pending coro=<RequestHandler.start() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f02012b9450>()]>>

[2020-03-18 11:39:36,764] [ERROR] [decoder.py:353 - raw_decode() ] Task was destroyed but it is pending!

task: <Task pending coro=<RequestHandler.start() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f02012b92d0>()]>>

[2020-03-18 11:39:36,764] [ERROR] [decoder.py:353 - raw_decode() ] Task was destroyed but it is pending!

task: <Task pending coro=<RequestHandler.start() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f02023f9910>()]>>

[2020-03-18 11:39:36,764] [ERROR] [decoder.py:353 - raw_decode() ] Task was destroyed but it is pending!

task: <Task pending coro=<RequestHandler.start() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f02023f9a90>()]>>

[2020-03-18 11:39:36,764] [ERROR] [decoder.py:353 - raw_decode() ] Task was destroyed but it is pending!

task: <Task pending coro=<RequestHandler.start() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f0201290f10>()]>>

[2020-03-18 11:39:36,765] [ERROR] [decoder.py:353 - raw_decode() ] Task was destroyed but it is pending!

task: <Task pending coro=<RequestHandler.start() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f0201288b90>()]>>

[2020-03-18 11:39:36,765] [ERROR] [decoder.py:353 - raw_decode() ] Task was destroyed but it is pending!

task: <Task pending coro=<RequestHandler.start() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f0201288210>()]>>
```

**Comment by semiworks** [comment]
Same for me:

also python 3.7 / aiohttp -latest

`
2020-03-23 08:49:54,914 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() done, defined at ./libs/aiohttp/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e44fbdf8>()]>>
2020-03-23 08:49:54,914 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() done, defined at ./libs/aiohttp/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e44fbfa8>()]>>
2020-03-23 08:54:41,711 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() running at ./libs/aiohttp/aiohttp/web_protocol.py:461> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e450b1c8>()]>>
2020-03-23 08:54:41,711 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() running at ./libs/aiohttp/aiohttp/web_protocol.py:461> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e455ea68>()]>>
2020-03-23 08:54:41,711 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() running at ./libs/aiohttp/aiohttp/web_protocol.py:461> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e445f168>()]>>
2020-03-23 08:54:41,712 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() running at ./libs/aiohttp/aiohttp/web_protocol.py:461> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e455e5b8>()]>>
2020-03-23 08:54:41,712 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() running at ./libs/aiohttp/aiohttp/web_protocol.py:461> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e44a9d68>()]>>
2020-03-23 08:54:41,712 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() done, defined at ./libs/aiohttp/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e44fbd68>()]>>
2020-03-23 08:54:41,712 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() done, defined at ./libs/aiohttp/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e44fbfa8>()]>>
2020-03-23 08:54:41,712 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() done, defined at ./libs/aiohttp/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e44fbca8>()]>>
2020-03-23 08:54:41,713 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() done, defined at ./libs/aiohttp/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e4529f18>()]>>
2020-03-23 08:54:41,713 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() done, defined at ./libs/aiohttp/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e450bcd8>()]>>
2020-03-23 08:54:41,713 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() done, defined at ./libs/aiohttp/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e4529f78>()]>>
2020-03-23 08:54:41,713 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() done, defined at ./libs/aiohttp/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e4529108>()]>>
2020-03-23 08:54:41,713 ERROR    Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() done, defined at ./libs/aiohttp/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe6e44a96d8>()]>>
`

**Comment by technillogue** [comment]
this is still an issue for us, python3.9 / aiohttp 3.7.4.post0


```
ERROR base_events:1738: Task was destroyed but it is pending!
task: <Task pending name='Task-82' coro=<RequestHandler.start() done, defined at /app/aiohttp/web_protocol.py:437> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f724eeaab20>()]>>
```

**Comment by webknjaz** [comment]
As Andrew said earlier, wait for v4.0.
