### ISSUE TITLE
can not find a way to creat a cookie

### ISSUE THREAD

**Issue by viponedream** [aio-libs/aiohttp#4418]
`requests` can easy to make a cookie like this:( with `domain` and `name`, `value`, `path`)

```python
c = requests.cookies.create_cookie(name, value, domain=domain, path=path)
requests_session.cookies.set_cookie(c)
```

===========
in aiohttp, how to set the cookie?
```python
    cookie_jar = aiohttp.CookieJar(unsafe=True)
    session = aiohttp.ClientSession(cookie_jar=cookie_jar)
```
the `CookieJar` only has a `update_cookies` method

**Comment by viponedream** [comment]
finally , this works
```python
from aiohttp.web_response import StreamResponse
 c = StreamResponse()
 c.set_cookie(_name, _value, domain=_domain, path=_path, max_age=_max_age)
aiohttp_session.cookie_jar.update_cookies(c.cookies)
```

**Comment by webknjaz** [comment]
Hello, please post such questions on StackOverflow and/or mailing lists, or in the Gitter chat. The GitHub issue tracker should only list bugs.
