### ISSUE TITLE
HTTPNotModified 304 must have no body 

### ISSUE THREAD

**Issue by PolarNick239** [aio-libs/aiohttp#442]
In the following code:

``` python
response = web.HTTPNotModified(headers={'ETag': etag})
```

reponse will be constructed with body = b'304: Not Modified'
But empty body expected.
### RFC:

```
... it responds with a special status code (usually, 304 (Not Modified)) and no entity-body ...
```

http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.3
### Workaround:

``` python
response = web.HTTPNotModified(headers={'ETag': etag}, body=b'')
```

For example QT client with small probability on such responses raises exception, that connection was closed. :(

**Comment by asvetlov** [comment]
Fixed in by a0a9d32
