### ISSUE TITLE
Aiohttp stream 1 was not closed cleanly when serving static files

### ISSUE THREAD

**Issue by enugentdt** [aio-libs/aiohttp#4426]
## Long story short

Essentially, when I have static content served through aiohttp using the following code:

```python
app.add_routes([web.static('/static', 'static')])
```

the server throws an HTTP2 error when querying the files:

```
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

## Expected behaviour

This should serve content as expected over HTTP2, or downgrade to HTTP1 if it cannot handle it.

## Actual behaviour

It closes the connection early, resulting in the content not being delivered properly to the client.

## Steps to reproduce

Create a basic server, and use the above mentioned line of code to serve a static file. If the client requests over HTTP2, it will fail.

## Your environment

Seems to be pretty agnostic, but mainly happens on Python 3.7 on Linux (CentOS, but also in Alpine Docker images). Latest version of aiohttp server.

Thanks!

**Comment by asvetlov** [comment]
aiohttp doesn't support HTTP/2 yet at all.
Why do yu expect that static files should work with it?

**Comment by enugentdt** [comment]
It looks like this issue is completely me being an idiot. I identified aiohttp static files as the commonality between the servers that were displaying the issue, but it wasn't actually aiohttp's fault. My apologies!

**Comment by asvetlov** [comment]
no problem!
