### ISSUE TITLE
cleanup_ctx doesn't work as expected.

### ISSUE THREAD

**Issue by Dnomin** [aio-libs/aiohttp#4430]
## Long story short
`cleanup_ctx` doesn't work as expected.

## Expected behaviour
[aiohttp docs](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.Application.cleanup_ctx)
```python
async def context(app):
    # do startup stuff
    yield
    # do cleanup
```

## Actual behaviour
startup stuff runs, but cleanup don't

## Steps to reproduce
`background_tasks.py`
```python
async def debug_1(app):
    while True:
        await asyncio.sleep(1)
        logger.info('debug_1')


async def debug_2(app):
    while True:
        await asyncio.sleep(3)
        logger.info('debug_2')


async def background_tasks(app):
    tasks = [asyncio.create_task(future(app)) for future in (debug_1, debug_2)]

    logger.info(f'Gathering tasks {tasks}')
    asyncio.gather(*tasks)
    yield
    logger.info(f'Closing tasks {tasks}')
    for task in tasks:
        task.cancel()
```
`app.py`
```python
...
app.cleanup_ctx.append(background_tasks)
...
```

## Your environment

`docker`: `python:3.7-slim`
`aiohttp = "==3.6.2"`

**Comment by asvetlov** [comment]
Sorry, I don't follow the problem.
Could you convert your example to something executable?

**Comment by Dreamsorcerer** [comment]
There's a missing await atleast in that code. The documentation now includes an exact example of this which can be copy/pasted:
https://docs.aiohttp.org/en/stable/web_advanced.html#complex-applications
