### ISSUE TITLE
Don't unqoute request path on server

### ISSUE THREAD

**Issue by tdriscoll** [aio-libs/aiohttp#444]
I would like to be able to differentiate between an escaped slash "%2F" and the real thing "\".

My use case is to match a URL that contains N number of key value pairs. The values can be any string, so it would be escaped when sent to the aiohttp server. 
For example, if I had the following:
`{'key1': 'value\1', 'key2': 'value2'}`
Then I would use this URI:
`\key1\value%2F1\key2\value2` 

The regex i was using `(([^{}/]+/){2})*([^{}/]+/[^{}/]+)` does not work because the path is unqouted before being matched.

Even if I get the regex to match, the match_info in the request object is unqouted so I have no way of parsing out the key values (I get \key1\value\1\key2\value2`).

FWIW, if I change: 
`self._path = unquote(res.path)` to `self._path = res.path` in Request it seems to work for me.

**Comment by tdriscoll** [comment]
Oops. I was looking at 0.16.6. I see the routing is already fixed in master and raw_path is exposed. The only thing is that it unqoutes the match_info.  It would be useful in my case to also expose raw_match_info. That way I don't need to reparse the raw_path. Would you be interested in a PR for that?

**Comment by asvetlov** [comment]
Please try master branch. `raw_path` property should satisfy your requirement: https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web_reqrep.py#L179

**Comment by asvetlov** [comment]
Sorry, I've missed your last message.

About `raw_match_info` -- at first glance it looks clumsy. Let me sleep on it.

**Comment by tdriscoll** [comment]
Well I don't even need `raw_match_info` anymore. Okay if I close this?

**Comment by asvetlov** [comment]
Closed
