### ISSUE TITLE
Why isn't aiodns used?

### ISSUE THREAD

**Issue by vangheem** [aio-libs/aiohttp#4446]
## Long story short

The documentation recommends to install aiodns. Reality is that even though aiodns might be installed, it's forced to not be used: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/resolver.py#L11

## Expected behaviour

aiodns to be used

## Actual behaviour

aiodns is not used

## workaround

Every time you create a `ClientSession`...

```python
from aiohttp.resolver import AsyncResolver

async with aiohttp.ClientSession(
        connector=aiohttp.TCPConnector(resolver=AsyncResolver())) as session:
    pass

```

**Comment by gjcarneiro** [comment]
See #559

**Comment by asvetlov** [comment]
I think @gjcarneiro answered the question.

#4451 can help with enabling aiodns by default on Python 3.8.
If somebody wants to champion the issue -- you are welcome!
