### ISSUE TITLE
websocket miss messages after add other coroutines into the event loop

### ISSUE THREAD

**Issue by yushizhao** [aio-libs/aiohttp#4449]
When I have one thread with one websocket client, everything is fine.
When I add other coroutines into the event loop where the websocket client is, it start to miss messages.
I create a new thread and move those new coroutines into that thread in a new the event loop, still,
the websocket client miss messages.

Am I use the websocket client in a wrong way, can they share the event loop with others?

**Comment by yushizhao** [comment]
updates: create separate threads for other coroutines actually solve the problem.

**Comment by socketpair** [comment]
Please provide minimal application that triggers the bug.

**Comment by yushizhao** [comment]
It's kind of hard to trigger. I think problems are in the other coroutines I have added.
