### ISSUE TITLE
Is break in finally intentional?

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#445]
In low-level server code I see `break` statements inside `finally` blocks like https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/server.py#L290

It looks suspicious: `break` inside `finally` block discards saved exception (see https://docs.python.org/3.5/reference/simple_stmts.html#break). 
I believe `return` should be used instead, it does the same in the case (stop reading incoming data) but it is show the intention much more explicitly.

@fafhrd91 you are author of these lines. Do you remember the motivation for `break` statement?

**Comment by fafhrd91** [comment]
I do not really remember, but good catch let's replace with returns
