### ISSUE TITLE
Can't process form fields + multipart file uploads: Could not find starting boundary

### ISSUE THREAD

**Issue by bitnom** [aio-libs/aiohttp#4473]
I'm trying to process a form that has several fields and multiple file upload fields. I'm re-using the code I already have for uploading a single image and nothing else. I'm trying to adapt it to handle multiple files along with other form fields (Hence the while loop). Function:

```
    async def store_images(self, request, item, image_num):
        reader = await request.multipart()
        pprint(reader)
        while True:
            field = await reader.next()
            
            if field is None or field.filename is None:
                continue
            original_filename = field.filename
            print("filename orig:", original_filename)
            file_extension = str(Path(field.filename).suffix).lower()
            filename = f"{item}_{image_num}{file_extension}"
            if not original_filename:
                return False, "No file chosen", "Try again"
            if file_extension != ".png" and file_extension != '.jpg' and file_extension != '.jpeg':
                return False, "Bad file format", "Only png and jpg images allowed."

            new_path = os.path.join('/images/', filename)
            # You cannot rely on Content-Length if transfer is chunked.
            size = 0
            with open(new_path, 'wb') as f:
                while True:
                    chunk = await field.read_chunk()  # 8192 bytes by default.
                    if not chunk:
                        break
                    #pprint(chunk)
                    if 'acTL' in str(chunk):
                        return False, "Sorry,", "Only static images allowed."
                    size += len(chunk)
                    if size > 1000000:
                        os.remove(new_path)
                        return False, "Too big,", "1MB max."
                    f.write(chunk)
            if file_extension == '.jpg' or file_extension == '.jpeg':
                im = Image.open(new_path)
                im.save(os.path.join('/images/', f"{item}_{image_num}.png"))
            return True, "Image uploaded!", "redirecting"
```

The form tag:
```
<form action="/submit_form" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
```

aiohttp web running on Linux x86_64 Python3

I am getting all the POST data from my fields by the usual request.post() but my file upload function throws:

`Could not find starting boundary b'-----------------------------782338621183287065832555821'`

after passing it the `request` object.

**Comment by bitnom** [comment]
This might be related to https://github.com/aio-libs/aiohttp/issues/3544 but the gists are 404

**Comment by bitnom** [comment]
It appears that calling form.get() before processing the upload causes the error. It also appears that any fields in the HTML before the file input fields will not be made available to form.get() after processing the image.

**Comment by hh-h** [comment]
Hello! You have a better chance of getting help if you attach an example of how to reproduce a bug.

**Comment by asvetlov** [comment]
@TensorTom did not provide enough info to identify a problem

**Comment by bitnom** [comment]
I figured it out. You have to use form.get and chunk process the multipart data in the order in which it is sent to the server. Otherwise, you get the error. It's annoying but since aiohttp is unique to allow this in the first place, I'm not complaining.
