### ISSUE TITLE
Client should accept a json_serialize function which returns bytes

### ISSUE THREAD

**Issue by ZacharyThomas** [aio-libs/aiohttp#4482]
## Long story short

Orjson (https://pypi.org/project/orjson/) dumps returns bytes rather than str. When using it as our serializer, we need to wrap it in a lambda to return a string, which the client library then promptly converts back to bytes. 

```
http_session = aiohttp.ClientSession(json_serialize=lambda x: orjson.dumps(x).decode())
```

## Expected behaviour

The client should accept both bytes and str 

## Actual behaviour

Client throws when using orjson serialization because it returns bytes

## Steps to reproduce

```
>>> import orjson                                                                  
>>> import aiohttp 
>>> import asyncio
>>> loop = asyncio.get_event_loop()                                                                
>>> sesh = aiohttp.ClientSession(json_serialize=orjson.dumps)                      
>>> async def do_post(): 
...      async with sesh.post("google.com", json={"body": "yes"}) as resp:
...        print("ok")

>>> loop.run_until_complete(do_post())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "<stdin>", line 2, in do_post
  File "/Users/zacharysmith/workspace/envs/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/Users/zacharysmith/workspace/envs/lib/python3.7/site-packages/aiohttp/client.py", line 365, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "/Users/zacharysmith/workspace/envs/lib/python3.7/site-packages/aiohttp/payload.py", line 389, in __init__
    dumps(value).encode(encoding),
AttributeError: 'bytes' object has no attribute 'encode'

```

## Your environment
client
aiohttp==3.6.2
python==3.7.5

**Comment by ZacharyThomas** [comment]
@asvetlov Do you think a workable solution would be a major version change which changes the interface of both the Encoder/Decoder to take bytes?

**Comment by derlih** [comment]
@ZacharyThomas 
From the documentation of `json.dumps`: `Serialize obj to a JSON formatted str`.
If I would need to get bytes directly, I would use `json.dump` with `io.BytesIO` as `fp` parameter.

The serialize function that passed as alternative to `json.dumps` IMHO should follow its signature.

**Comment by asvetlov** [comment]
If you need to use non-json compatible encoder  you can use a custom function: `async def load(resp: ClientResponse) -> Any`. The same for dump.

**Comment by stalkerg** [comment]
@asvetlov I disagree with this decision. orjson authors suppose what for blobs bytes it's the more correct type and I agree. 
Interface inside Python json library is not a standard, it's just one of implementation. 
For example if I want to use messagepack (it's binary) instead json I can't do it and here bytes have no alternative.

**Comment by niksabaldun** [comment]
I also believe this is not a good decision. Standard json library interface is just plain wrong, there is no reason whatsoever to serialize JSON to string (on rare occasions when you do want it, you can just utf-8 decode bytes). Orjson is the only library that does it right.

**Comment by stalkerg** [comment]
@niksabaldun can we push such a discussion to the python core team?
@asvetlov I ask to reopen this. Please. My example with MessagePack is still valid.

**Comment by niksabaldun** [comment]
@stalkerg I currently don't have the time for that myself. Also, the json module has been there for long time and so much code depends on it. I doubt they would consider a breaking change.

**Comment by AdamBajger** [comment]
The path forward often requires old structures to be tore down. I believe the fear of breaking changes is not a relevant reason for staying back. I suppose there are deprecation mechanisms for such things.

**Comment by stalkerg** [comment]
@niksabaldun because `loads` have already accept bytes I made proposal to add `dumpb` so you can join the conversation.

**Comment by Olegt0rr** [comment]
> If you need to use non-json compatible encoder you can use a custom function: `async def load(resp: ClientResponse) -> Any`. The same for dump.

Why should we do the unnecessary utf-8 encode/decode? :( 

P.S.: as workaround I manually construct `BytesPayload`

**Comment by Mooth34** [comment]
```
def orjson_dumps(obj):
    return orjson.dumps(obj).decode('utf-8')
```

Then works:

`aiohttp.ClientSession(json_serialize=orjson_dumps)`
