### ISSUE TITLE
Cant create multiple unix domain sockets, as per Supervisord Docs

### ISSUE THREAD

**Issue by binrebin** [aio-libs/aiohttp#4490]
## Long story short
I cant achieve multiple unix domain socket with Supervisord as per Aiohttp deployment documentation. Kindly update or suggest a possible solution..
Below is the aiohttp deployment doc extract.

NGINX part
```
http {
  upstream aiohttp {
    # Unix domain servers
    server unix:/tmp/example_1.sock fail_timeout=0;
    server unix:/tmp/example_2.sock fail_timeout=0;
    server unix:/tmp/example_3.sock fail_timeout=0;
    server unix:/tmp/example_4.sock fail_timeout=0;
  }
server {
        listen 80;
location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect off;
      proxy_buffering off;
      proxy_pass http://aiohttp;
}
}
```
AND Supervisord part

```
[program:aiohttp]
numprocs = 4
numprocs_start = 1
process_name = example_%(process_num)s

command=/path/to/aiohttp_example.py --path=/tmp/example_%(process_num)s.sock

user=nobody
autostart=true
autorestart=true
```
## Actual behaviour
**BUT Supervisord documentation says only one file path can provide and only one Unix doman socket and inet socket can create and listen**
See the Supervisord documentation link
http://supervisord.org/configuration.html#unix-http-server-section-example
Also see answer to this issue @ Supervisord github page.
https://github.com/Supervisor/supervisor/issues/1314
**THEN How can we achieve what Aiohttp documentation describes**

## Your environment
_Ubuntu server, Supervisord 4.1.0 (2019-10-19), Nginx-1.17.7-open source. aiohttp==3.6.2_
--

    **Aiohttp- Server**
     -->

**Comment by webknjaz** [comment]
@binrebin in Supervisor/supervisor#1314 you use different folders in the command option and nginx config. You seem to point nginx to supervisord's control socket instead of pointing it to a number of sockets that are being created by your app.

The docs you linked describe a completely different feature.

**Comment by binrebin** [comment]
@webknjaz Could you explain, just allow supervisord to create a unix socket and ponting nginx to the app created unix socket paths will do the job right?

**Comment by webknjaz** [comment]
You don't need superuserd to create a socket on its own. You should specify the command which will run your Python program and that program will then create a socket: `command=/path/to/aiohttp_example.py --path=/tmp/example_%(process_num)s.sock`. For any other questions use StackOverflow and their docs. We don't consult on how somebody else's software works.

**Comment by binrebin** [comment]
@webknjaz thanks a lot. Your supports will make aiohttp candid.
