### ISSUE TITLE
{ClientPayloadError}400, message='Can not decode content-encoding: br'

### ISSUE THREAD

**Issue by shmilylty** [aio-libs/aiohttp#4491]
## Long story short

I have installed the brotli library, but I still have a ClientPayloadError problem.
![image](https://user-images.githubusercontent.com/24275308/71834893-43227180-30eb-11ea-82fe-d065aa540a5b.png)

## Expected behaviour

Normal decoding

## Actual behaviour

{ClientPayloadError}400, message='Can not decode content-encoding: br'

## Steps to reproduce
git clone https://github.com/shmilylty/OneForAll.git
cd OneForAll
pip install -r requirements.txt
cd oneforall/
python oneforall.py --target freebuf.com  run

## Your environment
Windows 10 19.09
Python 3.8.0
aiohttp 3.6.2
client

**Comment by shmilylty** [comment]
@webknjaz @asvetlov Would you please take a look at this problem?

**Comment by asvetlov** [comment]
Perhaps you were unable to install/compile brotli successfully; `import brotli` fails in your environment.

Sorry, the installation of third-party libraries is out of the scope of the the project.
I would say that *aiohttp* uses `Brotli==1.0.7` to pass own test suite.

**Comment by shmilylty** [comment]
![image](https://user-images.githubusercontent.com/24275308/73455117-666ad480-43aa-11ea-9177-a5a640c14074.png)
I have installed the brotli library @asvetlov

**Comment by webknjaz** [comment]
@shmilylty you should have it in the same env.

**Comment by ydylla** [comment]
A bit late but maybe it helps some googlers like me.
The Problem here was that aiohttp 3.6.2 only works with `brotlipy` (I used 0.7.0) instead of `Brotli`.
Only with aiohttp 4 it is possible to use `brotlipy` or `Brotli`.

**Comment by v67bruno** [comment]
for me works installing backports.zstd.
`pip install backports.zstd`

**Comment by blahgeek** [comment]
FYI `aiohttp` prefers `brotlicffi` packages when it exists. So also make sure its version is up-to-date if it's installed

**Comment by Dreamsorcerer** [comment]
That's a mistake. Feel free to open a PR to swap them.

Installing via aiohttp[speedups] will install brotli if you're running on a supported platform, and only install brotlicffi otherwise. I guess nobody thought about what happens if both packages are already installed anway..
