### ISSUE TITLE
Redirects not working in case of domain change

### ISSUE THREAD

**Issue by sharmapala** [aio-libs/aiohttp#4494]
## Long story short

So, apparently the redirects of any Url is limited to adding up https from http OR adding www.domain.com 

## Expected behaviour

For the below piece of code 

async def fetch_html(url, session):
    try:
        resp = await session.request(method="GET", url=url, headers=headers, timeout=60, allow_redirects=True)
    except:
        return
    logger.info("Got response [%s] for URL: %s", resp.status, url)
    try:
        return await resp.text('utf-8')
    except:
        return

for the url : http://www.1800vending.com 
the expected redirect is : https://www.healthyyouvending.com

## Actual behaviour

for the url : http://www.1800vending.com 
the actual redirect : http://www.1800vending.com

**Comment by asvetlov** [comment]
I don't see a problem, redirects work fine.
Please provide minimal reproducible example next time
