### ISSUE TITLE
skip_auto_headers= should allow ["*"] for all. And update documentation for auto headers.

### ISSUE THREAD

**Issue by danielniccoli** [aio-libs/aiohttp#4499]
The current documentation reads as follows:

```
**skip_auto_headers –**

set of headers for which autogeneration should be skipped.

aiohttp autogenerates headers like `User-Agent` or `Content-Type` if these headers are not explicitly passed. Using skip_auto_headers parameter allows to skip that generation. Note that Content-Length autogeneration can’t be skipped.

Iterable of str or istr (optional)
```

Please either allow ["*"] to indicate that no headers should be auto generated.

Additionally, please update the documentation to show what headers are currently auto generated. If you need to pass them explicitly, it should be easy to see what one has to pass to completely disable it.

**Comment by asvetlov** [comment]
I disagree. 
For example, `Host` header is mandatory by HTTP/1.1 spec. The same is true for other headers as well (either content-length should be specified of chunked mode enabled).
Disabling all autogenerated headers is very dangerous. If you want to disable a part of them -- you always can pass a list of desired skips.

**Comment by danielniccoli** [comment]
@asvetlov I agree with the headers that are required by HTTP spec. I didn't think of those.

> If you want to disable a part of them -- you always can pass a list of desired skips.

But then please list the automatically added headers in the documentation. At least the ones who are not required by HTTP spec.
