### ISSUE TITLE
Please disable lockbot comments

### ISSUE THREAD

**Issue by achimnol** [aio-libs/aiohttp#4504]
I'm receiving a lot of notifications saying that the lock bot is locking issues/PRs with no activities more than 1 year. It is difficult to distinguish whether an issue/PR is just locked or recently discussed inside the notification UI.
There have been similar issues in other repositories and some have disabled comment by the lock bot, e.g., https://github.com/prometheus/prometheus/pull/5402

I'd like to suggest to apply the same here.

**Comment by webknjaz** [comment]
Yeah, that's a bit annoying but OTOH we'd like to notice if something is locked legit or not.
Also, you could filter out emails if you want to...

**Comment by achimnol** [comment]
The problem is that I'm not using emails to check GitHub notifications, but instead, https://github.com/notifications/beta .
Also I think we could describe the default behavior of the lockbot in the contribution guideline and add explicit comments only when "exceptional" cases (e.g., by moderation).

**Comment by webknjaz** [comment]
But then we won't get notified about locks meaning that we will miss the chance to moderate these actions...

**Comment by asvetlov** [comment]
@achimnol please feel free to make the proposed PR.
Lock bot adds "outdated" tag, I believe it is visible enough.
A few words about the bot in http://docs.aiohttp.org/en/stable/contributing.html would be awesome!

**Comment by asvetlov** [comment]
Fixed by #4508
