### ISSUE TITLE
`proxy_headers_hash` appears unused

### ISSUE THREAD

**Issue by dimaqq** [aio-libs/aiohttp#4507]
Looks like `ConnectionKey.proxy_headers_hash` is always None is never used:

<img width="566" alt="Screenshot 2020-01-17 at 14 46 36" src="https://user-images.githubusercontent.com/662249/72587371-61347100-3938-11ea-8b60-c8ba7826e21d.png">

**Comment by asvetlov** [comment]
Yes, you are right.
We can drop it I guess.

**Comment by Dreamsorcerer** [comment]
Isn't it used right here?
https://github.com/aio-libs/aiohttp/blob/faa15fd7d1bea808a64f979c1a7ace8340d68d61/aiohttp/client_reqrep.py#L315

**Comment by bdraco** [comment]
I think this was intended to avoid having to calc the hash every time

**Comment by bdraco** [comment]
reguardless, it is used

**Comment by dimaqq** [comment]
If it’s used now, that’s great!

**Comment by Dreamsorcerer** [comment]
It was used when you opened the issue, that's why I questioned it.
Here's a link to the same code at the time you opened the issue:
https://github.com/aio-libs/aiohttp/blob/95e548c31efe1f53cc0a5eeb919fa8d9e666f4d9/aiohttp/client_reqrep.py#L265
