### ISSUE TITLE
Is there a release plan for 3.7?

### ISSUE THREAD

**Issue by amsb** [aio-libs/aiohttp#4516]
With upcoming changes to how browsers handle cookies (https://web.dev/samesite-cookie-recipes/), we're eager to explicitly set the SameSite attribute for cookies using work already done in #4303. Happy to help out if there is anything I can do!

Thanks for all the great work on aiohttp!

**Comment by hh-h** [comment]
please, follow https://aio-libs.discourse.group/t/aiohttp-new-release/49

**Comment by amsb** [comment]
Thanks @hh-h! I'll leave this issue open so others like me can follow the discourse but, @asvetlov, feel free to close it if you prefer.

**Comment by asvetlov** [comment]
Will be done soon, in a few days I guess
