### ISSUE TITLE
Disqus integration

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#452]
I've added disqus comments for every documentation page.

You can try it for unreleased version: http://aiohttp.readthedocs.org/en/latest/web.html
Scroll down the page and see comments section.

I hope it's helpful.

I'm the prime moderator for aiohttp disqus project. @fafhrd91 @kxepal @popravich please sign up into disqus.com and send me your usernames privately -- I'll add your names to the list.

**Comment by ludovic-gasc** [comment]
A way exists to follow all comments on all documentation by RSS feed or by email?

**Comment by kxepal** [comment]
@GMLudo technically, should be possible to receive notifications by following aiohttp @ disqus. All the comments (or at least last activity) should be visible here: https://disqus.com/home/forum/aiohttp/

**Comment by ludovic-gasc** [comment]
@kxepal thank you for the link.
