### ISSUE TITLE
client post freezes when headers contains certain content length

### ISSUE THREAD

**Issue by yehbrianyeh** [aio-libs/aiohttp#4522]
## Long story short

```
import aiohttp
import asyncio

async def fetch(client):
    data = {
      "title": 'foo',
      "body": 'bar',
      "userId": 1
    }
    headers={"Content-Length": '6567'}
    headers2 = {}
    async with client.post('https://jsonplaceholder.typicode.com/posts', json=data, headers=headers) as resp:
        return await resp.text()

async def main():
    async with aiohttp.ClientSession() as client:
        html = await fetch(client)
        print(html)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

headers variable makes the request freeze. headers2 does not. 

## Expected behaviour

Don't freeze

## Actual behaviour

it freezes

## Steps to reproduce

Run code above. Switch between headers and headers2 for the post function. 

## Your environment
```

(venv) Brians-MacBook-Pro-2:verify_bug brianyeh$ pip freeze
aiohttp==3.6.2
async-timeout==3.0.1
attrs==19.3.0
chardet==3.0.4
idna==2.8
multidict==4.7.4
yarl==1.4.2
(venv) Brians-MacBook-Pro-2:verify_bug brianyeh$ python --version
Python 3.7.5
```

**Comment by yehbrianyeh** [comment]
Maybe hang is a better word. It's not actually "freezing" it will time out eventually.

**Comment by hh-h** [comment]
It is not `certain`, I think it's better to say when `content-length` is more than actual body size. In your example `content-length = 44` and it's fine, as well as 43, but 45+ leads to timeout error.

Also reproduced on the latest master.
The requests library works fine with incorrect content-length.

**Comment by Dreamsorcerer** [comment]
requests simply overrules you and actually sends `Content-Length: 44`.
If you've explicitly specified the header, I'm not sure we should overrule you...
But, obviously, a normal server will be expecting more data from you in this situation and will therefore continue waiting.
