### ISSUE TITLE
Custom line delimiter for the the aiohttp.streams.StreamReader.readline async iter

### ISSUE THREAD

**Issue by koi8-r** [aio-libs/aiohttp#4527]
## Long story short

Please allow custom line delimiter in the aiohttp.streams.StreamReader.readline coro.
Currently the "\n" is hardcoded: `ichar = self._buffer[0].find(b'\n', offset) + 1`

## Expected behaviour

Please make a class field from delimiter and it is allows for overriding the delimiter in the child class:

```python
class StreamReader(AsyncStreamReaderMixin):
    _delimiter: bytes = b"\n"
    async def readline(self) -> bytes:
        ...
        while not_enough:
            while self._buffer and not_enough:
                offset = self._buffer_offset
                ichar = self._buffer[0].find(self._delimiter, offset) + 1
        ...

class MySuperStreamReader(AsyncStreamReaderMixin):
    _delimiter: bytes = b";"
    ...
```

## Actual behaviour

Line delimiter is hardcoded at https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/streams.py#L313

**Comment by socketpair** [comment]
@asvetlov Sorry, I forget, why can't we use asyncio streams ?

**Comment by asvetlov** [comment]
In short, they are badly designed, sorry.

**Comment by asvetlov** [comment]
Please consider aiohttp StreamReader as **final** class.
It is not intended for user inheritance, user code should not create StreamReader instances explicitly.
If you need something similar but slightly different -- please feel free to copy-paste it.

**Comment by stuaxo** [comment]
Is there somewhere to read about what the issues are?

It might be worth submitting an upstream bug.
