### ISSUE TITLE
 can i legally use aiohttp in a commercial, educational video?

### ISSUE THREAD

**Issue by codefather-labs** [aio-libs/aiohttp#4537]
can i legally use aiohttp in a commercial, educational video?

**Comment by webknjaz** [comment]
Why not? I mean, the license does not prevent you from teaching other people how to use aiohttp. Of course, you're encouraged to post some of your code examples online. But if you fork aiohttp, you have to preserve mentions of the original authors and the upstream. In general, read the license and google some explanations to learn how it works and just follow the rules.
