### ISSUE TITLE
Why is asyncio.TimeoutError sometimes raised as class?

### ISSUE THREAD

**Issue by Colin-b** [aio-libs/aiohttp#4538]
## Long story short

I noticed that in some places, TimeoutError is raised as class instead of as an instance.

## Expected behaviour

I would expect the same behavior accross the whole library but this is more a question I ask myself, is it by design?

## Actual behaviour

https://github.com/aio-libs/aiohttp/blob/master/aiohttp/helpers.py#L594

https://github.com/aio-libs/aiohttp/blob/master/aiohttp/helpers.py#L606

## Steps to reproduce

await response.text() after ensuring that you will have a huge body and a small timeout to reproduce this issue.

## Your environment

Python 3.8.1
Windows 10 / Windows 7 / Alpine 3.11
aiohttp 3.6.2

**Comment by webknjaz** [comment]
https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.TimeoutError doesn't seem to have any args in the initializer so it doesn't really matter.
In Python, `raise SomeException` is internally turned into `raise SomeException()` automatically.

**Comment by Colin-b** [comment]
Thanks a lot, always good to learn some new stuff, I did not know that about exceptions in Python :)
