### ISSUE TITLE
Pass arguments to aiohttp class based view

### ISSUE THREAD

**Issue by NicoAdrian** [aio-libs/aiohttp#4555]
It would be cool if we could pass arguments to class-based views when instantiated.
It is possible with Tornado to pass a dict object for each request which is then accessible in the handler.

This works, using a partial class and basic inheritance:

```python
import aiohttp.web
import functools


class Parent:
    def __init__(self, val):
        self.var = val


class BaseView(aiohttp.web.View):
    def __init__(self, *args, **kwargs):
        self.parent = kwargs.pop("parent")
        super().__init__(*args, **kwargs)


class Handler(BaseView):
    async def get(self):
        return aiohttp.web.Response(text=self.parent.var)


def partial_class(cls, *args, **kwargs):
    class NewCls(cls):
        __init__ = functools.partialmethod(cls.__init__, *args, **kwargs)

    return NewCls


def main():
    parent = Parent("blablabla")
    app = aiohttp.web.Application()
    # New method with args
    app.router.add_view_with_args = functools.partial(
        lambda this, path, handler, d: this.add_view(path, partial_class(handler, **d)),
        app.router,
    )
    # Tornado-style
    app.router.add_view_with_args("/test", Handler, {"parent": parent})
    aiohttp.web.run_app(app)


main()
```

But I feel like this overcomplicated. Maybe there is a simpler way ?

**Comment by webknjaz** [comment]
What are you trying to achieve? You didn't fill out the form so I can only guess...

**Comment by NicoAdrian** [comment]
I am trying to find a way (simpler than my example, but maybe there isn't any) to pass arguments to views when a request is received. 

As you can see, in my `Handler`, I am able to access `parent` object because I passed a reference in my custom function `add_view_with_args`

**Comment by webknjaz** [comment]
1) why don't you have a base class for the handler?
2) are you trying to reinvent middlewares?
3) you describe the solution that you want but you didn't tell me what is the original problem that you are trying to solve. You try to transfer the usage patterns from Tornado but those patterns also solve some problem, what problem is that?

**Comment by NicoAdrian** [comment]
1. Sorry, I don't know what you mean.
2. I don't think so.
3. Sorry if I wasn't clear enough. I want to pass an object reference for every request. My solution indeed works but I feel like adding a static method like I did is overcomplicated and I was wondering if there is any simpler/built-in way to do this.

**Comment by webknjaz** [comment]
Alright, we have a progress now. I think you need to do `app['your_thing'] = your_data` in the cleanup context hook. Then, retrieve it from the app object whenever you need it while processing requests

**Comment by webknjaz** [comment]
* https://docs.aiohttp.org/en/latest/web_advanced.html#aiohttp-web-cleanup-ctx
* https://docs.aiohttp.org/en/latest/web_advanced.html#application-s-config

P.S. In CBV `app = self.request.app`

**Comment by NicoAdrian** [comment]
Ok I got it:

```python
import aiohttp.web


class Handler(aiohttp.web.View):
    async def get(self):
        # Returns "blablabla"
        return aiohttp.web.Response(text=self.request.app["my_thing"])


def main():
    app = aiohttp.web.Application()
    app["my_thing"] = "blablabla"
    app.router.add_view("/test", Handler)
    aiohttp.web.run_app(app)


main()
```

Works as expected. Is this what you meant ?

**Comment by NicoAdrian** [comment]
> 
> 
>     * https://docs.aiohttp.org/en/latest/web_advanced.html#aiohttp-web-cleanup-ctx
> 
>     * https://docs.aiohttp.org/en/latest/web_advanced.html#application-s-config
> 
> 
> P.S. In CBV `app = self.request.app`

I missed this in the docs.
Thanks for your explanations and your patience, closing the issue now.

**Comment by webknjaz** [comment]
> Is this what you meant ?

Yes, you can do this when you construct the app or in signal handlers, depending on at what stage you get your data.

**Comment by Quiet-Klirik** [comment]
Read about the magic method `__call__`
