### ISSUE TITLE
Support other URL objects (hyperlink, furl, etc) transparently

### ISSUE THREAD

**Issue by cdunklau** [aio-libs/aiohttp#4563]
🐣 **Is your feature request related to a problem? Please describe.**

I use [hyperlink](https://hyperlink.readthedocs.io/en/latest/) and it's somewhat annoying that I need to `str(myurl)` in order for `aiohttp` (really `yarl` I guess) to accept it.

💡 **Describe the solution you'd like**

It would be nice if this was transparent. I'd like to pass a `str`, a `hyperlink.URL`, a `yarl.URL`, or really anything that stringifies to a valid URL, and expect `aiohttp` to just do what I want.

`requests` added this way back [in version 0.13.7](https://github.com/psf/requests/issues/423), and I didn't even know I was relying on it until I switched to `aiohttp` and started getting `InvalidURL` exceptions. The "just hit it with `str`/`unicode`" approach used by `requests` probably has downsides, but I can't really think of any.

❓ **Describe alternatives you've considered**

`str(myhyperlinkurl)` as mentioned above, and subclassing `aiohttp.ClientSession` (ew, I know, but it crossed my mind).

**Comment by asvetlov** [comment]
Sorry, the request is rejected.
`requests` is string-based internally.
On the opposite, aiohttp uses `yarl.URL`; it constructs the URL if a string argument is passed, returns URL instance as response's property, etc.

`str(url)` doesn't work; `yarl.URL(str(url))` is too invasive and can make more harm than help.
