### ISSUE TITLE
Content-Type is always set

### ISSUE THREAD

**Issue by chrisseto** [aio-libs/aiohttp#457]
As of https://github.com/KeepSafe/aiohttp/commit/089e82993c8393453fa74b8a3ba6f0dd4240f8a0 the Content-Type header is alway set if not otherwise set by the user.
This behavior is often undesirable and should be opt-in or at least provide an option to opt-out.
In the case of using Amazon S3's signed URLs, extra steps must be taken to have this header included.

**Comment by asvetlov** [comment]
When you send request you know content type, isn't it?

As an option we may add `ignore_default_headers` parameter for client API (both for `ClientSession` and `request`).

What's your use case? Why S3's signed URLs are not aware about content type?

**Comment by jettify** [comment]
As far as I remember issues with s3 is following: s3 api requires special signature to be added, when you preparing request. So you take body and headers then calculate signature, but `content-type header` is not present on that time, it will be added when you actually send request. For my botocore port I just added `content-type` explicitly https://github.com/jettify/aiobotocore/blob/master/aiobotocore/endpoint.py#L87-L98

**Comment by asvetlov** [comment]
Well, `ignore_default_headers` (maybe better name?) looks a good idea.

**Comment by chrisseto** [comment]
@jettify That would work but I'm not certain how that would affect amazon's own content type detection
@asvetlov I like the idea of `ignore_default_headers` but how far would that extend? Some that are automatically added are fairly helpful, ie `User-Agent`.

**Comment by jettify** [comment]
@chrisseto I tested my implementation with almost all tests (except pagination) of botocore library and it works as expected.

**Comment by asvetlov** [comment]
See also #379

**Comment by asvetlov** [comment]
@chrisseto we don't autoset `User-Agent`. But you may setup default user-agent header with `ClientSession`:

```
session = ClientSession(headers={'User-Agent': 'aiohttp client 0.17'})
```

**Comment by chrisseto** [comment]
Using `aiohttp.request`, on version 0.14.1, it seems to set it.

``` python
In [5]: aiohttp.__version__
Out[5]: '0.14.1'

In [6]: asyncio.get_event_loop().run_until_complete(aiohttp.request('GET', 'http://localhost:1234'))
```

``` bash
~❯❯❯ nc -l 1234
GET / HTTP/1.1
ACCEPT: */*
ACCEPT-ENCODING: gzip, deflate
HOST: localhost:1234
CONTENT-LENGTH: 0
CONNECTION: keep-alive
USER-AGENT: Python/3.4 aiohttp/0.14.1
```

**Comment by asvetlov** [comment]
Ahh, got it. Sorry.

**Comment by mpaolini** [comment]
for `User-Agent` you can now use `skip_auto_headers={'USER-AGENT'}` and as of pull request #507 this same method works for `Content-Type` too

**Comment by mpaolini** [comment]
I think we can close this one
