### ISSUE TITLE
Server closes connection if wrong type returned by handler

### ISSUE THREAD

**Issue by Fogapod** [aio-libs/aiohttp#4572]
🐞 **Describe the bug**

Server closes session if handler returns anything else that `Response` instance.

💡 **To Reproduce**

```python
from aiohttp import web


async def handler(req):
    return 1

app = web.Application()
app.add_routes([web.get("/", handler)])
web.run_app(app)
```

```bash
~ curl localhost:8080
curl: (52) Empty reply from server
```

💡 **Expected behavior**

Error message in console and returned status 500.

📋 **Your version of the Python**

```console
$ python --version
Python 3.8.1
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

Tested with aiohttp `3.6.2` and `master` branch fresh installations.

**Comment by webknjaz** [comment]
@Fogapod thanks for the report! It'd be cool if you could submit a failing test marked with xfail in a PR as per https://pganssle-talks.github.io/xfail-lightning.

**Comment by Fogapod** [comment]
@webknjaz alright, I'll try to make a test for this issue.

I found that returning `HTTPException` instance in aiohttp 3.6.2 resulted in returning corresponding status code by server, in master branch it results in closed connection.
Is returning exceptions deprecated? I didn't find it in documentation, there is no traceback in console.

**Comment by webknjaz** [comment]
I think it is, or should be. Exceptions must be raised.

**Comment by Fogapod** [comment]
`RuntimeError` is raised here https://github.com/aio-libs/aiohttp/blob/f80029b553ec041370babf75d07e2abb9b2bdca3/aiohttp/web_protocol.py#L577-L579
after calling https://github.com/aio-libs/aiohttp/blob/f80029b553ec041370babf75d07e2abb9b2bdca3/aiohttp/web_protocol.py#L480
and catched here https://github.com/aio-libs/aiohttp/blob/f80029b553ec041370babf75d07e2abb9b2bdca3/aiohttp/web_protocol.py#L523-L526
For some reason these are only logged in asyncio debug mode.

I'm not sure how this could be fixed. Returning status 500 for all Runtime errors?

**Comment by webknjaz** [comment]
> Returning status 500 for all Runtime errors?

I think so

**Comment by webknjaz** [comment]
> Is returning exceptions deprecated? I didn't find it in documentation, there is no traceback in console.

v3.6 deprecates returning exceptions but it still works (see the red warning box): https://docs.aiohttp.org/en/stable/web_quickstart.html#exceptions

master/v4.0 doesn't support this anymore and doesn't mention returning exceptions: https://docs.aiohttp.org/en/latest/web_exceptions.html

**Comment by Fogapod** [comment]
I don't understand this condition: https://github.com/aio-libs/aiohttp/blob/f80029b553ec041370babf75d07e2abb9b2bdca3/aiohttp/web_protocol.py#L524-L526
What kind of exceptions can happen there and why they are silenced by default?
If there are exceptions that should be silenced and cause server to close connection without response, what could a workaround be? Raising different kind of exception from handler if wrong type returned?

Edit: according to this comment https://github.com/aio-libs/aiohttp/issues/1790#issuecomment-292745428, runtime exceptions should not be handled, but in this case it can be, so exception type should be changed?
