### ISSUE TITLE
Request validation

### ISSUE THREAD

**Issue by rafa-acioly** [aio-libs/aiohttp#4591]
🐣 **Is your feature request related to a problem? Please describe.**
Nowadays to validate the request content inside my views i'm using a 3p library (https://pypi.org/project/schema/) but i would like to receive the request on my views only if the request validation succeed, this maybe save some boilerplate code and reduce the code lines on each view

💡 **Describe the solution you'd like**
First suggestion:
Add a parameter on method `add_route` to pass a callable to validate the incoming request before calling the respective view.

```py
app.add_route('POST', '/endpoint/', MyViewClass, validator=MyValidator)
```

Second suggestion:
Identify the request validator as a dependency injection, e.g:

```py
class MyView(web.View):

    def post(request, validator: MyValidator):
        payload = request.json() # the json was already validated by MyValidator class

```

❓ **Describe alternatives you've considered**
Maybe it's possible to do this with a middleware but i can't find out a way to identify each route with the respective http verb :man_shrugging: 

📋 **Additional context**
Inspiration:
1. https://laravel.com/docs/6.x/validation#form-request-validation

**Comment by hh-h** [comment]
I doubt it'll be implemented, but you can check this library https://github.com/hh-h/aiohttp-swagger3 (full disclosure: I wrote it)

**Comment by borysvorona** [comment]
What about third-party libraries like https://github.com/dchaplinsky/aiohttp_validate?

**Comment by asvetlov** [comment]
Looks like third-party libs can solve the request without modifying aiohttp itself.
