### ISSUE TITLE
Force gzip compression in aiohttp web.StreamResponse

### ISSUE THREAD

**Issue by CaledoniaProject** [aio-libs/aiohttp#4602]
I use the following code to serve file download requests:

```
resp = web.StreamResponse(headers={
    'Server': 'Nginx', 
    'Content-Type': 'text/html',
    'Content-Disposition': 'attrachment; filename=' + filename
})
await resp.prepare(request)
```

How do I force gzip compression? The relevant document is missing on aiohttp's website.

**Comment by ttsia** [comment]
You can find relevant docs [here](https://docs.aiohttp.org/en/stable/web_reference.html?highlight=enable_compression#aiohttp.web.StreamResponse.enable_compression)
