### ISSUE TITLE
Using session.put method will cause memory leak

### ISSUE THREAD

**Issue by Aruelius** [aio-libs/aiohttp#4608]
🐞 **Describe the bug**

When I upload a data block using the session.put method, it will take up more memory, and when this method ends calling, the memory will not be released. 

**Here is the memory usage**  
start: 1.6% use
![image](https://user-images.githubusercontent.com/25380989/75852163-5b321b00-5e26-11ea-9c01-8c1ff388cec0.png)
first cycle: 4.5% use
![image](https://user-images.githubusercontent.com/25380989/75852237-80bf2480-5e26-11ea-8826-978b7f1dd452.png)
second cycle: 22.1% use
![image](https://user-images.githubusercontent.com/25380989/75852297-a6e4c480-5e26-11ea-800d-d37cf31d4b35.png)

**ps:**
When i use requests.put(), the memory usage is normal. 

💡 **To Reproduce**
~~~python
async def run():
    async with aiohttp.ClientSession() as session:
        async with session.put('http://httpbin.org/put', data=b'data', timeout=5) as resp:
            print(await resp.text())
def main():
    while True:
        if b = 1:    # the b is a contingency condition
            asyncio.run(run())
~~~

💡 **Expected behavior**
When run() finish running, the memory should be released.

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)

```

📋 **Your version of the Python**

```console
Python 3.7.4 (default, Mar  2 2020, 16:34:34) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
Name: aiohttp
Version: 3.6.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /root/.pyenv/versions/3.7.4/lib/python3.7/site-packages
Requires: multidict, attrs, async-timeout, yarl, chardet
Required-by: 
```
```console
Name: multidict
Version: 4.7.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /root/.pyenv/versions/3.7.4/lib/python3.7/site-packages
Requires: 
Required-by: yarl, aiohttp
```
```console
Name: yarl
Version: 1.4.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /root/.pyenv/versions/3.7.4/lib/python3.7/site-packages
Requires: multidict, idna
Required-by: aiohttp
```

📋 **Additional context**

CentOS Linux release 7.7.1908 (Core)
Ubuntu 16.04.6 LTS

**Comment by yb7** [comment]
Also will happen when use post.

**Comment by hf-kklein** [comment]
Any idea on how to workaround the issue?

**Comment by Aruelius** [comment]
I think this problem has been resolved.
