### ISSUE TITLE
HTTPFound prints to console

### ISSUE THREAD

**Issue by bitnom** [aio-libs/aiohttp#4609]
🐞 **Describe the bug**

`raise aiohttp.web.HTTPFound('/redirect')` always prints the line `Found` to console. This is bad for performance if there's no way to suppress it.

💡 **To Reproduce**

Raise an HTTPFound

💡 **Expected behavior**

I expect no output to stdout or stderr

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
NA
```

📋 **Your version of the Python**

```console
$ python --version
...
3.8.1
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
...
```

```
Version: 3.6.2
$ python -m pip show multidict
...
```

```
Version: 4.7.5
$ python -m pip show yarl
...
```
Version: 1.4.2

📋 **Additional context**

Linux x64

**Comment by webknjaz** [comment]
@TensorTom feel free to send a PR

**Comment by borysvorona** [comment]
It's here. 
https://github.com/aio-libs/aiohttp/blob/91963c0e96bc5ea4d884cb413d2f65c637f8c4c6/aiohttp/web_exceptions.py#L149-L151

@TensorTom , does it need to be changed?

**Comment by webknjaz** [comment]
No, repr by itself doesn't cause any stdout. We need a proper reproducer to see what's happening.

**Comment by bitnom** [comment]
> No, repr by itself doesn't cause any stdout. We need a proper reproducer to see what's happening.

It does for me. I'll try to trace it.

**Comment by bitnom** [comment]
My mistake. It was one of my middlewares.
