### ISSUE TITLE
Content-Type header should be optional in Response

### ISSUE THREAD

**Issue by rmedaer** [aio-libs/aiohttp#4612]
🐞 **Describe the bug**
I'm not able to remove the `Content-Type` header in `aiohttp.web.Response`. However, according to HTTP RFC, the `Content-Type` header is not mandatory. Especially if you don't return content (e.g. `204 No Content`) 

💡 **To Reproduce**

```python
from aiohttp.web import Response

async def handler(request):
    return Response(
        status=204,
        content_type=None
    )
```

💡 **Expected behavior**

Be able, some how, to remove the `Content-Type` header.

📋 **Logs/tracebacks**

Result from `curl`:
```
< HTTP/1.1 204 No Content
< Content-Length: 0
< Content-Type: application/octet-stream
< Date: Fri, 06 Mar 2020 11:32:46 GMT
< Server: Python/3.7 aiohttp/3.5.1
```

**Comment by borysvorona** [comment]
I do not agree with that, according to
https://tools.ietf.org/html/rfc2616#section-7.2.1

I think that an additional optional Response param can solve that issue.
For example:

```python
aiohttp.web.Response(status=204, force_empty_content_type=True)
```

**Comment by rmedaer** [comment]
> I do not agree with that, according to
> https://tools.ietf.org/html/rfc2616#section-7.2.1

Could you expand on that, please ?

If I well understand the RFC, the `entity-body` is optional... Here is the relevant quotes where I highlighted some keywords and added some footnotes:

[Section 7.2.1 Type](https://tools.ietf.org/html/rfc2616#section-7.2.1) (you quoted):
> **_When_<sup>2</sup> an entity-body is included** with a message, the data type of that body is determined via the header fields Content-Type (...)
> Any HTTP/1.1 message containing an entity-body **SHOULD**<sup>1</sup> include a Content-Type header field defining the media type of that body.

[Section 7.2 Entity Body](https://tools.ietf.org/html/rfc2616#section-7.2):
> The entity-body **(if any)** (...)
> An entity-body **is only present in a message when a message-body is present<sup>3</sup>** (...)

If my understanding is correct, it means:

  1. A `Content-Type` is not mandatory
  2. A `Content-Type` header should be specified **if** an `entity-body` is included
  3. If there is not any message body, there is no `entity-body`

So, if not any body is returned, not any `Content-Type` header should be returned !

**Comment by asvetlov** [comment]
This issue has been mentioned on **aio-libs**. There might be relevant details there:

https://aio-libs.discourse.group/t/optional-content-type-header/82/1

**Comment by alex-eri** [comment]
Write custom Response subclass and fix setter https://github.com/aio-libs/aiohttp/blob/fe647a08d1acb53404b703b46b37409602ab18b4/aiohttp/web_response.py#L254

**Comment by rmedaer** [comment]
@alex-eri I don't understand why I should write a custom Response subclass for what should be a default behavior.

IMHO we should use response subclass to add extra feature/behavior, not to remove them.

I found a nice illustration of the issue in Chrome. **Currently**, if I return a (not-so) empty 404:

```python3 
async def not_found(request):
    return Response(status=404)

# < HTTP/1.1 404 Not Found
# < Content-Type: application/octet-stream
# < Content-Length: 0
#  (...)
```
Chrome shows an invalid response (due to the `Content-Type` `application/octet-stream`)


![invalid](https://user-images.githubusercontent.com/2905530/77050890-b50c1680-69ca-11ea-806e-c287478e2a62.png)

If I remove the `Content-Type` and `Content-Length` headers (or if `Content-Type` is `text/html`), here is what Chrome shows:

![ok](https://user-images.githubusercontent.com/2905530/77051101-0d431880-69cb-11ea-8953-972b94a9f545.png)
