### ISSUE TITLE
Detect charset from <meta charset> on client

### ISSUE THREAD

**Issue by danielzgtg** [aio-libs/aiohttp#4619]
🐣 **Is your feature request related to a problem? Please describe.**

I'm always frustrated when the aiohttp client doesn't detect `<meta charset>` and crashes instead.

💡 **Describe the solution you'd like**

Sniff the encoding as per the [WHATWG specification](https://html.spec.whatwg.org/multipage/parsing.html#encoding-sniffing-algorithm).

Continue to use the `charset=` in the `Content-Type` HTTP header if present. When it's not present, sniff the first 1024 bytes for any `<meta charset>` before going to chardet. Only sniff for the `<meta charset>` if `Content-Type` is set to an HTML MIME or is missing.

❓ **Describe alternatives you've considered**

- Have whoever calls this library avoid `text()` and do the detection themselves. This is the current workaround, and it's not convenient.
- Improve the chardet library instead. Add the `<meta charset>` detection there, and make it return `ISO-8859-1` rather than the current `ISO-8859-8`. This is not ideal because aiohttp is more specialized for HTML/HTTP than chardet and aiohttp is not passing it the `Content-Type` to enable/disable this behavior.

📋 **Additional context**

Test case:

1. Run `vim charsettest.html`
2. Press `i` and paste the following:

```html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="windows-1251">
    <title>Charset test</title>
</head>
<body>
Test
абвгдеёжзийклмнопрстуфхцчшщъыьэюя
</body>
</html>
```

3. Press escape, and type `:w ++enc=windows-1251`
4. Run `python3 -m http.server 8000 &`
5. Open Chrome to `http://127.0.0.1:8000/charsettest.html`
6. Open DevTools Console and run `document.characterSet`
7. Make sure it says "windows-1251"
8. Run `python3 -m asyncio`
9. Run the following commands:

```python
import aiohttp
session = await aiohttp.ClientSession().__aenter__()
resp = await aiohttp.ClientSession().__aenter__()
text = await resp.text()
```

The last command should retrieve the text rather than crash with `UnicodeDecodeError: 'charmap' codec can't decode byte 0xfb in position 140: character maps to <undefined>`

**Comment by asvetlov** [comment]
No, sorry.
aiohttp is not a browser, it doesn't parse the response body.
You can do sniffing yourself though by `await resp.read()` + parse + sniff
