### ISSUE TITLE
`aiohttp.ClientSession().get()` takes around 30secs to make a request to `localhost` (unlike `127.0.0.1`)

### ISSUE THREAD

**Issue by Joacchim** [aio-libs/aiohttp#4627]
🐞 **Describe the bug**

This bug was observed on isolated servers we were preparing for soon-to-be production (ie: There's network setup, with isolation etc., but I don't have all the details at hand, though I can ask if it sounds relevant).

When using `localhost` instead of an ip (ie `127.0.0.1`) to make an async request to a "local" HTTP server, we're observing very odd behaviors, such as a very long time to connect to the server and run the request.

In our situation, we're reaching out to a data-providing server through a HAProxy, but I do not think it is relevant to this issue, as I could reproduce it with a simple `python3 -m http.server` as the local HTTP server.

Switching our configurations from `localhost` to `127.0.0.1` solved the issue, and fixed any odd behavior previously observed.

💡 **To Reproduce**

Run a simple http server:
```console
$> python3 -m http.server
```

Then run the following code against it:
```python3
import aiohttp
from datetime import datetime
import asyncio
async def do(host):
    async with aiohttp.ClientSession() as client:
        async with client.get(f'http://{host}/data/91a6570c981c96a35cffc819b203115085e7293c02f3196bd5566bc10b6c1663') as response:
            print(datetime.utcnow())
            print(response)

loop = asyncio.get_event_loop()
print(datetime.utcnow()) ; loop.run_until_complete(do('127.0.0.1:22023'))

print(datetime.utcnow()) ; loop.run_until_complete(do('0:22023'))
print(datetime.utcnow()) ; loop.run_until_complete(do('localhost:22023'))
```

You should get an output similar to the following :
```console
$> python3 reproductible.py
2020-03-13 11:30:35.297674
2020-03-13 11:30:35.302617
<ClientResponse(http://127.0.0.1:22023/data/91a6570c981c96a35cffc819b203115085e7293c02f3196bd5566bc10b6c1663) [400 Bad Request]>
<CIMultiDictProxy('x-request-id': '0', 'Content-Type': 'text/plain', 'Content-Length': '41')>

2020-03-13 11:30:35.297674
2020-03-13 11:30:35.302617
<ClientResponse(http://127.0.0.1:22023/data/91a6570c981c96a35cffc819b203115085e7293c02f3196bd5566bc10b6c1663) [400 Bad Request]>
<CIMultiDictProxy('x-request-id': '0', 'Content-Type': 'text/plain', 'Content-Length': '41')>

2020-03-13 11:32:06.165579
2020-03-13 11:32:37.738726
<ClientResponse(http://localhost:22023/data/91a6570c981c96a35cffc819b203115085e7293c02f3196bd5566bc10b6c1663) [400 Bad Request]>
<CIMultiDictProxy('x-request-id': '0', 'Content-Type': 'text/plain', 'Content-Length': '41')>

```

As you can see, in our server Setup, it took ~30 seconds to handle the request through `localhost`, while it was instanteneous with `127.0.0.1`.

💡 **Expected behavior**

We expect both `localhost` and `127.0.0.1` to behave the same in terms of connecting to the remote server and running the request.

📋 **Your version of the Python**

```console
$ python --version
Python 3.7.3
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.6.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /opt/shadow.services/scripts/data_manager/venv/lib/python3.7/site-packages
Requires: async-timeout, attrs, multidict, yarl, chardet
```

```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /opt/shadow.services/scripts/data_manager/venv/lib/python3.7/site-packages
Requires: 
Required-by: yarl, aiohttp
```

```console
$ python -m pip show yarl
Name: yarl
Version: 1.4.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /opt/shadow.services/scripts/data_manager/venv/lib/python3.7/site-packages
Requires: multidict, idna
Required-by: aiohttp
```

📋 **Additional context**

As stated in the bug description, this bug happens in our production-ready servers, and I cannot reproduce it on my laptop, for instance.

As I may not be knowledgeable enough in network, I did not know what could be relevant to this, and chose to turn to the community/developers of aiohttp (you), with which I observed the issue.

**Comment by borysvorona** [comment]
@Joacchim It looks like a DNS Resolving issue. Could you share your hosts file here?

**Comment by Joacchim** [comment]
Sure, I only anonymized some company-related hosts 
```console
# cat /etc/hosts
127.0.0.1	localhost
127.0.1.1	lb.domain.com	lb

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by borysvorona** [comment]
The `hosts` file is ok, but I am 100% sure, that your issue related to network setup. This does not apply to the aiohttp. You can find a solution on StackOverflow.

**Comment by Joacchim** [comment]
Well, as it does not seem to occur with tools such as `curl`, I wondered if there was anything specific to aio that could trigger this specifically.

**Comment by Joacchim** [comment]
I could check this up with the team responsible for the network on my side.
Somehow, the IPV6 resolution by default seemed to lead to a path where the network rules enforced were stricter that on IPV4.

This led to this odd situation. Now, I'm still surprised that most of the other tools I tried did not encounter the same issue (`curl`, `nc`...), and wondered what should be done, if anything.

Anyways, thanks for your time, and sorry for bothering you with something that was on us.

Cheers !
