### ISSUE TITLE
ws_connect doesn't follow proxy from environment

### ISSUE THREAD

**Issue by lookis** [aio-libs/aiohttp#4648]
🐞 **Describe the bug**

I have set both http_proxy and https_proxy, with trust_env=True when create ClientSession,
everything is ok when get or post with this session, but for the ws_connect, It doesn't run with proxy.

💡 **To Reproduce**

background: I cann't visit wss://stream.binance.com:9443/ws under my network but it's ok with proxy
1. prepare a proxy at port 1086
1. http_proxy="http://127.0.0.1:1086"
2. https_proxy="https://127.0.0.1:1086"

``` python
import asyncio
import aiohttp
async def main():
    async with aiohttp.ClientSession(trust_env=True) as client:
        await client.ws_connect('wss://stream.binance.com:9443/ws')
        print('ok')

loop = asyncio.get_event_loop()
loop.run_until_complete(main())

```
and it block forever (with a tcp handshake timeout exception)

💡 **Expected behavior**

just connect with proxy

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)

```

📋 **Your version of the Python**

```console
$ python --version
Python 3.7.6
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Version: 3.6.2
```
```console
$ python -m pip show multidict
Version: 4.7.5
```
```console
$ python -m pip show yarl
Version: 1.1.0
```

📋 **Additional context**

https://github.com/aio-libs/aiohttp/blob/bb7a4eaf21782612cc4c24fa75b9368ddb204cc7/aiohttp/client.py#L426
scheme of websocket is ws or wss, url.scheme will always be http or https and ignore any other proxy here 
https://github.com/aio-libs/aiohttp/blob/bb7a4eaf21782612cc4c24fa75b9368ddb204cc7/aiohttp/helpers.py#L232

but it's ok for ws/wss to use http proxy

**Comment by webknjaz** [comment]
Feel free to send a PR with tests bundled.
