### ISSUE TITLE
TCPSite bind address 0.0.0.0 response 406 error

### ISSUE THREAD

**Issue by Junior-Lv** [aio-libs/aiohttp#4649]
🐞 **Describe the bug**
TCPSite bind address 0.0.0.0 response 406 error

💡 **To Reproduce**
This is my demo code

```python3
class DemoHandler(web.View):
    async def get(self):
        return Response(text="hi")


async def main():
    app = web.Application()
    app.add_routes([web.view("/", DemoHandler)])
    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, "0.0.0.0", 8400)
    await site.start()
```

**Comment by webknjaz** [comment]
The issue is not clearly outlined and the repro is incomplete. When I augmented it, I couldn't reproduce the issue, there's no bug here. Next time, provide more details and fill out all fields in the issue template.
