### ISSUE TITLE
aiohttp throws client exception: serverDisconnectedError only on windows

### ISSUE THREAD

**Issue by SmarthomeNinja** [aio-libs/aiohttp#4658]
My code works on OSX, and on Linux, but on Windows 10 throws ServerDisconnectedError

My code simple... connect to the server, ask a .json file (the server sends it, anc close connection) and then processing the answer.

```python
                async with aiohttp.ClientSession(timeout=_TIMEOUT) as session:
                    try:  
                        async with session.get(
                            f"{_host_with_http}/sens_out.json",
                            auth=authenticate,
                        ) as response:
                            if response.status == 200:
                                server_data = json.loads(await response.text())
                            else:
                                _LOGGER.debug("Invalid sens_out.json")
                    except:
                        _LOGGER.debug(sys.exc_info())
```

so this part of program throws the exception:
`(<class 'aiohttp.client_exceptions.ServerDisconnectedError'>, ServerDisconnectedError(None), <traceback object at 0x0A1C7FA8>)`

but only on windows.... 

any issue?

**Comment by webknjaz** [comment]
It would be more useful to see actual traceback.
Also please submit a PR with a test that reproduces this problem.

**Comment by SmarthomeNinja** [comment]
so... the traceback prints this message:

```python-traceback
  File "C:\Users\lck\AppData\Roaming\.homeassistant\deps\Python38\site-packages\myio\comms_thread.py", line 85, in send
    response = await session.get(
  File "C:\Users\lck\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\client.py", line 504, in _request
    await resp.start(conn)
  File "C:\Users\lck\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "C:\Users\lck\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\streams.py", line 591, in read
    await self._waiter
```

**Comment by webknjaz** [comment]
How did you print it? I'm pretty sure it's incomplete. It should contain the whole chain.

**Comment by SmarthomeNinja** [comment]
I printed it with this code:
`traceback.print_tb(e1[2])`
How can I print the whole chain?

I am sorry, but I don't know, how can I submit a PR with tests...
This is a part of home assistant integration, that isn't published yet... but this library is on pypi.org : [https://pypi.org/project/myio/0.0.5/](https://pypi.org/project/myio/0.0.5/)

**Comment by hh-h** [comment]
What python version do you use?

> How can I print the whole chain?

replace `_LOGGER.debug(sys.exc_info())` with `raise`
