### ISSUE TITLE
Exception handling changes exception types unexpectedly

### ISSUE THREAD

**Issue by bitdancer** [aio-libs/aiohttp#466]
I was surprised that my 'except OSError' did not catch network related errors from my application's 'request' call.  The root error was ConnectionResetError, which is a subclass of OSError, and so I would have expected that catching OSError would catch it.  But it gets turned into a ServerDisconnectedError, which is not a subclass of OSError.  Now, it would be simple enough and logical enough to make DisconnectedError a subclass of OSError.  However, the ServerDisconnectedError in turn gets turned into a ClientResponseError (using raise from) for reasons I don't understand, so even if DisconnectedError were an OSError the OSError would still be masked.  In fact I note that the clauses in that same area of client.py explicity turn OSErrors into ClientOSErrors, which I see has been fixed to be a subclass of OSError, but something that started out as an OSError has gotten converted to something else.  Based on looking at that part of the code, I suspect there may be similar problems with masking HTTPErrors.

(I'm not clear on why there are so many custom exception classes, but I wasn't part of the development so I won't comment further on that :)

**Comment by bitdancer** [comment]
This may be another issue, but...I just printed out the error message from the ClientResponseError I got, and it is...absolutely nothing.  Not exactly useful.  I guess I'll have to log the entire exception chain in order to find out what went wrong, which is something I'd rather not do in production, since I don't want to log exceptions when the problem is just a network timeout.

I think it would be much more useful to just let the exceptions bubble up.  At the very least the error message needs to include the error message of the exception being masked.

To put it another way, the value of exception hierarchies is to allow the application to decide to respond to more specific exceptions, or to instead respond to a boad group of exceptions.  Because aiohttp catches the specific exceptions and masks them under a generic exception, the application is prevented from deciding to take action specific exceptions.  My application would have to chase the exception chain in order to find out what _really_ when wrong when I get a ClientResponseError, yet I can't on the other hand decide to handle all network related errors by catching OSError because ClientResponseError is not part of a logical exception hierarchy.

**Comment by asvetlov** [comment]
Well, maybe we need cleanup our exception hierarchy but when you use `traceback.print_exc()` for caught exception you see exception values for all nested exceptions on your chain, isn't it?

IIRC the main reason for not deriving from OSError is: we created custom exception hierarchy. Some exceptions are not OSErrors but parser errors or timeouts. But all of them are derived from `ClientError` base class.

Anyway, if you have a suggestion about exceptions refactoring please share your opinion.

**Comment by bitdancer** [comment]
Yeah, I'm going to try to look in to making a suggestion after I get my code working :)

A timeout should be a subclass of TimeoutError, shouldn't it?  And the base exception in the chain is a server disconnection, and that's an OSError, as I said.  So maybe the bug is that that base error is incorrectly getting turned into something that is not an OSError?  I'll try to investigate further, since I have a unit test that exercises this.  (Note that my code icurrently has to special case ClientResponseError and print out the full traceback so I can see the real error, whereas for those errors that are wrapped in ClientOSError, I can just log the error message...andit is OSError I'm catching).

**Comment by asvetlov** [comment]
I've added more information for raising `ClientOSError`.
See 0a5b068
About TimeoutError: ClientTimeoutError is derived from asyncio.TimeoutError.
The problem is asyncio.TimeoutError is not derived from standard TimeoutError because is has no errno code and asyncio.TimeoutError is logically not OSError.

**Comment by fafhrd91** [comment]
#1661
