### ISSUE TITLE
DEFAULT_JSON_DECODER redefinition

### ISSUE THREAD

**Issue by H--o-l** [aio-libs/aiohttp#4665]
🐣 **Is your feature request related to a problem? Please describe.**

I'm trying to change the value of the variable `DEFAULT_JSON_DECODER` defined here:
https://github.com/aio-libs/aiohttp/blob/4014183/aiohttp/typedefs.py#L25

My goal is to use `aiohttp.web.BaseRequest.json()` with a custom JSON loader, but without giving it each time as parameter.
`aiohttp.web.BaseRequest.json()` can be see here:
https://github.com/aio-libs/aiohttp/blob/72b5344/aiohttp/web_request.py#L577-L588

💡 **Describe the solution you'd like**

```py
import aiohttp
aiohttp.web.BaseRequest.DEFAULT_JSON_DECODER = my_custom_function
```

Or 

```py
import aiohttp
aiohttp.typedefs.DEFAULT_JSON_DECODER = my_custom_function
```

❓ **Describe alternatives you've considered**

📋 **Additional context**

Maybe it's already possible, and it's just a Python feature I don't know yet.
But I didn't find example in the documentation thus I'm a bit lost.

**Comment by mmasztalerczuk** [comment]
I have an idea how I can fix this. The DEFAULT_JSON_DECODER should be a wrapper for user's custom function. Something like that:

`class DefaultJSONDecoder():
    def __call__(self, *args, **kwargs):
        return JSON_DECODER(*args, **kwargs)

JSON_DECODER = json.loads
DEFAULT_JSON_DECODER = DefaultJSONDecoder()`

The user then can set JSON_DECODER to anything he wants to.

What do you think about this solution? If this is ok I can prepare PR for that (+ similar solution for encoder and I found that the DEFAULT_JSON_DECODER is not used in every place as default argument).

**Comment by adrienverge** [comment]
@mmasztalerczuk if I understand correctly, you propose to change aiohttp code to dynamically call `DefaultJSONDecoder().call()` instead of calling `JSON_DECODER()` directly?

If this allows users to set `aiohttp.typedefs.DEFAULT_JSON_DECODER = my_custom_function`, your proposal seems :ok_hand:

**Comment by mmasztalerczuk** [comment]
Yes. The current implementation is using DEFAULT_JSON_DECODER as default value in many functions. So, because python is binding default values to function during compilation time, we are not able to replace this value with another. This is why overwrite DEFAULT_JSON_DECODER doesn't work right now. 

Another solution can be use overwrite __defaults__ with a custom function for every function which is using DEFAULT_JSON_DECODER, but I think that is solution less elegant that first proposition.

**Comment by H--o-l** [comment]
> > If this allows users to set `aiohttp.typedefs.DEFAULT_JSON_DECODER = my_custom_function`, your proposal seems :ok_hand: 
>>
> Yes. The current implementation is using DEFAULT_JSON_DECODER as default value in many functions. So, because python is binding default values to function during compilation time, we are not able to replace this value with another. This is why overwrite DEFAULT_JSON_DECODER doesn't work right now.

@mmasztalerczuk thanks for your quick feedback!
I agree with @adrienverge, if the solution you propose allow to do `aiohttp.typedefs.DEFAULT_JSON_DECODER = my_custom_function`, and it seems it will, then it looks perfect to me.

**Comment by asvetlov** [comment]
Sure, you can monkey-patch the library's internal structures but please don't require that we support it officially :)
