### ISSUE TITLE
Improvements to static routes

### ISSUE THREAD

**Issue by playpauseandstop** [aio-libs/aiohttp#468]
I got into two problems with static routes recently,
1. There are no default ability to enable HEAD requests to static routes
2. Sometimes we need to serve lone static files as routes instead of serving static files inside of static dir

---

Workaround to 1st problem,

``` python
app.router.add_static('/static/', static_dir, name='static')
route = web.StaticRoute(None, '/static/', static_dir)
route._method = 'HEAD'
app.router.register_route(route)
```

Not very elegant solution, IMO

---

Workaround to 2nd problem,

``` python
def view_factory(url, path):
    async def static_view(request):
        prefix = url.rsplit('/', 1)[0] or '/'
        route = web.StaticRoute(None, prefix, static_dir)

        request.match_info['filename'] = path
        return await route.handle(request)
    return static_view

view = static_view('/', 'pages/index.html')
app.router.add_route('GET', '/', view_factory('/', 'pages/index.html'))
app.router.add_route('GET', 
                     '/favicon.ico', 
                     view_factory('/favicon.ico', 'favicon/favicon.ico'))
```

---

In total, I propose imrpove static routes by,
- Adding ability to setup routing HEAD requests to the static files on adding static route
- Adding shortcut or refactor Static Route to be able serve separate files

**Comment by asvetlov** [comment]
Sounds good.
Are you volunteered for the task ?

**Comment by playpauseandstop** [comment]
@asvetlov 

Ok, will try to make a PR today or next week

**Comment by redixin** [comment]
IMO router shouldn't have anything related to serving files. We can have some handler for this:

``` python
    from aiohttp import handlers
    app.router.add_route('GET', '/media/', handlers.static('/var/www/media/', indexes=True))
```

As for HEAD we can allow specifying multiple methods:

``` python
    app.router.add_route({'GET', 'HEAD'}, 'media', handlers.static('/var/www/media/'))
```

And ok. We can still have an alias for setting static route, which will just call add_route with proper handler:

``` python
    app.router.add_static('/static/', static_dir, name='static')
```

and inside add_static:

``` python
     def add_static(self, *args, **kw):
          self.add_route({'GET', 'HEAD'}, handlers.static(*args, **kw))
```

**Comment by asvetlov** [comment]
@redixin _path_ param for `.add_route` should specify full url path, not prefix only. That makes _path_ ugly for static file serving.

**Comment by rutsky** [comment]
@redixin, you mentined `indexes=True` --- any plans for implementing directory listings for static directories?
I think simple directory listings is a good feature.

**Comment by redixin** [comment]
@rutsky I want to finish logging first(https://github.com/KeepSafe/aiohttp/pull/572). After that I can try to look deep into routes/static/indexes.

**Comment by playpauseandstop** [comment]
@redixin 

Great suggestion on having handlers for serving static files. Totally agreed with it!

**Comment by binhnq94** [comment]
Plzz, illustrate where the docs for this solution. :dancer:

**Comment by eteamin** [comment]
@redixin Thank you

**Comment by asvetlov** [comment]
Thanks to @dkuznetsov and #901 now we have a `FileSender` class for sending local file via the wire.
