### ISSUE TITLE
Middleware for static route authentication

### ISSUE THREAD

**Issue by koenvanhauwe** [aio-libs/aiohttp#4681]
🐣 **Is your feature request related to a problem? Please describe.**

Right now I'm using [aiohttp-route-middleware](https://github.com/rob-blackbourn/aiohttp-route-middleware) to give each of my routes an authentication middleware. I'm serving some static files which ideally also need authentication so I would like to use this middleware for those static routes too.

Anyone know how I can add authentication to static routes?

💡 **Describe the solution you'd like**

I know I can define middlewares in web.Application, but I need to define these per route as I have routes that require JWT authentication and routes that require client certificates. That is why I use aiohttp-route-middleware.  I thought it would just be a simple modification to override router.add_static as well, but it doesn't take a handler parameter.

❓ **Describe alternatives you've considered**

**Comment by hh-h** [comment]
Unfortunately, I'm not sure that anyone going to extend the functionality of `add_static`. Let me explain, as you can see from the warning on the docs page, it should be used at all.
> Use add_static() for development only. In production, static content should be processed by web servers like nginx or apache.

I think I'd be right to assume that no one serves static files with aiohttp except some rare cases like yours. So, in summary, you can create a draft MR to discuss the design.

**Comment by koenvanhauwe** [comment]
I see, thank you for clarifying. It probably makes more sense to serve those with nginx or apache in the first place, but I wanted everything in one place for convenience.

**Comment by hh-h** [comment]
You're welcome. The idea is that nginx/apache designed for serve static files efficiently, but aiohttp was created for other things :)
