### ISSUE TITLE
how to get the post data

### ISSUE THREAD

**Issue by wsshopping** [aio-libs/aiohttp#469]
hi:
in my case ,this is my code :  

```
@post('/file')
def file(request):
    for m in request.post():
        print(m)
```

i want to get the post data, and the post request is :  

```
curl -XPOST --data-binary @myfile "http://192.168.1.1:8888/file"

```

but  the result is print nothing , actually, i want to get the data (a file named myfile)

how can i fix it ?

**Comment by krkd** [comment]
request.post is a coroutine.

you must use yield from

```
    for m in (yield from request.post()):
        ....
```
