### ISSUE TITLE
False warning and failure: The object should be created from async function

### ISSUE THREAD

**Issue by AndreVallestero** [aio-libs/aiohttp#4723]
🐞 **Describe the bug**
Reviving warning "The object should be created from async function" even though it is inside an async function. This results in `session.request()` to fail.

💡 **To Reproduce**
1. Install ProxyBroker
2. Try running `broker.find()` within a `coro`
3. Warning raised on session object creation line 79 of https://github.com/constverum/ProxyBroker/blob/master/proxybroker/providers.py
4. Call `session.request()` or request family and it will fail every time

📋 Logs/tracebacks
```console
C:\Program Files\Python37\lib\site-packages\proxybroker\providers.py:78: DeprecationWarning: The object should be created from async function
  headers=get_headers(), cookies=self._cookies, loop=self._loop
C:\Program Files\Python37\lib\site-packages\aiohttp\connector.py:731: DeprecationWarning: The object should be created from async function
  loop=loop)
C:\Program Files\Python37\lib\site-packages\aiohttp\cookiejar.py:55: DeprecationWarning: The object should be created from async function
  super().__init__(loop=loop)
```

💡 **Expected behavior**
No warning is raised on session creation and `session.request()` works as intended

📋 **Your version of the Python**
```console
$ python --version
Python 3.7.7
```

📋 **Your version of the aiohttp/yarl/multidict distributions**
```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.6.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: c:\program files\python37\lib\site-packages
Requires: async-timeout, multidict, chardet, yarl, attrs
Required-by: proxybroker
```
```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\program files\python37\lib\site-packages
Requires:
Required-by: yarl, aiohttp
```
```console
$ python -m pip show yarl
Name: yarl
Version: 1.4.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\program files\python37\lib\site-packages
Requires: idna, multidict
Required-by: aiohttp
```

📋 **Additional context**
aiohttp[speedups]
Windows 10
Client

This bug seems to be the main cause for issue #135 of ProxyBroker:
https://github.com/constverum/ProxyBroker/issues/135

**Comment by asvetlov** [comment]
I'm sorry but aiohttp test suite has tons of `ClientSession` creation lines.
And it explicitly tests that the warning is raised when created from non-async context and nothing happens if the creation is done from an async one.

**Comment by pmp-p** [comment]
i'm not sure it is testing for async context, looks like it is testing if loop is running ( in helpers.py from pypi published version )

**Comment by Dreamsorcerer** [comment]
Which is exactly the same thing....

Here's proof:
```
>>> import asyncio, threading, time
>>> async def main():
...  print("IN LOOP")
...  await asyncio.sleep(10)
...  print("FINISHED WITH LOOP")
... 
>>> def foo():
...   time.sleep(5)
...   print(asyncio.get_running_loop())
... 
>>> foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in foo
RuntimeError: no running event loop
>>> t = threading.Thread(target=foo)
>>> t.start(); asyncio.run(main()); t.join()
IN LOOP
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<stdin>", line 3, in foo
RuntimeError: no running event loop
FINISHED WITH LOOP
```

async context == having a running loop

**Comment by pmp-p** [comment]
Sure async context includes those having an asyncio running loop, but there are context without an asyncio running one that are not included by a get_running_loop test eg 
```py
import asyncio, time, traceback
import contextvars
import builtins

async_sentinel = contextvars.ContextVar('async')
async_sentinel.set(False)

def is_async():
    return async_sentinel.get()


builtins.is_async = is_async

test_now = False

try:
    loop = asyncio.get_running_loop()
except:
    loop = asyncio.get_event_loop()


def get_async_loop():
    global loop, is_running
    if is_async():
        return loop
    else:
        raise RuntimeError("Not running INSIDE an async loop")


get_running_loop_real = asyncio.get_running_loop
asyncio.get_running_loop = get_async_loop

WITH_SLEEP = 0
# patch get_running_loop so sleep(>0) does not bother us
if WITH_SLEEP:
    asyncio.events.get_running_loop = get_async_loop

async def main():
    global test_now, WITH_SLEEP
    print("ASYNC:main is_async=", is_async() )

    for i in range(10):
        if i==5:
            test_now = True
            foo()

        await asyncio.sleep(WITH_SLEEP)

        try:
            #asyncio.get_running_loop()
            get_running_loop_real()
            print(".", i)
        except Exception as ex:
            print("but i'm async i swear", i)


    print("FINISHED WITH LOOP")
    loop.close()


async def asyncmain():
    async_sentinel.set(True)
    await main()

# i don't see a way to get if function is async or not without
# introspection of function
def foo():
    print("?:foo is_async=", is_async())
    time.sleep(1)
    try:
        print(asyncio.get_running_loop())
    except Exception as ex:
        traceback.print_exc()


loop.create_task(asyncmain())


print("__main__ is_async=", is_async())

while not loop.is_closed():
    loop._run_once()
    if test_now:
        foo()
        test_now = False
```


So there are corner cases where published aiohttp is emitting harmless but still false warnings. I hope next version keep that in mind, because aiohttp is very usefull on threadless WebAssembly ports where it is not exactly expected to be asynciohttp but a more genering asynchttp where specific asyncio vision may not always apply ( it takes quite time to match 1:1).

i was using aiohttp to implement PEP0722 on cpython-wasm when i found this, but i guess i must switch to 723 :)

**Comment by Dreamsorcerer** [comment]
You're running an application using a private, undocumented method of a loop. I don't think that should be expected to work...

You mention WebAssembly, do you have a trivial example of something you expect to work (and how to run it)?

**Comment by pmp-p** [comment]
> do you have a trivial example

No nothing - really - simple for now, but it seems patching get_running_loop is enough for WebAssembly ( anyway running synchronous code is not pratical on wasm ) : it silences the annoying false positive warnings for good though it still is tested for.

 So i just thought to inform about a potential unusual use of aiohttp
And that `if sys.platform in ('emscripten','wasi'):` the warnings system could maybe just be turned off ( no more false positive and increased performance by removings the tests for context)

Of course i agree that apart from the minimal speed increase, it is better that asyncio full compatibility is achieved and that aiohttp behaves normally. And i'll try to reach that. If i can't i'll open a specific issue.

**Comment by Dreamsorcerer** [comment]
Yep, let us know when you've got something working and we'll consider such changes.
From my brief search for asyncio on wasm, I could only find things like brython.aio as an alternative to asyncio, which also includes it's own request methods, so probably not something I'd expect aiohttp to be used in (https://www.brython.info/static_doc/en/browser.aio.html). (And without the rest of asyncio, aiohttp is unlikely to work anyway...)

**Comment by pmp-p** [comment]
i use asyncio on [cpython-wasm](https://pygame-web.github.io/showroom/pygbag.html?cpython311&-i&noapp#src/hello.py%20arg1%20arg2) with a [specific wasm eventloop](https://github.com/pygame-web/python-wasm-sdk/tree/main/support/__EMSCRIPTEN__.patches/3.11/asyncio) called via "pygbag" a small pymain modification that does the loop._run_once() from C when vsync occurs in the browser. The above snippet gives the grasp of it ( the while block would be in C intertwined with https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame )

So it is basically libpython compiled for wasm cpu linked to a custom main, running on emscripten os.  [Here you can see it used to run pygame in a browser](https://www.youtube.com/watch?v=oa2LllRZUlU&t=2132s) at PyCon DE 

ref:  Pyodide is the closest to cpython-wasm but has its own async system and uses "fetch" from browser instead of aiohttp so i did not test aiohttp with it, Brython is in fact a python vm written in javascript so ( i guess ) it probably does not need asyncio since js provides coroutines natively.
