### ISSUE TITLE
Allow adding routes to frozen app after application has started when testing only.

### ISSUE THREAD

**Issue by nawarnoori** [aio-libs/aiohttp#4725]
I have a general purpose app fixture that I would like to be able to reuse as much as possible which means that certain tests may want to define their own routes and handlers for it.

Right now defining an ad-hoc route and handler fails with the well-known `RuntimeError: Cannot register a resource into frozen router.`, so I hack around it:

```python
def server(aiohttp_server):
    app = web.Application()
    server = await aiohttp_server(app)
    app.router._frozen = False  # allow tests to define their own routes and handlers
    ...  # do all kinds of set up etc. here that's relevant for all tests
    return server
```

Then the test itself can customise its own response:

```python
def test(server):   
    def response(request, *args, **kwargs):
        return web.json_response({})
    server.app.router.add_get("/server/", response)  # only customise response relevant for this test
    resp = client("/server"/)
    ...
```

That way every test that has the exact same setup fixture-wise can just customise whatever custom response makes sense for that test (the actual use case is a bit more involved but this a stripped down version).

Is it possible to have at least a flag or an allowance for this for testing?

I appreciate the rationale behind it for production, it's just that I don't want every test to have its own identical but independent app fixtures just so a route can be added to them.

It'd be perfect if the app fixture can be customised in the most general way and then each test can customise only what's relevant for it.

**Comment by asvetlov** [comment]
Sorry, I don't think that adding another 'test_only=True' flag to `web.Application` to prevent such checks is a good idea.
If the hack works for you -- that's fine.
If not -- you can slightly modify the test code to accept not fully instantiated server but pre-configured `web.Application` object that can be extended by test before start serving.
