### ISSUE TITLE
mypy AbstractMatchInfo has no attribute "route"

### ISSUE THREAD

**Issue by Dreamsorcerer** [aio-libs/aiohttp#4748]
When running mypy, I get the error:
`error: "AbstractMatchInfo" has no attribute "route"  [attr-defined]`

From this code:
```
        match_info = await request.app.router.resolve(request_clone)
        if isinstance(match_info.route, web.ResourceRoute):
```

But, looking at the code, it looks to me like everything is actually returning a `UrlMappingMatchInfo`, which does have this attribute.

Would it make sense to just change the return to `UrlMappingMatchInfo`? I can't see why you would get another type returned from this function.

**Comment by asvetlov** [comment]
Sorry for the late response.

Historically, I thought that AbstractMatchInfo can work with custom URL resolvers in additional to the default UrlDispatcher.
For example, sometimes a traversal-based resolver can look attractive.

The idea has failed for several reasons but the ABC class was not updated.
Please feel free to publish a PR.
