### ISSUE TITLE
StreamWriter appends not wanted information.

### ISSUE THREAD

**Issue by MatthiasSchild** [aio-libs/aiohttp#475]
I'm currently working on a mjpeg proxy server with aiohttp. I use the StreamWriter to transmit the information. But if I'm using

``` python
sr.write(b"x")
sr.write(b"y")
sr.write(b"z")
```

the StreamResponse appends the length of the chunk with a newline

```
x1\r\ny1\r\nz1\r\n
```

Is there a posibility to send raw data?

---

EDIT:

I wrote StreamWriter, but i mean StreamResponse.
I've found out that the StreamResponse uses the chunked transfer encoding and those "not wanted information" are part of it.

**Comment by asvetlov** [comment]
Would you provide a test that reproduces your problem?

I've wrote one: 

```
    def test_stream_response_multiple_chunks(self):
        @asyncio.coroutine
        def handler(request):
            resp = web.StreamResponse()
            resp.start(request)
            resp.write(b'x')
            resp.write(b'y')
            resp.write(b'z')
            return resp

        @asyncio.coroutine
        def go():
            _, srv, url = yield from self.create_server('GET', '/', handler)
            client = ClientSession(loop=self.loop)
            resp = yield from client.get(url)
            self.assertEqual(200, resp.status)
            data = yield from resp.read()
            self.assertEqual(b'xyz', data)
            yield from resp.release()

        self.loop.run_until_complete(go())
```

and it works as expeced.

**Comment by vbraun** [comment]
I think this is the same as #476, chunked transfer requires a HTTP/1.1 client to make sense of the reply

**Comment by asvetlov** [comment]
Perhaps yes. Let's close the issue.
