### ISSUE TITLE
_pong_response_cb does not close websocket

### ISSUE THREAD

**Issue by louisabraham** [aio-libs/aiohttp#4755]
I'm running a web app and have the infamous `socket.send() raised exception.` bug.

I cannot give any reproducible example but I ran the loop in a thread, thus giving me access to the REPL.

I created my WebSocket with `web.WebSocketResponse(heartbeat=5)`.

The problem seems to be that `_pong_not_received` was called but did not close the websocket. The REPL indicates that `ws._req.transport` is None, which is the reason why it does not do anything.

https://github.com/aio-libs/aiohttp/blob/48bf8c356c7c3bac5d520484ede5c35bd1795afb/aiohttp/web_ws.py#L113-L118

Why is the condition checked? I think the assumptions are too strong and the check should only be made before calling `self._req.transport.close()`.

**Comment by bdraco** [comment]
Yes
