### ISSUE TITLE
ClientResponseError raised by "raise_for_status" does not contain response body

### ISSUE THREAD

**Issue by mfrlin** [aio-libs/aiohttp#4760]
🐣 **Is your feature request related to a problem? Please describe.**
APIs return description of the problem in the body but the response body is lost if you use `raise_for_status`.

💡 **Describe the solution you'd like**
`raise_for_status` should throw exception that includes response body (or whole response for that matter).

**Comment by borysvorona** [comment]
Already mentioned here https://github.com/aio-libs/aiohttp/issues/4600

**Comment by andrea-cassioli-maersk** [comment]
Same issue here. I would expect to have the response body back from the request also in case of error (quite important when debugging!)

**Comment by HansBrende** [comment]
@mfrlin @andrea-cassioli-maersk after much tinkering, I was able to create a workaround for this issue while we are waiting for aiohttp v4 to come out. Implementation here: https://github.com/aio-libs/aiohttp/issues/4600#issuecomment-922520737

**Comment by towards-a-new-leftypol** [comment]
I am using wireshark for now to get the response message, but I need to log what the server sends back. Maybe it's as simple as a change like this:

```diff
diff --git a/aiohttp/client_exceptions.py b/aiohttp/client_exceptions.py
index f7023ef8..65d6de88 100644
--- a/aiohttp/client_exceptions.py
+++ b/aiohttp/client_exceptions.py
@@ -63,6 +63,7 @@ class ClientResponseError(ClientError):
         status: Optional[int] = None,
         message: str = "",
         headers: Optional[LooseHeaders] = None,
+        response: ClientResponse
     ) -> None:
         self.request_info = request_info
         if status is not None:
@@ -73,6 +74,7 @@ class ClientResponseError(ClientError):
         self.headers = headers
         self.history = history
         self.args = (request_info, history)
+        self.response = response
 
     def __str__(self) -> str:
         return "{}, message={!r}, url={!r}".format(
diff --git a/aiohttp/client_reqrep.py b/aiohttp/client_reqrep.py
index 3d7a90d6..dd3ebe2a 100644
--- a/aiohttp/client_reqrep.py
+++ b/aiohttp/client_reqrep.py
@@ -860,6 +860,7 @@ class ClientResponse(HeadersMixin):
                         status=exc.code,
                         message=exc.message,
                         headers=exc.headers,
+                        response=self
                     ) from exc
 
                 if message.code < 100 or message.code > 199 or message.code == 101:
@@ -964,6 +965,7 @@ class ClientResponse(HeadersMixin):
                 status=self.status,
                 message=self.reason,
                 headers=self.headers,
+                response=self
             )
 
     def _cleanup_writer(self) -> None:
```

**Comment by Dreamsorcerer** [comment]
I don't see how this can work, it seems to me like you'd be better not using raise_for_status for this scenario. To include the body on the exception would require reading the body from the connection, which could lead to memory/DoS issues, the code hanging or other exceptions happening. If we included the response object itself, then the connection for it would be closed when the exception propagates outside the `async with`...
