### ISSUE TITLE
Handlers should be awaited / documentation should advise to use a try block

### ISSUE THREAD

**Issue by louisabraham** [aio-libs/aiohttp#4763]
My API was silently failing because my handler function raised exceptions that were never reported because they happened in the handler async function that is not awaited.

This could be avoided in 2 ways:
- awaiting the handler task in the aiohttp code
- wrapping the handler code inside a try block, which should be suggested in the docs

**Comment by WisdomPill** [comment]
Can you provide some snippets so I can understand better what you are asking?

**Comment by louisabraham** [comment]
Hi, it's simple:

```
async def handler(request):
    do_something()
app = web.Application()
app.add_routes([web.get("/", handler)])
loop = asyncio.new_event_loop()
runner = web.AppRunner(app)
loop.run_until_complete(runner.setup())
site = web.TCPSite(runner, '0.0.0.0', 8080)
loop.run_until_complete(site.start())
loop.run_forever()
```

if `do_something` raises an exception, I won't be able to see it.

**Comment by asvetlov** [comment]
1. Web-handler **is** awaited, sure.
2. An exception in web-handler is stored in logs. The same is true for any python server
