### ISSUE TITLE
How to forward/proxy requests to different server?

### ISSUE THREAD

**Issue by MarSoft** [aio-libs/aiohttp#4768]
🐣 **Is your feature request related to a problem? Please describe.**

I have an `aiohttp.web` server. I want one of its endpoints to forward request to some other server: client sends request to `http://myserver/proxy`, then the server makes request to `http:/otherserver/some/endpoint` with the same HTTP method, params and body, then it forwards response back to the client.
This can obviously be achieved with trivial code like this:
```python
session = aiohttp.ClientSession()

@routes.post('/proxy')
async def proxy(request):
    body = await request.text()
    resp = await session.post('http://otherserver/some/endpoint', params=request.params, data=body)
    result = await body.text()
    return web.Response(body=result, status=resp.status, headers=resp.headers, ...)
```
This will work but it will read all the response to the memory before sending it to the client. This is not optimal, especially with large responses (or requests).

💡 **Describe the solution you'd like**

There should be some way to achieve this using `web.StreamResponse`. But I could not find how to do that.

❓ **Describe alternatives you've considered**

Described above.

📋 **Additional context**

**Comment by MarSoft** [comment]
Here is what I came up with for now. In this case I didn't need to pass along the request body though.
```python
# disable automatic decompression of gzip
session = aiohttp.ClientSession(auto_decompress=False)
# make sure session will be closed in the end
async def on_cleanup(app):
    await session.close()
app.on_cleanup.append(on_cleanup)

@routes.post('/proxy')
async def proxy(request):
    ...  # prepare params
    async with session.post(
        'http://otherserver/some/endpoint',
        params=dict(...),
        headers={
            h: self.request.headers[h]
            for h in [
                'Accept',
                'Accept-Encoding',
            ]
        },
    ) as r:
        sr = web.StreamResponse(status=r.status)
        count = sr.content_type = r.content_type
        sr.content_length = r.content_length
        sr.charset = r.charset
        sr.headers['Cache-Control'] = r.headers['Cache-Control']
        sr.headers['Content-Encoding'] = r.headers['Content-Encoding']

        # send headers out
        writer = await sr.prepare(self.request)
        # and send the response
        async for chunk, _ in r.content.iter_chunks():
            await writer.write(chunk)

        return sr
```
Not sure if it is optimal though. Would be good if there would be some helpers for such use cases.

**Comment by Dreamsorcerer** [comment]
Aiohttp is not suited to being a proxy server, so I don't think we'll add any helpers for this.
