### ISSUE TITLE
would like an option to remove Content-Length header from form data

### ISSUE THREAD

**Issue by thomasvs** [aio-libs/aiohttp#4782]
## Long story short

I have a Meural canvas which allows doing a FORM post of an image.
However, the post silently fails if the form data contains a Content-Length: line, and succeeds without it.

Sending this fails:

POST /remote/postcard HTTP/1.1
Host: localhost:8000
User-Agent: HomeAssistant/0.111.0.dev0 aiohttp/3.6.1 Python/3.7
Accept: */*
Accept-Encoding: gzip, deflate
Content-Length: 30028
Content-Type: multipart/form-data; boundary=f08d770c983b491e96525cc677a1ab3e

--f08d770c983b491e96525cc677a1ab3e
Content-Type: image/jpeg
Content-Disposition: form-data; name="photo"; filename="image.jpg"
Content-Length: 29833

<FF><D8><FF><E0> (snip)

Sending this succeeds:

POST /remote/postcard HTTP/1.1
Host: localhost:8000
User-Agent: HomeAssistant/0.111.0.dev0 aiohttp/3.6.1 Python/3.7
Accept: */*
Accept-Encoding: gzip, deflate
Content-Length: 30005
Content-Type: multipart/form-data; boundary=7bb201696ae046aeb0b3fa5a26a3a2d1

--7bb201696ae046aeb0b3fa5a26a3a2d1
Content-Type: image/jpeg
Content-Disposition: form-data; name="photo"; filename="image.jpg"

<FF><D8><FF><E0> (snip)

Commenting out the line in multipart.py that sets it:
        #    payload.headers[CONTENT_LENGTH] = str(size)

produces output that works, without Content-Length in the form data.

There doesn't seem to be a way I can avoid adding it; one of encoding and te_encoding needs to be non-False but the defaults of identity and binary explicitly reset them, so there is no option for either encoding or te_encoding that I can use without modifying the data.

Related issue: https://github.com/aio-libs/aiohttp/issues/2062

**Comment by Dreamsorcerer** [comment]
Adding a Content-Length to the parts is actually invalid multipart/form-data. This was fixed in a recent release.
