### ISSUE TITLE
Make `force` attr for `ClientResponse.close()` `True` by default

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#479]
`resp.close(force=False)` is not safe: you should make sure that all response body has been read.
That can be done by `yield from resp.release()` call.
So let's change `.close()` to _forcing close_ behavior. This simplifies response usage rules.

Appliying `.close(force=False)` should produce `DeprecationWarning` in next releases (say, until New Year). After that let's remove the parameter completely.

**Comment by fafhrd91** [comment]
is there other way to force close request socket?

**Comment by asvetlov** [comment]
@fafhrd91 except `resp.close(force=True)`? I'm not aware about alternatives.

**Comment by fafhrd91** [comment]
oh, i misunderstand description. +1

**Comment by asvetlov** [comment]
Done
