### ISSUE TITLE
Recommend aiohttp-csrf inclusion (In aiohttp or aio-libs).

### ISSUE THREAD

**Issue by bitnom** [aio-libs/aiohttp#4802]
3 years ago, the [aiohttp-csrf](https://github.com/asvetlov/aiohttp-csrf) repository was initialized. For 3 years, the master branch was left blank, the code left in the `init` branch, and nothing submitted to pypi. It was basically abandoned.

This year, I [forked the repo](https://github.com/TensorTom/aiohttp-csrf), transferred the code to the master branch, [fixed bugs/added features](https://github.com/TensorTom/aiohttp-csrf/commits/master), and gave the module [its pypi entry](https://pypi.org/project/aiohttp-csrf/).

I would like to request that aiohttp-csrf either be rolled into aiohttp or added as an aio-libs repo under the aio-libs account (Probably better). If you'd like to do the latter, I'll take whatever steps are asked of me to make your repo the obvious official repo on github and pypi. I will continue to contribute to it as I'm able.

**Comment by webknjaz** [comment]
I'm okay with moving your fork to this org as long as you are committed to maintaining it. It'll probably be necessary to improve some CI/CD setup and configure it to use our PyPI bot account with an API token for uploads.

**Comment by bitnom** [comment]
> I'm okay with moving your fork to this org as long as you are committed to maintaining it. It'll probably be necessary to improve some CI/CD setup and configure it to use our PyPI bot account with an API token for uploads.

Sounds good. I'll start fixing up the repo to the standard of the others as time permits. I pinged you on gitter to receive whatever else might be necessary, at your convenience.

**Comment by webknjaz** [comment]
Replied on Gitter. You need to add me to the repo so I'd be able to make the move.

**Comment by zAbdelAziz** [comment]
any updates on this matter?

**Comment by webknjaz** [comment]
Looks like @bitnom never proceeded with giving me the required privileges. I don't see any replies on Gitter. Closing the issue since it doesn't look like he's interested anymore.
