### ISSUE TITLE
How to customize stream response

### ISSUE THREAD

**Issue by Ailibert** [aio-libs/aiohttp#4814]
Now I have a function that needs to use aiohttp to forward the request, but this request returns a large file. I need aiohttp to return it in the form of a stream. I tried the web stream response, but I didn’t have the request parameter. How can I return a request 
Available stream responses

`

    async def download_image_file(self, uuid):
        """
        :param uuid:
        :return:
        """
        url = f"{self.ns_base_url}/{uuid}/download"
        return await self._download(url)

    @staticmethod
    async def _download(url, json_data=None, data=None):
        async with aiohttp.ClientSession() as session:
            async with session.post(url, json=json_data, data=data) as response:
                return await response.content.read()
`

**Comment by Ailibert** [comment]
Stream response must be achieved through the web？？

**Comment by asvetlov** [comment]
Sorry, I don't follow.
Please open a new better-constructed issue if you still need an answer
