### ISSUE TITLE
ClientSession default_trace_configs 

### ISSUE THREAD

**Issue by adamko147** [aio-libs/aiohttp#4834]
🐣 **Is your feature request related to a problem? Please describe.**
We use client tracing to report downstream API calls to central tracing system. While this works great for sessions initiated from our code, some libraries we use create own client session and often don't have possibility  to tweak it by providing e.g. session class or any other way how to configure the session. 

💡 **Describe the solution you'd like**
It would be great to have possibility to set up default `trace_configs` for each new session created. Ideal would be sth like
```python
ClientSession.default_trace_configs = [custom_trace_config]
```
custom trace config would be then used for every new ClientSession instance, regardless who created the session.

❓ **Describe alternatives you've considered**
Some libraries allows to pass session class, so that could be done using derived custom client session, however that won't solve issue with libs that won't allow that, e.g. kubernetes_asyncio. Also, patching `aiohttp.ClientSession` with derived class could be solution, but that seems to me rather as a hack.

**Comment by asvetlov** [comment]
Sorry, I'm inclining to rejection of the proposal.
Changing the global state is not an option; better to adopt a particular library (e.g. kubernetes_asyncio) to accept trace configs.
