### ISSUE TITLE
Correct response for not allowed methods CONNECT

### ISSUE THREAD

**Issue by RemiZOffAlex** [aio-libs/aiohttp#4858]
RFC 7231 Method Definitions:
* GET
* HEAD
* POST
* PUT
* DELETE
* CONNECT Issue: https://github.com/aio-libs/aiohttp/issues/4571
* OPTIONS
* TRACE

**Comment by webknjaz** [comment]
Please fill in an issue template instead of removing it. W/o a full context, this is not a bug but a few words making not much sense.
