### ISSUE TITLE
Boolean Type error in GET request params

### ISSUE THREAD

**Issue by ajyadav013** [aio-libs/aiohttp#4874]
When a boolean value is passed in a dictionary as params to the GET request, it gives an error - TypeError: Invalid variable type: value should be str or int, got True of type <class 'bool'>

```python
params = {"enabled": True}
import aiohttp 
async with aiohttp.ClientSession(auth=None) as session: 
    async with session.get(url, params=params)  as resp: 
        await resp.content.read() 
```

Env:
Python - 3.8
aiohttp - 3.6.2

This works if I use the params this way - {"enabled": "true"}
If the params are being accepted as a dictionary, then it should accept a boolean as a value type too.
Do correct me if I am wrong or if there's another way to fetch the results.

**Comment by webknjaz** [comment]
Boolean mustn't be accepted because it's not clear how it should be turned into a string. It's by design. Full explanation here: https://github.com/aio-libs/yarl#why-isnt-boolean-supported-by-the-url-query-api.
