### ISSUE TITLE
Way to define or delete the filename* field on a Content-Disposition part

### ISSUE THREAD

**Issue by umbreak** [aio-libs/aiohttp#4875]
Having the following code:
```python
    data = aiohttp.FormData()
    data.add_field('file', open(_file_, 'rb'), filename='other.txt', content_type='text/plain')
    async with aiohttp.ClientSession(headers=headers) as session:
        await session.post(_endpoint_, data=data)
```

Performs a `multipart/form-data` with a boundary block as follows
```
Content-Type: text/plain
Content-Disposition: file; filename="other.txt"; filename*=utf-8''other.txt
_file content_
```

However why `filename*` field has the value `utf-8''other.txt`? How can I manipulate that value? It should be the client who decides what to put there, for example:
```python
data.add_field('file', open(_file_, 'rb'), filename='other.txt', filenameUTF8 = 'other_whatever.txt' content_type='text/plain')
```

Note that this is a problem because the service will always prefer the `filename*` according to the RFC6266:
> Therefore, when both "filename" and "filename*" are present in a single header field value, recipients SHOULD pick "filename*" and ignore "filename"

So I will end up with filenames in my server with the prefix `utf8''` without the possibility to change it.

**Comment by umbreak** [comment]
There is a convoluted way of making this work, setting the header 'manually':

```python
    data = aiohttp.MultipartWriter('form-data')
    part = data.append(open(_file_, 'rb'))
    part.headers[aiohttp.hdrs.CONTENT_DISPOSITION] = 'form-data; name="file"; filename="other.txt"; filename*="other_filename.txt"'
    async with aiohttp.ClientSession(headers=headers) as session:
        await session.post(_endpoint_, data=data)
```

However I find it overly complicated

**Comment by hyzyla** [comment]
According to [RFC5987](https://tools.ietf.org/html/rfc5987) `filename*=utf-8''other.txt` is correct writing of filename in extended notation

**Comment by umbreak** [comment]
Many HTTP servers out there would just get the value of the field, without extra encoding.

I see that the RFC specifies encoding on fields, but in real world scenarios you find several http servers that do not implement it in this way and just get the value of the `filename*` field. In our case is the Akka HTTP server who's not dealing with the encoding part of the `filename*` value, as explained in the following issue: https://github.com/akka/akka-http/issues/1240

It would be nice to be able to change it s desired. But I understand your point. In any case, this issue might be useful as a documentation for someone...

**Comment by hyzyla** [comment]
Fully agree with you. I think, we can change type of issue to `Enhancement`: "Add filename_extended to FormData.add_field" and ask maintainers opinion about this enhancement

**Comment by 2foil** [comment]
> There is a convoluted way of making this work, setting the header 'manually':
> 
> ```python
>     data = aiohttp.MultipartWriter('form-data')
>     part = data.append(open(_file_, 'rb'))
>     part.headers[aiohttp.hdrs.CONTENT_DISPOSITION] = 'form-data; name="file"; filename="other.txt"; filename*="other_filename.txt"'
>     async with aiohttp.ClientSession(headers=headers) as session:
>         await session.post(_endpoint_, data=data)
> ```
> 
> However I find it overly complicated

Here is the way I take, to delete the useless `filename*`:

```python
data = aiohttp.MultipartWriter('form-data')
part = data.append(open(_file_, 'rb'))
part.set_content_disposition("form-data", name="file", filename="other.txt")
part.headers[aiohttp.hdrs.CONTENT_DISPOSITION] = '; '.join(part.headers[aiohttp.hdrs.CONTENT_DISPOSITION].split('; ')[:-1])
```
Just pop the last item `filename*=utf-8"xxx`
It avoid setting the header 'manually'

**Comment by Dreamsorcerer** [comment]
The parameter doesn't appear to be sent anymore (spec says it must not be used anyway: https://datatracker.ietf.org/doc/html/rfc7578#section-4.2).
