### ISSUE TITLE
Aiohttp server randomly stops with winerror 64

### ISSUE THREAD

**Issue by dl250123** [aio-libs/aiohttp#4876]
Aiohttp server randomly stops with a OSError: [WinError 64] The specified network name is no longer available

see https://stackoverflow.com/questions/61120572/aiohttp-server-critical-error-when-disconnecting-from-clients

OS: Windows 10 - Python: 3.8.4 - aiohttp: 3.6.2

**Comment by asvetlov** [comment]
I guess the mentioned error can be ignored, it doesn't terminates the server

**Comment by forhonourlx** [comment]
Similar Error.server stops.
