### ISSUE TITLE
Don't work "multipart/form-data" file upload.

### ISSUE THREAD

**Issue by Cykooz** [aio-libs/aiohttp#490]
Example for reproduce my case:

``` python
import asyncio
import aiohttp  # version 0.17.3
import io

data = {'file': io.BytesIO(b'some buffer')}
url = 'http://requestb.in/pdt7vypd'
f = aiohttp.request('post', url, data=data)
asyncio.get_event_loop().run_until_complete(f)
```

After running this code "RequestBin" has the following data:

```
multipart/form-data; boundary="22335db0b3594db981b72bd5d424c366"
0 bytes 

HEADERS

Via: 1.1 vegur
Connection: close
Total-Route-Time: 0
Accept: */*
Connect-Time: 13
X-Request-Id: 50f58dd3-3d12-4e72-a3f4-92c64fac1cdd
Accept-Encoding: gzip, deflate
Transfer-Encoding: chunked
Content-Type: multipart/form-data; boundary="22335db0b3594db981b72bd5d424c366"
User-Agent: Python/3.4 aiohttp/0.17.3
Host: requestb.in

FORM/POST PARAMETERS
None 

RAW BODY
None
```

It looks as if the server received a request with an empty body. 'Content-Length' header is not present at all.

**Comment by asvetlov** [comment]
I don't follow.

The [test](https://github.com/KeepSafe/aiohttp/blob/master/tests/test_client_functional2.py#L141) is passed. How to reproduce your issue?

**Comment by Cykooz** [comment]
To reproduce:
- go to http://requestb.in/;
- press "Create a RequestBin" and copy link at the top-right corner;
- run shell of python3 with installed aiohttp;
- execute my example code from first post.

Also you can make simple page with the form for file upload (without CSRF-protection) using Django.

**Comment by Cykooz** [comment]
I think that this problem is because of http://requestb.in and Django require to specify Content-Length for the whole request. :(

**Comment by kxepal** [comment]
That's my lovely issue with multipart (: Seems like it [won't](https://code.djangoproject.com/ticket/10819) be fixed for Django in nearest future.
