### ISSUE TITLE
Handling basic auth with a middleware or a request annotation

### ISSUE THREAD

**Issue by athoune** [aio-libs/aiohttp#491]
Does it already exist, du you want a pull request for that?

**Comment by asvetlov** [comment]
Security is not a part of aiohttp and perhaps will never be included.
There is [aiohttp_security](https://github.com/aio-libs/aiohttp_security) library that tries to solve auth/autz issues. It's almost ready but still not released yet.
The code looks good but I need write documentation for the library.
