### ISSUE TITLE
AttributeError: module 'ssl' has no attribute 'SSLContext'

### ISSUE THREAD

**Issue by tallgaijin** [aio-libs/aiohttp#4919]
🐞 **Describe the bug**
Any usage of aiohttp is causing an error. It looks like this is an issue related to libraries that have changed as SSL/TLS versions have changed, but my knowledge of Python is very limited and I'm struggling to figure out what the precise cause is.

💡 **To Reproduce**

import aiohttp is all that's required.

Issue occurred on Windows, switched to Ubuntu and it was fine, but now the issue is happening on Ubuntu.
Using VSCode.

💡 **Expected behavior**

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
Traceback (most recent call last):
  File "/home/adam/Documents/Crawler/test.py", line 1, in <module>
    import aiohttp
  File "/home/adam/.local/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/home/adam/.local/lib/python3.8/site-packages/aiohttp/client.py", line 34, in <module>
    from .client_exceptions import ClientConnectionError as ClientConnectionError
  File "/home/adam/.local/lib/python3.8/site-packages/aiohttp/client_exceptions.py", line 11, in <module>
    SSLContext = ssl.SSLContext
AttributeError: module 'ssl' has no attribute 'SSLContext'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/home/adam/.local/lib/python3.8/site-packages/requests/__init__.py", line 103, in <module>
    from urllib3.contrib import pyopenssl
  File "/home/adam/.local/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 84, in <module>
    ssl.PROTOCOL_TLSv1: OpenSSL.SSL.TLSv1_METHOD,
AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLSv1'

Original exception was:
Traceback (most recent call last):
  File "/home/adam/Documents/Crawler/test.py", line 1, in <module>
    import aiohttp
  File "/home/adam/.local/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/home/adam/.local/lib/python3.8/site-packages/aiohttp/client.py", line 34, in <module>
    from .client_exceptions import ClientConnectionError as ClientConnectionError
  File "/home/adam/.local/lib/python3.8/site-packages/aiohttp/client_exceptions.py", line 11, in <module>
    SSLContext = ssl.SSLContext
AttributeError: module 'ssl' has no attribute 'SSLContext'
```

📋 **Your version of the Python**

```console
$ python --version
...
3.8.2
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
...
3.6.2
```
```console
$ python -m pip show multidict
...
4.7.6
```
```console
$ python -m pip show yarl
...
1.5.1
```

📋 **Additional context**

Tried updating packages, uninstalling and reinstalling, but still getting the error. Tried pip3 install ssl, but got an error, it seems that package is no longer actively maintained?

**Comment by webknjaz** [comment]
Looks like you have a CPython install w/o SSL compiled-in. If that's the case, get a proper one. Also, since you use a user-global site-packages location, you may have messed up that env. Try using a proper virtualenv first.

**Comment by tallgaijin** [comment]
> CPython install w/o SSL compiled-in

On my Windows computer, I downloaded from the Python website. In my Linux computer, it's what came with Ubuntu. 

I tried "import ssl" but that didn't trigger any errors.

I also checked my OpenSSL version but it seems to be up to date: openssl is already the newest version (1.1.1f-1ubuntu2).

**Comment by webknjaz** [comment]
Can it be that you monkey-patch `ssl` in your script somehow? `SSLContext` was introduced in Python 2.7.9 so it should be there.

**Comment by webknjaz** [comment]
> AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLSv1'

this one is unrelated to aiohttp in any way, it comes from your requests client

**Comment by webknjaz** [comment]
> AttributeError: module 'ssl' has no attribute 'SSLContext'

This one is happening @ https://github.com/aio-libs/aiohttp/blob/1d296d5/aiohttp/client_exceptions.py#L10 during import time and this means that you have some other package/module in your `PYTHONPATH` or likely in your user-global site-packages so `import ssl` picked up that different thing called `ssl` that is not coming from stdlib.

You can inject a `debugger()` between the import and the attribute access line in your `/home/adam/.local/lib/python3.8/site-packages/aiohttp/client_exceptions.py`, and maybe `print(ssl.__file__)` to see what it actually imported.

And just to reiterate: use virtualenv, your problem is probably related to the fact that you dump a lot of stuff into the shared env from other projects and it has conflicts.

**Comment by webknjaz** [comment]
P.S. Ubuntu is infamous for breaking their Python layout (and Python-related packaging). So be careful with that and don't install things into system-global site-packages (and dist-packages for that matter) because you may easily break your system beyond recovery.

**Comment by webknjaz** [comment]
Here's a few pointers for you:
* https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment
* https://virtualenv.pypa.io/

(the first link suggests using built-in `venv` but I still recommend going for `virtualenv` because there was a major rewrite at the end of the previous year that's made it way faster)

**Comment by tallgaijin** [comment]
Thanks for the pointers, I found the issue...silly mistake, I had a test file in the same folder named ssl.py.
