### ISSUE TITLE
Does aiohttp make use of multi cores or single one?

### ISSUE THREAD

**Issue by ipeisong** [aio-libs/aiohttp#492]
Like Tornado that can make use of N cores by set proper parameters. Thanks.

**Comment by ludovic-gasc** [comment]
You can use the gunicorn worker as described in the documentation. 
In case of you need to serve other protocols than HTTP, you can use API-Hour.

**Comment by asvetlov** [comment]
Or just push several aiohttp processes behind nginx reverse proxy.
