### ISSUE TITLE
ServerDisconnectedError when using concurrency is > 100 clients

### ISSUE THREAD

**Issue by pmanoj133** [aio-libs/aiohttp#4923]
## Long story short

I have started using aiohttp. This is the client code structure:
If I am using more than 100 URLs, I am getting ServerDisconnectedError error. Using semaphore also didn't help here.
Is there a mechanism to reconnect the connection?
## Steps to reproduce

async def fetch(session, url):
    async with session.get(url) as response:
        resp_text = await response.text()
        return orjson.loads(resp_text)

async def fetch_all(urls):
    async with aiohttp.ClientSession(connector=aiohttp.TCPConnector(ssl=False)) as session:
        texts = []
        try:
            texts = await asyncio.gather(*[
                    fetch(session, url)
                    for url in urls ])
        except aiohttp.ServerDisconnectedError as e:
            print ("ServerDisconnectedError")
            return "Failure"
      return texts

loop.run_until_complete(fetch_all(urls_to_fetch))

## Your environment

aiohttp : 3.7
Client

**Comment by Dreamsorcerer** [comment]
Can you provide a complete reproducer? I can't seem to reproduce the issue, it could easily just be that the server has timed out the connection...
