### ISSUE TITLE
Allow to send list as a value for params in ClientSession

### ISSUE THREAD

**Issue by paulefoe** [aio-libs/aiohttp#4929]
🐣 **Is your feature request related to a problem? Please describe.**
In `requests` you can do something like this:
r.get('https://www.archlinux.org', params={'ids': [1,2,3,4,5,6]})
and the resulting url would be
https://www.archlinux.org/?ids=1&ids=2&ids=3&ids=4&ids=5&ids=6

The current behavior in `aiohttp` is to raise `TypeError`

`TypeError: Invalid variable type: value should be str or int, got [1, 2, 3, 4, 5] of type <class 'list'>`

💡 **Describe the solution you'd like**
My suggestion is to convert a list like this to list of tuples in the end, i.e.:
```
params={
   some: 1,
   list_ids: [1,2 ,3 ]
}
```
would look like this:
```
[('some', 1), ('list_ids', 1), ('list_ids', 2), ('list_ids', 3)]
```

📋 **Additional context**
If the community decides that this is desirable behavior I am more than willing to work on it.

**Comment by WolframAlph** [comment]
@webknjaz is this the behaviour we want to have?

**Comment by webknjaz** [comment]
I believe there's been something similar merged into yarl master recently. Check that out first.

**Comment by webknjaz** [comment]
Try searching and linking related issues and PRs, if you find something.

**Comment by paulefoe** [comment]
https://github.com/aio-libs/yarl/pull/443
https://github.com/aio-libs/aiohttp/issues/4714

Yeah, here it is.
