### ISSUE TITLE
How to properly store the aiohttp.ClientSession()

### ISSUE THREAD

**Issue by vgoklani** [aio-libs/aiohttp#4932]
Hey there,

I need to store the ClientSession() object for easy-reuse: 

    class MySession(object):
        def __init__(self):
            self._session = asyncio.ClientSession() # ideally

Unfortunately I'm unable to store the session object directly, even with an async call, as the ClientSession() object can't be awaited.

However, I see that it's possible via the documentation, but I'm unable to replicate those snippets. Please see the links below:

1. https://docs.aiohttp.org/en/stable/client_advanced.html#connectors

    ```python
    conn = aiohttp.TCPConnector()
    session = aiohttp.ClientSession(connector=conn)

     # DeprecationWarning: The object should be created from async function
    ```

2. https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession
same issue, unable to replicate this line:

    ```python
    client_session = aiohttp.ClientSession(raise_for_status=True)

     # DeprecationWarning: The object should be created from async function
    ```

---

Here's my more general attempt:

   ```python
	import asyncio
	import aiohttp

	loop = asyncio.get_event_loop()


	async def get_session1():
		await aiohttp.ClientSession()


	async def get_session2(self):
		return aiohttp.ClientSession()


	# Fails, DeprecationWarning: The object should be created from async function
	session = aiohttp.ClientSession()

	# Fails, ClientSession can't be used in 'await' expression
	session = loop.run_until_complete(get_session1())

	# Fails, An asyncio.Future, a coroutine or an awaitable is required
	session = loop.run_until_complete(get_session2())

    ```

I'm using aiohttp.__version__ = 3.6.2 with Python 3.7.7 on Ubuntu.

How do I properly store the session object so it's easy to reuse, without re-creating a separate instance each time? Thanks!

Note: This was also asked here: https://github.com/aio-libs/aiohttp/issues/3658

cc: @asvetlov

**Comment by hyzyla** [comment]
you can use builder pattern

```python
 import asyncio
 import aiohttp

class MySession:
    def __init__(self, session):
        self._session = session

async def build_session(*args, **kwargs):
      session = aiohttp.ClientSession()
      return MySession(session)

async def main():
      my_session = await build_session()
      
asyncio.run(main())
```

**Comment by vgoklani** [comment]
How does that store the session instance for re-use?

```python
import asyncio
import aiohttp

class MySession:
	def __init__(self, session):
		self._session = session

async def build_session(*args, **kwargs):
	session = aiohttp.ClientSession()
	return MySession(session)

async def main():
	my_session = await build_session()


loop = asyncio.get_event_loop()
instance = loop.run_until_complete(main())
```

Leads to

	Unclosed client session
	client_session: <aiohttp.client.ClientSession object at 0x7fe1583144d0>


I need to store the session object for easy re-use, so we can programmatically make async post/get calls

**Comment by hyzyla** [comment]
You should just close session after exiting main function. Functionality works as intended

**Comment by hyzyla** [comment]
There is a good example https://docs.aiohttp.org/en/stable/client_reference.html how to open and close session with context manager:
```python3
import aiohttp
import asyncio

async def fetch(client):
    async with client.get('http://python.org') as resp:
        assert resp.status == 200
        return await resp.text()

async def main():
    async with aiohttp.ClientSession() as client:
        # 10 concurent requests with one client session
        await asyncio.gather(*[fetch(client) for _ in range(10)])

asyncio.run(main())
```

**Comment by vgoklani** [comment]
Hi @Hyzyla thanks for the response!

The example you cited works for the one use case, but doesn't allow us to store the session for subsequent queries after the first chunk has been processed.

btw, this was possible in the previous version of aiohttp, where we were able to store the session object and manually clear it. 

There is a lot of overhead in creating the session object, which affects low latency applications.

**Comment by WolframAlph** [comment]
Hi @vgoklani hope this one helps you. 

```python
import asyncio
import aiohttp


class MySession:
    def __init__(self):
        self._session = None

    async def _get_session(self, *args, **kwargs):
        self._session = aiohttp.ClientSession(*args, **kwargs)

    async def __call__(self, *args, **kwargs):
        # set ClientSession object for subsequent queries
        await self._get_session(*args, **kwargs)

        # access self._session here to do your stuff

        # close session when all work is done
        await self._session.close()


session = MySession()
loop = asyncio.get_event_loop()

# pass any parameters ClientSession expects to session object when calling in loop.run_until_complete
instance = loop.run_until_complete(session(raise_for_status=True))
```
In fact you can use any method where you set `ClientSession` object. I used `__call__` just for my own convenience. Just remember that you have to instantiate `ClientSession` in `async` method and respectively `await` it when calling to set `ClientSession` object. In fact you dont event need `_get_session` method you can instantiate directly in the `__call__` method.

**Comment by WolframAlph** [comment]
@webknjaz I guess this one can be closed?

**Comment by asvetlov** [comment]
I think so

**Comment by rz-vishalkumar** [comment]
> Hi @hyzyla thanks for the response!
> 
> The example you cited works for the one use case, but doesn't allow us to store the session for subsequent queries after the first chunk has been processed.
> 
> btw, this was possible in the previous version of aiohttp, where we were able to store the session object and manually clear it.
> 
> There is a lot of overhead in creating the session object, which affects low latency applications.

hii I am facing the same situation here, did you find your answer?

**Comment by Olindholm** [comment]
I ran into this issue a little while ago. I tried storing the `aiohttp.ClientSession` in the __init__ function, but whenever I tried to use it, I got `RuntimeError: Timeout context manager should be used inside a task`.

This is OK, but the trick is to do it right. The `aiohttp.ClientSession` must be initialized inside a task, meaning an async function. The __init__ function is not async, however it is still OK, as long as any parent function is async. Let me clarify with some code snippets.

```
import aiohttp
import asyncio


class MyClass:
    def __init__(self) -> None:
        self._session = aiohttp.ClientSession()

    async def make_http_get_request(self, url: str) -> str:
        async with self._session.request("GET", url) as response:
            response.raise_for_status()
            return await response.text()


def main() -> None:
    my_class = MyClass()
    html = asyncio.run(my_class.make_http_get_request("http://github.com/"))
    print(html)


if __name__ == "__main__":
    main()
```

This code will result in a `RuntimeError: Timeout context manager should be used inside a task` because the `MyClass`, and it's `aiohttp.ClientSession` is initialized outside of a task. The correct way would be:
```
import aiohttp
import asyncio


class MyClass:
    def __init__(self) -> None:
        self._session = aiohttp.ClientSession()

    async def make_http_get_request(self, url: str) -> str:
        async with self._session.request("GET", url) as response:
            response.raise_for_status()
            return await response.text()


async def main() -> None:
    my_class = MyClass()  # This is now being initilized inside a task (async function)
    html = await my_class.make_http_get_request("http://github.com/")
    print(html)


if __name__ == "__main__":
    asyncio.run(main())
```

Of course, you will still get some warnings like `Unclosed client session` and `Unclosed connector` with code like this, because you are not closing your resources properly. Let's write better code to take care of that:
```
import aiohttp
import asyncio


class MyClass:
    def __init__(self) -> None:
        self._session = aiohttp.ClientSession()

    async def close(self) -> None:
        await self._session.close()

    async def make_http_get_request(self, url: str) -> str:
        async with self._session.request("GET", url) as response:
            response.raise_for_status()
            return await response.text()


async def main() -> None:
    my_class = MyClass()
    html = await my_class.make_http_get_request("http://github.com/")
    print(html)

    await my_class.close()


if __name__ == "__main__":
    asyncio.run(main())
```

However, this would still leave us with these pesky warnings if we for some reason crash, due to some unforeseen exception. We can make this better yet, using context managers:
```
import aiohttp
import asyncio
from traceback import TracebackException
from types import TracebackType


class MyClass:
    def __init__(self) -> None:
        self._session = aiohttp.ClientSession()

    async def __aenter__(self) -> "MyClass":
        return self

    async def __aexit__(
        self,
        exc_type: Exception,
        exc_val: TracebackException,
        traceback: TracebackType,
    ) -> None:
        await self.close()

    async def close(self) -> None:
        await self._session.close()

    async def make_http_get_request(self, url: str) -> str:
        async with self._session.request("GET", url) as response:
            response.raise_for_status()
            return await response.text()


async def main() -> None:
    async with MyClass() as my_class:
        html = await my_class.make_http_get_request("http://github.com/")
        print(html)


if __name__ == "__main__":
    asyncio.run(main())
```

I hope this clears things up, because I've seen many threads, questions and articles on this when I googled around yesterday. All with lacking a proper explaination/answer. Sorry for the long post. :)

**Comment by Dreamsorcerer** [comment]
At the point of your last example, you might want to consider just making the context manager a requirement and thus ensure that it is always initialised in an async function:
```
class MyClass:
    async def __aenter__(self):
        self._session = await ClientSession().__aenter__()
        return self

    async def __aexit__(self, exc_type, exc_val, traceback):
        await self._session.__aexit__(exc_type, exc_val, traceback)
```

**Comment by Olindholm** [comment]
While it may be tempting to some, I don't like this approach. Context managers are great, but not applicable everywhere. Forcing it's use would limit your class usability. Not a trade-off I would do personally. It'd be better to keep both options available.

**Comment by lucasgadams** [comment]
This is fairly weird behavior for asyncio code. There shouldn't be any requirement that objects be initialized inside of async tasks, or if there is, that should be properly enforced in code with an async `ainit` type of method. And ideally it isn't a requirement at all, as it makes things like global sessions tricky.

**Comment by Dreamsorcerer** [comment]
> This is fairly weird behavior for asyncio code.

Actually, it's something that's probably exclusive to asyncio code:
```
>>> e = asyncio.Event()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/asyncio/locks.py", line 260, in __init__
    self._loop = events.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

**Comment by Lxstr** [comment]
Hi I was wondering how this would look in a situation where say a user is hitting a button to run the requests and it could be completely variable in terms of demand. I may have misunderstood @Olindholm example but I can't see how the session is stored for example in the flask context in a way an endpoint could access it any time it is hit.

**Comment by Dreamsorcerer** [comment]
As Flask is not an asyncio-native framework, I've never tried mixing async code into it, so I'm afraid I can't give any help there. That would be a question for Flask, as we don't do anything particularly unusual here.

**Comment by Dreamsorcerer** [comment]
For comparison, if it help at all, in aiohttp we'd just do:
```
async def client_session(app: web.Application):
    async with ClientSession() as sess:
        app[sess] = sess
        yield

app.cleanup_ctx.append(client_session)
```
And then we can just use the sess object in any handlers.

**Comment by Lxstr** [comment]
Thank you I will give that a try!

**Comment by rjanovski** [comment]
gke audit log bucket creation

**Comment by eboraks** [comment]
I solve this problem by creating an async method getClient within the class. Here is an example

`
class Client:

    def __init__(self) -> None:
        self._client_session = None

    async def getClientSession(self) -> aiohttp.ClientSession:
        
        if self._client_session is None:
            self._client_session = aiohttp.ClientSession()
        return self._client_session
     
      async def api_call(self, payload) -> dict:
        API_URL = self._api_url
        async with self.getClientSession.post(API_URL, json=payload) as res:
            status = res.status
            ....
`

My general comment is that making async HTTP calls in Python shouldn't be so complicated.

**Comment by Dreamsorcerer** [comment]
> My general comment is that making async HTTP calls in Python shouldn't be so complicated.

I'm not sure what you're considering to be so complicated given my previous example of how to do this in an async web framework: https://github.com/aio-libs/aiohttp/issues/4932#issuecomment-1885866867

**Comment by Dreamsorcerer** [comment]
> This could typically prevent the unclosed message.

You code doesn't make any attempt to close the session. That looks no different from just using a global variable. Again, if you're working in a web framework or similar, then use something like aiohttp's cleanup_ctx to start/stop the client (https://github.com/aio-libs/aiohttp/issues/4932#issuecomment-1885866867). If you're not using a framework, then figure out another way to use `async with` or similar.
