### ISSUE TITLE
Docs: Comparison vs httpx

### ISSUE THREAD

**Issue by clbarnes** [aio-libs/aiohttp#4933]
There are two major asyncio-based HTTP clients for python. Anyone wanting an asyncio-based HTTP client in python (i.e. a superset of httpx's users) therefore needs to pick between them. However, the documentation for neither refers to the other.

A look at the docs suggests their APIs are superficially similar, other than aiohttp providing additionally providing a server.

In what use case should aiohttp be preferred? What kind of user should be redirected to httpx? Why are they not the same project? Given answers to these questions are valuable to all python HTTP client users (rather than just aiohttp users), it would be very helpful to make the distinctions clear.

[Mirror issue on the httpx repo](https://github.com/encode/httpx/issues/1216). I cross-post them not to start any sort of tit-for-tat, but because it benefits the python HTTP and asyncio communities to have accurate and unbiased information available for our options.

**Comment by ghost** [comment]
> other than aiohttp providing additionally providing a server.

HTTPX does not provide websockets either last I checked. I believe there is an issue for it to consider implementing it (I haven't checked in a while so I might be totally wrong here).

**Comment by asvetlov** [comment]
The reason is similar to why Flask and Django co-exists?

I would say that aiohttp was started in 2013. 
In fact, the project is the oldest asyncio third-party library in the world :)

**Comment by clbarnes** [comment]
> The reason is similar to why Flask and Django co-exists?

For good reasons! Flask is a minimal, flexible web backend library with a minimal barrier to entry, on top of which you can use a variety of other libraries as you need them. Django is an opinionated, structured web backend library which enforces a particular way of doing things but is a batteries-included solution. There are dozens of pages comparing them and largely echoing this sentiment. They're in the same general sphere, but targeting different users and different use cases, and are pretty upfront about that. An understanding of that relationship between httpx and aiohttp is all I'm interested in!

Does the metaphor with flask and django extend any further?

**Comment by webknjaz** [comment]
Point is that aiohttp is the oldest framework and if anything it's httpx should have such a document explaining how they are different. There's really no point in turning the docs into a library comparison website.

**Comment by asvetlov** [comment]
Agree. Please don't get me wrong but I personally don't want to contribute into this (very opinionated, sure) comparison. Even more, the comparison should evolve on every major release of both libraries
