### ISSUE TITLE
Documentation for update_cookies is incorrect

### ISSUE THREAD

**Issue by Lonami** [aio-libs/aiohttp#4941]
The documentation for [`CookieJar.update_cookies`](https://docs.aiohttp.org/en/stable/client_reference.html?highlight=update_cookies#aiohttp.CookieJar.update_cookies) is wrong. It claims:

> **Parameters**:
> 
> * response_url ([*str*](https://docs.python.org/3/library/stdtypes.html#str)) – URL of response

However, trying to use a Python `str` fails:

```
  File "/home/user/.local/lib/python3.8/site-packages/aiohttp/cookiejar.py", line 121, in update_cookies
    hostname = response_url.raw_host
AttributeError: 'str' object has no attribute 'raw_host'
```

This can be seen in the code:

https://github.com/aio-libs/aiohttp/blob/5f0a59fd38f048ee65b6199a26d2355075d0d196/aiohttp/cookiejar.py#L116-L120

Either the code should be updated to accept strings or the documentation changed.

**Comment by Lonami** [comment]
(I'm not fully sure if this is a bug, but I don't think it's an enhancement either and there was no blank template I could find…)

**Comment by WisdomPill** [comment]
Hello @Lonami!

Nice catch!
Do you fancy proposing a PR to address the issue?

Otherwise I can step in and do it

**Comment by Lonami** [comment]
Not interested in sending a PR, you or someone else looking for Hacktoberfest PRs may do it :)

**Comment by WisdomPill** [comment]
I do not know what is hacktoberfest material, I will do it anyways
