### ISSUE TITLE
Websocket exits on bad UTF-8 message without opportunity to debug or ignore

### ISSUE THREAD

**Issue by shbatm** [aio-libs/aiohttp#4963]
🐣 **Is your feature request related to a problem? Please describe.**

The WebSocketReader class forces a strict UTF-8 decoding of the payload for `WSMsgType.TEXT` messages; however if the sender passes corrupt or malformed UTF-8, the websocket will close and throw an exception. This creates a situation where if the sender happens to only throw a single junk message, the downstream code isn't afforded the opportunity to manage it.

💡 **Describe the solution you'd like**

An option that would set the default error method of decode in [this line](https://github.com/aio-libs/aiohttp/blob/6a5ab96bd9cb404b4abfd5160fe8f34a29d941e5/aiohttp/http_websocket.py#L384); which would allow the user to select how the websocket responds to a bad message:

e.g. change:

```python
text = payload_merged.decode('utf-8') 
# Equivalent to:
text = payload_merged.decode(encoding='utf-8', errors='strict')
```

to something that would allow selecting the error method:

```python
text = payload_merged.decode(encoding='utf-8', errors='ignore')
# or
text = payload_merged.decode(encoding='utf-8', errors='replace')
```

❓ **Describe alternatives you've considered**

📋 **Additional context**

Source issue: https://github.com/automicus/PyISY/issues/124#issuecomment-695328324

**Comment by asvetlov** [comment]
Sorry, I don't think that optional `ignore` or `replace` error-mode is acceptable here.

WebSocket protocol explicitly says that the TEXT message is UTF-8 at https://tools.ietf.org/html/rfc6455#section-5.6

Non-UTF8 TEXT payload is invalid. There are no alternative encodings. Why should we care about malformed messages?

**Comment by shbatm** [comment]
> Non-UTF8 TEXT payload is invalid. There are no alternative encodings. Why should we care about malformed messages?

Agree, there is no question on the standard. The biggest issue in our use case is the code as-is causes the websocket to abort/close on a single bad message, rather than allow the user to decide what to do about it.

In our use case the bad message is coming from an event stream on a device we cannot modify. A single malformed character appearing in a message is a known bug on that device, that single message can be discarded when connecting via other methods, but the only way to respond to it right now with aiohttp is to catch the closed socket, reconnect and re-subscribe, which causes subsequent messages to be missed. 

So maybe instead of allowing setting the error handling on decoding, allow a setting for what to do with the socket on a bad message, instead of just closing?

**Comment by asvetlov** [comment]
How other websocket libraries behave with malformed messages?
What is their API?

**Comment by shbatm** [comment]
> What is their API?

I read through several other libraries and the Mozilla Docs [API](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) which is pretty unambiguous -- close the socket with a `1007` on any bad UTF-8; disappointing, but looks like I'll need to wait until the device developer corrects the bug on their end causing the bad message.

Closing this, thanks for the review.

**Comment by asvetlov** [comment]
You are welcome!
