### ISSUE TITLE
Writing data to S3 produces error

### ISSUE THREAD

**Issue by ghost** [aio-libs/aiohttp#4974]
## Long story short
I'm trying to export data to s3 using s3fs but it throws error - AttributeError: module 'asyncio' has no attribute 'current_task'

I am not able to export my data from dask dataframe to s3.

dask_df = dd.from_pandas(df, npartitions = 20)

dask_df.to_csv('s3://bucket/foldername/filename.csv')
## Expected behaviour
CSV exported to S3 table.

## Actual behaviour
```
    result[0] = await future
  File "/users/abc/aws-staging/aws/lib/python3.6/site-packages/s3fs/core.py", line 462, in _mkdir
    if not key or (create_parents and not self.exists(bucket)):
  File "/users/abc/aws-staging/aws/lib/python3.6/site-packages/fsspec/asyn.py", line 118, in wrapper
    return maybe_sync(func, self, *args, **kwargs)
  File "/users/abc/aws-staging/aws/lib/python3.6/site-packages/fsspec/asyn.py", line 90, in maybe_sync
    return _run_until_done(func(*args, **kwargs))
  File "/users/abc/aws-staging/aws/lib/python3.6/site-packages/fsspec/asyn.py", line 21, in _run_until_done
    task = asyncio.current_task()
AttributeError: module 'asyncio' has no attribute 'current_task'
```

## Steps to reproduce
`
import pandas as pd
import dask.dataframe as dd

dask_df = dd.from_pandas(df, npartitions = 20)

dask_df.to_csv('s3://bucket/foldername/filename.csv')`

## Your environment
grep aiobotocore
aiobotocore==1.1.1
grep boto3
boto3==1.9.246
grep aiobotocore
aiobotocore==1.1.1

**Comment by WisdomPill** [comment]
Hello @Shubham-Jha-GT!

The method current_task is available from python 3.7 as noted [here](https://docs.python.org/3/library/asyncio-task.html#asyncio.current_task) so I guess that the reason why you are facing this issue.

Can you explain how is this related to `aiohttp`?

Otherwise I think this issue should be closed
