### ISSUE TITLE
Query parameters remain encoded since yarl==1.6.0

### ISSUE THREAD

**Issue by deansg** [aio-libs/aiohttp#4981]
I apologize in advance if this is not a bug, or alternatively, a bug which isn't in aiohttp. I'm reporting it here since I'm not familiar with the aiohttp code and I experienced this unexpected change in behaviour by using aiohttp.

🐞 **Describe the bug**

The query parameters from a Request object now appear in their url encoded form rather than the previously decoded form. 

💡 **To Reproduce**

1. Install aiohttp with yarl version 1.6.0 (came out in September 23)
2. Write a simple http service with a controller
3. Send a request with query parameters which include characters that get encoded in urls (such as spaces)
4. Attempt to retrieve the query parameter objects and see that they are in an encoded form

💡 **Expected behavior**

The query parameters should be decoded, as before.

📋 **Your version of the Python**

```console
$ python --version
...
```
3.7.9

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
...
```
```console
$ python -m pip show multidict
...
```
```console
$ python -m pip show yarl
...
```
yarl==1.6.0
aiohttp==3.6.2
multidict==4.7.4

**Comment by TBBle** [comment]
Duplicate of #4972.

**Comment by deansg** [comment]
> Duplicate of #4972.

I've somehow missed the other one, sorry.
