### ISSUE TITLE
Url GET parameters are lost when redirecting

### ISSUE THREAD

**Issue by squaredbeaver** [aio-libs/aiohttp#499]
What's the purpose of trimming get parameters [here](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L188)?

**Comment by asvetlov** [comment]
I believe the intention was removing just fragment part (`#achor`).
But it's also questionable.
I'm fine with leaving location untouched.

@fafhrd91 looks like it's your code. Do you remember details?

**Comment by asvetlov** [comment]
@fafhrd91 ping.
Could we just drop lines https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L188-L191 ?

**Comment by fafhrd91** [comment]
Sure, I actually do not remember reason for this code

**Comment by asvetlov** [comment]
Done!
