### ISSUE TITLE
rtd integration

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#5]
@kxepal do you have access to rtd where we post aiohttp docs?

**Comment by kxepal** [comment]
Yes, I do.

**Comment by fafhrd91** [comment]
Somehow I don't have access anymore, could you point docs to new repo.

Get Outlook for iOS




On Sat, Mar 11, 2017 at 10:06 AM -0800, "Alexander Shorin" <notifications@github.com> wrote:












Yes, I do.

**Comment by kxepal** [comment]
Hm...I saw you in members there. But anyway, already done.

**Comment by kxepal** [comment]
Check this up: http://aiohttp.readthedocs.io/en/latest/

**Comment by fafhrd91** [comment]
thanks
