### ISSUE TITLE
v3.6.3: aiohttp.http_exceptions.BadStatusLine: invalid HTTP method

### ISSUE THREAD

**Issue by bashalex** [aio-libs/aiohttp#5011]
🐞 **Describe the bug**
After the update to 3.6.3, this error gets constantly raised when a python app with the `aiohttp` dependency is deployed to a Kubernetes cluster. No such exception was noticed with 3.6.2 and the same environment.

I believe it has something to do with telemetry that Kubernetes tries to collect. From the log itself it's pretty much impossible to determine what exact requests cause this behavior.

📋 **Logs/tracebacks**
```
13.10.2020[15:41:48] [6    ] aiohttp.server           ERROR Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```

📋 **Your version of the Python**
3.8.6

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
3.6.3
```
```console
$ python -m pip show multidict
4.7.6
```
```console
$ python -m pip show yarl
1.5.1
```

📋 **Additional context**
P.S. Is there any available changelog between v3.6.3 and v3.6.2?

**Comment by asvetlov** [comment]
The only difference between 3.6.2 and 3.6.3 is the yarl library version pinning: https://github.com/aio-libs/aiohttp/compare/v3.6.2...v3.6.3
I don't see how it affects BadStatusLine problem.
I personally don't see any issues after upgrading our codebase to 3.6.3
