### ISSUE TITLE
Refactor client api for sending requests

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#502]
Current process is:
1. `ClientSession` creates request class
2. Acquires connection from connector
3. Sends request's headers via complicated procedure:
   
   3.1. `ClientRequest` sends headers
   
   3.2. It creates a task for sending request's BODY
   
   3.3.  After that request creates `ClientResponse` instance and returns it
   
   3.4. `ClientSession` starts response by `resp.start()` call. 
4. Outer code gets response object with preloaded headers and it's ready to process RESOPONSE BODY.

That looks overcomplicated. I believe `ClientSession` should send request and so on. Request should know nothing about Response.

Pros:
1. It makes the process for sending request and getting back response much more clear for my brain at least.
2. Later we can add _HTTP request pipelining_ for sending multiple requests without immediate waiting response for the same connection as browsers do. Historically `Connector` and `Connection` are second-class citizens but after introducing `ClientSession` we can bring up `ClientConnection`, e.g.

```
    async with session.connect(address) as conn:
        ask1 = conn.get('/data1')
        ask2 = conn.post('/data2', data=b'data')
        resp1 = yield from ask1
        data1 = yield from resp1.read()
        resp2 = yield from ask2
        data2 = yield from resp2.read()
```

Honestly I don't sure pipelining is so important, looks like python libraries just don't care.
But if we can support it -- why not?

Cons:
1. We will break current API. That part is not documented properly and I suspect nobody rely on. I believe we will not break any existing code but I should mention the breakage.
2. Requires significant changes in our code base but I'm volunteer for the task. 

@kxepal @fafhrd91 @popravich I need your opinion.

P.S. I want make a change to suppress warnings for unclosed response when session was closed properly. Looks like it requires significant changes for test suite anyway, that's why I'm asking right now. 
Another option is just adding yet another flag to `ClientResponse` or using weakrefs but I see the proper way.

**Comment by kxepal** [comment]
> Honestly I don't sure pipelining is so important, looks like python libraries just don't care.

They don't care by simple reason: this requires a lot of work and specific API while most part of users will not use that feature. These users mostly follow the logic:
1. Do request and fetch response
2. Do the math and decide what next to do
3. Repeat

Pipelining gives advantage when you need to make a lot of requests without any logic in-between. Web crawlers and browsers are the profit gainers here. For rare HTTP API you would need the same feature, unless that API doesn't provides any way to bulk get things.

Also, POST requests [should not](http://tools.ietf.org/html/rfc2616#section-8.1.2.2) be pipelined:

> Clients SHOULD NOT pipeline requests using non-idempotent methods or non-idempotent sequences of methods (see section 9.1.2). Otherwise, a premature termination of the transport connection could lead to indeterminate results. A client wishing to send a non-idempotent request SHOULD wait to send that request until it has received the response status for the previous request. 

As for idea in general, I need to think about. Looks good, but feel that there could be monsters. For instance, if we take any API client library, it will try to hide underlying low level protocol routines under high level interface. So end user wouldn't have to do `conn.get('/books')`, he will do `books.get()` where deep inside connection is creates against constructed url, request being made, response read and result returned in some special form. 

What the profit for these top-level wrappers around aiohttp and how they can benefit from pipelining feature without making low level details leak is a kind of good question.

**Comment by popravich** [comment]
I need to think it over.

**Comment by fafhrd91** [comment]
let's reopen if anyone will have ideas and plan for implementation
