### ISSUE TITLE
Support multidict 5

### ISSUE THREAD

**Issue by RhinosF1** [aio-libs/aiohttp#5075]
🐣 **Is your feature request related to a problem? Please describe.**

We want to keep what we install up to date but our checks show aiohttp blocks multidict 5 (See travis on https://github.com/MirahezeBots/bots-pip-auto/pull/113)

💡 **Describe the solution you'd like**

Allow multidict 5 with aiohttp
❓ **Describe alternatives you've considered**

N/A

📋 **Additional context**

**Comment by asvetlov** [comment]
Thanks for raising the question; I just forgot to relax the dependency.
Please let me propose an alternative PR which raises the top cap; it should be backward-compatible without any issue.

**Comment by RhinosF1** [comment]
@asvetlov: Multidict 5+ doesn't support python 3.5 which I think you do. That's why I chose what I did.

**Comment by RhinosF1** [comment]
Could we get a version on PyPi with this on @asvetlov so I can fix our install list?

**Comment by asvetlov** [comment]
The next aiohttp will not support Python 3.5 as well (`python_requires='>=3.6'`)
