### ISSUE TITLE
warning socket.send() raised exception

### ISSUE THREAD

**Issue by nadiasvertex** [aio-libs/aiohttp#508]
When a user terminates a connection early inside of an aiohttp handler, there is no notification that that has happened. For example, the following code:

'''
with open(to_download, "rb") as i:
        chunk_size = 1 << 16
        start = time.time()

```
    while True:
        data = i.read(chunk_size)
        if not data:
            break

        try:
            r.write(data)
        except:
            log.exception("Failed to send data.")
            break

        yield from r.drain()'''
```

The exception handler never gets called if I abort the connection part way through. Instead, I get hundreds of log messages about the socket.send() raising an exception. What should happen instead is that the exception is propagated up to me in the r.write ( or the r.drain()) so that I can handle it properly. Which in this case means aborting the loop.

**Comment by jashandeep-sohi** [comment]
First, I think you should do a `try..execpt` around the `r.drain()`.

But, this sounds like the following: http://stackoverflow.com/questions/32175217/how-to-detect-write-failure-in-asyncio

You could try an empty `yield` before `r.drain()` and see if that fixes it.
