### ISSUE TITLE
Restructure web & client files into separate packages

### ISSUE THREAD

**Issue by jashandeep-sohi** [aio-libs/aiohttp#509]
This is more of cosmetic issue/question rather than a functional one, but what do you think about restructuring web & client files into separate packages?
i.e. `aiohttp/client/__init__.py` & `aiohttp/web/__init__.py`

**Comment by asvetlov** [comment]
Why?
Your _cosmetic_ change breaks backward compatibility BTW

**Comment by jashandeep-sohi** [comment]
> Why?

For the same reason why all the code isn't in a single file: better organization & separation.
Most of the `aiohttp.web` files already have a `web_` prefix, but this would just be a more Pythonic way of splitting it.

> Your cosmetic change breaks backward compatibility BTW

True, but only for the people explicitly importing the modules i.e. `import aiohttp.websocket_client`. All the other API should work fine by exporting the proper symbols in `aiohttp/__init__.py`.

**Comment by asvetlov** [comment]
Well, if you import all public names from `__init__.py` only why do you care?
Anyway, the ship has sailed.

**Comment by jashandeep-sohi** [comment]
Fair enough.
