### ISSUE TITLE
implement response.ok like requests.get().ok

### ISSUE THREAD

**Issue by erny** [aio-libs/aiohttp#5099]
🐣 **Is your feature request related to a problem? Please describe.**
Implement requests lib response.ok  for compatibility reasons

💡 **Describe the solution you'd like**
response.ok == (200 >= requests.status > 400)  # as per requests.ok description

@property
def ok(self):
    return 200 >= self.status > 400

❓ **Describe alternatives you've considered**
Comparing result with status codes

📋 **Additional context**

**Comment by asvetlov** [comment]
If you want to provide a pull request -- please go ahead

**Comment by Fogapod** [comment]
`ok` body: https://github.com/psf/requests/blob/143150233162d609330941ec2aacde5ed4caa510/requests/models.py#L696-L708

Status checks: https://github.com/psf/requests/blob/143150233162d609330941ec2aacde5ed4caa510/requests/models.py#L936-L943

So it should be this if compatibility is needed?  `return not (400 <= self.status < 600)`

**Comment by Fogapod** [comment]
Actually, this was implemented already? https://github.com/aio-libs/aiohttp/pull/4711

**Comment by asvetlov** [comment]
Ooh, yes.
I've forgotten about it.
Please wait for the next release.

**Comment by erny** [comment]
Thanks a lot. Sorry, I didn't see it. Regards
