### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by leszekhanusz** [aio-libs/aiohttp#5107]
🐞 **Describe the bug**

After updating aiohttp from 3.6.2 to 3.7.0, the [gql](https://github.com/graphql-python/gql) tests are failing on python 3.8 with the Exception `ModuleNotFoundError: No module named 'typing_extensions'`

```
tests/conftest.py:15: in <module>
    from aiohttp.test_utils import TestServer as AIOHTTPTestServer
.tox/py38/lib/python3.8/site-packages/aiohttp/test_utils.py:43: in <module>
    from .web import (
.tox/py38/lib/python3.8/site-packages/aiohttp/web.py:23: in <module>
    from .web_app import Application as Application
.tox/py38/lib/python3.8/site-packages/aiohttp/web_app.py:39: in <module>
    from .web_middlewares import _fix_request_current_app
.tox/py38/lib/python3.8/site-packages/aiohttp/web_middlewares.py:7: in <module>
    from .web_urldispatcher import SystemRoute
.tox/py38/lib/python3.8/site-packages/aiohttp/web_urldispatcher.py:36: in <module>
    from typing_extensions import TypedDict
E   ModuleNotFoundError: No module named 'typing_extensions'

```

💡 **To Reproduce**

Check the PR [#156](https://github.com/graphql-python/gql/pull/156)

**Comment by leszekhanusz** [comment]
Probably related to the aiohttp PR #5078 (6 days ago)

**Comment by asvetlov** [comment]
Thanks for the report!

**Comment by asvetlov** [comment]
Fixed by #5123

**Comment by xpkcs** [comment]
Hi, I'm still running into a similar issue with aiohttp v3.7.3.

I have a Docker image using Python 3.8 in which pipenv installs from a Pipfile.lock. In my Pipfile, I require python=3.8, but when I build the Pipfile.lock, the dependency typing-extensions has the marker:
```
"markers": "python_version < '3.8'",
"version": "==3.7.4.3"
```

Because of this, my pytests failed to find typing-extensions with the same error as the title of this issue.

I was able to get around this issue by explicitly requiring typing-extensions in my Pipfile, instead of implicitly installing it as a dependency of aiohttp, but it seems hacky.

**Comment by telemmaite** [comment]
Same issue as above with `aiohttp==3.7.3`
```
  File ".pyenv/versions/ENV-3.8.6/lib/python3.8/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File ".pyenv/versions/ENV-3.8.6/lib/python3.8/site-packages/aiohttp/helpers.py", line 48, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'

```

**Comment by nomad-software** [comment]
I had the same issue, see: https://github.com/psf/black/issues/1928#issuecomment-763523321

**Comment by webknjaz** [comment]
> Same issue as above with `aiohttp==3.7.3`

It can't be the same: https://github.com/aio-libs/aiohttp/commit/e7dc8448a556db7a23a97d7dc5964f002b96ab99 + https://github.com/python/typing/commit/c6c7dfdd4b999a2bbd46d120adeacc504d74e044.
