### ISSUE TITLE
aiohttp_cors - CORS support

### ISSUE THREAD

**Issue by rutsky** [aio-libs/aiohttp#516]
What is the status of CORS middleware support?

@GMLudo, you showed interest in implementing aiohttp_cors [here](https://github.com/KeepSafe/aiohttp/issues/238) and [here](https://github.com/KeepSafe/aiohttp/issues/249), any progress?

@mwfrojdman, you [have submitted](https://github.com/KeepSafe/aiohttp/issues/506) issue about implementing CORS middleware. Will you plan to release your code to Open Source?

@asvetlov, is mentioned in #506 bug #401 is total showstopper for implementing aiohttp_cors?

**Comment by mwfrojdman** [comment]
I did write some code, but I'm using it strictly as non-middleware because middlewares can't manipulate stream responses and the whole reason I'm using aiohttp is because I need asynchronous handlers for streaming. Unless I'm missing something crucial, the current middleware API just doesn't allow to tweak the responses, unless they're not started (which wont happen when streaming).

**Comment by asvetlov** [comment]
Signals will be published in next release. They will allow stream response
headers manipulation.

**Comment by hairychris** [comment]
Is there a roadmap / rough ETA for the next release?

**Comment by ludovic-gasc** [comment]
We've made a very small quick'n'dirty middleware to handle that. 
We didn't open-sourced because we're waiting an "official" solution from aiohttp community.

**Comment by asvetlov** [comment]
@hairychris I'd like to publish next aiohttp 0.18 release roughly in two or three weeks.
It will not contain CORS itself but will allow to process CORS correctly for streaming responses as well as for regular ones.
For now I have no time for working on CORS unfortunately.

But if somebody will create a library I'd like to move the lib under aio-libs umbrella and share maintenance  burden.

**Comment by alexdutton** [comment]
I've got CORS code at https://github.com/ox-it/apiox-core/blob/master/apiox/core/middleware/cors.py, which works as a signal handler with the patch proposed in #401. Ignore the `WWW-Authenticate` nonsense; that should probably live elsewhere.

Happy to contribute this elsewhere when it'll work with a aiohttp release.

**Comment by ludovic-gasc** [comment]
@alexsdutton thanks for the link.
In fact, from my point of view, now I understand better the implications with CORS, the technical logic behind CORS is enough simple (only add more headers in HTTP Response) that a generic business logic via a middleware or a router for every need should be more complicated to use than understand/handle CORS itself.

**Comment by alexdutton** [comment]
@GMLudo Also worth remembering that each route needs to support OPTIONS requests, and to not do auth on those.

**Comment by ludovic-gasc** [comment]
For OPTIONS requests, we add a special route for that:

```
    self.servers['http'].router.add_route('OPTIONS',
                                          '{foo:.*}',
                                          endpoints.http.options)
```

Maybe we should provide an example to handle CORS in examples/ folder of aiohttp ?

**Comment by alexdutton** [comment]
@GMLudo does that then look through the router for other routes that match the path?

FWIW, Our implementation uses class-based views with all routes declared with a '*' method (https://github.com/ox-it/apiox-core/blob/master/apiox/core/handlers/base.py#L64-L79)

**Comment by ludovic-gasc** [comment]
@alexsdutton no, only adds the same CORS headers for all requests.

**Comment by rutsky** [comment]
I'm working on `aiohttp_cors` implementation.
Here is PR with WIP of an initial implementation:
https://github.com/aio-libs/aiohttp_cors/pull/1

It uses @alexsdutton's [Signals](https://github.com/KeepSafe/aiohttp/issues/401) implementation, and I plan to release it in parallel with the next release of `aiohttp`, when Signals will be merged.

Current version has complete CORS implementation, but tests and documentation are not finished yet (so there are probably bugs).
Comments and review are very welcome.
Basic API examples  can be found in the Usage section of [README.rst](https://github.com/rutsky/aiohttp_cors/blob/initial_implementation/README.rst).

**Comment by rutsky** [comment]
I released initial version of aiohttp_cors tonight: https://github.com/aio-libs/aiohttp_cors.

Please take a look and report if you find any issues or suggestions about it.

I believe this issue can be closed now.

**Comment by asvetlov** [comment]
Thanks!
