### ISSUE TITLE
Missing close status codes for websockets

### ISSUE THREAD

**Issue by achimnol** [aio-libs/aiohttp#5192]
🐞 **Describe the bug**

ref: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent
current: https://github.com/aio-libs/aiohttp/blob/707736b/aiohttp/http_websocket.py#L31-L42

The close code 1014, 1015 is missing, and one of my use case (websocket proxy) involves 1014,
which results in an unexpected error "Invalid close code: 1014".

I think we need to update the list.

**Comment by derlih** [comment]
@achimnol do you mean that the values are missing in the `WSCloseCode` enum?

**Comment by asvetlov** [comment]
There is an interesting question: how to prevent such problem in future, when a new code will be added again?

**Comment by derlih** [comment]
It could be a GitHub  action that periodically fetchs the https://github.com/mdn/content/blob/main/files/en-us/web/api/closeevent/index.html , parses it and compares to the enum in master branch. In case of mismatch creates an issue with a tag.

**Comment by derlih** [comment]
@achimnol I think 1015 shouldn't be set in aiohttp. The connection error should be raised in this case IMHO.
From MDN:
> Indicates that the connection was closed due to a failure to perform a TLS handshake (e.g., the server certificate can't be verified).

**Comment by achimnol** [comment]
Even [the original RFC](https://tools.ietf.org/html/rfc6455#section-7.4.1) and its follow-up docs does not specify all of the close codes listed in the MDN document.
Since [the status codes are largely left as "extensible"](https://tools.ietf.org/html/rfc6455#section-7.4.2), I think we should allow arbitrary unknown close codes in the range of 1000 to 4999 as *valid* with an *optional* conversion to pre-defined constant enums.

I agree with that 1015 might not be necessary for the application layer, i.e., aiohttp., but if we decide to accept any status code in the range of 1000 to 4999, this wouldn't be important anyway.

**Comment by derlih** [comment]
I think we are talking not only the enum values, but also about the handing the "unexpected" close codes.
https://github.com/aio-libs/aiohttp/blob/2a9d5e9ecacbddad0fba48480aa5417ee9c8f8d6/aiohttp/http_websocket.py#L282-L293

IMO the question is: should we change this behavior and how?
For example we could just use the value from `close_code = UNPACK_CLOSE_CODE(payload[:2])[0]` without additional checks and keep the enum to improve clearness of the code like `http.HTTPStatus` does.
But on the other hand it changes the behavior of the code.

May be it would be better to raise an excpetion if the code is not OK (1000).
