### ISSUE TITLE
[Vote] Commit rights for Dmitry Erlikh

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#5213]
I want to propose adding @derlih to the aiohttp Core team.
His 7 Pull Requests are merged (and backported), two are in the review stage.
During in-person emailing, Dmitry expressed a willingness to participate more in aiohttp development.
Commit rights is a little appreciation for this contribution and invitation to more work.

@aio-libs/aiohttp-committers please vote here in the comments.
The vote is ended in a week, on Tuesday of November 17.

**Comment by samuelcolvin** [comment]
👍 sounds good to me.

Thanks @derlih and welcome.

**Comment by webknjaz** [comment]
+0

**Comment by socketpair** [comment]
+1

**Comment by mjpieters** [comment]
+0

**Comment by asvetlov** [comment]
The vote is closed.

Welcome, @derlih to our team!
The invitation is sent.
Please feel free to ask for any help if needed.

**Comment by derlih** [comment]
Thanks!
