### ISSUE TITLE
[docs] is web socket read really required to happen from the request handler task?

### ISSUE THREAD

**Issue by danking** [aio-libs/aiohttp#5214]
(I asked [this question on the discourse forum](https://aio-libs.discourse.group/t/why-can-a-web-socket-only-be-read-from-the-request-handler-task/154) and received no response for 11 days, so I'm escalating it to a docs bug)

🐞 **Describe the bug**

The docs [currently state](https://docs.aiohttp.org/en/stable/web_advanced.html#reading-from-the-same-task-in-websockets):

> Reading from the WebSocket ( await ws.receive() ) must only be done inside the request handler task

That verbiage was introduced in this PR: https://github.com/aio-libs/aiohttp/pull/647. Before that PR the verbiage was:

> You must use the only websocket task for both reading (e.g await ws.receive()) and writing but may have multiple writer tasks which can only send data asynchronously (by ws.send_str('data') for example).

Can someone confirm or deny if I am allowed to call receive from a task other than the request handling task? Only one task will call receive in this setting.

Specifically, I want to write the following code. Is this code invalid because the receive occurs inside a task *other than the request handling task*?

```python3
class WebSocketKeepAliveContextManager:
    def __init__(self, ws):
        self.ws = ws
        self.task = None

    async def __aenter__(self):
        self.task = asyncio.create_task(self.ws.receive())

    async def __aexit__(self, exc_type, exc, tb):
        if self.task.done():
            message = self.task.result()
            raise ValueError(f'unexpected message during keepalive: {message}')
        else:
            self.task.cancel()

def keep_ws_alive(ws):
    return WebSocketKeepAliveContextManager(ws)

def some_request_handler(request):
    # ... create a web socket ...
    async with keep_ws_alive(ws):
        await long_running_activity()
```

💡 **To Reproduce**
N/A

💡 **Expected behavior**

I expect the docs to state that no more than one coroutine may await `receive` at any given time. The identity of the coroutine that awaits receive is irrelevant.

📋 **Logs/tracebacks**

N/A
📋 **Your version of the Python**
N/A
📋 **Your version of the aiohttp/yarl/multidict distributions**
I looked at the docs website on 2020-11-10.

📋 **Additional context**
N/A

**Comment by asvetlov** [comment]
Answered on the Doscourse
