### ISSUE TITLE
Access log %(D)s has tens-of-microseconds precision

### ISSUE THREAD

**Issue by sterwill** [aio-libs/aiohttp#524]
I couldn't find any documentation that says what precision aiohttp server will give me, but the gunicorn docs (which the aiohttp server's interpolation dict seems to follow) say %(D)s will contain the request duration's microseconds part.  aiohttp is logging to tens-of-microseconds precision because of a too-short string slice:

https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/helpers.py#L257

If we want microseconds, we need 6 digits after the decimal point, and since a slice's end index is exclusive, so we need [:6] instead of [:5].

**Comment by asvetlov** [comment]
I have no objections.
Would you make a Pull Request?
Not tests required if your patch doesn't break current aiohttp test suite.
Otherwise just fix existing tests.

**Comment by asvetlov** [comment]
Fixed by #527
