### ISSUE TITLE
Enable PR builds on Read The Docs

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiohttp#5253]

**Comment by asvetlov** [comment]
Love to have it done!

**Comment by webknjaz** [comment]
@asvetlov it's on you because I don't have access to RTD. And you can only tick the checkbox via UI, not a config file.

**Comment by asvetlov** [comment]
You are added to aiohttp maintainers now :)
Thanks for the reminder, I thought I got permissions on RTD ages ago.

**Comment by webknjaz** [comment]
I only had access to multidict, not aiohttp and not yarl. I've enabled this for multidict a long time ago.

**Comment by webknjaz** [comment]
Enabled. FYI the toggle is here: https://readthedocs.org/dashboard/aiohttp/advanced/.

**Comment by asvetlov** [comment]
Thanks, good to know
