### ISSUE TITLE
Pre-commit workflows runs on forks

### ISSUE THREAD

**Issue by WisdomPill** [aio-libs/aiohttp#5258]
🐞 **Describe the bug**

The pre-commit auto-update workflow runs on forks too, to me it seems unnecessary also because I get an email about a failed job every night, since I do not have secrets set for the bot. In my opinion this workflow should run only on the main repository.

💡 **To Reproduce**

Just clone the repo and wait for the schedule of []() to kick in

💡 **Expected behavior**

The auto-update should not run on forks, it should work only on the main repository.

📋 **Logs/tracebacks**

Just have a look at my fork, (here)[https://github.com/WisdomPill/aiohttp/actions]

💡 **Proposed solutions**

1. Everybody can disable actions on their fork, but it does not seem a viable solution because people will encounter the problem often.

2. Although github actions does not support to add conditionals on the event, it supports them only in the steps, so an if on every step is what can be done. [here](https://github.com/prisma/prisma/issues/3539#issuecomment-689104691)

I would be more than happy to contribute to the repo and fix this if the second proposed solution works for you, otherwise let's discuss it and find a more elegant solution to this annoying problem.

**Comment by WisdomPill** [comment]
Maybe @webknjaz would be interested since he likes GitHub actions, bots and he is behind sanitizers/octomachinery

**Comment by webknjaz** [comment]
How about adding a conditional on the job level?

**Comment by WisdomPill** [comment]
Is it possible?

I can try and let you know

**Comment by webknjaz** [comment]
It is. But it's still a runtime check. So the job will show up as skipped.

**Comment by asvetlov** [comment]
> it's still a runtime check. So the job will show up as skipped.

I think that's fine.
Grey jobs don't hurt :)

**Comment by asvetlov** [comment]
Done
