### ISSUE TITLE
_http_parser.HttpResponseParser.__init__ got multiple values for keyword argument 'timer'

### ISSUE THREAD

**Issue by SomberNight** [aio-libs/aiohttp#5260]
[We](https://github.com/spesmilo/electrum) use aiohttp as a client to fetch json files from remote webservers.
After recently releasing a new version that included newer aiohttp than before (3.6.3->3.7.2), some users on Windows [started getting errors](https://github.com/spesmilo/electrum/issues/6748#issuecomment-730730346).

The users are running pyinstaller frozen binaries, on Windows 10, that [bundle](https://github.com/spesmilo/electrum/blob/6f105ae43bb624654fbe74a976c439f5fb75efd7/contrib/deterministic-build/requirements.txt):
```
Python 3.7.9 (win32)
aiohttp==3.7.2
multidict==4.7.6
yarl==1.5.1
```
The affected users can reliably reproduce the error using this binary, however not with the previous binary that contained aiohttp 3.6.3.

Log/traceback:
```
20201120T004731.576120Z |    ERROR | exchange_rate.CoinGecko | Exception in get_rates: TypeError("__init__() got multiple values for keyword argument 'timer'")
Traceback (most recent call last):
  File "electrum\util.py", line 1039, in wrapper
  File "electrum\exchange_rate.py", line 302, in get_rates
  File "electrum\exchange_rate.py", line 64, in get_json
  File "aiohttp\client.py", line 1124, in __aenter__
  File "aiohttp\client.py", line 544, in _request
  File "aiohttp\client_proto.py", line 160, in set_response_params
  File "aiohttp\_http_parser.pyx", line 566, in aiohttp._http_parser.HttpResponseParser.__init__
TypeError: __init__() got multiple values for keyword argument 'timer'
20201120T004731.579047Z |     INFO | exchange_rate.CoinGecko | failed fx quotes: TypeError("__init__() got multiple values for keyword argument 'timer'")
20201120T004731.579047Z |    ERROR | asyncio | Unclosed connection
client_connection: Connection<ConnectionKey(host='api.coingecko.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=892630978)>
```
Some mentioned and related lines:
https://github.com/spesmilo/electrum/blob/6f105ae43bb624654fbe74a976c439f5fb75efd7/electrum/exchange_rate.py#L63-L64
https://github.com/spesmilo/electrum/blob/6f105ae43bb624654fbe74a976c439f5fb75efd7/electrum/util.py#L1098

(note that code above supports using a socks proxy via [aiohttp-socks](https://github.com/romis2012/aiohttp-socks) but the reporting users are not using one)

Unfortunately I cannot reproduce the error using the same binary on Windows 10, or indeed when running from source on Windows, or on Linux.

I have been trying to identify the cause, e.g. looking at exactly how the 'timer' arg is being passed around, but could not find the issue so far.
Also a bit confused why I cannot reproduce using the same frozen binary...
Any help would be appreciated!

**Comment by webknjaz** [comment]
This sort of issue usually happens when both kwargs and args are used. For example:
```python
def func(a, b, c=3, d=4):
    pass

kwargs = {'c': 3, 'd': 4}
func(1, 2, 3, **kwargs)
```
but I have no clue how this would come to be in aiohttp. Is it possible that you monkeypatch the source code? That would explain it. Also, have you inspected the packages that end up being used? You could compare them to the actual source and check if there's any files that shouldn't be in the package.
If nothing works, maybe check out Cython tracker to see if this could be their bug.

**Comment by asvetlov** [comment]
The problem can happen when old binaries for aiohttp C Extension is used with newer aiohttp Python code.

This should not happen if everything is installed correctly. 
I'm not surprised why @SomberNight cannot reproduce the bug -- perhaps you do everything the right way but your users do not. I suggest removing all files and reinstall the bundle from scratch.

**Comment by SomberNight** [comment]
> The problem can happen when old binaries for aiohttp C Extension is used with newer aiohttp Python code.

Ah indeed that is the cause! Thanks for the comment, it helped me to figure out the exact scenario.
We distribute multiple binaries (even for windows) and I did not realise it only affects the NSIS installer (which unpacks files into %programfiles% - as opposed to e.g. portable single-file).

see detailed cause at https://github.com/spesmilo/electrum/issues/6748#issuecomment-731163468
