### ISSUE TITLE
Add final declarations to the library constants.

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#5275]
The library has many constant definitions that are declared as `NAME = 'val'`, e.g. https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L161

We need to add `Final` type hint to let users know that these constants should be considered as immutable (this hint doesn't prevent the actual modification and fully backward compatible).

```
from typing_extensions import Final  # support Python < 3.8

NAME: Final = 'val'
```

**Comment by WisdomPill** [comment]
Hello @asvetlov !

I would be glad to step in and make a PR, are there other places that come to your mind that have these kind of constants?

**Comment by asvetlov** [comment]
Basically, any module-level assignment falls into one of three categories:
1. `__all__ = ...`  Not sure what to do. Maybe nothing.
2. Type alias, e.g. `_BytesIterator = AsyncIterator[bytes]`. Nothing to do here.
3. Constant assignment.  aiohttp has no global variables at all IIRC but has very many global constants. `aiohttp/hdrs.py` is a good example.

**Comment by WisdomPill** [comment]
Closing, it was merged almost a month ago
