### ISSUE TITLE
[Vote] Commit rights for Sam Bull

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#5302]
I'm nominating @Dreamsorcerer to the aiohttp Core team.

He is the aiohttp-jinaja2 maintainer already, also he proposed several PRs for aiohttp, aiohttp-session, etc.
PRs are in a good shape and demonstrate a good understanding of the development process
and our requirements for code, docs, tests, etc.

@aio-libs/aiohttp-committers please vote here in the comments.
The vote is ended in a week, on Tuesday of December 8.

**Comment by webknjaz** [comment]
+1

**Comment by derlih** [comment]
+1

**Comment by WisdomPill** [comment]
+1

**Comment by asvetlov** [comment]
Done. Congrats, @Dreamsorcerer 
Sorry for a little delay
