### ISSUE TITLE
Can support proxy with a specific scheme and host?

### ISSUE THREAD

**Issue by Green-li** [aio-libs/aiohttp#5305]
🐣 **Is your feature request related to a problem? Please describe.**

I want to use aiohttp with a proxy which has a specific scheme and host. This is support in `requests`.([requests doc page about proxy](https://requests.readthedocs.io/en/master/user/advanced/#proxies))

💡 **Describe the solution you'd like**

Can aiohttp support this feature? like:
```
async def read_website():
    async with aiohttp.ClientSession() as session:
        host = "http://example.com"
        proxy = "https://123.123.123.123:12345"
        proxy = {host: proxy}
        async with session.get('http://example.org/', proxy=proxy) as resp:
            await resp.read()
```

❓ **Describe alternatives you've considered**

When want to use this feature. I use ThreadPoolExecutor with requests.

📋 **Additional context**

**Comment by asvetlov** [comment]
HTTPS proxies are not supported yet
