### ISSUE TITLE
Make aiohttp.client_exceptions.InvalidURL have an error message

### ISSUE THREAD

**Issue by rgeronimi** [aio-libs/aiohttp#5315]
🐣 **Is your feature request related to a problem? Please describe.**
My project is storing failed requests from the aiohttp client. I store the string representation of the exception "str(exception)" in a database (>100.000 urls) which is enough. However I do get empty strings this way. These come from aiohttp.client_exceptions.InvalidURL exceptions that have no error message. This is unusual in Python where printing an exception (the equivalent operation to str(exception)) always gives you something.

💡 **Describe the solution you'd like**
aiohttp.client_exceptions.InvalidURL should have error messages to follow Python practices. There may be other exception types in this case.

❓ **Describe alternatives you've considered**
- Dumping the entire exception stack trace to get the exception type. Which in most high-volume crawling cases is useless and spammy
- Formatting myself the excepton message, adding for example the type itself when the exception has no message. This is not pythonic

📋 **Additional context**
Using latest version of aiohttp

**Comment by Mte90** [comment]
I got the same error and to me the URL seems valid but there isn't any hint why it isn't valid.

**Comment by webknjaz** [comment]
@Mte90 try the latest release candidate. It has some improvements in this area IIRC.

**Comment by Dreamsorcerer** [comment]
> This is unusual in Python where printing an exception (the equivalent operation to str(exception)) always gives you something.

This behaviour seems to be inherited from exceptions, so I'm not convinced that's true:
```
>>> str(Exception())     
''
```

I think you should be using `repr()`:
```
>>> repr(Exception())
'Exception()'
>>> repr(aiohttp.InvalidURL(""))   
'<InvalidURL >'
```
