### ISSUE TITLE
Returned Response object is None from session.get()

### ISSUE THREAD

**Issue by PythonCoderAS** [aio-libs/aiohttp#5332]
🐞 **Describe the bug**

On a request that I made to a server, the Response object that should be returned was replaced with `None`.

💡 **To Reproduce**

I'm not really sure how this happened, because the cause was a long-running task that made a request every 5 minutes. However, I suspect that the server was having major issues, although my logs cannot tell me exactly what happened.

💡 **Expected behavior**

A Response object is returned, regardless of server status.

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
Traceback (most recent call last):
  File "/home/PokestarFan/PokestarBot/bot_data/extensions/updates.py", line 419, in mangadex_update
    request.raise_for_status()
AttributeError: 'NoneType' object has no attribute 'raise_for_status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/PokestarFan/.local/share/virtualenvs/PokestarBot-NMj7rRyG/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/PokestarFan/PokestarBot/bot_data/extensions/updates.py", line 569, in check_for_updates
    await self.mangadex_update(manga_id, name)
  File "/home/PokestarFan/PokestarBot/bot_data/extensions/updates.py", line 420, in mangadex_update
    json = await request.json()
  File "/home/PokestarFan/.local/share/virtualenvs/PokestarBot-NMj7rRyG/lib/python3.8/site-packages/aiohttp/client.py", line 1026, in __aexit__
    self._resp.release()
AttributeError: 'NoneType' object has no attribute 'release'
```
Issue tied with log entry: https://github.com/PythonCoderAS/PokestarBot/issues/718

📋 **Your version of the Python**

```console
$ python --version
...
```

Python 3.8.6

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
...
```
```console
$ python -m pip show multidict
...
```
```console
$ python -m pip show yarl
...
```

```
Name: aiohttp
Version: 3.6.3
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /home/PokestarFan/.local/share/virtualenvs/PokestarBot-NMj7rRyG/lib/python3.8/site-packages
Requires: attrs, multidict, async-timeout, chardet, yarl
Required-by: discord.py, asyncprawcore

Name: multidict
Version: 4.7.6
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/PokestarFan/.local/share/virtualenvs/PokestarBot-NMj7rRyG/lib/python3.8/site-packages
Requires: 
Required-by: yarl, aiohttp

Name: yarl
Version: 1.5.1
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/PokestarFan/.local/share/virtualenvs/PokestarBot-NMj7rRyG/lib/python3.8/site-packages
Requires: idna, multidict
Required-by: asyncprawcore, aiohttp
```

📋 **Additional context**

Client session

Relevant code: https://github.com/PythonCoderAS/PokestarBot/blob/e4245558826898332e2d0e3753b62614f5260f78/bot_data/extensions/updates.py#L417-L420

**Comment by greshilov** [comment]
I've checked the original repo and I think the problem is in your code.

In the very beginning of the `check_for_updates`,  `load_session()` method is called:

https://github.com/PythonCoderAS/PokestarBot/blob/3dc4f17a47b8f94aab31e6f7040898f7555fd1cb/bot_data/extensions/updates.py#L551

This method replaces `aiohttp.ClientSession` with a `ReloadingClient`  in certain cases. `ReloadingClient` is defined here:

https://github.com/PythonCoderAS/PokestarBot/blob/ab258eb2d5289b3bb62ba6000a719aaf5639ece9/bot_data/utils/reloading_client.py#L9-L19

There is a bug in `ReloadingClient`. If the`ClientConnectorError` is raised, the `_request` method will return `None`. 

P.S. Please **do not** create issues in the library repo if you're not really sure what is happened.

**Comment by PythonCoderAS** [comment]
Thank you so much. The problem with a project like mine where I replace everything with custom versions that automatically handle certain exceptions is that it gets 10 times harder to trace errors that I haven't accounted for. I'll patch the code so that it raises otherwise.
