### ISSUE TITLE
Workflows cache is not used for skipping install

### ISSUE THREAD

**Issue by WisdomPill** [aio-libs/aiohttp#5337]
🐞 **Describe the bug**

Workflows have cache action to save installed packages but do not skip dependencies install

💡 **To Reproduce**

Just have a look at the actions runs

💡 **Expected behavior**

The actions to use the cache and actually skip installations.

I can work on that, I already worked on the workflows of this project and lately I have worked with workflows quite a bit.
Only an if is missing

**Comment by webknjaz** [comment]
Are you talking about GHA? Being a bit more specific would be helpful for understanding what it's all about.

**Comment by WisdomPill** [comment]
Yes, basically cache action has an output value to know if the cache was hit or not. In my opinion it should be like the example [here](https://github.com/actions/cache#example-workflow).

But if you have a look at the runs (for example [this](https://github.com/aio-libs/aiohttp/runs/1544749683?check_suite_focus=true)) the install dependencies step is executed while it can be skipped.

**Comment by asvetlov** [comment]
Cache works by saving/restoring a folder.
For aiohttp, it helps to skip downloading pip packages from PyPI.
It caches the `pip` cache (see also `pip cache ...` commands).
The installation of local copies is fast, I see no reason to skip this step.
Moreover, caching the `site-packages` folder can make a mess when dependencies are updated.

**Comment by webknjaz** [comment]
I agree with Andrew. And I've rechecked that it does indeed work. The only thing I'd change is maybe making the cache key more specific. But that's about it.

**Comment by WisdomPill** [comment]
I agree that the files are restored but then the `pip install` uses the cached packages, but it can be skipped using the hash of the requirements directory (like [here](https://github.com/actions/cache/blob/main/examples.md#python---pip) and [here](https://github.com/actions/cache#skipping-steps-based-on-cache-hit)) to make sure that if a dependency change then the cache would not restore and the dependencies are then installed from scratch. 

Now that I had a deeper look into it I discovered that the install is done only in the lint step and one question came to my mind, why the cache works with key `pip-ci-${{ runner.os }}-${{ matrix.pyver }}-{{ matrix.no-extensions }}-${{ hashFiles('requirements/*.txt') }}` in the `test` step if it is not saved with the same name elsewhere?

**Comment by WisdomPill** [comment]
Now I see, in the `Makefile` the `.develop` target installs the dependencies

**Comment by asvetlov** [comment]
@WisdomPill your first [link](https://github.com/actions/cache/blob/main/examples.md#python---pip) caches the pip cache folder, not site-packages.
How is it different from the settings that we have now in aiohttp?

**Comment by WisdomPill** [comment]
The difference is just that the install step is skipped, that's it. Like it is shown [here](https://github.com/actions/cache#skipping-steps-based-on-cache-hit)

But I understand that it is not a big optimization since the install is done in the `Makefile` when running unittests. So it will be done anyway

**Comment by webknjaz** [comment]
@WisdomPill `pip install` must never be skipped. It knows better than our simplistic cache whether the installs should be happening. Especially when some deps are unpinned or lack hashes. Or in case of post-releases that pip prefers over the regular ones. If you make it do nothing, we'll face problems far later in the future and that will make it hard to debug those.

**Comment by WisdomPill** [comment]
But the requirements are fixed in the `requirements` folder, so if the packages are cached there is no reason why pip would do something else besides saying that the dependency is already installed. I might be missing something here, as of my understanding `pip install` should run only if the requirements files change. 

In my opinion, the solution would be to create a separate target for unittest in `Makefile` that would not run the install before running the unittests , so that the install could be skipped conditionally if they have not been changed. This would result in approximately 20/25 seconds secs of skipped installation of already installed dependencies, with 9 combinations of environments it would result in 3/4 minutes less time to run all tests

But this is my opinion I understand if you do not welcome this change. After all it is about 20/25 seconds per build that would be skipped so not a big enhancement.

Feel free to close it

**Comment by webknjaz** [comment]
1) `pip install pkg==1.0.0` will pick up `1.0.0.post0` over `1.0.0` even if the post release is not in the pin.
2) You suggest caching `site-packages` but you should realize that those are also tightly coupled with the CPython install and will break every time GitHub updates Python in their worker VM images. Are you prepared to fix a broken CI every week or two?

**Comment by WisdomPill** [comment]
> `pip install pkg==1.0.0` will pick up 1.0.0.post0 over 1.0.0 even if the post release is not in the pin.

So the post release will be used if `pip install` is ran every time, I understand, it did not occur to me.

> You suggest caching `site-packages` but you should realize that those are also tightly coupled with the CPython install and will break every time GitHub updates Python in their worker VM images. Are you prepared to fix a broken CI every week or two?

I see, you mean that if the current version of python3.7 is `3.7.1` and then GitHub updates python 3.7 to python `3.7.2` something could break?

So your suggestion for every project (not only `aiohttp`) is to run `pip install` all the time?

In other projects I am using `pipenv`, in that case the two points that you have made are not valid anymore?
What if the version of python is used in the cache key?
Would number two be solved?

I am not trying to impose my opinion on the issue, I see it as an opportunity to learn from somebody that has more experience than me.

**Comment by webknjaz** [comment]
> I see, you mean that if the current version of python3.7 is `3.7.1` and then GitHub updates python 3.7 to python `3.7.2` something could break?

Yes. Especially, the virtualenvs will break because they are hard-linked to the interpreter for which they were created.
Don't take my word for it: pip maintainer @pradyunsg explains here why it's a bad idea™ to cache the installed packages: https://github.com/actions/cache/issues/175#issuecomment-636799040.

> So your suggestion for every project (not only `aiohttp`) is to run `pip install` all the time?

Yes, it's the safest approach possible.

> In other projects I am using `pipenv`, in that case the two points that you have made are not valid anymore?

pipenv still creates virtualenvs with site-packages under the hood. You can cache the location of the downloaded artifacts but not the installed site-packages. FWIW it uses the same dependency resolver as the most recent pip does. I don't know about the implementation details but it should also respect `.post`-versions per PEP440. OTOH, it probably works with its lockfile slightly differently.

> What if the version of python is used in the cache key?
> Would number two be solved?

This *sounds* safer but software distros aren't the same just because the runtime reports the same version. Some OS distros would add some patch backports and that would not necessarily change the main version part (even though they're supposed to patch it with something like a local version identifier). I don't know if GitHub does that but it's theoretically possible that they redeploy CPython of seemingly the same version but with some patch.

Have you never seen a virtualenv breaking after a system Python upgrade that doesn't bump the minor version, how about patch?

**Comment by WisdomPill** [comment]
I see, thanks for the clarification.

Last question before closing.
I guess that since also OS patches can cause disruption then also `pyenv` python distributions are affected?

**Comment by webknjaz** [comment]
Yes, but you normally don't replace them but build a newer version next to the old one and the old virtualenvs keep being connected to those.

**Comment by WisdomPill** [comment]
Okay, thanks for the clarification
