### ISSUE TITLE
`web_response.Response.prepared` is `False` after `write_eof()`

### ISSUE THREAD

**Issue by arthurdarcet** [aio-libs/aiohttp#5343]
`web_response.Response.prepared` is `False` after `write_eof()` (the payload writer goes back to None).

This is a bit mis-leading - any reason not to change `Response.prepared` to `self._eof_sent or self._payload_writer is not None`?

**Comment by asvetlov** [comment]
This is the oversight, sure.

Please feel free to make a pull request.
