### ISSUE TITLE
Drop python 3.3 support

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#537]
We are rely on `__del__` in the library a lot.
For graceful finalization for bare `aiohttp.request()` and family after merging #536 we should do session detach in https://github.com/KeepSafe/aiohttp/pull/536/files#diff-7dd84b5ef8d5eea2de1dfc5329411dfcR472

It doesn't work on Python 3.3. I can add weakref tricks, sure. But prefer dropping Python 3.3 at all.

Thoughts?

**Comment by fafhrd91** [comment]
+1

**Comment by ludovic-gasc** [comment]
+1

**Comment by carlcarl** [comment]
Should be closed?

**Comment by asvetlov** [comment]
Sure, thanks
