### ISSUE TITLE
[maintenance] Adjust test job timeouts in GitHub Actions CI/CD jobs

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiohttp#5389]
🐞 **Describe the bug**

The CI doesn't complete currently because the test jobs are capped to run under 15 minutes and they now get killed on timeout. I believe this is called by the new pip resolver doing backtracking which is rather time-consuming.

💡 **To Reproduce**

It's visible in any recent CI build.

💡 **Expected behavior**

The jobs should complete. Carefully bumping the timeout in the workflow file should be enough.

📋 **Logs/tracebacks**

Example: https://github.com/aio-libs/aiohttp/runs/1669008218?check_suite_focus=true

📋 **Your version of the Python**

N/A

📋 **Your version of the aiohttp/yarl/multidict distributions**

repo master

📋 **Additional context**

N/A

**Comment by greshilov** [comment]
Increased timeout will not solve the problem completely, I guess. Stricter `requirements.txt` could help though.

**Comment by webknjaz** [comment]
I think increasing the timeout should be enough to get it to run completely for the first time and then many things will probably get picked up from cache. One of the problems there is that when pip has to download many package versions, it makes the backtracking substantially slower when those packages don't have wheels.
