### ISSUE TITLE
Version 3.7.3 requires requires chardet<4.0,>=2.0, while having installed chardet 4.0.0

### ISSUE THREAD

**Issue by BKPepe** [aio-libs/aiohttp#5390]
🐞 **Describe the bug**

While using pip, it throws this error:

aiohttp 3.7.3 requires chardet<4.0,>=2.0, but you'll have chardet 4.0.0 which is incompatible.

💡 **To Reproduce**

- Install aiohttp version 3.7.3
- Install chardet 4.0.0

💡 **Expected behavior**

aiohttp 3.7.x is compatible with chardet 4.0.0
The same PR https://github.com/aio-libs/aiohttp/pull/5334 should be merged into 3.7 branch as well.

📋 **Your version of the Python**

```console
python3 --version
Python 3.9.1
```

**Comment by Harmon758** [comment]
It seems likely that the next version to be released will be 3.8.0.
See also #5366.

**Comment by BKPepe** [comment]
I missed somehow that issue. Too bad that there's not going to be 3.7.4 wth just applied PR, but let's see.

**Comment by BKPepe** [comment]
Duplicate of #5366
