### ISSUE TITLE
suspend coroutine instead of throwing timeout error when pool connection limits are exceeded

### ISSUE THREAD

**Issue by sify21** [aio-libs/aiohttp#5415]
🐣 **Is your feature request related to a problem? Please describe.**

I'm using aiohttp as client with connection pools. I read the docs about `ClientTimeout` and it says that
> connect
> The maximal number of seconds for connection establishment of a new connection or for waiting for a free connection from a pool if pool connection limits are exceeded.    

That means two situations for a timeout error:
- connection establishment is slow
- connection pool is full    

IMHO the latter one is an inner mechanism in the program, it shouldn't be clarified as a timeout.

💡 **Describe the solution you'd like**

In my use case, connection pool is to limit the number of async taks, to avoid `too many open files` error. When the pool is full, I want the coroutine suspended and can run it later when the pool is available.

❓ **Describe alternatives you've considered**

📋 **Additional context**

**Comment by Dreamsorcerer** [comment]
Isn't that something that should be done with an asyncio queue or similiar?
https://docs.python.org/3/library/asyncio-queue.html#queues

In other words, a coroutine won't run until you await on it, so avoid doing so if you don't want it to run yet.

Although, the docs also say "For pure socket connection establishment time use sock_connect.", so it sounds like that would do what you wanted anyway?
https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientTimeout.connect

**Comment by sify21** [comment]
> Isn't that something that should be done with an asyncio queue or similiar?
> https://docs.python.org/3/library/asyncio-queue.html#queues
> 
> In other words, a coroutine won't run until you await on it, so avoid doing so if you don't want it to run yet.
> 
> Although, the docs also say "For pure socket connection establishment time use sock_connect.", so it sounds like that would do what you wanted anyway?
> https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientTimeout.connect

thanks for the advice, I think you are right, I'll close.
