### ISSUE TITLE
URL querystring missing in tracer

### ISSUE THREAD

**Issue by DurandA** [aio-libs/aiohttp#5432]
🐞 **Describe the bug**

The URL querystring is not propagated to `params.url` in tracer callbacks.

💡 **To Reproduce**

```python
import aiohttp
import asyncio

async def on_request_start(session, trace_config_ctx, params):
    print(f'{repr(params.url)}')

async def main():
    trace_config = aiohttp.TraceConfig()
    trace_config.on_request_start.append(on_request_start)
    session = aiohttp.ClientSession(trace_configs=[trace_config])
    async with session:
        params = {'key1': 'value1', 'key2': 'value2'}
        async with session.get('http://httpbin.org/get', params=params) as resp:
            print(resp.url)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

💡 **Expected behavior**

`parms.url` should contain the query string (e.g. `http://httpbin.org/get?key1=value1&key2=value2`).

📋 **Your version of the Python**

Python 3.8.5

📋 **Your version of the aiohttp/yarl/multidict distributions**

aiohttp 3.6.2
multidict 4.7.6
yarl 1.6.3

**Comment by vadimber18** [comment]
@DurandA  `on_request_exception` did not actually triggered for your case, because request does not finishes with exception. You can try to change request url for invalid one to make sure `on_request_exception` works well when exception actually happens

**Comment by DurandA** [comment]
@vadimber18 Thanks. I replaced the example with `on_request_start` since the querystring is missing with other signals as well.

**Comment by vadimber18** [comment]
@DurandA `params.url` is an `URL` object, you can get query string with `params.url.query_string`

for your case try this:

```
print(params.url.query_string)
```

You can check other details on yarl readme [here](https://github.com/aio-libs/yarl#introduction)

**Comment by DurandA** [comment]
@vadimber18 Yes, `query_string` is empty.
