### ISSUE TITLE
Inconsistent Timeout Behaviour

### ISSUE THREAD

**Issue by trdavidson** [aio-libs/aiohttp#5451]
## Long story short
When using `aiohttp` to perform a get request, for some websites the timeout is not consistently respected, e.g. timeouts of <20 sec seem to work, while timeouts of >30 are not always respected.

## Expected behaviour
A timeout should be absolute, i.e. always timeout when the allotted time is exceeded.

## Actual behaviour
See print out of script below:
```
$ python minimal_reproducible.py 
Get error for http://www.stampsbythemes.com/kall/Allots.htm, , <class 'concurrent.futures._base.TimeoutError'>
timeout set: 10 sec - observed running time:  10.70 sec

Get error for http://www.stampsbythemes.com/kall/Allots.htm, , <class 'concurrent.futures._base.TimeoutError'>
timeout set: 15 sec - observed running time:  16.00 sec

Get error for http://www.stampsbythemes.com/kall/Allots.htm, , <class 'concurrent.futures._base.TimeoutError'>
timeout set: 20 sec - observed running time:  21.00 sec

Get error for http://www.stampsbythemes.com/kall/Allots.htm, , <class 'concurrent.futures._base.TimeoutError'>
timeout set: 25 sec - observed running time:  26.00 sec

timeout set: 30 sec - observed running time:  38.98 sec

timeout set: 40 sec - observed running time:  59.55 sec
```

## Steps to reproduce

```
import time
import aiohttp
import asyncio


async def get_url(url, session):

    html_page = None
    try:
        async with session.get(url) as resp:
            html_page = await resp.text()
            response_status = resp.status
    except Exception as er:
        error_type = str(type(er))
        print(f"Get error for {url}, {er}, {error_type}")

    return html_page


async def chain(url, timeout=50):
    timeout = aiohttp.ClientTimeout(total=timeout)
    connector = aiohttp.TCPConnector(limit=100)
    dummy_jar = aiohttp.DummyCookieJar()
    async with aiohttp.ClientSession(timeout=timeout, connector=connector, cookie_jar=dummy_jar) as session:
        result = await get_url(session=session, url=url)

    return result


async def main(url_batch, timeout=50):
    results = await asyncio.gather(*(chain(url=url, timeout=timeout)
                                     for url in url_batch),
                                   return_exceptions=True)
    return results

url_batch = [
    'http://www.stampsbythemes.com/kall/Allots.htm'
]
timeouts = [10, 15, 20, 25, 30, 40, 50]

for to in timeouts:
    start_time = time.perf_counter()
    results = asyncio.run(main(url_batch=url_batch, timeout=to))
    end_time = time.perf_counter() - start_time
    print(f'timeout set: {to} sec - observed running time: {end_time: .2f} sec\n')
```

## Your environment
- OS: MacOS Catalina
- aiohttp: tested on 3.7.2 and 3.7.3

**Comment by Dreamsorcerer** [comment]
Minimal example:
```
import time
import aiohttp
import asyncio

async def main(timeout):
    timeout = aiohttp.ClientTimeout(total=timeout)
    async with aiohttp.ClientSession(timeout=timeout) as session:
        async with session.get('http://www.stampsbythemes.com/kall/Allots.htm') as resp:
            try:
                print(len(await resp.text()))
            except asyncio.TimeoutError:
                print("TIMEOUT")

timeouts = [10, 15, 20, 25, 30, 40, 50]
for to in timeouts:
    start_time = time.perf_counter()
    asyncio.run(main(timeout=to))
    end_time = time.perf_counter() - start_time
    print(f'timeout set: {to} sec - observed running time: {end_time: .2f} sec\n')
```

**Comment by Dreamsorcerer** [comment]
The timeout is working correctly. If the connection times out within that period, TIMEOUT will be printed at the correct time.

In the other cases you are seeing, the connection must have completed before the timeout. As it continues to print the length of the response.

It seems that to process the full response takes a good 15-20 seconds of computation (you'll see the CPU usage running at 100% during this time). So, the delay you're seeing is from a successful completion, plus signifcant processing time.

The response is fairly large at about 8MB, but it seems odd to me that it would take 20 seconds to process it, so this may indicate there is some other performance bug (but, this has nothing to do with the timeout).

**Comment by trdavidson** [comment]
Hi @Dreamsorcerer - thanks for the quick response. That's the hunch we had as well - what is odd in that case, is that the `response.text()` operation appears to be taking >20+ seconds. Would you have any suggestion on how to catch such a case? or would it be possible to have a timeout on the content read/processing operation?

Thanks!

**Comment by Dreamsorcerer** [comment]
I'm not sure. For anyone looking to debug this, a minimal example for the performance issue:
```
import aiohttp
import asyncio

async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get('http://www.stampsbythemes.com/kall/Allots.htm') as resp:
            print(len(await resp.text()))

asyncio.run(main())
```

Observe 100% CPU usage for 10+ seconds.

**Comment by Dreamsorcerer** [comment]
Guessing this is related to string encoding though. I see no performance issues if I change it to `resp.read()`.

**Comment by trdavidson** [comment]
Haha - thanks for making the minimal example actually minimal :)

**Comment by Dreamsorcerer** [comment]
Perhaps encoding 8MB of data is too much, I'm not really sure of what the expected performance is here. Maybe someone else can answer whether this is an issue or not.

If you can use the data as bytes, then hopefully that's good enough for you. Otherwise, maybe look at processing a bit at a time, rather than loading the entire response into memory?
See: https://docs.aiohttp.org/en/stable/client_quickstart.html#streaming-response-content

**Comment by trdavidson** [comment]
@Dreamsorcerer - one possible fix to ensure the process stays within a bound:

```
html_page = await asyncio.wait_for(resp.text(), timeout=6.). # will at least have session_timeout + read_timeout as max
```

**Comment by Dreamsorcerer** [comment]
That won't make any difference. It's using much the same mechanism, if the code is busy and doesn't yield back to the event loop, then the wait_for() can't interrupt it in order to cancel. Once we're in the CPU bound section, there's no cancelling it.

**Comment by trdavidson** [comment]
@Dreamsorcerer - apologies for belated reply. You were absolutely correct. We ended up implementing a chunk based read as suggested and decoding manually. Thanks again for the pointer!
