### ISSUE TITLE
Server: query params decoding does not work for spaces encoded as %20

### ISSUE THREAD

**Issue by leeho** [aio-libs/aiohttp#5453]
🐞 **Describe the bug**

Since yarl 1.6.0, query params encoded with %20 does not get decoded. However, query params encoded with + do decode into spaces in place of +.

I can't reproduce this with a yarl.URL sample however, something is special about aiohttp.

💡 **To Reproduce**

Implement a route and print out a parameter:

@routes.get('/test')
async def test(request):
    try:
        query_params = request.query
        logger.info("Parameter: %s" % request.query["param"])

You will have:

?param=a+b > "a b"
?param=a%20b > "a%20b"

💡 **Expected behavior**

As far as I know, percent encoding should still be supported for spaces along with + in query params.

📋 **Your version of the Python**

3.6.8

📋 **Your version of the aiohttp/yarl/multidict distributions**

aiohttp==3.5.1
yarl==1.6.2 (reproduces since 1.6.0)

📋 **Additional context**

server

**Comment by code-yeongyu** [comment]
This same as client, when sending request. Waste my hours.

**Comment by webknjaz** [comment]
A reproducer would be useful. Without it, there's nothing actionable.

**Comment by Dreamsorcerer** [comment]
> aiohttp==3.5.1

It appears everything you are running is more than 5 years old and unsupported. Can you atleast verify the issue still exists on current releases (and a supported version of Python).

**Comment by leeho** [comment]
The issue was opened quite a while ago and is obsolete.

**Comment by leeho** [comment]
The issue was opened quite a while ago and is obsolete.
