### ISSUE TITLE
Make parameters to ClientResponse's __aexit__ default to None

### ISSUE THREAD

**Issue by iscai-msft** [aio-libs/aiohttp#5463]
🐣 **Is your feature request related to a problem? Please describe.**

Calling [`__aexit__`](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_reqrep.py#L1048) on `ClientResponse` requires three inputs that are typed as `Optional` and aren't actually used. Would be great to make these parameters default to `None`, so no need to supply when making this call.

💡 **Describe the solution you'd like**

Change the signature to 

```python
async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]] = None,
        exc_val: Optional[BaseException] = None,
        exc_tb: Optional[TracebackType] = None,
)
```

❓ **Describe alternatives you've considered**

📋 **Additional context**

**Comment by webknjaz** [comment]
They are not optional but the caller passes `None` in certain cases.

**Comment by Dreamsorcerer** [comment]
To expand on that:
> Optional[X] is equivalent to Union[X, None].
https://docs.python.org/3/library/typing.html#typing.Optional

The only way to mark an argument as not being needed is with `=`.

The signature of this method is well defined and should be the same in all applications:
[https://docs.python.org/3/reference/datamodel.html#object.`__aexit__`](https://docs.python.org/3/reference/datamodel.html#object.__aexit__)


Maybe the better question is why are you calling `__aexit__()`? This is meant to be used indirectly by using `async with`. If you're writing your own context manager that wraps this, then you should have a method with the exact same signature, and therefore pass the same arguments through. I'm not sure in what case you might be trying to call this method without arguments...

**Comment by webknjaz** [comment]
I'm curious if we should use `Union[X, None]` on args that don't have defaults to make it less confusing to people...

**Comment by Dreamsorcerer** [comment]
I feel that's a question more for the Python developers who named it. We should probably stick to the accepted norm, which is to use `Optional`. I guess the meaning is roughly `X` type is optional, so you can pass `None` if you don't have `X`.

I think it makes things more concise and readable in these circumstances, even if there's potential confusion for people new to annotations.

**Comment by webknjaz** [comment]
Closing per above.
