### ISSUE TITLE
Multipart/form-data is not carried over when proxying

### ISSUE THREAD

**Issue by Humbedooh** [aio-libs/aiohttp#5501]
🐞 **Describe the bug**

Whe accepting multipart/form-data from a client request (`aiohttp.web.Request`) and reading the data using `request.post()`, you are returned a `MultiDictProxy` with form key/value pairs and FileField objects for any files sent. When passing this onto a new `aiohttp.ClientSession` (I'm doing a transparent-ish proxy here), any `FileField` object is interpreted verbatim `str()` conversion instead of being put in as a multipart file element (which would in turn set the session post format to multipart).

Thus, instead of sending the multipart I receive as multipart to the backend, it is sending my file as a standard string, for instance: `FileField(name='filename', filename='testupload.txt', file=<_io.BufferedRandom name=9>, content_type='text/plain'` This of course causes my backend to complain about the file upload not being multipart.

💡 **To Reproduce**

Set up a simple `aiohttp.web.Application` and route anything to a function that does a `request.post()` fetch.
Pass the MultiDictProxy on to a `aiohttp.ClientSession` POST or PUT request, and it will bork the data by converting the object to a textual representation instead of the actual file.

💡 **Expected behavior**

aiohttp should analyze the multidict and see there is a FileField, and thus convert to multipart.

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)

```

📋 **Your version of the Python**

```console
$ python --version
Python 3.8.5
...
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
3.7.3
...
```
```console
$ python -m pip show multidict
5.1.0
...
```
```console
$ python -m pip show yarl
??
...
```

📋 **Additional context**

The work-around that I have found to work is as follows:
~~~python3
async def handle_request(req):
    post_dict = req.post()
    form_data = aiohttp.FormData()
    for k, v in post_dict.items():
        if isinstance(v, aiohttp.web.FileField):
            form_data.add_field(name=v.name, filename=v.filename, value=v.file.raw, content_type=v.content_type)
        else:
            form_data.add_field(name=k, value=v)
     async with aiohttp.ClientSession() as session:
        async with session.post("https://foo.bar.example.org/bla", data = form_data) as resp:
            pass
~~~

whereas passing `post_dict` instead of `form_data` would fail to create a multpart context

**Comment by paulefoe** [comment]
I can confirm that this exists. Unfortunately, so far I wasn't able to find an elegant way to fix this. Maybe someone has a suggestion where it should be fixed?

This is one place that I was looking at, where it chooses a different path, but probably it should be fixed a little bit higher https://github.com/aio-libs/aiohttp/blob/742a8b6d09b2623670ddede838c913d2a8a4d89e/aiohttp/formdata.py#L166


Here's code to reproduce:

client
```python
async def main():
    async with aiohttp.ClientSession() as session:
        data = FormData()
        data.add_field(
            'file',
            io.BytesIO(),
            filename='bytes_file',
        )

        await session.post('http://localhost:8080', data=data)
```
server1.py
```python
import aiohttp
from aiohttp import web
routes = web.RouteTableDef()
@routes.post('/')
async def hello(request):
    data = await request.post()

    async with aiohttp.ClientSession() as session:
        async with session.post("http://0.0.0.0:8081/", data=data) as resp:
            pass
    return web.Response(text="Hello, world")
app = web.Application()
app.add_routes(routes)
web.run_app(app, port=8080)

```

server2.py
```python
from aiohttp import web
routes = web.RouteTableDef()
@routes.post('/')
async def hello(request):
    data = await request.post()
    print(data)
    return web.Response(text="Hello, world")

app = web.Application()
app.add_routes(routes)
web.run_app(app, port=8081)

```

**Comment by Dreamsorcerer** [comment]
Aiohttp is not meant be a proxy, so I'm not sure this is a case that we want to support. If someone desperately wants to implement this though, they'd probably need to change FileField to some kind of protocol (e.g. subclassing IOBase) or something in order to allow the FormData.add_field() method to work with it.
