### ISSUE TITLE
More information about deployment?

### ISSUE THREAD

**Issue by songololo** [aio-libs/aiohttp#552]
As someone new to deploying websites, I'm wondering if it would be possible to provide more information about aiohttp deployment along with some recommended setups and settings, and some recommendations for when to use what type of setup given different goals. (e.g. websockets, CPU intensive apps, etc.)

What I've found so far:
- There is a documentation [page on deployment with gunicorn](http://aiohttp.readthedocs.org/en/stable/gunicorn.html?highlight=worker).
- There are also some comments in various issues discussions suggesting that aiohttp can be deployed directly (without gunicorn) behind nginx as a reverse proxy / load balancer.
- Some of the example files (websocket and multiprocess examples) use os.fork() to create child processes. I'm assuming that these examples would be used as a stand-alone deployment, presumably behind nginx?

**Comment by songololo** [comment]
The Gunicorn approach seems to make sense. I've made some suggested edits to the Gunicorn deployment page in the hopes of making it a bit easier to understand for newcomers to Gunicorn and web deployment in general. 

I'm still uncertain as to the deployment workflow if using the Supervisor / Child (with os.fork()) workflow shown in some of the aiohttp examples? I presume that these cases would be deployed directly behind nginx as a reverse proxy?

**Comment by asvetlov** [comment]
Yes, forked model is not intended to be run behind gunicorn.

**Comment by ludovic-gasc** [comment]
About the fact to handle by yourself supervisor/multiworker pattern with os.fork(), I've started with that in API-Hour, finally, it was easier to subcontract that to Gunicorn.

If you serve only HTTP/Websocket, at least to me, Gunicorn deployment is the simplest way for newcomers.

However, launch several times your daemon on several ports and loadbalance HTTP queries with Nginx or HAproxy is also a good pattern, especially with HAproxy, because you can control precisely the loadbalancing behaviour in HAproxy.

**Comment by auvipy** [comment]
what about uWSGI?

**Comment by asvetlov** [comment]
What is the reason to run aiohttp behind uWSGI?

**Comment by auvipy** [comment]
same as running behind gunicorn. does aiohttp support self hosted deployment behind nginx?

**Comment by asvetlov** [comment]
1. Gunicorn has dedicated aiohttp worker. uWSGI has no aiohttp support.
2. Yes, aiohttp can be set up in self hosted configuration (like tornado). It's native mode for the library.

**Comment by auvipy** [comment]
wasn't aware!! thanks for sharing!

**Comment by songololo** [comment]
Just to confirm, is it still recommend to use `aiohttp.worker.GunicornWebWorker` for the worker class instead of the built-in `gaiohttp` worker available in gunicorn?

**Comment by fafhrd91** [comment]
`gaiohttp` works only with `wsgi` and does not support aiohttp.web
we need to add wsgi support to `aiohttp.worker.GunicornWebWorker` and move it to gunicorn

**Comment by songololo** [comment]
Thanks for the clarification.

**Comment by asvetlov** [comment]
Fixed by 702dd0a
