### ISSUE TITLE
Version `3.7.4.post0` fails on `distutils.StrictVersion`

### ISSUE THREAD

**Issue by belegnar** [aio-libs/aiohttp#5520]
🐞 **Describe the bug**

```python-traceback
from distutils.version import StrictVersion
StrictVersion("3.7.4.post0")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.9/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/local/lib/python3.9/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '3.7.4.post0'

```

💡 **To Reproduce**

💡 **Expected behavior**

`StirctVersion` doesn't raise exception

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)

```

📋 **Your version of the Python**

```console
$ python --version
...
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
3.7.4.post0
...
```
```console
$ python -m pip show multidict
...
```
```console
$ python -m pip show yarl
...
```

📋 **Additional context**

**Comment by webknjaz** [comment]
This post-release version is compliant with https://www.python.org/dev/peps/pep-0440/#post-releases. It's not a bug in aiohttp, maybe in distutils.
But FWIW you really should be using https://packaging.pypa.io/ for parsing PEP 440 version strings.
