### ISSUE TITLE
Feature request: socket write timeout

### ISSUE THREAD

**Issue by runminlook** [aio-libs/aiohttp#5546]
🐣 **Is your feature request related to a problem? Please describe.**

When uploading a big file, we cannot use timeout.total. We need timeout.sock_write.

💡 **Describe the solution you'd like**

❓ **Describe alternatives you've considered**

📋 **Additional context**

**Comment by webknjaz** [comment]
Please fill out the form so we'd at least understand what you're trying to do and what your motivation might be. Be verbose, we can't guess what you had on your mind with this message.

**Comment by Dreamsorcerer** [comment]
I think you're saying that you need a `sock_write` timeout for uploads.

But, I'm not sure why `total` does not work for you.

@runminlook Can you provide an example to show why `total` cannot be used?
