### ISSUE TITLE
Authentication problems with vk.com

### ISSUE THREAD

**Issue by pohmelie** [aio-libs/aiohttp#557]
I'm trying to port [vk](https://github.com/dimka665/vk) to asyncio and aiohttp, [aiovk](https://github.com/pohmelie/aiovk). Everything goes fine until getting `access_token`. I spent a couple of hours to understand logic and find out what happens. So I made simple functions: one based on [requests](https://github.com/kennethreitz/requests) and other one based on [aiohttp](https://github.com/KeepSafe/aiohttp). They return at point when this libraries differs. I tried enable debug to see raw http requests, but it looks like aiohttp does not provide logging for this. So I can't compare it with requests (btw, requests does not provide full logging too, or I missed something). I can't compare them via wireshark, cause it is http**s**. So I'm here.
Here is [code](https://gist.github.com/pohmelie/2d6d39592f32b8827d47) to reproduce
On my side it produce:

```
requests version: 2.8.0
syn: https://oauth.vk.com/blank.html#access_token=*****&expires_in=*****&user_id=*****
aiohttp version: 0.17.4
asyn: https://oauth.vk.com/blank.html
```

And this is the point, where it breaks. Access token are not available with aiohttp. `response.text` is equal, but there is not this «redirection» to `#blah-blah`. Actually, when I tried it in browser (logged in with vk) https://oauth.vk.com/authorize?client_id=APP_ID&display=mobile&response_type=token&scope=message&v=5.28 (do not forget replace APP_ID) and it just works (even it is `params`, not `data`). Also, I checked that aiohttp version logged in successfully and tried `master` version from github.

I don't want run it in executor :sob:

**Comment by jettify** [comment]
Should be something very simple, I had similar issues with amazon s3. I suspect one of the headers is different or missing, you need to compare headers some how. In a mean time take a look here https://github.com/klen/aioauth-client There is vk auth client using aiohttp.

**Comment by pohmelie** [comment]
AFAIK it's not OAuth2, it is «special» type of getting token: you log in to get cookies and then request token. Anyway, today it silently works(!) and I don't understand why.
Also, I have tested headers via http://requestb.in and they are the same.

**Comment by pohmelie** [comment]
Tested on VM with xubuntu 15. Seems like this is 17.4 from pypi problem, since master version is ok.

**Comment by asvetlov** [comment]
I don't recall any difference related to your issue.

**Comment by pohmelie** [comment]
@asvetlov probably my tests are bad or not clean, but right now I made test on xubuntu 14.04 real machine:

``` shell
[broomrider ~/pro/py/tmp]$ python3 test-requests-aiohttp-auth-vk.py 
requests version: 2.8.0
syn: https://oauth.vk.com/blank.html#access_token=***&expires_in=86400&user_id=***
aiohttp version: 0.17.4
asyn: https://oauth.vk.com/blank.html
[broomrider ~/pro/py/tmp]$ git clone https://github.com/KeepSafe/aiohttp
Cloning into 'aiohttp'...
remote: Counting objects: 10550, done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 10550 (delta 115), reused 0 (delta 0), pack-reused 10362
Receiving objects: 100% (10550/10550), 4.72 MiB | 868.00 KiB/s, done.
Resolving deltas: 100% (7910/7910), done.
Checking connectivity... done.
[broomrider ~/pro/py/tmp]$ cd aiohttp
[broomrider ~/pro/py/tmp/aiohttp]$ sudo python3 setup.py install  
running install
...
Finished processing dependencies for aiohttp==0.18.0a0
[broomrider ~/pro/py/tmp/aiohttp]$ cd ..
[broomrider ~/pro/py/tmp]$ python3 test-requests-aiohttp-auth-vk.py 
requests version: 2.8.0
syn: https://oauth.vk.com/blank.html#access_token=***&expires_in=86400&user_id=***
aiohttp version: 0.18.0a0
asyn: https://oauth.vk.com/blank.html#access_token=***&expires_in=86400&user_id=***
```

Do not know what it exactly is, but… seems like version counts.

**Comment by asvetlov** [comment]
Ok. Maybe. I will publish aiohttp 0.18 soon anyway.
