### ISSUE TITLE
Warning if handler returned something different than Response

### ISSUE THREAD

**Issue by so1ov** [aio-libs/aiohttp#5587]
🐣 **Is your feature request related to a problem? Please describe.**

It makes me sad when the aiohttp server closes the session when I forgot to return aiohittp.web.json_response(some_dict) instead of just some_dict from the handler.

💡 **Describe the solution you'd like**

I want the code outside of the handler to produce a warning of the returning type not matching a valid response. 

❓ **Describe alternatives you've considered**

Maybe there should be an alternative Response type that behaves like now (silently closes connection) if explicitly used on the handler return.

Example:
>async def my_cool_handler(self, request):
    if cond1:
      return aiohttp.web.no_response() # closes session without returning anything
    elif cond2:
      return aiohttp.web.json_response({'foo': 'bar'}) # sends a response
    elif cond3:
      return {'foo': 'bar'} # should produce a warning!

   

📋 **Additional context**

**Comment by Dreamsorcerer** [comment]
Works for me. You should probably make sure you're developing with dev features enabled. I usually run with `python -bb -Wall -X dev ...`.

You could also use mypy for static typing, which would also give you an error without even needing to run that branch of the code.

```
from aiohttp import web

async def handle(request):
    return {'a': 'b'}

app = web.Application()
app.router.add_get("/", handle)

if __name__ == '__main__':
    web.run_app(app)
```

Produces:
```
Unhandled runtime exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 447, in start
    raise RuntimeError("Web-handler should return "
RuntimeError: Web-handler should return a response instance, got {'a': 'b'}
```
