### ISSUE TITLE
aiohttp client does not support ipv6 addresses

### ISSUE THREAD

**Issue by mx2323** [aio-libs/aiohttp#559]
attempting to get a webpage from an ipv6 address doesnt appear to work in aiohttp 0.17.4

when i run the ipv6 address through curl it works. 

i also tried the ipv4 address through the aiohttp client and that worked as well. 

http://[::1]:9001/foo fails with the following exception
*\* 
socket.gaierror: [Errno -9] **Address family for hostname not supported**
**

```
 Cannot connect to host ::1:9001 ssl:False http://[::1]:9001/foo
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 571, in _create_connection
    server_hostname=hinfo['hostname'] if sslcontext else None)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 581, in create_connection
    infos = f1.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -9] **Address family for hostname not supported**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 292, in connect
    transport, proto = yield from self._create_connection(req)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 588, in _create_connection
    (req.host, req.port)) from exc
aiohttp.errors.ClientOSError: Can not connect to ::1:9001
```

**Comment by mx2323** [comment]
looks like through a client with a session, it has to be specified via the connector, which is not intuitive or called out clearly in the documentation imo.

**Comment by asvetlov** [comment]
That makes sense, I see no objections for relaxing default _family_ param from IPv4 to both IPv4 and IPv6.

**Comment by asvetlov** [comment]
Fixed

**Comment by gwillem** [comment]
@asvetlov relaxing family breaks (cryptically) on systems with an IPv6 stack, `aiodns` installed but no IPv6 route. See https://github.com/saghul/aiodns/issues/23

Not sure if pycares should default to IPv4 for `gethostbyname`. If not, then perhaps the `aiohttp` docs should include a warning about this situation.

**Comment by asvetlov** [comment]
aiodns is disabled by default by 9fbb7d7

**Comment by brunsgaard** [comment]
For other people wanting to use aiodns, but force IPv4, the solution is to make a custom connector, with `family` bound to `socket.AF_INET` (IPv4).

``` python
import aiohttp
import asyncio
import socket

async def main(loop):
    url = 'http://requestb.in/yn6p4wyn'

    conn = aiohttp.TCPConnector(family=socket.AF_INET)
    async with aiohttp.ClientSession(connector=conn) as session:
        async with session.get(url) as resp:
            await resp.release()

loop = asyncio.get_event_loop()
loop.run_until_complete(main(loop))
loop.close()
```

I would just point that out, as I think it might be helpfull to some people out there ;)
