### ISSUE TITLE
WebSocketResponse.send_str should be a coroutine?

### ISSUE THREAD

**Issue by warvariuc** [aio-libs/aiohttp#560]
[`WebSocketResponse.send_str`](http://aiohttp.readthedocs.org/en/latest/web_reference.html#aiohttp.web.WebSocketResponse.send_str) unlike [`WebSocketResponse.receive`](http://aiohttp.readthedocs.org/en/latest/web_reference.html#aiohttp.web.WebSocketResponse.receive) is not coroutine. Sending data to a client is an input/output operation, which is an async job.

I have a lot of websocket clients to send them the same message:

```
for ws in websockets:
    ws.send_str(a_message)
```

IIUC, clients will be sent the message one after another.

How to fix this? Or am I missing something?

**Comment by asvetlov** [comment]
Socket writing is asynchronous operation. `send_str()` call instantly forms websocket message and puts it into internal buffer. Sending buffer via socket is performed by transport code in background.

**Comment by warvariuc** [comment]
Ah, thanks

**Comment by warvariuc** [comment]
I think adding this info to the docs would be a good idea.

**Comment by asvetlov** [comment]
Would you make a Pull Request with documentation clarification?

**Comment by asvetlov** [comment]
WebSocket case is very similar to regular `StreamResponse.write()` which is also non-coroutine.

**Comment by warvariuc** [comment]
Maybe later. For now will leave the [link here](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.WriteTransport.write):

> `write(data)`
> Write some data bytes to the transport.
> 
> This method does not block; it buffers the data and arranges for it to be sent out asynchronously.
