### ISSUE TITLE
Unable to install with speedups in CPython 3.10.0-alpha-7 due to failures with pycares

### ISSUE THREAD

**Issue by davfsa** [aio-libs/aiohttp#5604]
🐞 **Describe the bug**
When installing aiohttp with speedupds, it installs `aiodns`, which itself relies on `pycares`. These two libs are currently unmaintained as stated here: https://github.com/saghul/pycares/issues/139. This will make installing aiohttp with speedups impossible in CPython 3.10. 

💡 **To Reproduce**
Install CPython 3.10 and try to install aiohttp with speedups.

Examples:
- https://github.com/hikari-py/hikari/pull/516/checks?check_run_id=2305172086 (Linux)
- https://github.com/hikari-py/hikari/pull/516/checks?check_run_id=2305172150 (MacOS)
- https://github.com/hikari-py/hikari/pull/516/checks?check_run_id=2305172240 (Windows)

💡 **Expected behavior**
Installation with speedups succeeds. This might require looking for a different package or maintaining that package.

📋 **Logs/tracebacks**
Check links above

📋 **Your version of the Python**
```console
$ python --version
Python 3.10.0a7
```

📋 **Your version of the aiohttp/yarl/multidict distributions**
Unable to install, but the version that we are trying to install is `3.7.4.post0`

📋 **Additional context**
None

**Comment by webknjaz** [comment]
Well, that's unfortunate... As a workaround, you could install `Brotli` and `cchardet` directly w/o depending on the `speedups` extra. I don't know how much we can do about these deps. Maybe we could guide them towards setting up shared maintenance but I doubt anybody under @aio-libs has the capacity to step up.

**Comment by davfsa** [comment]
> Well, that's unfortunate... As a workaround, you could install `Brotli` and `cchardet` directly w/o depending on the `speedups` extra. I don't know how much we can do about these deps. Maybe we could guide them towards setting up shared maintenance but I doubt anybody under @aio-libs has the capacity to step up.

In my project we install the dependencies separately to aiohttp if people choose to install the speedups, so we will most likely disable `aiodns` for Python 3.10 if nobody takes over. Thanks for the info tho. I hope someone can take over (I personally lack too much C knowledge for this task)

**Comment by Molkree** [comment]
@davfsa, try installing `wheel` first, then you should be able to install `aiohttp[speedups]` on Python 3.10.
See [here](https://github.com/Molkree/github_actions/actions/runs/775800055).
And when I removed `wheel` [here](https://github.com/Molkree/github_actions/actions/runs/775828557).

**Comment by davfsa** [comment]
> @davfsa, try installing `wheel` first, then you should be able to install `aiohttp[speedups]` on Python 3.10.
> See [here](https://github.com/Molkree/github_actions/actions/runs/775800055).
> And when I removed `wheel` [here](https://github.com/Molkree/github_actions/actions/runs/775828557).

Yep, that seems to have fixed it :+1: TIL that `-e` flag will not install the `requires` specified in `pyproject.toml`. Thanks for pointing this out!

I think this issue should be fixed then, as you can just use `wheels` to install the package
