### ISSUE TITLE
Autobahn test needs updating

### ISSUE THREAD

**Issue by Dreamsorcerer** [aio-libs/aiohttp#5606]
The `_make_handler()` method was removed in this PR: https://github.com/aio-libs/aiohttp/pull/3939

But, is still used at: https://github.com/aio-libs/aiohttp/blob/master/tests/autobahn/server.py#L37

This needs updating, if anybody would like to take on this small task.

References to `aiohttp.ws_connect()` appear to also need updating:
https://github.com/aio-libs/aiohttp/blob/master/tests/autobahn/client.py#L9

**Comment by wfatherley** [comment]
For the `server.py` bugfix, is it sufficient to utilize `web.run_app` in conjunction with an on-shutdown signal, like so:
```python
...

async def on_shutdown(app):
    for ws in set(app["websockets"]):
        await ws.close(code=WSCloseCode.GOING_AWAY, message="Server shutdown")


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.DEBUG, format="%(asctime)s %(levelname)s %(message)s"
    )

    app = web.Application()
    app.router.add_route("GET", "/", wshandler)
    app.on_shutdown.append(on_shutdown)
    try:
        web.run_app(app)
    except KeyboardInterrupt:
        print("Server stopped at http://127.0.0.1:9001")
```

or will usage of an `AppRunner` be preferred?

**Comment by Dreamsorcerer** [comment]
At a quick glance, that looks good to me. Atleast, it makes more sense to me than the original code does.
