### ISSUE TITLE
Webserver crashes when a client connects using HTTPS

### ISSUE THREAD

**Issue by Aed3r** [aio-libs/aiohttp#5616]
🐞 **Describe the bug**
I set up a simple HTTP web server using aiohttp. Since it doesn't need secure communications with it's clients I didn't set up SSL. Unfortunately, this means that as soon as someone tries connecting using HTTPS the program crashes. The crash report indicates this happens entirely inside aiohttp, so I see no way of handling this in my program.

💡 **To Reproduce**

1. Create a simple server. Eg :
```python
from aiohttp import web

async def hello(request):
    return web.Response(text="Hello, world")

app = web.Application()
app.add_routes([web.get('/', hello)])

web.run_app(app)
```

2. Run the program and go to `https://0.0.0.0:8080/`

3. The server crashes with :
```python-traceback
Error handling request
Traceback (most recent call last):
  File "/home/aeder/.local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"`
```

💡 **Expected behavior**
Not immediately crashing, or having a way to catch the error without setting up HTTPS

📋 **Logs/tracebacks**

```python-traceback
Error handling request
Traceback (most recent call last):
  File "/home/aeder/.local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
```

📋 **Your version of the Python**

```console
$ python --version
Python 3.9.2
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.4.post0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /home/aeder/.local/lib/python3.9/site-packages
Requires: chardet, typing-extensions, multidict, attrs, async-timeout, yarl
Required-by: 
```
```console
$ python -m pip show multidict
Name: multidict
Version: 5.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/aeder/.local/lib/python3.9/site-packages
Requires: 
Required-by: yarl, aiohttp
```
```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.3
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/aeder/.local/lib/python3.9/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

📋 **Additional context**

OS: Manjaro
No proxy
aiohttp server framework

**Comment by Dreamsorcerer** [comment]
The server does not crash when I try your example.
It just raises an exception for that current request (but still handles more requests).
Unless you're running with `-We` or something (which would be weird to do in production), I don't see a reason it would crash/exit.

Regardless, if you're deploying an app on the internet, you should probably be running this behind a proxy server such as nginx, which would stop HTTPS traffic reaching aiohttp in the first place.
See the documentation at: https://docs.aiohttp.org/en/stable/deployment.html#aiohttp-deployment

**Comment by Aed3r** [comment]
That's weird. Are you using a different version ? I just simply run `python test.py` without any options. 

The server is intended for a local network only, so using a proxy doesn't really make sense. But I'll look into it if it doesn't add too much work. Thanks for the link.

**Comment by Dreamsorcerer** [comment]
Running python 3.8 with latest (3.7.x) aiohttp. I can definitely open the page multiple times in the browser and have the exception appear multiple times and then go back to http: successfully, the server only stops when I Ctrl+C.

**Comment by Dreamsorcerer** [comment]
Output exactly matches what you posted in the description (once for each HTTPS attempt).

**Comment by Aed3r** [comment]
Welp, you're right, being used to other such error messages I assumed the whole thing stopped working and didn't think of checking again. Seems everything is fine after all. Sorry for the trouble, and thanks for your work!
