### ISSUE TITLE
Forbidden error raised by aiohttp used in dask-gateway

### ISSUE THREAD

**Issue by aravindrp** [aio-libs/aiohttp#5624]
🐞 **Describe the bug**

I am trying to setup dask-gateway in kubernetes and it uses aiohttp internally for connecting with api server. While trying to connect with dask-gateway from a jupyter notebook, I am getting the following error:

![image](https://user-images.githubusercontent.com/29331442/114976921-6918f300-9ea4-11eb-8594-fb2900dfe638.png)

api server is hosted in another namespace within the same kubernetes cluster. First I thought that it was an issue with k8 setup or dask-gateway. But the same code worked, when I tried to curl the same url. Also from the same jupter notebook I tried to connect with url using urllib3 library then also it worked without any issues. So it seems like a behavior related to aiohttp.

![image](https://user-images.githubusercontent.com/29331442/114977011-94034700-9ea4-11eb-9454-f360eb9fc9db.png)

💡 **To Reproduce**

💡 **Expected behavior**

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)

---------------------------------------------------------------------------
ClientResponseError                       Traceback (most recent call last)
<ipython-input-8-f8cbd85b6152> in <module>
----> 1 gateway.list_clusters()

/opt/conda/lib/python3.7/site-packages/dask_gateway/client.py in list_clusters(self, status, **kwargs)
    453         clusters : list of ClusterReport
    454         """
--> 455         return self.sync(self._clusters, status=status, **kwargs)
    456 
    457     def get_cluster(self, cluster_name, **kwargs):

/opt/conda/lib/python3.7/site-packages/dask_gateway/client.py in sync(self, func, *args, **kwargs)
    341             )
    342             try:
--> 343                 return future.result()
    344             except BaseException:
    345                 future.cancel()

/opt/conda/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

/opt/conda/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

/opt/conda/lib/python3.7/site-packages/dask_gateway/client.py in _clusters(self, status)
    432 
    433         url = "%s/api/v1/clusters/%s" % (self.address, query)
--> 434         resp = await self._request("GET", url)
    435         data = await resp.json()
    436         return [

/opt/conda/lib/python3.7/site-packages/dask_gateway/client.py in _request(self, method, url, json)
    417                 raise GatewayServerError(msg)
    418             else:
--> 419                 resp.raise_for_status()
    420         else:
    421             return resp

/opt/conda/lib/python3.7/site-packages/aiohttp/client_reqrep.py in raise_for_status(self)
   1003                 status=self.status,
   1004                 message=self.reason,
-> 1005                 headers=self.headers,
   1006             )
   1007 

ClientResponseError: 403, message='Forbidden', url=URL('http://dask-gateway.<namespace>.svc:8000/api/v1/clusters/')

```

📋 **Your version of the Python**

```console
$ python --version
...

python version - 3.7.9
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
...

aiohttp version : 3.7.2
```

```console
$ python -m pip show multidict
...
```
```console
$ python -m pip show yarl
...
```

📋 **Additional context**

**Comment by webknjaz** [comment]
There's not enough information to conclude what's happening. Maybe some data in the request is encoded differently (it may depend on the multidict or yarl versions which you didn't fill out). Besides we don't know if you use aiohttp and other libraries with C-extensions or without them.
And more importantly, this needs an aiohttp-based reproducer. For all I know, this looks like your `dask_gateway` thingy may be misusing aiohttp or adding some extra headers under the hood that you didn't pass directly to `requests`, you should really report a bug to that project first, there's nothing we can do about it here.
P.S. You need to at least figure out what HTTP requests are sent over the wire in both cases. If it's really plain unencrypted HTTP, you could just use tcpdump/wireshark. If it's HTTPS, you may want to write a simple web server, send requests there, and record what data it gets.

Anyway, as it stands now, it's not a bug, there's no evidence that it may be.
