### ISSUE TITLE
ClientResponse.json() method's return not properly documented

### ISSUE THREAD

**Issue by Srogozins** [aio-libs/aiohttp#563]
The doc for ClientResponse.json()  states:

`:return dict: *BODY* as *JSON* data.`

However it seems that that's not always the case. When the response JSON body top element is an array, it returns a list object. Additionally, if the body is just whitespace, it returns None:
https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client_reqrep.py#L749

Tested on aiohttp 0.17.4

**Comment by asvetlov** [comment]
Well, it returns `json.loads(<response body>)`  technically.
If _stripped_ response body is empty the method returns `None`.
Would you provide a Pull Request for documentation?

**Comment by Srogozins** [comment]
I can do it some time next week.

**Comment by asvetlov** [comment]
Thanks

On Sun, Oct 11, 2015 at 10:54 PM, Staņislavs Rogozins <
notifications@github.com> wrote:

> I can do it some time next week.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KeepSafe/aiohttp/issues/563#issuecomment-147239409.

## 

Thanks,
Andrew Svetlov

**Comment by asvetlov** [comment]
Fixed
