### ISSUE TITLE
server response will assert when being serialized if compression enabled and body is not set

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiohttp#5638]
🐞 **Describe the bug**
If you don't set a body on a http response and enable compression the response will crash due to this [assert](https://github.com/aio-libs/aiohttp/blob/3.7/aiohttp/web_response.py#L726).

💡 **To Reproduce**
```python
    async def handler(_):
        resp = web.Response()
        resp.enable_compression()
        return resp
```

💡 **Expected behavior**
not assert.  Perhaps if it's None it should just skip the compression and have empty body like if compression were not enabled, or it could compress an empty string body.  Having it assert while it's serializing the response is not good.

📋 **Your version of the Python**
python 3.8.6

📋 **Your version of the aiohttp/yarl/multidict distributions**
aiohttp 3.7.4.post0

**Comment by thehesiod** [comment]
probably it should assert on the call to enable_compression then

**Comment by anesabml** [comment]
@thehesiod I think that would be better but we'll need to check the git history and see if there's a reason why the assert exists in `_compress_body`.

**Comment by anesabml** [comment]
It looks like the assert was added in this [commit](https://github.com/aio-libs/aiohttp/commit/22a58e251063cb3a060a7576d356c94a73dcd99c).

**Comment by anesabml** [comment]
@asvetlov Any idea about the placement of the assert statement?

**Comment by Dreamsorcerer** [comment]
> @asvetlov Any idea about the placement of the assert statement?

It was a typing PR, so clearly he thought it could never happen at runtime and was just resolving the typing error for mypy.

**Comment by Dreamsorcerer** [comment]
I don't get any error with the example, so I assume that was fixed at some point.
