### ISSUE TITLE
Redirects do not use cookies from the main request's response

### ISSUE THREAD

**Issue by IamMusavaRibica** [aio-libs/aiohttp#5659]
🐞 **Describe the bug**
Sending a request that has redirects updates the cookies at the end of all redirects instead of immediately after the redirect (the old session cookies apply to all the redirects in the request)

Real example:
Having a ClientSession and sending a GET request to specific website sets some cookies.
Next request that is to be done with that session is a POST which is used to log in. It has to send the cookies from the first response. This request is a redirect, however after the first redirect server returns a new cookie with the **same keys** but **different values**. That new cookie has to be used in the redirect The aiohttp request just uses the old cookies from the first GET request and therefore the request fails.
The synchronous `requests` library does that correctly, though. 

💡 **To Reproduce**
I cannot make full reproducing steps here because it involves passing some private data but my messages are open to aiohttp's devs.
```python
from aiohttp import ClientSession
import asyncio
from bs4 import BeautifulSoup

url = "https://ocjene.skole.hr/"

async def main():
    session = ClientSession()
    r1 = await session.get(url + "login")
    # The csrf token that is retrieved from the html form
    csrf = BeautifulSoup(await r1.text(), 'html.parser')("input", limit=3)[2]["value"]
    data = {"username": "foo", "password": "bar", "csrf_token": csrf}

    # Convert session cookies to a dictionary
    cookies = {}
    for c in session.cookie_jar:
        cookies[c.key] = c.value

    r2 = await session.post(url, data=data, cookies=cookies)
    print(await r2.text())
    await session.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```
Since the second request (r2) consists of several redirects, the first request should modify the session's cookies which will be passed in the next redirects.
[![Chrome Dev tools Network tab request screenshot](https://image.prntscr.com/image/mTYbkISNTZ_XSJAOrFHP-w.png)](https://image.prntscr.com/image/mTYbkISNTZ_XSJAOrFHP-w.png)

💡 **Expected behavior**
Since the second request (r2) consists of several redirects, the first request should modify the session's cookies which will be passed in the next redirects, but those cookies update after **all** redirects. (Checked with `session.cookie_jar` before and after r2)
Cancelling redirects and making a third request manually that would be the same as the redirect works:
```python
r2 = await session.post(url, data=data, headers=r1headers, allow_redirects=False)
# Modifying the old cookie with the new one
cookies["cnOcjene"] = dict(r2.cookies)["cnOcjene"].value

# url + 'class' is the URL of the first redirect in before example
r3 = await session.get(url + 'class', cookies=cookies)
print(await r3.text())  # correct
```

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)

```

📋 **Your version of the Python**

```console
$ python --version
Python 3.8.6
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.6.3
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: c:\users\iammusavaribica\appdata\local\programs\python\python38\lib\site-packages
Requires: chardet, async-timeout, attrs, yarl, multidict
Required-by: fortnitepy, discord.py
```
```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.6
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\users\iammusavaribica\appdata\local\programs\python\python38\lib\site-packages
Requires:
Required-by: yarl, aioxmpp, aiohttp
```
```console
$ python -m pip show yarl
Name: yarl
Version: 1.5.1
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\users\iammusavaribica\appdata\local\programs\python\python38\lib\site-packages
Requires: idna, multidict
Required-by: aiohttp
```

📋 **Additional context**

**Comment by anesabml** [comment]
@IamMusavaRibica can you confirm that this code example reproduces your issue:
1. server.py:
```python
from aiohttp import web
from pprint import pformat

routes = web.RouteTableDef()

tmpl = """\
<html>
    <body>
        <p>{}</p>
    </body>
</html>"""

@routes.get('/')
async def root(request: web.Request) -> web.StreamResponse:
    resp = web.Response(content_type="text/html")
    resp.text = tmpl.format(pformat(dict(request.cookies)))
    return resp

@routes.get('/login')
async def login(request: web.Request):
    exc = web.HTTPFound(location="/")
    exc.set_cookie("AUTH", "secret")
    raise exc

def init() -> web.Application:
    app = web.Application()
    app.add_routes(routes)
    web.run_app(app)
    return app


web.run_app(init())
```

2. client.py:
```python
import aiohttp
import asyncio


async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get('http://localhost:8080/login') as resp:
            print(resp.status)
            print(await resp.text())

loop = asyncio.get_event_loop()
loop.run_until_complete(main())

```

**Comment by IamMusavaRibica** [comment]
The example you provided doesn't have anything to do with cookies and redirects though;
I fixed my issue by not allowing redirects and instead making those redirect requests manually, but i opened this because it differs from `requests` library

**Comment by Dreamsorcerer** [comment]
> @IamMusavaRibica can you confirm that this code example reproduces your issue:

I think that example will just reproduce the server-side bug (in aiohttp 3.7) that drops the cookie. Probably nothing to do with this bug report which is about client-side behaviour.

**Comment by anesabml** [comment]
@Dreamsorcerer yes I agree because the code example works fine on new versions. Do you have any suggestions on how to reproduce this bug?

**Comment by Dreamsorcerer** [comment]
I'm struggling to fully understand the original issue, it would be helpful if @IamMusavaRibica could provide step-by-step what is meant to happen (like add a comment in each line of the example code explaining what is happening and what is going wrong).

Then it should be easier to write a full reproducer including server-side code.

**Comment by IamMusavaRibica** [comment]
> I'm struggling to fully understand the original issue, it would be helpful if @IamMusavaRibica could provide step-by-step what is meant to happen (like add a comment in each line of the example code explaining what is happening and what is going wrong).
> 
> Then it should be easier to write a full reproducer including server-side code.

Sorry for being this late. Consider the following request scenario:

1. You make a request to an endpoint, `/first`
2. The server responds with a Set-Cookie header, let's say `session=1234`. The response is a 302 with a Location header set to `/second` (so it's a redirect)
3. Since you sent the request without disallowing redirects, `aiohttp` will follow the redirect to `/second`, and it should use the cookie that the server returned before. But it doesn't. In contrast, `requests` library does that

**Comment by IamMusavaRibica** [comment]
However, I tested this recently, and it worked exactly it was supposed to, so I'm closing this
