### ISSUE TITLE
Autosquash doesn't work for the Dependabot PRs

### ISSUE THREAD

**Issue by greshilov** [aio-libs/aiohttp#5665]
🐞 **Describe the bug**

Since March 2021 workflows that are triggered by Dependabot are treated as they were opened from forks.
Thus, `secrets` context is not available for them, and that's why `Autosquash` job fails again and again for the Dependabot PRs.

Read more on that topic [here](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/).

💡 **To Reproduce**

See  #5664,  #5663 and others.

💡 **Expected behavior**

Should work, maybe without `Autosquash` functionality.

📋 **Logs/tracebacks**

```
Run tibdex/github-app-token@v1
Error: Error: Input required and not supplied: app_id
```

**Comment by webknjaz** [comment]
I think I haven't seen that job succeed in quite a while. I'd probably just drop it altogether.

**Comment by greshilov** [comment]
> I think I haven't seen that job succeed in quite a while. I'd probably just drop it altogether.

Fair enough!

**Comment by Dreamsorcerer** [comment]
Is there any relation here to aiohttp-jinja2? Seems the dependabot PRs have stopped auto-merging just this week or last week.
e.g. https://github.com/aio-libs/aiohttp-jinja2/pull/442

**Comment by Dreamsorcerer** [comment]
So expected behaviour is to trigger the merge manually now? Which is quite a hassle with the number of PRs dependabot produces.

**Comment by webknjaz** [comment]
Yes. I saw a "combined PR" automation in the Warehouse repo. Feel free to explore how it's set up if you want: https://github.com/pypa/warehouse/pull/9226 / https://github.com/pypa/warehouse/pull/9227.

**Comment by Dreamsorcerer** [comment]
> Yes. I saw a "combined PR" automation in the Warehouse repo. Feel free to explore how it's set up if you want: [pypa/warehouse#9226](https://github.com/pypa/warehouse/pull/9226) / [pypa/warehouse#9227](https://github.com/pypa/warehouse/pull/9227).

I found an automerge action. Is it worth trying one of these out?
https://github.com/marketplace/actions/dependabot-auto-merge
or
https://github.com/fastify/github-action-merge-dependabot/
 (There's a writeup of this one at: https://www.nearform.com/blog/github-dependabot-automation/)

There's also this script:
https://appsectribe.medium.com/automerge-github-dependabot-alerts-with-github-actions-7cd6f5763750

**Comment by Dreamsorcerer** [comment]
@webknjaz ^^^
If it's worth trying, I've prepared a PR for aiohttp-jinja2, it just needs a token added.
https://github.com/aio-libs/aiohttp-jinja2/pull/458/files
