### ISSUE TITLE
Incorrect behavior for `timeout` parameter in `aiohttp.request` method

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#57]
Now the library uses timeout only for reading data from opened socket, not for connecting stage.
So if the server don't answer I'll get a error like `TimeoutError: [Errno 110] Connect call failed ('66.221.212.5', 8888)` where `TimeoutError` is not `asyncio.TimeoutError` but exception derived from `OSError`, it's raised by OS.
Moreover, event if we put connection stage under the hood of timeout we still have a bit strange behavior: timeout will work only for connecting and reading HTTP headers but not for getting HTTP body.

I guess just to remove `timeout` parameter from the API and recommend to use `asyncio.wait_for` directly if needed.

Thoughts?

**Comment by liqvidus** [comment]
Using asyncio.wait_for leads to  resource leaks
```
    conn = aiohttp.ProxyConnector(proxy=random.choice(PROXY), force_close=True)
    try:
        resp = yield from asyncio.wait_for(aiohttp.request('HEAD', 'http://google.com', connector=conn), 1.0)
    except asyncio.TimeoutError:
        pass
    conn.close()
```

https://github.com/KeepSafe/aiohttp/pull/79

**Comment by liqvidus** [comment]
Using asyncio.wait_for leads to resource leaks when timeout occurs
```
    conn = aiohttp.ProxyConnector(proxy=random.choice(PROXY), force_close=True)
    try:
        resp = yield from asyncio.wait_for(aiohttp.request('HEAD', 'http://google.com', connector=conn), 1.0)
    except asyncio.TimeoutError:
        pass
    conn.close()
```
found issue with resource leaks https://github.com/KeepSafe/aiohttp/pull/79
