### ISSUE TITLE
Not establishing connections after update of both aiorun and aiohttp 

### ISSUE THREAD

**Issue by pavka14** [aio-libs/aiohttp#5705]
🐞 **Describe the bug**
We have several microservices running with aiorun and using aiohttp.
After version update we get the following:
aiorun==2020.12.1 and aiohttp==3.6.2 -> works as before
aiorun==2019.4.1 and aiohttp==3.7.4 -> works as before
aiorun==2020.12.1 and aiohttp==3.7.4 -> outgoing requests do not work.

Unfortunately, I cannot get any reason more specific than this trace:
```python-traceback
Traceback (most recent call last):
File "/home/pavka/Documents/console/slayer2/venv/lib64/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore # noqa
File "/usr/lib64/python3.9/asyncio/base_events.py", line 1056, in create_connection
raise exceptions[0]
File "/usr/lib64/python3.9/asyncio/base_events.py", line 1041, in create_connection
sock = await self._connect_sock(
File "/usr/lib64/python3.9/asyncio/base_events.py", line 955, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/lib64/python3.9/asyncio/selector_events.py", line 502, in sock_connect
return await fut
File "/usr/lib64/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8500)
```
In the above instance, it is trying to talk to a local docker container but the same happens when trying to connect to external services:
```python-traceback
Traceback (most recent call last):
File "/home/servicelayer/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore # noqa
File "/usr/local/lib/python3.7/asyncio/base_events.py", line 954, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.7/asyncio/base_events.py", line 941, in create_connection
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
return await fut
File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 494, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.17.11.3', 8500)
```
I raised the issue with the aiorun project and their guess was that something replaces the event loop where the code is running but I have been unable to find anything like that, or to get the code to produce a more descriptive error.

📋 **Your version of the Python**
```console
$ python --version
Python 3.9.4
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.4
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /home/pavka/Documents/console/slayer2/venv/lib/python3.9/site-packages
Requires: chardet, typing-extensions, async-timeout, multidict, attrs, yarl
Required-by: 
```
```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.6
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/pavka/Documents/console/slayer2/venv/lib/python3.9/site-packages
Requires: 
Required-by: yarl, aiohttp
```
```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.3
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/pavka/Documents/console/slayer2/venv/lib/python3.9/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

📋 **Additional context**

We are running services in an endless loop, thus they are wrapped in aiorun.
From aiohttp we only use the client part.

**Comment by Dreamsorcerer** [comment]
I think we'd need an example that reproduces the issue. But, one thing that might be worth checking is whether the `self._loop` in the traceback (in aiohttp) is actually the same loop being used by aiorun. Maybe they have ended up with 2 separate loops somehow.

**Comment by pavka14** [comment]
Unfortunately, our unit tests are a mighty spaghetti tangle and I could not extract a meaningful self-contained example.
What I did though was:
a) load the old version, then
b) start replacing the code piece by piece with the new one until our unit tests break, in order to find the part that makes the difference.
Finally, what I got was this: in connector.py::BaseConnector if you change the close() method to what it was in the previous version (you also need to restore noop2() in helpers.py), it all works.
In other words:

This bit works:
```python
    def close(self) -> Awaitable[None]:
        """Close all opened transports."""
        self._close()
        return _DeprecationWaiter(noop2())
```
where noop2 is:

```python
async def noop2(*args: Any, **kwargs: Any) -> None:
    return
```

and changed like this, it doesn't:
```python
    def close(self) -> Awaitable[None]:
        """Close all opened transports."""
        self._close()
        return _DeprecationWaiter(noop())
```

And yes, it seems it has something to do with changing the event loop because I can see in the debug messages that the connection works and retrieves content from the response, but then the process that raised the task does not get the result.

**Comment by webknjaz** [comment]
> I raised the issue with the aiorun project and their guess

This would be a great place to actually link that issue from here.

**Comment by pavka14** [comment]
> > I raised the issue with the aiorun project and their guess
> 
> This would be a great place to actually link that issue from here.

Yes, sorry: https://github.com/cjrh/aiorun/issues/61

**Comment by cjrh** [comment]
If a loop instance is not supplied, aiorun creates a new one: https://github.com/cjrh/aiorun/blob/master/aiorun.py#L191. That change was made in commit https://github.com/cjrh/aiorun/commit/ba73ee6d4ade7465a5daba4e287c234c5727228c#diff-fc46405ea60bb1998800d16a8ff3c7635d42facaffd496590c07cd5a4f5426ffR174 which was after aiorun==2019.4.1. 

@pavka14 If you can obtain the loop that aiohttp is using, you can provide it to `aiorun.run()`. Alternatively, creating all aiohttp things within an aiorun.run context should also work, e.g. within a coroutine function being run by aiorun, because then aiohttp should pick up that loop. (I assume you're using aiohttp to make client connections, not a server).

**Comment by pavka14** [comment]
Thanks @cjrh - passing the loop explicitly fixed the issue with two of our applications, but am still getting errors with another one. I'll try and follow where the coroutine functions are being created so as to follow your second suggestion.
