### ISSUE TITLE
Such code takes up a lot of memory!

### ISSUE THREAD

**Issue by flyinghu123** [aio-libs/aiohttp#5726]
🐞 **Describe the bug**

I don't need the return value, but Python will still save the Task object.

💡 **To Reproduce**
```python
import asyncio

async def test(sem, i):
    async with sem:
        asyncio.sleep(1)
        print(i)

async def main():
    sem = asyncio.Semaphore(100)
    tasks = []
    for i in range(100000000):
        tasks.append(asyncio.create_task(test(sem, i)))
    await asyncio.gather(*tasks)


if __name__ == "__main__":
    asyncio.run(main())

```

**Comment by Dreamsorcerer** [comment]
How is this a problem with aiohttp? You've not even used the library in the example.

"Python will still save the Task object"
Your code literally saves it explicitly into a list...

**Comment by webknjaz** [comment]
Agreed. This is unrelated to aiohttp. And also the tasks list will get garbage-collected sometime after exit from `main()` but since it's the only thing executed, it may seem that it doesn't get freed until the app is terminated.
