### ISSUE TITLE
WebSocket protocol factory in aiohttp

### ISSUE THREAD

**Issue by ariddell** [aio-libs/aiohttp#574]
Is there a way to use a protocol factory à la Autobahn or SockJS with aiohttp's websockets? Is such a thing part of the goals for aiohttp -- or at this point should one be using something else (like Autobahn)?

For clarity, here's how Autobahn does a websocket with asyncio:

```
from autobahn.asyncio.websocket import WebSocketServerProtocol

class MyServerProtocol(WebSocketServerProtocol):

    def onConnect(self, request):
        print("Client connecting: {}".format(request.peer))

    def onOpen(self):
        print("WebSocket connection open.")

    def onMessage(self, payload, isBinary):
        if isBinary:
            print("Binary message received: {} bytes".format(len(payload)))
        else:
            print("Text message received: {}".format(payload.decode('utf8')))

        # echo back message verbatim
        self.sendMessage(payload, isBinary)

    def onClose(self, wasClean, code, reason):
        print("WebSocket connection closed: {}".format(reason))
```

**Comment by asvetlov** [comment]
SockJS is not websocket but multiprotocol which starts from websocket but may degrade to long-polling etc. 
Please take a look on https://github.com/aio-libs/sockjs

**Comment by ariddell** [comment]
Thanks. I was using sockjs but then I thought I'd make things simpler (and avoid needing a sockjs javascript dependency)  by just using aiohttp's websockets.
