### ISSUE TITLE
'pip install aiohttp[speedups]' installs (deprecated) brotlipy, not Brotli or brotlicffi

### ISSUE THREAD

**Issue by sbaack** [aio-libs/aiohttp#5746]
🐞 **Describe the bug**

I'm a bit confused about these similarly named libraries, but installing `brotlipy` when using `pip install aiohttp[speedups]` def. seems to be wrong considering that [using `brotlipy` is deprecated because it has been renamed to `brotlicffi`](https://github.com/python-hyper/brotlicffi/blob/de7ee050f809448735f0f05a6379383b8cf4554f/HISTORY.rst#080-2020-11-30). According to #3803, `Brotli` should be installed?

BTW, the [docs](https://docs.aiohttp.org/en/stable/index.html) also talk about `brotlipy`, which should be changed to either `Brotli` or `brotlicffi` (whatever is used now).

💡 **To Reproduce**

```bash
python -m venv aiohttp_showcase
source aiohttp_showcase/bin/activate
python -m pip install aiohttp[speedups]
```
This installs `brotlipy`, here is the `pip list` output from a fresh venv:

```
Package           Version
----------------- -----------
aiodns            3.0.0
aiohttp           3.7.4.post0
async-timeout     3.0.1
attrs             21.2.0
brotlipy          0.7.0
cchardet          2.1.7
cffi              1.14.5
chardet           4.0.0
idna              3.1
multidict         5.1.0
pip               21.1.2
pycares           4.0.0
pycparser         2.20
setuptools        57.0.0
typing-extensions 3.10.0.0
wheel             0.36.2
yarl              1.6.3
```

💡 **Expected behavior**

`pip install aiohttp[speedups]` should install either `Brotli` or `brotlicffi` (again, whatever is currenty used).

📋 **Your version of the Python**

```console
$ python --version
Python 3.9.5
```

📋 **Your version of the aiohttp**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.4.post0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /Users/sb/.virtualenvs/aiohttp_showcase/lib/python3.9/site-packages
Requires: yarl, async-timeout, multidict, typing-extensions, attrs, chardet
Required-by:
...
```

**Comment by greshilov** [comment]
Thank you for the report!

Yep, `aiohttp 3.7` requires `brotlipy` according to its `setup.py`. 
https://github.com/aio-libs/aiohttp/blob/184274d9b28bbfa06ac60e48bf286a761c6a6cb0/setup.py#L137-L143

For `aiohttp 3.8` this problem is already solved.
https://github.com/aio-libs/aiohttp/blob/f00b481c55e2c039bdf3d730badde204defe5c59/setup.py#L138-L144

@webknjaz I can create a small fix for the `3.7` branch, but maybe it's time to might as well release `3.8`?

**Comment by webknjaz** [comment]
3.7 is not going to get any updates. I've made one exception to deal with a security bug but that's it, I have no desire to resurrect that stream again.

**Comment by mgorny** [comment]
Is 3.8 going to get any release soon then?

**Comment by webknjaz** [comment]
There's no date set.

**Comment by Rongronggg9** [comment]
@greshilov @webknjaz so the changelog told a lie?

https://github.com/aio-libs/aiohttp/blob/3.7/CHANGES.rst#373-2020-11-18
> 3.7.3 (2020-11-18)
> Features
>
> **Use Brotli instead of brotlipy #3803**
> Made exceptions pickleable. Also changed the repr of some exceptions. #4077

**Comment by Dreamsorcerer** [comment]
> @greshilov @webknjaz so the changelog told a lie?

Apparently, yes: https://github.com/aio-libs/aiohttp/pull/3803#issuecomment-741915328
