### ISSUE TITLE
Confusion with aiohttp

### ISSUE THREAD

**Issue by AeroActuallyDev** [aio-libs/aiohttp#5747]
Hey, in the docs it says ProxyConnector is in 
aiohttp.ProxyConnector
But now i have seen a post saying its embeded in TcpConnector?
How would i use it in this way
connector = ProxyConnector("http://1.1.1.1:1000", proxy_auth=basic_auth)

**Comment by anesabml** [comment]
@AeroActuallyDev `ProxyConnector` has been deprecated and removed. Please check the documentation [here](https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support) on how to connect to a proxy.
