### ISSUE TITLE
how to log the incoming requests and the response

### ISSUE THREAD

**Issue by matrixise** [aio-libs/aiohttp#575]
Hi all,

the web.Application class takes a logger in the constructor, but this one does not seem to work, because in debug mode, there is no message in the logger.

I have read the code of ServerHttpProtocol and we can specify the access_log logger, but this one is just used in the test.

What do you suggest if I want to see the logs ?

Thank you

**Comment by asvetlov** [comment]
What do you expect from logger?
access logs or error reports?

**Comment by matrixise** [comment]
just show the routes with the status code. just when I run the app in debug mode

**Comment by ludovic-gasc** [comment]
Personally, I've no issues to have logs with this config file:
https://github.com/Eyepea/cookiecutter-API-Hour/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/etc/%7B%7Bcookiecutter.app_name%7D%7D/api_hour/logging.ini
And this Web.Application:
https://github.com/Eyepea/cookiecutter-API-Hour/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/__init__.py#L39

**Comment by matrixise** [comment]
Thanks @GMLudo if I specify the logger with make_handler, I have the logs.

Thanks

**Comment by ohsabry** [comment]
@asvetlov is there a way to specify the the logger without calling `make_handler`? If not, what do you recommend as an access logger strategy for a `gunicorn` setup?

**Comment by asvetlov** [comment]
Fixed by #1117
