### ISSUE TITLE
Allow setting an Application's router

### ISSUE THREAD

**Issue by sloria** [aio-libs/aiohttp#577]
`Application.router` is currently a read-only property. It may be useful to be able to set the router.

The use case I am thinking of is a plugin that has a custom router.

``` python
app = web.Application()
setup(app)

# in a plugin
def setup(app):
    app.router = CustomRouter()
```

If you decide to support this, I'd be glad to send a PR.

**Comment by fafhrd91** [comment]
-1, you can pass custom router as `Application` constructor parameter

**Comment by sloria** [comment]
The idea is that a plugin might want to modify the router after an Application has been initialized. This is akin to the `init_app` idiom from flask extensions (http://flask.pocoo.org/docs/0.10/extensiondev/) or the `setup` function that is common in aio-libs (https://github.com/aio-libs/aiohttp_jinja2/blob/master/aiohttp_jinja2/__init__.py#L18).

The example in the OP is contrived. Real setup functions would be more involved.

``` python
def setup(app):
    app[PLUGIN_KEY] = PluginConfig()
    app.router = PluginRouter()
    app.middlewares.append(plugin_middleware)
    #...
```

It would be a bit strange if custom routers had to be special-cased in the above example.

**Comment by asvetlov** [comment]
No, plugin cannot replace router. But it can register new route, middleware and signal.
