### ISSUE TITLE
No requests are logged for some calls and tasks appear to get lost

### ISSUE THREAD

**Issue by gboor** [aio-libs/aiohttp#5791]
🐞 **Describe the bug**

Under heavy load, it appears that some requests get "lost". They execute, but are not logged. This is indirectly messing with the cleanup of the database sessions, as those also get "lost".

💡 **To Reproduce**

Create a simple aiohttp application with a handful of endpoints, stress test them and check the logs; not all calls are logged, even if they are executed in the client.

💡 **Expected behavior**

Calls to be logged and properly disposed

📋 **Logs/tracebacks**

My server uses SQLAlchemy with async and at first I thought it was an issue with SQLAlchemy, so I started logging every aspect of a call to an endpoint with the current_task() as prefix. Here is a call that works properly;

```
Jun 11 15:07:56 Task-871: Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x000001B9DAF34840> checked out from pool
Jun 11 15:07:56 Task-871: BEGIN (implicit)
Jun 11 15:07:56 Task-871: SELECT countries_cities.countries.id, countries_cities.countries.iso2, countries_cities.countries.iso3, countries_cities.countries.name 
FROM countries_cities.countries ORDER BY countries_cities.countries.name
Jun 11 15:07:56 Task-871: [cached since 347.4s ago] ()
Jun 11 15:07:56 Task-871: ROLLBACK
Jun 11 15:07:56 Task-871: Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x000001B9DAF34840> being returned to pool
Jun 11 15:07:56 Task-871: Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x000001B9DAF34840> rollback-on-return
Jun 11 15:07:56 Task-871: Pool size: 20  Connections in pool: 4 Current Overflow: -15 Current Checked out connections: 1
Jun 11 15:07:56 Task-871: 127.0.0.1 [11/Jun/2021:13:07:56 +0000] "GET /countries?include-unknown HTTP/1.1" 200 8329 "http://localhost:8081/?sku=12-5733&vendor_id=12" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/92.0.4512.0 Safari/537.36"
```

You can see that all the processing is done, DB connection etc. and finally it shows the GET request.

Here is the SAME request when it fails;

```
Jun 11 15:07:50 Task-843: Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x000001B9DAEE5F40> checked out from pool
Jun 11 15:07:50 Task-843: BEGIN (implicit)
Jun 11 15:07:50 Task-843: SELECT countries_cities.countries.id, countries_cities.countries.iso2, countries_cities.countries.iso3, countries_cities.countries.name 
FROM countries_cities.countries ORDER BY countries_cities.countries.name
Jun 11 15:07:50 Task-843: [cached since 341.4s ago] ()
Jun 11 15:07:51 Task-843: ROLLBACK
Jun 11 15:07:51 Task-843: Pool size: 20  Connections in pool: 4 Current Overflow: -15 Current Checked out connections: 1
```

As you can see, it stops; the task gets "lost", there is no reporting on the actual GET request, even if everything else was done properly.

I should note that after upgrading aiohttp from 3.7.3 to 3.7.4-post0, this started happening a lot LESS, but it still happens (logs are from 3.7.4-post0).

📋 **Your version of the Python**

```console
$ python --version
Python 3.9.2
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.4.post0
```
```console
$ python -m pip show multidict
Name: multidict
Version: 5.1.0
```
```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.3
```

📋 **Additional context**

Problem occurs on both Windows with raw Python and on Linux when running Dockerized with gunicorn and uvloop, so it seems to be fairly consistent.

Problem also occurs when stress testing without any database connections, those were just good for context. This issue is not all that problematic in itself (some missing logs), but it also means my DB connection teardown fails... which is very problematic.

**Comment by webknjaz** [comment]
I suggest you investigate if it's the client that drops connections. Because in case of dropped connection, aiohttp cancels the handler invoked to process the incoming request.

**Comment by Dreamsorcerer** [comment]
And if it is that, you'll likely need to rethink your DB teardown, using `try: ... except asyncio.CancelledError`, `asyncio.create_task()` or `asyncio.shield()`.

**Comment by gboor** [comment]
I can try doing some more wrapping, but no exceptions are thrown at all and the connection is not dropped; the client gets a full response as expected, the server just doesn't log it and gets lost somewhere after the data is returned.

**Comment by Dreamsorcerer** [comment]
Have you actually tried with a `try: .. except:` or a `try: ... finally:`? A CancelledError is normal operation and does not get output to logs typically.

For example:
```
>>> import asyncio
>>> async def main():
...  try:
...   await asyncio.sleep(20)
...  finally:
...   print("CANCELLED")
... 
>>> async def main2():
...  t = asyncio.create_task(main())
...  await asyncio.sleep(1)
...  t.cancel()
... 
>>> asyncio.run(main2())
CANCELLED
```

**Comment by Dreamsorcerer** [comment]
Essentially, any time you have an `await` keyword, you should be aware that control may return to the event loop, and the task could be cancelled at that point. So, if you have any cleanup code that should always be run even if something gets cancelled, make sure that cleanup code appears in a `finally` block.

**Comment by gboor** [comment]
It was already wrapped in a try/finally, with the DB teardown happening in the finally. Investigating the cancel errors shows that it's more likely the problem is in sqlalchemy. I will investigate that further. Thanks for the tips and if it turns out to be in aiohttp after all, I'll post a new ticket.
