### ISSUE TITLE
[TODO] Finish wiping the attrs usage

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiohttp#5806]
### Describe the bug

Originally, @asvetlov intended to delete any use of `attrs` from aiohttp 4.0+ series via https://github.com/aio-libs/aiohttp/pull/5284. He dropped it from the runtime deps too.

But there are some places that still rely on `attrs` meaning that this will cause failures in runtime because of the missing dep. The tests currently succeed because attrs is listed as a test dep.

One place where it's used is https://github.com/aio-libs/aiohttp/blob/4d58400477331704132cc9427d66699e5815ee25/aiohttp/web_protocol.py#L23.

### To Reproduce

pip install the recent master w/o the test deps and it should fail

### Expected behavior

aiohttp shouldn't rely on deps not declared in the metadata.

### Logs/tracebacks

```python-traceback
N/A
```

### Python Version

```console
$ python --version
```

### aiohttp Version

```console
$ python -m pip show aiohttp
```

### multidict Version

```console
$ python -m pip show multidict
```

### yarl Version

```console
$ python -m pip show yarl
```

### OS

N/A

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
A small side task here would be to add flake8-requirements, which will help ensure we don't have undeclared dependencies.

**Comment by RawatDevanshu** [comment]
> A small side task here would be to add flake8-requirements, which will help ensure we don't have undeclared dependencies.

hey there, im new to git hub and beginner at coding too so.... can you please elaborate, thanks in advance

**Comment by Dreamsorcerer** [comment]
> > A small side task here would be to add flake8-requirements, which will help ensure we don't have undeclared dependencies.
> 
> hey there, im new to git hub and beginner at coding too so.... can you please elaborate, thanks in advance

Well, probably just need to add flake8-requirements to requirements/lint.txt (and add a line in `.flake8` pointing to requirements/base.txt, similar to https://github.com/aio-libs/aiohttp-session/blob/master/.flake8#L23).
But, obviously it will need the attrs stuff removed first, otherwise it will give an error. There could be other things we haven't noticed as well.

**Comment by webknjaz** [comment]
> Well, probably just need to add flake8-requirements to requirements/lint.txt

Nobody should manually edit pin constraint files managed by `pip-tools`. They should instead add direct deps to the corresponding `.in` files and regenerate the pins from that.

**Comment by griels** [comment]
Any reason these haven't been backported to 3.9+?

**Comment by asvetlov** [comment]
It is a backward incompatible change and could break some code potetially.

**Comment by griels** [comment]
OK, thanks - had a quick look at backporting the changes and looked fiddly - do you mean in terms of end user semantics? Would this have to wait for aiohttp 4?

**Comment by asvetlov** [comment]
I mean that attrs types are exported as a part of public API: `MimeType`, `ProxyInfo`, `RouteDef`, `ClientTimeout` etc.
If a user calls, e.g. `attrs.evolve()` to modify client timeout -- the code will be broken; it should be replaced with `dataclasses.replace()`. 
The same if applicable to type checkers.

So yes, this change should wait for 4.0. 
I have no idea when it will happen though.
