### ISSUE TITLE
Ability to trigger server-to-client messaging from local driven events, after websocket connection opened.

### ISSUE THREAD

**Issue by iradization** [aio-libs/aiohttp#5815]
### Is your feature request related to a problem?

I'd like to be able to broadcast the clients about events that were originated locally on the server side. 

### Describe the solution you'd like

I'd like to be able to store the `web.WebSocketResponse()` somewhere it could be used anywhere in the code (to be used in async method of course) 

### Describe alternatives you've considered

This is what i've tried but it didn't work well. I guess it's because signal is not async.

```
#!/usr/bin/python3.7

import signal
import sys
import time
import aiohttp
from aiohttp import web, WSCloseCode
import asyncio


ws = web.WebSocketResponse()

async def websocket_handler(request):
    await ws.prepare(request)
    
    async for msg in ws:
        if msg.type == aiohttp.WSMsgType.TEXT:
            if msg.data == 'close':
                await ws.close()
            else:
                await ws.send_str('some websocket message payload')
        elif msg.type == aiohttp.WSMsgType.ERROR:
            print('ws connection closed with exception %s' % ws.exception())
 
    return ws


def create_runner():
    app = web.Application()
    app.add_routes([
        web.get('/ws', websocket_handler),
    ])
    return web.AppRunner(app)

async def start_server(host="127.0.0.1", port=44444):
    runner = create_runner()
    await runner.setup()
    site = web.TCPSite(runner, host, port)
    await site.start()

async def signal_handler(signal, frame):
    print('You pressed Ctrl+C!')
    ws.send_str("event was created")

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(start_server())
    signal.signal(signal.SIGINT, signal_handler)
    loop.run_forever()


### Related component

Server

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
What if you schedule it to run in the event loop?
```
signal.signal(signal.SIGINT, lambda s, f: asyncio.create_task(signal_handler(s, f)))
```

**Comment by Dreamsorcerer** [comment]
In fact, don't do that. Use the asyncio API for signal handlers:
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.add_signal_handler

Maybe:
```
loop.add_signal_handler(signal.SIGINT, lambda *args: asyncio.create_task(signal_handler(*args)))
```

**Comment by iradization** [comment]
This works great. thank you !

However, in real life, the server mostly need to monitor some filesystem events.  

For example, new version of a file is now available, and the clients need to be notified about it - this event should occur whenever the file is being modified). 

So i've tried calling `loop.add_writer` but it invoke the callback infinitely since it should be triggered whenever the file is available for writing, and I only wanted it to be called upon actual writings to that file. Any idea how it can be done, if possible (haven't  seen anything useful on asyncio-eventloop documentation.) 

thanks again.

**Comment by Dreamsorcerer** [comment]
The documentation for that method says the callback occurs when the file is available for writing, not when it has been modified, that's a totally different usecase.

Don't know if this is exactly what you are looking for, but take a look at https://github.com/samuelcolvin/watchgod.
This is used by aiohttp-devtools to reload the app when you modify your code.

I think we're rather off-topic now though, so I'll close this.
