### ISSUE TITLE
Cannot create connections with verify_ssl=False on OSX

### ISSUE THREAD

**Issue by dudecc** [aio-libs/aiohttp#583]
I found this issue on my laptop which is still running OSX 10.8, but also on someone else's laptop running 10.9.

The issue seems to be [this line](https://github.com/KeepSafe/aiohttp/blob/d65f9be02b810670236f9372012168d595fac05d/aiohttp/connector.py#L452), where we assume unconditionally that ssl has the OP_NO_COMPRESSION attribute whenever we create a connection with verify_ssl=False.  But according to the [ssl docs](https://docs.python.org/3/library/ssl.html#ssl.OP_NO_COMPRESSION), this attribute only exists if the version of libssl backing the ssl module is at least 1.0.0.  But on both of these OSX machines the _ssl extension module is linking in /usr/lib/libssl.0.9.8.dylib, and consequently ssl.OP_NO_COMPRESSION does not exist.

There was already a [workaround](https://github.com/KeepSafe/aiohttp/blob/230bdf30d84fdda03f8285704d09f58bbdc984e5/aiohttp/connector.py#L375) for this in the codebase fairly recently, but it got taken out when python3.3 support was dropped in [this commit](https://github.com/KeepSafe/aiohttp/commit/08cedb82a89ea2ec9a1e1f41b2d71a28b35ca45e#diff-7f25afde79f309e2f8722c26cf1f10adL375).  (For the record I am seeing this problem on 3.4.3.)

**Comment by asvetlov** [comment]
Fixed by 0.18.2 bugfix
