### ISSUE TITLE
Ability to use web.WebSocketResponse() to send file along with some additional info (like filename)

### ISSUE THREAD

**Issue by iradization** [aio-libs/aiohttp#5830]
### Is your feature request related to a problem?

yes, i wish to send to client a file, along with some additional meta-data like file name, md5, etc ... 
currently there's only 2 options for sending `sent_str` and `send_data`, but i need the mixture of both

### Describe the solution you'd like

ability to sent mixed response of data and text.

### Describe alternatives you've considered

I considered sending data and meta-data in 2 separated messages. 

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I think you need to explain your solution. I don't understand how you intend to mix bytes and str together in one call. What would the code look like? And how would the client read it?

**Comment by iradization** [comment]
I was thinking about the following way : 

step 1: create the dictionary : 
```
In [92]: f=open('/tmp/111', 'rb')
In [93]: x=f.read()
In [94]: y=base64.encodebytes(x)
In [95]: d["data"] = y.decode('ascii')
In [96]: d["name"] = "/tmp/111"
```

now we have dictionary : 
```
In [97]: d
Out[97]:
{'name': '/tmp/111',
 'data': 'yv66vgAAAAIBAAAHAAAAAwAAQAABFwXwAAAADgEAAAwAAAAAAReAAAEOp/AAAAAOAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\n'}
```

step 2: convert dictionary to binary string
```
In [98]: j=json.dumps(d)
In [99]: j
Out[99]: '{"name": "/tmp/111", "data": "yv66vgAAAAIBAAAHAAAAAwAAQAABFwXwAAAADgEAAAwAAAAAAReAAAEOp/AAAAAOAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\\n"}'

In [100]: k=j.encode('ascii')
```

now we have binary string which represent both meta-data and data : 

```
In [101]: k
Out[101]: b'{"name": "/tmp/111", "data": "yv66vgAAAAIBAAAHAAAAAwAAQAABFwXwAAAADgEAAAwAAAAAAReAAAEOp/AAAAAOAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\\n"}'
```

The client simply have to reverse it back to regular dictionary. and all this code is better being wrapped in another method like `sent_mixed` or something ...

**Comment by iradization** [comment]
@Dreamsorcerer ,  Do you think my approach can be encapsulated inside a built-in method as part of `web.WebSocketResponse` ?

**Comment by Dreamsorcerer** [comment]
I'm still confused what the proposal is. Your example just converts the bytes to a string. So, why not just pass that dictionary into the `.send_json()` method?

**Comment by iradization** [comment]
Mow that you mention it, I understand there's nothing to add. I can just read this dictionary on client side, read the meta-data fields, and convert the file data base64 format back to it's original binary representation, and that's it. case close :-)
