### ISSUE TITLE
tests/test_formdata.py::test_mark_formdata_as_processed relies on external web server

### ISSUE THREAD

**Issue by derlih** [aio-libs/aiohttp#5840]
### Describe the bug

This test uses http://httpbin.org to send the request. If this server is not responding, the test will fail.
Actually I caught this problem in CI while I was working on a PR. This makes `aiohttp` CI not so reliable.

https://github.com/postmanlabs/httpbin/issues/150#issuecomment-49462515

### To Reproduce

Sometimes it just happen.

### Expected behavior

Use local instance of httpbin or use aiohttp test server if possible.

### Logs/tracebacks

```python-traceback
n/a
```

### Python Version

```console
$ python --version
Python 3.8.5
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 4.0.0a1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /home/dmitry/Sources/aiohttp
Requires: chardet, multidict, async-timeout, yarl, typing-extensions, frozenlist, aiosignal
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/dmitry/Sources/aiohttp/venv/lib/python3.8/site-packages
Requires: 
Required-by: yarl, aiohttp
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.3
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/dmitry/Sources/aiohttp/venv/lib/python3.8/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

ubuntu 20.04
but happen in CI for mac 

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Doesn't look like the test has anything to do with httpbin.org. It just needs to send a post request _somewhere_ twice.

~~Also, it appears the original commit raises a RuntimeError, when it should probably raise some kind of client error, and in fact the change file says it raises a ClientPayloadError...~~
Nevermind: https://github.com/aio-libs/aiohttp/pull/4351#discussion_r347149791

https://github.com/aio-libs/aiohttp/commit/02735353dfdca0729d6f8c2b756437363e8de309

**Comment by derlih** [comment]
https://github.com/aio-libs/aiohttp/blob/d55728da7486e0295a11bf2378a2eceb8fe39c64/tests/test_formdata.py#L91-L101
I think so too. IMO it would be better to use aiohttp server instead.
