### ISSUE TITLE
Download speed cannot be over a specific rate when concurrency number is over 9

### ISSUE THREAD

**Issue by meow-watermelon** [aio-libs/aiohttp#5846]
### Describe the bug

I have a HTTP client to download data. I noticed that when the concurrency number is less than 9, the total download speed rate is the same as what curl does with the same number of processes running, However, when the concurrency number is over 9, aiohttp client cannot over a specific speed rate, in my case it's ~115MB/sec. The client and server hosts are both using 10G NIC. 

I did use aiofiles to write data to /dev/null. And curl is also writing data to /dev/null. Here's the [code snippet](https://github.com/meow-watermelon/http_benchmarker/blob/main/http_benchmarker.py#L31-L38) that how my client is downloading data.

In summary, even I specify the concurrency number to 20, the total download speed is still at ~115MB/sec. But if I triggered 20 curl processes in parallel, I can see the total download speed is at linear speed easily. Both aiohttp and curl testing are within NIC bandwidth, no ethernet frame drop or errors.

### To Reproduce

1. Run 20 curl command to download the same large file(e.g. 1GB) to /dev/null in parallel. Simply using bash `for` loop to run those 20 curl commands background.
2. Run the HTTP client [here](https://github.com/meow-watermelon/http_benchmarker/blob/main/http_benchmarker.py) to download the same file with the concurrency number 20.
3. Compare both ethernet I/O usage. The curl example would show linear speed, but aiohttp client just shows ~115MB/sec ethernet IO usage. 

### Expected behavior

I would expect what the download speed should be in linear when I bump up the concurrency number in aiohttp client, it should not be fixed at a specific speed.

### Logs/tracebacks

```python-traceback
N/A
```

### Python Version

```console
$ python --version
Python 3.8.6
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.7.4
```

### multidict Version

```console
$ python -m pip show multidict
5.1.0
```

### yarl Version

```console
$ python -m pip show yarl
1.6.3
```

### OS

RHEL 7

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by derlih** [comment]
Hi @meow-watermelon ,
For me it looks like you've hit the data limit of how much data a single core can process. 
Your benchmark is single-threaded. But when you run 20 instances of `curl` it means they can use 20+ threads to process the data.

**Comment by meow-watermelon** [comment]
Hi @derlih,

Thanks for your reply. I think your theory is correct. Do you think this behavior should be noted in the aiohttp documentation? I don't think I'm the only person who encounters this issue. But I can hardly find the answer when I search on the web.

Thank you again.

**Comment by Dreamsorcerer** [comment]
If you can see your CPU (core) is running at 100%, that should be the hint. It doesn't seem like something specific to aiohttp, you're just using all the CPU resources available.

Obviously, if you want to go faster, figure out a way to utilise multiprocessing:
https://docs.python.org/3/library/multiprocessing.html

**Comment by meow-watermelon** [comment]
Thanks @Dreamsorcerer. Yes, it's not about aiohttp and I do see the CPU core is pegged when downloading data. I will close this request as it's been answered properly. 

Thanks.
