### ISSUE TITLE
Use pytest-xdist?

### ISSUE THREAD

**Issue by AustinScola** [aio-libs/aiohttp#5849]
### Is your feature request related to a problem?

While developing #5847, I noticed that the pytests were taking quite a while to run on my machine (which is a pretty weak old desktop).

### Describe the solution you'd like

I thought that one easy way to speed up the testing time would be parallelization. I gave using [`pytest-xdist`](https://pypi.org/project/pytest-xdist/) a quick try and it cut the execution time from around ~4 minutes to ~1.5 minutes. And somewhat surprisingly all the tests passed

The only changes I made were the following:
- Add `pytest-xdist==2.3.0` to `requirements/test.txt`
- Run the `pip-compile` command
- Re-build and activate the venv
- Add the flag `-n auto` to the test command in the Makefile

Then I ran `make test`.

### Describe alternatives you've considered

- Do nothing
- Use `pytest-parallel`

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by derlih** [comment]
Hi @AustinScola ,
4 mins is too long, but 1.5 is long as well. To reduce this time during development I usually run only related tests. Usually they are localized in a single file. And only before commit I run full test suite.
For example you can run all tests from a `test_test_utils.py` with `pytest tests/test_test_utils.py`.
It really speeds up the dev time.

I hope that all our tests are independent so it should be possible to run them in parallel. But I would prefer to add another target in Makefile to do so and leave `make test` as it is. For CI I would also stick to sequential run.

**Comment by AustinScola** [comment]
Hi @derlih, I agree that 1.5 mins is still too long. I suspect the speedup would be better on a more powerful machine than mine.

Thanks for the suggestion about running tests for just one file. When changing more than a few files though that technique becomes un-fun.

Can you explain why you think it would be better to add a new target rather than change the `test` target? Do you think the parallelization is likely to be flaky?

**Comment by derlih** [comment]
To not to break the existing behavior.
Parallel tests can have side effects that can cause the failure of the suite.
Also `test` target from the Makefile is used by other targets.
May be introducing a new target like `xtest` would allow developers to use faster suite run w/o affecting other parts. What do you think?

**Comment by AustinScola** [comment]
I think an `xtest` target would be useful right now and if the parallelization turns out to be really safe then maybe it could be made the default down the road or if it turns out to be unsafe or not worth the cost then it can be gotten rid of.

**Comment by webknjaz** [comment]
I've added some feedback in the related PR @ https://github.com/aio-libs/aiohttp/pull/5852#pullrequestreview-699338507. Let's move any further discussion there.

**Comment by webknjaz** [comment]
xref #5431
