### ISSUE TITLE
Cleanup Context type alias

### ISSUE THREAD

**Issue by AustinScola** [aio-libs/aiohttp#5883]
### Is your feature request related to a problem?

When typing an application, there is no type alias for a cleanup context available for users to use.

### Describe the solution you'd like

Add a type alias `CleanupContext` to `aiohttp.typedefs`:

```python3
CleanupContext = Callable[[Application], AsyncIterator[None]]
```

### Describe alternatives you've considered

- Define it myself in my code.
- Don't bother typing it

### Related component

Server

### Additional context

This is similar to #5842 which was addressed in #5847.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
What's an example of when this would be used?

**Comment by AustinScola** [comment]
Here is an example of how a user might use this:

```Python3
from typing import List

from aiohttp.web import Application

from server.contexts.database_client import database_client_context
from server.contexts.web_client import web_client_context

app = Application()

contexts: List[CleanupContext] = [database_client_context, web_client_context]
for context in contexts:
    app.cleanup_ctx.append(context)

```

**Comment by AustinScola** [comment]
It could also be used internally in `aiohttp`.

**Comment by Dreamsorcerer** [comment]
Seems reasonable enough. I've added it to #4686. Feel free to make a PR (also, one for Middleware if you fancy closing out that issue).

**Comment by AustinScola** [comment]
Will do.
