### ISSUE TITLE
RouteDef kwargs default value

### ISSUE THREAD

**Issue by AustinScola** [aio-libs/aiohttp#5884]
### Is your feature request related to a problem?

This is just a very minor inconvenience not a problem. When defining `aiohttp.web.RouteDef`'s the `kwargs` argument is required:

Example:
```python3
RouteDef('GET', '/api/status', get_status, kwargs={})  # requires "kwargs={}"
```

This is because `kwargs` field of the `dataclass` does not have a default:

https://github.com/aio-libs/aiohttp/blob/8c5bb416a20c3febb9b8e4a6af458b9d74cdb5ef/aiohttp/web_routedef.py#L57-L62

### Describe the solution you'd like

Define `aiohttp.web.RouteDef.kwargs` with the value of `field(default_factory=dict)`.

```python3
@dataclasses.dataclass(frozen=True, repr=False)
class RouteDef(AbstractRouteDef):
    method: str
    path: str
    handler: _HandlerType
    kwargs: Dict[str, Any] = field(default_factory=dict)
```

There are probably other places that similar changes could be made.

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by asvetlov** [comment]
Why do you instantiate `RouteDef` in your code?

`aiohttp.web.route()` factory should be used instead
