### ISSUE TITLE
Add new docs markup for asyncio syntax

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#589]
Half year ago I've added simple sphinx plugin for `coroutinemethod` and `coroutinefunction` support (borrowed from CPython repo, @haypo is initial author IIRC).
The code is https://github.com/KeepSafe/aiohttp/blob/master/docs/aiohttp_doctools.py

Now I feel the need for yet another markup.

For example `aiohttp.ClientSession.get` (regular function) returns an object https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L431-L481 which can be used both as coroutine and async context manager:

```
resp = yield from client.get(addr)
resp = await client.get(addr)
async with client.get(addr) as resp:
     ...
```

How the sphinx directive for `get` should be named? 
Just `.. coroutinemethod::` is not enough.

@1st1 @haypo do you have any idea?

**Comment by kxepal** [comment]
> aiohttp.ClientSession.get (regular function) returns an object which can be used both as coroutine and async context manager

Imho, that's the answer:

```
.. method:: get

    ...
    :returns: :class:`_BaseRequestContextManager`

.. class:: _BaseRequestContextManager

  Can be used as coroutine or async context manager.
```

Not such cool that you want, but that's how things are set in real.

Alternatively, you can introduce not directives, but plain bool options for the directive `method` like:

```
.. method:: get
  :coroutine:
  :async-context-manager:
```

And use them to generate proper method signature. Requires more hacking into sphinx, but imho that's the only way to describe such many roles that plays this(and similar) method.

**Comment by asvetlov** [comment]
@kxepal I don't want to introduce `_BaseRequestContextManager` as part of public API.
The helper should be hidden for end user IMHO.

Would you elaborate the second approach?
How can I implement this and (mostly important) how it will be displayed for end user in our docs?

**Comment by kxepal** [comment]
> How can I implement this and (mostly important) 

IIRC, first need to find ObjectDescription for methods, there is option_spec which holds list of allowed options. The displayed name builds in handle_signature method (at least for httpdomain, which I know better) of the same object - just need to process these options there and tweak fullname attribute of signode.

I'm not familiar with pythondomain, so things may be a bit different and complicated, but idea should be still the same. But unlikely you can teach autodoc for the same trick.

> how it will be displayed for end user in our docs?

How would you like. You can make it as: 

```
coroutine context-manager get(url, *, allow_redirects=True, **kwargs)
```

or stay with default options rendering:

```
get(url, *, allow_redirects=True, **kwargs)
    coroutine
    context manager
```

**Comment by asvetlov** [comment]
Fixed
