### ISSUE TITLE
Why the usual import "import aiohttp" causes a 30 MiB increase in RAM

### ISSUE THREAD

**Issue by masksshow** [aio-libs/aiohttp#5891]
### Describe the bug

Hello.

Why the usual import "import aiohttp" causes a 10-15 MB increase in RAM. This is critical for me.
I have implemented several projects using the aiohttp client. I've always used docker.
1.What is it connected with?
2. Is it possible to reduce the consumption of RAM.

### To Reproduce
```python
from time import sleep

import aiohttp

sleep(200)
```

### Expected behavior

Simple imports shouldn't cause such memory consumption.

### Logs/tracebacks

```python-traceback
CONTAINER ID   NAME                   CPU %     MEM USAGE / LIMIT     MEM %     NET I/O       BLOCK I/O     PIDS
66f2348bb8f2   app_1     0.00%     30.32MiB
```

### Python Version

```console
$ python --version
python:3.9
```

### aiohttp Version

```console
$ python -m pip show aiohttp
aiohttp==3.7.3
```

### multidict Version

```console
$ python -m pip show multidict
```

### yarl Version

```console
$ python -m pip show yarl
```

### OS

python:3.9-slim

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
Duplicate of https://github.com/aio-libs/aiohttp/discussions/5889.
