### ISSUE TITLE
ServerHttpProtocol handle_request exception handling

### ISSUE THREAD

**Issue by fgasperino** [aio-libs/aiohttp#59]
ServerHttpProtocol.handle_request does not honor the handled exception's message member variable.
# 

--- ../../../lib/python3.4/site-packages/aiohttp/server.py  (revision )
+++ ../../../lib/python3.4/site-packages/aiohttp/server.py  (revision )
@@ -192,9 +192,9 @@
                 self.log_debug('Ignored premature client disconnection.')
                 break
             except errors.HttpException as exc:
-                self.handle_error(exc.code, message, None, exc, exc.headers)
-                self.handle_error(exc.code, message if not exc.message else exc.message, None, exc, exc.headers)
           except Exception as exc:
-                self.handle_error(500, message, None, exc)
-                self.handle_error(500, message if not exc.message else exc.message, None, exc)
           finally:
               if reader.output and not reader.output.at_eof():
                   self.log_debug('Uncompleted request.')

**Comment by binhnq94** [comment]
I have same problem.
example code:

``` python
def handle_errors(func):
    def wrapped(request):
        data = {}
        try:
            data = func(request)
        except Exception as e:
            print('Pha 1: %s', e)
            data = {
                'status': False,
                'error_message': str(e)
            }
            data = web.Response(body=json.dumps(data).encode('utf-8'))
        finally:
            return data
    return wrapped

@handle_errors
def index(request):
    raise ExceptionError('error')
```

my server dont return data = { 'status': False,'error_message': str(e)}.
it response 500 Internal Server Error.

**Comment by asvetlov** [comment]
Surprisingly your code works as expected after I've added application startup procedure to it.
