### ISSUE TITLE
resolver.py/ThreadResolver: address[3] does not exist

### ISSUE THREAD

**Issue by dilyanpalauzov** [aio-libs/aiohttp#5901]
### Describe the bug

As outlined at https://github.com/pimutils/vdirsyncer/issues/916, I use python 3.8 with aiohttp 3.8 branch (v3.7.4.post0-209-g22f8be99) .  In aiohttp/resolver.py:ThreadedResolver the line
>    if family == socket.AF_INET6 and address[3]:  # type: ignore[misc]

fails, as address has only two elements and address[3] is out of range.

The values of adress are:
> AddressFamily.AF_INET ('142.250.185.238', 443)
> AddressFamily.AF_INET6 (10, b'\x01\xbb\x00\x00\x00\x00*\x00\x14P@\x01\x08\x13')

The system is not connected to IPv6, no routes, no iPv6 addressese etc, but the kernel understands IPv6.  I fixed it locally with:
```diff
diff --git a/aiohttp/resolver.py b/aiohttp/resolver.py
index 2161c8fa..4e57b319 100644
--- a/aiohttp/resolver.py
+++ b/aiohttp/resolver.py
@@ -38,16 +38,7 @@ class ThreadedResolver(AbstractResolver):
 
         hosts = []
         for family, _, proto, _, address in infos:
-            if family == socket.AF_INET6 and address[3]:  # type: ignore[misc]
-                # This is essential for link-local IPv6 addresses.
-                # LL IPv6 is a VERY rare case. Strictly speaking, we should use
-                # getnameinfo() unconditionally, but performance makes sense.
-                host, _port = socket.getnameinfo(
-                    address, socket.NI_NUMERICHOST | socket.NI_NUMERICSERV
-                )
-                port = int(_port)
-            else:
-                host, port = address[:2]
+            host, port = address[:2]
             hosts.append(
                 {
                     "hostname": hostname,
```

### To Reproduce

See above.

### Expected behavior

Shall not read address[3], when address[3] does not exist.

### Logs/tracebacks

```python-traceback
Not applicable.
```

### Python Version

```console
$ python --version

Python 3.8.8+
```

### aiohttp Version

```console
$ python -m pip show aiohttp

3.8.0a0
```

### multidict Version

```console
$ python -m pip show multidict
5.1.0
```

### yarl Version

```console
$ python -m pip show yarl

1.6.3
```

### OS

Linux from Scratch, python 3.8.8+

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Hanaasagi** [comment]
`resolve` use the `getaddrinfo` to get the socket infomation.

https://github.com/aio-libs/aiohttp/blob/60f57272ab1ac230b2e5a3c8eca9f3ccf9c24252/aiohttp/resolver.py#L27-L39

From the Python doc, the `sockaddr` part of  `getaddrinfo` function' return value is a 4-tuple if the family is `AF_INET6`. 


> The function returns a list of 5-tuples with the following structure:
> 
> (family, type, proto, canonname, sockaddr)
> 
> In these tuples, family, type, proto are all integers and are meant to be passed to the socket() function. canonname will be a string representing the canonical name of the host if AI_CANONNAME is part of the flags argument; else canonname will be empty. sockaddr is a tuple describing a socket address, whose format depends on the returned family (a (address, port) 2-tuple for AF_INET, a (address, port, flow info, scope id) 4-tuple for AF_INET6), and is meant to be passed to the socket.connect() method.

The behavior is strange, not as stated in the doc. :confused:

Ref: https://docs.python.org/3.8/library/socket.html#socket.getaddrinfo

**Comment by webknjaz** [comment]
> The behavior is strange, not as stated in the doc.

IIRC, it returns the structure from the underlying kernel syscall. FWIW I think this has been fixed by https://github.com/aio-libs/aiohttp/pull/5176 on `master`, `3.8` and `3.7`.

**Comment by webknjaz** [comment]
Duplicate of https://github.com/aio-libs/aiohttp/issues/5156. Please post any other observations or/and a reproducer there.
