### ISSUE TITLE
Prioritize exact matches over regex matches

### ISSUE THREAD

**Issue by PythonCoderAS** [aio-libs/aiohttp#5926]
### Is your feature request related to a problem?

My feature request has to deal with the problem of a regex route overriding my exact routes. I have a generic route to `/commands/{command:.+}`, but I also want a specific route to `/commands/create`. However, aiohttp will always choose the latter, and so the handler for the generic route needs to check for the latter URL and then call the appropriate handler.

### Describe the solution you'd like

I would like it to be possible for handlers to have a priority, determined by exact match or the number of slashes. Therefore, an exact match would get top priority, and a handler for a subdirectory would get the second-highest priority.

### Describe alternatives you've considered

I have considered n alternative where we can manually set the priority ourselves.

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by asvetlov** [comment]
aiohttp router has a different design: routes are tested in the same order as they were registered.
If you want to prioritize exact matches over regexes -- just register exact routes first.
