### ISSUE TITLE
Add request.handler (access current handler function from request)

### ISSUE THREAD

**Issue by sloria** [aio-libs/aiohttp#597]
Proposal: Add a read-only `handler` property to `aiohttp.web.Request`.

Example use case: I have a content negotiation plugin which may render responses to JSON or HTML. "Renderers" receive a `request` and `data`. The HTML renderer needs to read a value saved to the handler function's `__dict__` attribute.

``` python
class RouterWithTemplating(web.UrlDispatcher):
    def add_route(self, method, path, handler, template: str=None, **kwargs):
        if template:
            handler.__dict__['template'] = template
        super().add_route(method, path, handler, **kwargs)

def render_mako(request, data):
    template_name = request.handler.__dict__.get('template', None)
    #... render template_name

app = web.Application(router=RouterWithTemplating())
negotiation.setup(app, renderers={
    'application/json': render_json,
    'text/html': render_mako,
})
app.router.add_route('GET', '/', index, template='index.html')
```

The workaround is to have the negotiation middleware pass the handler function to renderers, so the signature becomes

``` python
def render_mako(request, data, handler):
```

However, one of my favorite things about aiohttp is that `request` objects typically contain everything you need to produce a response. I think adding `handler` would complete the picture.

Thoughts? 

By the way, if there is a better way to meet the above use case, I am open to feedback.

**Comment by asvetlov** [comment]
Time machine is here.
Try `request.match_info.handler`

**Comment by sloria** [comment]
Exactly what I needed. Thanks!
