### ISSUE TITLE
Custom 404 response

### ISSUE THREAD

**Issue by luhn** [aio-libs/aiohttp#598]
Perhaps I'm missing something, but there doesn't seem to be a way of customizing the 404 page except for writing your own router.

To clarify, I understand that you can customize manually raised 404s by using middlewares.  I'm talking about a 404 triggered when the router cannot resolve a URL to a handler.

**Comment by luhn** [comment]
I retract this issue; I'm completely wrong on this.  You can indeed use middlewares.  I don't why I thought you couldn't.

**Comment by luhn** [comment]
Although it could be good to document how to do this.  Also, include simple middleware in aiohttp for handling this.  Is this a contribution you'd be interested in?

**Comment by asvetlov** [comment]
Yes, I'm interesting in docs contributions written by users and describing their problems.
As library author a don't always understand weak places in documentation.
