### ISSUE TITLE
Possibility to append to default User-Agent

### ISSUE THREAD

**Issue by scop** [aio-libs/aiohttp#5986]
### Describe the solution you'd like

The autogenerated default User-Agent header is nice, but I'd like to add my client implementation details to it.

Making the default user agent string part of the documented API would be one way I could reuse the default and trust that it's going to stay available.

### Describe alternatives you've considered

I could do away with setting it in ClientSession headers, and using `aiohttp.http.SERVER_SOFTWARE` as the basis, but `aiohttp.http.SERVER_SOFTWARE` doesn't sound like it's part of the aiohttp API and I'm not sure if I should be accessing it.

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by scop** [comment]
#5987 contains an example implementation. I also realised that there's no natural place to actually document these (as in "part of the documented API" I mentioned), but perhaps they're "more part of it", easier to discover, and less likely to go away even without docs when done this way.

**Comment by asvetlov** [comment]
Please consider these constants as *implementation details*.
If you want to override User-Agent -- do it from scratch, for example by setting the default User-Agent header in `ClientSession` constructor.

**Comment by scop** [comment]
I can of course override it from the scratch. But the underlying aiohttp version might be significant as well, and currently there's no clean way to include that, too. So one has to pick and choose, which is not good.

**Comment by Dreamsorcerer** [comment]
> But the underlying aiohttp version might be significant as well, and currently there's no clean way to include that, too.

`aiohttp.__version__`?

**Comment by scop** [comment]
I don't see anything in the docs that would make `aiohttp.__version__` usage any more allowable than `aiohttp.http.SERVER_SOFTWARE`, so in that sense they're no different. On the other hand the former is just the version, whereas the latter is the complete user agent string (currently) which is what I was looking for here.

**Comment by Dreamsorcerer** [comment]
> I don't see anything in the docs that would make `aiohttp.__version__` usage any more allowable

It's a standardised approach to including the version number in libraries. It appears in PEP 8, for example, and is used by a large number of libraries.

> On the other hand the former is just the version, whereas the latter is the complete user agent string (currently) which is what I was looking for here.

I guess we're just struggling to understand the use case here. What use case makes it important to use the default user agent, but at the same time need a custom user agent by modifying that? Normally, the default user agent is used because a developer doesn't care, or a custom user agent is used to identify their program or impersonate a browser. I've never seen a case where someone wants to tweak the default user agent string, it doesn't seem useful.

**Comment by asvetlov** [comment]
Feel free to import this constant on your own risk. The forward compatibility is not guaranteed (but in practice I expect that this sources part  will not be changed often). Or just copy-paste, this is another option :)
