### ISSUE TITLE
Forbid duplicating of web.Application and web.Request 

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#602]
I've found both Application and Request has `.copy()` method with unpredictable behavior.
We should forbid this one.

There are two options:
1. Don't inherit web.Application and web.Request from dict but implement `MutableMapping` abc from scratch.
2. Override `.copy` with raising `NotImplementedErrorr` exception.

I'm inclining to second choice.

The patch is trivial but requires two additional tests in our suite and docs change.

Any volunteers?

**Comment by jashandeep-sohi** [comment]
I'll make a PR with option 2.

**Comment by asvetlov** [comment]
Thanks
