### ISSUE TITLE
Update docs with python 3.3 support info.

### ISSUE THREAD

**Issue by popravich** [aio-libs/aiohttp#605]
I think we need to add a section in docs providing info on python 3.3~3.4.1 support and restrictions
as many libraries have been using `aiohttp` since very begining and it might be inconvinient when
people do (pip) upgrade and end with not working projects.

The docs section must state what `aiohttp` version support python 3.3 -- 3.4.0 and why.
So users can freeze their dependencies.

**Comment by popravich** [comment]
I just noticed that LTS Ubuntu (14.04.3) has python 3.4.3.

**Comment by asvetlov** [comment]
@popravich would you provide a patch?

**Comment by popravich** [comment]
Sure
