### ISSUE TITLE
undefined symbol '_PyGen_Send' for py3.10

### ISSUE THREAD

**Issue by sandeep-gh** [aio-libs/aiohttp#6089]
### Describe the bug

I have compiled aiohttp (from github) with latest cython. On runs I get error: 
```
python3:/home/kabira/DrivingRange/asyncweb/py310async/lib/python3.10/site-packages/aiohttp-3.7.4.post0-py3.10-openbsd-7.0-arm64.egg/aiohttp/_http_parser.cpython-310.so: undefined symbol '_PyGen_Send'
```

As I understand this was issue was patched and fixed. 

### To Reproduce

Download and install latest cython.
Download and install latest aiohttp.
Run any example code. 

### Expected behavior

Aiohttp code should not refer to _PyGen_Send (I think).

### Logs/tracebacks

```python-traceback
not applicable
```

### Python Version

```console
Python 3.10.0
```

### aiohttp Version

```console
Name: aiohttp
Version: 3.7.4.post0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /home/kabira/DrivingRange/asyncweb/py310async/lib/python3.10/site-packages/aiohttp-3.7.4.post0-py3.10-openbsd-7.0-arm64.egg
Requires: async_timeout, attrs, chardet, multidict, typing_extensions, yarl
Required-by:
```

### multidict Version

```console
Name: multidict
Version: 5.2.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/kabira/DrivingRange/asyncweb/py310async/lib/python3.10/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
Name: yarl
Version: 1.7.0
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/kabira/DrivingRange/asyncweb/py310async/lib/python3.10/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

OpenBSD

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
> I have compiled aiohttp (from github) with latest cython.

I don't have any familiarity with this, but I notice the version in your output is 3.7.4.post0. Are you compiling from the 3.8 branch on Github? 3.7 is known to be broken with python 3.10 anyway.

**Comment by sandeep-gh** [comment]
I was compiling from the master branch . Let me try 3.8  branch. Not sure why the version output is 3.7.4

**Comment by asvetlov** [comment]
C sources should be regenerated by fresh cython to avoid the issue.
Already fixed on github
