### ISSUE TITLE
Proxy authentication when connecting to https host does not working

### ISSUE THREAD

**Issue by ssbb** [aio-libs/aiohttp#617]
Hi!

I have my own proxy server which support both HTTP/HTTPS with authentication and works fine with `requests`/`urllib.request`. But with aiohttp `ProxyConnector` I got 407 error when trying to load HTTPS page via GET request (everything is okay with HTTP).

**Comment by ssbb** [comment]
Why it can happens and maybe I can tune my proxy servers (TOR + Polipo + HAProxy) for make it work? Thanks :)

**Comment by ssbb** [comment]
@asvetlov  It works for me with this change: https://github.com/ssbb/aiohttp/blob/master/aiohttp/connector.py#L660 (sorry, just have few typo commits, so it will be easy to read just code instead of commit).

But I am not sure if it's a right solution. Can someone confirm?

**Comment by ssbb** [comment]
Also I got this warning for each opened connection when using ssl proxies:

`Unclosed response
client_response: <ClientResponse(http://********/) [200 Tunnel established]>
<_CIMultiDictProxy()>`

**Comment by asvetlov** [comment]
Hi. I have notification about broken ssl proxy from private source.
Will check your patch soon.

**Comment by Eijebong** [comment]
Same problem here.

**Comment by asvetlov** [comment]
Fixed
