### ISSUE TITLE
Path component in url constructed by Route.url() is not quoted

### ISSUE THREAD

**Issue by mfya** [aio-libs/aiohttp#623]
The url returned by StaticRoute.url() and DynamicRoute.url() can not be properly split, if the parameters contain reserved chars. 
I'm not sure if this is intended, but considering that the query is urlencoded, it appears to be inconsistent and may render the result useless unless the caller always performs additional steps.

``` python
>>> urllib.parse.urlparse(route.url(filename='te st?x&y#z', query={'a':'b&c'}))
ParseResult(scheme='', netloc='', path='/static/te st', params='', query='x&y', fragment='z?a=b%26c')
>>> urllib.parse.urlparse(route.url(filename=urllib.parse.quote('te st?x&y#z'), query={'a':'b&c'}))
ParseResult(scheme='', netloc='', path='/static/te%20st%3Fx%26y%23z', params='', query='a=b%26c', fragment='')
```

Adding calls to [urllib.parse.quote](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote) before joining the path and the urlencoded query should fix this.

**Comment by asvetlov** [comment]
I feel your need but have no strong opinion how to do it.
Say, for URL matching we have two parameters: `path` and `raw_path`.
Maybe adding `.raw_url()` makes sense also?
Need to sleep on it anyway.

**Comment by asvetlov** [comment]
Fixed by introducing `url_for()` returning YARL instance.
