### ISSUE TITLE
0.19.0 release

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#625]
There is no need to rush but I want to make 0.19 release in the end of November or begin of December.

Personally I have no specific issues which should be ultimately implemented in 0.19 and inclined to publish release on time expiration basis.

We have 17 closed issues now, I believe we will get even more in three weeks.

Please add showstoppers as comments if you have any.

**Comment by fafhrd91** [comment]
+1

**Comment by auvipy** [comment]
++1 go with it

**Comment by asvetlov** [comment]
I'll make the release next week

**Comment by asvetlov** [comment]
Released

**Comment by auvipy** [comment]
awesome
