### ISSUE TITLE
Make UrlDispatcher.routes() return Sequence

### ISSUE THREAD

**Issue by rutsky** [aio-libs/aiohttp#627]
Currently [routes()](https://aiohttp.readthedocs.org/en/stable/web_reference.html#aiohttp.web.UrlDispatcher.routes) returns limited subset of Sequence operations:

```
class RoutesView(Sized, Iterable, Container):
```

I propose to support `Sequence` interface, which includes `Sized`, `Iterable`, `Container`, and adds some list-like methods (indexing, `count()`, support for reversed protocol).

Personally I need this for indexing: I need to make copy of a list of all currently added routes and instead of

```
for route in app.router.routes()[:]:
    # Here new routes will be added
    ...
```

as done usually with sequences, currently I forced to explicitly build list:

```
for route in list(app.router.routes()):
    ...
```

**Comment by asvetlov** [comment]
I intentionally did not support indexing because did not see a use case for accessing a route by ordinal number.

Please elaborate why do you need this?

**Comment by rutsky** [comment]
> Please elaborate why do you need this? 

I need this to make copying in slice-style work (`app.router.routes()[:]`).

> I intentionally did not support indexing because did not see a use case for accessing a route by ordinal number.

Looking from this point of view I don't see reason to have indexing either.
And copying using slicing is actually a hack for less typing.

You convinced me that there is no need to support `Sequence` on routes, at least until reasonable example will be introduced. So I'm closing this issue.
