### ISSUE TITLE
Export a method to clear the cache

### ISSUE THREAD

**Issue by smurfix** [aio-libs/aiohttp#636]
Please export a method to clear the connection cache, i.e. close all cached connections.

Otherwise Python 3.5 will spew not-so-nice ResourceWarning messages.

**Comment by asvetlov** [comment]
What part are you talking about: client or server side?

**Comment by smurfix** [comment]
Client.

## 

-- Matthias Urlichs

**Comment by asvetlov** [comment]
RTFM: http://aiohttp.readthedocs.org/en/stable/client.html#releasing-response

`ClientSession.close()` can be useful also.
