### ISSUE TITLE
Curio?

### ISSUE THREAD

**Issue by jab** [aio-libs/aiohttp#639]
Dave Beazley recently released an alternative coroutine library for Python 3.5+ that looks super interesting: http://curio.readthedocs.org/

I'm guessing aiohttp is only interested in staying tied to asyncio (and supporting 3.4+) for greatest interoperability, but I was just wondering what the aiohttp developers thought of this alternative library / would ever wish aiohttp could switch to it.

**Comment by jab** [comment]
(https://www.youtube.com/watch?v=lYe8W04ERnY was also super cool)

**Comment by asvetlov** [comment]
I think ship has sailed.
