### ISSUE TITLE
[Security] Workflow update-pre-commit.yml is using vulnerable action py-actions/py-dependency-install

### ISSUE THREAD

**Issue by Ale0x78ButInBinary** [aio-libs/aiohttp#6435]
The workflow update-pre-commit.yml is referencing action py-actions/py-dependency-install using references v2. However this reference is missing the commit [5df6847b1bc7e7eff410a6d05aab1708d592de20](https://github.com/py-actions/py-dependency-install/commits/5df6847b1bc7e7eff410a6d05aab1708d592de20) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by Dreamsorcerer** [comment]
Looks to me like it was already updated 5 days ago...
https://github.com/aio-libs/aiohttp/blame/master/.github/workflows/update-pre-commit.yml#L16
