### ISSUE TITLE
Index out of range in create_wsgi_environ

### ISSUE THREAD

**Issue by alex-kaufman** [aio-libs/aiohttp#653]
Gunicorn version 19.4.1
aiohttp version 0.19.0
nginx 1.4.6
Ubuntu 14.04

> [2015-12-03 13:24:27 -0500] [12308] [ERROR] Error handling request
> Traceback (most recent call last):
> File "/home/vagrant/.virtualenvs/mighty/lib/python3.4/site-packages/aiohttp/server.py", line 262, in start
>    yield from self.handle_request(message, payload)
>  File "/home/vagrant/.virtualenvs/mighty/lib/python3.4/site-packages/aiohttp/wsgi.py", line 127, in handle_request
>    environ = self.create_wsgi_environ(message, payload)
>  File "/home/vagrant/.virtualenvs/mighty/lib/python3.4/site-packages/aiohttp/wsgi.py", line 93, in     create_wsgi_environ
>    environ['REMOTE_ADDR'] = remote[0]
> IndexError: index out of range

This change occurred in between the two releases https://github.com/KeepSafe/aiohttp/commit/d904071c30737baa7189ed1c842c76954274c129#diff-58081209a1b73c318d74d4fe7ad41460L91
to 
https://github.com/KeepSafe/aiohttp/commit/eb54e6c010f55c02e49a36cb2e74b077f8aa77e4#diff-58081209a1b73c318d74d4fe7ad41460R92
which may be related to the issue

This gunicorn issue from June 2014 is somewhat similar https://github.com/benoitc/gunicorn/issues/785.

Downgrading to aiohttp 0.18.4 fixes the issue.

**Comment by redixin** [comment]
It seems aiohttp is listening unix socket. Ill make a patch in few minutes.

**Comment by redixin** [comment]
@alex-kaufman could you please check this patch? It should work and REMOTE_\* and SERVER_\* vars should be set.

Or at least tell me how to start app with gunicorn and unix socket.

**Comment by alex-kaufman** [comment]
@redixin that works, thanks!
