### ISSUE TITLE
Invalid Header stops processing Body?

### ISSUE THREAD

**Issue by AlJohri** [aio-libs/aiohttp#659]
Hi,

I'm not sure if this is intended behavior but I was scraping an rss feed which has a malformed header yet the body is still okay. Chrome seems to render the content fine. This is what the headers look like:

```
➜  ~  curl -I http://www.epw.in/feed/commentary.xml
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 05 Dec 2015 08:20:16 GMT
Content-Type: application/rss+xml; charset=utf-8
Connection: keep-alive
Keep-Alive: timeout=300
Set-Cookie: url_info=/feed/commentary.xml; path=/
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Last-Modified: Sat, 05 Dec 2015 08:20:15 GMT
Cache-Control: store, no-cache, must-revalidate
Cache-Control: post-check=0, pre-check=0
"X-XSS-Protection: 0"
```

The `X-XSS-Protection` header is the culprit yielding a:
`InvalidHeader('400, message=\'Invalid HTTP Header: "X-XSS-PROTECTION\'',)`

Would it make sense to continue processing and get the body?

**Comment by asvetlov** [comment]
Processing malformed headers is cumbersome procedure, many workarounds are required.
We don't try to fix protocol errors.

**Comment by AlJohri** [comment]
Fair enough!
