### ISSUE TITLE
Unclosed response errors

### ISSUE THREAD

**Issue by asdfix** [aio-libs/aiohttp#661]
Linux fedora 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Python 3.5.0 (default, Oct 20 2015, 18:25:15) 
aiohttp 0.19.0

I have "Unclosed response" after successful "Attempt to decode JSON with unexpected mimetype: application/x-javascript; charset=utf-8"
Content is valid json for r.json() but bad mimetype header by remote side can not release response:

client_reqrep.py[LINE:736]# WARNING  [2015-12-05 23:20:44,423]  Attempt to decode JSON with unexpected mimetype: application/x-javascript; charset=utf-8
base_events.py[LINE:1034]# ERROR    [2015-12-05 23:20:44,425]  Unclosed response
client_response: <ClientResponse(http://91.217.10.210:3128/) [200 Connection established]>
<CIMultiDictProxy()>

After several "Unclosed response" errors:

base_events.py[LINE:1034]# ERROR    [2015-12-05 23:40:01,395]  Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fd9ae7372e8>
transport: <_SelectorSocketTransport fd=116 read=polling write=<polling, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 660, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 9] Bad file descriptor

**Comment by asvetlov** [comment]
1. "Attempt to decode JSON with unexpected mimetype: " is a warning not leading to any bad behavior.
2. "Unclosed response" is a warning also.
3. "Bad file descriptor" means someone closed a socket. aiohttp never does it in such inconsistent way.

I cannot say more without additional information (source code and stacktraces are needed).

**Comment by asdfix** [comment]
Thank you for your comments.

It seemed to me there was a link with the socket closing and a lot of "Unclosed response".
I understand that it does not happen.
Unfortunately after migration to py3.5 async/await sintax socket error is not repeated 
and I can not send additional details for my issue now. I think my issue may be closed.

ThanxxL..)
