### ISSUE TITLE
ClientResponseError wrong error propagation?

### ISSUE THREAD

**Issue by AlJohri** [aio-libs/aiohttp#662]
In the client, I believe you catch `ServerDisconnectedError` and a couple other errors and propagate as `ClientResponseError` with `__cause__` set as the real error. I think some other place in the code, I'm getting the raw "ServerDisconnectedError". Realized this since I wasn't catching the error.

Usually: `ClientResponseError` with cause `ServerDisconnectedError`
Sometimes: `ServerDisconnectedError` with cause `ConnectionResetError`

Is this by design?

**Comment by fafhrd91** [comment]
`ServerDisconnectedError` means server dropped connection before completing response.
in second case is second case you probably should get ConnectionResetError

exception handling needs some cleanup

**Comment by fafhrd91** [comment]
client does not catch ServerDisconnectedError anymore
