### ISSUE TITLE
Please support multi language url

### ISSUE THREAD

**Issue by nyssance** [aio-libs/aiohttp#667]
http://xxx.com/(Chinese or Japanese)/  not work, will return 404

**Comment by asvetlov** [comment]
Please elaborate. 
Providing concrete URL example that fails may be very helpful.

**Comment by nyssance** [comment]
#248

**Comment by asvetlov** [comment]
Is your report WSGI-only related?

**Comment by nyssance** [comment]
Yes

**Comment by fafhrd91** [comment]
Wsgi is deprecated
