### ISSUE TITLE
Store elapsed time in the response object

### ISSUE THREAD

**Issue by kaimac1** [aio-libs/aiohttp#670]
It would be useful to have an `elapsed` property on the response object storing the elapsed time, like requests has: http://docs.python-requests.org/en/latest/api/#requests.Response.elapsed

**Comment by asvetlov** [comment]
It makes disambiguation.
While _requests_ reads the whole answer under the hood and has the only _eplased_ time aiohttp has two separate calls: one for getting response headers and second for fetching body.

For aiohttp is more native to have two times but I afraid people will confound these timing attributes.

The need for storing elapsed times is not high from other side. You can do it manually easy without aiohttp API changes.
