### ISSUE TITLE
it is not possible to disable internal compression

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#672]
i could find any way how to disable internal compression if i pass "content-encoding": "gzip" with already compressed data

**Comment by asvetlov** [comment]
Are you asking about server API?
For client we have #619

**Comment by fafhrd91** [comment]
server

**Comment by kxepal** [comment]
`Content-Encoding: identity` serves that purpose.

**Comment by fafhrd91** [comment]
i actually wants to send `"Content-Encoding": "gzip"`

**Comment by asvetlov** [comment]
Fixed by #906

**Comment by asvetlov** [comment]
Actually it's not fixed, the test was bad.
See also https://github.com/KeepSafe/aiohttp/pull/906#issuecomment-225167361

**Comment by fafhrd91** [comment]
fixed tests 3e1b194baea90f85861d7e13d772225df42af0eb
