### ISSUE TITLE
Compression Extensions for WebSocket

### ISSUE THREAD

**Issue by kxepal** [aio-libs/aiohttp#673]
See [RFC-7692](http://tools.ietf.org/html/rfc7692).

**Comment by asvetlov** [comment]
See also #309

**Comment by jzwinck** [comment]
`permessage-deflate` is supported in Chrome (since 32), Firefox (since 37), Tornado, Autobahn, and wspy. It would be a great addition to aiohttp.

**Comment by asvetlov** [comment]
@jzwinck totally agree with you.
Would you work on Pull Request?

**Comment by fanthos** [comment]
aaugustin/websockets has it implemented.
That project licensed under BSD-3.
The extension source code is at:
https://github.com/aaugustin/websockets/blob/master/websockets/extensions/permessage_deflate.py

**Comment by asvetlov** [comment]
Thanks, @fanthos
