### ISSUE TITLE
Limit server connection pool size

### ISSUE THREAD

**Issue by codingjoe** [aio-libs/aiohttp#675]
Is there any way to limit the servers connection pool size?
I'd like to tell my server that this should only allow a certain amount of connections. Sure it can handle very very many, but eventually I won't be able to delivery in time. I'd like to refuse a connection to tell my router to try another app server.

Thanks in advance,
Joe

**Comment by asvetlov** [comment]
It's application level duty.
aiohttp accepts all incoming connections.
If the application cannot process all of them it should return 4xx or 5xx response.
Throttling is too sophisticated task to solve it on aiohttp side, client may have different policies for specific resource paths and users.

**Comment by codingjoe** [comment]
Thanks @asvetlov for the quick reply!
It's not about throttling, I just like to limit the incoming connection pool.
How would you serve a aiohttp service? NGINX?

**Comment by asvetlov** [comment]
Yes, putting aiohttp as upstream behind NGINX in proxy mode is a good practice.

NGINX doc has chapter about connection limiting http://nginx.org/en/docs/http/ngx_http_limit_conn_module.html but it is a bit more complicated than just pushing a limit for all connections opened by server.

What do you mean by _limit the incoming connection pool_?
Should aiohttp reject socket connections or send http response with error status code?

**Comment by codingjoe** [comment]
Reject the socket connection. Anyways, NGINX will do just fine.
