### ISSUE TITLE
Python 3.4.0 support

### ISSUE THREAD

**Issue by ivan** [aio-libs/aiohttp#676]
Would it be possible to add back Python 3.4.0 support?  Ubuntu 14.04 LTS comes with Python 3.4.0, so it is still a very common Python 3 version.

I depend on aiohttp in https://github.com/ludios/grab-site and it would be a hassle for my users to install another Python.

```
  File "/tmp/pip_build_grab/aiohttp/setup.py", line 61, in <module>
    raise RuntimeError("aiohttp requires Python 3.4.1+")
RuntimeError: aiohttp requires Python 3.4.1+
```

https://github.com/KeepSafe/aiohttp/commit/08cedb82a89ea2ec9a1e1f41b2d71a28b35ca45e dropped support for 3.4.0.

**Comment by asvetlov** [comment]
No. Garbage collector is broken in Python 3.4.0
http://aiohttp.readthedocs.org/en/stable/python33.html

**Comment by ludovic-gasc** [comment]
@ivan: you can use tools like miniconda or pythonz to install easily the latest Python version on Linux, without break your python system.

**Comment by ivan** [comment]
Thanks!  I forgot that `trusty-updates` _does_ have Python 3.4.3.  I had a scaleway machine and online.net imaged it with a `/etc/apt/sources.list` that lacks `trusty-updates`.

**Comment by asvetlov** [comment]
Also keep in mind [deadsnakes](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes)
