### ISSUE TITLE
POST query with upgrade to websocket?

### ISSUE THREAD

**Issue by spinus** [aio-libs/aiohttp#679]
I'm trying to do exec in kubernetes (to execute command in a pod). To do that, I need to make a POST query (with params) and upgrade that connection to listen on websocket and wait for events.
Is it possible to do that in aiohttp, if yes, how I can do that?

I tried to pass url with params to ws_connect method and looks like connection is upgraded correctly, but probably there are some issues becasue ti's not POST request.

**Comment by fafhrd91** [comment]
As I remember, websocket handshake requires 'GET' request. You need to customize default handshake implementation

**Comment by asvetlov** [comment]
According to [RFC 6455](https://tools.ietf.org/html/rfc6455#page-14) 

> The method of the request MUST be GET, and the HTTP version MUST be at least 1.1.
> 
> For example, if the WebSocket URI is "ws://example.com/chat", the first line sent should be "GET /chat HTTP/1.1".

Using POST for establishing websocket connection is explicitly forbidden.

**Comment by spinus** [comment]
@fafhrd91 thank you for quick answer, I'll try to do that.

@asvetlov I'm not trying to argue about it's forbidden or not, is it right or not. I'm just trying to connect to the service.

https://github.com/kubernetes/kubernetes/issues/10366 - If I understand correctly from their docs GET and POST should work, but when switching to websocket I have different behaviour for GET and POST. I couldn't get it working with GET so I'll try with POST. Maybe I'm missing something (that's highly probable) and I have to dig into it a little more.

**Comment by fafhrd91** [comment]
@spinus you can just modify aiohttp inplace to see if that helps.

**Comment by spinus** [comment]
@fafhrd91 thank you. That's exactly what I'll try to do.
