### ISSUE TITLE
ParserBuffer can be easily implemented through asyncio ReadStream

### ISSUE THREAD

**Issue by socketpair** [aio-libs/aiohttp#681]
https://github.com/python/asyncio/pull/297 will implement `readuntil`. So everything of ParserBuffer class may be implemented without reinventing wheel.

**Comment by fafhrd91** [comment]
it can not

**Comment by socketpair** [comment]
Moreover, since your implementation  you call `.find()` as a classical painter:

https://en.wikipedia.org/wiki/Joel_Spolsky#Schlemiel_the_Painter.27s_algorithm

In my implementation it is not so.

**Comment by socketpair** [comment]
@fafhrd91, some details ?

**Comment by fafhrd91** [comment]
`ParserBuffer.readuntil()` is not coroutine, it is generator.

**Comment by fafhrd91** [comment]
check **doc** in `parsers.py`

**Comment by socketpair** [comment]
OK, I understand, you are right.

In any way, you can get ideas from my implementation...

Also, It will be nice if you mention in comments (docstring?) that similar code exists in asyncio's StreamReader...

**Comment by fafhrd91** [comment]
i do not have time at the moment, but PRs are welcome!
