### ISSUE TITLE
modifying request object

### ISSUE THREAD

**Issue by ghost** [aio-libs/aiohttp#682]
Hi,

The Request object is currently read only.
I think it would be usefull to be able to modify request headers in a middleware for example.
Being able to add stuff in the request object is nice, but so is having code that don't rely on it (that event works when the middleware is not there)

**Comment by jashandeep-sohi** [comment]
Perhaps you are looking for [`Signals`](http://aiohttp.readthedocs.org/en/latest/web.html#signals)?

**Comment by jashandeep-sohi** [comment]
@asvetlov Ahh, yes -- Been working with responses so much, every "r" word is a "response" in my head now ;-)

**Comment by asvetlov** [comment]
Fixed by #1361
