### ISSUE TITLE
Documentation should aware reader that it is based on 3.5+ syntax

### ISSUE THREAD

**Issue by SzieberthAdam** [aio-libs/aiohttp#683]
Dependencies in documentation list Python 3.4.1+. However, anyone with that version who tries any code of the documentation will face `SyntaxError`s.

So, I suggest to notify reader about this or drop support of 3.4.

Issue discovered by Aymeric Augustin in https://github.com/aaugustin/websockets/issues/88#issuecomment-164822626.

**Comment by asvetlov** [comment]
Personally I don't want to drop 3.4 support at least up to python 3.6 release.
Using async/await in the doc reflects modern python best practices.

Adding a doc page describing `@coroutine` -> `async def` and `yield from` -> `await` translation for Python 3.4 would be helpful.

Would you make a Pull Request with doc update?

**Comment by fafhrd91** [comment]
-1 drop 3.4
i use it in production

**Comment by jashandeep-sohi** [comment]
The README has a pretty clear note. Someone just copy that over to the docs.

**Comment by asvetlov** [comment]
Fixed by #692
