### ISSUE TITLE
[Feature Request] Provide a JsonResponse class

### ISSUE THREAD

**Issue by sk-** [aio-libs/aiohttp#689]
We have been using aiohttp successfully, however we miss a simpler way of generating json responses.
For such we have a utility classes defining a `JsonResponse` class. Note that using directly a `web.Response` is tedious, as you have to set the `content_type`, and probably you want to convert to JSON at the very last minute.

Our (hacky) implementation is as follows:

``` python
class JSONResponse(aiohttp.web.Response):
    """Build an aiohttp.web.Response using a json object."""
    def __init__(self, *, data=None, status=200, reason=None, headers=None):
        super().__init__(content_type=JSON_CONTENT_TYPE, status=status,
                         reason=reason, headers=headers)
        self.data = data

    # The overrides below allow us to change the content of the data object and
    # lazily convert it to an UTF-8 encoded byte string.
    @property
    def body(self):
        body_content = json.dumps(self.data).encode('utf-8')
        self.content_length = len(body_content)
        return body_content

    @body.setter
    def body(self, value):
        pass

    @property
    def _body(self):
        return self.body

    @_body.setter
    def _body(self, value):
        pass
```

I would really love to have JSON support to be much simpler out of the box, and would be happy to contribute a non hacky version.

**Comment by asvetlov** [comment]
Use `json_response` instead.
See #592 for objections against class-based implementation.

**Comment by sk-** [comment]
I tried to use that, but one problem with that approach, is that you no longer have access to the original data. So for example, it is not possible to have a middleware that inspects the data and does something with it (my use case), or in tests for example.

Another problem is that nothing restricts you from changing the underlying text representation. So you could end up with a malformed json body.

Also, the data is serialized eagerly, instead of lazily. Which means that you would incur the cost of serializing even if you end up dropping that response.

**Comment by asvetlov** [comment]
I got your point.
You want to use middleware for json modification.
Someone else might want to use them for image changing: resizing or saturation adjustment for example.

Both usages may be fine for application code but will never get a chance to land into aiohttp library.
If you really need `JSONResponse` class -- please keep it inside your code bounds.
