### ISSUE TITLE
Async iterator never returns close message

### ISSUE THREAD

**Issue by mattupstate** [aio-libs/aiohttp#694]
As you can see [here](https://github.com/KeepSafe/aiohttp/blob/e09b86204c9099389c530b2886770e0060a05f63/aiohttp/web_ws.py#L297) the last message never gets returned because the exception is raised before it has a chance. As a result a developer can't respond to the close message, perhaps cleaning up something or closing another connection.

**Comment by asvetlov** [comment]
Try

```
async for msg in ws:
    processs_msg(msg)
process_closing()
```
