### ISSUE TITLE
Enable sinks

### ISSUE THREAD

**Issue by eyal-stratoscale** [aio-libs/aiohttp#698]
Feature request/ Enhancement.
In Falcon, there is a routing feature I use, called sink. we need it in aiohttp in order to port our server.
The dispatcher should iterate those sinks after all the routes matching failed.
Then, a sink catches the request if the url is prefixed with sink url, and no rule on the method (aiohttp method == '*').

http://falcon.readthedocs.org/en/stable/api/api.html?highlight=sink#falcon.API.add_sink

Thanks.

**Comment by asvetlov** [comment]
In aiohttp routes are organized in an ordered list.
To make _sink_ just register sink route at the very end.

**Comment by eyal-stratoscale** [comment]
I thought of it as a possibility, but the urldisaptcher escapes characters like `.*`, and then the regex don't catch the path.
Is there a way to add the `.*` regex to an end of a url?

**Comment by asvetlov** [comment]
try "/prefix/to/{tail:.+}"
See #291 for details.

**Comment by eyal-stratoscale** [comment]
Thanks, not exactly what I need but it can work.
