### ISSUE TITLE
Pass response to WSServerHandshakeError

### ISSUE THREAD

**Issue by mattupstate** [aio-libs/aiohttp#701]
It might be useful to be able to reference the response when capturing a `WSServerHandshakeError`. The response object also doesn't seem to get closed when the client consumes this error.

**Comment by asvetlov** [comment]
I believe you actually need status code and headers only, not the whole response.
See #706 for fix

**Comment by asvetlov** [comment]
Fixed by #706

**Comment by jeduden** [comment]
@asvetlov can we re-open this issue ? since ws_connect actually makes troubleshooting connection errors very difficult as the response in our case contains detailed error information.

**Comment by asvetlov** [comment]
Please create a new one with detailed description of your problem.

**Comment by jeduden** [comment]
@asvetlov  opened  https://github.com/aio-libs/aiohttp/issues/2279
