### ISSUE TITLE
split client, server & websocket stuff into separate packages

### ISSUE THREAD

**Issue by petri** [aio-libs/aiohttp#704]
I wanted just an asyncio http client, and first tried aiohttp. However when installing, I saw the package is very large. I did not realize there is also websocket stuff etc.

It is of course ok to stay monolithic if aiohttp wants to become the Twisted of HTTP. But there are downsides.

It would be greate if there were separate client, server & websocket support packages.

**Comment by asvetlov** [comment]
Sorry, it will never happen.
That ship has sailed couple years ago.
