### ISSUE TITLE
Remove AbstractMatchInfo.route etc

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#719]
I think current implementation with routes is overcomplicated.

Looks like it present only for `SystemRoute` existence (which can be removed as well).

@fafhrd91 do you remember the reason for it?

**Comment by fafhrd91** [comment]
you can not remove SystemRoute, it unifies all routes. #340

**Comment by asvetlov** [comment]
Thanks, I've missed this PR
