### ISSUE TITLE
My server cant handle Exception.

### ISSUE THREAD

**Issue by binhnq94** [aio-libs/aiohttp#720]
I have same problem.
example code:

``` python
def handle_errors(func):
    def wrapped(request):
        data = {}
        try:
            data = func(request)
        except Exception as e:
            print('Pha 1: %s', e)
            data = {
                'status': False,
                'error_message': str(e)
            }
            data = web.Response(body=json.dumps(data).encode('utf-8'))
        finally:
            return data
    return wrapped

@handle_errors
def index(request):
    raise ExceptionError('error')
```

my server dont return data = { 'status': False,'error_message': str(e)}.
it response 500 Internal Server Error with Traceback:

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/server.py", line 272, in start
    yield from self.handle_request(message, payload)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/web.py", line 85, in handle_request
    resp = yield from handler(request)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 143, in coro
    res = yield from res
  File "...................................................../handlers.py", line 118, in xxxxx
    raise ExceptionError('error')
ExceptionError: 'error'
```

**Comment by asvetlov** [comment]
Provide full reproducible example please.
As far as I see your code should work correctly.

**Comment by binhnq94** [comment]
my repository: https://github.com/cloudcomputinghust/bio-wrapper/blob/master/wrapper/handlers.py

if u try request: http://localhost:8080/job/?job_id=1 , my service will reponse 500 Internal Server Error with Traceback.

note: - start service: python3 service.py (https://github.com/cloudcomputinghust/bio-wrapper/blob/master/wrapper/service.py)

**Comment by binhnq94** [comment]
I fixed the error through the solution:
https://docs.python.org/3/library/asyncio-dev.html#detect-exceptions-never-consumed

**Comment by asvetlov** [comment]
Cool!

**Comment by binhnq94** [comment]
it is my bad =)))
I did not really understand asyncio and I think there are some people who have similar problems: http://stackoverflow.com/questions/30361824/asynchronous-exception-handling-in-python .
Error handling in asyncio is  very different.
