### ISSUE TITLE
Enabling compression sets Transfer-Encoding chunked

### ISSUE THREAD

**Issue by danielnelson** [aio-libs/aiohttp#721]
When I call `web.Response.enable_compression` it adds `TRANSFER-ENCODING: chunked` to the response.

It looks like it causes `autochunked` to be true since the length is set to None.

**Comment by asvetlov** [comment]
Is it close to #690 ?

#672 sorry

**Comment by danielnelson** [comment]
I don't see the connection between these, is that the right link?

**Comment by fafhrd91** [comment]
it is related to #672

**Comment by asvetlov** [comment]
Superseded by #672
