### ISSUE TITLE
Break backward compatibility in protocol.py

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#724]
Looking on #515 (adding `raw_headers` support) I found that `HttpParser.parse_headers()` should return both string encoded headers and raw data.
This breaks backward compatibility in our very low level API.

I believe it's ok, I never considered `protocol.py` as part of aiohttp _Public API_.
Moreover, I tend to assume that not explicitly documented API is unstable (with obvious exceptions like `streams.StreamReader`). 

http://aiohttp.readthedocs.org/en/stable/api.html should be removed eventually and replaced with non-autodoc page describing really _public_ functions and classes.

**Comment by fafhrd91** [comment]
i think it is ok to break compatibility in protocol.py

**Comment by asvetlov** [comment]
`raw_headers` added
