### ISSUE TITLE
possibly malformed sslcontext breaks server responses without any error

### ISSUE THREAD

**Issue by dotSynergy** [aio-libs/aiohttp#7241]
### Describe the bug

i'm running aiohttp only to serve a redirect so a reverse proxy wasn't an option, and i wanted to replace an older raw tcp implementation with aiohttp, however by leaving my previous ssl context code somehow i only got empty body responses.
ssl negotiation and header would look fine, until (using curl): `curl: (52) Empty reply from server` and connection would close.

the error, minus ssl, looks exactly as this stackoverflow question:
https://stackoverflow.com/questions/66855708/empty-reply-from-server-with-aiohttp-with-python-3-8

older code:

```
if use_ssl is True:
            path = os.path.dirname(os.path.abspath(__file__))
            ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH) # CLIENT_AUTH didn't work either
            ssl_context.load_cert_chain(f'{path}/certs/tls.crt', f'{path}/certs/tls.key')
```

for everyone left scratching its head, this code works:
```
if use_ssl is True:
            path = os.path.dirname(os.path.abspath(__file__))
            ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER) #only this combination works, class + PROTOCOL_TLS_SERVER
            ssl_context.load_cert_chain(f'{path}/certs/tls.crt', f'{path}/certs/tls.key')
```

### To Reproduce

```python

async def handler()
    return web.Request(...)

path = "...."
addr = "0.0.0.0"
port = 8080

ctx = None

if use_ssl is True:
            path = os.path.dirname(os.path.abspath(__file__))
            ctx = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH) # CLIENT_AUTH didn't work either
            ctx.load_cert_chain(f'{path}/certs/tls.crt', f'{path}/certs/tls.key')

server = web.Server(handler)
runner = web.ServerRunner(server)

await self.runner.setup()

site = web.TCPSite(
            runner, 
            host=addr, 
            port=port,
            ssl_context=

await self.site.start()

```

### Expected behavior

any log of the error

### Logs/tracebacks

```python-traceback
nope
```

### Python Version

```console
$ python --version

 3.10.10
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.8.4
```

### multidict Version

```console
$ python -m pip show multidict
6.0.4
```

### yarl Version

```console
$ python -m pip show yarl
1.8.2
```

### OS

docker ubuntu:focal

### Related component

Server

### Code of Conduct

- [x] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
From the `create_default_context()` documentation:

> The settings are chosen by the [ssl](https://docs.python.org/3/library/ssl.html#module-ssl) module, and usually represent a higher security level than when calling the [SSLContext](https://docs.python.org/3/library/ssl.html#ssl.SSLContext) constructor directly.

So, my suspicion is that your client doesn't support a secure protocol or something. Upon seeing a response for a protocol it doesn't recognise, it disconnects. Maybe if you use access logging, you can see the client disconnects in the logs there. I don't think there's anything else for us to do here.

If you're curious exactly what your client is failing on, try adding all the flags from the default context one at a time until you find the one that breaks it.

**Comment by webknjaz** [comment]
@Dreamsorcerer it might be interesting for us to add a a test case with a cipher mismatch...

Not sure if an empty response would be something representing this case, though. curl would probably display an error message, I think.
This should be checked with more verbosity and `openssl s_client -host <hostname> -port <port>`.

**Comment by Dreamsorcerer** [comment]
Yep, if someone wants to try to play with it and create a test, that'd be good. But, I'm pretty sure I've seen that curl error before in relation to TLS errors.

Possibly, the sequence of events looks more like: server responds with acceptable protocols etc., client responds with no compatible ciphers/protocols, server closes connection. As the TLS connection cannot be completed, the server would be unable to send a response, so I think that's why you end up with the empty reply error.
