### ISSUE TITLE
Memory leak in set_parser

### ISSUE THREAD

**Issue by mpaolini** [aio-libs/aiohttp#725]
I've got two more leaks tracked down with `tracemalloc` and disabled gc

```
<StatisticDiff traceback=<Traceback (<Frame filename='/usr/local/lib/python3.4/site-packages/aiohttp/client_reqrep.py' lineno=481>,)> size=984648 (+209328) count=5547 (+267)>,
 <StatisticDiff traceback=<Traceback (<Frame filename='/usr/local/lib/python3.4/site-packages/aiohttp/protocol.py' lineno=319>,)> size=298096 (+116064) count=601 (+234)>,
```

**Comment by mpaolini** [comment]
this only happens whe using aiohttp as a client library to consume dropbox longpolling API. I have a similar client implemented with aiohttp that is consuming regular APIs and it does not leak

**Comment by mpaolini** [comment]
this is also quite bad

```
[<StatisticDiff traceback=<Traceback (<Frame filename='/usr/local/lib/python3.4/ssl.py' lineno=653>,)> size=62132428 (+11269768) count=935525 (+169116)>,
```

**Comment by mpaolini** [comment]
the ssl memory leak I gues has been fixed in python 3.4.4 (I am using 3.4.3) http://bugs.python.org/issue25578

**Comment by asvetlov** [comment]
The report belongs to `aiohttp==0.20.2`, right?

**Comment by mpaolini** [comment]
yep

**Comment by asvetlov** [comment]
@mpaolini I believe we can cloase the issue

**Comment by mpaolini** [comment]
@asvetlov please give me some time to try it out with the new aiohttp release

**Comment by asvetlov** [comment]
ok

**Comment by fafhrd91** [comment]
Is this stil issue?

**Comment by asvetlov** [comment]
I believe we can close it.
