### ISSUE TITLE
Add optional support for aiodns to TCPConnector for async DNS resolving

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#728]
See http://stackoverflow.com/questions/34700311/how-to-handle-dns-timeouts-with-aiohttp for reasoning

**Comment by gwillem** [comment]
Thanks for your suggestions! To be solved:
1. The HTTP host header needs to be overwritten (easy)
2.  SSL verification requires the true hostname. I have dug in the code but not found a way yet to cleanly pass the hostname to the SSL context ([relevant code here](https://github.com/python/cpython/blob/6c223d811812f36ac38ec19e2f59d68f2336a0e4/Lib/ssl.py#L254))

**Comment by asvetlov** [comment]
`TCPConnector._resolve` https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/connector.py#L531 performs DNS lookup if `use_dns_cache` for `TCPConnector` http://aiohttp.readthedocs.org/en/stable/client_reference.html#tcpconnector is `True`.
I suggest adding new ctor parameter `use_aiodns` (also `False` by default) to resolve through aiodns if `use_dns_cache` is `True`.

**Comment by fafhrd91** [comment]
-1 for `use_aiodns`, better is to invert dependency.
we need Resolver object, and pass that object as parameter to connector, then we can create default resolver that uses asyncio and aiodns one.

**Comment by asvetlov** [comment]
Yes, `Resolver` sounds better than `use_aiodns`.
Thanks for correction.

**Comment by asvetlov** [comment]
Fixed by #819
