### ISSUE TITLE
Deprecate bare request(), get() and family for encouraging ClientSession usage

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#729]
Recreating `Connector` on every request is a little expensive.
`ClientSession` allows connection utilization, it also supports keep-alives out-of-the box.

Unfortunately I see many examples of bare coroutines usage -- people are lazy :(

**Comment by gwillem** [comment]
Hi Andrew! IMHO most people will follow the basic examples without reading everything. Upper half of http://aiohttp.readthedocs.org/en/stable/client.html does not mention connectors. 

Then again, people who care for performance are probably also the ones who do read the reference doc.

**Comment by asvetlov** [comment]
Would you update docs to emphasize `ClientSession`  usage?

**Comment by asvetlov** [comment]
Fixed by e194ede and e8b47f7
