### ISSUE TITLE
Using a file object as the data parameter forces chunked transfer encoding

### ISSUE THREAD

**Issue by catlee** [aio-libs/aiohttp#732]
I'm trying to PUT to S3 using code like this:

```
response = yield from session.request('put', put_url, headers=headers, data=fileobj)
```

I already know how big fileobj is, and I've included that in the content-length header. However, it appears as if aiohttp can't figure out how big it is, and so forces the request to use chunked transfer encoding, which S3 rejects.

In my case, fileobj is a tempfile.TemporaryFile object.

**Comment by asvetlov** [comment]
Use `bytes` instead for example or `io.BytesIO` / `io.BufferedReader`.
Generic `io.IOBase` has no size, aiohttp uses chunked encoding in the case.
See https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client_reqrep.py#L284-L304 for details.

**Comment by catlee** [comment]
I don't really want to read the whole file into memory, which is why I'm
using a file object. Also, I already know the size, why does aiohttp have
to second guess me?

https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client_reqrep.py#L294
could be changed to check if I have already set Content-Length, and not set
chunked transfer mode if I have it set already.

**Comment by asvetlov** [comment]
I agree that chunked encoding should be off if `Content-Length` is specified in headers regardless on data type.

Would you provide a Pull Request?

**Comment by fafhrd91** [comment]
I thought we do that already.  Could we check same for server code

**Comment by asvetlov** [comment]
We made a fix for providing `Content-Length` in many cases when the length is available but don't respect `Content-Length` for provided data in client api.

**Comment by fafhrd91** [comment]
we have more general issue #1655 and #1172
