### ISSUE TITLE
aiohttp can not execute in parallel on the same method

### ISSUE THREAD

**Issue by ghost** [aio-libs/aiohttp#749]
Here are the codes:
###### 

```
import asyncio
from aiohttp import web

async def hello(req):

    print("start")
    await asyncio.sleep(5)
    print("stop")
    return web.Response(body=b"hello")

def main():

    loop = asyncio.get_event_loop()

    app = web.Application()
    app.router.add_route("GET", "/", hello)

    handler = app.make_handler()
    srv = loop.run_until_complete(loop.create_server(handler, "127.0.0.1", 8080))
    try:
        loop.run_forever()
    except KeyboardInterrupt:
        pass
    finally:
        srv.close()
        loop.run_until_complete(srv.wait_closed())
        loop.run_until_complete(handler.finish_connections(1.0))
        loop.run_until_complete(app.finish())
        loop.run_until_complete(ds.close())
    loop.close()

main()
```
###### 

when I visit "http://localhost:8080/" twice, I expect that it costs 5 seconds and prints: 

```
start
start
stop
stop
```

but it turns out that it costs 10 seconds and prints:

```
start
stop
start
stop
```

which means it is a blocking call
Is there someting wrong with my code?

**Comment by jettify** [comment]
On my machine your code works as expected. Could you try to execute your code on other machine/OS?

**Comment by ghost** [comment]
Thanks for @jettify , it looks like that the result depends on the machine os

OS X Yosemite 10.10.5    =>   5 seconds   start start stop stop
Windows 7 SP1                => 10 seconds   start stop start stop
