### ISSUE TITLE
Why this happen?

### ISSUE THREAD

**Issue by wanggp3** [aio-libs/aiohttp#759]
I have a handler class, and I increase a counter when the request comes, and decrease counter when request ends, but when I test the web application in a high loading requets, and the client disconnect proactively(eg: timeout or keyaborad). In the end, the counter was not zero? Could someone explain to me why the counter was not zeor? Thanks.

**Comment by asvetlov** [comment]
It's impossible to guess without looking on your code, sorry.

**Comment by wanggp3** [comment]
Oh, it's now ok after I add try..except for every coroutine in the request handler, so I think may be when the client cancel the request, exception happen without catched, thus interrupt that request

**Comment by asvetlov** [comment]
Yes, exactly!
