### ISSUE TITLE
Backward incompatible changes in RawRequestMessage (add raw_headers)

### ISSUE THREAD

**Issue by pahaz** [aio-libs/aiohttp#760]
problem: https://github.com/aio-libs/sockjs/issues/20

commit: https://github.com/KeepSafe/aiohttp/commit/fa06acc2392c516491bdb25301ad3ef2b700ff5f

Please answer in https://github.com/aio-libs/sockjs/issues/20

**Comment by asvetlov** [comment]
`RawRequestMessage` is not supposed to be backward-compatible.

I'll take a look on sockjs in few days.
