### ISSUE TITLE
wheel

### ISSUE THREAD

**Issue by hynek** [aio-libs/aiohttp#762]
Hi,

would you mind uploading a wheel file of aiohttp to PyPI?  They have smaller downloads and faster installs (they don't run setup.py on install).

All you have to do is:

Add

``` init
[wheel]
universal = 1
```

to your `setup.cfg` (it tells wheel that you’re python-only and that you need only one wheel file that works on all architectures)

and then installing the wheel package + running `python setup.py bdist_wheel`.  More details in my [blog post](https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/). :)

Thanks for the consideration!

**Comment by asvetlov** [comment]
Unfortunately aiohttp has C extensions (Cython ones actually) for multidict and websockets.
While these extensions are optional they are improve performance significally, so I cannot ship pure python wheel.

I set up appveyor process to build and upload windows wheels for all supported platforms.
Wheel for linux is impossible until we'll get PEP 513 implemented.
Sorry, I don't know what CI server can help with building MacOSX wheels -- it's totally dark matter for me.

**Comment by hynek** [comment]
Ah dammit sorry, that was stupid of me.  But the windows wheels weren’t there when I opened this issue, right? :)  I’m also not aware of a way to build OS X wheels.  At PyCA we have Travis Instances for that (which I’m not familiar with).

**Comment by asvetlov** [comment]
I've tried to configure Travis-CI for running MacOSX worker but got a failure.
Now aiohttp deployment is executed by pushing git tag. 
Travis just works faster and publish tgz sooner than appveyor builds and uploads wheels :)

**Comment by hynek** [comment]
oh got yes, appveyor is glacial :)

as for OS X, you need to have some flag I believe.

and even then it’s not _that_ simple.  @reaperhulk may be able to give you the gist of it, but I understand there’s good reasons why PyCA is running tests (also) on Travis but building the wheels elsewhere.
