### ISSUE TITLE
logging docs don’t reflect recent changes

### ISSUE THREAD

**Issue by hynek** [aio-libs/aiohttp#763]
Access log is on by default but https://github.com/KeepSafe/aiohttp/blob/master/docs/logging.rst claims the opposite.  It would be really nice if the docs mentioned how to get rid of them again for people upgrading. :)

**Comment by asvetlov** [comment]
Reasonable proposal.
I'll update docs.
As quick answer you should pass `access_log=None` into `app.make_handler(...)`

**Comment by asvetlov** [comment]
Fixed by dd2146cc, published in 0.21.1
