### ISSUE TITLE
"http" should be uppercase in docstrings

### ISSUE THREAD

**Issue by rutsky** [aio-libs/aiohttp#770]
#546 fixed "http" only in RST documentation for #538 (thanks @carlcarl!), but there are still `Http` and `http` in docstrings in Python sources, for example:

https://github.com/KeepSafe/aiohttp/blob/fa06acc2392c516491bdb25301ad3ef2b700ff5f/aiohttp/errors.py#L74

**Comment by asvetlov** [comment]
Not bad idea but the priority is very low from my perspective.
