### ISSUE TITLE
Provide a simple fake Request object

### ISSUE THREAD

**Issue by brettcannon** [aio-libs/aiohttp#771]
The docs very clearly say that a `Request` object should not be constructed manually, but in not being able to do so it makes it hard to test any code that takes a `Request` object as an argument. If there was a simple way to create a fake `Request` object that would help alleviate the issue.

**Comment by brettcannon** [comment]
And I should mention the fake request could be as simple as an ABC that only needs one or two things set.

**Comment by asvetlov** [comment]
Brilliant idea.
To be clear -- are you propose fake request for usage by unit tests only, right?
Function `fake_request()` which files transport/reader/writer with mocks may solve your need than.

**Comment by brettcannon** [comment]
Yep, just for unit tests. For instance, I'm using [a fake `web.Request`](https://github.com/brettcannon/knights-who-say-ni/blob/8a50f2d5a56371bf6db19ed4d31cfccf10111ce3/ni/test/test_github.py#L12) for testing an [API that takes a `web.Request` object](https://github.com/brettcannon/knights-who-say-ni/blob/8a50f2d5a56371bf6db19ed4d31cfccf10111ce3/ni/abc.py#L35) as an argument. It's a little sketchy, though, since I'm faking specific attributes and methods, when I would rather either have an ABC that I can fake fully and properly or some subclass where I can just provide any headers and payload I want and have all the attributes and methods just work properly (I tried that and I got errors about headers being read-only and such).

**Comment by akhomchenko** [comment]
@asvetlov Does someone works on this? I can take it

**Comment by asvetlov** [comment]
Please do.
I want to include the feature into 0.22 release but did not start to work on it yet.

**Comment by jettify** [comment]
I will work on this one on sprints

**Comment by pfreixes** [comment]
Though IMHO this is only the tip of the Iceberg, what about the conception of a unit test pattern without the needed of a real client/server scenario ? It is not because of Flask does it [1], its because testing and its practices became easily, perhaps the patching.

[1] http://flask.pocoo.org/docs/0.11/testing/

**Comment by asvetlov** [comment]
Fixed by #900
