### ISSUE TITLE
How to set a TCP timeout?

### ISSUE THREAD

**Issue by qnnnnez** [aio-libs/aiohttp#774]
I tried `asyncio.wait_for` and `aiohttp.Timeout`, but they just set a timeout for the connection, but do not care about the connection itself. So if your download is not finished when the deadline is reached, your download is cancelled. `TCPConnector` has a timeout param, but it is the same.

This is not always helpful, especially if you want to download a file but you do not know its size. Small files and big files can be downloaded using a same TCP timeout, but not a entire timeout. You can calculate a timeout from file size, but it is I think a bit tricky. And if your network condition is bad (just like me), a TCP timeout is a signal to reset the connection and maybe restart it later.

Both `requests` and `urllib.request` provide adjustable TCP timeout, while `aiohttp` does not. I wonder is it possible to implement it in an async way? It can be very helpful.

**Comment by asvetlov** [comment]
Yes, the requested feature worth to be added.
Technically I suggest adding `tcp_timeout` parameter to `TCPConnector` constructor.
@qnnnnez would you create a Pull Request? It's relative easy task.

**Comment by qnnnnez** [comment]
@asvetlov 
I will have a try.

**Comment by qnnnnez** [comment]
Maybe I can create a task that raises an exception after a few seconds, and cancel it if received any data and create a new?
Will this work? @asvetlov

**Comment by qnnnnez** [comment]
Setting a timeout for an non-blocking socket makes no sense, so when you set a non-zero timeout for a socket, it is switched to blocking mode.

But logically, await means blocking. You are awaiting a host and because the host do not response for a long time, the event loop tells you that time is out. I think that is natural.

But I do not know how to do this. Maybe it is not easy for me, as I am really a beginner.

**Comment by qnnnnez** [comment]
Maybe I should turn to asyncio and request to add the feature to the event loop?

**Comment by asvetlov** [comment]
No, it's not asyncio duty.
Let's return to very beginning.
You do want to download a huge file using slow network.

```
    with aiohttp.Timeout(5):
        async with client.get(url) as resp:
            content = await resp.read()
```

doesn't work for you, right?
I may suggest reading by relative small pieces:

```
    with aiohttp.Timeout(5):
        resp = await client.get(url)
    while True:
        with aiohttp.Timeout(5):
            try:
                chunk = await resp.content.read(512*1024)
                if not chunk:
                    break
                else:
                    # process chunk
            except aiohttp.EofStream:
                break
```

**Comment by qnnnnez** [comment]
If I have another coroutine that is doing a calculation that needs 6 seconds, will that downloading task be cancelled? I'm not very familiar with how the event loop actually works.

**Comment by qnnnnez** [comment]
Yeah, but your method should work fine, thanks.

**Comment by asvetlov** [comment]
You always can apply timeout to `resp.content.read(...)` call only.

**Comment by qnnnnez** [comment]
But what if I do my tiring calculation in another coroutine without a break for 6 seconds?

**Comment by asvetlov** [comment]
Please provide a code snippet, I don't follow your thoughts.

**Comment by qnnnnez** [comment]
Well, it doesn't really matter. Thanks for your kind help.

```
def calculate():
    time.sleep(6.0)

async def download(...)
    ...
    with aiohttp.Timeout(5):
        resp = await client.get(url)
    while True:
        with aiohttp.Timeout(5):
            try:
                chunk = await resp.content.read(512*1024)
                if not chunk:
                    break
                else:
                    # process chunk
            except aiohttp.EofStream:
                break
    ...
```

I await `download` and then call `calculate` somewhere else (maybe this should be done in a new thread, but not this time), so after 6 seconds, download is cancelled even if the socket is ready for reading. I didn't do a experiment.
`calculate` might be an action that needs a lot of CPU time, or a disk read/write operation, etc.

**Comment by asvetlov** [comment]
Won't fix it, sorry
