### ISSUE TITLE
Closing the response's connection does not prevent the body from being downloaded

### ISSUE THREAD

**Issue by Djayb6** [aio-libs/aiohttp#776]
Hello,

I wanted to see whether it is possible to cancel a client-side connection before the body is downloaded (i.e to prevent big downloads based on the Content-Type header). I found in the aiohttp docs' comments this [gist](https://gist.github.com/asvetlov/64cd475d5c080a711ce4) which claims to be able to prevent the download of the body by calling `.close()` on the response.  

I tested the code below that is similar to the gist (mine just closes the connection) and fired up Wireshark to inspect the packets. I saw that even though the response was closed the body has been downloaded.

Is this the correct behaviour? Otherwise is there a way to prevent the download of the body ? 

Many thanks,

JB

```
import asyncio
import aiohttp

async def get_file(session, url):
    async with session.get(url) as response:
        response.close()

loop = asyncio.get_event_loop()
with aiohttp.ClientSession() as session:
        loop.run_until_complete(get_file(session, 'http://www.thinkbroadband.com/download.html'))
```

**Comment by fafhrd91** [comment]
server sends payload unconditionally, also your incoming kernel buffer probably large enough to receive whole payload.
you should test it on large file

**Comment by Djayb6** [comment]
That makes sense, thank you!
