### ISSUE TITLE
Add an option to periodicaly ping idle websockets to keep proxies happy

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#777]
See tornadoweb/tornado#1640 for explanation

**Comment by fafhrd91** [comment]
can we use keep-alive timers for that?

**Comment by asvetlov** [comment]
So you mean utilizing `SO_KEEPALIVE` from low-level `server.py` code?
It's only hop-to-hop setting, proxies don't cope with it.

**Comment by fafhrd91** [comment]
No, just keep

**Comment by fafhrd91** [comment]
I thought we have timer for keep alive, but it just ceil on time. Ok, np

**Comment by rutsky** [comment]
What is intended interface and behavior?

Currently `WebSocketResponse` has only `autoping=True` parameter which tells to auto-send `PONG` replies for each received `PING` message.

Behavior that can implemented for this feature:
1. `WebSocketResponse` sends `PING` messages every `ping_interval` seconds,
2. if no `PONG` messages are received for `pong_timeout` seconds, `WebSocketResponse` closes connection.

Should received from client data reset `pong_timeout`?

What if client doesn't implement `PONG` sending? His connection will be closed according to described above behavior (which is OK if this behavior is not enabled by default).

Do we need separate option for current `autoping=True` behavior, or we can put both behaviors under same option?

**Comment by asvetlov** [comment]
Let me re-read RFC prior to keeping conversation

**Comment by fafhrd91** [comment]
added `heartbeat` option to client and server web sockets
