### ISSUE TITLE
Add autoreload option

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#778]
One of the most requested features is autoreloading aiohttp server on source file changes.

I never use the feature at all and don't have a strong personal feeling for adding it.
It may have negative effects by abnormal breaking opened connections (e.g. websockets) also.

But I see to many requests for the feature over internet for last months, so we need to implement it.

It's a easy task though.

**Comment by ssbb** [comment]
This functionality is provided by aiohttp_utils already. Also it's possible to use watchdog (watchmedo) without writing any Python code :)

**Comment by ssbb** [comment]
As, forgot. There is also `--reload` option for gunicorn which is works for me.

**Comment by asvetlov** [comment]
See also https://github.com/anti1869/aiohttp_autoreload/blob/master/src/aiohttp_autoreload.py and https://github.com/tornadoweb/tornado/blob/master/tornado/autoreload.py

https://github.com/sloria/aiohttp_utils/blob/327de04a1c3a09d4aa641a01137c67826b1ccc57/aiohttp_utils/runner.py

**Comment by samuelcolvin** [comment]
https://github.com/samuelcolvin/aiohttp_runserver

As I just explain on the mailing list I don't think it makes sense to include all the debug paraphernalia in aiohttp itself.

Whether it's this library or anther I think the should be a companion tool for aiohttp which help during development. 

I built `aiohttp-runserver` after using gunicorn with `--reload` for a while and getting annoyed at it's logging (amount other things), particularly when you change the terminal window size!

**Comment by ohsabry** [comment]
@samuelcolvin just my two cents, but as someone who recently bet on using aiohttp in production, it would be a huge turn off for me if all of the debug and development tools are scattered around a bunch of small external repositories that may never get maintained. 

unless it's a single other lib that's officially maintained and has all of the development tools, having a bunch of small libs these small libraries will lead to a typical node/reactjs style bootstrapping nightmare for new adopters.  https://twitter.com/thomasfuchs/status/708675139253174273

The batteries included mentality of the python community is what made me choose `aiohttp` and not something built on top of node.

**Comment by samuelcolvin** [comment]
@ohsabry I've create a new issue #1156 addressing this very reasonable concern directly.

**Comment by mshahbazi** [comment]
gunicorn --reload does not work immediately. it waits until the next timeout loop. any idea?

**Comment by samuelcolvin** [comment]
@mshahbazi have a try with [aiohttp-devtools](https://github.com/samuelcolvin/aiohttp-devtools), it's still a work in progress but the `runserver` command is working well and has autoreload by default.

**Comment by mshahbazi** [comment]
thank you for your reply and thank for the module. it looks great but I had the following problems:
I cannot figure out how does it work.
after installation, I got this error: cannot import name ‘StaticRoute'
I commented out the corresponding lines and still have problem with running my script.
let’s say I should run my script as: “aiohttp-runserver main.py” I get a long chain of errors, starting with:

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp_runserver/serve.py", line 240, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py", line 454, in log
    self.logger.info(self._log_format % tuple(values), extra=extra)
  File "/usr/lib/python3.5/logging/__init__.py", line 1279, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp_runserver/logs.py", line 53, in emit
    method, path, _, code, size = msg.split(' ')
ValueError: too many values to unpack (expected 5)

During handling of the above exception, another exception occurred:
…

to keep it simple, main.py holds the following codes only:
app = aiohttp.web.Application()
aiohttp.web.run_app(app=app, host=config.SERVER_HOST, port=config.SERVER_PORT, shutdown_timeout=1)

**Comment by samuelcolvin** [comment]
Hi @mshahbazi happy to help but please repost the question over on https://github.com/samuelcolvin/aiohttp-devtools to avoid even more confusion.

A few more details like OS and aiohttp version would be helpful too.

**Comment by samuelcolvin** [comment]
For me https://github.com/samuelcolvin/aiohttp-devtools is ready for use so this can be closed.

**Comment by fafhrd91** [comment]
closing in favor of https://github.com/samuelcolvin/aiohttp-devtools
