### ISSUE TITLE
Add headers to ClientSession.ws_connect.

### ISSUE THREAD

**Issue by Rapptz** [aio-libs/aiohttp#785]
The documentation says bare `aiohttp.ws_connect` is deprecated and `ClientSession.ws_connect` should be used instead.

However, the latter has less features than the former. `ClientSession.ws_connect` does not have the `headers` keyword argument to allow us to add any headers we want while `aiohttp.ws_connect` does.

**Comment by asvetlov** [comment]
Does session headers satisfy your requirements or do you need temporary headers specific to `ws_connect` request?

**Comment by Rapptz** [comment]
The latter. Some headers can be global, e.g. I set the content type in the Session headers but the ws_connect does not need them.

**Comment by asvetlov** [comment]
That makes sense. Would you provide a Pull Request?

**Comment by asvetlov** [comment]
Fixed by #898
