### ISSUE TITLE
BaseConnector keepalive_timeout fails with None as value

### ISSUE THREAD

**Issue by veaviticus** [aio-libs/aiohttp#786]
According to the docs (https://aiohttp.readthedocs.org/en/stable/client_reference.html#aiohttp.BaseConnector), keepalive_timeout can take None as a value to signify no timeout.

However, the code (https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/connector.py#L128) doesn't check for None, it assumes a float value was passed (it is later used in an addition operation https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/connector.py#L221)

Passing None to this value will fail. The function should check for None, or the docs should be updated.

**Comment by asvetlov** [comment]
`keepalive_timeout=None` should imply `force_close=True`.
`force_close=True` should raise `ValueError`  if `keepalive_timeout` is set also.

The patch is pretty easy.
Any volunteers?

**Comment by denismakogon** [comment]
@asvetlov let me step in for it.

**Comment by asvetlov** [comment]
Fixed by #907 and 804dda1
