### ISSUE TITLE
the absence of a cookies keyword argument  

### ISSUE THREAD

**Issue by arheo** [aio-libs/aiohttp#790]
it seems that there is no argument cookies in coroutine _request() in client.py. aiohttp 0.21.2

**Comment by asvetlov** [comment]
It will use cookies stored in session instance.
Looks like you are asking for request scoped cookies if I understand you correctly.
Please describe your use case, I curious why users are not satisfied with session scoped ones.

**Comment by arheo** [comment]
You are right, i just used manual page (http://aiohttp.readthedocs.org/en/stable/client.html#custom-cookies) and got an exception. As I understand the docs is out of date in some places. Thanks!

**Comment by asvetlov** [comment]
Yes, it is documentation issue.

**Comment by asvetlov** [comment]
Fixed by 4e01955
