### ISSUE TITLE
Attempt to await read from closed response should raise an exception.

### ISSUE THREAD

**Issue by Kentzo** [aio-libs/aiohttp#791]
It would make easier to detect incorrect usage of already closed responses.

**Comment by asvetlov** [comment]
Makes sense.

**Comment by toffer** [comment]
I'll start working on this one.

**Comment by toffer** [comment]
@asvetlov can explain more, but after looking at this yesterday and discussing it, it looks like raising an error when reading from a closed response would be a backwards-incompatible change.

There are four tests in [test_client_functional_oldstyle.py](https://github.com/KeepSafe/aiohttp/blob/master/tests/test_client_functional_oldstyle.py) that allow reading a closed response. One example is [test_HTTP_200_OK_METHOD](https://github.com/KeepSafe/aiohttp/blob/master/tests/test_client_functional_oldstyle.py#L43-L59), which does this:

```
content1 = self.loop.run_until_complete(r.read())
content2 = self.loop.run_until_complete(r.read())
...
self.assertEqual(content1, content2)
```

If you check the response connection after getting `content1` but before `content2`, you'll see that `r._connection is None`.

**Comment by asvetlov** [comment]
The supported behavior is:
1. `resp.read()` reads an entire response body and caches it.
2. Next `resp.read()` call returns the cached value.
3. If user prefers to work with low-level api like `resp.content.read()` that's fine unless he don't intermix  it with high level one (`.read()`, `.text()`, `.json()` calls).
4. On reaching the end of content (HTTP body) `resp.content.read()` call will return empty byte-string `b''` like `socket.read()` does.
