### ISSUE TITLE
ClientSession is leaking cookies across hostnames

### ISSUE THREAD

**Issue by panda73111** [aio-libs/aiohttp#792]
Since ClientSession does not link cookies to hostnames, all cookies are sent with every request made using the same session. This leaks cookies across hostnames. Even when using a seperate session for each hostname specific request, the session cookies are sent across HTTP 3xx redirects.

The intuitive fix would be connecting the cookies to their hostname within ClientSession. I'll try to write a patch and test cases if no one has a better idea.

**Comment by asvetlov** [comment]
Yes, the issue describes a very serious bug.
But solution is not so easy.
 I afraid: if aiohttp client should mimic cookie processing by modern browsers it should respect subdomains also and CORS. The first is relative easy but emulating `withCredentials` for CORS is a real nightmare.

**Comment by gwillem** [comment]
Thanks @panda73111 for your PR. I use aiohttp to crawl half the internet and I could not explain why my outbound traffic was 20x inbound, until I ran tcpdump ;-)

**Comment by asvetlov** [comment]
Fixed by Cookie filter #799
