### ISSUE TITLE
Client Upload/Download progress

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#800]
1. Upload progress
2. Cancellation of upload procedure

See http://aiohttp.readthedocs.org/en/latest/client.html#comment-2534219492

**Comment by fafhrd91** [comment]
cancellation should be fixed

**Comment by socketpair** [comment]
@asvetlov. link to comment is broken. Please write what did you mean.

**Comment by asvetlov** [comment]
Should be done by #2313
