### ISSUE TITLE
AttributeError: 'Application' object has no attribute 'shutdown'

### ISSUE THREAD

**Issue by realcr** [aio-libs/aiohttp#801]
I followed the code example for Graceful Shudown (http://aiohttp.readthedocs.org/en/stable/web.html#graceful-shutdown), however it seems like there is no app.shutdown. I am running Ubuntu 14.04, Python 3.4.3. Code example to reproduce the problem:

```
import asyncio
import aiohttp
from aiohttp import web

def run():
    loop = asyncio.get_event_loop()
    asyncio.set_event_loop(None)
    app = web.Application(loop=loop)
    handler = app.make_handler()
    f = loop.create_server(handler, '0.0.0.0', 8085)
    srv = loop.run_until_complete(f)
    print('serving on', srv.sockets[0].getsockname())
    try:
        loop.run_forever()
    except KeyboardInterrupt:
        pass
    finally:
        srv.close()
        loop.run_until_complete(srv.wait_closed())
        loop.run_until_complete(app.shutdown())
        loop.run_until_complete(handler.finish_connections(60.0))
        loop.run_until_complete(app.cleanup())
    loop.close()


if __name__ == '__main__':
    run()
```

This is the exception I get when I try to run this code:

```
$ python3 graceful_shutdown.py 
serving on ('0.0.0.0', 8085)
^CTraceback (most recent call last):
  File "graceful_shutdown.py", line 27, in <module>
    run()
  File "graceful_shutdown.py", line 20, in run
    loop.run_until_complete(app.shutdown())
AttributeError: 'Application' object has no attribute 'shutdown'
```

Is there a new way to perform a graceful shutdown for an Application?

My use case for this is as follows: In some of my tests when I close the test loop I get output that indicates that some tasks that probably belong to the app are still open. I tried to use the method proposed for graceful shutdown, but it seems like shutdown method is not present at the Application class.

Thank you for your help!

**Comment by realcr** [comment]
I was on version 0.20. I just Upgraded to the latest version 0.21.2 and it works.
Sorry for not checking earlier. Thank you for your great work.

**Comment by asvetlov** [comment]
Thank you for high appraisal
