### ISSUE TITLE
Can't instantiate abstract class NotesView with abstract methods coll ?

### ISSUE THREAD

**Issue by binhnq94** [aio-libs/aiohttp#805]
Code:

``` python
#views.py
from aiohttp import web
import asyncio
import aiohttp_jinja2
from bson import json_util, objectid
from mongoclient import db

class View(web.View):
    coll = None

    @property
    def accepts(self):
        return self.request.headers.getall('ACCEPT', [])

    @property
    def json(self):
        return 'application/json' in self.accepts

    def response(self, document):
        if self.json:
            return web.Response(body=json_util.dumps(document, sort_keys=True,indent=4).encode())
        context = {'json': json_util.dumps(document, sort_keys=True, indent=4)}
        return aiohttp_jinja2.render_template('base.html',
                                              self.request,
                                              context)

class DetailView(View):

    @asyncio.coroutine
    def get(self):
        _id = self.request.match_info.get('id', None)
        _id = objectid.ObjectId(_id)
        document = yield from self.coll.find_one({'_id':_id})
        return self.response(document)

    @asyncio.coroutine
    def put(self):
        _id = self.request.match_info.get('id', None)
        _id = objectid.ObjectId(_id)
        text = yield from self.request.text()

        note = json_util.loads(text)
        note.pop('_id', None)
        result = yield from self.coll.update({'_id': _id}, {'$set':note})
        note = yield from self.coll.find_one({'_id': _id})
        return self.response(note)

class ListView(View):
    @asyncio.coroutine
    def get(self):
        cursor = self.coll.find()
        notes = yield from cursor.to_list(length=20)
        return self.response(notes)

    @asyncio.coroutine
    def post(self):
        text = yield from self.request.text()
        notes = json_util.loads(text)
        # return notes
        ids = yield from self.coll.insert(notes)
        if ids is not list:
            _len = 1
            ids = [ids]
        else:
            _len = len(ids)
        cursor = self.coll.find({'_id': {'$in': ids} })
        notes = yield from cursor.to_list(length=_len)

        return self.response(notes)

class NoteView(DetailView):
    coll = db.notes

class NotesView(ListView):
    coll = db.notes
```

Error:

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/web.py", line 90, in handle_request
    resp = yield from handler(request)
TypeError: Can't instantiate abstract class NotesView with abstract methods coll


```

**Comment by asvetlov** [comment]
I have wonder if you provided actual error info. At least code from your example allows to instantiate `NotesView` class.

**Comment by binhnq94** [comment]
``` python
#mongoclient.py
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient

client = AsyncIOMotorClient('localhost', 27017)
db = client.mydb
```

``` python
#service.py init()
app = web.Application(loop=loop)
app.router.add_route('*', '/notes/', views.NotesView, name='notes')
```

when i try request with 'localhost:8080/notes/', service return:

```
500 Internal Server Error
Server got itself in trouble
```

And, occur error:

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/web.py", line 90, in handle_request
    resp = yield from handler(request)
TypeError: Can't instantiate abstract class NotesView with abstract methods coll
```

**Comment by asvetlov** [comment]
Sorry, I have no enough information for reproducing your problem.

I suspect some silly mistake on your side.
Where did you declare that `coll` is abstract method?
`aiohttp.web.View` has no such name at all.

**Comment by binhnq94** [comment]
i declare 'coll' (collection term in mongo) here:

``` python
#views.py
...
class NotesView(ListView):
    coll = db.notes
```

Full example here: https://github.com/TechBK/aio-rest-test/blob/master/aio-rest-test/views.py#L102

**Comment by asvetlov** [comment]
Funny bug: motor heavy use metaprogramming for for building own classes.
It clashes with ABC api.

To avoid the clash (and for sake of better code) I suggest getting rid of global state for storing mongo DB connection.

See http://aiohttp.readthedocs.org/en/stable/faq.html#where-to-put-my-database-connection-so-handlers-can-access-it for details.

**Comment by binhnq94** [comment]
I only understand a little of you meaning.
And, i will try use global state for storing mongo DB connection.
Addition, if i declare 'coll':

``` python
class NotesView(ListView):
    @property
    def coll(self):
        return db.notes
```

Do you think this is a good way ?

**Comment by asvetlov** [comment]
It can solve your problem but I suggest something better.

At first don't use global state (module variable in your case).

Drop `mongoclient.py`.

Insert after [application creation](https://github.com/TechBK/aio-rest-test/blob/master/aio-rest-test/service.py#L62) the following lines:

```
app['mongo'] = AsyncIOMotorClient('localhost', 27017)
app['db'] = app['mongo'].mydb
```

Replace `coll = db.notes` [here](https://github.com/TechBK/aio-rest-test/blob/master/aio-rest-test/views.py#L76) with

```
@property
def coll(self):
    return self.request.app['db'].notes
```

That's it for beginning.

Also subscribing on [`on_cleanup`](http://aiohttp.readthedocs.org/en/stable/web_reference.html#aiohttp.web.Application.on_cleanup) signal would be helpful for [graceful shutdown](http://aiohttp.readthedocs.org/en/stable/web.html#aiohttp-web-graceful-shutdown).

**Comment by binhnq94** [comment]
ok, thank u :+1:

**Comment by asvetlov** [comment]
@ajdavis you may found the issue is funny.

Long story short: when motor collection is used as class variable in `abc.ABC` inherited class it raises

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/web.py", line 90, in handle_request
    resp = yield from handler(request)
TypeError: Can't instantiate abstract class NotesView with abstract methods coll
```

exception. 

Looks like too much metaprogramming in Motor. 
I know **why** you use the technique but the clash is worth to be mentioned.

**Comment by ajdavis** [comment]
I see. I haven't learned the `abc` module so I didn't anticipate this at all. I can reproduce it:

```
from abc import ABC
from motor.motor_asyncio import AsyncIOMotorClient

db = AsyncIOMotorClient().test

class C(ABC):
    db = db

# TypeError: Can't instantiate abstract class C with abstract methods db
c = C()
```

Andrew do you know whether I can do anything in Motor to fix this?

I've opened a ticket:

https://jira.mongodb.org/browse/MOTOR-104

**Comment by popravich** [comment]
Hi, @ajdavis!
It seems like trivial `__getattr__` issue: ABCMeta looks through all class attributes and tries to get `__isabstractmethod__` attr for each attribute in new class namespace and in case of motor
(and I guess pymongo as well) it receives `AgnosticCollection` named `__isabstractmethod__` )

So I would recommend filtering names that starts and/or ends with double underscore in `__getattr__` method

**Comment by ajdavis** [comment]
Right, in fact PyMongo had already fixed this a while ago:

https://jira.mongodb.org/browse/PYTHON-480

Now I've fixed it in Motor:

https://github.com/mongodb/motor/commit/ec858147f9cbb22228b8343eb2a025f81b0b9041

Thanks for reporting this and helping me fix it!

**Comment by asvetlov** [comment]
Cool!

**Comment by binhnq94** [comment]
Wow! It is amazing!
