### ISSUE TITLE
Why uppercase HTTP headers?

### ISSUE THREAD

**Issue by gwillem** [aio-libs/aiohttp#813]
What is the reason aiohttp converts HTTP headers to uppercase? It is [ok according to RFC](http://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive), but virtually every other client and server uses capitalized headers.

I am mimicking regular browsers so I want to stay as close to their behaviour as possible.

**Comment by asvetlov** [comment]
It was easy to implement.
Upper-cased names are here from very beginning and 100% compatible with the standard.
Also using upper-case is faster thanks to `str.upper()`. For CamelCase new function is needed.

**Comment by gwillem** [comment]
Ok!

**Comment by DriverX** [comment]
> It was easy to implement.

How?
upstr() encapsulated into https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/protocol.py#L611 and change behavior is too hard (too many overrides).

**Comment by asvetlov** [comment]
I mean we've decided to use upper case at very beginning. Period.

HTTP2 prescribes lower-cased header names BTW.
