### ISSUE TITLE
r.json() 

### ISSUE THREAD

**Issue by ZYecho** [aio-libs/aiohttp#815]
I use python 3.5 
 `async with session.get('http://www.zhihu.com') as r: 
    json = await r.json()`
the json = await r.json() always report Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8 is there any bugs ?

**Comment by kxepal** [comment]
@ZYecho `text/html`  is definitely not right content type for JSON data. Much likely you received not JSON data, but some HTML page instead. If your server returns JSON with such content type, you should fix it in first place to return correct `application/json` instead.

**Comment by ZYecho** [comment]
r is an object of ClientResponse. I don't understand your expanlation.
Here is my problem!

I want to get the cookies after I login (www.zhihu.com) by posting the data. 

but according to documents, 

> Response cookies contain only values, that were in Set-Cookie headers of the last request in redirection chain. To gather cookies between all redirection requests you can use aiohttp.ClientSession object.

how can I get the correct cookies after I login?

**Comment by kxepal** [comment]
@ZYecho 
[Use the same session](http://aiohttp.readthedocs.org/en/stable/client.html#keep-alive-connection-pooling-and-cookie-sharing) for login request and all the following ones.

**Comment by popravich** [comment]
Hi, @ZYecho, I think I've got your problem:
`async with session.get('http://www.zhihu.com') as r: json = await r.json()`
this decodes page body as json.
If you need to access cookies after request you should do something like this:

``` python
await session.get('http://www.zhihu.com')
print(session.cookies)
```

Also see updated docs in #817
