### ISSUE TITLE
[QUESTION] How to add headers to response

### ISSUE THREAD

**Issue by Marco-Sulla** [aio-libs/aiohttp#821]
I tried to create a middleware to disable cache without success.

This is my attempt:

```
@asyncio.coroutine
def disableCacheMiddleware(app, handler):
    """
    @author Marco Sulla (marcosullaroma@gmail.com)
    @date Mar 10, 2016
    """

    @asyncio.coroutine
    def middleware_handler(req):
        response = yield from handler(req)
        past = arrow.now() - timedelta(1)
        http_date = email.utils.formatdate(past.timestamp)
        response.headers["Cache-Control"] = "no-cache, must-revalidate"
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = http_date

        return response

    return middleware_handler
```

Then I registered the middleware. This seems to not work. The header of a png file of my site, for example, is:

> HTTP/1.1 200 OK
> CONTENT-TYPE: image/png
> LAST-MODIFIED: Wed, 09 Dec 2015 15:50:04 GMT
> CONTENT-LENGTH: 12555
> CONNECTION: keep-alive
> DATE: Thu, 10 Mar 2016 13:20:43 GMT
> SERVER: Python/3.4 aiohttp/0.20.1

I also tried to use the `add_header`, but I get this error: 

> AttributeError: 'Response' object has no attribute 'add_header'

aiohttp version: 0.20.1, but I also tested it with the latest, 0.21.2

**Comment by asvetlov** [comment]
Perhaps you are trying to modify headers of resource handled by static route.
Middleware cannot do it because response headers and body are already sent when the middleware gets control.

For early setting response headers please use [signals](http://aiohttp.readthedocs.org/en/stable/web.html#signals)

**Comment by Marco-Sulla** [comment]
Thank you, it works. My ignorance, I already read signals, but when I read "streams" I do not applied it to static files, but only to websockets, while, well... all response are streams, and files cannot be nothing else streams! :)
