### ISSUE TITLE
URL with #

### ISSUE THREAD

**Issue by wanggp3** [aio-libs/aiohttp#824]
test.py

```
import asyncio,aiohttp
url = 'http://www.bcbgeneration.com/shop-dresses-day#?start=0&sz=39&format=ajax'
@asyncio.coroutine
def fetch():
session = aiohttp.ClientSession()
      r = yield from session.get(url)
      body = yield from r.read()
      print(r.status)
      session.close()

def get():
      import requests
      r = requests.get(url)
      print(r.status_code)

 get()

 print('===' * 10)

 loop = asyncio.get_event_loop()
 loop.run_until_complete(fetch())
 loop.close()
```

You can see that when a '#' in the url, aiohttp fail to get the url, but the requests can.  I don't know why it , can you tell me

**Comment by rutsky** [comment]
Hash part of address string shouldn't be send on the sever by aiohttp: http://stackoverflow.com/a/3664262/391865

I'm outside of dev environment, so can't test what aiohttp does.
Is aiohttp sends it to the server? Then it's a bug.

**Comment by avamsi** [comment]
@asvetlov This behavior is undesirable, right?
Why was #846 closed?

**Comment by asvetlov** [comment]
It was an accidental mistake.
The PR was committed as 01057dc.
Thank you for raising the question up.

**Comment by remort** [comment]
I still face this issue with aiohttp version 3.4.4. During Yandex oAuth flow my server get request at 'redirect uri' from yandex. Url parameters within this url are started with `#` instead of `&`. And aiohttp's request.query represents an empty multidict object. `request.query_string` is empty.

**Comment by webknjaz** [comment]
@remort fragment part does not reach HTTP servers and is accessible only from the client.

**Comment by remort** [comment]
@webknjaz, you mean aiohttp server cuts fragment part off the url ?

But, you're right, I used wrong oAuth `implicit` flow which is intended to be used with JS-apps. Since I use authorization code flow within my server app, I got my customers access code and so on...

But cutting off fragment part from url at the server side is a big question.
Thank you!

**Comment by webknjaz** [comment]
@remort server doesn't even receive that. Because according to the standard, browsers doesn't send the fragment part at all (it's illegal from the HTTP perspective).

**Comment by remort** [comment]
@webknjaz, ok, thank you for clarification. My fault then.
