### ISSUE TITLE
Misleading "Running on..." message

### ISSUE THREAD

**Issue by ygravrand** [aio-libs/aiohttp#832]
## Long story short

The console message output by `web:run_app` is misleading when one binds on `0.0.0.0` (the default): it says `127.0.0.1`, so one can think it's listening on local interface only.
I can provide a simple PR modifying the `aiohttp/web.py:312` line.
Also, maybe it would be good practise to make the default `127.0.0.1`?
## Expected behaviour

======== Running on http://0.0.0.0:8000/ ========
(Press CTRL+C to quit)
## Actual behaviour

======== Running on http://127.0.0.1:8000/ ========
(Press CTRL+C to quit)
## Steps to reproduce

Simply call `web.run_app` as in the examples

**Comment by asvetlov** [comment]
Fixed by a1f39a9
Thanks
