### ISSUE TITLE
Add option to manually send out large files

### ISSUE THREAD

**Issue by SteffenDE** [aio-libs/aiohttp#839]
I'm working on a project where I need aiohttp to send out large files (and I do not want to use an extra server). For static files there is the add_static method, but what if somebody wants to send out a large file manually from a request handler using os.sendfile (if available)?

I've written some scripts demonstrating what I achieved to do:
https://gist.github.com/SteffenDE/f1d19190cdaecb93e4a6

This works, but I wondered if there was a way to add something like this to aiohttp, e.g. as web.FileResponse?

**Comment by asvetlov** [comment]
aiohttp doesn't support it yet.
See also #773

**Comment by amirouche** [comment]
any update on this?

**Comment by asvetlov** [comment]
Fixed by #901
