### ISSUE TITLE
CTRL+C to stop doesn't work in python -m aiohttp.web 

### ISSUE THREAD

**Issue by mr-rodgers** [aio-libs/aiohttp#841]
## Long story short

After launching a server with ``python -m aiohttp.web` on my machine, the `CTRL+C` key sequence doesn't stop the server as expected. Instead, the server keeps running and I have to manually kill the process.
## Steps to reproduce

I launch with this command:

```
> python -m aiohttp.web glotpod.api:make_app
======== Running on http://localhost:8080/ ========
(Press CTRL+C to quit)
```

And here's the application that I'm running:

``` python
# SNIPPED-IMPORTS
from aiohttp import web
from glotpod.api.rpc import RPCHandler

class Application(web.Application):
    def __init__(self):
        super().__init__()

        # Expose the config dict
        self.config = Config()

        # Setup the executor
        if 'executor' in self.config:
            if 'threads' in self.config['executor']:
                self['executor'] = ThreadPoolExecutor(
                    self.config['executor']['threads'])
            else:
                self['executor'] = ProcessPoolExecutor(
                    self.config['executor']['processes'])
        else:
            self['executor'] = None


def make_app(_):
    return Application()
```
## Your environment

Windows 10 64-bit
32-bit Python
aiohttp 0.22.0a0 (from master branch)

**Comment by popravich** [comment]
I believe its a problem with `executor`s -- you should manually `shutdown` them on application finish.
See [gracefull shutdown section](http://aiohttp.readthedocs.org/en/stable/web.html#aiohttp-web-graceful-shutdown) in docs.
I think `on_cleanup` signal is the one you need to stop executors.

**Comment by mr-rodgers** [comment]
Hey @popravich, I removed all of my own code entirely and I still experience the same problem. The script now looks like this:

``` python
from aiohttp import web

def make_app(_):
    return web.Application()
```

**Comment by asvetlov** [comment]
Do you use proactor event loop on Windows?
Maybe it's related to https://github.com/python/asyncio/issues/191

**Comment by mr-rodgers** [comment]
That's entirely possible. I don't set the loop explicitly so maybe it gets used by default.
