### ISSUE TITLE
Outdated cookie example in docs

### ISSUE THREAD

**Issue by xinghanchuanqizibenguanliyou** [aio-libs/aiohttp#848]

**Comment by xinghanchuanqizibenguanliyou** [comment]
I can't use cookies. i just use the example in  [http://aiohttp.readthedocs.org/en/stable/client.html#response-cookies](http://aiohttp.readthedocs.org/en/stable/client.html#response-cookies) but fail

**Comment by popravich** [comment]
Have you tried checking cookies in ClientSession: http://aiohttp.readthedocs.org/en/stable/client_reference.html#aiohttp.ClientSession.cookies

**Comment by xinghanchuanqizibenguanliyou** [comment]
```
async def fetch():
    session = aiohttp.ClientSession()
    url = 'http://httpbin.org/cookies'
    cookies = dict(cookies_are='working')
    with aiohttp.ClientSession() as session:
        async with session.get(url, cookies=cookies) as resp:
            assert await resp.json() == {"cookies":
                                             {"cookies_are": "working"}}

if __name__=='__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(fetch())
    loop.close()
```

you can try upper code, it didn't work. raise an error of "TypeError: _request() got an unexpected keyword argument 'cookies' "..

In fact, i insert cookie in headers, this way works well. So I hope the example in document could fix this bug, coz it really costs time to a newer.

**Comment by xinghanchuanqizibenguanliyou** [comment]
`async def fetch():
    session = aiohttp.ClientSession()
    url = 'http://httpbin.org/cookies'
    cookies = dict(cookies_are='working')
    with aiohttp.ClientSession() as session:
        async with session.get(url, cookies=cookies) as resp:
            assert await resp.json() == {"cookies":
                                             {"cookies_are": "working"}}

if __name__=='__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(fetch())
    loop.close()`

**Comment by popravich** [comment]
ok, this looks like a bug in docs, we will check it.
You can try this:

``` python
async def fetch():
    session = aiohttp.ClientSession()
    session.cookies.update(cookies_are='working')
    url = 'http://httpbin.org/cookies'
    async with session:
        async with session.get(url) as resp:
            assert await resp.json() == {"cookies": {"cookies_are": "working"}}
```

**Comment by asvetlov** [comment]
I don't follow.
The [mentioned example](http://aiohttp.readthedocs.org/en/stable/client.html#response-cookies) does not pass `cookies` parameter into `session.get()` method.

**Comment by AdaJass** [comment]
@asvetlov why not try the code i gave, which from the example in doc.

**Comment by asvetlov** [comment]
Finally got which doc had a error.
Fixed in master.
