### ISSUE TITLE
Can one ClientSession be used for multiple simultaneous websocket connections?

### ISSUE THREAD

**Issue by DanLipsitt** [aio-libs/aiohttp#857]
## Long story short

I'm reusing `ClientSession`s between websocket connections and I'm getting `ERROR:asyncio:Unclosed client session`, and I don't know if it's a bug in my code or not. For now I'm just going to switch to using one session per connection. But should I expect to be able to reuse sessions in this way?
## Environment

aiohttp 0.21.5

**Comment by asvetlov** [comment]
`ClientSession` contains a socket pool inside, so it may be used with several websocket connections without problems.

`Unclosed client session` means that a session is not closed properly (`async with session` or `await session.close()` should be used).
