### ISSUE TITLE
Wrong version number on readthedocs.io

### ISSUE THREAD

**Issue by navreetaft** [aio-libs/aiohttp#859]
## Long story short

0.21.5 docs got pushed out to http://aiohttp.readthedocs.io/en/v0.24.5/
## Expected behaviour

http://aiohttp.readthedocs.io/en/v0.21.5/ should work
## Actual behaviour

http://aiohttp.readthedocs.io/en/v0.21.5/ shows 404

**Comment by asvetlov** [comment]
Fixed. Also 0.24.6 released
