### ISSUE TITLE
ClientWebSocketResponse with a json method

### ISSUE THREAD

**Issue by greut** [aio-libs/aiohttp#862]
## Long story short

I would love to have a `json()` method next to the `data` property of a `ClientWebSocketResponse`.
## Expected behaviour

That I can do `msg.json()` instead of manually `json.loads(msg.data)` just like the HTTP response.
## Actual behaviour

No `json()`
## Steps to reproduce

```
async with aiohttp.ws_connect(url) as ws:
    while True:
        msg = await ws.receive()

        if msg.tp == aiohttp.MsgType.text:
            print(json.loads(msg.data))
            print(msg.json())
        else:
            print(msg.tp, file=sys.stderr)
            break
```
## Your environment

Python 3.5, Archlinux, GNU/Linux 4.5.1 x86_64

**Comment by asvetlov** [comment]
Should msg.data be stripped?

**Comment by greut** [comment]
I don't understand the _stripped_ idea?

Maybe a better way is to deal with it like the `receive_str` and `receive_bytes`, adding a `receive_json`:

https://github.com/KeepSafe/aiohttp/compare/master...greut:862-json

**Comment by asvetlov** [comment]
I mean should `receive_json()` work like `return json.loads(await self.receive_str())` or `return json.loads(await self.receive_str().strip())`.

And what to do with empty string data?

**Comment by greut** [comment]
After some use of it, it's hard to beat `for msg in ws:` simplicity. It's probably not adding much value vs complexity.

**Comment by asvetlov** [comment]
Fixed by #897

**Comment by greut** [comment]
@asvetlov Great! Thanks mate.

**Comment by asvetlov** [comment]
Thanks to @sseg
