### ISSUE TITLE
bahaviour of params with dict and list as values 

### ISSUE THREAD

**Issue by jgelens** [aio-libs/aiohttp#864]
When sending a request as a client I expected query params to be expanded as follows:

```
In [32]: _encode_params({"aigentk": ["TEST_ONE", "TEST_TWO"]})
Out[32]: 'aigentk=TEST_ONE&aigentk=TEST_TWO'
```

However aiohttp does the following:

```
In [35]: update_path({"aigentk": ["TEST_ONE", "TEST_TWO"]})
Out[35]: aigentk=%5B%27TEST_ONE%27%2C+%27TEST_TWO%27%5D
```

So it encoded the list as an actual list.

If I a use a list of tuples it's working like I expected:

```
In [33]: update_path([("aigentk", "TEST_ONE"), ("aigentk", "TEST_TWO")])
Out[33]: aigentk=TEST_ONE&aigentk=TEST_TWO'
```

Is this a design choice or an inconsistency?

Thanks.

**Comment by popravich** [comment]
Hi @jgelens,

It is so by design.
http://aiohttp.readthedocs.io/en/stable/client.html#passing-parameters-in-urls
`MultiDict` has the same behavior also.

**Comment by jgelens** [comment]
ok thanks! I will update my code. I encountered this issue when porting an application which was using the requests library.
