### ISSUE TITLE
proxying request.scheme with nginx

### ISSUE THREAD

**Issue by imbolc** [aio-libs/aiohttp#872]
aiohttp server is working over https behind nginx and it has `proxy_set_header X-Forwarded-Proto $scheme;` setting in nginx config, but `request.scheme` anyway equals 'http'

**Comment by popravich** [comment]
You must provide `secure_proxy_ssl_header` keyword parameter in `app.make_handler`
 ([see doc1](http://aiohttp.readthedocs.io/en/stable/web_reference.html?highlight=secure_proxy_ssl_header), [doc2](http://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.Application.make_handler)):

``` python
app.make_handler(secure_proxy_ssl_header='X-Forwarded-Proto')
```

**Comment by imbolc** [comment]
Thank you, it's working:

```
app.make_handler(secure_proxy_ssl_header=('X-Forwarded-Proto', 'https'))
```

**Comment by popravich** [comment]
yeah, it must be tuple of header and expected value)
