### ISSUE TITLE
Use some components from werkzeug

### ISSUE THREAD

**Issue by sametmax** [aio-libs/aiohttp#876]
aiohttp write its own components for things like routing, multidict, requests, etc.

Those components, which are decoupled from any async workflow, exist, are rich and battle tested in the famous [werkzeug](http://werkzeug.pocoo.org). It would make sense to either:
- use directly the components from werkzeug to benefit from their feature, stability and community;
- allow to be able to swap internal components with werkzeug components to allow a better integration of aiohttp into other projects.

By working on [tygs](https://github.com/Tygs/tygs), we already doing a bit of this work in our project. Of course, it's hacky and requires some bypass because we have to bend aiohttp to do something it's not designed for. 

Besides, making some things swapable offer the potential to optionally provide optimized components later on such as [http-parser](http://magic.io/blog/uvloop-blazing-fast-python-networking/).

We are interested in working with your on the matter.

**Comment by popravich** [comment]
It does not make much sence to use werkzeug components.
They are realy decoupled from any async code but they are tighten to other werkzeug code
and werkzeug is all about wsgi.
About routing: it basically depend on werkzeug exceptions, this would lead to some compatibility layer between aiohttp.web exceptions and werkzeug ones.
As for request: aiohttp.web Request object is of async nature (see how many coroutine methods it has and how it reads request data) as opposed to werkzeug requests.

Trying to put werkzeug into aiohttp.web would result in `aiohttp.werkzeug` framework.

**Comment by sametmax** [comment]
If you don't want to integrate werzeug, the second solution still stands: making components swapable. We can work together to define clear and pluggable API so that somebody wanting to replace a piece of aiohttp can.

It's already possible, but it leads to some undesirable [hacks](https://github.com/Tygs/tygs/blob/master/src/tygs/components.py#L183).

This would have the additional benefit of allowing aiohttp to have a richer ecosystem and on the long run, help us to contribute upstream.

**Comment by popravich** [comment]
aiohttp.web provides [some](http://aiohttp.readthedocs.io/en/stable/web_abc.html) interfaces for customizing it. As far as I remember request handler factory and request handler are for internal use and may change without notification.

**Comment by sametmax** [comment]
That's what I saw, and is why I'm proposing we could work on making it something more customizable. As aiohttp is bound to become more and more included in bigger product as a defacto solution to provide asyncio http core features, it will become handy for the authors of said libs to be able to adapt it.

Now we are not asking somebody to do all the work, we are asking if you think it's interesting, and if you can see yourself working with us to build that together ?

**Comment by ludovic-gasc** [comment]
@sametmax Theoretically, I'm agree with you. But, for this practical use case, I see few chances to have more synergy with the help of werkzeug, however, I see a lot of chances to complexify aiohttp for the debugging, to add new features and reduce efficiency.

Nevertheless, thank you for your suggestion.

**Comment by fafhrd91** [comment]
@sametmax we can add some api for replacing different parts of aiohttp, but it should be useful. adding new functionality if painful, it requires a lot of effort to support it in the future.

**Comment by asvetlov** [comment]
werkzeug has no chance to be integrated with aiohttp core.
It built on another design patterns and just pursuits different targets.
