### ISSUE TITLE
Use aiohttp.client.request with a TCPConnector fails future requests after a failed DNS resolution.

### ISSUE THREAD

**Issue by m13253** [aio-libs/aiohttp#883]
## Long story short

Use `aiohttp.client.request` with a `TCPConnector` causes "Session is closed" with future requests, after a failed DNS resolution.

In other words, one failed resolution affects not only that single connection, but also the whole connector, preventing the creation of any new connections.

See the code below to reproduce it.

It was a fairly old [codebase](https://github.com/m13253/openwepro) (2014, before `ClientSession` was implemented). I think it would be better to fix the problem here, rather than switch to `ClientSession` at my side.
## Expected behaviour

First request a non-existent hostname, then a normal one.

The first request should fail, and the second should succeed.
## Actual behaviour

Both requests failed.

```
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "test.py", line 21, in main
    await fetch(connector, 'http://example.com')
  File "test.py", line 24, in fetch
    request = await aiohttp.client.request('POST', url, connector=connector)
  File "/usr/lib/python3.5/site-packages/aiohttp/client.py", line 586, in __await__
    return (yield from self._coro)
  File "/usr/lib/python3.5/site-packages/aiohttp/client.py", line 150, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
```
## Steps to reproduce

``` python
import aiohttp
import asyncio
import urllib.request

async def main():
    # Read the environment variables to decide which connector to use
    # In this example, only TCPConnector can cause the problem
    http_proxy = urllib.request.getproxies().get('http')
    if http_proxy:
        connector = aiohttp.connector.ProxyConnector(proxy=http_proxy)
    else:
        connector = aiohttp.connector.TCPConnector()

    # Fetch a non-existent hostname
    try:
        await fetch(connector, 'http://non-exist')
    except Exception:
        pass

    # Then a normal hostname
    await fetch(connector, 'http://example.com')

async def fetch(connector, url):
    request = await aiohttp.client.request('POST', url, connector=connector)
    try:
        print(await request.content.read())
    finally:
        request.close()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```
## Your environment

OS: ArchLinux
Python: 3.5.1
Downstream bug report: https://github.com/m13253/openwepro/issues/1

**Comment by m13253** [comment]
> Hi, what version of aiohttp are you using?

Version 0.21.5

**Comment by popravich** [comment]
ok, there seems to be an issue with `ClientSession`s and `Connector`s but I need to take a closer look

**Comment by fafhrd91** [comment]
is this still a bug

**Comment by popravich** [comment]
Yes, it is,
ClientSession closes Connector on exception and then reusing same connector with new session is
impossible.

**Comment by fafhrd91** [comment]
I see, this is ownership problem.

**Comment by fafhrd91** [comment]
I fixed this problem. question is, should we support passing ownership into session.

**Comment by fafhrd91** [comment]
@asvetlov

**Comment by asvetlov** [comment]
What do you mean by "passing ownership"?
`ClientSession` should be exclusive owner of own connector.
If connector passed explicitly into `ClientSession.__init__` the session grabs ownership.

**Comment by fafhrd91** [comment]
ok, then we need to add documentation. and close this issue with won't-fix

**Comment by fafhrd91** [comment]
and let's kill `aiohttp.request()` as well

**Comment by asvetlov** [comment]
Ok with dropping `aiohttp.request()` (along with `get()`, `post()` and others).
Not sure what should we document.

BTW, module imports from issue's example is a perfect illustration for #1659 motivation

**Comment by fafhrd91** [comment]
we should document that if connector is passed to session, it is not available anymore

**Comment by fafhrd91** [comment]
reverted

**Comment by slorg1** [comment]
@fafhrd91 @asvetlov I am sorry for coming so late to the game. I started `aiohttp` on a new project and I am running into this issue.

My use case is as follows, I am looking to use a shared `TCPConnector` using `limit_per_host` to  throttle my program (so I am a nice client :-) ). This seemed to do exactly what I was looking for. What I would like is to honour that limit globally (across the program), not just for a set of grouped requests.

Unfortunately, the `ClientSession` closes the connection automatically effectively not allowing me to use the limit.

Would you have any recommendations on how to achieve this?

To the earlier point, there is an argument to be made that `ClientSession` should use the `TCPConnector` and not own it. The connector manages how to connect in general the session should have a much shorter live cycle. I am sure that being new to this, I do not know the ins and outs of the logic here. Could you help me understand?

Thank you in advance for your help!

**Comment by asvetlov** [comment]
Does `ClientSession(connector=connector, connector_owner=False)` satisfy your needs?
https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession

**Comment by slorg1** [comment]
@asvetlov yes! Thank you, I missed it in the documentation. I love your lib 👍

**Comment by asvetlov** [comment]
:)
