### ISSUE TITLE
Proxy rotation in one session

### ISSUE THREAD

**Issue by drjackild** [aio-libs/aiohttp#886]
Hey! I want to ask, is there any plans, or may be currently aiohttp have method to set proxy on per-request basis, or any other chances to rotate proxy in one session? Currently, I creating new session to make requests with different proxies.  

Thank you in advance!

**Comment by asvetlov** [comment]
In theory we could refactor API to accept `proxy` and `proxy_auth` for every request but now I don't have strong need for it.

But the Pull Request is welcome as usual :)

**Comment by asvetlov** [comment]
See also #985

**Comment by asvetlov** [comment]
Fixed by #998

**Comment by drjackild** [comment]
@asvetlov Wow, that's amazing news, thank you! Also, thank you so much @mind1master or this great patch!
