### ISSUE TITLE
Provide an application startup signal

### ISSUE THREAD

**Issue by sseg** [aio-libs/aiohttp#887]
Suggested improvement: fire an ApplicationCreated signal providing the app instance as an argument once the app is ready to receive requests. This would allow start-up related tasks to be called while having access to the app's event loop. 

Potential use cases include setting the asyncio debug mode, or validating database resources.

Is there any interest in this?

**Comment by asvetlov** [comment]
aiohttp is ready for receiving requests after 
1. Application has created and set up
2. Handler returned by `app.make_handler()` has passed to `loop.create_server()` call

On first incoming request protocol aka `RequestHandler` instance is instantiating.
On what stage do you propose to call a signal?

P.S. 
Please take a look on https://github.com/KeepSafe/aiohttp/blob/master/demos/polls/aiohttpdemo_polls/main.py
[init](https://github.com/KeepSafe/aiohttp/blob/master/demos/polls/aiohttpdemo_polls/main.py#L18) coroutine could be considered as an code which is executed before accepting incoming requests for tasks like you are requesting.

**Comment by sseg** [comment]
For my use case it turns out I'll be able to handle it in the app setup with `app.loop`. I had intended a signal that would be fired once that could perhaps trigger smoketests running. Closing this issue as it seems like something best handled by the server (whether `web.run_app` or gunicorn).
