### ISSUE TITLE
Add shortcut for for request.app.router[path].url(**kw)

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiohttp#895]
## Long story short

Currently we need to write rather long line just to get reverse url:

``` python
async def handler(request):
    url = request.app.router['users'].url(**kw)
```

I propose to add shortcut function:

``` python

url_for(request, name, **kw)
```

**Comment by abusaidm** [comment]
I second this.

**Comment by asvetlov** [comment]
PR is welcome :)

**Comment by asvetlov** [comment]
API for routes has changed, `aiohttp-jinja2` supports `url` context function. Subapplications added.
I don't feel we need shortcut like proposed.
