### ISSUE TITLE
Coveralls authorisation to show source coverage

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp#915]
## Long story short

https://coveralls.io/builds/6464523/source?filename=aiohttp%2Ftest_utils.py

> ## SOURCE NOT AVAILABLE
> 
> The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.
## Expected behaviour

should show source
## Actual behaviour

no source code showing in coveralls

**Comment by asvetlov** [comment]
@samuelcolvin could you see coveralls report now?

**Comment by samuelcolvin** [comment]
Still can't. Coveralls is very buggy, might not be what it says it is. Have you considered moving to codecov? It's generally a way better service.

**Comment by asvetlov** [comment]
Changed coveralls to codecov.

**Comment by samuelcolvin** [comment]
Great, thanks. I can see codecov but still not coveralls, but that doesn't matter.
