### ISSUE TITLE
How to share cookies between multiple requests?

### ISSUE THREAD

**Issue by netpie** [aio-libs/aiohttp#924]
## Long story short

use the example in docs http://aiohttp.readthedocs.io/en/stable/client.html#keep-alive-connection-pooling-and-cookie-sharing

```
import aiohttp
import asyncio
async def test(session):
    async with session.post('http://httpbin.org/cookies/set/my_cookie/my_value') as resp:
        pass
    async with session.get('http://httpbin.org/cookies') as r:
        json = await r.json()
        print(json)
with aiohttp.ClientSession() as client:
    asyncio.get_event_loop().run_until_complete(test(client))

```

The output is :{'cookies': {}} 
The cookies dose not share between requests. How to ？

**Comment by netpie** [comment]
`async with session.post('http://httpbin.org/cookies/set/my_cookie/my_value') as resp`
the clientResponse got 405 "method not allowed"
session.post change to session.get ,it works!

**Comment by asvetlov** [comment]
Fixed in master, the code always uses `GET` method.
