### ISSUE TITLE
Documented cookie-setting feature results in TypeError (unexpected keyword argument)

### ISSUE THREAD

**Issue by stefanw** [aio-libs/aiohttp#926]
## Long story short

[The feature described here](http://aiohttp.readthedocs.io/en/stable/client.html#custom-cookies) that allows to set cookies directly on `session.get` does not seem to be implemented.
## Expected behaviour

``` python
import aiohttp
session = aiohttp.ClientSession()
url = 'http://httpbin.org/cookies'
cookies = dict(cookies_are='working')
session.get(url, cookies=cookies)
```

Should not raise an exception.
## Actual behaviour

An exception is raised:

``` python
TypeError: _request() got an unexpected keyword argument 'cookies'
```
## Steps to reproduce

See above.
## Your environment

Python 3.5.

**Comment by FukujiMihoko** [comment]
Happens on my end as well; Python3.5.1 on Linux.

By the way, the traceback points to https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L383

And `cookies` isn't a kwarg declared in _request, in L129.

That's one of the issues, even with the `cookies` kwarg added to _request, it won't send the cookies.

**Comment by popravich** [comment]
It seems that `stable` version did not get updated, please see `latest` docs:
http://aiohttp.readthedocs.io/en/latest/client.html

**Comment by popravich** [comment]
ok, `stable` is actually `v0.21.6` but docs are fixed in master (`latest`)
