### ISSUE TITLE
Cookie's value include char '=' will be double-quoted in ClientSession's request header.

### ISSUE THREAD

**Issue by netpie** [aio-libs/aiohttp#928]
https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client_reqrep.py#L227

```
        for name, value in cookies:
            if isinstance(value, http.cookies.Morsel):
                c[value.key] = value.value
            else:
                c[name] = value

        self.headers[hdrs.COOKIE] = c.output(header='', sep=';').strip()

```

Example:`Set-Cookie: CheckCode=42kHBlGFz/k=;` in resp will be double-quoted with value when request. The cookie in request header convert to  `Set-Cookie: CheckCode="42kHBlGFz/k=";` .

**Comment by nibrag** [comment]
related: https://github.com/KeepSafe/aiohttp/issues/802
Maybe we should make quoting optional? For example http://google.com/search does not recognize quoted cookies. I am sure many other web servers also do not understand quoted cookies.

**Comment by blueyed** [comment]
Given that https://github.com/aio-libs/aiohttp/issues/802 was closed, this should be closed probably, too.

**Comment by asvetlov** [comment]
I'm biased.
Adding an option to quote/unquote cookie values doesn't work.
It reduces usability very much: how easy tell people when to use the option and when don't?

Changing *default* to mo sophisticated is a viable solution, but we need a champion.
For example, do quote if cookie value has forbidden symbols (where to find a good list of denied chars is another question).

I have no time to work on this problem but can review a PR if somebody provides it.

**Comment by qwertypoluyt** [comment]
Is there anyway we could set custom cookies for url redirections after redirecting to another URL the set-cookies are being sent with double quotations
