### ISSUE TITLE
Route Resolving Bug

### ISSUE THREAD

**Issue by trivigy** [aio-libs/aiohttp#932]
## Long story short

Because of the way dynamic routing resolving paths, the default regex is messing with proper simply resolving.
## Expected behaviour

I would expect the two paths to be resolved properly as separate paths.
## Actual behaviour

When mapping two different paths that are similar and the second subsumes the first one, the second does not get resolved but rather the first one does.
## Steps to reproduce

Try mapping:

```
/javascript-{version}.js
```

and

```
/javascript-{version}.min.js
```

this produces (Resouce.get_info()):

```
{'formatter': '/javascript-{version}.js', 'pattern': re.compile('^\\/javascript\\-(?P<version>[^{}/]+)\\.js$')}
{'formatter': '/javascript-{version}.min.js', 'pattern': re.compile('^\\/javascript\\-(?P<version>[^{}/]+)\\.min\\.js$')}
```

Notice that the first regex subsumes the second, therefore the second will never get matched!!!
## Your environment

Not applicable.

**Comment by asvetlov** [comment]
It is not a bug.
You should keep in mind that routes are matched in the same order as they was created.
If first added route is wider than second the second will never be matched, sure.
So just reverse order of route adding.
