### ISSUE TITLE
ImportError: No modile named 'http.server' when I try to run pytests

### ISSUE THREAD

**Issue by eteamin** [aio-libs/aiohttp#936]
File "/.virtualenvs/project-name/lib/python3.5/site-packages/aiohttp/protocol.py", line 5, in <module>
    import http.server
ImportError: No module named 'http.server'

when I run the tests in console using py.test everything is fine, but running the tests in Pycharm results in this error. what is the problem?
also when I try importing in solo python file or in ipython, it imports without problem

**Comment by asvetlov** [comment]
Perhaps something is wrong with your Pycharm environment, import paths actually.
`http.server` is part of Python itself, not `aiohttp`.

**Comment by eteamin** [comment]
yeah there was something wrong with the debug configuration. thanks
