### ISSUE TITLE
pytest example in testing.rst

### ISSUE THREAD

**Issue by faassen** [aio-libs/aiohttp#939]
There are a few confusing things concerning pytest in `testing.rst`:
- it doesn't uses async/await unlike the rest of the docs but `@asyncio.coroutine` and `yield from`.
- it _says_ in the comment "`# assuming you are using pytest-asyncio`" but then it sets up its entirely independent `loop` fixture and uses `loop.run_until_complete` explicitly, instead of using `pytest.mark.asyncio` from `pytest-asyncio`

If people agree that these should be changed to async/await and `pytest.mark.asyncio` then I can create a pull request to update the example.

**Comment by faassen** [comment]
In addition the examples refer to a `_create_example_app` and in the pytest case, `create_app`, but they're not spelled out. But this would be useful for me to see for newbies like me.

**Comment by faassen** [comment]
When I try to naively update the example to use `pytest-asyncio` and change the fixtures to use `event_loop` from `pytest-asyncio` and also use `@pytest.mark.asyncio`, things fail for me with errors. So I think the docs should either explain you should _not_ use `pytest-asyncio` or also include a `pytest-asyncio` example that works.

**Comment by pfreixes** [comment]
Agree that there is a confusion with the `testing.rst` file, however the test case coded is not oriented to the `pytest-asyncio` plugin.

Talking about the issue that you mentioned it is a well known issue that is like a pain in the ass, and already reported and in the roadmap for future versions of `pytest-asyncio` [1].

There is a workaround that can be modified and use it to avoid the issue of close the loop just after the execution of the tests. The following fixture will replace the `event_loop` used by `py.test` and will avoid the side effects of the premature close of the loop faking it as a lambda parameter yielding the responsibility to close the loop to the `loop_context` delivered by aiohttp.

``` python

@pytest.yield_fixture
def loop():
    with loop_context() as loop:
        yield loop

@pytest.yield_fixture
def event_loop(loop):
    loop._close = loop.close
    loop.close = lambda: None
    yield loop
    loop.close = loop._close
```

However will be nice if the guys from asyncio keep on eye on the pytest-asyncio project and once this issue will be fixed code another test example using the pattern that uses `pytest.mark.asyncio` decorator having a less verbose code /cc @asvetlov 

[1] https://github.com/pytest-dev/pytest-asyncio/issues/29

**Comment by faassen** [comment]
Yes, the test code isn't oriented to pytest-asyncio but it mentions you assume you use it in a comment, which is very misleading, as it's the opposite of what it actually does... I went with ignoring pytest-asyncio altogether myself. The documentation should be modified so it says you _shouldn't_ be using pytest-asyncio if you use this pattern.

**Comment by asvetlov** [comment]
I think the issue can be closed.

Feel free to open another one if you discovered a new issue with testing doc.
