### ISSUE TITLE
Use "ws" or "wss" for request.scheme when using Websockets

### ISSUE THREAD

**Issue by frederikaalund** [aio-libs/aiohttp#942]
## Long story short

When aiohttp receives a Weboscket request (e.g. via "ws://localhost/stream") the `request.scheme` is set to `http` and not `ws`.
## Expected behaviour

I except `request.scheme` to contain `ws` (and `wss` for secure websocket connections).
## Actual behaviour

I see that `request.scheme` contains `http`.
## Steps to reproduce

Create a websocket route and log the request object.
## Your environment

Python 3.5.1 and aiohttp 0.21.0

**Comment by asvetlov** [comment]
The problem is: technically websocket request is started as regular HTTP request with asking for upgrade to websocket protocol.

`scheme` is `http`/`https` which is totally correct.

`web.WebSocketResponse().prepare(request)` converts a protocol to `ws`/`wss`.
It **may** switch `request.schema` but do we **really** need it?

https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web_reqrep.py#L124 is complicated now, should we add another level of complexity?

@popravich @kxepal and others, what do you think about?

**Comment by kxepal** [comment]
> The problem is: technically websocket request is started as regular HTTP request with asking for upgrade to websocket protocol.
> 
> scheme is http/https which is totally correct.

HTTP upgrade may works in the way `http -> https` - does it means that the result `request.scheme` have to be `http` in this case?

Technically, I think that `request.scheme` should represent real state of the request, specifically here, the protocol schema kind.

However, indeed it's a good question of do we really need it. The only important bit for me here is the protocol security state which is scheme agnostic.

Assume we have `request.scheme` set correctly to `ws` or `wss` - how could it be used then?

**Comment by popravich** [comment]
I don't think it really matters. `upgrade` header is the way to detect protocol switch so somehow depending on request scheme does not make much sense. I can't imagine any other use-cases where it might be useful (scheme == ws(s)).

**Comment by frederikaalund** [comment]
Thanks for reviewing! I'll just rely on the `upgrade` header then.

**Comment by popravich** [comment]
So the real problem is to detect a websocket request, ie having single handler to detect if request is HTTP request (maybe long polling or anything else) or WebSocket request and process it in appropriate way.
Maybe we should provide some helper function for this?
@asvetlov what do you think?

**Comment by asvetlov** [comment]
[can_prepare](http://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.WebSocketResponse.can_prepare) is already exists.

**Comment by popravich** [comment]
Oh, missed that
