### ISSUE TITLE
Syntactic Sugar: Would it be possible to allow `app.run()` instead of `aiohttp.web.run_app(app)`?

### ISSUE THREAD

**Issue by cclauss** [aio-libs/aiohttp#943]
## Long story short

Would it be possible to create some syntactic sugar to allow the use of the simple `app.run()` syntax instead of the boilerplate of `aiohttp.web.run_app(app)`? Clearly this is not a vital feature but I see a lot of elegance in the aiohttp project and this might add to that.

**Comment by asvetlov** [comment]
No. Application should not create a socket, it's another level of abstraction.
Utility function `run_app` is a right place for non-core helpers.
