### ISSUE TITLE
TestClient cannot take a handler

### ISSUE THREAD

**Issue by faassen** [aio-libs/aiohttp#945]
The new test_client facility takes an `app` argument and then calls `make_handler` on it. I however want to use the TestClient to test my own custom `ServerHttpProtocol` implementation, so I want to pass in my own `handler` argument on it, and not an app.

Can we agree that this would be useful? If so, let's talk about a solution:

`TestClient` doesn't appear to directly depend on `app` except for its `cleanup` and `shutdown` methods.

There are two ways to fix this that I can see:
- split off a base class for `TestClient` that contains most of the logic, and a `TestClient` subclass that integrates with app. The base class needs a few hooks so that the subclass can initiate the cleanup and shutdown.
- optionally pass in a `handler` argument into `TestClient` and let `app` be `None`, and modify it so that it doesn't try to deal with `self.app` if it's `None`.

**Comment by asvetlov** [comment]
I support the first option.
@faassen would you provide a pull request?

**Comment by asvetlov** [comment]
Looks like nobody have interest in the feature request.
`TestClient` was changed, `TestServer` was introduced.

Implementation should differ than proposed anyway.
