### ISSUE TITLE
Exception in DeflateBuffer when deflate encoding

### ISSUE THREAD

**Issue by niosega** [aio-libs/aiohttp#948]
I try to execute the following code : 
`answer = await aiohttp.request("GET", my_url)`
`cal_lines = await answer.text()`
in order to get the content of an html page.

I should have had the content of the page in cal_lines. 

Instead of that, I has an contentEncodingError which came from line 384 of file protocol.py.

My server uses content-encoding deflate.
I solve my problem by editing the class DeflateBuffer. I replace the line : 
`self.zlib = zlib.decompressobj(wbits=zlib_mode)`

by 

`self.zlib = zlib.decompressobj(wbits=0)`.

**Comment by paradoxxxzero** [comment]
The previous commit does not fix anything, both implementations exists (with zlib header and without) and apparently to be compatible you have to implement fuzzy logic (with wbits=0 for instance). Ref: http://stackoverflow.com/questions/388595/why-use-deflate-instead-of-gzip-for-text-files-served-by-apache/388633#388633
