### ISSUE TITLE
Are gunicorn instructions still current?  Is pyenv bug fixed?

### ISSUE THREAD

**Issue by cclauss** [aio-libs/aiohttp#953]
## Long story short

https://github.com/KeepSafe/aiohttp/blob/master/docs/gunicorn.rst#prepare-environment  Is based on Ubuntu 14.04.  Have things changed now that we are at Ubuntu 16.04?  It the pyenv bug on Ubuntu fixed or is the `extra manipulation` still required?  If the bug is not fixed, could we please have a link to it in order to follow its status?  Would it be right to update `pyvenv-3.4 --without-pip venv` to be `pyvenv-3.5 --without-pip venv`?

**Comment by mpaolini** [comment]
The bug has been fixed in 16.04 and you now can do:

``` bash
apt-get install python3 python3-venv
python3 -m venv virtual
source virtual/bin/activate
pip install aiohttp
```
