### ISSUE TITLE
SSL Certificate Verify Failed

### ISSUE THREAD

**Issue by bySam** [aio-libs/aiohttp#955]
## Long story short

I get a SSL certificate verification error running aiohttp despite being able to connect to the website using Firefox and cURL.
## Expected behaviour

To get my response
## Actual behaviour

See Long Story Short
## Steps to reproduce

```
`    with aiohttp.Timeout(10):
        session = aiohttp.ClientSession()
        url = 'https://api.lootbox.eu/pc/us/'
        async with session.get(url) as response:
            if response.status == 200:
                rtxt = await response.text()`
```
## Your environment

Windows 10, Python 3.5.2

**Comment by asvetlov** [comment]
I don't know what's wrong with certificates for your site but you may disable certificate checks by passing `verify_ssl=False` to connector ctor:

```
session = aiohhtp.ClientSession(connector=aiohttp.TCPConnector(verify_ssl=False))
```

**Comment by mickeyl** [comment]
FWIW, (sadly) there are a lot of embedded systems out there which contain invalid SSL certificates. Systems which we can't update / are not under our maintenance. For these cases it's good that we can disable certification validation with aiohttp.

**Comment by asvetlov** [comment]
For your pleasure

**Comment by monkeym4ster** [comment]
Navigate to
`cd /Applications/Python\ 3.7/`

Click on `Install Certificates.command`

This should solve it.

**Comment by john-shine** [comment]
Better with certifi module:

```
import ssl
import certifi

sslcontext = ssl.create_default_context(cafile=certifi.where())
with aiohttp.Timeout(10):
        ......
        async with session.get(url, ssl=sslcontext) as response:
            ......
```

**Comment by kerchner** [comment]
On my Mac with Python 3.8, running this resolved it:
```/System/Volumes/Data/Applications/Python 3.8/Install Certificates.command```

**Comment by lk-jeffpeck** [comment]
For anyone still looking for this and using conda, also check your conda version:
https://github.com/conda/conda-build/issues/2255

**Comment by Cowm00** [comment]
FYI, verify_ssl is deprecated, use ssl=False instead:
connector=aiohttp.TCPConnector(ssl=False)

**Comment by merrymercy** [comment]
@monkeym4ster It works! Thanks

**Comment by VAUsIGT** [comment]
"SSL: CERTIFICATE_VERIFY_FAILED" - the bot tries to contact the site, but sees an unknown certificate on it. You need to manually upload this certificate to trusted:
1. On the website, click on the lock (next to the url) --> find a valid certificate --> in the advanced tab, export it in the ".crt" format
2. Open "MMC" via start. Next, file --> add snap-in --> certificates --> add --> my account (then also add for local PC) --> open certificates - local PC through the root of the console --> action --> all tasks --> next and overview --> find the certificate downloaded in paragraph 1 --> done!

**Comment by hayotech** [comment]
> Navigate to `cd /Applications/Python\ 3.7/`
> 
> Click on `Install Certificates.command`
> 
> This should solve it.

This solved the problem %100. Thanks!
