### ISSUE TITLE
Discarding cookies in client session

### ISSUE THREAD

**Issue by tailhook** [aio-libs/aiohttp#957]
It looks like there is no good way to discard cookies after each request.

In previous versions of aiohttp I've just used `aiohttp.request(connector=...)` for requests, but it's deprecated now. And it looks like the only way to do connections is to make `ClientSession`.

But `ClientSession` has hardcoded cookie processing which I don't need at all. I supply `Cookie` header value to the `client_session.request()`. And it gots replaced as soon as first response returns `Set-Cookie` (I mean `CookieJar` replaces the header on the all following requests), as far as I can observe.

Currently, I can fix it by:

```
session._cookie_jar._cookies.clear()
session.request(...)
```

But it looks like too ugly and wrong.

The overall use case is similar to a simple proxy: I maintain multiple server connections and send requests to the backends using a single ClientSession (to maintain a single connection pool for all incoming connections). So `CookieJar`'s implementation handling is just wrong for it.

Any good ideas how to achieve this using aiohttp?

**Comment by asvetlov** [comment]
You can replace `session._cookie_jar._cookies.clear()` with just `session.cookies.clear()`.
As an option we may add new flag to `ClientSession` for disabling cookie processing.

**Comment by tailhook** [comment]
> You can replace session._cookie_jar._cookies.clear() with just session.cookies.clear().

Sorry missed that property.

> As an option we may add new flag to ClientSession for disabling cookie processing.

Would be nice. Because I don't want to pay for `call_later` used for cookie tracking.

Alternatively, there might be an option to replace `CookieJar` class with some no-op class. But I'm not sure if there are any other use cases for that. Maybe storing cookies on disk/across processes?

**Comment by asvetlov** [comment]
Fixed by #963

**Comment by tailhook** [comment]
Looks great. Thanks!
