### ISSUE TITLE
Enable cookie parsing for URLs which are IP-based, not DNS

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#968]
## Long story short

Working on aiohttp_session I've figured out that current behavior is not convenient for development and tests writing. 
## Expected behaviour

Don't ignore Set-Cookie from sites with IP address in URL

It's result of #799 PR

@panda73111 could you remind why you have added the filter?

As an option we can have `StrictCookieJar` class or `strict=True` CookieJar parameter with IP filter enabled but I believe default behavior should accept cookies from IP URLs.

@popravich what do you think?

**Comment by asvetlov** [comment]
@kxepal @1st1 @fafhrd91 and others, I'm asking for your opinions

**Comment by fafhrd91** [comment]
I don't have opinion on this topic. One note, would it be better to allow to use different implementation and provide cookies with filtering as an extra instead of adding more parameters?

**Comment by popravich** [comment]
same as @fafhrd91

**Comment by kxepal** [comment]
IP addresses in cookies are strongly discouraged by RFC. However, it's still allowed case per [RFC-2109](https://tools.ietf.org/html/rfc2109) and [RFC-2965](https://tools.ietf.org/html/rfc2965), but not for current one [RFC-6265](https://tools.ietf.org/html/rfc6265).

So it's ok to have that behaviour optional, but not by default.

**Comment by asvetlov** [comment]
@kxepal I don't understand you clean: are you suggest _allowing_ ip addresses by default or _forbidding_?

**Comment by kxepal** [comment]
@asvetlov forbid as newest RFC defines and common guidelines defines. Enabling this is actually fallback to old RFCs where this is allowed, but discouraged, so I think that should be default state of things today.

**Comment by asvetlov** [comment]
Gotcha. Will publish bug fix release soon.

**Comment by asvetlov** [comment]
BTW what is good name for the class?
Both `RelaxedCookieJar` and `CookieJarWithoutIPFiltering` looks ugly.

**Comment by kxepal** [comment]
`CookieJarDiscouraged`

**Comment by asvetlov** [comment]
@kxepal are you kidding me?

**Comment by kxepal** [comment]
@asvetlov Sorry, but it was too seductive to not propose (:
Actually, why not to have a special option for CookieJar which controls that behaviour?

**Comment by asvetlov** [comment]
Fixed by aiohttp 0.22.2 release.
`CookieJar(unsafe=True)` disables IP address check
