### ISSUE TITLE
Can aiohttp run as https directly without gunicorn or nginx

### ISSUE THREAD

**Issue by abusaidm** [aio-libs/aiohttp#971]
Hello,

I would like to run aiohttp on https without gunicorn or nginx.
is there a method I can pass or can I create a http.server with https setup and pass it to aiohttp

Thank you

**Comment by asvetlov** [comment]
The simplest way is calling [`aiohttp.web.run_app(..., ssl_context=context)`](http://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.run_app) where `context` should be created by [`ssl.create_default_context(...)`](https://docs.python.org/3/library/ssl.html#ssl.create_default_context) with passing appropriate certificate files.

**Comment by abusaidm** [comment]
thank you. I have read the code and found the same solution, you beat me to close it.

Thank you
