### ISSUE TITLE
Server shuts down if route is lost

### ISSUE THREAD

**Issue by Marco-Sulla** [aio-libs/aiohttp#972]
## Long story short

aiohttp server stops to work if route to the host get lost.
## Steps to reproduce
1. Start an aiohttp server
2. Reproduce an interruption of the route, for example disconnecting the physical cable
3. try to connect to server with a client
## Expected behaviour

The error should be logged, but server should stay up
## Actual behaviour

```
In base_events.py line 912, ERROR: Fatal read error on socket transport
protocol: <RequestHandler GET:/meas/data/602 connected>
transport: <_SelectorSocketTransport fd=291 read=polling write=<polling, bufsize=3643503>>
Traceback (most recent call last):
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/asyncio/selector_events.py", line 582, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 113] No route to host
```

and server shuts down.
## My environment

aiohttp: 0.20.1
OS: CentOs 6.5

**Comment by asvetlov** [comment]
The error is raised by client socket, not server one.

Perhaps your server has some connections to DB or cache and these connections are not recreated after network shutdown.

**Comment by Marco-Sulla** [comment]
In our REST api, `/meas/data/` creates a websocket and sends data to client.

We have a DB, but it's managed with plain sqlalchemy, without using asyncio, and every db connection is inside a `with` statement.

It's strange I can't have the whole stack trace, I also activated the asyncio debug mode.

**Comment by asvetlov** [comment]
Please check on Python 3.5.2+
@1st1 says it should be fixed.
