### ISSUE TITLE
Python interpreter not working in aiohttp/aiohttp directory

### ISSUE THREAD

**Issue by argaen** [aio-libs/aiohttp#974]
## Long story short

When executing the python interpreter or calling python under the `aiohttp/aiohttp` directory, it crashes with the following output:

``` python
19:17 $ python
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/Users/manuelmiranda/.virtualenvs/aiohttp/bin/../lib/python3.5/io.py", line 52, in <module>
  File "/Users/manuelmiranda/Projects/aiohttp/aiohttp/abc.py", line 1, in <module>
ImportError: No module named 'asyncio'
Abort trap: 6
```

This is because having a module named `abc.py` in that directory.
## Steps to reproduce

`cd aiohttp/aiohttp;python`
## Your environment

MAC, using virtualenv and without using it.

After checking this module it seems classes there are not exposed to public functionality. If it's fine, I could try to do a pull request with the changes (i.e renaming the file to something like `abstracts.py` or `abstract_classes.py`).

Cheers!

**Comment by popravich** [comment]
Do not name your directories `asyncio` it conflicts with `asyncio` module.

**Comment by asvetlov** [comment]
It's not asyncio/aiohttp issue but the rule how Python is working.

**Comment by argaen** [comment]
@popravich @asvetlov d'oh, sry for the mess, when I was writing `asyncio` I meant `aiohttp`. I've just updated the description =/. Guess it doesn't affect because the issue is already closed but wanted to correct it.

**Comment by popravich** [comment]
anyway it's a problem with path names -- try renaming your paths so that they dont match python lib names

**Comment by argaen** [comment]
@popravich they are not my paths, I just cloned the `aiohttp` repo, then `cd aiohttp/aiohttp` and then `python`. Then it's giving the crash.
