### ISSUE TITLE
aiohttp.ClientSession raises ServerDisconnectedError

### ISSUE THREAD

**Issue by alex-eri** [aio-libs/aiohttp#975]
## Long story short

I communicating with LTE-modem using aiohttp.ClientSession it fails to retrieve data, but other clients works and data sended from modem.

Tried changing options, versions...
## Expected behaviour

If i get this url in wget, browser, curl etc. - it returns me content.
## Actual behaviour

Simplified code and output is here 
https://gist.github.com/alex-eri/10ce6f3c7e6b47413847113606f20ead

https://yadi.sk/d/Gmemw5LatSq9F - wget trafic captured
https://yadi.sk/d/VAiwuhEItSq9H - aiohttp trafic captured
## Steps to reproduce

You need ZTE LTE modem. Run example on it.
## Your environment

Python3.5 / aiohttp (0.22.1) / Debian 8

**Comment by fafhrd91** [comment]
aiohttp does not catch `ServerDisconnectedError` anymore
