### ISSUE TITLE
Version string from multidict replaces aiohttp version.

### ISSUE THREAD

**Issue by danielnelson** [aio-libs/aiohttp#978]
It looks like the **version** string from multidict is being imported over the `aiohttp.__version__`, causing the wrong version to be shown in responses.

```
python -c 'import aiohttp; print(aiohttp.__version__)'
1.2.0
```

```
SERVER: Python/3.5 aiohttp/1.2.0
```

This is with 0.22.0 or newer

**Comment by asvetlov** [comment]
Wow!!!
Funny bug, thank you.
Fixed by `multidict==1.2.1` release.
aiohttp itself has the same issue, fixed by e2c2e71
