### ISSUE TITLE
"async with aiohttp.ClientSession:" causes Syntax Error in py3.5.1

### ISSUE THREAD

**Issue by raphaelsoul** [aio-libs/aiohttp#982]
i am following the guide of Section "Make a Request"in HTTP Client. the code is some as the document

```
async with aiohttp.ClientSession() as session:
    async with session.get('https://api.github.com/events') as resp:
        print(resp.status)
        print(await resp.text())
```

and caused SyntaxError

```
async with aiohttp.ClientSession() as session:
             ^
SyntaxError: invalid syntax
```

After that, I tried in CLI, it also caused SyntaxError like this:

```
>>> import aiohttp
>>> async with aiohttp.ClientSession():
  File "<stdin>", line 1
    async with aiohttp.ClientSession():
             ^
SyntaxError: invalid syntax
>>>
```

The version tag of my Python is `Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32`

maybe I should upgrade it to the version at least supported PEP492?

**Comment by asvetlov** [comment]
Unfortunately `async with` syntax is available inside `async def` coroutines only, the same as `yield` is available only inside `def`.

Thus you cannot use `async with` in CLI.
