### ISSUE TITLE
Concurrent call to receive() is not allowed for 2 different websockets

### ISSUE THREAD

**Issue by bayandin** [aio-libs/aiohttp#999]
## Long story short

I write a websockets proxy. For each connection to a client exists a connection to a server. I try to use `asyncio.wait` for waiting for the first message either from the client or from the server. But aiohttp raises an error `Concurrent call to receive() is not allowed`.
## Expected behaviour

Concurrent call to receive() from different websockets should be allowed.
## Actual behaviour

Exception `Concurrent call to receive() is not allowed`
## Steps to reproduce

Handler for websockets looks like this:

``` python
async def ws_handler(request):
    ws_to_client = WebSocketResponse() 
    session = aiohttp.ClientSession(loop=request.app.loop)
    ws_to_server = await session.ws_connect(url, autoclose=False, autoping=False) 
    ...
    while True:
        done, pending = await asyncio.wait(
            [ws_to_client.receive(), ws_to_server.receive()],
            return_when=asyncio.FIRST_COMPLETED
        )
    ...
```
## Your environment

Python 3.5.2, aiohttp 0.22.2

**Comment by asvetlov** [comment]
This is intended behavior.

Please create a separate task for serving client web socket in your example.

See also 8d9ee8b

**Comment by bayandin** [comment]
Thanks a lot, @asvetlov. It works!

**Comment by bayandin** [comment]
Hi @asvetlov. I still curious, how I can handle more than 2 incoming sources? More than one task will fail with the same exception as above. Are there any other tricks for this case?

**Comment by asvetlov** [comment]
Could you elaborate?
It's really hard to answer without looking on problematic code.

**Comment by larryclean** [comment]
Hi @asvetlov  
same problem, here's my code:

```
async def websocket_handler(request):
    ws = web.WebSocketResponse()
    await ws.prepare(request)
    name = ""

    while True:
        msg = await ws.receive()
        if msg.type == web.MsgType.text:
            try:
                data=eval(msg.data)
                if msg.data==1 :
                    ws.send_str(2)
                elif data.get('type')=='1':
                    name=data.get('uid')
                    if request.app['sockets'].get(name) is not None:
                        request.app['sockets'][name].close()
                    request.app['sockets'][name] = ws
                    for ws in request.app['sockets'].values():
                        ws.send_str(json.dumps({'type':1,'online':online},ensure_ascii=False,default=utils.json_default))
            except Exception as e:
                print(e.args)
        elif msg.tp == web.MsgType.close:
            print('websocket connection closed')
            break
        elif msg.tp == web.MsgType.error:
            print('ws connection closed with exception %s' % ws.exception())
            break
        else:
            break

    del request.app['sockets'][name]
    for ws in request.app['sockets'].values():
        ws.send_str(json.dumps({'action': 'disconnect',
                                'name': name}))
    return ws
```

**Comment by larryclean** [comment]
![image](https://cloud.githubusercontent.com/assets/18585750/18823885/885384ca-83f0-11e6-88ab-5a8a9097d08e.png)

**Comment by asvetlov** [comment]
You cannot call `request.app['sockets'][name].close()` from foreign task.
But your traceback points on a different problem: web request should be followed by exactly one response. I believe the rule is obvious.
